### ISSUE TITLE
[doxygen] No doxygen is provided for wrapping objects

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1015]
Only match when searching for `wrap` in [doxygen](http://myosin.sourceforge.net/1011/) is `wrapObjectSet`.

**Comment by chrisdembia** [comment]
I think Sam Hamner hid the Wrap* classes from doxygen.

**Comment by tkuchida** [comment]
I think it could be helpful to unhide these doxygen pages—and also to provide sample code for adding wrapping objects to `PhysicalOffsetFrame`s in particular, as the "obvious" approaches (to me, at least) don't seem to be working.

**Comment by chrisdembia** [comment]
+1.

**Comment by aseth1** [comment]
>I think Sam Hamner hid the Wrap* classes from doxygen

On my behest. They were/are minimally/spottily  documented and I did not want encourage their direct use via the API. We also didn't think we would update the to the extent we have been doing (had Ian and Andreas working on new wrapping at the time).

Documenting them will cause us to argue for fixing the interface, which will not be possible for 4.0.

**Comment by chrisdembia** [comment]
Oh.. I think we may have discussed this fairly recently when deciding if we should wrap these classes for MATLAB.

**Comment by jimmyDunne** [comment]
We should not count on wrapping ever being updated to Ian/Andreas' method.

**Comment by tkuchida** [comment]
This might not be as much of an issue as I originally thought, as @aymanhab's #1005 makes the "obvious" approach work.
