### ISSUE TITLE
Methods removed from GeometryPath and PathPoints that were used by GUI

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1016]
Some of these may have trivial replacement but for now just documenting the missing functions
PathPoint.getPath()
ConditionalPathPoint.getRange()
PathPoint.makePathPointOfType()
MovingPathPoint.getXFunction(), getYFunction(), getZFunction()
MovingPathPoint.getXCoordinateName(), getYCoordinateName(), getZCoordinateName()
ConditionalPathPoint.getCoordinateName()

**Comment by aymanhab** [comment]
getRange replaced with get_range() and get{X,Y,Z}Function replaced with get_{x,y,z}_location()

**Comment by aymanhab** [comment]
Remaining methods missing, please rview the list and suggest alternatives @aseth1 Thanks.

**Comment by aseth1** [comment]
`PathPoint.getPath()`: points were no longer using back pointer to their path so it was removed. For access to the owning GeometryPath from PathPoint you can use `PathPoint.getParent()`.

`PathPoint.makePathPointOfType()` made PathPoint a factory and its factory method seemed incorrect. There was also no use case for it that I could see. 

`MovingPathPoint.get#Function()` - > `get_#_location()`

 `MovingPathPoint.get#CoordinateName()` -> `get#Coordinate.getName()`

`ConditionalPathPoint.getCoordinateName()`-> `getCoordinate().getName()`

**Comment by jenhicks** [comment]
It looks like this PathPoint.makePathPointOfType() is the remaining gap. @aymanhab are you still missing a means to do this? If so, can you provide more details about the use case?

**Comment by aymanhab** [comment]
Muscle editor as of v. 3.3 has an Attachments tab that allows users to add path points to a GeometryPath these PathPoints could be either fixed (PathPoint, viaPoint aka ConditionalPathPoint or moving aka MovingPathPoint) the methods to create all these have been removed. We could just "new" an object of the right type and somehow add it but it's unknown how safe is it to add a "Component" to a live model, how that affects the state backing it up or how the wiring/connection would work.

**Comment by aseth1** [comment]
Now that PathPoints are Components using the factory would have had the same issues (if any). I suggest going ahead and creating the new PathPoint of the desired concrete type and simply adding it to the list. Property editing already has the effect of forcing an initSystem() (which performs finalizeFromProperties()->connect()->addToSystem() ...) so I don't forsee adding Components in the GUI as a problem if it is a property.

**Comment by aymanhab** [comment]
Thanks @aseth1 Will test and report back
