### ISSUE TITLE
Path of ground body is serialized differently than path of other bodies

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1018]
The following code creates a Body and attaches it to Ground with a FreeJoint:

``` cpp
using SimTK::Vec3;

auto myModel = OpenSim::Model();
myModel.setName("myModel");
auto myBody = new OpenSim::Body("myBody", 1., Vec3(0), SimTK::Inertia::brick(Vec3(1.)));
auto myJoint = new OpenSim::FreeJoint("myJoint", myModel.getGround(), *myBody);
myModel.addBody(myBody);
myModel.addJoint(myJoint);
```

When serialized, the xml looks like this:

``` xml
...
<FreeJoint name="myJoint">
    <!--List of connectors (structural dependencies) that this component has.-->
    <connectors>
        <Connector_PhysicalFrame_ name="parent_frame">
            <!--Name of the component this Connector should be connected to.-->
            <connectee_name>../myModel/ground</connectee_name>
        </Connector_PhysicalFrame_>
        <Connector_PhysicalFrame_ name="child_frame">
            <!--Name of the component this Connector should be connected to.-->
            <connectee_name>myBody</connectee_name>
        </Connector_PhysicalFrame_>
    </connectors>
...
```

I believe the connectee_name of parent_frame is intended to be "ground", not "../myModel/ground". (The connectee_name is just "ground" in [the hopper model file used during the hackathon](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/ExampleHopperDevice/BouncingLeg.osim#L318).)

**Comment by chrisdembia** [comment]
@carmichaelong investigated this and we think we understand what is happening. First, if you call `initSystem()`, then the paths are fixed (`../ground` and `../myBody`).

The issue is that the connectee_names are determined before `Joint` is part of Model. Inside Joint's constructor, it connects up both bodies to its connectors, at which Joint thinks it's the root component. We could detect when this would be an issue by ensuring the connectee and the component with the connector both have the same root component. Or perhaps the connectee_names are not stored in the property until one calls initSystem().

**Comment by carmichaelong** [comment]
> Or perhaps the connectee_names are not stored in the property until one calls initSystem().

Is there any reason someone would want to make a model but then not call initSystem()?

Would it be possible to check and repopulate connectee_names at each of the lines `myModel.addBody(myBody);` and `myModel.addJoint(myJoint);`? Seems like whenever you add something to the model, the topology can change and should be updated each time when it could change.

**Comment by chrisdembia** [comment]
Oh like as soon as you learn there is a new root, update everything accordingly?

**Comment by chrisdembia** [comment]
Is there any reason someone would want to make a model but then not call initSystem()?

Yeah I think so. I should be able to build a model and write it to file without calling initSystem.

**Comment by carmichaelong** [comment]
> I should be able to build a model and write it to file without calling initSystem.

So it sounds like we can't just wait until initSystem().

> Oh like as soon as you learn there is a new root, update everything accordingly?

Sounds about right. When does a component learn that it has a new root?

**Comment by aseth1** [comment]
`connect()` is what stores the connection names in `<connectee_name>` property and it needs to be called anytime the topology changes and is called by `initSystem`. You do not have to call `initSystem()` to see what connectee names are stored just `connect()`.
