### ISSUE TITLE
Adapters.h should be #included in osimCommon.h

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1033]
It's currently necessary to include
```cpp
#include <OpenSim/Common/Adapters.h>
```
(in addition to OpenSim.h) if you want to use `CSVFileAdapter`.

**Comment by chrisdembia** [comment]
@carmichaelong, interested?

**Comment by carmichaelong** [comment]
Sure I'll take a look at it.

**Comment by tkuchida** [comment]
Fixed by #1035
