### ISSUE TITLE
TableReporter does not write meaningful column labels

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1034]
Currently, an output like this
```cpp
reporter->updInput("inputs").connect(myJoint->getCoordinateSet()[0].getOutput("value"));
```
produces a column labeled "value" in the resulting table. Better would be to use either the full path name or the annotation provided to `connect()` (if one is provided).

**Comment by chrisdembia** [comment]
Relevant line: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Reporter.h#L175

from:
```
label = chan.getOutput().getName();
```

to:
```
label = chan.getPathName();
```

**Comment by tkuchida** [comment]
Also affects the `ConsoleReporter` and the hopper example (e.g., when displaying hopper height [slider joint displacement] and knee angle, the headings are `time | value | value`). Perhaps a good default would be `ComponentName/Output`.

**Comment by chrisdembia** [comment]
That would be better at least.

**Comment by tkuchida** [comment]
The annotation passed to `connect()` is not currently respected. For example:
```cpp
reporter->updInput("inputs").connect(
    elbow->getCoordinateSet()[0].getOutput("value"), "elbow_angle");
```
still displays the default "value" label.

**Comment by chrisdembia** [comment]
You have to ask for the annotation specifically; `input.getAnnotation()`.

**Comment by tkuchida** [comment]
> You have to ask for the annotation specifically; `input.getAnnotation()` for single-value and `input.getAnnotation(int)` for list input.

That's what I tried first (in `Reporter::extendConnect()`) but I wasn't sure whether `Component::connect()` was doing something unexpected with the annotation. Still working on it :hourglass_flowing_sand:
