### ISSUE TITLE
Iterating through ComponentList in MATLAB (and java) could be improved

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1036]
Right now, the only way to iterate through a ComponentList in MATLAB is the following:

```
it = list.begin();
while ~it.equals(it.end())
     it.getName();
     it.next();
end
```

There is a MATLAB File Exchange package that enables a `for-each` loop in MATLAB, but its license doesn't seem very friendly. This package would allow:

```
for item = each(list)
    ...
end
```
http://www.mathworks.com/matlabcentral/fileexchange/48729-for-each

**Comment by chrisdembia** [comment]
Here's how we could do it in Java (but wouldn't help much for MATLAB): http://stackoverflow.com/questions/9465856/no-iterator-for-java-when-using-swig-with-cs-stdmap

**Comment by jenhicks** [comment]
I'm going to close this issue because it duplicates #643 and is referenced in that issue so we don't lose discussion.
