### ISSUE TITLE
Warning C4800 on Visual Studio

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1040]
Compiler reports `warning C4800: 'const OpenSim::Component *': forcing value to bool 'true' or 'false' (performance warning)` [due to coercion of pointer into bool](https://msdn.microsoft.com/en-us/library/b6801kcy.aspx) in [Component::hasComponent()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L456). Perhaps do the conversion manually:
```cpp
bool hasComponent(const std::string& pathname) const {
    const auto* comp = this->template traversePathToComponent<Component>(pathname);
    return comp != 0; //instead of "return comp;"
}
```
or include a #pragma at the top of Component.h:
```cpp
#ifdef WIN32
#pragma warning( disable : 4800 ) //forcing value to bool
#endif
```
@chrisdembia

**Comment by chrisdembia** [comment]
Thanks for reporting.
