### ISSUE TITLE
Path parsing bug in Component::traversePathToComponent()

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1049]
Suppose [traversePathToComponent()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L1806) is called with `path = "/abc/def"`. Then [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L1810) sets `back` to 4 and [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L1815) sets `compName` to `"/def"`. The comparison [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L1842) will never result in a match because of the leading slash in `compName`.

@aseth1: This bug might explain why `findComponent()` is being triggered even when `getComponent()` is provided with a full path name.

**Comment by chrisdembia** [comment]
@carmichaelong are you interested in this?

**Comment by tkuchida** [comment]
Test cases should be added to the `testComponentPathNames()` method in testComponentInterface.cpp to exercise `Component::traversePathToComponent()`.

**Comment by carmichaelong** [comment]
Looks like @tkuchida assigned himself this? Tom, let me know if you need extra eyes/help on parts or all of it.

**Comment by chrisdembia** [comment]
It seems like @aseth1 may have started to address this: https://github.com/opensim-org/opensim-core/pull/1057/files#diff-a8c6cc5aa99c4c61fcc4d4b0a45a4813L1848

**Comment by tkuchida** [comment]
> It seems like @aseth1 may have started to address this

Oh, interesting. Thanks for letting me know; I didn't notice it was changed.

**Comment by chrisdembia** [comment]
It's not merged yet.

**Comment by tkuchida** [comment]
> It's not merged yet.

#1057 has been merged and it resolves the issue.
