### ISSUE TITLE
TODOs to complete Cleanup of add Geometry and attachment (in #1038)

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1058]
#1038 was merged with these issues remaining
1. Enable test case for visualization of Input driven Geometry and one attached to a floating Frame. @chrisdembia started this [here](https://github.com/opensim-org/opensim-core/tree/cleanup_add_geometry_test_floating_frame) 
   1. Use OPENSIM_THROW_FRMOBJ macro
   2. Make error messages use "connected" to a Frame instead of "attached" since attached has added meaning that the Frame the Geometry is connected to also owns it and is contained in `<attached_geometry>` which may not be the case
   3. remove spurious debugging output (calc or find Acceleration)

**Comment by chrisdembia** [comment]
This branch will be helpful https://github.com/opensim-org/opensim-core/tree/cleanup_add_geometry_test_floating_frame
