### ISSUE TITLE
"Manager::setPerformAnalyses(false)" causes getting "has no associated model"

### ISSUE THREAD

**Issue by MohammadhosseinSaadatzi** [opensim-org/opensim-core#1061]
Reporting a bug:
Using "OpenSim::Manager::setPerformAnalyses(false)" causes getting "has no associated model" error message, when running "OpenSim::Manager::integrate". I have attached the entire error message, in case it makes it easier to find the reason.

Updating Model file from 30000 to latest format...
Loaded model BipedModel_10dof24musc.osim from file BipedModel_10dof24musc.osim

Model'BipedModel_10dof24musc.osim'::findComponent()  Found '/BipedModel_10dof24musc.osim/hip_r/hip_flexion_r' as a match for:
Component 'hip_flexion_r' of type Coordinate, but it is not on specified path.

Model'BipedModel_10dof24musc.osim'::findComponent()  Found '/BipedModel_10dof24musc.osim/knee_r/knee_angle_r' as a match for:
Component 'knee_angle_r' of type Coordinate, but it is not on specified path.

ModelComponentSet_Controller_::getModel() - has no associated Model (nullptr)
Press any key to continue . . .

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
