### ISSUE TITLE
Introduce classes for managing paths of Components, Outputs, Channels, etc.

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1069]
Paths are currently strings that are passed around and parsed throughout the Component API, which is error prone. It might be better to introduce classes for managing paths, annotations on Inputs, etc.

**Comment by chrisdembia** [comment]
related: #596.

**Comment by tkuchida** [comment]
Also: perhaps use a different delimiter between Component path and Output name; a path to a Component is currently indistinguishable from a path to an Output.
