### ISSUE TITLE
TODO from hopper example

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1073]
The "Hopper Device" project used to run without making any changes, but now crashes before the simulation starts. Also, each step should execute successfully when `if (false)` is changed to `if (true)` (though won't necessarily do anything interesting at first).

**Comment by chrisdembia** [comment]
Successfully reproduced. "patellaFrame" does not have a mobilized body index.

**Comment by tkuchida** [comment]
Interesting… it works as long as the `ConsoleReporter` has been added.

**Comment by chrisdembia** [comment]
Occurs in `simulate()`, in `PathActuator::computeForce()`

**Comment by tkuchida** [comment]
> Occurs in `simulate()`, in `PathActuator::computeForce()`

Sounds like it might be related to #1064. @aseth1: any ideas?

**Comment by chrisdembia** [comment]
@tkuchida when you tested #1064 against the hopper device example, you tested it against `_answers.*`?

**Comment by tkuchida** [comment]
> @tkuchida when you tested #1064 against the hopper device example, you tested it against `_answers.*`?

Yes, IIRC. Sorry, it's difficult for me to imagine an issue like this could occur. Why does adding a `ConsoleReporter` affect whether forces are computed correctly?

**Comment by tkuchida** [comment]
It works if I replace `addConsoleReporterToHopper(hopper);` with `hopper.initSystem();` (i.e., calling `initSystem()` twice).

**Comment by chrisdembia** [comment]
I don't know why this is, but adding the ConsoleReporter causes a reordering of the components (when traversing with the ComponentList()). I don't know if this is the issue though.

**Comment by tkuchida** [comment]
Ok, thanks for investigating @chrisdembia. I'll include a workaround for now.

**Comment by chrisdembia** [comment]
Had a lengthy discussion about this with @aseth1. He may try a fix, but IMO we should not rely on it for tomorrow.

**Comment by chrisdembia** [comment]
The issue is that `addToSystem()` is invoked on `patellaFrame` before it is invoked on the Joints. The fix for now is to make sure `addToSystem()` is invoked on Joints before it is invoked on anything else.

**Comment by chrisdembia** [comment]
@tkuchida my opinion is that at this point, you could push right to master if you are only editing the hopper device. The tests don't test the hopper device.

**Comment by tkuchida** [comment]
Ok, thanks @chrisdembia. We could also consider elevating the hopper to a test case, since it seems that's how it's being used now.

**Comment by chrisdembia** [comment]
I agree in general, but do you mean for tomorrow?

**Comment by tkuchida** [comment]
> but do you mean for tomorrow?

Definitely not.

**Comment by tkuchida** [comment]
> The fix for now is to make sure `addToSystem()` is invoked on Joints before it is invoked on anything else.

How do I do that? I moved the `addBody()` lines below the `addJoint()` lines and get the same behavior.

**Comment by chrisdembia** [comment]
Well, if you use `addModelComponent()` for the PhysicalOffsetFrames, this issue is likely to go away. The issue is that the `patellaFrame` has `addToSystem()` invoked on it before the Joints. Not anything about the order of addJoint and addBody calls.

**Comment by chrisdembia** [comment]
Sorry nevermind...I am a bit confused. I realize that you add the PhysicalOffsetFrame to the thigh, which does not have `addModelComponent()`. You could add those PhysicalOffsetFrames to the Model (via addModelComponent() and the issue should go away.

**Comment by tkuchida** [comment]
> You could add those PhysicalOffsetFrames to the Model (via addModelComponent() and the issue should go away.

That didn't work. I'm just going to revert to attaching the patella to the thigh and using the translation property, as before #1064.

**Comment by aseth1** [comment]
I just ran the "student" version Hopper Example on my laptop without the failure. I didn't see any changes to the hopper in the last few hours.

**Comment by tkuchida** [comment]
> I just ran the "student" version Hopper Example on my laptop without the failure. I didn't see any changes to the hopper in the last few hours.

The "student" version of the hopper example doesn't run on master without #1074. What was supposed to happen in the last few hours?

**Comment by aseth1** [comment]
I am wondering why I didn't get a failure? I was expecting to see the problem I saw on my Mac and on my desktop in the lab. I will merge your PR if it runs for you and @chrisdembia . Does CI test that the hopper example runs?

**Comment by tkuchida** [comment]
> I am wondering why I didn't get a failure?

I don't know and I don't anticipate having time to investigate tonight.

> Does CI test that the hopper example runs?

No. The hopper is supposed to be an example, not a test. Currently, all tests pass but the hopper doesn't work, so I think that means tests are missing.

**Comment by aseth1** [comment]
> No. The hopper is supposed to be an example, not a test. Currently, all tests pass but the hopper doesn't work, so I think that means tests are missing.

We generally test the examples so we don't break them. We should add this one too.

I was also getting an "access null reference" failure in debug on Windows when building the Component traversal list (inside of `showSubcomponentInfo`) and it is related to this:
```cpp
// Build the hopper.
        auto hopper = buildHopper();
```
hopper is a copy. We have a known issue that copies do not have `finalizeFromProperties(`) automatically invoked (unlike constructing from file).  If we invoke `finalizeFromProperties()` on the next line then the problem goes away

**Comment by tkuchida** [comment]
> We generally test the examples so we don't break them. We should add this one too.

That would be good, too, and would have avoided some of the early issues.

> If we invoke `finalizeFromProperties()` on the next line then the problem goes away

Ok, thanks. I'll add it.

**Comment by chrisdembia** [comment]
> We have a known issue that copies do not have finalizeFromProperties() automatically invoked (unlike constructing from file). If we invoke finalizeFromProperties() on the next line then the problem goes away

I reproduced this problem locally. Thanks for figuring out the fix.

**Comment by tkuchida** [comment]
Follow-up items:
- [ ] `WrapCylinder` attached to `PhysicalOffsetFrame` fails when no `ConsoleReporter` is added.
- [ ] Add hopper example (without visualizer) to tests and/or add test cases.
- [ ] Remove requirement to call `finalizeFromProperties()` explicitly.

**Comment by jenhicks** [comment]
@tkuchida Can I make a separate issues for each of these? Are the three items in the list of the last column all of the remaining todos?

**Comment by tkuchida** [comment]
> Can I make a separate issues for each of these?

I will open separate issues and provide additional detail and/or links to existing issues where relevant.

> Are the three items in the list of the last column all of the remaining todos?

Yes, AFAIK all other issues we encountered have been filed separately.

**Comment by jenhicks** [comment]
Thanks @tkuchida
