### ISSUE TITLE
Tool setup without a model does not give a related error message

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1099]

**Comment by tkuchida** [comment]
For which Tool was this issue reported? Some have checks, others do not:
- AnalyzeTool - checks [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/AnalyzeTool.cpp#L509)
- CMCTool - checks [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/CMCTool.cpp#L393)
- ForwardTool - checks [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/ForwardTool.cpp#L238)
- InverseDynamicsTool - [no explicit check](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseDynamicsTool.cpp#L245)
- InverseKinematicsTool - [no explicit check](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseKinematicsTool.cpp#L262)
- RRATool - checks [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/RRATool.cpp#L355)
- ScaleTool - checks [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/ScaleTool.cpp#L252)

It might be helpful if all Tools were derived from an AbstractTool class that handled loading files, etc.

**Comment by aseth1** [comment]
Thanks @tkuchida for checking these. It was the InverseDynamicsTool. I suspect the same will be true for the InverseKinematicsTool

**Comment by tkuchida** [comment]
Fixed by #1141
