### ISSUE TITLE
marking subcomponents should not cause Object to become out of date with properties

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1100]
This causes unnecessary redo of finalizeFromProperties, which can be expensive if it triggers repeated file loading. This was reported by @stavness while adding multiple Components and already added geometry repeatedly attempted to load.

**Comment by tkuchida** [comment]
May be related to #958

**Comment by stavness** [comment]
I created a PR #1120 for the proposed (untested) fix that Ajay and I worked
on at the workshop. This should probably go into a separate branch for
testing, but I didn't now how to "PR" that.

**Comment by stavness** [comment]
And yes, we saw the same behavior as #958 and tracked this down to the geometry being reloaded each time addComponent() was called -- if geometry files were missing then the errors were output many times, if the geometry files were found then the load time was slow

**Comment by tkuchida** [comment]
Fixed by #1120
