### ISSUE TITLE
Support simultaneous opensim 4.0 and 3.x python modules

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1101]
It seems that using opensim 4.0 in a virtual environment on a computer with opensim 3.3 (python) may have issues finding the correct shared libraries. Reported by @juzhang .

**Comment by juzhang** [comment]
The observations below are as described above: opensim 3.3 with python bindings installed. Opensim 4.0 built and installed, opensim 4.0 python bindings installed in a virtual env.

In the virtual env, the build-directory python bindings can be imported successfully when the python interpreter is started in its directory (e.g. $opensim_build/Bindings/Python/RelWithDebInfo). These bindings can also be moved to where needed. 

This is not the case for the install-directory bindings (e.g. opensim_install/lib/python2.7/site-packages) which cannot be successfully imported either from the site-packages directory or elsewhere.

**Comment by chrisdembia** [comment]
Thanks @jenhicks for elaborating.

**Comment by juzhang** [comment]
Similar observations on a fresh Lubuntu install, no virtual environments or previous opensim versions.

Just built Opensim 4.0 with python bindings on a Lubuntu 16.04 VM. Installing the bindings from $opensim_build/Bindings/Python/RelWithDebInfo results in successfully installed and importable python bindings.

However, installing from $opensim_install/lib/python2.7/site-packages results in ImportErrors, e.g. "ImportError: libSimTKsimbody.so.3.6: cannot open shared object file: No such file or directory".

**Comment by chrisdembia** [comment]
Thank you for reporting. Did you set your LD_LIBRARY_PATH?

**Comment by juzhang** [comment]
I think when I set LD_LIBRARY_PATH, the import error moved to the next import statement which was for libosimcommon.

**Comment by aymanhab** [comment]
Could it be that there are libraries in the build folder that are not copied to the installation folder (e.g. Simbody or lapack?)
