### ISSUE TITLE
"Array index out of bounds" error when reordering Joints in the multibody tree

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1105]
Attaching the device from the hopper example to the leg6dof9musc model crashes at initSystem(), specifically at [line 689 of Model.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Model.cpp#L689). Presumably, this "swap" code is attempting to swap one of the model's Joints with one of the Joints in the device (which is not in the model's JointSet).

**Comment by aseth1** [comment]
Has not been verified yet. Reopening.
