### ISSUE TITLE
Models loaded from file are not automatically "connected"

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1107]
The user can get references to `Joint`s without a problem, but needs to call `connect()` or `initSystem()` before calling methods like `getChildFrame()` on the `Joint`. This extra step is not intuitive since it is possible to get references to `Joint`s. Perhaps it would be better to call `connect()` automatically when a model is loaded.

**Comment by jenhicks** [comment]
For 4.0, we will address through documentation/examples.
