### ISSUE TITLE
Consider allowing getting the names of state variables in the same order as State::getY().

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1112]
This would solve many people's issues with using their own solver in MATLAB, etc.

**Comment by chrisdembia** [comment]
A related change that would help a lot would be to turn the following protected method into a public method:

```cpp
SimTK::SystemYIndex  Component::getStateVariableSystemIndex(const std::string& stateVariableName) const;
```

**Comment by jenhicks** [comment]
I think this duplicates #426. As such, can I close one of them?

**Comment by chrisdembia** [comment]
Yes; I'll close #426.

**Comment by chrisdembia** [comment]
This issue is a way to address the problem mentioned in #426. This would be nice to have soon but it's fine if it's in 4.1, etc.

**Comment by chrisdembia** [comment]
In my work with @humphreysb with the implicit interface, I've made some changes that make this easier.
