### ISSUE TITLE
Support both python2 and python3

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1113]
I thought we already had an issue for this but I guess not.

@clnsmith @juzhang

**Comment by wagglefoot** [comment]
Hey Chris!

Speaking of this very issue; when will examples appear? 

From the [documentation](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) we have this:

> We are currently in the process of developing example Python scripts for OpenSim and will share these with the community soon.

If I go into Sherlock mode, it would appear that that page was lasted edited in August last year.

Any updates?

**Comment by chrisdembia** [comment]
There are plenty of examples in the tests folder: https://github.com/opensim-org/opensim-core/tree/master/Bindings/Python/tests

One roadblock, though silly, has been figuring where examples should go in our distribution. In the repo, they should be arranged in a way that makes it easy to test them; perhaps they should be in the `tests` folder. In the installation/distribution, I suppose they could they go in `sdk/python/opensim/examples`, as is typical for python packages. We can always rearrange them later.

Would you be interested in contributing any examples? The example in the README would be a great place to start.

@moorepants any suggestions for how to make sure examples run successfully (just making sure no exceptions are thrown) as part of running the tests?

**Comment by wagglefoot** [comment]
I would be quite keen to contribute actually, as I am having to learn how to do it anyway, and in that process I might as well write something up. 

Naturally, someone more in the know, should double-check them whence they are done.

**Comment by chrisdembia** [comment]
> I would be quite keen to contribute actually

Excellent! Please take a quick look at our [contributing guidelines](https://github.com/opensim-org/opensim-core/blob/master/CONTRIBUTING.md); most of it is not relevant if you are writing python examples, so just look at the beginning.

If you are planning a larger contribution, it may be good to open an Issue in which you propose what you want to contribute. Then we can discuss and agree on it so that you don't waste your time creating something that doesn't match what we want. We should not have the discussion on this Issue, since it is specifically about python3 support.

> Naturally, someone more in the know, should double-check them whence they are done.

Of course. We review everything that users want to contribute.

**Comment by moorepants** [comment]
I typically run examples in the build process for releases, since they often take longer than unit tests. You could have the examples run through a release/build script, for example.

**Comment by wagglefoot** [comment]
> If you are planning a larger contribution, it may be good to open an Issue in which you propose what you want to contribute. Then we can discuss and agree on it so that you don't waste your time creating something that doesn't match what we want. We should not have the discussion on this Issue, since it is specifically about python3 support.

To start, I am just planning on bolting on some muscles to a skeleton, and then simulate resulting torques in Gazebo or something similar (I know you can do this in OpenSim too). I am very interested in hooking up OpenSim's muscle models, with other python packages.

**Comment by chrisdembia** [comment]
In the process of updating the confluence page on Python, I've made a branch that extends support to python3: https://github.com/opensim-org/opensim-core/tree/python3.

**Comment by chrisdembia** [comment]
I'll let the rest of the team decide if we should try to merge this soon or wait until after 4.0 is released.
