### ISSUE TITLE
Create "Category" for Components to allow filtering in user friendly way

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1114]
In the build up to devweek, many approaches for Filtering components have been proposed including using generated "NiceTypeName". A reasonable alternative is to have Components declare their category (or categories if it makes sense) as a String (e.g. all Constraints would return the string "Constraint", Joints return "Joint" etc.) this method would be implemented only in the base classes and as such derived classes get them through inheritance and that would allow:
- Filtering using humanly readable, less error-prone mechanisms (e.g. comp.getCategory()=="Joint")
- It's all natural cross-platform, cross-language with no wrestling with Compilers or SWIG.
- Components can be separated into "bins" in extensible way (e.g. if we add "Sensor", or "Adaptor" they get their own bins without any custom code). We can leverage that for non-Components as well so that all "Tools" can be accessed uniformly (right now we use Dynamic casting if there's a common base class)

The catch is that when you filter you only get Objects or Components which may be of little use without an associated base class but that maybe good enough in common situations, or you can SafeDowncast to a more useful base class if needed.

Your thoughts, ideas and feedback is greatly appreciated.

**Comment by tkuchida** [comment]
> A reasonable alternative is to have Components declare their category (or categories if it makes sense) as a String (e.g. all Constraints would return the string "Constraint", Joints return "Joint" etc.)

Is something like [this](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/ExampleHopperDevice/helperMethods.h#L115) insufficient? Don't all constraints inherit from Constraint; all joints, from Joint; etc.? Are there specific cases where the Components we would want to group lack a common base class?

**Comment by aymanhab** [comment]
Great question @tkuchida. 
Problems with using base class today AFAIK are:
- Class objects are not cross language creatures, which leads to many hoops to jump through if using Scripting (especially from Matlab our most common scripting environment) As of now we pre-instantiate filters but that doesn't scale or extend.
- There's no generic "binning" ability, though you can downcast to arbitrary granularity but that may not help our target users.
- In the case where there's no base class (as in Tools) or only instantiated templates, this falls apart. This works only for Components. We can make everything into Component but that would be a bit artificial.

**Comment by chrisdembia** [comment]
> Are there specific cases where the Components we would want to group lack a common base class?

I have not yet been convinced that we need an "Operator" base class for things like Delay, etc. 

I'm also thinking of the Simulink block browser: 

![image](https://cloud.githubusercontent.com/assets/846001/16599300/8d87fc62-42b6-11e6-95aa-cb8e52211058.png)

Those things on the left seem to meld with @aymanhab's notion of "categories."

**Comment by aymanhab** [comment]
@aseth1 @jimmyDunne

**Comment by aseth1** [comment]
My preference would be to not "invent" categories"and to leverage the API for getting lists of Components by type. The issue seems more one of scripting environment syntax that led us to specialize variants  `Component::getComponentList<C>()`.  This does not seem "sustainable" in the sense we have to add these lists, although I am doubtful that users will define new types that don't already fall into one or more of these lists.

To address the sustainability issue and allow the GUI to present lists of types they are interested in the Navigator, we could systematically add (via a macro perhaps) something like the following method to each Component type:

```cpp
class OSIMSIMULATION_API ThisComponent: public SomeBaseComponent {
...
typedef ComponentList<ThisComponent> ThisComponentList;

ThisComponentList getThisComponentList(const Component& root) const {
    return root.getComponentList<ThisComponent>();
}
```

This could be static or it could be called on the registered Component. In either case it is called with the model as `root`.

**Comment by tkuchida** [comment]
Also see discussion here: https://github.com/opensim-org/opensim-gui/pull/565
