### ISSUE TITLE
The "Kinematics for external loads" OPTION should be removed from the Tools/GUI 

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1117]
External loads supports transforming the point of force application expressed in the Ground frame to be re-expressed in the Body frame of the point of application, based on provided kinematics (coordinates in a motion file).

For Tools and analyses like ID and SO, this option is a complete waste of time.  The kinematics of the model does not vary from the input motion. In CMC/RRA (for which the option was envisioned to help) I have found no evidence that tracking performance is improved. In the case that tracking is failing (diverging) it occasionally delays failure by a few ms.

**Comment by jenhicks** [comment]
@aseth1 A couple questions:

1) This may affect the tests. Do you (or @jimmyDunne) know if any of the test cases use this specification?

2) We'll also have to update in doc and examples

3) If this setting is not specified, it will just be removed?

**Comment by jenhicks** [comment]
Decision is to remove the option from the GUI. Will move to the GUI repo.

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-gui #50](https://github.com/opensim-org/opensim-gui/issues/50) via [**ZenHub**](https://www.zenhub.com/)
