### ISSUE TITLE
Possible bug in Storage::getColumnIndicesForIdentifier()

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#1124]
This function intent (as I understand it) is to return the list indices of columns whose labels (or names) contain the string passed in as argument. The bug is that it does not do that:

``` c++
   int startIndex = 0;
    int size = _columnLabels.getSize();
    for(int i=startIndex;i<size;++i){
        if(_columnLabels[i].compare(0,lid, identifier)==0)
            found.append(i);
    }
```

By not incrementing `startIndex`, it is just comparing passed in string to the beginning of the every column name. I think the original intention was to have another for loop that marches through every column label character by character.

This function returns a `OpenSim::Array` which is to be empty if nothing was found. But as discovered in #1119, an empty `OpenSim::Array` does not lead to seg-fault if 0th element is accessed.

**Comment by jenhicks** [comment]
We don't think this is a bug since compare is doing a comparison of the whole string. Documentation should clarify the intent. Please let us know if we're missing something.
