### ISSUE TITLE
Move hopper example to Examples folder and add as test

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1128]
The hopper example currently resides in the Sandbox; it should be moved into the Examples folder at this point. We should at least be ensuring that the "student" and "teacher" versions continue to build, but perhaps they should also be tests. In that case, we will need to disable the visualizer (could simply add a condition [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/ExampleHopperDevice/helperMethods.h#L168)), but ideally a "student" should be able to run the example _without making any changes_ and the visualizer should appear—is this possible? Telling the "student" to toggle a flag at the top of some file would be highly undesirable for this didactic example.

**Comment by chrisdembia** [comment]
It should be easy to use an environment variable or a compile definition to cause the visualizer not to show in testing. CMake lets you set environment variables to use when running tests.

**Comment by klshrinidhi** [comment]
I think the `main()` could take arguments (which is standard) that say whether or not visualizers should show. In the absence of an argument, visualizer is shown. This will allow users to run the example separately and not provide any arguments.

**Comment by chrisdembia** [comment]
Ah +1. That's a much better idea.

**Comment by klshrinidhi** [comment]
I can do this after I am done with my current task.

**Comment by tkuchida** [comment]
Possibly related to organization of proposed Example Gallery; see #1144.
