### ISSUE TITLE
Add requirement for user to call finalizeFromProperties() explicitly in all cases

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1130]
In the hopper example, the user must call `finalizeFromProperties()` explicitly after creating a model; otherwise, an exception will be thrown downstream (and I believe the exception is likely to be unhelpful—e.g., indicating that a Component cannot be found on the specified path). Ideally, the user should not need to be concerned with how/when OpenSim organizes its internal data structures.

In addition to a formal test case, we should be able to remove the `finalizeFromProperties()` calls in [exampleHopperDevice.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/ExampleHopperDevice/exampleHopperDevice.cpp#L171) and [exampleHopperDevice_answers.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/ExampleHopperDevice/exampleHopperDevice_answers.cpp#L243).

**Comment by chrisdembia** [comment]
It is an unfortunate reality of C++ that one should not call virtual methods in constructors. Therefore, we should not be calling `finalizeFromProperties()` in constructors (since it invokes the virtual `extendFinalizeFromProperties()`). It may still be possible to internally invoke `finalizeFromProperties()` farther downstream, but still before the exception gets thrown.

**Comment by klshrinidhi** [comment]
Maybe it is good to re-think how this whole thing is laid out to eliminate this step needed by user. It is a result of previous decisions.

**Comment by tkuchida** [comment]
Other potential alternatives are to (1) call `finalizeFromProperties()` automatically whenever necessary, or (2) track down the most likely downstream calls a user would make and include a "did you remember to call finalizeFromProperties()?" reminder in the exception message. Point (2) is related to existing issues with user-facing messages (e.g., see #521 and #337).

**Comment by chrisdembia** [comment]
Related: #1010

**Comment by jenhicks** [comment]
Will update API so that loadModel doesn't call finalizeFromProperties(), but users have to call explicitly to be consistent with copy and making edits.

**Comment by tkuchida** [comment]
> Will update API so that loadModel doesn't call finalizeFromProperties(), but users have to call explicitly to be consistent with copy and making edits.

Sounds good. I suggest also catching/adding a meaningful error message if the user forgot to call `finalizeFromProperties()` to avoid cryptic exceptions thrown downstream.
