### ISSUE TITLE
VS 2015 Update 3 fatal error C1001: An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#1136]
It seems that with the update 3 of VS14 OpenSim is not able to build because of Array.h (allocation of the array in the constructor).

From the following topic:
[Error](https://connect.microsoft.com/VisualStudio/feedback/details/2869042/new-internal-compiler-error-only-in-vs2015-update-3)

It seems that there is a problem when we have a templetized class initialization:
T& array = new T[SIZE]
in combination with default parameters to the constructor. It is probable a compiler error, but I was curious if we can have a fix so others will not get the same error. I had to remove update 3.

[Forum](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=6842&p=0&start=0&view=)

**Comment by carmichaelong** [comment]
We're all still on update 2 as well, and we set our Appveyor builds to use update 2 as well in #1115. I'd suggest staying on update 2 since it looks like there will be a fix to this in the next VS 2015 update which is planned to roll out soon.

**Comment by chrisdembia** [comment]
@carmichaelong can you close this if you think we can?

**Comment by carmichaelong** [comment]
I'm planning on testing locally before closing.

**Comment by carmichaelong** [comment]
The *updated* Update 3 compiles and passes test. Our Appveyor builds will now be using this version. Should be safe to update now, and I'll close this issue now with #1167 merged.

**Comment by tkuchida** [comment]
> Should be safe to update now

Thanks for investigating! :mag_right:

**Comment by chrisdembia** [comment]
Thank you @carmichaelong.

**Comment by chrisdembia** [comment]
And thank you for reporting, @mitkof6
