### ISSUE TITLE
Building on Ubuntu 14.04 (with Python bindings) and Simbody 3.5.3 -- install issues

### ISSUE THREAD

**Issue by wagglefoot** [opensim-org/opensim-core#1138]
This issue appears when trying to install OpenSim on Ubuntu

Upon invoking `sudo make -j8`

```
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_opensim.so] Error 1
make[1]: *** [OpenSim/Wrapping/Python/CMakeFiles/_opensim.dir/all] Error 2
make: *** [all] Error 2
```

Using the instructions from here: http://simtk-confluence.stanford.edu:8080/display/OpenSim/Building+OpenSim+from+Source (perhaps they are deprecated?)

Ignoring the above and running `ctest -j8` yields

```
96% tests passed, 2 tests failed out of 52

Total Test time (real) = 467.32 sec

The following tests FAILED:
	 47 - testScale (SEGFAULT)
	 52 - testRRA (OTHER_FAULT)
Errors while running CTest
```

It seems to have something to do with this:

- [Libpython error while building YouCompleteMe](http://stackoverflow.com/questions/22990769/libpython-error-while-building-youcompleteme)
- [How to ignore local python when building python from source](http://stackoverflow.com/questions/16986952/how-to-ignore-local-python-when-building-python-from-source)

**Comment by wagglefoot** [comment]
Ok, I managed to get this to work by changing the `CMAKE` flag to

`PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so`

it's default address is to the .a (static lib) file:

`PYTHON_LIBRARY=/usr/local/lib/libpython2.7.a
`
but the linker should point to the .so (shared object) file and not the .a (static lib) file.

**Comment by chrisdembia** [comment]
Ah happy you were able to fix that. Sounds like a bug in CMake. You could try using a more recent version of CMake.

**Comment by wagglefoot** [comment]
Ok, _almost_ there; having installed the
