### ISSUE TITLE
Consistency between WrapObject and  ContactGeometry components/layout

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1139]
In trying to add a ContactMesh and a WrapCylinder to a visualization test model, I was able to connect the ContactMesh to a Body/Frame using Connector but no similar setup for WrapCylinder (or likely other WrapObject). Is that intentional? If so, why? In both cases these are geometric shapes attached to a Frame with potential transform in between. Having similar functionality users would expect similar XML layout, similar API/user interface which would be more friendly and less confusing.

**Comment by aseth1** [comment]
`WrapObjects` are still currently owned by  `PhysicalFrame` (previously Body) in its `WrapObjectSet`. All the WrapObject related methods on `PhysicalFrame` should be removed and then it would make sense to have connectors. There is a comment to this effect in PhysicalFrame.h [here](https://github.com/opensim-org/opensim-core/blob/4ccecb05096e1faa970acc5fb78e6cca33e95c26/OpenSim/Simulation/Model/PhysicalFrame.h#L60). The biggest issue would be handling the update from earlier models. Want to take a crack at it @aymanhab ?

**Comment by aymanhab** [comment]
Thanks for the explanation @aseth1 will need to see where it fits in our 4.0 objectives/timeline/priorities.
