### ISSUE TITLE
Speedup CI Testing by reducing simulation period of tests

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1140]
I believe a more effective strategy than splitting tests into smaller bits (which achieves more granularity so more cores are used effectively) is to reduce the total test times by reducing the simulation period for many test. (Not that splitting tests is bad, but it has less impact than reducing test duration and currently it is leading to code duplication).  

Here is an ongoing list:
- [ ]  `testCMCArm26`: simulates for 1s. This could be reduced to 0.25s duration, (e.g. 0.40 to 0.65) and the comparison tolerances tightened.
- [ ]  `testCMCEMGDrivenArm`: simulates for 1s. This can be reduced to 0.25s duration, (0.65 to 0.90) to target time with high "EMG".
- [ ]  `testCMCGait10dof18musc`: simulates from 0.6 to 1.1s and can be reduced to 0.25s duration, (0.75 to 1.0).

@klshrinidhi you could start working through this list.

**Comment by klshrinidhi** [comment]
:+1:
