### ISSUE TITLE
addJoint() seems to be missing from the python API (opensim.py)

### ISSUE THREAD

**Issue by wagglefoot** [opensim-org/opensim-core#1142]
I am trying to replicate the simple arm example whose elbow is actuated by a muscle. 

It would appear that `addJoint` is not available in `opensim.py`. Used here:

`    model.addJoint(shoulder);  model.addJoint(elbow);`

Further, the following equivalent python bindings appear to be missing as well:

```
   // Add a console reporter to print the muscle fiber force and elbow angle.
    ConsoleReporter* reporter = new ConsoleReporter();
    reporter->set_report_time_interval(1.0);
    reporter->updInput("inputs").connect(biceps->getOutput("fiber_force"));
    reporter->updInput("inputs").connect(
        elbow->getCoordinateSet()[0].getOutput("value"), "elbow_angle");
    model.addComponent(reporter);

    // Configure the model.
    State& state = model.initSystem();
    // Fix the shoulder at its default angle and begin with the elbow flexed.
    shoulder->upd_CoordinateSet()[0].setLocked(state, true);
    elbow->upd_CoordinateSet()[0].setValue(state, 0.5 * Pi);
    model.equilibrateMuscles(state);
```

**Comment by chrisdembia** [comment]
Cool. That member function was added after OpenSim 3.3. Are you working with OpenSim 3.3 or the master branch? If you are planning on contributing to this repo, you must be working with the master branch.

**Comment by wagglefoot** [comment]
*furiously checking version*

I am on  OpenSim 3.3 it would appear. Silly me. 

That being said, are `ConsoleReport, set_report_time_interval(), initSystem() ...` all available in the master repo?

**Comment by chrisdembia** [comment]
Sorry! You should be able to get going with master branch fairly quickly; see the instructions "for the impatient."

Yes. Except for bugs, we hope that the README is consistent with the commit it is part of.

**Comment by wagglefoot** [comment]
Ok, np, I'll report back w.r.t. Python progress!

**Comment by chrisdembia** [comment]
Do the python tests pass? That is, `ctest -R python` in the build directory. 

You might need to modify the LD_LIBRARY_PATH variable as such:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/local/wagglefoot/cloud/simtk/lib/<x86_64-linux-gnu>
```

I'm not sure about that last part; where are the `*.so` files for OpenSim?

**Comment by wagglefoot** [comment]
Hmm that's worrying, so running the test in the `opensim-core-build` dir [as created based on these instructions](https://github.com/opensim-org/opensim-core#on-ubuntu-using-unix-makefiles), the tests comes out as:

```
wagglefoot@home:~/cloud/simtk/opensim-core-build$ ctest -R python
Test project /local/wagglefoot/cloud/simtk/opensim-core-build
    Start 75: python
1/1 Test #75: python ...........................***Failed    4.70 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.71 sec

The following tests FAILED:
	 75 - python (Failed)
Errors while running CTest
```

**Comment by wagglefoot** [comment]
Indeed the `.so` files are here:

```
wagglefoot@home:~/cloud/simtk/opensim-core/lib/x86_64-linux-gnu$ ls
cmake  libosimActuators.so  libosimAnalyses.so  libosimCommon.so  libosimLepton.so  libosimSimulation.so  libosimTools.so
```

**Comment by chrisdembia** [comment]
Thanks for that info. The correct path to have on `LD_LIBRARY_PATH` is `~/cloud/simtk/opensim-core/lib/x86_64-linux-gnu`.

But don't worry about trying to make the installed python library useable until the python tests pass. Can you run `ctest -R python -V` (for verbose) and email me the result?

We should move this conversation to email; GitHub issues are for known issues.

**Comment by wagglefoot** [comment]
np

**Comment by wagglefoot** [comment]
Hey chris,

Please see attached.

Best,

Neil

**Comment by chrisdembia** [comment]
@wagglefoot, if you think this issue has been resolved, could you close it?
