### ISSUE TITLE
Comments in InverseKinematicsTool::updateFromXMLNode() disagree with code

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1148]
See [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseKinematicsTool.cpp#L523) and [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseKinematicsTool.cpp#L558). Unsure whether to update the comments or the code.

**Comment by chrisdembia** [comment]
I dug through the history and it does seem that the default accuracy used to be 1e-5. I couldn't find if the weight used to be 100.

**Comment by jenhicks** [comment]
Unless anyone has a motivating reason, I would update the comment rather than the code.

**Comment by tkuchida** [comment]
> Unless anyone has a motivating reason, I would update the comment rather than the code.

In that case, we should just delete the comment. @chrisdembia's reply ("the default accuracy used to be 1e-5") suggests that the comment is correct (not the code), so I think we should investigate and use whatever values were default when version 20201 was current.

**Comment by chrisdembia** [comment]
Unless we think there is a problem with the current values (are they causing issues for our users?), we should leave the defaults as they are now. 

I think it is very unlikely that the default accuracy got changed from 1e-5 to 1e-4 by accident. I imagine there was a reason--a reason that was not documented where one might expect, but that we should assume was valid until we come across any other evidence.

I prefer deleting the comment over editing it.

**Comment by tkuchida** [comment]
> are they causing issues for our users?

I don't know. If these values are set incorrectly, users will get (slightly) different IK results in different versions of OpenSim (assuming that values for these properties have not been specified in their setup file).

My understanding is that the `updateFromXMLNode()` converters are supposed to set up the same conditions as would have been present in old versions. If true, then we can determine what these properties should be by looking into the repo history. However, you are probably right: the values were probably changed for some other (undocumented) reason. I agree with deleting the comments.
