### ISSUE TITLE
Document available textures for visualization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1149]
As of PR#1122, we're moving to use a name to indicate texture preference. Depending on visualizer, some of these preferences  may not be supported (e.g. API visualizer supports no user defined texture and has 2 built in options for background). The GUI/Visualizer will support textures like "bone", "wood", "metal" etc. We need to document what's available in the XML format so users know what options are available to them and what are the limitations (e.g. Geometry have to have texture coordinates, and what happens if a specified texture can't be loaded etc.).

**Comment by tkuchida** [comment]
Ideally, the comment for the "texture" property in Appearance.h would tell the user how to determine what strings are supported by whatever visualizer they're using (or, at least, the OpenSim API and GUI).
