### ISSUE TITLE
Bintray does not allow updating a release from more than 180 days ago

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1153]
Last year I set up a mechanism for storing binary installations of simbody and opensim-core on bintray. This worked for about 180 days. After 180 days, bintray does not allow removing/editing a "release". The RackHD project had a similar problem and someone over there graciously explained their solution: https://github.com/RackHD/RackHD/issues/283.

Note: this is separate from the more advanced caching that @klshrinidhi set up, also using bintray.

**Comment by jenhicks** [comment]
@chrisdembia What does bintray give us over simtk for hosting binaries?

**Comment by chrisdembia** [comment]
Not risking the Stanford network (we would have to put information in the public travis.yml, etc. would allow uploading to a server on Stanford's network). We could encrypt it, but it would be nice to avoid all of this. A long time ago, I had talked with Henry and Joy about using the SimTK servers  for something like this. Henry gave me an account to use and it would have worked, but I suppose I just didn't feel comfortable with it.

This is different from storing the binaries for releases of OpenSim. This is about caching data (either intermediate or final binary files) for every commit to the master branch.

We could also use the sourceforge server that we use for hosting the doxygen for every PR.

**Comment by chrisdembia** [comment]
#1356 disables deploying to bintray (after all, it has not been working). We should eventually re-enable the bintray deployment if we can fix it.

**Comment by chrisdembia** [comment]
It has been a hope of mine for a long time that the binaries for releasing OpenSim would be automatically generated. We already do this for Windows. This would be possible for Linux and macOS if we fix this issue. I have already started replacing Bintray with myosin.sourceforge.net. I may try to finish this in time for the release.

**Comment by chrisdembia** [comment]
This was fixed by #1628 .
