### ISSUE TITLE
getComponentList<C> breaks for nested loops

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1159]
We currently cannot cycle through the Joints and concurrently cycle through each of their Coordinates using the `ComponentList`, as in:

```cpp
        for (auto& joint : hopper.getComponentList<Joint>()) {
            std::cout << "Joint:" << joint.getFullPathName() << std::endl;
            for (auto& coord : joint.getComponentList<Coordinate>()) {
                std::cout << "   coord:" << coord.getFullPathName() << std::endl;
            }
        }
```
Because the Component's `_nextComponent` pointer is reset every time the list is created. The list is recreated each time for reliability as to never allow the tree to be "stale" so the solution is not revert back to building the list once at some special time and build in smarts to detect changes.  Instead this is a strong case for removing the `_nextComponent` member in `Component`.  We should not have mixed (stuffed in as convenience) the linked link structure of the `ComponentList` with the Component itself! The Component should not partly implement nor have any effect on any data structure it is a part of. 

We should add this to `testIterators.cpp` and eliminate `Component::_nextComponent`  as a 'cache' for the ComponentList's underlying linked list. Subsequently I would like to see the need for `initComponentTreeTraversal()` to go away. The iterator should simply walk the same path used to set the `_nextComponent` pointers, which is all the init method does. @klshrinidhi can you add test case(s) to `testIterators.cpp` and try to fix this?

**Comment by klshrinidhi** [comment]
I will work on this.

**Comment by jenhicks** [comment]
@klshrinidhi Please check in with @aymanhab about the implementation before proceeding so you don't chase 👻

**Comment by jenhicks** [comment]
The immediate bug is fixed by the PR referenced above, so I am in favor of working on decoupling Component from ComponentList after 4.0. @aseth1 does that sound reasonable?

**Comment by aseth1** [comment]
> I am in favor of working on decoupling Component from ComponentList after 4.0. @aseth1 does that sound reasonable?

Yes. But I think we should be prepared for this issue to creep up again and then address it once and for all. As @aymanhab noted in the last meeting, reassigning the `_nextComponent` pointer can lead to undefined behavior. I am unsure of the circumstances that guarantee that the `_nextComponent` pointer is being preserved on repeated calls. It seems to be OK but it has not been tested extensively. The band-aid seems to be holding, for now.

**Comment by jenhicks** [comment]
Thanks for the input @aseth1 . I will defer this issue for now.

**Comment by aseth1** [comment]
Bug reported was fixed. Created #1345 to contain remaining concerns for next release.
