### ISSUE TITLE
Update "building doxygen" instructions and move to CONTRIBUTING.md

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1161]
From #1157: [the "Guide to Building Doxygen" page on Confluence](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Guide+to+Building+Doxygen) "is out of sync with the master branch. The master branch does not require latex/dvips/ghostscript; it downloads MathJax for you. Perhaps the long-term solution is the move that content right into the CONTRIBUTING.md."

**Comment by chrisdembia** [comment]
Thank you!

**Comment by tkuchida** [comment]
Some additional updates:
- We now build two versions of doxygen (into the "html_developer" and "html_user" directories).
- There is no class called "MuscleCurveFunctionFactory"; perhaps point to "Frame" instead.

**Comment by jenhicks** [comment]
I added a note to the current confluence page that the instructions apply to versions 3.x. I agree that prior to 4.0 release we should remove that page from confluence and put the appropriate info in the contributing.md.
