### ISSUE TITLE
Some contributing.md Info is also general API info

### ISSUE THREAD

**Issue by humphreysb** [opensim-org/opensim-core#1172]
@aseth1 and I had a good discussion about this:  Some of the information in contributing.md is very useful in general API usage, not just contributions to the code base.  For example understanding naming conventions: i.e. why "get" vs "calc" vs "realize" are used.  

Probably anyone using the API should really at least read through contributing.md in it's entirety.  So I am suggesting that either the convention information should be in the API Guide or possibly the Landing page on Git should reference contributing.md.  Contributing.md deserves more love than just from contributing developers; lot's of good info.

**Comment by chrisdembia** [comment]
Thanks @humphreysb. Interestingly, the content in the CONTRIBUTING.md was originally on Confluence, hidden in a developer section.

**Comment by jenhicks** [comment]
Let's update the readme.md to refer to the contributing.md and API guide in doxygen.
