### ISSUE TITLE
Relative paths in XML files: make use of Simbody's new Pathname functions, perhaps with a Pathname property.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#118]
People have reported various issues with using relative paths in XML files. The only issue I have run into is the following:
1. A setup file `setup.xml` specifies an external loads file `../extloads.xml`. This can be successfully specified with a path relative to `setup.xml`.
2. The external loads file then specifies a path to a GRF file `data/grf_data.mot` relative to the external loads file.

The issue is that `data/grf_data.mot` will be resolved relative to `setup.xml`, _not_ the external loads file. That's because, to resolve relative paths, OpenSim changes directory to the setup file (well, the directory containing the setup file) and then tries to open files.

**Comment by jimmyDunne** [comment]
Is this issue on the agenda for 3.2.1?

**Comment by sherm1** [comment]
> Is this issue on the agenda for 3.2.1?

Assuming we're going to use Simbody 3.6 with OpenSim 3.2.1 (per earlier discussion), this could use @carmichaelong 's "specified working directory" routine designed for this purpose and under discussion in PR simbody/simbody#307.

**Comment by chrisdembia** [comment]
In order to fix this issue, we have to come up with cases where we know relative paths are failing. I know of one specific case, but @jimmyDunne has mentioned other distinct cases that I haven't yet encountered.

**Comment by aymanhab** [comment]
@jimmyDunne Most other issues for 3.2.1 are surgical fixes and require no across the board  testing of the API/GUI/Scripting environments. Switching to using a Path property that we haven't even created or tried under the variety of scenarios that it needs to address seems risky to me. Also the GUI and scripting need to handle this new property type. It's a great long term project but I feel it's too much for 3.2.1.

**Comment by aymanhab** [comment]
@jimmyDunne I'd say however that I can look at the reported bug(s) related to relative paths and if a surgical fix can be made do it, otherwise document behavior and/or improve error message(s). That seems like more reasonable scope.

**Comment by chrisdembia** [comment]
I agree with @aymanhab. I am *very* excited for improved path handling in OpenSim, but even if OpenSim uses Simbody 3.6, we'd be rushed to try to get OpenSim to use it in time for the 3.2.1 release.

**Comment by jenhicks** [comment]
Create a class FilePath or Path that can generate useful strings of filenames. Knows working directory. Knows original relative path name.

**Comment by jenhicks** [comment]
@chrisdembia filed a specific bug on the SimTK bug tracker

**Comment by chrisdembia** [comment]
One place where this needs to be fixed: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Control/PrescribedController.cpp#L103

```cpp
void PrescribedController::extendConnectToModel(Model& model)
{
    Super::extendConnectToModel(model);
    if(!getProperty_controls_file().empty()){
        Storage controls(get_controls_file());

```

**Comment by chrisdembia** [comment]
OpenSim's Pathname property should also handle generic exceptions if unable to find the file.

**Comment by sherm1** [comment]
> OpenSim's Pathname property should also handle generic exceptions if unable to find the file

Wouldn't this property also be used to provide names of files to write to (which might not exist yet)? When are you thinking these exceptions would get generated?

**Comment by chrisdembia** [comment]
Hmm..not sure. Perhaps upon `Pathname.open()`?

**Comment by chrisdembia** [comment]
Nevermind, the Pathname should never itself open a file. It should be able to provide you with a valid pathname, and if it is unable to generate a valid pathname, throw an exception. `Pathname.get()`? The details are not clear to me. Good point about using Pathname for writing files..hadn't thought about that.

**Comment by chrisdembia** [comment]
This property can also be used for Appearance's texture_file.

**Comment by chrisdembia** [comment]
@carmichaelong
