### ISSUE TITLE
Add tests for Millard2012AccelerationMuscle or label "experimental"

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1185]
Millard2012AccelerationMuscle isn't being tested thoroughly (e.g., with CMC) and many changes have been made to EquilibriumMuscle that have not been propagated to AccelerationMuscle. We should either add tests or indicate in the doxygen that AccelerationMuscle is still experimental.

**Comment by jenhicks** [comment]
I think we should indicate in doxygen that AccelerationMuscle is experimental.
