### ISSUE TITLE
Component does not handle Connector, Input and Output copying upon clone()

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#119]
A component that is currently cloned will find it has not Inputs or Outputs. I don't believe the current use of a map containing unique_ptrs resolves this issue although it does fix the problem of leaking Inputs and Outputs.

**Comment by chrisdembia** [comment]
What exactly is the desired behavior upon copy of, e.g., connected inputs? If I make a copy of a model that contains connected inputs, I want the inputs to be wired up to the NEW model's outputs, not the previous one's.

**Comment by aseth1** [comment]
The connection should not be copied. The connector and its property that identifies its connectee should be copied. You should be forced to call connect() or connectToModel() on the model that copy is added to. This guarantees that the copy has no effect on the original component, its connections and the model it belongs to.
