### ISSUE TITLE
Renaming Components Functionality

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1199]
As of version 3.3, Objects that can be renamed in the GUI are Models, and Markers we need to make sure that's still functional in 4.0 (especially if using connection to get results from Markers, post rename). Longer term we should strive to keep model intact post a rename since the name is used for wiring at the moment.

**Comment by jenhicks** [comment]
@aymanhab can you verify?

**Comment by jenhicks** [comment]
Need to verify that changing the name of a marker doesn't crash the GUI and gives an informative error message.

**Comment by jenhicks** [comment]
Works for me in the latest GUI beta ... closing
