### ISSUE TITLE
C3DFileAdapter is undocumented in doxygen

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1202]
Can't find any doxygen C3DFileAdapter documentation on [myosin.sourceforge](http://myosin.sourceforge.net/) or on local builds.

**Comment by tkuchida** [comment]
Related to #1068

**Comment by chrisdembia** [comment]
Nice catch. Maybe we have to define the `WITH_BTK` preprocessor macro in the Doxyfiles.

**Comment by chrisdembia** [comment]
@jimmyDunne would you be interested in trying to fix this? I think the fix is  to edit [these lines](https://github.com/opensim-org/opensim-core/blob/master/doc/doxyfile_shared.in#L1547):

```
PREDEFINED             = FINAL_11=final OVERRIDE_11=override \
                         OpenSim_DOXYGEN_Q_PROPERTY=Q_PROPERTY \
                         WITH_BTK=1
```

**Comment by jimmyDunne** [comment]
Sure. Will edit and put in a PR.

**Comment by jimmyDunne** [comment]
#1207
