### ISSUE TITLE
Accessing C3DFileAdapter() through Java Wrap

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1203]
Accessing force and marker data through Python interface is 

`
adapter = osim.C3DFileAdapter()
tables = adapter.read(os.path.join(test_dir, 'walking2.c3d'))
markers = tables['markers']
forces = tables['forces'] `

forces = tables['forces'] Does not work through Java-Matlab. Using ('force') doesn't work either. 

How do I access the tables in Java-Matlab?

**Comment by chrisdembia** [comment]
What does `methods(tables)` or `methodsview(tables)` show?

**Comment by jimmyDunne** [comment]
![methodsview](https://cloud.githubusercontent.com/assets/5296507/17900953/3d2c44fe-6916-11e6-80d4-cb4a37456759.png)

**Comment by chrisdembia** [comment]
Yeah; looks like you have to use `tables.get('forces')`.

**Comment by jimmyDunne** [comment]
Thanks, that seemed to solve my most immediate problem.
