### ISSUE TITLE
Need an effective process for performing design reviews before code reviews

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1208]
**Problem**
PRs often include discussions about implementation details that are a direct consequence of design decisions. Changes in design and high-level goals cause frustration/confrontation regardless of if the resulting code is stronger for it or not.  The main issue is that detailed design discussions are happening too late in the dev process where too much time is already invested in a particular implementation. 
Whereas *issues* articulate the problem or feature to be addressed and can serve as requirements, they are not a great forum for collaborative review/approval of designs. It should be noted that not all code changes require designs or design reviews. 

Design reviews would also encourage input/feedback from more team (and outside) members without bogging them down in implementation details.

Design reviews could also facilitate outside contribution, especially of new capabilities.  In which case, the contributor can get help making critical design decisions, which can be the main stumbling block for getting an implementation that works or serves as the roadblock for getting their code merged.

The intent is that a design review is a fast way to get some detailed feedback, including implementation details that would impact your design, without implementing and testing it all out in order to open a PR. 

We have been using [WIP] PRs in some cases to serve as reviewing "depots" but in my view they still include too much implementation to step back and look at the approach.  A WIP also has no mechanism of confirming the design is complete/agreed upon independent of completing the implementation - it  still all gets lumped into a single merge event.

**One Idea**
 - @klshrinidhi and I discussed having design review PRs where designs could be debated and approved (merged) into a "Design repository". Designs would include brief description (refer to issues), use cases (as pseudo code) and outline of the design with its key constructs (which classes, data-structures, algorithms,...) to be changed/implemented.  Code PRs would simply refer to the design PR instead of attempting to explain the design.

We could have a separate Design repository OR have a `designs` sub-directory in every source directory like we have baked in `tests`. The designs in the repo (with commit logs and issues)  also serve to document design decisions.

@opensim-org/dev-team please chime in.

**Comment by jenhicks** [comment]
Thanks @aseth1 for the nice summary. @klshrinidhi chatted about this a little. This sounds like a good idea to me. How about a DesignDocs folder in OpenSim under the opensim-core repo (similar to Sandbox)? It seems like it might be nice to keep the design details in the same repo.

**Comment by chrisdembia** [comment]
This is similar to OSRF's `gazebo_design` repository, publically accessible here: https://bitbucket.org/osrf/gazebo_design. They use the markdown format.

They chose to use a separate repo, but I think it would be fine for us to use the same repo (at least for the first few).

**Comment by jenhicks** [comment]
Thanks for sharing the osrf link @chrisdembia. I like how they have a template markdown file and simple "how to create a project" steps.

**Comment by tkuchida** [comment]
:+1: Sounds like a great thing to try.

**Comment by aymanhab** [comment]
Sounds like a good idea. We should decide who is the target audience as that may dictate placement and lifetime.

**Comment by jenhicks** [comment]
We will call the documents DevelopmentProposals. And it will live under OpenSim. Use OSRF process. They will be markdown files. Every proposal will go in its own folder.  

Categories to add to the template include:
- Effects on Bindings
Describe how you will access the functionality from scripting. Should it be wrapped. If so, how will wrapping be handled.

- Backwards Compatibility
Will the project break backward compatibility? What code will need to be updated to ensure old models are handled?

Add to Overview: Include a description of how the change will benefit (which) users.

Add to Requirements: Include constraints and define scope of the project.

**Comment by jenhicks** [comment]
Include a readme.md, as well.

**Comment by jenhicks** [comment]
Tag PRs with "DevProp" -- add this to the readme.md

**Comment by tkuchida** [comment]
Addressed by #1211.
