### ISSUE TITLE
Offline docs do not link locally

### ISSUE THREAD

**Issue by moorepants** [opensim-org/opensim-core#122]
I was perusing the installed doxygen docs yesterday locally when I didn't have an internet connection, but some of the main links on the front page do not send you to the proper local resources. For example, the "optimizer" orange button takes you to:

https://simtk.org/api_docs/simbody/api_docs33/Simbody/html/classSimTK_1_1Optimizer.html

This ideally would direct you to the local copy of the simbody docs??

**Comment by chrisdembia** [comment]
One solution is to use CMake to configure the OpenSimDoxygenMain.h file to replace [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/OpenSimDoxygenMain.h#L135) with the variable of the `OPENSIM_SIMBODY_DOXYGEN_LOCATION` variable.
