### ISSUE TITLE
Please add getTable to TableReporter's

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1220]
The TableReporter holds tables, so my instinct would be to ask something like getTable(). It took Chris telling me about getReport() to figure out that is what gives me a table. 

Since we don't have reports, we have tables, we should be calling the method getTable()

**Comment by tkuchida** [comment]
Another potential challenge is that the method appears in the doxygen as
```cpp
const TimeSeriesTable_<ValueT>& OpenSim::TableReporter_< InputT, ValueT >::getReport( ) const
```
and has no comments.

**Comment by jimmyDunne** [comment]
The only way I can figure out how to use the tables and adapters is to use methodsview() in Matlab, or search through the github repo, hoping there is an example of use. 

I understand that Macros and templates reduce code redundancy, but it sure makes it harder to find public methods.

**Comment by jenhicks** [comment]
Change getReport() to getTable()
