### ISSUE TITLE
getNumInputs and/or getNumConnectors return incorrect value. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1224]
For a TableReporter, the methods getNumInputs() or getNumConnectors() don't give me intutive answers. I am able to connect many inputs to the Reporter but the methods return 1 and 0 respectively. 

```
>> markerReporter = TableReporterVec3()
>> markerReporter.set_report_time_interval(0.1)
>> nMarkers = model.getMarkerSet.getSize; % Where nMarkers = 12

>> for iMarker = 0 : nMarkers - 1
>>      markerReporter.updInput('inputs').connect(model.getMarkerSet.get(iMarker).getOutput('location'), char(model.getMarkerSet.get(iMarker).getName) );
>> end    
>> model.addComponent(markerReporter)
>> markerReporter.getNumInputs
ans = 
1
>> markerReporter.getNumConnectors 
ans
= 
0
```

After the simulation is complete, I can drill into the table and see that there are the correct number of columns. 

```
>> table  = markerReport.getReport()
>> table.getColumnLabels.getSize()
ans = 
12
```

**Comment by tkuchida** [comment]
This is a naming issue. There is only one Input component, but it holds a vector of ReferencePtrs to Channels ("ChannelList"). I think Input should be renamed InputContainer (or something similar) to indicate that it can hold more than a single Output.

**Comment by chrisdembia** [comment]
Thanks for explaining, @tkuchida. Better names would be good. For now, try `getInput('input').getNumConnectees()`?

**Comment by jimmyDunne** [comment]
The below line works.

```
markerReporter.getInput('inputs').getNumConnectees()
```

I feel there needs to be diagram/map of how the reporters, inputs, and tables are arranged.

**Comment by chrisdembia** [comment]
> I feel there needs to be diagram/map of how the reporters, inputs, and tables are arranged.

For sure. Where do you think it should go?

**Comment by aseth1** [comment]
Perhaps the fundamental unit should be an Input and Output instead of channels and the list type of Inputs should just be a (list) property as the container. For most Components these would fixed sized (add one Input at a time via macro but into the same list)  but for Reporters it would vary.  I have to thin more about the machinery but I think it is doable.
