### ISSUE TITLE
Matlab crashing during multiple simulation due to Reporters/TimeSeriesTable

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1225]
[double_pendulum_markers.osim.zip](https://github.com/opensim-org/opensim-core/files/448366/double_pendulum_markers.osim.zip)

Running multiple forward simulations in a loop (with reporters) continually crashes Matlab. 

If I pass the function a model object, it will not run a second time (fwd_simulation function at bottom of post). 

```
import org.opensim.modeling.*

model = Model('double_pendulum_markers.osim');
time_interval = 0.01;
default_coordinates = [0.5 0.3];

for i = 1 : 100
    [coordinatetable, markertable] = fwd_simulation(model, time_interval, default_coordinates, false)
end
```
 On the second iteration I get this error;

```
Error using fwd_simulation (line 57)
Java exception occurred:
java.lang.RuntimeException: Timestamp at row 10001 with value 0.000000 is less-than/equal to
timestamp at row 10000 with value 10.000000
	In file
        /Users/jimmy/repository/opensim-master/opensim-core/OpenSim/Common/TimeSeriesTable.h:194
	In function 'validateRow'
	at org.opensim.modeling.opensimModelSimulationJNI.Manager_integrate__SWIG_1(Native Method)
	at org.opensim.modeling.Manager.integrate(Manager.java:183)
```

I am interpreting this as there is a pesky TimesSeriesTable hanging around somewhere, even though everything should be getting wiped at the end of the function call. 

I managed to get it running more than once by passing the string name for the model and creating the Model object on the side of the function

```
import org.opensim.modeling.*

time_interval = 0.01;
default_coordinates = [0.5 0.3];

for i = 1 : 100
    [coordinatetable, markertable] = fwd_simulation('double_pendulum_markers.osim', time_interval, default_coordinates, false)
end
```

This allows me to run the function more than once (great!), but it will crash Matlab after 10 iterations without warning or sufficient error message. 

If I do not create any reporters in the function, it will run continually (tested up to 100 iterations)

Something funky is going on with Reporters and tables, so if anyone can give it a test that would be super. 

```
function [coordinatetable, markertable] = fwd_simulation(modelname, time_interval, default_coordinates, plotMarkers)

import org.opensim.modeling.*

%% add a table reporter for the coordinates
coordinateReporter = TableReporter();
coordinateReporter.set_report_time_interval(0.001)
coordinateReporter.updInput('inputs').connect(model.getCoordinateSet.get(0).getOutput('value'), 'q1' );
coordinateReporter.updInput('inputs').connect(model.getCoordinateSet.get(1).getOutput('value'), 'q2' );
model.addComponent(coordinateReporter);
% 

%% add a table reporter for the markers
nMarkers = model.getMarkerSet.getSize;
markerReporter = TableReporterVec3();
markerReporter.set_report_time_interval(time_interval);

for iMarker = 0 : nMarkers - 1
markerReporter.updInput('inputs').connect(model.getMarkerSet.get(iMarker).getOutput('location'), char(model.getMarkerSet.get(iMarker).getName) );
end    

model.addComponent(markerReporter);

%%  Configure the model.
for iCoordinate = 0 : model.getCoordinateSet.getSize - 1
        model.getCoordinateSet.get(iCoordinate).setDefaultValue(default_coordinates(iCoordinate+1))
end

% Simulate.
state = model.initSystem();
manager = Manager(model);
manager.setInitialTime(0); manager.setFinalTime(10.0);
manager.setWriteToStorage(0) 
manager.integrate(state);

%% get the coordinates
coordinatetable = coordinateReporter.getReport();

%% get the markers
markertable = markerReporter.getReport();

clear model
clear state
clear manager
clear markerReporter
clear coordinateReporter

```

**Comment by chrisdembia** [comment]
I think we need to see any error messages you get (or the MATLAB crash log) to help with your second issue.

There is a meaningful message given for the first issue: 
> Timestamp at row 10001 with value 0.000000 is less-than/equal to
timestamp at row 10000 with value 10.000000

This is because you are trying to append new simulation results (starting at time 0) into a reporter that already has results from a previous simulation, and the timestamps in TimeSeries data tables must be increasing. You can address this by calling `getReport()` and then clearing the data table.

@aseth1, should the data table in a TableReporter be cleared in `finalizeFromProperties()` or something like that?

**Comment by chrisdembia** [comment]
@aseth1 or should there be a `clearReport()` method on TableReporter?

**Comment by aymanhab** [comment]
Another possibly related question is "what is the expected life time for a reporter?"

**Comment by tkuchida** [comment]
> should the data table in a TableReporter be cleared in `finalizeFromProperties()` or something like that?

We could adopt the "clear on read" philosophy commonly seen in hardware registers; if a Reporter were used in a loop, for example, an exception would be thrown before overwriting data that was never read. I think a clear-on-read approach would produce the desired behavior in most cases.

**Comment by chrisdembia** [comment]
Ah I like that.

**Comment by aseth1** [comment]
> We could adopt the "clear on read" philosophy commonly seen in hardware registers; ...

That would mean that upon getting the report (TimeSeriesTable) the internal report would be cleared, correct? We could do that with the report being a copy instead of a reference. If you do not get the report than is it expected that you want to continue to append during subsequent simulation? That would make sense to me.

We should also clear if the System is rebuilt. Properties will not necessarily be changed but connections will be re-established (cleared and then satisfied again) so that would also be a good time to clear an existing report.

Also, re-running a simulation does not require calling `initSystem()` but just keeping track of the initial state and setting back on the Model (System) before re-running.  It is therefore possible (perhaps likely) to get the non sequential time exception when doing this (if you don't get the report after running the first time). The reporter then should perhaps catch the non sequential time stamp exception, re-throw as an "Overwriting existing Report" exception and list potential remedies to: 1. get the report (which will clear), or 2. manually clear before re-running the simulation.

**Comment by tkuchida** [comment]
> That would mean that upon getting the report (TimeSeriesTable) the internal report would be cleared, correct?

Yes. In most scenarios, I would expect users to get the TimeSeriesTable exactly once, so the "clear on read" behavior would *just work* without the user needing to think about it. The user could be inconvenienced in two ways:

1. Attempts to read the TimeSeriesTable twice – I think this scenario is unlikely to be problematic, as it seems like the user should be able to hold onto the Table and extract all necessary information without wanting to fetch it again. If the user attempts to read an empty Table, we could throw an exception like "The Table is empty: either it has not been filled, or it has been read which causes an automatic clear".

2. Attempts to overwrite the TimeSeriesTable without reading/clearing – This scenario could occur if the user is, say, running a simulation in a loop and cares only about the Table after the last iteration. In this case, an exception should be thrown indicating that the user must clear or read-and-clear the Table before writing to it again.

> If you do not get the report than is it expected that you want to continue to append during subsequent simulation?

I think an exception should be thrown before writing a non-increasing time (e.g., restarting a simulation from t=0), but time-stepping or pausing and resuming the simulation where it left off should be permitted.

> We should also clear if the System is rebuilt.

:+1:

> …and list potential remedies to: 1. get the report (which will clear), or 2. manually clear before re-running the simulation.

That sounds good. IIRC, hardware registers often don't have a separate `clear()` method (you need to perform a read-and-clear by reading into a trash variable). Having a separate `clear()` method violates the "minimal API" rule, but in this context I think it would be cleanest.

**Comment by aseth1** [comment]
@klshrinidhi if these changes are reasonable to you, would you consider making them to `TableReporter`?

**Comment by klshrinidhi** [comment]
Okay. Sounds good.

**Comment by klshrinidhi** [comment]
I just talked to Tom. Here is the summary of changes I am going to try to make:
* Add `clearReport()` or `clearTable()` to `TableReporter` to clear the rows of the underlying `TimeSeriesTable`. This will have to be called at the end of a loop when running simulation multiple times in a loop.
* `TableReporter` should catch the exception thrown by `TimeSeriesTable` when attempting to append a row that can cause time column to be *decreasing*. The `TableReporter` should throw giving a more contextual message to callers. The message can contain suggestion to use `clearReport()` if using `TableReporter` in a loop.

**Comment by tkuchida** [comment]
> `TableReporter` should catch the exception thrown by `TimeSeriesTable` when attempting to append a row that can cause time column to be *decreasing*.

Isn't the exception thrown if time is *non-increasing*? I think we decided that integrators should not be allowed to report the state before and after an instantaneous event is processed.

**Comment by klshrinidhi** [comment]
`TimeSeriesTable` is currently coded to only allow strictly increasing timestamps. The comment comes from that. I can change the behavior but will have to be another PR.

**Comment by tkuchida** [comment]
> `TimeSeriesTable` is currently coded to only allow strictly increasing timestamps.

`[allows only strictly increasing timestamps] == [disallows non-increasing timestamps]`. Your most recent comment and my understanding are in agreement.

**Comment by klshrinidhi** [comment]
Got it. I should have said *non-increasing* in my summary.

**Comment by aymanhab** [comment]
@klshrinidhi We need to touch base on this and ideally have a good working C++ example, then troubleshoot whatever issues that are due to SWIG wrapping. Do we have such an example in C++? Thanks.

**Comment by klshrinidhi** [comment]
Address by #1265.
