### ISSUE TITLE
Utilities or improved interface for passing data between OpenSim and Matlab data types

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1229]
@jimmyDunne Will upload Matlab scripts to Sandbox to show the usecases. @aymanhab will investigate if a lower-level solution is possible.

**Comment by jenhicks** [comment]
@jimmyDunne  The plan for this issue is to provide conversion scripts

**Comment by chrisdembia** [comment]
@jimmyDunne are you familiar with MATLAB's `table` objects? 
https://www.mathworks.com/help/matlab/matlab_prog/modify-units-descriptions-and-table-variable-names.html

It seems that, ideally, the conversion script would create a MATLAB table object.

I'm not sure which version of MATLAB introduced tables, though.

**Comment by chrisdembia** [comment]
I think tables were introduced in 2013b:

http://blogs.mathworks.com/loren/2013/09/10/introduction-to-the-new-matlab-data-types-in-r2013b/

**Comment by chrisdembia** [comment]
It seems like MATLAB's Table also supports metadata. One key difference is that MATLAB's tables can have a different data type for each column (I think...).

**Comment by aymanhab** [comment]
This will likely be handled by @jimmyDunne scripts that users can test/modify at least for 4.0. Longer term solutions may include: SWIG module for Matlab (has been experimental for a while), auto-generate MEX files etc. The advantage of the current scheme is that very little API changes between C++, Python and Matlab and has been working rather well overall.

**Comment by chrisdembia** [comment]
> This will likely be handled by @jimmyDunne scripts that users can test/modify at least for 4.0.

I agree. I think having a conversion script that creates a MATLAB Table object would be very nice, perhaps in addition to others that create a normal matrix, etc.

**Comment by jenhicks** [comment]
See PR #1311
