### ISSUE TITLE
Hopper example throws a !hasSystem() exception out-of-the-box

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1230]
The "Examples/Hopper Device" project should spawn a visualizer and simulate when run. The current behavior is for `Component::getSystem()` to throw a `!hasSystem()` exception on `viz.drawFrameNow(state);`:
```
Hopper Example Failed to run due to the following Exception: PathWrapPoint::getS
ystem()  has no reference to a System.
Make sure you added the Component to the Model and called Model::initSystem().
```
The expected behavior (minus the hop) is observed when `vastus->updGeometryPath().addPathWrap(*patella);` (line 164 in buildHopperModel.cpp) is commented out.

**Comment by aseth1** [comment]
Fixed by #1260
