### ISSUE TITLE
Investigate wrapping of Coordinate enum classes

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1232]
PR #1116 introduced an enum class in each concrete joint (excluding CustomJoint and WeldJoint). Coordinates are accessible via `myPlanarJoint.get_coordinates(0)` (which closely resembles the old `myPlanarJoint.getCoordinateSet()[0]`), but it might be better if the enum classes were also wrapped to allow something like `myPlanarJoint.getCoordinate(PlanarJoint_Coord_RotationZ)`. See discussion in PR #1222.

**Comment by klshrinidhi** [comment]
I looked at this briefly.

**In Python:**
The result of wrapping is:
```python
class PinJoint(Joint):
    #....... other stuff ........
    Coord_RotationZ = _simulation.PinJoint_Coord_RotationZ
    #....... other stuff ........
```
```python
class SliderJoint(Joint):
    #....... other stuff ........
    Coord_TranslationX = _simulation.SliderJoint_Coord_TranslationX
    #....... other stuff ........
```
```python
class GimbalJoint(Joint):
    #....... other stuff ........
    Coord_Rotation1X = _simulation.GimbalJoint_Coord_Rotation1X
    Coord_Rotation2Y = _simulation.GimbalJoint_Coord_Rotation2Y
    Coord_Rotation3Z = _simulation.GimbalJoint_Coord_Rotation3Z
    #....... other stuff ........
```
The enums appear as data members of the class but with an underscore as seen above. It is possible to use:
```python
pin_joint.getCoordinate(PinJoint.Coord_RotationZ)
slider_joint.getCoordinate(SliderJoint.Coord_TranslationX)
# ..... so on .......
```
**In Java:**
```java
public class PinJoint extends Joint {
 // ............. other stuff ....................
  public Coordinate getCoordinate(PinJoint.Coord idx) {
 // ............. other stuff ....................
 public final static class Coord {
    public final static PinJoint.Coord RotationZ = new PinJoint.Coord("RotationZ");
 // ............. other stuff ....................
```
```java
public class SliderJoint extends Joint {
 // ............. other stuff ....................
  public Coordinate getCoordinate(SliderJoint.Coord idx) {
 // ............. other stuff ....................
  public final static class Coord {
    public final static SliderJoint.Coord TranslationX = new SliderJoint.Coord("TranslationX");
 // ............. other stuff ....................
```
```java
public class GimbalJoint extends Joint {
 // ............. other stuff ....................
  public Coordinate getCoordinate(GimbalJoint.Coord idx) {
 // ............. other stuff ....................
  public final static class Coord {
    public final static GimbalJoint.Coord Rotation1X = new GimbalJoint.Coord("Rotation1X");
    public final static GimbalJoint.Coord Rotation2Y = new GimbalJoint.Coord("Rotation2Y");
    public final static GimbalJoint.Coord Rotation3Z = new GimbalJoint.Coord("Rotation3Z");
 // ............. other stuff ....................
```
The enums appear as static data members. It is possible to use:
```java
pin_joint.getCoordinate(PinJoint.Coord.RotationZ);
slider_joint.getCoordinate(SliderJoint.Coord.TranslationX);
// ............. so on .................
```

**Comment by tkuchida** [comment]
Thanks @klshrinidhi for investigating. If this behavior is satisfactory as it is, I can add Python/Matlab usage notes to the concrete classes (e.g., [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/BallJoint.h#L58)).

**Comment by jenhicks** [comment]
This seems reasonable to me. It will be helpful to exercise this when we write examples.

**Comment by chrisdembia** [comment]
I agree that that interface looks fine. When writing examples in doxygen for python, it might be good to show the `opensim` module:

```python
import opensim
pin_joint.getCoordinate(opensim.PinJoint.Coord_RotationZ)
slider_joint.getCoordinate(opensim.SliderJoint.Coord_TranslationX)
```

The following would also work, but is not advised:
```python
from opensim import *
pin_joint.getCoordinate(opensim.PinJoint.Coord_RotationZ)
slider_joint.getCoordinate(opensim.SliderJoint.Coord_TranslationX)
```

**Comment by chrisdembia** [comment]
I am unable to get the coordinate enums to work in MATLAB. I have tried the following, but it did not work and is also not what we'd want:
https://www.mathworks.com/matlabcentral/answers/15711-how-do-i-access-a-java-inner-class-from-matlab

It would be great if we could get this working and add a MATLAB test for this.

**Comment by tkuchida** [comment]
> It would be great if we could get this working and add a MATLAB test for this.

Investigating. Apparently @klshrinidhi's Java code (above) doesn't work in MATLAB. The ugly way still works, though:
```
myJoint.get_coordinates(0);
```

**Comment by chrisdembia** [comment]
Yes, I have managed to use the "ugly" way. At the least, we could update the doxygen description for `getCoordinate()`.

**Comment by tkuchida** [comment]
> At the least, we could update the doxygen description for `getCoordinate()`.

I'll do this for now as I think it will take me a while to figure out how to expose the enum via SWIG.

**Comment by chrisdembia** [comment]
One option is to create methods on the respective joints that return individual enum values, like `FreeJoint::getTranslationX()`.

**Comment by tkuchida** [comment]
> One option is to create methods on the respective joints that return individual enum values, like `FreeJoint::getTranslationX()`.

That would also be fine. I'll wait for others to chime in before proceeding further.
:bell: @aseth1 @klshrinidhi

**Comment by klshrinidhi** [comment]
I think the problem here is that when Matlab loads the jar file, it is ignoring the inner class (`BallJoint::Coord`).
@aymanhab's suggestion was that `Coord` class may be pulled out of `Joint`. That will require one such class for every joint. 
@chrisdembia's suggestion requires us to add lot of methods. 
I cannot think of any good solution without more investigation.
Maybe it is better to document this in Doxygen for now unless @aseth1 has ideas.

**Comment by aseth1** [comment]
@chrisdembia Adding the methods that return the enum values seems to oppose the value of having the enums, which enables us to use the same coordinate access machinery for all joints (just different indices/enums defined by the Joint). If we have accessors for the enum that you then use to access the coordinate, then why not have separate accessors for each coordinate of a joint to begin with?

I also don't have a good sense for why the enum is accessible via Python and not Java/MATLAB. 

My preference would be to document the mapping between enum and index number so MATLAB users can access coordinates the "ugly way" and eventually figure out how to expose the enums in MATLAB.

**Comment by chrisdembia** [comment]
> why not have separate accessors for each coordinate of a joint to begin with?

This is indeed my preferred solution.

> I also don't have a good sense for why the enum is accessible via Python and not Java/MATLAB.

The enum is accessible in Java. I think the issue is that MATLAB does not support nested Java types.

> My preference would be to document the mapping between enum and index number so MATLAB users can access coordinates the "ugly way" and eventually figure out how to expose the enums in MATLAB.

+1
