### ISSUE TITLE
Case sensitivity of strings representing types supported by STOFileAdapter

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#1246]
Refer to #1158.

**Comment by jenhicks** [comment]
@aymanhab I think you brought this up. What, if anything, do you think is in scope for 4.0?

**Comment by aymanhab** [comment]
Document options for Datatype clearly, if no match is found, describe supported ones, case sensitivity or give examples in error message/exception to guide users.

**Comment by jenhicks** [comment]
@klshrinidhi will test whether using ALL CAPS extensions or MIxED CAps works

**Comment by klshrinidhi** [comment]
All the `DataAdapter`s are case-insensitive to extension as per code [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/FileAdapter.cpp#L45).
This means:
* STO, sto, StO, sTo etc are treated the same.
* CSV, csv, CsV CSv etc are treated the same.
