### ISSUE TITLE
Bug in ComponentListIterator

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#1247]
`ComponentListIterator` has a data member `const Component& _root` which refers to nothing (null) in some instances, leading to `_root` being _a reference to a nullptr_, which is _undefined behavior_.

This problem can be reproduced by examining the data member `_root` in `ComponentListIterator<T>::advanceToNextValidComponent()`.

**Comment by jenhicks** [comment]
Should use a smart pointer to _root
