### ISSUE TITLE
Converting TimesSeriesTableVec3 to a writable MOT format

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1252]
`C3DFileAdapter()` generates a marker and a force TimesSeriesTableVec3 for each markers and forces. The marker TimesSeriesTableVec3 can sent to `TRCFileAdapter` and written to file. Forces are stored as Vectors of Vec3's but they need to get printed to a mot file which has independent columns for each force (force, torque, point) with *_x, *_y, *_z column headings

`MOTFileAdapter` doesn't exist on the scripting side at the moment so can't test.

**Comment by jenhicks** [comment]
Need converters to convert flattened mot format.

Take tables that are Vec types and convert into a timeseries of double.
Take option suffixes for elements; otherwise 1,2,3 (by default)

**Comment by klshrinidhi** [comment]
Addressed by #1278. Also verified.
