### ISSUE TITLE
python compiling error due to signal 11: SIGSEGV

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#1253]
Hi again.

I was trying to run the code `Arm_elbow_example_py.py` in the terminal and pycharm, but I got an error, which is the following:
``
AttributeError: 'NoneType' object has no attribute 'updInput'
Segmentation fault (core dumped)
``

I haven't modified anything from the code given by you. 

Do you know why this is happening?

Thanks a lot!

**Comment by chrisdembia** [comment]
@nikorose87 Do you still have an issue? Could you try the updated example at the link below?

 https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/examples/build_simple_arm_model.py

**Comment by nikorose87** [comment]
Unfortunately, I updated the code but I got the following error:

`Traceback (most recent call last):
  File "/home/nikorose/Documents/PythonProjects/Python_arm2.py", line 120, in <module>
    elbow_coord = elbow.getCoordinate().getOutput("value")
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simulation.py", line 22969, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, PinJoint, name)
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simulation.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simulation.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
`

**Comment by chrisdembia** [comment]
Ah shucks. Thanks for trying. Did you rebuild OpenSim using the latest master branch?

**Comment by nikorose87** [comment]
Hi
After rebuilded Opensim and running the lastest example, I got the following error:

`/usr/bin/python2.7 /home/nikorose/Documents/PythonProjects/Arm_other.py
Traceback (most recent call last):
  File "/home/nikorose/Documents/PythonProjects/Arm_other.py", line 147, in <module>
    state = arm.initSystem()
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simulation.py", line 53831, in initSystem
    return _simulation.Model_initSystem(self)
RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:163:
  Error detected by Simbody method VisualizerProtocol::ctor(): Unable to spawn executable 'simbody-visualizer' from directories:
  /usr/bin/
  /home/nikorose/opensim_dependencies_install/simbody/libexec/simbody/
  /usr/local/Simbody/libexec/simbody/
  /usr/local/SimTK/libexec/simbody/
Final system error was errno=2 (No such file or directory).
  (Required condition 'status == 0' was not met.)
`
It seems that the problem now is simbody, I build simbody with the dependencies but I don't know if it builded well because I didn't test it.
Should I try to build symbody by myself?

Thanks

**Comment by chrisdembia** [comment]
Progress! 

The folder `/home/nikorose/opensim_dependencies_install/simbody/libexec/simbody/` should contain the executable `simbody-visualizer`. Did you move the installation of Simbody to another folder?

**Comment by nikorose87** [comment]
Thank you very much!

It works now, I have moved the directory because it installed the dependencies in home directory, so I moved back the directory and done.

Regards.

**Comment by chrisdembia** [comment]
Great. I will close this issue then.

By the way, it should be fine to move the installation location of simbody; just add the path to `simbody-visualizer` to your PATH environment variable.

**Comment by nikorose87** [comment]
As a matter of fact, I've already done it, but it just works with the opensim folder, not dependencies. I don't know why.
regards

**Comment by chrisdembia** [comment]
Simbody hard-codes the location of the `simbody-visualizer` executable into its libraries, based on the value of CMAKE_INSTALL_PREFIX.
