### ISSUE TITLE
Order of PhysicalOffsetFrames are not adequately handled

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1255]
We have been fortunate in most cases to be applying `PhysicaloOffsetFrames` (POFs) to Bodies and Ground.  Bodies and Ground are part of the Multibody tree that we follow to appropriately add components to the MultibodySystem. In `testFrames` we also add a POF to another POF, but in that case we happen to be adding them to the Model in the correct order (proximal POF then distal POF).

If we invert the order in which they are added to the Model (distal prior to proximal) then `initSystem` fails to add the distal POF to the System.

For example, The following code fails:
```cpp
    Model pendulum("double_pendulum.osim");

    SimTK::Transform X_RO;
    X_RO.setP(SimTK::Vec3(0.1, 0.2, 0.3));
    X_RO.updR().setRotationFromAngleAboutAxis(SimTK::Pi / 4.0, SimTK::ZAxis);

    // create PhysicalOffsetFrames Distal and Proximal to identify their
    // relative location to the w.r.t a Body in the Model.
    PhysicalOffsetFrame* offsetFrameDistal = new PhysicalOffsetFrame();
    offsetFrameDistal->setName("offsetFrameDistal");
    offsetFrameDistal->setOffsetTransform(X_RO);
    pendulum.addComponent(offsetFrameDistal);

    PhysicalOffsetFrame* offsetFrameProximal = new PhysicalOffsetFrame();
    offsetFrameProximal->setName("offsetFrameProximal");
    offsetFrameProximal->setOffsetTransform(~X_RO);
    pendulum.addComponent(offsetFrameProximal);

    // Now attach them such that offsetFrameProximal is attached to rod2 of
    // the pendulum and offsetFrameDistal  is attached to offsetFrameProximal 
    offsetFrameProximal->setParentFrame(pendulum.getComponent<Body>("rod2"));
    offsetFrameDistal->setParentFrame(*offsetFrameProximal);

    SimTK::State& s = pendulum.initSystem();
```
with the following Exception:
```
Assigned an invalid SimTK::MobilizedBodyIndex
        In object 'offsetFrameDistal' of type PhysicalOffsetFrame.
        In file G:\OpenSimGit\opensim-core\OpenSim\Simulation\Model\PhysicalFrame.cpp:73
        In function 'setMobilizedBodyIndex'
```

This also came up in #1205 where a mechanism was introduced to enable us to define a desired order independent of the order of POFs in the Model and a fix could potentially be added to that PR. I am in favor of a separate PR to address this issue.

**Comment by carmichaelong** [comment]
Can be handled in separate PR.

**Comment by chrisdembia** [comment]
Thanks for creating this issue; I agree about a separate PR.
