### ISSUE TITLE
Coordinate's "clamped" and "locked" descriptions can be confusing

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#1256]
The property comments from [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Coordinate.h#L71) for clamped and locked are confusing.

Furthermore, the property name "clamped" may also be misleading to users doing forward simulations since (to my knowledge) it is only respected during IK. I think a few steps could be taken to clarify this:

1) Explicitly say that "clamped" is only respected in IK and/or that it is not respected in forward simulations.
2) Change the property name "clamped" to something else.
3) Use Simbody's unilateral constraints to add a "joint_stop" property.

I think 1 and 2 should be done for 4.0, and 3 could be added later.

**Comment by chrisdembia** [comment]
My preference is to only do (1), and to say both. Potential wording:

"This does not affect forward simulations (e.g., RRA, CMC, Forward), and is currently obeyed only by inverse kinematics and the assembly solver"

I'm not sure if the thing about the assembly solver is true.

Do you have a suggestion to replace `clamped`? Personally, I feel `clamped` is OK.

At some point, Sherm shared some thoughts about the interface for joint stops, and I don't remember where that information is but he might have suggested using the `clamped` property to determine whether or not to add unilateral joint stop constraints. I really don't remember, but it has been thought about and quickly discussed in a previous dev meeting.

**Comment by carmichaelong** [comment]
I guess I'd be okay with leaving it as `clamped` as long as it's clear, just wanted to bring it up as an option. It may not be worth breaking the backward compatibility with changing `clamped`. If there's no clear better alternative, keeping it `clamped` is fine.

I would imagine you could use `clamped` in different ways depending on if it's in IK vs. forward. So you could use it as bounds of a solver vs. joint stops depending on the context, but I don't think we have to deal with this until unilateral constraints are in.

**Comment by aseth1** [comment]
@carmichaelong do you want to update the documentation to state that `clamped` refers to the joint limits being enforced (`clamped true`) during assembly and IK? I agree hard joint stops would be great as well for forward simulation and that was on Sherm's plate before he left 😢

**Comment by carmichaelong** [comment]
Sure, I can update this.
