### ISSUE TITLE
Add get/upd methods for fetching Coordinates by name

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1268]
Required for backwards compatibility with the GUI.

**Comment by klshrinidhi** [comment]
This could be done without editing C++ code by extending classes in Java wrapping. This way the *backwards compatibility* changes are localized to Java wrapping (where it is actually needed) and can be removed as GUI is upgraded.

**Comment by tkuchida** [comment]
Hm, I was thinking it might be a good idea to have this method anyway, but @aymanhab - can you use something like
``` cpp
auto& coord = joint.getComponent<Coordinate>("name");
```

**Comment by klshrinidhi** [comment]
If you add string based methods now, you may have to discourage their usage for general users because the current enum based methods are better. If they don't even appear in C++, there will be no such problem.

**Comment by aymanhab** [comment]
Thanks @tkuchida 
joint.getComponent<Coordinate>("name"); can be done in C++ and then wrapped but generally we try to avoid diverging C++ API from Scripting API for maintenance purposes. I'll investigate if some caching can be done on the GUI side to avoid doing the name search later.

**Comment by chrisdembia** [comment]
Both the enum-based and string-based accessors for coordinates are necessary. It is fine if the string-based accessor is `getComponent<Coordinate>("name")` (would reduce duplication but also make it harder to do a very common task). But it is very common and necessary to get a coordinate by its name. "I want to lock the knee angle of my model" is easier via `getCoordinate("knee_angle_r").setLocked(true)` than via `getJoint("knee").getCoordinate(PinJoint::Coord::RotationX).setLocked(true)`.

**Comment by tkuchida** [comment]
> easier via `getCoordinate("knee_angle_r").setLocked(true)` than via `getJoint("knee").getCoordinate(PinJoint::Coord::RotationX).setLocked(true)`

1. Since the knee joint is a PinJoint in your example, you could just do `knee.getCoordinate()` because there's only one Coordinate.
2. I assume by your first example that you want to call `getCoordinate(name)` on Model rather than Joint; otherwise, the only difference between your examples would have been `"knee_angle_r"` in the first and `PinJoint::Coord::RotationX` in the second.

**Comment by chrisdembia** [comment]
Ah yeah you're right about the PinJoint.

Yes; I was assuming some sort of top-level call on the model (those methods don't actually exist on the Model).

**Comment by aymanhab** [comment]
Thanks @tkuchida & @chrisdembia This turned out to be a bit more complicated than expected (surprise) because at this point in the GUI code I have access only to a TransformAxis object that contains "coordinates" property that actually contains only names of Coordinates!. The method to get the coordinates (list property now) from Joint are not available post SWIG, was that intentional, @chrisdembia? Should I be following the "Component" route rather than the "Properties" route?

**Comment by chrisdembia** [comment]
> , was that intentional, @chrisdembia? 

I don't know; I'm not all that familiar with these changes. Seems like right now you could do (in Java):

```java
Coordinate.safeDownCast(joint.getComponent("<coord-name>"))
```

**Comment by aymanhab** [comment]
Thanks much @chrisdembia (I think that was also @tkuchida suggestion earlier) I was worried about using getComponent because it takes a "Path" rather than name which can cause other complications but I was pleasantly surprised and it worked ok with name :+1:  I still think the highlevel access to Coordinates would be useful but maybe a different issue. Let me know @chrisdembia

**Comment by chrisdembia** [comment]
`Component::getComponent()` takes a name or a path.

I think users might like high-level access to coordinates. There are at least two scenarios:

1. looping through all coordinates in the model (`model.getCoordinateList()`).
2. getting a specific coordinate (`model.getCoordinate()`), but I think it should take the full path name.

I think the nice new enum interface for accessing coordinates is mostly beneficial to model-builders (e.g., in the hopper-device example). But model-consumers will most likely prefer string look-up. They are less likely to care whether a coordinate is a RotationX, etc, and more likely to use its biological meaning (e.g., its name, like `knee_r/flexion`).

**Comment by jenhicks** [comment]
make sure there is a getCoordinateList() for the Model

**Comment by jenhicks** [comment]
@aymanhab please investigate whether this is still an issue for the GUI
