### ISSUE TITLE
Memory leak in Coordinate::_lockFunction (a ModifiableConstant)

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#127]
I want to test PinJoint in testComponents, but there's a memory leak in Coordinate. Valgrind says it comes from allocating the ModifiableConstant here: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Coordinate.cpp#L174

Now, Simbody says that it'll own that pointer and delete it (when we pass it to SimTK::Constraint::PrescribedMotion).

I tried making _lockFunction a regular pointer (not a ReferencePtr), and deleted it in the destructor of Coordinate (if it is not null). This gave a segfault.

I don't plan on investigating this any further; just sharing this knowledge.

**Comment by jiangping1989** [comment]
I fixed it. See here:

https://simtk.org/forums/viewtopic.php?f=47&t=5889&start=10

**Comment by chrisdembia** [comment]
A fix for this was attempted with #510, but I'd like @aseth1's blessing on the fix before we close this issue.
