### ISSUE TITLE
Using "\" to specify folders for dependencies in CMake leads to problems downstream

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1271]
Ran into this when I specified a folder for simbody with back-slashes. The build succeeded but later builds that parse the resulting  *config.cmake complained about escape sequences while parsing and failed.

**Comment by chrisdembia** [comment]
In which variable did you use backslashes? `SIMBODY_HOME`?

**Comment by chrisdembia** [comment]
@aymanhab is this problem different from #338?

**Comment by aymanhab** [comment]
Nope, same problem as #338 which was closed, sorry I didn't see it.  I believe the specific directory I used was for Simbody_DIR.  I ended up editing the config.cmake file manually to flip slashes to avoid rebuilding.

**Comment by jenhicks** [comment]
For now, let's document this issue, unless someone knows of an easy fix.

**Comment by chrisdembia** [comment]
Sounds good.

It might be that we have to make sure Simbody_DIR is marked as a PATH variable.

**Comment by chrisdembia** [comment]
I'm almost positive that this has been addressed #1664: we no longer use paths to Simbody's original installation in the OpenSimConfig.cmake file. We can reopen if we find the issue still exists.
