### ISSUE TITLE
Consider storing aliases in Outputs rather than Inputs

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1277]
An "annotation" (to be renamed "alias" per #1226) can be set when connecting Outputs to Inputs. Currently, the Input stores the alias. If an Output is wired into multiple Inputs, each Input can (perhaps accidentally) assign a different alias.

As an example, consider two Marker positions being fed into a Component called Averager: the Output of this Component will _always_ be the average of its Inputs, regardless of the consumer. Thus, it may be appropriate to set the alias on the Averager's Output rather than on the Input of every consumer.

The catch is that Outputs are not currently serialized, so some redesign would be necessary.

**Comment by chrisdembia** [comment]
Thanks for documenting this.

**Comment by chrisdembia** [comment]
Issue #1287  has some valuable discussion related to *this* issue. I've copied some of it here:

@aseth1:

> Related to #1279 is how best to record the path of the Output and its alias that satisfies the Input so that it can be serialized and the connection re-established upon deserialization (and connect()) without user intervention. Currently, this information is stored as the single connectee_name (string) of the Input, which appears like this: /path/to/component:<output_name>(<alias>). Adding the the alias to the connectee_name may be excessive/error prone because of the strict path, ':' and '()' requirements combined (for parsing). We could consider a separate output_name and alias fields (properties) serialized with the Input.

> This would compliment #1277 and separate path information (to identify the Component) and the alias to identify the specific Output or Channel. It would also enable the alias to replace the need to know the output_name if an alias is already assigned to the Output. Something to consider as we approach serialization of Inputs.

@chrisdembia:

> Thanks for those thoughts. I agree about the shortcomings of the current scheme.

We could consider a separate output_name and alias fields (properties) serialized with the Input.
This is appealing but may be even harder to implement for list inputs than the current scheme. If a Reporter has 5 outputs wired to it, and only one of them (say the 3rd one) has an alias, how do I match that one alias to the correct input?

This would compliment #1277
I am starting to agree with @aymanhab etc that perhaps the alias does belong with the output.

> ...separate path information (to identify the Component) and the alias to identify the specific Output or Channel.
This raises a question: are the aliases "global" or "local" to the component? I had imagined that an alias would replace all of /path/to/component:<output_name>(<alias>), not just output_name. In what I'm thinking though, using an alias as a connectee_name may make it much harder to make the connections: the top-level Model would have to store a dictionary mapping aliases to components.

**Comment by aseth1** [comment]
also from #1287 @tkuchida:

>It may be possible to address these design issues using UUIDs (#1192) and storing/serializing a master lookup table of aliases/connections (perhaps materials as well). Perhaps something to discuss in the context of model nesting and introducing an omniscient Environment or World Component. Definitely post-4.0

>@chrisdembia 👍, @aseth1 :+1:
