### ISSUE TITLE
Consider combining Input::getShortLabel() and getLongLabel() to one label related method

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1287]
This issue is a replacement for DevProp #1284, which has been closed.  Many points reflect the input from @tkuchida. This is my quick summary:

Potential issues to consider:
1. `getAlias()`, `getShortLabel()`, and `getLongLabel()` all return `alias` when an alias has been provided and this may be confusing for users since all methods are part of the public interface. Secondarily, it doesn't adhere to a minimally complete interface that we try to follow.
2. `getShortLabel()` returns the output name that may be *value* (e.g. Coordinate) or other generic output of a Component (like *force*, *speed*, ...) and would not be descriptive enough to distinguish between Outputs.

A single method alternative:
 - `getReportingLabel(uint width)` (or maybe just `getLabel()`) to return  the *alias* value when provided otherwise the Output's full path name.  In the case that `width > minSize`  use *width* to truncate the resulting label.  The truncated label would be used by ConsoleReporter and/or plotting where concise labels are necessary.

Some proposals for truncation  are:
 - show last width-3 characters prefixed by `...`
 - show first (width-3)/2 chars, `...`, and last (width-3)/2

In the case that no truncation is provided the ConsolerReporter could still print labels on multiple lines if necessary:

<pre>
             |             | a/very/long/
        time |  activation |  output/path
</pre>

**Comment by aseth1** [comment]
Related to #1279 is how best to record the *path* of the `Output` and its *alias* that satisfies the `Input` so that it can be serialized and the connection re-established upon deserialization (and `connect()`) without user intervention.  Currently, this information is stored as the single `connectee_name` (string) of the `Input`, which appears like this: `/path/to/component:<output_name>(<alias>)`.  Adding the the *alias* to the `connectee_name` may be excessive/error prone because of the strict path, ':' and '()' requirements combined (for parsing). We could consider a separate *output_name* and *alias* fields (properties) serialized with the `Input`.   

This would compliment #1277 and separate path information (to identify the Component) and the `alias` to identify the specific `Output` or `Channel`. It would also  enable the *alias* to replace the need to know the *output_name* if an *alias* is already assigned to the `Output`. Something to consider as we approach serialization of `Input`s.

**Comment by chrisdembia** [comment]
Thanks for those thoughts. I agree about the shortcomings of the current scheme.

> We could consider a separate output_name and alias fields (properties) serialized with the Input.

This is appealing but may be even harder to implement for list inputs than the current scheme. If a Reporter has 5 outputs wired to it, and only one of them (say the 3rd one) has an alias, how do I match that one alias to the correct input?


> This would compliment #1277

I am starting to agree with @aymanhab etc that perhaps the alias does belong with the output.


> ...separate path information (to identify the Component) and the alias to identify the specific Output or Channel. 

This raises a question: are the aliases "global" or "local" to the component? I had imagined that an *alias* would replace all of `/path/to/component:<output_name>(<alias>)`, not just `output_name>`. In what I'm thinking though, using an alias as a connectee_name may make it much harder to make the connections: the top-level Model would have to store a dictionary mapping aliases to components.

**Comment by jenhicks** [comment]
Pushing to next release, but we can elevate should issues come up during user testing.

**Comment by tkuchida** [comment]
It may be possible to address these design issues using UUIDs (#1192) and storing/serializing a master lookup table of aliases/connections (perhaps materials as well). Perhaps something to discuss in the context of model nesting and introducing an omniscient Environment or World Component. Definitely post-4.0.

**Comment by aseth1** [comment]
@tkuchida I believe your PR #1316 addressed the principle issue raised and I would like to close this issue. Any objections to moving the good points raised here (concerning serializing and identifying Outputs via the *alias*) to #1277 and closing this issue? @chrisdembia?

**Comment by chrisdembia** [comment]
I agree; we can close this. Some of the content here has already been copied to #1277.

**Comment by tkuchida** [comment]
Sounds good :+1:
