### ISSUE TITLE
Python and MATLAB do not have non-default PhysicalOffsetFrame constructors

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1293]
The constructors for `PhysicalOffsetFrame` are inherited from `OffsetFrame<PhysicalFrame>`, and SWIG does not support inherited constructors (`using OffsetFrame<PhysicalFrame>::OffsetFrame;`). As a result, the constructors for PhysicalOffsetFrame are not available in the bindings. 

We need to do the same thing we did for the Joint classes.

**Comment by jenhicks** [comment]
@jimmyDunne and @chrisdembia do you know if this is still an issue? If so, it sounds like one we should resolve for 4.0

**Comment by chrisdembia** [comment]
Yes, this is still an issue.

**Comment by chrisdembia** [comment]
This should be easy to fix.

**Comment by jenhicks** [comment]
fixed by #1391
