### ISSUE TITLE
Write examples for alpha testing of API

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1297]
- [x] Script to build a template actuators file that can be used in Static Optimization, RRA and CMC (see PR #541 (Shrinidhi)
- [ ] Convert dynamic walker example (James)
- [ ] Convert hopper example (Chris)
- [ ] Convert between Millard and Thelen muscle models  (Ayman)
- [ ] Simple arm model in Matlab (James)
- [x] Plot muscle curves (James, look for already written version)
- [ ] Show how to use the DataTable's `flatten()` and pack() in scripting (James)
- [ ] Muscle analysis (Ajay)
- [ ] Point and body kinematics; also report Center of Mass (Ajay)
- [ ] Use of states trajectory for a custom post-hoc analysis (maybe trapeziodal rule for integration, Chris) 
- [ ] Extending a class (controller) in Python (Ayman)
- [ ] Update old matlab and python examples (Shrinidhi; start some)
- [ ] Optimization of standing balance movements with synergies (Mazen)
- [ ] Dump model's connections, inputs and outputs (Ayman)

**Note**
Remember to add dependencies (e.g., double_pendulum_markers.osim) to [CMakeLists.txt](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/CMakeLists.txt) when moving scripts from the Sandbox into Bindings/Java/Matlab/examples.

**Comment by jenhicks** [comment]
@jimmyDunne Creating the functionality of #541 would be great to add to the list.

**Comment by jimmyDunne** [comment]
np. Have copied over the script into a new commit elsewhere.

**Comment by jenhicks** [comment]
Cool. Thanks -- where's the new one?

**Comment by aseth1** [comment]
What do you think of an example that highlights the data handling and new `TableSource` component to read marker data from trc and C3D, wire the data to ExperimentalMarker components and visualize them? If we could do this in 25 lines or less it would be a compelling and practical example of the new capabilities. I am working on a prototype in C++.

**Comment by tkuchida** [comment]
> What do you think of an example that highlights the data handling and new TableSource component to read marker data from trc and C3D, wire the data to ExperimentalMarker components and visualize them?

Some relevant discussion in #1144.

**Comment by aymanhab** [comment]
I'd add that the number of lines likely doesn't matter as much as that users can follow the code and modify it to fit their needs.

**Comment by jimmyDunne** [comment]
My hope was that we could have a pipeline of *Read C3D -> scale model -> IK -> ID*

**Comment by jimmyDunne** [comment]
I am keeping all Matlab scripts in branch _adding_matlab_scripts_

**Comment by jimmyDunne** [comment]
All Matlab scripts are in the this PR/branch #1311

**Comment by jimmyDunne** [comment]
Matlab scripts to create an actuators file and plot muscles f-l curves can be found in PR1311, [here](https://github.com/opensim-org/opensim-core/pull/1311/commits/3d7ba9a4014579449e233ef59b31991a0956596f)

**Comment by chrisdembia** [comment]
I added myself to two of the examples above.

**Comment by tkuchida** [comment]
**Project** – The right `Frame` of mind
**Team** – James and Tom
**Description** – The new `Frames` infrastructure makes it easy for users to report quantities in reference frames that are most convenient for analysis. Using a simple model, we will demonstrate how to use the 4.0 API to define anatomical reference frames (PhysicalOffsetFrames) programmatically from experimental marker data.

**Comment by apoorvar** [comment]
Project - re-do the Tug-of-war example in the Developer's guide (http://simtk-confluence.stanford.edu:8080/display/OpenSim/Performing+a+Simulation) using Matlab/4.0 and add mini-analyses like get muscle-tendon lengths and velocities

**Comment by nickbianco** [comment]
Project - I will work on converting the dynamic walker example

**Comment by chrisdembia** [comment]
> Project - I will work on converting the dynamic walker example

@nickbianco, do you plan to work with @jimmyDunne on this? He is almost done with the conversion  (see here https://github.com/opensim-org/opensim-core/pull/1439).

**Comment by nickbianco** [comment]
@chrisdembia, oh right. James sent me the PR yesterday, I didn't realize they were mostly done. Mazen and I talked about added an optimization for guesses of the initial states (as @jimmyDunne suggested), but never decided exactly what we were going to do.

**Comment by carmichaelong** [comment]
@aseth1 Are you working on both projects above? If not I can take one off your hands.

**Comment by chrisdembia** [comment]
> Mazen and I talked about added an optimization for guesses of the initial states (as @jimmyDunne suggested), but never decided exactly what we were going to do.

Oh cool; I think something like that would be awesome.

**Comment by chrisdembia** [comment]
@nickbianco @malborno  then perhaps you want to build on top of @jimmyDunne's branch ([matlabScripts_DynamicWalker](https://github.com/opensim-org/opensim-core/tree/matlabScripts_DynamicWalker))

**Comment by nickbianco** [comment]
Actually, I'm all of sudden not really feeling so well. I'm going to head home to catch up on some rest before the TA meeting later today.
