### ISSUE TITLE
FInding Python version on path (Cmake)

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1303]
When building the python wrapping, Cmake defaults to a standard dir (OSX; user/bin/python2.7). If that is not the version of python that is on your path, you only get exceptions once you try to `import opensim`.

Would be swell if Cmake could find the python version currently being used.

**Comment by chrisdembia** [comment]
Thanks @jimmyDunne. Related: #691.

**Comment by jimmyDunne** [comment]
Cool. Ill add that I didn't use homebrew. Mine was a Anaconda installation 💯

**Comment by chrisdembia** [comment]
🐍
