### ISSUE TITLE
Master list to track scripting issues

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1308]
List of PRs and/or open issues that @jimmyDunne is stuck on while trying to write test scripts:
- [ ] Fix crash running README file in a loop
- [x] Issue related to column labels/units when converting trc to Sto file for Forces
- [x] Matlab crashing during multiple simulation due to Reporters/TimeSeriesTable
- [x] Changing values in a TimesSeriesTableVec3 (Matlab) 
- [x] Add clearReport() to TableReporter. Throw meaningful exception while appendRow
- [ ] MetaData in DataTable/TimeSeriesTable not accessible from Python/Java/Matlab. See #1312.

**Comment by aymanhab** [comment]
@jimmyDunne This is a place holder for the issues we discussed yesterday with @klshrinidhi I know you had more but wanted to get this started so we can keep an eye on progress and help where needed. Please feel free to mark resolved issues as such or add other items that we discussed and are still unresolved. Thanks.

**Comment by klshrinidhi** [comment]
I addressed the second one (￼*Issue related to column labels/units when converting trc to Sto file for Forces*) is addressed in #1278.

**Comment by aymanhab** [comment]
Thanks @klshrinidhi I added comments on the PR and will have @jimmyDunne check it off when it works for him. Feel free to add any other related issues you're working on to this list.

**Comment by aymanhab** [comment]
Thanks much @klshrinidhi for the fixes and added tests. @jimmyDunne if you can go through the list and check what's done and add any functionality you're waiting on that would be great. Thank you.

**Comment by aymanhab** [comment]
@jimmyDunne If there are no outstanding issues, please close, otherwise mark and assign to responsible party. Thanks.
