### ISSUE TITLE
Accessibility of table metadata values in Matlab 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1312]
I have marker data in a table, and I would like to get the data rate. I can access `.getTableMetaDataKeys` to see what metadata is available. Unfortunately, I can't seem to find a way to access the metadata values (in this case the data rate). `.getTableMetaData` gives an exception and I am unsure on any other methods I could use to get the rate.

**Comment by klshrinidhi** [comment]
This requires wrapping of the classes `OpenSim::ValueArrayDictionary`, `SimTK::AbstractValue`, `SimTK::Value` and may be more.

**Comment by klshrinidhi** [comment]
I will try to add a templated member function to `AbstractDataTable` to retrieve table metadata based on the specified type in the call. I will then try to expose this method to Python/Java. This will avoid the need for wrapping more classes.
