### ISSUE TITLE
CMC_Task may be ignoring many of its properties

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1335]
The `updateFromXMLNode()` function in `CMC_Task` does not make use of the property member variables like `_propKP`, etc. So it is possible that CMC_Task is ignoring these properties.

This was first raised in #1333.

**Comment by aseth1** [comment]
`updateFromXMLNode()` is not necessary to make use of properties. It should only be implemented to make updates to naming or handle other changes that impact how the properties are represented in XML. Most of the implementation should be removed and all that should remain is the call to its `Super` (aka `TrackingTask`).

**Comment by aseth1** [comment]
The use of properties is unrelated to `updateFromXMLNode()` in #1333 so I am closing this issue.
