### ISSUE TITLE
Updates to InverseKinematicsSolver's marker weights are not respected

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1339]
### Issue
Marker weights updated with [InverseKinematicsSolver::updateMarkerWeight()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/InverseKinematicsSolver.h#L95) do not affect subsequent solutions computed by `assemble()`. The expected behavior is
``` cpp
// ...
InverseKinematicsSolver iks(model, markersRef, coordinateRef);
iks.assemble(state); //uses weights specified in markersRef
iks.updateMarkerWeight("myMarker", desiredWeight);
iks.assemble(state); //uses new weight for myMarker
```
The second `assemble()` call does not respect the new desiredWeight.

### Workaround
Create a new `InverseKinematicsSolver` when adjusting marker weights (which is unlikely to occur frequently anyway).

### Suggested short-term solution
Perhaps simply remove the `updateMarkerWeight()` methods for now because they are neither covered by test cases nor used anywhere in the API.

**Comment by chrisdembia** [comment]
Does this affect your leet PR #1337?

**Comment by tkuchida** [comment]
> Does this affect your leet PR #1337?

```
if (getPR(1337).isMerged()) {
    auto& newBranch = createBranch();
    newBranch.addressIssue(1339);
    createPR(++getLastPRNum(), newBranch);
} else {
    updPR(1337).updBranch().addressIssue(1339);
}
```

**Comment by aseth1** [comment]
@tkuchida thank you for reporting this issue.

> Perhaps simply remove the updateMarkerWeight() methods for now because they are neither covered by test cases nor used anywhere in the API.

Friedl used this to update weightings using an adaptive filter she implemented.  I would prefer to fix it.

I would like to understand what happened after the second assemble call. Was there  an error/exception or did the resulting kinematics not change as expected? Did you look at the error of the specific marker?

If you have a use case that failed handy, I could include it as a test case, otherwise, I will come up with one.   Thanks.

**Comment by tkuchida** [comment]
> Friedl used this to update weightings using an adaptive filter she implemented.

Ok, thanks. I must be doing something wrong then. I'll close this issue and investigate again. We may just need to improve the doxygen.

Nevertheless, I think we should add a unit test for InverseKinematicsSolver as it currently isn't being tested in isolation. It would also be useful to have `updateMarkerWeight()` used somewhere in the API so future developers know how it's supposed to work. Tracked at #1350.

**Comment by aseth1** [comment]
@tkuchida It is be possible that somehow the updating is no longer working or did not work as expected. I totally agree about the unit tests. Thanks for opening #1350.
