### ISSUE TITLE
Difficult to resize, hide, make transparent or change axis lengths for FrameGeometry

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1342]
All Frames in OpenSim (Ground, Bodies, parent and child offset frames of Joints, etc...)  have an associated `FrameGeometry` that serves to draw the Frame's axes in the Visualizer. It currently appears white, opaque, and with each axis being 20cm long. For models like the shoulder and the neck with many frames you can barely see the model. 

There is currently no way to: hide the `FrameGeometry`; change the default size (0.20 is hard coded); or make it transparent. The only way to effectively diminish them was to loop through each `FrameGeometry` and set its scale factor to something small (like 0.001).

Respecting visualizer hints to ignore the drawing of this geometry would be helpful.

**Comment by tkuchida** [comment]
Related: #1023

**Comment by aymanhab** [comment]
Sure, I'll update the branch that dates back to before the dev week to move forward.
