### ISSUE TITLE
Add unit test for InverseKinematicsSolver

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1350]
InverseKinematicsSolver is used by InverseKinematicsTool and MarkerPlacer but isn't being tested in isolation (unit test is missing); `InverseKinematicsSolver::updateMarkerWeight()` is not being tested anywhere. Possible test cases for InverseKinematicsSolver include the following:
- Call `assemble()`, use `setAccuracy()` to tighten the tolerance, and call `assemble()` again. The total marker error should be lower after the second call to `assemble()`. Note that the second call must be `assemble()` rather than `track()` because the latter will not propagate the new accuracy to the underlying `SimTK::Assembler` (see PR #1343).
- Create a multi-marker model and set only one marker weight high (:cow:). (For this test, it must be impossible to satisfy all marker targets simultaneously.) Call `assemble()` and verify that :cow: has been correctly positioned. Now use `updateMarkerWeight()` to set :cow:'s weight low and a different marker's weight high (:cow2:). Call `assemble()` again and verify that :cow2: is now correctly positioned.

**Comment by jenhicks** [comment]
@aymanhab Can you take a look?
