### ISSUE TITLE
Millard2012Equilibrium Muscle - fiberStiffnessAlongTendon  incorrect calculation

### ISSUE THREAD

**Issue by humphreysb** [opensim-org/opensim-core#1357]
In calcMuscleDynamicsInfo, mdi.fiberStiffnessAlongTendon is calculated:

`dFmAT_dlceAT = calc_DFiberForceAT_DFiberLengthAT(dFm_dlce, mli.sinPennationAngle, mli.cosPennationAngle, mli.fiberLength);`

The first argument provided is _dFm_dlce_  (muscle stiffness), change in force along **the fiber** / lce.  But the method requires:

`double Millard2012EquilibriumMuscle::calc_DFiberForceAT_DFiberLengthAT(double dFmAT_d_lce, double sinPhi, double cosPhi,double lce) const`

 where  _dFmAT_d_lce_ is the change in force along **the tendon**/ lce

I verified that calc_DFiberForceAT_DFiberLengthAT is written to use dFmAT_d_lce, so it is being provided the wrong parameter when  invoked in  calcMuscleDynamicsInfo.

**Comment by chrisdembia** [comment]
Thanks for reporting. [Here is the current implementation of that function](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1220):

```cpp
double Millard2012EquilibriumMuscle::
calc_DFiberForceAT_DFiberLengthAT(double dFmAT_d_lce,
                                  double sinPhi,
                                  double cosPhi,
                                  double lce) const
{
    double dphi_d_lce = getPennationModel().
                            calc_DPennationAngle_DfiberLength(lce);

    // The change in length of the fiber length along the tendon.
    // lceAT = lce*cos(phi)
    double DlceAT_Dlce = cosPhi - lce*sinPhi*dphi_d_lce;

    // dFmAT/dlceAT = (dFmAT/dlce)*(1/(dlceAT/dlce))
    //              = dFmAT/dlceAT
    return dFmAT_d_lce * (1.0/DlceAT_Dlce);
}
```

**Comment by humphreysb** [comment]
I carried out the derivation, and I get the following (it's a bit long, but I can post it if you want).  The stiffness along the fiber and along the tendon are nearly identical (in fact, if the fiber stiffness is linear, they are exactly equal).
![screenshot from 2016-10-23 19 49 12](https://cloud.githubusercontent.com/assets/7395691/19630506/cbf60c38-9959-11e6-8209-f3f2c27b309c.png)

**Comment by jenhicks** [comment]
@aseth1 or @tkuchida could you provide input?

**Comment by tkuchida** [comment]
Thanks for reporting, @humphreysb. This is, indeed, a bug :beetle:. The `Millard2012EquilibriumMuscle::calc_DFiberForceAT_DFiberLengthAT()` method is called from `calcMuscleDynamicsInfo()` and `estimateMuscleFiberState()`; the argument is incorrect in only the first case. I checked the calculations themselves and they appear to be correct.

I'll submit a PR to fix the incorrect argument, but hesitate to make further changes without careful analysis of the rest of the code. The current `calc_DFiberForceAT_DFiberLengthAT()` method doesn't appear to be doing anything egregious. Note that `estimateMuscleFiberState()` uses the stiffness calculations to find an equilibrium between the fiber and tendon; we would need to analyze the new calculation keeping in mind that some relationships among variables may not be satisfied until the algorithm has converged.
