### ISSUE TITLE
CMC look ahead window and path actuated model

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#1360]
When performing CMC with PathActuators for muscles, the default look ahead window causes instabilities, due to the fact that the PathActuators does not need a prediction. This behavior is observed when we have external forces attached (e.g. gait2354 example). The solution is to use smaller look ahead time window (e.g. 0.001). Unfortunately, this causes the simulation to be very slow. I am not sure if there is a quick fix, but by default a PathActuator should not need the time window look ahead.

**Comment by chrisdembia** [comment]
Interesting. To be clear, do you use any muscles in this scenario? Or *only* PathActuators?


Given that a proper fix for this would take a long time, I would say that all we can expect to do in the short term is to document this behavior (on confluence).

**Comment by mitkof6** [comment]
> Interesting. To be clear, do you use any muscles in this scenario? Or only PathActuators?

I use only PathActuators, but there may be cases of both.

**Comment by chrisdembia** [comment]
> I use only PathActuators, but there may be cases of both.

I wonder if you could then use RRA instead...not sure.

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
