### ISSUE TITLE
Excitation is not clamped (in many cases)

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#1365]
From what I can see, excitation is finally clamped when `FirstOrderMuscleActivationDynamics::calcActivationDerivative()` is called. This can cause issues with things like the `Umberger2010MuscleMetabolicsProbe` since it needs excitations for calculations. A user can set the excitation of a muscle to be outside of the [0,1] range, thinking that it will be clamped at some point, which can lead to issues with the probe.

At what point should excitation be clamped?

**Comment by tkuchida** [comment]
**A word of caution:** `MuscleActivationDynamics` and the classes derived therefrom (`ZerothOrderMuscleActivationDynamics` and `FirstOrderMuscleActivationDynamics`) aren't being tested AFAIK and may be out of date. I originally intended to replace the existing activation dynamics code (e.g., `MuscleFirstOrderActivationDynamicModel` and the pieces sprinkled throughout the muscles) with these, which would make it easy to change the activation model without creating an entirely new muscle (see #366)—though there are differing opinions about what should and shouldn't be configurable (see the discussion in #1266).

**To answer your question:** Classes derived from `MuscleActivationDynamics` were designed to require an `ExcitationGetter` (see [this comment](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/MuscleActivationDynamics.h#L58)). The `ExcitationGetter::getExcitation()` method should clamp before returning.

**Comment by jenhicks** [comment]
@carmichaelong Is this still an issue for you? Is there a bug or is the behavior just not as expected?

**Comment by carmichaelong** [comment]
I think the best way to describe this is that the behavior may be unexpected for other classes that look up muscle excitations during a simulation, which could be seen as a bug for these other classes. To give a concrete example:

1) Someone can set a muscle's control value to anything (even outside of [0,1]), assuming that it will be clamped at some point. This number is stored as is though (so if you call `getControl()` on an actuator that was set to -0.5, you'll get back -0.5).
2) When calculating activation, some methods do clamp the excitation internally (see [here](https://github.com/opensim-org/opensim-core/blob/dc17ff08e0b40311c984f978b1462f7e31e2756a/OpenSim/Actuators/MuscleFirstOrderActivationDynamicModel.cpp#L82) for example). In this case, our value of -0.5 will be clamped up to `get_minimum_activation()`. Note that the control value is still left unchanged, but does not affect calculations for determining muscle force.
3) Other methods may need to know the excitation of a muscle (for instance the `Umberger2010MuscleMetabolicsProbe` at this [line](https://github.com/opensim-org/opensim-core/blob/dc17ff08e0b40311c984f978b1462f7e31e2756a/OpenSim/Simulation/Model/Umberger2010MuscleMetabolicsProbe.cpp#L276)). This will return -0.5, which can cause issues for the metabolics calculator (so it could be seen as a bug from this perspective).

I think this issue first needs discussion about how we should handle excitation internally, which will determine if there are further bugs or not.

**Comment by chrisdembia** [comment]
It would be nice to have a consistent way to handle clamping of quantities across the API.

**Comment by aseth1** [comment]
My preference would be that Components and/or algorithms do not clamp their inputs, but state in their documentation what are acceptable bounds for its inputs. If the inputs exceed these bounds an exception is thrown. The onus is then on the supplier to provide valid values. Otherwise, we could have muscle controllers that produce complete garbage but still run because the muscle clamps garbage into a valid range - I think that is wrong. If it is a muscle controller it should know and respect the valid range of input values for its actuators. That was why we added max and min control values on `Actuator` so that a controller can know about and respect those limits. This is similar to how the Assembly and InverseKinematicsSolvers behave by respecting the limits (if any) on the Coordinates.

**Comment by tkuchida** [comment]
Fixed by #1548.
