### ISSUE TITLE
Test cases use assert() rather than ASSERT()

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1375]
`assert()` does nothing in Release mode:
``` cpp
#ifdef NDEBUG
    #define assert(expression) ((void)0)
#else
    ...
#endif
```
`assert()` should probably be replaced with `ASSERT()` in testComponentInterface.cpp, testDataTable.cpp, and testWrapping.cpp, as there does not appear to be a reason to suppress the tests appearing therein when building in Release mode. Presumably, the test cases should be checking everything regardless of configuration.

- [x] testComponentInterface.cpp
- [x] testDataTable.cpp
- [x] testWrapping.cpp

**Comment by klshrinidhi** [comment]
I have fixed this in `testDataTable` in PR #1372. `testDataTable` has a mix of both `assert` and `ASSERT`, probably from copy-paste. It is now fixed to use `ASSERT` everywhere.
