### ISSUE TITLE
StatesTrajectory documentation is inconsistent

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1381]
The class description says that "The states are ordered nondecreasing in time (adjacent states can have the same time)." while the `append()` method "ensures that the time in the new SimTK::State is greater than the time in the last SimTK::State in the trajectory". Whether adjacent states can have the same time should be clearly documented and consistent throughout the code. If the class allows adjacent states to have the same time, the `append()` method should not prohibit appending such states.

**Comment by tkuchida** [comment]
Related to #820

**Comment by chrisdembia** [comment]
For the current implementation of StatesTrajectory, the doxygen documentation for `append()` is incorrect.

**Comment by chrisdembia** [comment]
Fixed by #1385.
