### ISSUE TITLE
DataTable::getRow() should not perform equality comparison on double

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1384]
[`DataTable::getRow()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/DataTable.h#L485) uses `std::find()` to search for a specified entry in the independent column. When the independent variable is of type `double` (e.g., time, as will often be the case), `std::find()` must include a tolerance (e.g., using `std::find_if()`). Currently, filling a `TimeSeriesTable` with time points spaced 0.01 seconds apart and doing
```cpp
for (unsigned i=0u; i<table.getNumRows(); ++i)
    table.getRow(0.01*i);
```
throws `KeyNotFound` when `i=6u` due to roundoff error.

**Comment by chrisdembia** [comment]
The same issue arises with https://github.com/opensim-org/opensim-core/pull/774.

See this function: https://github.com/opensim-org/opensim-core/pull/774/files#diff-b69edb579e6af6dc07da35945b3e3eadR124

**Comment by klshrinidhi** [comment]
This was actually intended when DataTable was written. Since DataTable is a just a container allowing multiple types to be stored in the independent column, it does not implement any special code for finding values of type `double`.

If you need to search the independent column, get it first, search it yourself and use the resulting row index to get the row.

I can change the behavior but this will require extra argument to all the getRow and updRow functions.

**Comment by klshrinidhi** [comment]
If the PR #1372 gets merged, it will add a function named `getNearestRow` which can be used instead to avoid this problem.
So basically that PR addresses this issue.

**Comment by tkuchida** [comment]
> Since DataTable is a just a container allowing multiple types to be stored in the independent column, it does not implement any special code for finding values of type double.

I don't think this implementation detail will be obvious to the user. After filling a table with t = 0.00, 0.01, 0.02, …, calling `getRow(0.05)` works but calling `getRow(0.10)` throws an exception. That behavior doesn't seem to be logically consistent from the user's perspective.

> If you need to search the independent column, get it first, search it yourself and use the resulting row index to get the row.

It might be useful to include this message when `getRow()` throws `KeyNotFound`.

> So basically that PR addresses this issue.

I suggest also adding a comment to the documentation for `getRow()` indicating that it performs an equality comparison, with `@see getNearestRow()`.

**Comment by chrisdembia** [comment]
An aside:

> After filling a table with t = 0.00, 0.01, 0.02, …, calling getRow(0.05) works but calling getRow(0.10) throws an exception.

I find this surprising, because both times you specify `0.10`, it should have the same exact representation as a `double`.

**Comment by klshrinidhi** [comment]
> I don't think this implementation detail will be obvious to the user. After filling a table with t = 0.00, 0.01, 0.02, …, calling getRow(0.05) works but calling getRow(0.10) throws an exception. That behavior doesn't seem to be logically consistent from the user's perspective.

This is the behavior one will see with standard containers (like `std::vector<double>`) as well. So it is consistent with the notion of **containers**, that they don't perform any special searching for any type. They rely on `==` operator of the type. 
I think this is a problem for users who are **unaware of floating-point representation**. 

> It might be useful to include this message when getRow() throws KeyNotFound.

Good idea. I will sneak this into PR #1372. The message will point the user to use `getNearestRow` if appropriate.

-----------------------------------

I think it is important to not have getRow() behave differently for different types -- that is search for exact equality in some types and search for approximate equality in other types. If an approximate search is desired, it should have its own function. That will be explicit in user code and potentially avoid confusion. Once a user encounters an exception while using `getRow`, the message will hopefully help not make the same mistake again.

**Comment by tkuchida** [comment]
> I find this surprising, because both times you specify `0.10`, it should have the same exact representation as a `double`.

What I described was the user-side logic (for brevity). The actual code was time-stepping:
```cpp
// Case 1
double t = 0.;
for (unsigned i=0u; i<numSteps; ++i) {
    //stuff
    t += stepSize;
}
```
Of course, I can do this instead:
```cpp
// Case 2
for (unsigned i=0u; i<numSteps; ++i) {
    const double t = stepSize*i;
    //stuff
}
```
which seems to allow `getRow(0.10)`, etc., but these two approaches are logically similar and I don't think we can expect users to adopt Case 2 over Case 1.

**Comment by chrisdembia** [comment]
> I think this is a problem for users who are unaware of floating-point representation.

_Our_ users 😞 

> What I described was the user-side logic (for brevity).

Thank you for explaining. This makes sense to me now. I brought up my point mainly to see if there was another issue/bug.

**Comment by tkuchida** [comment]
> I think this is a problem for users who are **unaware of floating-point representation**.

I disagree. I am aware of floating-point representation. I think the problem is that I'm working with a `TimeSeriesTable` [where the independent column is time of type double](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/TimeSeriesTable.h#L98), so it would seem that `getRow()` would be designed to play nicely with an independent column of doubles.

**Comment by klshrinidhi** [comment]
> I disagree. I am aware of floating-point representation. I think the problem is that I'm working with a TimeSeriesTable where the independent column is time of type double, so it would seem that getRow() would be designed to play nicely with an independent column of doubles.

I don't think so. From what I understood while writing it, TimeSeriesTable is meant to be a container that stores what it was given. It does not treat certain types differently, just like standard containers. In fact the independent column is implemented as a `std::vector` and so behaves exactly like that.

Expecting TimeSeriesTable::getRow() to handle doubles differently is same expecting std::vector to handle doubles differently.

In any case, I think having two different functions -- one for exact search and one for approximate search is a good thing. It will be confusing if one function did both.

**Comment by jenhicks** [comment]
@klshrinidhi I agree that you have implemented according to specification as a container. But @tkuchida is one of our savviest users, so if this caught him off guard, I think that others will get tripped up. The solution of adding getNearestRow() with an more informative error message for getRow() sounds like a good first fix that everyone agrees on. We can discuss as a group whether additional updates are warranted.

**Comment by tkuchida** [comment]
> the independent column is implemented as a `std::vector` and so behaves exactly like that

Interesting. The title of the doxygen page is **OpenSim::TimeSeriesTable_< ETY > Class Template Reference**. Does that mean there could be a TimeSeriesTable whose independent column is of type `unsigned` (or even `bool`)? My intuition says that time is always of type `double` and a TimeSeriesTable is a table whose independent column is of type `double`. The class description ("TimeSeriesTable_ is a DataTable_ where the independent column is time of type double.") seemed to confirm this intuition.

**Comment by klshrinidhi** [comment]
TimeSeriesTable is derived from DataTable, which contains the implementation of the independent column. It is possible to have independent column of type other than `double` for DataTable. However TimeSeriesTable locks the independent column to be of type `double` but does not do much more in terms of handling independent column differently. My understanding has been that DataTable and its derived classes are all just containers, not mathematical objects. 
Any special handling for certain types will have to go into DataTable because it would be confusing if TimeSeriesTable alone treated certain types differently. One would lose the special handling after upcasting from TimeSeriesTable to DataTable and that can potentially cause problems for users. Now since DataTable (in my understanding) was meant to be a just container with metadata, it does not handle any types differently.
*Strictly speaking, dependent columns of DataTable are restricted to ones for which SimTK::Matrix_ can be created. So it is not possible to create DataTable with dependent columns of any type.*

**Comment by tkuchida** [comment]
> One would lose the special handling after upcasting from TimeSeriesTable to DataTable and that can potentially cause problems for users.

Ah, that's a good point. I think your new `getNearestRow()` method and adding references to it in the documentation/exception message are sufficient.

**Comment by klshrinidhi** [comment]
Sounds good.
If we don't see the independent column used for any type other `double` in practice (currently I don't), we can lock it to being `double` and remove the first template argument from DataTable. Then we could have all the methods use the knowledge that the independent column is always `double`.

**Comment by klshrinidhi** [comment]
I think this issue can be closed now. The PR #1372 added functions `getNearestRow` and `updNearestRow`. It also [adds documentation](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/DataTable.h#L671-L674) to `getRow` pointing to these added functions depending on the need.
