### ISSUE TITLE
ForceReporter() needs to be updated or a replacement made.  

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1396]
The FroceReporter still functions as is on Master (via Matlab), but it doesn't fit with the new component interface. Not using the ForceReporter() to reporter ALL the forces in a model, is pretty involved. 

ForceReporter should internally use the TableReporter and Component outputs, or there should be a new class that achieves the same thing as ForceReporter (reports all forces from a model during a simulation).

**Comment by aymanhab** [comment]
I'd strongly recommend not removing it, since so many users count on it. A refactoring is totally reasonable.

**Comment by jimmyDunne** [comment]
👍  Looks like it storage just needs to be gutted out and replaced with tables.

**Comment by chrisdembia** [comment]
That would be a good first step.

**Comment by jenhicks** [comment]
Try accessing component list and looping through and using TableReporter. Flag anything that doesn't have outputs.
