### ISSUE TITLE
Clean up Manager interface/usage

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#1405]
These are left over TODOs from #1386:

- [x] Remove `_system` and subsequently make CMC use its own `TimeStepper` rather than the `Manager` to do its integration
- [x] Prevent any chance of mixing the wrong system/model between the integrator and timestepper. This may involve removing/changing some of the constructors and methods such as `setIntegrator()` and `setModel()`. As per discussion with @aseth1, it may be best to only allow construction of a `Manager` when given both the Model and Integrator, just before integration.

**Comment by aseth1** [comment]
Just to clarify point 1: The setting of the `_system` member of the `Manager` was a way for CMC to integrate the `CMCActuatorSystem` and not a Model's underlying `MultibodySystem`.  I believe the purpose of a `Manager` is to manage the integration of `Model` dynamics and this was a misuse.

**Comment by chrisdembia** [comment]
It may be good to make sure the same integrator type is used for both systems.

**Comment by aseth1** [comment]
> It may be good to make sure the same integrator type is used for both systems.

I agree, but they are currently not the same 😿.  Hard coded within `VectorFunctionForActuators`:
```cpp
    _integrator = new SimTK::RungeKuttaMersonIntegrator(*aActuatorSystem);
    _integrator->setAccuracy( 5.0e-6 );
    _integrator->setMaximumStepSize(1.0e-3);

    // Don't project constraints while inside the controller
    _integrator->setProjectInterpolatedStates( false );
```
