### ISSUE TITLE
Add outputs on Frame for getting only the translational velocity and acceleration of the origin

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1415]
Frame has outputs `velocity` and `acceleration`, but these are SpatialVecs. This is good to have, but I think it may be helpful to also have output son Frame that give *just* the translational portion of the velocity and acceleration. Otherwise, one needs to add a Point (Station) at the origin of the Frame (PhysicalFrame).

**Comment by tkuchida** [comment]
Specifically requested at TGCS workshop.

**Comment by chrisdembia** [comment]
Thank you for adding that note!
