### ISSUE TITLE
Input::setAlias is not reflected in TableReporter, etc.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1420]
Users can call `AbstractInput::setAlias()` and this will update the alias stored within `AbstractInput`. However, upon connecting, this alias is not obeyed; instead the alias (if any) from the `connectee_name` property is used. Therefore, calls to `setAlias()` will not be reflected in TableReporter's column labels.

The fix is to no longer store aliases as a separate member variable in `AbstractInput::_aliases`. Two solutions:

1. Only store the alias in the connectee_name property. This will be made easier with the `ChannelPath` class I am working on (PR is coming in a few weeks, maybe).
2. Move aliases to Outputs (instead of Inputs).

**Comment by tkuchida** [comment]
Related: #1277

**Comment by jenhicks** [comment]
Let's go with 1. @klshrinidhi could you work on this? Let @aseth1 know if you have questions.

**Comment by chrisdembia** [comment]
I think this should probably wait until my ChannelPath PR (having the connectee_name properties be ComponentPath for Connectors and ChannelPath for Inputs), since that PR would undo any current fix. A current fix would require some unpleasant string-editing (when someone updates an alias, the could would need to append "(<alias>)" to the connectee name, but also check if an alias already exists (probably using parseConnecteeName()). 

Alternatively, @klshrinidhi could take on what I had started with connectee_name being a ChannelPath.

**Comment by chrisdembia** [comment]
This is the branch related to ChannelPath: https://github.com/opensim-org/opensim-core/tree/ComponentPath_property. This branch should be somewhat functional, but is also stale (it's from before the rename to Socket).

I also created another branch that builds upon the one above and has some intermediate code that I do not think works: https://github.com/opensim-org/opensim-core/tree/ComponentPath_property_sandbox.

**Comment by chrisdembia** [comment]
Here's some more background. This issue first came up when adding an example for PR#1340, based on a suggestion by @aymanhab:
![image](https://cloud.githubusercontent.com/assets/846001/22446348/fa04601c-e700-11e6-8d2d-2401bce28ee1.png)

 I wanted the example to use `setAlias()`, and I could not get it to work; here's the comment:
![image](https://cloud.githubusercontent.com/assets/846001/22446283/b4b36ef4-e700-11e6-8068-2973de12a023.png)

Here are the MATLAB/Python examples where I had hoped to show off `setAlias()`:
- https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/examples/wiring_inputs_and_outputs_with_TableReporter.py
- https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/examples/wiringInputsAndOutputsWithTableReporter.m

I think the issue arose because the model is serialized and then deserialized, and the alias is not preserved across that.
