### ISSUE TITLE
The option to "reverse" the sense of a Joint should  be removed

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1424]
**Background**
In 3.3 and earlier versions, we did not have an automatic way of building a Multibody Tree. The tree was defined by the order of Joints and its parent-to-child direction. If the user wanted to reverse the direction of the tree say from the ground up for a leg model (instead of pelvis down), for example, they would re-order the joints and swap the child and parent bodies of each Joint. To maintain the sense of each Joint such that the motion of the distal body was described in the proximal frame, required setting the *reverse* flag to true.

**Current Functionality**
The user-supplied *reverse* flag is unused. Instead the `SimTK::MultibodyGraphMaker` creates an "optimal" tree with consideration of loops, constraints and mass distribution. The user can specify any order of Bodies and Joints and specifies the desired sense of the Joint by choosing its parent and child frames (bodies). The MultibodyGraphMaker therefore determines if a Joint must be reversed to form a viable Tree. This Tree is used to create the MultibodySystem topology.

In SWIG wrapping (for scripting) the option to *reverse* the Joint has already been blocked leading to issues like #1406. Instead of re-exposing the option in SWIG, I would prefer to remove the option from the API, since it is currently a dead option even in C++.

**Repercussions**
There are models where users have used the *reverse* option to create a bottom up model like the leg example above. Ignoring the flag in this case results in having the incorrect sense of the reversed Joints (see #781). The fix is to define the Joint in the desired sense of parent (proximal) to child (distal) and let OpenSim reverse the Joint if necessary, which is likely if the foot is welded to the ground. We could handle this formally by swapping the parent and child frames when updating from XML for any Joint with *reverse* set to *true*.

**Comment by jenhicks** [comment]
I am closing this issue, as it duplicates #611.
