### ISSUE TITLE
Test does not ensure potentially helpful warnings are displayed

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1428]
On [testComponentInterface.cpp L1042](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Test/testComponentInterface.cpp#L1042), the comment "Should yield warnings about unconnected Inputs" is followed by a call to `world.connect();` but there is no check to ensure the warnings are printed. We are unlikely to catch a PR that accidentally removes these warnings. It would be easy to redirect cout to stringstream (see, e.g., [testReportersWithModel.cpp L55](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Test/testReportersWithModel.cpp#L55)) to at least throw an exception if nothing is printed.

**Comment by chrisdembia** [comment]
Indeed those warnings are no longer printed; [they were commented out](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L239). I agree with your general suggested approach. We should also make helper functions that make it easier to capture cout. My opinion about the specific warning you mention is that it should not exist--it is okay for inputs to not be connected, so long as they are never used (their value is never requested).

**Comment by tkuchida** [comment]
> those warnings are no longer printed

Ah, I should have run the test. In that case, the comment on L1042 and the `cout` on L1043 should be deleted so the test reflects the desired functionality. I'll do this.

> it is okay for inputs to not be connected, so long as they are never used (their value is never requested)

Yes, that seems fine.
