### ISSUE TITLE
Decide what format of motion files to support into GUI and Tools

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1433]
GUI and Tools used to store simulation results as States (for example so that muscles can be colored) with short name headers. Now we write headers that contain fullPathName. Is the plan to support both formats for headers or just new "e.g. /model/Joint/coordinate" ?

**Comment by jenhicks** [comment]
First step: try reading motion file into a states trajectory.

**Comment by chrisdembia** [comment]
See [this](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/StatesTrajectory.h#L417) part of the doxygen description for `StatesTrajectory::createFromStatesStorage()`:

> The naming convention for state variables changed in OpenSim v4.0;
     * `ankle_r/ankle_angle_r/speed` used to be `ankle_angle_r_u`,
     * `soleus_r/activation` used to be `soleus_r.activation`, etc. This
     * function can handle %Storage column labels that use the pre-v4.0 naming
     * convention.

**Comment by aymanhab** [comment]
Thanks @chrisdembia I'll give that a try.  Which format do the tools now "save"? or do they use "Aliases" to relabel?

**Comment by chrisdembia** [comment]
The tools should now write the absolute path names for state variables. There is no code that sets aliases in a generic way like that; only example code.
