### ISSUE TITLE
Should it be possible to connect the same output to a list input multiple times?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1445]
Currently, you can do the following (if `input` is a list input).

```
input.connect(outputA);
input.connect(outputA);
```

That is, you can connect the same output to an input multiple times. 

Is this okay? @aseth1 thinks that if a user does this, it's most likely an error. I somewhat agree. But we both also seem to think that there might be valid cases for this (perhaps not for reporting, but for other use cases). 

Another option: only allow duplicate outputs if they have different aliases.

**Comment by aymanhab** [comment]
@chrisdembia This seems quite confusing since a user doesn't know if a new call to connect replaces an older one or appends, what if it's not a list? If the latter, i.e. append, than it should be clear from the name rather than guessed or left to interpretation.

**Comment by chrisdembia** [comment]
Ah good point, @aymanhab . At the very least, the documentation should clarify what happens.
