### ISSUE TITLE
Possibley add exceptions in functions that are not yet implemented

### ISSUE THREAD

**Issue by cpizzolato** [opensim-org/opensim-core#1448]
Despite the clear doxygen comments, it took me a while to realise that `Value<T>::getValueAsString()` is not implemented yet. The confusion also comes from the fact that Visual Studio shows me the doxygen comment of `AbstractValue::getValueAsString()`, which, obviously, doesn't say anything about the implementation of  `Value<T>::getValueAsString()`.

Anyhow, although quite pedantic, do you think it would be a good idea to add an exception in those functions that are not implemented yet? It may help to save some debug time.

Cheers
Claudio

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
