### ISSUE TITLE
attached_geometry ends up under "components" upon deserialization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1450]
While this may not be an issue for the visualization code since it traverses the tree of components regardless, it affects how geometry is displayed in the navigator/GUI.

**Comment by aseth1** [comment]
upon deserialization from 3.0 and early document versions or even in the latest version?

**Comment by aymanhab** [comment]
I've seen it in older files (document number before 3.0) that were included in 3.3 distro. We don't have any saved model in 4.0 format. The issue is likely updateFromXML related so not critical for Alpha as far as I can tell.

**Comment by aseth1** [comment]
This does not seem to be a problem for versionNumber 20303 up. I was able to replicate the problem for version 20001 with Neck3dof_point_constraint.osim in `testModelCopy`.  In `PhysicalFrame::updateFromXMLNode()` there is an `if (versionNumber < 20101) {` which does not correctly update to a 20303 or later model and it does not invoke the `convertDisplayGeometryToGeometryXML` method that creates the the `attached_geometry` list.

**Comment by chrisdembia** [comment]
🕵️  🔍

**Comment by aymanhab** [comment]
Thanks for the investigation @aseth1 It shouldn't be a problem to require users to save their models in version 3.2 or 3.3 to get around that, but then we broke some backward compatibility that was supposedly baked in. Do you think this would be fixable after all the changes we made in 4.0? We should discuss.

**Comment by aseth1** [comment]
Closed by #1469
