### ISSUE TITLE
WrapObject::wrapLine() hidden from SWIG

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1457]
I am working on a MATLAB version of the hopper-device example. Building the hopper model involves adding a WrapCylinder to a model. Right now, the function `wrapLine()` is `ifndef SWIG`'d, making SWIG think that WrapCylinder, etc. are concrete classes and thus preventing me from constructing a WrapCylinder in MATLAB.

Is it okay to expose the `wrapLine()` functions in scripting? I looked at the git history and did not quickly find any answers.

@aymanhab

**Comment by aymanhab** [comment]
The function was hidden long time ago before the parameters were useful (e.g. SimTK::State). That said the method is rather internal and is invoked automatically by GeometryPath::applyWrapObjects during path computation. What's the rationale for exposing it?

**Comment by chrisdembia** [comment]
Ah thanks for explaining. The only reason is to allow users to construct WrapObjects in scripting. Since wrapLine is a pure virtual, if we hide it, then SWIG does not create constructors because it thinks the classes like WrapCylinder are still abstract.

**Comment by aymanhab** [comment]
The fix then is to make the method protected so it's not an issue for swig. If that doesn't work we can tell it explicitly that these classes are noabstract. Let me know what you think @chrisdembia
