### ISSUE TITLE
StaticOptimization output storage files contain incorrect column headers

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#146]
For me, the activation storage file contains columns Right_GRF and Left_GRF, even though these are not muscles: these are the names of the ExternalForce's I have. The bug is here:
https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/StaticOptimization.cpp#L225

Even the force.sto file has the wrong number of columns though. Right_GRF and Left_GRF contain more than one force value. Perhaps the force should only be written for actuators, and the activation should just contain muscle activations.

**Comment by aymanhab** [comment]
Addressed by #546
