### ISSUE TITLE
copyProperty_GeometryPath doesn't work

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1464]
While writing a script to Change Muscle type in python, the copyProperty_* macro generated functions all worked on primitive types but copyProperty_GeometryPath resulted in an empty GeometryPath. This could be pilot error something specific to GeometryPath or generic problem for all Properties that are Objects.

**Comment by aymanhab** [comment]
Using getValueAsObject() on the GeometryPath property doesn't work either and results in an empty GeometryPath.

**Comment by aymanhab** [comment]
This could also be due to PathPointSet, PathWrapSet being Deprecated but the copy methods not implicitly invoked.

**Comment by jenhicks** [comment]
@aymanhab Will continue investigating and report back.

**Comment by jenhicks** [comment]
@aymanhab Can you post a link to the code that produces the isse?

**Comment by aseth1** [comment]
@aymanhab how does this behavior differ from that of cloning the Model with GeometryPaths, which we do routinely?  Is it that we only need/use `copyProperty_GeometryPath` for a custom copy constructor? I could not find any instance in the API where we use `copyProperty_GeometryPath` so it is possible there are issues with it since it is never exercised. Why do you need to explicitly copy the property and not rely on default copy?

**Comment by aymanhab** [comment]
@aseth1 The functionality I'm trying to accomplish here is to copy Properties of similar name between objects of different types as such there's no built in/default copy method to use.
The python script actually uses copyProperty for atomic types and they all work fine.

**Comment by aseth1** [comment]
This approach seems error prone unless you have an automatic way of sweeping through all the properties in the class hierarchy. You still have to manually map from property A in class X to property A in class Y and invoke it by `X.copyProperty_A(Y)` method. How is that easier/better than X.set_A(Y.get_A())?  Can you do this in a more generic way by copying the common elements of the property tables?

**Comment by aymanhab** [comment]
@aseth1 All the Properties in the class hierarchy end up in the flat tables maintained by Object. That's the automatic way to process all properties The current code checks for name and class which is not completely fool-proof but doable. set_A(get_A())  are available only to the level where A is defined. Doing this for each pair of classes out of a group of N results in O(N^2) methods per class

**Comment by aseth1** [comment]
I agree. Copying the common properties in the propertyTable seems like the way to go for generic conversion between different Object types. 

So is there a bug to fix here with `copyProperty_GeometryPath`?

**Comment by aymanhab** [comment]
Nope copyProperty_GeometryPath is completely innocent 👶

**Comment by aseth1** [comment]
Then we should close this issue. Thanks for clarifying!

**Comment by aymanhab** [comment]
Sure, thanks @aseth1 I'll open another one since there's still an issue with the generic approach.
