### ISSUE TITLE
Probe isDisabled flag uses reverse logic

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1471]
In trying to unify treatment of Components that can be disabled/enabled based on a Property in the latest GUI, I ran into the Probe Component which continues to use reverse logic for the enabling property (isDisabled) as opposed to all other components that use affirmativenow (enabled, applies_force, enforce_constraint etc.) it seems that reversing the logic in Probe would be the cleaner solution that makes the API more consistent.

**Comment by jenhicks** [comment]
Change to "enabled"

**Comment by klshrinidhi** [comment]
Addressed by #1479.
