### ISSUE TITLE
Problem with python's DLLs on Windows 10

### ISSUE THREAD

**Issue by kidzik** [opensim-org/opensim-core#1482]
I am trying to run python wrappers on Windows 10 64-bit with conda 4.3.5 and python 2.7.12.
I successfully compiled and installed sdk using
```bash
mkdir opensim_dependencies_build
cd .\opensim_dependencies_build
cmake ..\dependencies^
        -G"Visual Studio 14 2015 Win64"^
        -DCMAKE_INSTALL_PREFIX="%PREFIX%"
cmake --build . --config Release -- /maxcpucount:8
cd ..

mkdir opensim_build
cd .\opensim_build
cmake ..\^
        -G"Visual Studio 14 2015 Win64"^
        -DCMAKE_INSTALL_PREFIX="%PREFIX%"^
        -DOPENSIM_DEPENDENCIES_DIR="%PREFIX%"^
        -DBUILD_PYTHON_WRAPPING=ON^
        -DWITH_BTK=ON
cmake --build . --target install --config Release -- /maxcpucount:8
```
where %PREFIX% is some conda environment ="C:\\Anaconda2\\conda-bld\\_b_env\\"

Next I install python wrappers
```bash
cd sdk/python
python setup.py install
```

When I run python and try to import opensim
`python -c "import opensim"`
I'm getting
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "opensim\__init__.py", line 1, in <module>
    from simbody import *
  File "opensim\simbody.py", line 21, in <module>
    _simbody = swig_import_helper()
  File "opensim\simbody.py", line 20, in swig_import_helper
    return importlib.import_module('_simbody')
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _simbody
```
So it can't find pyds, which is ok, this I can fix. But when I have pyds in the same folder and it can find it, I'm getting another error which I am unable to solve:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\opensim\__init__.py", line 1, in <module>
    from simbody import *
  File "C:\Anaconda2\lib\site-packages\opensim\simbody.py", line 21, in <module>
    _simbody = swig_import_helper()
  File "C:\Anaconda2\lib\site-packages\opensim\simbody.py", line 20, in swig_import_helper
    return importlib.import_module('_simbody')
  File "C:\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: DLL load failed: The specified module could not be found.
```
From what I found on stackoverflow it seems that the DLLs that '_simbody' is referring may be compiled for some older Windows and linking breaks. I don't know where to look for such errors. http://www.dependencywalker.com/ shows that almost all links are broken (kernel32.dll, vcruntime140.dll, mvcp140.dll, etc.) but I have them all in recent versions. I am not sure how reliable dependencywalker is.

I am trying to build a conda package https://github.com/kidzik/conda-opensim - everything works well on Mac and Linux.

Thanks!

**Comment by chrisdembia** [comment]
Two possibilities come to mind:
- You are using 32bit python instead of 64bit python
- The PATH environment variable does not contain the path to the OpeSim DLLs like `osimCommon.dll`.

**Comment by kidzik** [comment]
Thanks! Adding directory with DLLs to PATH solved the issue.

**Comment by chrisdembia** [comment]
Ah great. I think it would be good for conda to manage things like that for you. Were you in a virtual environment? If so, conda could update PATH to include the virtualenv's bin dir. I would think this is an issue for any python package that depends on DLLS (maybe PyQt).

**Comment by kidzik** [comment]
They actually give clear guidance where to put things
http://conda.pydata.org/docs/building/environment-vars.html
When, on windows, I use %LIBRARY_PREFIX% as the destination instead of just %PREFIX% everything works well without modifying path (since %LIBRARY_PREFIX%\\bin\\ is already on PATH). It probably still suboptimal to put everything there but it works for now. I will look into details later.

**Comment by chrisdembia** [comment]
Oh I think you probably *do* want to install the OpenSim binaries into %LIBRARY_PREFIX%.

**Comment by Aleph-Zero0** [comment]
> Thanks! Adding directory with DLLs to PATH solved the issue.

Hello, I am having similar issue, but I am not using conda environment
When I try to import opensim I get

```
Traceback (most recent call last):
File "<script_dir>\CMC_Run.py", line 3, in <module>
    import opensim as osim
File "C:\OpenSim 4.4\sdk\Python\opensim\__init__.py", line 9, in <module>
    from .simbody import *
File "C:\OpenSim 4.4\sdk\Python\opensim\simbody.py", line 13, in <module>
    from . import _simbody
ImportError: DLL load failed while importing _simbody: The specified module could not be found.
```

Can you specify which folder path I must include in which env. variable?
I am using OpenSim 4.4 and Python 3.9.13
