### ISSUE TITLE
Copying properties from an Object to another Object fails

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1488]
This is related to the discussion in PR #1460 a straightforward implementation that cycles through Properties and copy values if they match name and class fails for GeometryPath

**Comment by jenhicks** [comment]
@aseth1 will investigate source of bug

**Comment by aseth1** [comment]
I was looking into and was able to distill it to the `Property` assignment:
```cpp
        {
            Property<double>* a = Property<double>::TypeHelper::create("a", true);
            a->setValue(0.123456789);
            Property<double>* b = Property<double>::TypeHelper::create("b", true);
            b->setValue(10.0);

            *b = *a;

            cout << "b = " << b->toString() << endl;
            ASSERT(*a == *b);
        }
```
The ASSERT fails because Property `b` is not assigned to the property value(s) of `a` (although the property name is updated). 
Thanks @klshrinidhi for taking a look.

**Comment by klshrinidhi** [comment]
I will get back soon on what is going on.

**Comment by jenhicks** [comment]
Will merge this PR and then revisit script in #1460

**Comment by jenhicks** [comment]
@aymanhab Would you like to test out the script again before the API beta or can I move this to the backlog?

**Comment by aymanhab** [comment]
I'd move it to backlog. To set my environment to master in order to write/test the new script doesn't seem practical at the moment. Thank you.

**Comment by jenhicks** [comment]
Related #1542
