### ISSUE TITLE
Serialize trajectories of States in their exact and complete form

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#149]
Includes discrete state variables but not cached variables. A States trajectory must be tied to a model.
It shouldn't be easily human readable (e.g. zipped) and not bound by model name but by other unique key. It would also be handy if it maintained the version of OpenSim used to generate the States as well. Party addresses issue raised in #104 for robust post-hoc analysis of a simulation result.

**Comment by chrisdembia** [comment]
Just found this binary format MessagePack: https://github.com/msgpack/msgpack/blob/master/spec.md#formats-array
