### ISSUE TITLE
Hopper example no longer hops

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1494]
Step 3 in exampleHopperDevice_answers.cpp should show the hopper hopping.

**Comment by chrisdembia** [comment]
I have fixed this in the branch we are using to prepare for TGCS. I will file a PR eventually.

**Comment by chrisdembia** [comment]
The issue is that the device no longer wraps around the patella, because the path to the patella wrap surface has changed.

**Comment by chrisdembia** [comment]
Still an issue!

**Comment by chrisdembia** [comment]
Tom, would you be able to test the fix, once I create a PR?
