### ISSUE TITLE
Component renaming could be simplified

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1497]
### Current design AIUI

Connectivity is represented in two forms: the `connectee_name` property and a reference from child to parent that is set based on the `connectee_name` string when `finalizeConnections()` is called. When a Component :panda_face: is renamed, the `connectee_name` string of all Components connected to :panda_face: becomes obsolete and must be updated (e.g., by calling `connect()`); otherwise, a connection failure (e.g., unable to find Component named "oldName") will occur downstream.

### Proposed changes

In the short term:
1. Create a `Component::rename()` method that calls `setName()` on self and updates all `connectee_name`s that refer to it.
2. If `Component::setName()` is called after connecting, perhaps display a warning that connections with other Components may break and suggest using `Component::rename()` instead.

In the long term, something like #1192 might be helpful to separate names from connectivity.

### Related

#1199

**Comment by aymanhab** [comment]
Doesn't seem on critical path for 4.0, except if it turns out GUI needs functionality for model renaming support, will address then per @aseth1
