### ISSUE TITLE
Remove dependency on OPENSIM_HOME

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1498]
ModelVisualizer and Geometry use OPENSIM_HOME and a hard coded set of directories to search for mesh files, and it may have been used to locate other resources. Windows machines with older installations will have this set incorrectly and the environment variables mechanism is not cross platform. Would be good to abstract the search paths into a class that maintain a list of directories with the ability to add to the list os that the GUI can decide where to pull these resources and same for other programs/visualizer.

**Comment by chrisdembia** [comment]
+1; I think we have to add this to the 4.0 list.

**Comment by jenhicks** [comment]
Maintain a list of directories to search for geometry files and GUIs and Visualizers will be customizers of the list.

**Comment by jenhicks** [comment]
Use Carmichael's Path class
@aymanhab can point to places where hard coded path is being used

**Comment by aymanhab** [comment]
Geometry.cpp has a call to ModelVisualizer::findGeometryFile that populates passed in search paths using hard coded list of options described in doxygen, there's no API to modify these search paths so that a client (e.g. the GUI) can add directories to search. This is a problem because the actual search paths have to be found on client machine after installation or could be user specified. Either abstract searchPath into a class and allow it to be passed in, or give option to provide additional search paths.

**Comment by aymanhab** [comment]
Issue related to Geometry location was fixed in #1560, separate issue is open for locating visualizer executable #1572
