### ISSUE TITLE
Create a new "osimExampleComponents" library, and put PropMyoController and Device classes in it.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1501]

**Comment by chrisdembia** [comment]
@klshrinidhi please see the tgcs2017 branch before working on this. In particular, see this file: https://github.com/opensim-org/opensim-core/blob/f23ad6fccdf7d0f9e256ff0d2413f3e76be1e93b/OpenSim/Simulation/Control/ToyPropMyoController.h

**Comment by tkuchida** [comment]
Fixed by #1557
