### ISSUE TITLE
Component::printSubcomponentInfo(), printSocketInfo(), printInputInfo(), printOutputInfo()

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1503]

**Comment by tkuchida** [comment]
There might be some useful code in ExampleHopperDevice/helperMethods.h:
- [`showSubcomponentInfo()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleHopperDevice/helperMethods.h#L37)
- [`showAllOutputs()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleHopperDevice/helperMethods.h#L49)

**Comment by chrisdembia** [comment]
I should have filled out the issue better...yes, I plan on using those functions, which have very nice output.

**Comment by aseth1** [comment]
My preference *print* instead of *dump* and also like having the option to print to a user specified stream. Any other opinions?

**Comment by chrisdembia** [comment]
@klshrinidhi please look at Component.h in the tgcs2017 branch as a starting point.

**Comment by chrisdembia** [comment]
In the tgcs2017 branch, I already started moving the methods that @tkuchida mentions.

**Comment by tkuchida** [comment]
> Any other opinions?

Recursive vs. non-recursive? Show types?
