### ISSUE TITLE
Issues with Integrating Frames into Model

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#153]
1. When to create BodyFrame(s) for all Bodies in the model?
   - Can't rely on deserialization since Bodies can be added programmatically. 
     -> Should serialization call addBody so there's only one path to modify/test/maintain in the code?
   - How to handle Body renames (connection of BodyFrame to Body is thru a body connector that references a body by name, keeping the name in multiple places can lead to inconsistency.
2. How to Handle Body removal/deletions (can we get a list of all objects connected to Body, so as to signal them as "disconnected")? how to get a list of all downstream objects (recursively)

**Comment by aymanhab** [comment]
Any reason why not to close this one, @aseth1 ?

**Comment by aseth1** [comment]
>Any reason why not to close this one,

Nope. Closing!
