### ISSUE TITLE
InverseDynamicsSolver.h is not included in osimSimulation.h

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1538]
The headers `InverseDynamicsSolver.h` and `InverseKinematicsSolver.h` are not included in `osimSimulation.h`. There may be more that are not included as well. The consequence is that simply including `<OpenSim/OpenSim.h>` is not sufficient to use these classes.

**Comment by aymanhab** [comment]
Good find @chrisdembia Feel free to add them in. Would be great to auto-find these in the future.

**Comment by chrisdembia** [comment]
Thanks @aymanhab; I've created PR #1544.
