### ISSUE TITLE
Bindings: Cannot edit curves for Millard2012EquilibriumMuscle

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1541]
The bindings put the Millard2012EquilibriumMuscle in the [simulation module](https://github.com/opensim-org/opensim-core/blob/master/Bindings/simulation.i#L237), but some of the classes that are used by the MIllard2012EquilibriumMuscle are still wrapped in the [actuators module](https://github.com/opensim-org/opensim-core/blob/master/Bindings/actuators.i) (e.g., TendonForceLengthCurve). Therefore, it is not possible to edit the Millard curves from bindings. We could move more of classes (e.g., TendonForceLengthCurve) from the actuators module to the simulation module, but then the benefit of having a separate actuators module is reduced.

**Comment by chrisdembia** [comment]
Discovered by @nickbianco

**Comment by jenhicks** [comment]
Is this a new issue in 4.0 or did it exist in previous releases, as well?

**Comment by chrisdembia** [comment]
This is a new issue; I just checked and verified that 3.3 python bindings provided access to the TendonForceLengthCurve class.

**Comment by jenhicks** [comment]
@nickbianco : @chrisdembia mentioned you have a PR that solves the issues. Can you submit the PR?
