### ISSUE TITLE
Model::printBasicInfo() and printDetailedInfo() do not account for components added via addComponent()

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1551]
The model has some utility functions for printing information about the model, such as the number of joints. However, if a joint was added to the model via `Component::addComponent()`, then it is not accounted for in the output of `printBasicInfo()`, etc.

**Comment by tkuchida** [comment]
Should we be deprecating any/all of the Model::add:cow: methods, where :cow: = {ModelComponent, Body, Marker, Joint, Constraint, Force, Probe, ContactGeometry, Controller}? Stated another way, how does a user decide whether to add a Joint to a Model via `Model::addJoint()` or `Model::addComponent()`? AFAIK, both work now. Perhaps `Model::addJoint()` should just call `Model::addComponent()` under the hood, in which case Model::print:turtle:Info() can be revised to just search through the subcomponent lists.

**Comment by aseth1** [comment]
> in which case Model::print🐢Info() can be revised to just search through the subcomponent lists.

Good idea! All components are in included its `ComponenList` (regardless of the containing property), so we could make this update without any other changes.
