### ISSUE TITLE
Display preference for wrap objects is not remembered

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1553]
This issue is related to https://github.com/opensim-org/opensim-gui/issues/87: a model will display its wrap surfaces even if a v3.3 model file says it's not supposed to display a wrap surface. This might be because the `display_geometry` property of wrap objects is not being used in `updateFromXML()`?

**Comment by jenhicks** [comment]
Still need to determine whether this is an API or GUI issue. Do properties show up correctly in the Properties panel in the GUI when the model is loaded?

**Comment by chrisdembia** [comment]
I looked into this by looking at the Properties panel, and this is an API issue. The `Gastroc_at_condyles_r` should be hidden:

![image](https://cloud.githubusercontent.com/assets/846001/23843461/2a1bf86c-0779-11e7-9c24-8455f0cffc91.png)

but the Properties panel says it is visible:

![image](https://cloud.githubusercontent.com/assets/846001/23843469/3d3f612c-0779-11e7-930b-c8e08bedd473.png)

This might *also* be a GUI issue, since I am so far unable to hide a wrap surface within the GUI (toggling the "visible" flag for a WrapObject's appearance).

**Comment by chrisdembia** [comment]
WrapObject does not have any `updateFromXMLNode()` code, even though its properties have changed since 3.3: WrapObject used to have the following properties `VisibleObject`, `display_preference`, `color`.

**Comment by chrisdembia** [comment]
@aymanhab @aseth1 since both of you have worked on WrapObject since 3.3, please let me know if you have any insights. I can carve out time to add the necessary `updateFromXMLNode()`.

**Comment by aymanhab** [comment]
@aseth1 will review
