### ISSUE TITLE
MacOS RPATH for osimJavaJNI (and maybe other osim libraries) is absolute, but should be relative

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1554]
The RPATH for the osimJavaJNI is an absolute path, but should be a relative path in order make the (GUI) installation relocatable.

Relative RPATHs for the python dylibs is maybe not a good idea, since these shared libraries are usually copied into the python packages directory, therefore rendering a relative path incorrect. Perhaps the step of installing the python package on macOS should include editing the RPATH using `install_name_tool`.

**Comment by chrisdembia** [comment]
While #1573 largely addresses this issue, it does not handle the case where WITH_BTK is ON. So even if #1573 is merged, we should not yet close this issue.

**Comment by jenhicks** [comment]
Maybe fixed, @aymanhab will test

**Comment by chrisdembia** [comment]
Given that the fact that the GUI worked on Macs at ISB, I think we can close this issue.
