### ISSUE TITLE
Make osimJavaJNI loadLibrary message platform-dependent.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1555]
The Java exception/error for failing to find the OpenSim shared libraries is tailored toward Windows (it mentions the PATH environment variable, but not LD_LIBRARY_PATH or DYLD_LIBRARY_PATH) (https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/swig/java_common.i#L189). It would be great to update this error message to be more accurate for platforms like macOS and linux.

**Comment by aymanhab** [comment]
@chrisdembia thinks can be addressed but not critical to 4.0 Beta
