### ISSUE TITLE
Create a method that returns simple, informative data type

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1558]
**Example:** If given `"SimTK::Vec<2,SimTK::Vec<3,double,1>,1>"`, returns `"SpatialVec"`.

See [issue 73 in GUI repo](https://github.com/opensim-org/opensim-gui/issues/73) and [Component::printOutputInfo()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L1552).

**Comment by jenhicks** [comment]
@chrisdembia has a proposal for a few line solution. Will see if this works, otherwise postpone.

**Comment by tkuchida** [comment]
@klshrinidhi: see [Object_GetClassName](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Object.h#L1081) and getClassName().

**Comment by chrisdembia** [comment]
@tkuchida would you say this could be closed?

**Comment by tkuchida** [comment]
> @tkuchida would you say this could be closed?

Yes (fixed by #1562).
