### ISSUE TITLE
Allow easy integration of Model state in Matlab

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#156]
In version 3.2, users could instantiate a Manager(model) from Matlab and then integrate forward using a default integrator with minimal overhead. This functionality has been removed in master branch while refactoring the code. Either we need to restore this functionality to Manager or provide an easy alternative that doesn't involve the Manager class altogether.

**Comment by chrisdembia** [comment]
Use unique_ptr and swap.
