### ISSUE TITLE
Add/remove columns from a DataTable

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1578]
In my current research project, I find myself wanting to remove or add columns from a DataTable. For example, I might load a csv file of all states, and then want to create a table with only joint angles, and so I would want to load the csv file and remove all columns that aren't joint angles. Or, create a new table and add the columns that are the joint angles.

**Comment by aymanhab** [comment]
@chrisdembia I find myself with similar needs in the GUI. Ideally there would be some sort of annotation maintained with the datatable that says what's what (e.g. Columns 1-5 Coordinates, 7-20 Muscle states etc.) in cases where we create the files that are read into datatables at least this should be possible I think.

**Comment by chrisdembia** [comment]
We could have `StatesTrajectory::exportTable()` add those annotations.

**Comment by klshrinidhi** [comment]
As per discussion with Ajay & James, I will add `addColumn` function to `DataTable`.

**Comment by chrisdembia** [comment]
Awesome :) Would `appendColumn()` be more consistent with `appendRow()`, or is there a difference between the two that we would want to signal by using `add` instead?
