### ISSUE TITLE
Cryptic exception message if finalizeFromProperties() called after initSystem()

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1584]
To reproduce:
```cpp
#include <OpenSim/OpenSim.h>
using namespace SimTK;
using namespace OpenSim;

int main() {
    try {
        auto model = Model("gait10dof18musc.osim");
        auto state = model.initSystem();
        //model.finalizeFromProperties(); //frog
        RungeKuttaMersonIntegrator integrator(model.getSystem());
        Manager manager(model, integrator);
        state.setTime(0.);
        manager.integrate(state, 1.);
    } catch (const std::exception& ex) {
        std::cout << ex.what() << std::endl;
        return 1;
    }
    return 0;
}
```
When :frog: is uncommented, the following exception message is reported:
<pre>
SimTK Exception thrown at Integrator.cpp:431:
  Integrator initialization failed apparently because:
Component::isCacheVariableValid: ERR- name not found.
 for component 'geometrypath_' of type GeometryPath
</pre>
Although this example may seem contrived, it was discovered in a "real world" situation in testWrapping.cpp (`simulateModelWithMusclesNoViz()`), where `Model::printBasicInfo()` was being called after `Model::initSystem()` (and `printBasicInfo()` must now be preceded by `finalizeFromProperties()` due to #1582).

There are at least two possible resolutions:
1. Make `Model::finalizeFromProperties()` "harmless" if the model hasn't changed. In the example above, `initSystem()` had just been called, so it doesn't seem like `finalizeFromProperties()` should do much of anything. If that's not possible, then…
2. Catch the exception from Integrator and provide a more user-friendly message that indicates what went wrong and how the problem might be fixed.

**Comment by aseth1** [comment]
I disagree that calling `finalizeFromProperties` after `initSystem` should be "harmless" in the sense that it does nothing. It is like calling *realizeTopology* after *realizeDynamics*, we wouldn't expect the dynamics cache variable in the `State` to remain valid, and they are not accessible.

After a call `initSystem` there should be no reason to call `finalizeFromProperties` to permit `printBasicInfo`.

**Comment by tkuchida** [comment]
> I disagree that calling `finalizeFromProperties` after `initSystem` should be "harmless" in the sense that it does nothing. It is like calling *realizeTopology* after *realizeDynamics*, we wouldn't expect the dynamics cache variable in the `State` to remain valid, and they are not accessible.

With my "user hat" :tophat: on, my thinking was that if the Model is already up-to-date with its properties, then `finalizeFromProperties` has nothing to do and nothing should change.

> After a call to `initSystem` there should be no reason to call `finalizeFromProperties` to permit `printBasicInfo`.

#1582 introduces the requirement that `isObjectUpToDateWithProperties()` must be true before calling `printBasicInfo()`. Here's the result if :frog: is replaced with `model.printBasicInfo();` in the example above with the changes in #1582:
<pre>
Model::finalizeFromProperties() must be called first.
        In object 'gait10dof18musc.osim' of type Model.
        In file C:\Users\tkuchida\Documents\opensim-core\OpenSim\Simulation\Model\Model.cpp:1477
        In function 'printBasicInfo'
</pre>
That's why I tried calling `finalizeFromProperties()`. Why isn't `isObjectUpToDateWithProperties()` true after calling `initSystem()`?

**Comment by aseth1** [comment]
> Why isn't isObjectUpToDateWithProperties() true after calling initSystem()?

That's the crux of the issue. You are absolutely right- that's a high-priority bug.

**Comment by chrisdembia** [comment]
I could imagine that any component might modify properties during `extendAddToSystem()`. We should add a check in `testComponents()` to make sure that everything is up to date after initSystem().

**Comment by tkuchida** [comment]
Thanks for investigating. I've opened #1587 to track the `initSystem()` bug; the exception message issue described above isn't critical.
