### ISSUE TITLE
Revisit using SWIG rename facility to expose commonly used operators

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1586]
In #1581 a fixed set of template operator* implementations are specialized and exposed as a `Rotation::multiply()` method available through scripting. It may be possible to use SWIG's `rename` facility to rename all (or a swath of) `operator*` methods on C++ to `multiply()` in wrapping. That would be a more generic way that would require less maintenance as pointed out by @aymanhab.

@chrisdembia added: 
> See here for examples: https://scion.duhs.duke.edu/vespa/gamma/wiki/SwigOperatorRenaming.
>http://www.swig.org/Doc2.0/SWIG.html#SWIG_rename_ignore

> I vaguely remember looking into exposing more operators in the bindings, and my recollection was that Simbody's templating of the operators in a lot of cases was too complex for SWIG to handle.
—

**Comment by aymanhab** [comment]
Will create issue to cleanup swig wrapping to remove dead/unused "proxy" classes and fold this in.
