### ISSUE TITLE
Clean up "unwrapped" SWIGTYPE_p classes.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1590]
The Java bindings show that there are lots of new "SWIGTYPE_p" classes; we should try to eliminate these.

**Comment by aymanhab** [comment]
As of Alpha release of the API there are 113 such classes.

**Comment by chrisdembia** [comment]
I had suggested delaying this but I now realize that examining these classes can reveal bugs we introduced into the bindings when the bindings were split up into multiple modules. See #1764 for an example.
