### ISSUE TITLE
Add a DataTable::setRow(), for bindings

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1591]
Right now, it is not possible to use `updRow()` (?) to set a row in MATLAB. So it would be nice to have a `updRow()`. Reported by @jimmyDunne .

**Comment by klshrinidhi** [comment]
Will get back on this.

**Comment by tkuchida** [comment]
Is there a reasonable workaround or is this Issue on the critical path to release?

**Comment by chrisdembia** [comment]
Perhaps this feature needs to be tested in MATLAB in order to close this issue. It seems to already be tested in Java; I wonder if that's enough.

**Comment by aseth1** [comment]
> Perhaps this feature needs to be tested in MATLAB  ...

That's what I was looking for. In reviewing #1434 I was able to run the scripts that executed `setRowAtIndex` without any issue. My impression is that @jimmyDunne can and is using this wrapped method in MATLAB. If that is the case, @jimmyDunne please confirm and then close. Thanks!

**Comment by jimmyDunne** [comment]
Hey, Guys-
Tested setRow() this morning. It is working! 🍾 

Thanks!!!
