### ISSUE TITLE
Right now, users *must* override constructProperties, etc.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#160]
constructInfrastructure calls the virtual construct(Properties, ...) methods. I have a class that has structural connectors but *not* properties. So, when I call constructInfrastructure in my constructor, I get this error:

```
what():  PropertyTable::adoptProperty(): Property isDisabled already in table.
```

This is because I am invoking my parent's constructProperties. My parent *already* called its own constructProperties in its constructor. So, now I need to override constructProperties and give it a blank definition, or not call constructInfrastructure.

**Comment by jenhicks** [comment]
Related to #200

**Comment by jenhicks** [comment]
Would be made obsolete with use of initializer. Will see if we can get it in for 4.0

**Comment by jenhicks** [comment]
@chrisdembia Can I close this issue?

**Comment by aseth1** [comment]
Yes. `constructInfrastructure` no longer exists and `constructProperties` is not virtual.
