### ISSUE TITLE
Support importing a model from URDF

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1604]
Roboticists use the URDF file format for robot models. If we are interested in getting the robotics community to use OpenSim, it would be great if we could import URDF files. Simbody has a URDF reader, which it uses to simulate the ATLAS robot.

**Comment by tkuchida** [comment]
[simbody/URDFReader.h](https://github.com/simbody/simbody/blob/master/examples/TaskSpaceControl-Atlas/URDFReader.h)
[simbody/URDFReader.cpp](https://github.com/simbody/simbody/blob/master/examples/TaskSpaceControl-Atlas/URDFReader.cpp)
