### ISSUE TITLE
Using ClutchedPathSpring() out of box does not work

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#1607]
This can be seen in the hopper example by trying to use a `CluthedPathSpring()` in place of the `PathActuator()` at this [line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleHopperDevice/buildDeviceModel_answers.cpp#L112). This is  because the `stiffness` and `dissipation` parameters are set to `nan` when using the constructor without any arguments.

This also leads to different behavior in Release and Debug builds (at least on a Windows x64 build). Using a Release build, the hopper model will "disappear" after the first frame, and the reporter will return "nan"s for the height and knee angle. Using a Debug build, the simulation will crash, returning an error related to the integrator.

**Comment by chrisdembia** [comment]
This behavior is consistent with `PathSpring` (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/PathSpring.cpp) and `CoordinateLimitForce` (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/CoordinateLimitForce.cpp).

At the least, we should document this ("Users must set the properties, as the defaults are NaN.").

**Comment by tkuchida** [comment]
@carmichaelong will address. `ClutchedPathSpring::extendFinalizeFromProperties()` should check that all properties have suitable values and throw an exception if they don't. See, for example, [`Millard2012EquilibriumMuscle::extendFinalizeFromProperties()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L109). Also see the description for `extendFinalizeFromProperties()` introduced in PR #1585.

**Comment by chrisdembia** [comment]
Sorry for having listed `CoordinateLimitForce`; I was looking at `setNull()` by accident.

**Comment by carmichaelong** [comment]
No worries. It was quick to double check!

**Comment by tkuchida** [comment]
Fixed by #1614.
