### ISSUE TITLE
Socket<C>::findAndConnect() should always display message when ComponentNotFoundOnSpecifiedPath

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1609]
It seems that the user should be notified if `ComponentNotFoundOnSpecifiedPath` is thrown by `Socket<C>::findAndConnect()`, even though the error may be recoverable. In particular, perhaps we should uncomment [Component.h#L2936](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L2936):
```cpp
...
catch (const ComponentNotFoundOnSpecifiedPath&) {
    // TODO leave out for hackathon std::cout << ex.getMessage() << std::endl;
    comp = root.template findComponent<C>(path.toString());
}
```
(though we should ensure that our favorite models load without reporting an unreasonable number of these messages).

### Update (September 6, 2017)
`Socket<C>::findAndConnect()` currently shows message only if `Object::getDebugLevel() > 0`. Comment in code: "once we fix how connections are established when building models programmatically, we should show this warning even for debug level 0."

**Comment by jenhicks** [comment]
Need to delete or update the comment

**Comment by jenhicks** [comment]
Leaning towards deleting the comment.

**Comment by tkuchida** [comment]
Simplest solution may be to keep commented out for the beta (but remove mention of hackathon) and re-introduce pre-release if deemed necessary.
