### ISSUE TITLE
In MATLAB on Windows, cout is not sent to the Command Window

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1612]
OpenSim methods often spew out useful text, but this text does not appear in the MATLAB Command Window; this behavior might surprise users. For example, calling `Component::printOutputInfo()` would logically display its output in the MATLAB Command Window, but the current behavior is that such output only appears in the `out.log` file. 

This was noted by @carmichaelong and @nickbianco while working on the TGCS example. 

From MATLAB Central (https://www.mathworks.com/matlabcentral/answers/102200-how-can-i-capture-stdout-of-a-generic-shared-library-method-called-from-matlab): 

> Anything printed to standard output (stdout) or standard error (stderr) is lost when a Windows program is running without a console.

Also, the behavior may depend on compatibility between the C runtime library used for MATLAB and OpenSim: 

> If the library is linked with (built with?) the same or a compatible version of the Microsoft C run-time libraries as MATLAB then you should not need this fix and stdout should be automatically redirected to MATLAB.

We can't rely on such compatibility, since we can't compile OpenSim separately for every possible version of MATLAB our users may have.

One workaround for TGCS is to tell users to just open the out.log file in MATLAB. This is what @carmichaelong has been doing.

Other relevant links:

- https://www.mathworks.com/matlabcentral/newsreader/view_thread/15323
- https://www.mathworks.com/matlabcentral/answers/132527-in-mex-files-where-does-output-to-stdout-and-stderr-go
- https://github.com/acado/acado/issues/145
- http://stackoverflow.com/questions/25417792/how-to-call-system-out-println-from-c-via-jni
- http://stackoverflow.com/questions/2328090/getting-text-data-from-c-using-jni-through-stdostream-into-java

**Comment by chrisdembia** [comment]
@aymanhab does the GUI do anything special to get cout to print to the Messages pane in the GUI?

**Comment by aymanhab** [comment]
@chrisdembia The GUI doesn't do anything special. I vaguely remember (from at least 10 yrs ago) that we created a logger to be accessed from both C++ and Java since streams were not portable cross language. If you look for "logger" you may find some clues if that code is still around :confused:

**Comment by carmichaelong** [comment]
On Windows, using a python IDE, output is also sent to out.log rather than command windows. Seen during advanced user workshop.

**Comment by chrisdembia** [comment]
@nickbianco mentioned that the following code may help:

```
std::cout.rdbuf(LogManager::cout.rdbuf());
std::cerr.rdbuf(LogManager::cerr.rdbuf());
```

It's helped us in Moco (in C++; not tested in Matlab).

**Comment by aymanhab** [comment]
This should be closed by the new logging feature (spdlog), any reason not to close, @chrisdembia, @nickbianco?
