### ISSUE TITLE
registerType for Connector<T>

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#162]
When a user adds Connectors, they need to ensure they add corresponding registerType(Connector<T>()) calls to the correct `*DLL.h` files. Is this / will this be documented somewhere?

See this line in the component interface test case: https://github.com/opensim-org/opensim-core/blob/9c554c80b25c3f25759b345943a397735bd48aa5/OpenSim/Common/Test/testComponentInterface.cpp#L387

**Comment by jenhicks** [comment]
This one is very old. Did it ever get documented @chrisdembia @aseth1 ?
