### ISSUE TITLE
WrapObjects are not attached to correct frame for visualization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1634]
WrapObject's generateDecorations method places and computes the geometry relative to Ground. While this works if recreating the scene from scratch for every frame (As used in API visualizer) this construct wrong scene graph that results in wrap objects not moving with the Frames/Bodies they are attached to.
![opensim_snapshot 16](https://cloud.githubusercontent.com/assets/3972208/24633716/bdc7f640-187e-11e7-935c-dfe871187791.jpg)

**Comment by jenhicks** [comment]
Need to fix bug, update documentation, update test case to catch this bug. Review other objects that use generateDecorations to make sure they don't create the same issue.
