### ISSUE TITLE
Assembly of unprescribed coordinates unduly affected by PrescribedMotion of other coordinates 

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1636]
Reported by Zach Lerner at the workshop.

**Comment by jenhicks** [comment]
Potentially a bug. Need to follow up with Zach to get model

**Comment by aseth1** [comment]
From Zach:

>Here’s a zipped folder containing everything that should replicate the assembly error. Run “Test_for_Ajay.m”
>I’ve been meaning to try this with a model that does not include the patellas, even though those coordinates are skipped in “prescribeMotion.m”. 

[Assemble_Error.zip](https://github.com/opensim-org/opensim-core/files/900849/Assemble_Error.zip)

**Comment by aseth1** [comment]
Investigating this is on my TODO when I return, buy to if anyone @opensim-org/dev-team what to take a look, please do. If it isn't user/interface error, then my hunch is that it may be how the assembly goals are specified. Specifically, any prescribed coordinates should be excluded and perhaps they are not.

**Comment by jenhicks** [comment]
@aseth1 Couldn't reproduce in 4.0. Will test in 3.3

**Comment by tkuchida** [comment]
Moved to opensim32 repo [here](https://github.com/opensim-org/opensim32/issues/84).
