### ISSUE TITLE
Enable prescribing motions from a file

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1647]
Can do this via a script. Would be nice to better integrate

**Comment by chrisdembia** [comment]
The issue is that prescribed motion lives in the model, and the trajectory is presented as a really long value for an XML element. One potential interface is to provide a STO file of coordinate values to the tools, and the tools use the STO file to add prescribed motion to the model.

**Comment by chrisdembia** [comment]
Someone on the forums recently requested this feature: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=8045&p=21652
