### ISSUE TITLE
Provide a useful message when mobilities are coincident

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1648]
Reported at March 2017 workshop

**Comment by tkuchida** [comment]
Do you mean *when a model has redundant degrees of freedom* (topology dependent), or does this issue have to do with configuration (pose dependent)?

**Comment by jenhicks** [comment]
Good question. I'm not sure -- I transcribed from the whiteboard.

**Comment by chrisdembia** [comment]
This was an issue for the bicycle model. It would also be an issue for a four-bar linkage.

**Comment by tkuchida** [comment]
Seems to be related to #337, which advocates for a "formal error checking mechanism that makes sure all enabled degrees of freedom are actuated." A preprocessor that catches (and helps users fix) common modeling errors would be great.

**Comment by tkuchida** [comment]
Possibly related: #1716
