### ISSUE TITLE
Document how to create an OpenSim Vector in Python

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1655]
And if time permits, could create a utility similar to the Matlab one.

**Comment by chrisdembia** [comment]
See https://github.com/opensim-org/opensim-core/pull/459 for some sample documentation.

**Comment by chrisdembia** [comment]
I've added some documentation to http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Scripting+in+Python. 

(I know the following does not belong in this issue) I still need to add documentation of accessing subcomponents (and to mention that safeDownCast is often not necessary in Python), and using sockets/inputs/outputs. I also want to make an "example" version of the DataTable test.

**Comment by chrisdembia** [comment]
I think we can close this issue:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/846001/46694570-15860a00-cbc2-11e8-9746-27dd82178030.png">
