### ISSUE TITLE
InverseKinematicsTool leaves a stale KinematicsReporter in the Model post run

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1656]
InverseKinematicsTool  adds a KinematicsReporter for its internal working but doesn't remove it when done. This causes problems downstream since the reporter is created on the stack, once out of scope it's a 💣 waiting to explode.

**Comment by tkuchida** [comment]
:boom: likely occurring in #1632 (see posts 15 and 16).

**Comment by tkuchida** [comment]
Fixed by #1657
