### ISSUE TITLE
Manipulation of GeometryPath to insert/delete/changeType of PathPoints is broken

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1670]
OpenSimContext.addPathPoint() throws exception
java.lang.RuntimeException: PathPoint::getSystem() muscle1-P2 has no reference to a System.
Make sure you added the Component to the Model and called Model::initSystem(). 

OpenSimContext.deletePathPoint() crashes 

OpenSimContext.replacePathPoint(..)  throws exception
java.lang.RuntimeException: Failed to connect Socket 'coordinate' of type Coordinate (details: Model'leg6dof9musc'::findComponent() cannot find a nameless subcomponent.).
	In object 'default' of type ConditionalPathPoint.
	In file D:\src\opensim-core\OpenSim\Common\Component.cpp:236
	In function 'finalizeConnections'
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.OpenSimContext_replacePathPoint(Native Method)

**Comment by aseth1** [comment]
Please supply some test cases and I will investigate. I assumed `testContext` was testing functions used by the GUI. It looks like `testContext` is not sufficient.

**Comment by aymanhab** [comment]
Created branch fix_path_manipulation_from_OpenSimContext to exercise PathPoint deletion that should fail testContext test case. Will add remaining calls after this one is fixed.

**Comment by aymanhab** [comment]
Thanks @aseth1 PR #1681 includes the test and fails expectedly.
