### ISSUE TITLE
Skyscraper in muscle force plot with Analyze Tool

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1675]
### To reproduce
- download and unzip [skyscraper40.zip](https://drive.google.com/a/stanford.edu/file/d/0B1BKpngQdIZIVWRwbUFYcjE5QUU/view?usp=sharing)
- run `analyze -S Setup_Analyze_isokinetic.xml` at the command line
- in the resulting Tug_of_War_Millard_Iso_ForceReporter_forces.sto file, plot "LeftMuscle" vs. "time"

![skyscraper](https://cloud.githubusercontent.com/assets/4203505/25827932/64235194-3402-11e7-95a5-5f4ad73d78b4.png)

### Additional information
Same aberration as reported in [issue 83 in the opensim32 repo](https://github.com/opensim-org/opensim32/issues/83).

**Comment by aseth1** [comment]
The `AnalyzeTool` does not perform a forward dynamics simulation. The `controls_file` is likely being applied at each instant, but since excitation only affects the activation rate, which is not being integrated, there is no way to update the activation state at the next time frame. Instead the `AnalyzeTool` is likely computing the muscle equilibrium at its default activation.

The *skyscraper* bug in 3.3 is likely due to a jump in (or bad) the equilibrium solution.

For excitation to affect the answer, switch to the `ForwardTool` and prescribe the isokinetic motion of the block. You should be able to associate the same Analyses with the `ForwardTool`.

**Comment by tkuchida** [comment]
The behavior you describe in 4.0 is different from the behavior in 3.3. Has this change been documented somewhere?

**Comment by aseth1** [comment]
I believe this is the same behavior since 2.4 and perhaps earlier. The `AnalyzeTool` never performed a forward simulation AFAIK.

**Comment by tkuchida** [comment]
I am not claiming that the `AnalyzeTool` performs (or ever performed) forward simulations. What I am saying is that the `AnalyzeTool` now behaves differently than it did before. (The tug-of-war example used to work.) Has this change in the behavior of the `AnalyzeTool` been documented? Users who have been relying on the old behavior in their workflows will be surprised when they upgrade to 4.0.

**Comment by aseth1** [comment]
It is unclear whether the `AnalyzeTool` is behaving differently or if the solution to the muscle equilibrium (and/or other muscle model) are affecting the answer. Given how controls affect activations it is unlikely that the `AnalyzeTool` does not apply controls (and title of the issue) is the cause of the discrepency.

If the tutorial requires running the `AnalyzeTool` to compute the effect of excitations (and not activations), then the tutorial has been incorrect. One must run a forward simulation more muscle excitations to affect activations. To see the effect of maximal activation the default activation of the muscles could be set to 1.0 with the `AnalyzeTool` (or the plotter).

**Comment by tkuchida** [comment]
Ok @aseth1. I will update the example on Confluence. If there is anything else you would like me to do, please list it here.

**Comment by aseth1** [comment]
I am just curious, if you do set the default_activation to 1.0 do you get the same answers as before? Is there any chance that was expected in the tutorial? Scanning the tutorial quickly I noticed:

> Also, set "default_activation" to 1.0 for this part (part C) of the lab only. 

But I'm not sure if that was the relevant section for this issue.
Thank you for investigating.

**Comment by tkuchida** [comment]
Yes, I carefully followed the instructions on Confluence. If you download the .zip file that is linked in the issue description, you will find that `default_activation` has been set to 1 in the model file.

**Comment by aseth1** [comment]
Thanks for verifying. That suggests that in 4.0 the default_activation is not being applied. The tutorial seems fine if it requires the default_activation = 1.0 (in which case it is not relying on the controls).

**Comment by aseth1** [comment]
> That suggests that in 4.0 the default_activation is not being applied.

I am investigating this.

**Comment by aseth1** [comment]
`AnalyzeTool::createStatesStorageFromCoordinatesAndSpeeds` sets state variable values to zero if not found in the loaded .mot or .sto file. This bug was exposed when another bug, which always used the `default_activation` to solve for muscle equilibrium regardless of the provided state was fixed.

**Comment by tkuchida** [comment]
> This bug was exposed when another bug… was fixed.

#1548, I think. Should `AnalyzeTool::createStatesStorageFromCoordinatesAndSpeeds()` be setting unknown state variable values to `NaN` instead of zero?

**Comment by tkuchida** [comment]
Test again now that #1686 has been merged.

**Comment by tkuchida** [comment]
Tested on master after merge of #1686; now produces same behavior as in 3.3. (Updated title and issue description.)

**Comment by aymanhab** [comment]
PR in review
