### ISSUE TITLE
List of Confluence updates for 4.0 release

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1684]
The following updates must be made to Confluence once the 3.3 version has been archived (please add to this list as necessary):
- [ ] [New features](http://simtk-confluence.stanford.edu:8080/display/OpenSim/New+Features+in+OpenSim+3.3)
- [ ] [Upgrade notes](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Upgrade+Notes+for+OpenSim+3.3)
- [ ] [Command line interface](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Command+Line+Utilities)
- [ ] [Tug-of-war example](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Designing+a+Muscle+for+a+Tug-of-War+Competition) (replace `AnalyzeTool` with `ForwardTool` in Part C; see #1675)
- [ ] Joint constructors no longer have _reverse_ flag (appears on [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Common+Scripting+Commands), [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Part+II:+Building+a+Passive+Dynamic+Walker+Model), and likely others)
- [ ] Update instructions for configureOpenSim.m on [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+with+Matlab)
- [ ] Changes listed in [CHANGELOG.md](https://github.com/opensim-org/opensim-core/blob/master/CHANGELOG.md)
- [ ] Python version number and use instructions on [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) (see second comment on #1669). Comments from @chrisdembia:

>It seems like the python bindings work with python3, which is great (I hadn't known this before); we should definitely document this. In general, the python bindings should not require any *specific* version of python (that is, python 3.4 and 3.6 should both work). So the documentation should be that the python bindings can be built from source for both python 2 and python 3 (most likely, the binary release will only be for python 2), but I think we should not need to say which specific version of python 2 or 3 is necessary (or perhaps we could say "2.7 or greater").

> The `sys.path` call should only be necessary because @klshrinidhi chose not to install the python package system-wide; I don't think we should encourage users to use this mechanism. They should instead run `python setup.py install` from the `sdk/python` directory; [our instructions](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) already mention this.

**Comment by jenhicks** [comment]
Thanks for making this list Tom. I am going to break it up into separate issues so we can assign to (different) people and track incremental progress.

**Comment by jenhicks** [comment]
Closing this issue -- I duplicated the list in other issues.
