### ISSUE TITLE
Sporadic Exceptions in getSystem() claiming no underlying System.

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1685]
Started appearing after latest changes to master branch. After loading a model and calling initSystem on it, Trying to get transforms throws exception in Frame.getTransformInGround(state) claiming no System.

java.lang.RuntimeException: Component has no underlying System.
You must call initSystem() on the top-level Component (i.e. Model) first.
	In object 'ground' of type Ground.
	In file D:\Dev\src\opensim-core\OpenSim\Common\Component.cpp:1401
	In function 'getSystem'
	at org.opensim.modeling.opensimSimulationJNI.Frame_getTransformInGround(Native Method)

**Comment by aymanhab** [comment]
This maybe model specific, reproduces with Matt DeMers ToyLandingModel_activeAFO in models repo but not Tug_of_war.

**Comment by aseth1** [comment]
@aymanhab can you provide a bit more context by supplying the sequence of calls you made to elicit the failure?

**Comment by aymanhab** [comment]
@aseth1 It is a bit hard to provide specific context because once the model is loaded and initSystem is called on it, many tools/windows try to access it (e.g. to get Coordinates, Build navigator tree, Visualization, Topology view) sometimes from different threads and the order could depend on how long  it takes to open a window for example . If a specific behavior was changed recently to cause the System to be invalidated it would be easier to search the GUI code base for suspect calls.

**Comment by aymanhab** [comment]
This was actually a good catch due to a GUI bug/issue that resulted in using Ground from a previously closed model. Closing.

**Comment by aseth1** [comment]
Great. Glad the recently added exceptions exposed an issue rather than creating a new one.
