### ISSUE TITLE
Modifying properties of bodies without reinitialization of the model

### ISSUE THREAD

**Issue by kidzik** [opensim-org/opensim-core#1687]
Hi,
In the beta build I am trying to:
1. load a walker model,
2. add 'obstacles' (sphere contact bodies) for a forward simulation,
3. run the simulation,
4. change positions and sizes of the obstacles at the end,
5. rerun the simulation with the new properties of the obstacles.

If I run `initSystem` after each simulation, it recreates the visualizer, eats a lot of memory and breaks after a few simulations. When I just run `initializeState` after the simulation, the visualizer is kept and the simulation is nicely 'lightly' restarted but:
* obstacles don't change the positions
* if I scale obstacles up it works, if I try to scale them down they remain the same size.

Here is the minimal script reproducing the errors (with just 1 obstacle "ballBody"). Any hack will work for me, this is the last thing we need for our NIPS competition :). Thanks!
```python
import opensim

# Settings
stepsize = 0.01

# Load existing model
model_path = "../osim/models/gait9dof18musc.osim"
model = opensim.Model(model_path)
model.setUseVisualizer(True)

# Create a ball
r = 0.1
ballBody = opensim.Body('ball', 0.0001 , opensim.Vec3(0), opensim.Inertia(1,1,.0001,0,0,0) );
ballGeometry = opensim.Ellipsoid(r, r, r)
ballGeometry.setColor(opensim.Gray)
ballBody.attachGeometry(ballGeometry)

# Attach the ball to the model
ballJoint = opensim.WeldJoint("weldball",
                         model.getGround(), # PhysicalFrame
                         opensim.Vec3(0, 0, 0),
                         opensim.Vec3(0, 0, 0),
                         ballBody, # PhysicalFrame
                         opensim.Vec3(0, 0, 0),
                         opensim.Vec3(0, 0, 0))
model.addComponent(ballJoint)
model.addComponent(ballBody)

# Add contact
ballContact = opensim.ContactSphere(r, opensim.Vec3(0,0,0), ballBody);
model.addContactGeometry(ballContact)

# Initialize the system
state = model.initSystem()

# Simulate
for i in range(100):
    t = state.getTime()
    manager = opensim.Manager(model)
    manager.integrate(state, t + stepsize)

    # Restart the model every 10 frames, with the new position of the ball
    if (i + 1) % 10 == 0:
        newloc = opensim.Vec3(float(i) / 10, 0, 0)
        opensim.PhysicalOffsetFrame.safeDownCast(ballJoint.getChildFrame()).set_translation(newloc)

        r = i * 0.01
        ballGeometry.setEllipsoidParams(r,r,r)
        ballContact.setRadius(r)

        state = model.initializeState()
```

**Comment by tkuchida** [comment]
> obstacles don't change the positions

A short-term solution could be to mount the obstacles on dummy bodies and connect the dummy bodies to ground with joints, effectively converting the obstacle positions from properties into states. You would then be able to adjust the obstacle positions (and then lock these new joints before simulating) without calling `initSystem()`.

> if I scale obstacles up it works, if I try to scale them down they remain the same size.

Sounds like new geometry is always being drawn, but isn't visible if it's smaller because it's drawn inside the existing geometry. I don't know how to work around adjusting contact geometry properties. Could you instead adjust the vertical position of the obstacle?

**Comment by kidzik** [comment]
Locked `FreeJoint` works great, I can move obstacles, thanks a lot!

Regarding the geometry, now when I can move it I see that it is correctly redrawn in the right location but the problem with size remains: when I make it larger it is redrawn larger, when I make it smaller it is redrawn the same size.
This is a smaller problem though: I can just draw contact geometry which is fine - the problem is only with the body geometry.

**Comment by aymanhab** [comment]
API visualizer doesn't support editing as expected, but if you can erase everything from the visualizer window before restarting then it may do the trick.
You may try changing the scale factors instead of recreating the Geometry but I doubt that would do it.

**Comment by jimmyDunne** [comment]
@kidzik Were you able to find workarounds? Anything high priority we could help with for the challenge?

**Comment by kidzik** [comment]
Yes, everything works now, thanks! I have some performance issues when adding multiple contact spheres -- I will post a small example with details soon. It's less urgent though. Thanks a lot!

**Comment by aymanhab** [comment]
Thanks @kidzik Feel free to close if no outstanding issues.
