### ISSUE TITLE
Create mechanism to start work on new documentation in confluence

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1690]
I would like to create a new copy of the Scripting and Development branch. Running in to bugs that I am working with support to figure out.

**Comment by jenhicks** [comment]
OK ... I think I have figured this out. I can:

- Create a copy of the entire "Documentation" branch and the entire "Examples & Tutorials". These branches will be labeled with the prefix "__40__". We can make changes to the structure, as long as any new pages still use this prefix as well. These branches will be private to the dev team while we are editing.

- When we are ready to release, we will remove the __40__ prefix in the live version and delete the old copy. We will also make a copy of the entire space, call it OpenSim Documentation 3.3. and keep the old versions of the doc and examples here.

**Comment by jenhicks** [comment]
Let me know if you have thoughts @aseth1 @aymanhab @jimmyDunne @chrisdembia @tkuchida 

And I just realized that github interpreted the prefix as markup. The prefix is "_ _ 4 0 _ _" but with no spaces. This is defined by the plugin I'm using on confluence.

If everyone is reasonably happy with this, I can create the copies.

**Comment by chrisdembia** [comment]
@jenhicks I fixed the formatting for the `__40__` prefix in your earlier post.

This sounds good to me. It would be helpful to be able to compare/diff two different pages so that we can easily resolve any divergent edits between the 3.3 and 4.0 copies. It seems like there might be a free add-on for doing this: https://community.atlassian.com/t5/Confluence-questions/Can-I-compare-two-pages-in-different-spaces-in-confluence/qaq-p/103442

To be clear, by "branch" you mean something like "subsection", not "branch" in the git sense, correct?

**Comment by aseth1** [comment]
This seems like the procedure we used for previous (major) releases of OpenSim.  Sounds good to me.

**Comment by jimmyDunne** [comment]
+1. Sounds like a good way of doing it given the tech.

**Comment by jenhicks** [comment]
Thanks for the feedback. I mean branch as in branch of a tree (the tree of pages on confluence). See the left nav tree.

**Comment by aymanhab** [comment]
Sounds reasonable. Thanks Jen.

**Comment by jenhicks** [comment]
Here's the 40 branch of the "Documentation" section (Users' Guide, scripting and development section, etc):
http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Documentation

I will work on copying the Examples and Tutorials next. 

Viewing and editing will soon be restricted to the dev team. Let me know if you can't edit or view. I've made these restrictions at the top level. Please don't change any of the child pages (otherwise, it will be hard to turn all the pages public again).

**Comment by chrisdembia** [comment]
Clicking that link brings me to a login page. After logging in, I am able to edit that page (though I did not make or save any edits).

>  Please don't change any of the child pages (otherwise, it will be hard to turn all the pages public again).

When will we be able to edit the child pages? If I understand correctly, this will be necessary to edit the scripting pages, etc.

**Comment by jenhicks** [comment]
You can edit the pages. Just don't change any of the "Restrictions" (who can edit/view). I will control this from the top page. If you change children pages, we'll have to individually go and find/change permissions for those ones.

**Comment by chrisdembia** [comment]
Oh okay great; thank you.
