### ISSUE TITLE
finalizeFromProperties() usage and exception messages

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1693]
Since it is a new procedure, I forgot that we need to call `finalizeFromProperties()` immediately after reading a model into memory (Matlab). So I spent a solid half hour trying to figure out why I was getting exceptions when trying to work with coordinates. 

Doing this in Matlab, the exception was;

``
model.getCoordinateSet().get(0)

>>Java exception occurred:
>>java.lang.RuntimeException: ArrayPtrs.get: Array
>>index out of bounds.
>>	at   org.opensim.modeling.opensimSimulationJNI.SetCoordinates_get__SWIG_0(Native
>>        Method)
>>	at org.opensim.modeling.SetCoordinates.get(SetCoordinates.java:145) 
``
I don't find this helpful. It is also not helpful that asking the coordinate set for its size returns 0— it should return an exception. 

Perhaps there can be additions to the exception messages that suggest to the User to try `finalizeFromProperties`

**Comment by tkuchida** [comment]
> It is also not helpful that asking the coordinate set for its size returns 0— it should return an exception.

:+1: Perhaps `OPENSIM_THROW_IF_FRMOBJ(!isObjectUpToDateWithProperties(), ...);` is needed.

**Comment by aseth1** [comment]
Will need to come up with a solution that does no require adding `OPENSIM_THROW_IF_FRMOBJ(!isObjectUpToDateWithProperties(), ...);`  on every getter!

**Comment by aseth1** [comment]
I think we are seeing that the practical benefits of automatically calling `finalizeFromProperties()` upon Model construction outweighs the inconsistency of having to invoke  `finalizeFromProperties()` manually upon cloning (which is a less common usage). Once we have bugs under control, I will look into how we can get the model to be finalized after cloning so we can put this issue to rest.

**Comment by tkuchida** [comment]
> Will need to come up with a solution that does no require adding `OPENSIM_THROW_IF_FRMOBJ(!isObjectUpToDateWithProperties(), ...);`  on every getter!

Of course. Conceptually, the problem is that the user can interact with the CoordinateSet before it's meaningful. It should not be possible for the user to see a CoordinateSet of size zero unless the Model really can't move; before calling `finalizeFromProperties()`, the information given to the user should be that the size of the CoordinateSet is undefined (e.g., answer "I don't know" rather than "I know that the size is zero").

I agree with your second comment: ideally, the user would not be required to call `finalizeFromProperties()` after construction.

**Comment by tkuchida** [comment]
@aseth1 I'm wondering whether it would make any sense to include `OPENSIM_THROW_IF_FRMOBJ(!isObjectUpToDateWithProperties(), ...);` (or something like it) in the macro for getting properties (of Components). Here's why:
```cpp
Model myModel = Model("myModel.osim");
myModel.finalizeFromProperties();
std::cout << myModel.getCoordinateSet().getSize() << std::endl;

//create a new joint and add it to the model

std::cout << myModel.getCoordinateSet().getSize() << std::endl;
```
Would the second `cout` print the same number as the first one (i.e., from a stale CoordinateSet)?

**Comment by jimmyDunne** [comment]
Potential solution: override clone so that it calls finalizeFromProperties()
