### ISSUE TITLE
C3DFileAdapter: very slow file reading to Tables

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#1698]
Reading a c3d file's data to a Table using the C3DFileAdapter is currently very slow. I compared loading a c3d file (1 minute of walking data) using @jimmyDunne's `btk_loadc3d()` MATLAB script to the C3DFileAdapter and got the following results after 3 runs (Windows 7, 64-bit, i5 2.50 GHz): 

btk in MATLAB: 0.39 +/- 0.07 seconds
C3DFileAdapter: 671.96 +/- 20.08 seconds

If you'd like to recreate the test, I can send you the file I used.
```matlab
import org.opensim.modeling.*

file = 'slk.c3d';

% Using btk directly in MATLAB (need btk MATLAB wrapper)
tic
data = btk_loadc3d(file);
disp('btk in MATLAB: ')
toc

disp(' ')
 
% Using new C3DFileAdapter in 4.0
tic
adapter = C3DFileAdapter();
tables = adapter.read(file);
disp('C3DFileAdapter: ')
toc

```

**Comment by jimmyDunne** [comment]
Need to add a benchmark to the test case. Profile each step to see where issue is coming from.

**Comment by jimmyDunne** [comment]
@aseth1 will profile

**Comment by chrisdembia** [comment]
I did some profiling and it seems that the issue is the resizing that `DataTable_::appendRow()` does (this takes up 66% of the time in testC3DFileAdapter). I tried to pre-allocate the matrix underneath the DataTable, but I was not successful. @aseth1 let me know if you want to chat about this.

**Comment by chrisdembia** [comment]
Here's how I got the number of rows and column:

```cpp
        int marker_num_frames = marker_pts->GetFrontItem()->GetFrameNumber();
        int marker_num_columns = marker_pts->GetItemNumber();
        marker_table.updMatrix().resize(marker_num_frames, marker_num_columns);
```

**Comment by aseth1** [comment]
Thanks @chrisdembia for checking and suggesting a fix. I can confirm your findings in VS2015 profiler:
**87.1 %** -> `_depData.resizeKeep(_depData.nrow() + 1, _depData.ncol());`

**Comment by chrisdembia** [comment]
Ah; it seems like your profiler was more helpful. Let me know if you want to chat more.

**Comment by aymanhab** [comment]
PR in review
