### ISSUE TITLE
list of memory leaks

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#170]
The test case testInitState filas on Windows (2013 Pro) with error log below. Need to either plug leak if true, or relax condition if this's not true so that developers have confidence in their environment. The test case passes on Travis,
...
Loaded model arm26 from file arm26.osim
**********************\* testMemoryUsage ***********************
MODEL: arm26.osim uses 136KB
156KB change in memory use after 100 state initializations.
Approximate leak size: 1.55957KB or 1.14674% of model size.
Average initialization time: 0.66ms
testInitState failed: 
Exception:
  testMemoryUsage: state initialization leak > 0.5% of model memory
  footprint.
  file= C:\Users\Ayman\Documents\GitHub\opensim-core\OpenSim\Simulation\Test\testInitState.cpp
  line= 195

<end of output>

**Comment by chrisdembia** [comment]
The reason why we currently do not use travis to detect memory leaks is that we already have a bunch of leaks. However, it is possible to suppress specific errors with valgrind:

- http://valgrind.org/docs/manual/manual-core.html#manual-core.suppress
- http://stackoverflow.com/questions/3174468/is-it-possible-to-make-valgrind-ignore-certain-libraries
