### ISSUE TITLE
Muscle equilibrium solve mishandles Newton steps to short fiber lengths

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1700]
When the current iteration steps to a fiber length < min_fiber_length, the fiber length is *clamped* to the minimum. Subsequent step estimates a length that overshoots the solution and then next step is back to a length that is < min_fiber_length, which gets clamped to the min. From this point on the solve is in endless cycle. A max count in which the min fiber length is *achieved* (regardless of bouncing back > min) is triggered and the fiber length is incorrectly set to the min_fiber_length. This causes a jump disontinuity in the muscle's reported fiber-length and corresponding muscle force from the AnalyzeTool.

This issue results in the [skyscraper bug](https://github.com/opensim-org/opensim32/issues/83) reported by @tkuchida.

**Comment by aseth1** [comment]
The crux of the issue is the ad-hoc implementation of the Newton solve.  A robust method will halve the step-size with the error increases due to a step (which is also the case above).  To test this hypothesis I halve the step-size every time in this case the algorithm converges to the correct solution (no more cycling back and forth between two bad solutions).

A positive change would be to abstract out the Newton solver baked into the muscle model and call a separate (published/tested) RootSolver implementing Newton-Raphson or other established (e.g. [Brent's](https://en.wikipedia.org/wiki/Brent%27s_method#Brent.27s_method))  method.

**Comment by chrisdembia** [comment]
@humphreysb may be interested.

**Comment by tkuchida** [comment]
> This issue results in the skyscraper bug reported by @tkuchida.

See #1675.

**Comment by aymanhab** [comment]
PR in review
