### ISSUE TITLE
Potential of holding to stale references in GUI and Scripting

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1701]
Under the cover, most Java and Python objects used across the API are references to C++ objects. It may be useful in some cases to avoid using references that could get stale e.g. feedback on issue #1681 PR, using IDs (if there's a unique one)  or indices may be better option

**Comment by chrisdembia** [comment]
We could also use some type of shared pointer; that way the object does not get deleted (no segfault), but we could also indicate somehow that the component is orphaned (runtime exception).
