### ISSUE TITLE
Rename initSystem() to finalizeSystem()

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1705]
Working on the documentation and in discussion with @tkuchida @chrisdembia and other, that the operations (stages) of the top-level (e.g. Model) in creating the underlying System, should be clear. We currently have `finalizeFromProperties()`, `finalizeConnections()` and `initSystem() as the major  steps or stages in forming a computational `System` that embodies the `Model`. 

If we think of *finalizing* as the end point for changes in properties (parameters of the Model), changes to connections (inter dependencies and Inputs and Output wiring), and changes to the System (computational representation) then `finalizeSystem()` seems to be a more logical name. 

Then we would have "finalization" stages of the `Model` for model creation/configuration and realization stages of the System's State for computation/simulation.

**Comment by aymanhab** [comment]
I like a lot trying to comeup with a Staging mechanism (and ideally embed that somehow in the API documentation to indicate what calls are available at which stage) :+1:

For the actual name, I have a mixed feeling about using the word "finalize" altogether. In my mind if it's ever used it probably should be one finalize to do everything. Too many "finalize" dilutes the meaning that it means nothing :smiley:  Could be just me..

**Comment by tkuchida** [comment]
Potentially relevant: #1668

**Comment by chrisdembia** [comment]
I too think it would be good to brainstorm some alternatives to "finalize." I think "realize" is good, but it's taken.

**Comment by chrisdembia** [comment]
We would also need to rename "finalizeFromProperties" to "finalizeProperties()" or something like that.

**Comment by aseth1** [comment]
>Potentially relevant: #1668

Absolutely pertinent. Thanks. 

I agree @aymanhab @chrisdembia with *finalize* but couldn't think of something better.  What is relevant about *finalize* is that after that *stage* the properties, connections, or System are locked-in. Attempting to make changes knocks you back down to previous stage.

**Comment by chrisdembia** [comment]
@aseth1 I agree that finalize can be seen as having the desired meaning. Here are some synonyms:

> conclude, complete, clinch, settle, work out, secure, wrap up, wind up, put the finishing touches to; reach an agreement on, agree on, come to terms on; informal sew up.

"Realize" is nice because it is somewhat 'directionless': things are happening both before and after each stage.

**Comment by aseth1** [comment]
Some alternatives might be: *actualize*, *process*, *confirm*.

**Comment by aymanhab** [comment]
One way I've been trying is to start at the "names" of the Stage(s) which convey something about the status of the Component or Model (inline with @tkuchida in #16668) and then come up with names for methods to bring the model/component to that stage to see if it holds. For example the Model is first: 
- Constructed
- Deserialized (populated from properties)
- Connected (connections satisfied, wired-up)
- Ready (or Built)
Names just made up but may help the discussion if that sounds like a reasonable approach.. Then the methods could carry names related to the stages (makeConnected, markConnected, finishConnection,  establishConnections.... etc.)
