### ISSUE TITLE
Update confluence documentation of the command line interface

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1708]
[Command line interface](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Command+Line+Utilities)

**Comment by chrisdembia** [comment]
I can do this.

**Comment by chrisdembia** [comment]
I've finished updating this Confluence page. See http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Command+Line+Utilities.

Here's a screenshot of the updated page:

![image](https://cloud.githubusercontent.com/assets/846001/26094717/ee77ff98-39cf-11e7-91c6-1313eabef4a0.png)

---

How do we proceed from here? Should I close this issue, or should someone review my changes to the Confluence page?

**Comment by jenhicks** [comment]
Thanks Chris. You could move it to the "Needs verifying" pipeline and we can close after someone reviews.

**Comment by chrisdembia** [comment]
Okay thanks. I've moved this to the Needs Verifying pipeline and I await someone's review.

**Comment by jimmyDunne** [comment]
Verified! I have been using the documentation to run cmd line tests on W10 with the latest artifact. Documentation is clear and awesome! Only took a year 🥀

**Comment by chrisdembia** [comment]
Thank you!
