### ISSUE TITLE
Update Python version number and use instructions on confluence

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1711]
[this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) (see second comment on #1669). Comments from @chrisdembia:

>It seems like the python bindings work with python3, which is great (I hadn't known this before); we should definitely document this. In general, the python bindings should not require any *specific* version of python (that is, python 3.4 and 3.6 should both work). So the documentation should be that the python bindings can be built from source for both python 2 and python 3 (most likely, the binary release will only be for python 2), but I think we should not need to say which specific version of python 2 or 3 is necessary (or perhaps we could say "2.7 or greater").

> The `sys.path` call should only be necessary because @klshrinidhi chose not to install the python package system-wide; I don't think we should encourage users to use this mechanism. They should instead run `python setup.py install` from the `sdk/python` directory; [our instructions](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+in+Python) already mention this.

**Comment by chrisdembia** [comment]
I can do this.

**Comment by chrisdembia** [comment]
I have updated this confluence page to provide instructions for macOS, and to clarify that Python 3 is not supported (I tested this locally and could not yet achieve Python 3 support). 

I still have to update the Windows setup instructions (I want to remove the suggestion to use Enthought Canopy).

http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Scripting+in+Python

**Comment by chrisdembia** [comment]
I also updated the "Available Example Scripts" section.

**Comment by chrisdembia** [comment]
I also want to update the Python instructions to include some Python-specific aspects of the interface (iterating through components, getting concrete types from getComponent(), etc.). I might also like to create some simple python examples based on the python tests.

**Comment by chrisdembia** [comment]
The only remaining task here is to change the Windows instructions to use Anaconda instead of Enthough Canopy. Anaconda is much more popular now.
