### ISSUE TITLE
Document new visualizer in the User's Guide

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1712]
This page needs to be updated:
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Navigating+the+Visualizer+Window
We may also want to add a section or change the name of this page, since we also need to include information about changing lighting, backgrounds, etc.

**Comment by aymanhab** [comment]
Page updated, looking for your feedback @jenhicks

**Comment by aymanhab** [comment]
@jenhicks I added an image that shows all the above, please let me know if that's adequate or if you prefer separate images for the different parts. Thank you.

**Comment by aymanhab** [comment]
camera icon updated.
