### ISSUE TITLE
GeometryPath has addhoc method to control its color

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1720]
GeometryPath is used as a utility for computation and to visualize Muscles, PathSprings. It has no associated Appearance property so its behavior is inconsistent with other geometry (e.g. Opacity and Show/Hide status are not persistent). This breaks functionality that used to exist in version 3.3.

**Comment by aymanhab** [comment]
PR in review

**Comment by jenhicks** [comment]
Need to verify that you can show/hide/wireframe/change transparency/color of muscles
