### ISSUE TITLE
AbstractDataTables cannot be used with SimTK::ClonePtr() 

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1722]
Using `SimTK::ClonePtr` requires that a class `T` has a function `T* clone() const`. The AbstractDataTable class and its subclasses have a `clone()`, but it returns a `std::shared_ptr<AbstractDataTable>`. While this has the beneficial feature of making memory leaks less likely, it also means that we cannot use `SimTK::ClonePtr<TimeSeriesTable>`, etc.

**Comment by aymanhab** [comment]
For a large table shared_ptr seems appropriate, need to understand the problem better. Please provide usecase @chrisdembia
