### ISSUE TITLE
RuntimeError: std::exception in 'bool OpenSim::InverseKinematicsTool::run()'...

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#1723]
Hi again @chrisdembia 
Related to the #1716 issue, after solving that problem the next warning appeared:

> 	In file /home/.../opensim-core/OpenSim/Common/TRCFileAdapter.cpp:82
> 	In function 'extendRead

And after that the next error was shown: 

> Traceback (most recent call last):
>   File "/home...", line 43, in <module>
>     iktool.run()
>   File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/tools.py", line 9612, in run
>     return _tools.InverseKinematicsTool_run(self)
> RuntimeError: std::exception in 'bool OpenSim::InverseKinematicsTool::run()': InverseKinematicsTool Failed, please see messages window for details...

any idea about this error?
Thanks

**Comment by chrisdembia** [comment]
Are you sure that the TRC file you are trying to load exists and is in the expected location?

**Comment by aymanhab** [comment]
Need minimum example to reproduce.

**Comment by nikorose87** [comment]
Dr. Ayman, I'm playing the complete error, like this:

> InverseKinematicsTool Failed: Error reading MetaData in file 'subject01_walk1.tr.'. Unexpected key. Expected = OrigNumFrames. Received = OrigNumFrames
> 	In file /home/nikorose/Workspace/Opensim/opensim-core/OpenSim/Common/TRCFileAdapter.cpp:82
> 	In function 'extendRead'
> Traceback (most recent call last):
>   File "2354IK-ID-RRA.py", line 44, in <module>
>     iktool.run()
>   File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/tools.py", line 9612, in run
>     return _tools.InverseKinematicsTool_run(self)
> RuntimeError: std::exception in 'bool OpenSim::InverseKinematicsTool::run()': InverseKinematicsTool Failed, please see messages window for details...
> 

And the complete files are shown below. Maybe some files are useless.
[Gait2354_Simbody.zip](https://github.com/opensim-org/opensim-core/files/1029982/Gait2354_Simbody.zip)

Basically the error is presented doing IK, after scaling.

I hope it can be useful.

Thanks

**Comment by chrisdembia** [comment]
Ah okay; this is the same issue as with #1726, but for TRC files. The file you have has `\r\n` line endings, but on Linux, the line endings are expected to be `\n`, so the `\r` remains in the parsed string.

As a workaround, use `dos2unix` (or `set ff=unix` in Vim) to convert the TRC's line endings to `\n`.

**Comment by nikorose87** [comment]
Thank U all!

**Comment by chrisdembia** [comment]
This is still a bug; I'll be updating a PR soon to fix this without the need for a workaround.

**Comment by nikorose87** [comment]
Ok, sorry!

**Comment by chrisdembia** [comment]
No need to apologize; thanks again for the bug reports.
