### ISSUE TITLE
"DataType not specified" when reading version-1 STO file

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1725]
Attempting to read a version=1 STO file (see attached) using `import opensim; opensim.FileAdapter.readFile('<file-name>')` (in Python) causes the following error:

```
RuntimeError: std::exception in 'OpenSim::DataAdapter::OutputTables OpenSim::FileAdapter::readFile(std::string const &)': DataType not specified in the header.
        In file /Users/chris/repos/opensim/13/opensim-core/OpenSim/Common/STOFileAdapter.cpp:62
        In function 'createSTOFileAdapterForReading'
```

This is because the function `createSTOFileAdapterForReading(const std::string& fileName)` checks for a DataType metadata field.  I think if the STO file does not have a version number (that is, its version is 1), then it is parsed as if DataType is double.

[testGait10dof18musc_netgeneralizedforces.sto.zip](https://github.com/opensim-org/opensim-core/files/1016502/testGait10dof18musc_netgeneralizedforces.sto.zip)

**Comment by aymanhab** [comment]
Need test case, assume doubles if older sto file
