### ISSUE TITLE
Binary vtp files can't be opened

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1729]
Up to version 3.3, we used vtk to read mesh files (vtp) so we handled them seamlessly. The API and new visualization doesn't use the vtk native libraries and accordingly fails to load binary vtp files (only ASCII vtp files). This showed in one user model/geometry for the OpenSim 4.0 paper (Apoorva's model).

**Comment by tkuchida** [comment]
3.3:
![image33x8](https://cloud.githubusercontent.com/assets/4203505/26370199/f815260c-3fab-11e7-99ed-ea487549e623.png)

4.0:
![image40](https://cloud.githubusercontent.com/assets/4203505/26370240/0d8985aa-3fac-11e7-8527-ee2c4948d197.png)

**Comment by aymanhab** [comment]
Thanks @tkuchida 💯

**Comment by aymanhab** [comment]
Will manually convert our vtp files to ascii and ask users to do that using Paraview for their own files.

**Comment by chrisdembia** [comment]
This example might be helpful: http://www.vtk.org/Wiki/VTK/Examples/Cxx/IO/WriteVTP
