### ISSUE TITLE
C3DFileAdapter::read() assumes time starts at 0.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1732]
Based on discussion with @jimmyDunne, this assumption might be reasonable, in which we could just document this behavior.

**Comment by tkuchida** [comment]
See comments in C3DFileAdapter.cpp, [L121](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/C3DFileAdapter.cpp#L121) and [L243](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/C3DFileAdapter.cpp#L243).

**Comment by chrisdembia** [comment]
I think it would be good to additionally provide user-facing documentation, perhaps in the class description for C3DFileAdapter.

**Comment by tkuchida** [comment]
> I think it would be good to additionally provide user-facing documentation, perhaps in the class description for C3DFileAdapter.

I agree; I was not advocating against that. The comments on these lines should be updated if a design decision has been made about start time.
