### ISSUE TITLE
Document that CoordinateActuator::getCoordinate() requires calling Model::initSystem()

### ISSUE THREAD

**Issue by AnCaPepe** [opensim-org/opensim-core#1739]
After loading a .osim file containing a CoordinateActuator and calling finalizeFromProperties() on it, I can find it in the list returned by getActuators()/updActuators(), indexed by its name string.

However, using Python bindings, the object is identified as a base OpenSim::Actuator one, not having the getCoordinate() method available. Using C++ directly I can dinamic_cast it to a CoordinateActuator successfully, but the getCoordinate() method returns a NULL pointer.

(small Python test attached below)

[coord_act_test.zip](https://github.com/opensim-org/opensim-core/files/1048205/coord_act_test.zip)

**Comment by chrisdembia** [comment]
We provide a method to downcast in the bindings:

```py
a = CoordinateActuator.safeDownCast(m.getActuators().get('knee_actuator'))
c = a.getCoordinate() # should work now
```

This is documented [here](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Common+Scripting+Commands).

Please close this issue if this works for you.

Note that in 4.0, `m.getComponent('knee_actuator')` should directly give you a CoordinateActuator, removing the need to downcast.

**Comment by Bitiquinho** [comment]
Thanks for answering that quickly

Both methods allow me to acquire a **CoordinateActuator** object, but the **getCoordinate()** method now returns me a **NoneType** result, similarly to how in C++ I end up getting a **NULL** pointer

**Comment by chrisdembia** [comment]
Ah I see. Call `m.initSystem()` first. I've renamed this issue.

**Comment by Bitiquinho** [comment]
Oh, that works now. Thanks a lot !

Will this ticket remain open for now ?

**Comment by chrisdembia** [comment]
> Will this ticket remain open for now ?

Yes; thank you for checking.

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
