### ISSUE TITLE
isEqual() always declares equality if two doubles or two angles are within 1e-7

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1745]
It seems dangerous to expose a method that declares equality based on a fixed, arbitrary tolerance. Note the "TODO" comments:
- [comparing doubles](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Property.cpp#L52)
- [comparing Transforms](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Property.cpp#L91)

**Comment by chrisdembia** [comment]
I think those functions are used to determine if two Objects are equal (they are called by `Object::operator==()`). Perhaps they could be renamed.

**Comment by tkuchida** [comment]
> I think those functions are used to determine if two Objects are equal (they are called by `Object::operator==()`). Perhaps they could be renamed.

What is the rationale for `Object` to declare equality if two doubles are within 1e-7? I would have expected something like `SimTK::SignificantReal`.

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
