### ISSUE TITLE
Images missing from Confluence page

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1747]
[\_\_40\_\_Taking Snapshots and Making Movies](http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Taking+Snapshots+and+Making+Movies)

E.g., "1. Click the camera button [blank space] in the current 3D View Toolbar."

**Comment by jenhicks** [comment]
These are actually missing in the live page (so not a prefix or copy issue)

http://simtk-confluence.stanford.edu:8080/display/OpenSim/Taking+Snapshots+and+Making+Movies
