### ISSUE TITLE
Avoid duplication of student and teacher versions for C++ Hopper Device example

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1758]
The MATLAB Hopper Device example has student and teacher versions of some files, but we avoid duplicating entire files by using CMake to generate the student version automatically from the teacher version by extracting the "answers."

We could use CMake to avoid duplication for the C++ version of the Hopper Device example as well, as suggested by @aseth1 in #1737.

**Comment by jenhicks** [comment]
@chrisdembia Is this issue still relevant?
