### ISSUE TITLE
Bouncing block model does not load.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1762]
The reason seems to be that it uses a PointToPointSpring, which does not have updateFromXMLNode() code for sockets.

Related #206, https://github.com/opensim-org/opensim-gui/issues/68

**Comment by tkuchida** [comment]
The model can be loaded but `finalizeConnections()` fails:
<pre>
Failed to connect Socket 'body1' of type PhysicalFrame (details: Model'toy_with_forces'::findComponent() cannot find a nameless subcomponent.).
        In object 'spring' of type PointToPointSpring.
        In file C:\Users\tkuchida\opensim-core\OpenSim\Common\Component.cpp:236
        In function 'finalizeConnections'
</pre>

**Comment by tkuchida** [comment]
Fixed by #1902.
