### ISSUE TITLE
XML Ground appears as first element in Model, above <publications>, etc.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1763]
The Ground property now appears at the top of XML files (unless the Model also has subcomponents in <components>), above other elements like <publications>. I think it makes more sense to put the Ground property next to the BodySet, etc.

This was originally raised in #776.

**Comment by aymanhab** [comment]
@chrisdembia If the order is based on the order of declaration of properties then it might be easy to move the declaration line down without changing any APIs. Would that work?

**Comment by chrisdembia** [comment]
Yes; the fix is that simple (I think it's actually the `constructProperty_()` calls we need to reorder). We just need to agree on the ordering.
