### ISSUE TITLE
Using IKSolver - Matlab Segfault

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1765]
I keep getting segfaults in Matlab when trying to run a simple iksolver script. I have attached a zip containing the script, a model, and the marker file. I am not getting any usable error messages printed to OpenSim log files or the Matlab crash dump. 

[iksolver_test.zip](https://github.com/opensim-org/opensim-core/files/1076376/iksolver_test.zip)

**Comment by jenhicks** [comment]
Add log

**Comment by jimmyDunne** [comment]
[logs.zip](https://github.com/opensim-org/opensim-core/files/1078778/logs.zip)

**Comment by aseth1** [comment]
The issue appears to be double deletion of the `MarkerWeight`s here:
```MATLAB
    markerWeights.adoptAndAppend( MarkerWeight(markerName{i},1) );
```

Which is saying that the `Set` of markerWeights owns the `MarkerWeight` which is created, but Java is also deleting it upon garbage collection.

If we give the Set of MarkerWeights its own clone, then it can do with it as it pleases:

```MATLAB
    markerWeights.cloneAndAppend( MarkerWeight(markerName{i},1) );
```
I was unable to get it to fail mysteriously after the change, but I was not always able to get MATLAB to crash with the straight `adopt` either. It could still be luck that it isn't dying and there could be another double deletion somewhere.

Java's delayed/arbitrary garbage collection makes these double deletion issues hard to track down.
One idea is to use SWIG to automatically mark objects as adopted when appended to a `Set` or other container.

For the time being, let us know if using `clone` fixes the issue for you.

**Comment by jimmyDunne** [comment]
Thanks, Ajay!! 

I substituted in `.cloneAndAppend`. I ran the function in a loop with 1000 iterations without a crash, so it seems to be working well!

Thanks for looking into it!

-j
