### ISSUE TITLE
Duplicate names for bodies cause exception

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1768]
@jimmyDunne commented on [Wed Jun 14 2017](https://github.com/opensim-org/opensim-gui/issues/175)

There is an exception if the model has the same name for multiple bodies or joints. There is a testing model attached. 

[subject01.osim.zip](https://github.com/opensim-org/opensim-gui/files/1075736/subject01.osim.zip)

---

@jenhicks commented on [Thu Jun 15 2017](https://github.com/opensim-org/opensim-gui/issues/175#issuecomment-308828553)

Add to the message, "As of 4.0, duplicate names are not allowed. Please update your model's osim file."

**Comment by tkuchida** [comment]
I think duplicate names are permissible, but all full paths must be unique.

**Comment by tkuchida** [comment]
Catch in a general component validation method; should not simply add a message when the `runtime_error` exception is thrown by MultibodyGraphMaker. See comments from @aymanhab in unmerged PR #1866.

**Comment by jenhicks** [comment]
Should be addressed by #1887

**Comment by aseth1** [comment]
Closed by #1887
