### ISSUE TITLE
Provide a table summarizing and comparing OpenSim Tools

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1772]
The potential uses of and differences between SO, CMC, and other Tools may be unclear. Perhaps add a summary table, similar to [these slides by Tim Dorn](http://simtk-confluence.stanford.edu:8080/download/attachments/4489509/SimulationPipeline_TimDorn_Feb2013.pdf?version=1&modificationDate=1360089653546&api=v2), that compares features, benefits, limitations, potential uses, etc.

**Comment by tkuchida** [comment]
A table summarizing and comparing strategies for simulating contact would also be helpful. See the Forum threads [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=7465) and [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=4203), for example.

**Comment by jenhicks** [comment]
Closing ... Carmichael gave a nice webinar that laid some of this out.
