### ISSUE TITLE
Port improvements on "The Strength of Simulation" example to 40 version of documentation

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1773]
[The Strength of Simulation: Estimating Leg Muscle Forces in Stance and Swing](http://simtk-confluence.stanford.edu:8080/display/OpenSim/The+Strength+of+Simulation%3A+Estimating+Leg+Muscle+Forces+in+Stance+and+Swing)

In [Part I](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Part+I%3A+Leg+Muscle+Force+Estimation+in+Swing):
- [x] Add a note at the end of Section B indicating how close the user should expect to get to the IK solution (to avoid spending too much time optimizing by hand).

In [Part II](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Part+II%3A+Leg+Muscle+Force+Estimation+in+Stance):
- [x] Section A, Question 3 refers to "ground_force_vy and 1_ground_force_vy", but the "1_" prefix is neither intuitive nor explained.
- [x] Some filenames in the instructions are incorrect.
- [x] File naming convention ("adjusted" vs. "adjustment") is confusing and inconsistent.

**Comment by tkuchida** [comment]
Improved Confluence pages, including addressing the issues noted above.

**Comment by jenhicks** [comment]
Thanks for making these updates @tkuchida . I'm reopening this issue because we will also need to port these changes to the 40 version of the documentation. We could either copy the pages again or make each change, depending on the scope. @jimmyDunne or I can take a look.
