### ISSUE TITLE
Excessive enforcement of build type consistency

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1793]
My understanding is that while on windows mixing release and debug libraries is prohibited, it is not the case on osx and other platforms. While trying to compile OpenSim core as debug (to troubleshoot a specific problem at the OpenSim core level) the build failed because it claimed dependencies were not built in debug configuration, is this how it's supposed to work?

**Comment by aseth1** [comment]
I build *opensim_dependencies* in debug and the I have no issues.

**Comment by chrisdembia** [comment]
>  is this how it's supposed to work?

Currently, this is the expected behavior. However, I agree that we could be more flexible.

I'll submit a proposed change.

**Comment by chrisdembia** [comment]
@aymanhab it sounds like it's discouraged (https://stackoverflow.com/questions/11658915/mixing-debug-and-release-library-binary-bad-practice), but I would think that at least mixing release with relwithdebinfo is okay. I've submitted a PR that I think strikes a good balance
