### ISSUE TITLE
updAbstractPropertyByIndex index out of range

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1805]
I've seen this exception with the GUI on macOS (https://github.com/opensim-org/opensim-gui/issues/190) and someone reported it with @kidzik's reinforcement learning environment (https://github.com/stanfordnmbl/osim-rl/issues/20). @kidzik, do you have any more information about this issue?

**Comment by aymanhab** [comment]
Seen it too sporadically. Would be great to reproduce consustently.

On Jun 27, 2017 4:43 PM, "Christopher Dembia" <notifications@github.com>
wrote:

I've seen this exception with the GUI on macOS (opensim-org/opensim-gui#190
<https://github.com/opensim-org/opensim-gui/issues/190>) and someone
reported it with @kidzik <https://github.com/kidzik>'s reinforcement
learning environment. @kidzik <https://github.com/kidzik>, do you have any
more information about this issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensim-org/opensim-core/issues/1805>, or mute the
thread

**Comment by kidzik** [comment]
I was getting that error with something like below. Whenever I save references to model objects (forces, muscles etc) in a python list and then recreate the object exactly the same way, I can't access the properties. I ended up ditching the references lists ( 21cc8adb3e77e969f209d8e4405320885e71c5f3 ) and the problem disapeared. I just assumed that I am doing something wrong in python and moved on, but hopefully, it helps. The code below just gives me SegmentationFault now without traceback, but I used to get the error as you mentioned.

```python
import os
import opensim

model_path = 'gait9dof18musc.osim'

class TestEnv:
    forces = []
    model = None
    state = None
    
    def __init__(self, model_path):
        self.model = opensim.Model(model_path)
        self.state = self.model.initSystem()
        forces_set = self.model.getForceSet()
        self.forces += [opensim.CoordinateLimitForce.safeDownCast(forces_set.get(j)) for j in range(20,21)]

    def test(self):
        print(self.forces[0].calcLimitForce(self.state))

env = TestEnv(model_path)
env.test()
env = TestEnv(model_path)
env.test()
```
My ouptut
```
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file tests/../osim/models/gait9dof18musc.osim
0.0
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file tests/../osim/models/gait9dof18musc.osim
Segmentation fault (core dumped)
```
The osim model which I am using is here
https://github.com/stanfordnmbl/osim-rl/blob/master/osim/models/gait9dof18musc.osim

**Comment by chrisdembia** [comment]
Thanks @kidzik, I am able to get that segfault locally.

**Comment by chrisdembia** [comment]
The crash log has this at the bottom of the stack:

```
0   libosimSimulation.dylib       	0x00000001108d1f2d OpenSim::Coordinate::getValue(SimTK::State const&) const + 13
1   libosimSimulation.dylib       	0x00000001107cba1f OpenSim::CoordinateLimitForce::calcLimitForce(SimTK::State const&) const + 31
2   _simulation.so                	0x0000000113a7129a _wrap_CoordinateLimitForce_calcLimitForce(_object*, _object*) + 538
```

**Comment by chrisdembia** [comment]
Simply adding this line in `test()` brings back the `getAbstractPropertyByIndex()` exception:

```
print('upper stiffness: %f', self.forces[0].get_upper_stiffness())
```

The complete test is:

```
import os
import opensim

model_path = 'gait9dof18musc.osim'

class TestEnv:
    forces = []
    model = None
    state = None
    
    def __init__(self, model_path):
        self.model = opensim.Model(model_path)
        self.state = self.model.initSystem()
        forces_set = self.model.getForceSet()
        self.forces += [opensim.CoordinateLimitForce.safeDownCast(forces_set.get(j)) for j in range(20,21)]

    def test(self):
        print('upper stiffness: %f', self.forces[0].get_upper_stiffness())
        print(self.forces[0].calcLimitForce(self.state))

env = TestEnv(model_path)
env.test()
env = TestEnv(model_path)
env.test()
```

And the error is:

```
RuntimeError: std::exception in 'double const & OpenSim::CoordinateLimitForce::get_upper_stiffness() const': PropertyTable::getAbstractPropertyByIndex(): index 3 out of range (0 properties in table).
```

**Comment by chrisdembia** [comment]
So, actually, in this example, `forces` contains pointers to objects that have been deleted. You simply need to add a `self.forces = []` before `self.forces += ...` and the exception goes away. So at least in this case, there is a bug in the script. That doesn't mean that there isn't also a bug somewhere in the SWIG wrapping or the C++ libraries. 

It is easy to accidentally hold onto these "dangling pointers," so I'm not sure what the best solution is. Definitely, the resulting error message is very confusing. I feel like SWIG should have given some sort of error message saying that the underlying C++ object has been destructed. 

As for the GUI, I notice that the API has a `Model::deleteUnusedMarkers()` function. Could the GUI be using this function, causing the exception with the marker set?

**Comment by chrisdembia** [comment]
@aymanhab what's the expected behavior with SWIG when an underlying C++ object has been deleted?

**Comment by chrisdembia** [comment]
The following also produces the exception:

```
m = opensim.Millard2012EquilibriumMuscle()
c = m.getActiveForceLengthCurve()
c.get_minimum_value()
m = opensim.Millard2012EquilibriumMuscle()
c.get_minimum_value()
```

**Comment by chrisdembia** [comment]
I tested commit 589340c985c163f2cce336af83a77d3062e6e63e, from about May 27, and got the same exception. So I'm not sure how old this behavior is. @aymanhab when did you start seeing the MarkerSet exception?

**Comment by aymanhab** [comment]
@chrisdembia I can't reproduce this consistently. The marker set issue I saw was because of the method replaceMarkerSet that was stale and didn't reconnect the model after replacing markers, so likely unrelated. I'd like to know if others are seeing it and if in general GUI use or during scaling specifically.
