### ISSUE TITLE
McKibben actuator is not wrapped

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1812]
Missing from [OpenSim/Actuators/RegisterTypes_osimActuators.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/RegisterTypes_osimActuators.cpp), [Bindings/actuators.i](https://github.com/opensim-org/opensim-core/blob/master/Bindings/actuators.i), etc.

**Comment by tkuchida** [comment]
Arose in [Forum topic 7941](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=7941).

**Comment by aseth1** [comment]
I don't see any harm in wrapping it.

**Comment by tkuchida** [comment]
Fixed by #1943.
