### ISSUE TITLE
Model::printDetailedInfo() causes crash in version 3.3 (in ControllerExample).

### ISSUE THREAD

**Issue by kenembanisi** [opensim-org/opensim-core#1813]
Hello,

In my experience, the controllerExample.cpp code crashed everytime I ran it. However, I observed that after I commented out the following line, it worked properly:
osimModel.printDetailedInfo( si, std::cout );

This might be me or something with the setup. I thought to share it here.

Thanks.

**Comment by aseth1** [comment]
@kenembanisi thank you for sharing the issue! We will definitely investigate.

**Comment by aymanhab** [comment]
This is likely a duplicate of the issue/forum-thread
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9427&p=25927&start=0&view=
