### ISSUE TITLE
Fix ScaleTool to handle the removal of Marker::Fixed

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#182]
Rewriting of Marker as a ModelComponent exposed the flag "Fixed" which was used in an unorthodox way by the ScaleTool so that a Marker is denoted as "Fixed" during MarkerPlacement while not during actual Scaling. This suggested that "Fixed" is not an intrinsic property of the Marker but rather a designation made by the process. We need to adjust the ScaleTool code accordingly.

**Comment by jenhicks** [comment]
Related to #465

**Comment by aymanhab** [comment]
Marker fixed flag has been restored in PR #1486 Will keep open until all issues related to the use of the flag have been addressed.

**Comment by jenhicks** [comment]
Duplicates #465
