### ISSUE TITLE
Data files printed with 4.0 on Mac cannot be read in 3.3 on Windows

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1820]
Reported by @jimmyDunne. This is likely because 4.0 on macs uses only LF line endings, while 3.3 on Windows is expecting CRLF.

- https://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf/6089413#6089413
- https://gist.github.com/josephwb/df09e3a71679461fc104

**Comment by chrisdembia** [comment]
@jimmyDunne says that it might be the intermediate step of saving the MOT file in Excel that changes the line endings to be incompatible with Windows.

**Comment by jenhicks** [comment]
I think this one is resolved? Closing, but feel free to re-open and add latest status @jimmyDunne
