### ISSUE TITLE
Wrap SimTK::Array_<CoordinateReference> as SimTKArrayCoordinateReference for consistency

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1822]
Not sure whether the intention was to allow use of `InverseKinematicsSolver` in MATLAB, but it isn't currently possible (or, if there is a workaround, it isn't obvious). [The constructor](http://myosin.sourceforge.net/1809/classOpenSim_1_1InverseKinematicsSolver.html#abb7799dcaff64b08356b090689efe02f) takes a reference to `SimTK::Array_<CoordinateReference>` but only a few types of `SimTK::Array_` have been wrapped [in simbody.i](https://github.com/opensim-org/opensim-core/blob/master/Bindings/simbody.i#L211) and `CoordinateReference` is not among them.

See [Forum topic 7965](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=7965). @jimmyDunne's suggestion to use `InverseKinematicsTool` seems appropriate in this scenario, but it might be helpful to use an `InverseKinematicsSolver` directly if, say, iterating to find acceptable marker weights.

**Comment by chrisdembia** [comment]
In my opinion, ff that's the only class that needs to be wrapped for the solver to be useful, then we should add that one line to the appropriate SWIG interface file.

**Comment by jimmyDunne** [comment]
I have written a script for using the IK solver in Matlab. This has worked with only tracking Marker data, but I do create CoordinateRef Objects

```matlab
....
% Create an arry of blank coordinate reference objects
coordref = ArrayCoordinateReference();

% Populate coordinate references object with desired coordinate values
% and weights
for i = 1 : length(coordName)
    coordRef = CoordinateReference(coordName{i} , Constant() );
    coordRef.setWeight(0);
    coordRef.markAdopted();
    coordref.push_back(coordRef);
end
....
%% Instantiate the ikSolver and set some values. 
ikSolver = InverseKinematicsSolver(model,markerref, coordref,constweight);


```

[run_iksolver.m.zip](https://github.com/opensim-org/opensim-core/files/1136516/run_iksolver.m.zip)

**Comment by tkuchida** [comment]
Why are `SimTK::Array_`s of these data types wrapped as `SimTKArrayBlah`
```cpp
%template(SimTKArrayString) SimTK::Array_<std::string>;
%template(SimTKArrayDouble) SimTK::Array_<double>;
%template(SimTKArrayVec3) SimTK::Array_<SimTK::Vec3>;
%template(SimTKArrayInt) SimTK::Array_<int>;
```
but a `SimTK::Array_` of type `CoordinateReference` is wrapped as `ArrayCoordinateReference`?

**Comment by tkuchida** [comment]
Decided to :one: change wrapping from `ArrayCoordinateReference` to `SimTKArrayCoordinateReference` for consistency and :two: add a note to this effect in CHANGELOG.
