### ISSUE TITLE
OpenSim uses Matlab's home dir to run tests, Not one specified by OpenSim

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1829]
When running Matlab tests (locally), `ctest -R Matlab`, the tests get run in the Matlab working directory (set and managed in Matlab), not in opensim-build-dir/Matlab (where we want it to run).

Some Matlab tests use resources copied to opensim-build-dir/Matlab, so will fail. This can be tested with `ctest -R Matlab_Simbody`. 

You can get the tests to pass by opening Matlab and changing the working directory to opensim-build-dir/Matlab.

**Comment by chrisdembia** [comment]
You can also set MATLAB to set its working directory based on the directory where you start it.

**Comment by chrisdembia** [comment]
@jimmyDunne you actually fixed this in #1704:

```
UNITTEST_PRECOMMAND "cd('${matlab_output_dir}')"
```

Consider carrying this fix over to #1434.

**Comment by jimmyDunne** [comment]
Will be fixed when the Matlab PR's are merged.

**Comment by aseth1** [comment]
@jimmyDunne, how about just making this fix separately and getting it merged?

**Comment by jimmyDunne** [comment]
@aseth1 PR at #1917

**Comment by aymanhab** [comment]
@jimmyDunne Can you explain where are these tests located? Thank you

**Comment by jimmyDunne** [comment]
/Bindings/Java/Matlab/tests
