### ISSUE TITLE
[ISB] Provide doxygen for ISB workshop

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1831]
There was some discussion of adding a GUI scripting part to the workshop. If so, it might be helpful to provide participants with the doxygen corresponding to the API version on which the GUI was built. Could post in a semi-permanent location or include in the .zip that is distributed.

**Comment by chrisdembia** [comment]
Internet at a conference may be spotty so ideally, it's in the zip. My mac builds have included the user doxygen. The doxygen is large, so I don't think we should include the developer doxygen.

**Comment by aseth1** [comment]
Sounds good to me. We should also have @apoorvar or @jenhicks briefly explain what it is and how they can find additional commands (methods) there. Very few will be familiar with programming and even fewer will know what Doxygen is.
