### ISSUE TITLE
Model _lengthUnits and _forceUnits generally unused

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1833]
`Model` has `_lengthUnits` and `_forceUnits` members and related properties that are exposed to users. They do not have any effect on the `Model` or its computations and therefore is confusing for users.

I think we should get rid of them in 4.0 to eliminate confusion. For the two cases that  `_lengthUnits` are used (`MarkerPlacer` and `ModelScaler` both deailing with `MarkerData`) these should always be converted to **m**.

**Comment by jimmyDunne** [comment]
The suggestion is to get rid of this. All internals should be meters and newtons.

**Comment by aseth1** [comment]
If there is consensus that we assume all internal units are SI then we can remove these for 4.0.

Next release we can add units to data (in some cases just use existing metadata) and automatic conversion to SI units internally. Right now, marker data in mm is read in and not converted so it is up to the consumer of the data to convert, which is not ideal.

**Comment by jenhicks** [comment]
@aymanhab Will double check GUI usage. If no issues, then we can remove and document that meters, kg, Newtons expected.

**Comment by aymanhab** [comment]
Model.getLengthUnits() is called from 2 places in the GUI to convert trc/MarkerData to model length units. Call sequence:
markerData.convertToUnits(model.getLengthUnits());
Model.getForceUnits() is unused by the GUI.
There's a separate Units class that's used more broadly and shouldn't be removed.
