### ISSUE TITLE
MATLAB initSystem() with setUseVisualizer(true) causes MATLAB crash (simbody-visualizer crashes if OSX_DEPLOYMENT_VERSION > [user's OSX version])

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1835]
This was experienced by one of the participants for the TGCS tutorial. I can provide more details later.

**Comment by jimmyDunne** [comment]
> setUseVisualizer(true)

I have seen this behavior in my code as well. The visualizer instance won't close, and if you force close it, Matlab will crash soon after.

**Comment by chrisdembia** [comment]
Ah it would be great if you could show met this when I get back.

**Comment by tkuchida** [comment]
Possibly related: https://github.com/simbody/simbody/pull/554

**Comment by aseth1** [comment]
@chrisdembia do you have more details to add?

**Comment by apoorvar** [comment]
I'm using Matlab 2015b. My list of commands:
import org.opensim.modeling.*
m = Model();
m.setUseVisualizer(true);
m.initSystem()

At this point, I got a message saying the simbody-visualizer quit unexpectedly. My matlab crash logs are attached.

[matlabCrashLog.txt](https://github.com/opensim-org/opensim-core/files/1853869/matlabCrashLog.txt)
[matlab_crash_dump.95264-1.txt](https://github.com/opensim-org/opensim-core/files/1853870/matlab_crash_dump.95264-1.txt)

**Comment by chrisdembia** [comment]
@jenhicks had the same exact issue.

It's not clear that the original issue from 2017 is the same as the one happening now. Both Jen and Apoorva were on their Macs (Jen: OSX 10.10, Matlab 2017; Apoorva: 10.11, Matlab 2015). I think Travis is building for 10.12. 

We thought the issue might be related to Matlab version, but James had no crash and is using Matlab 2015.

The crash may also be sporadic. Jen had been able to launch a blank visualizer without a crash.

**Comment by chrisdembia** [comment]
@apoorvar reported the following in an email:

> I built the master branch, and ran configureOpenSim.m from that build. With that, the simple test of m.setVisualizer(true) followed m.initSystem() worked fine -- the visualizer opened with a white screen. I then ran the version of InteractiveHopper.m distributed with the GUI build from today, and everything seems to be working as it should. This seems consistent with Ajay's suspicion that the issue may be related to the simbody visualizer distributed with the GUI having been built on OSX 10.12 and me trying to use it on 10.11.
