### ISSUE TITLE
Preview Experimental Data works for Markers OR Forces

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1836]
As separate motion previews.  When attempting to sync motions, markers/forces disappear but the motion player time keeps advancing.

Additionally, making either data file current, afterwards, fails to display the current markers or forces data.

**Comment by aseth1** [comment]
Interestingly it just worked on Mac, but not on Windows 10.

**Comment by jimmyDunne** [comment]
@jenhicks can you please move this to GUI. Three engineers and I couldn't figure it out.

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-gui #339](https://github.com/opensim-org/opensim-gui/issues/339) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jenhicks** [comment]
Ha ... sure. I see a "Move Issue" button in the bottom right that lets me select a repo. Appearance of the button might be permissions based.
