### ISSUE TITLE
Visual Studio reports warnings when building ExampleMain

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1845]
- built and installed opensim-core (Visual Studio 14 2015 Win64)
- copied the contents of OpenSim/Examples/ExampleMain into a new directory
- ran CMake (3.8.2); completed successfully though reported the following warning:
<pre>
CMake Warning (dev) at CMakeLists.txt:14 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.
</pre>
- opened OpenSimTugOfWar.sln and built in RelWithDebInfo mode; Output window reports success though some warnings are displayed:
<pre>
1>------ Build started: Project: ZERO_CHECK, Configuration: RelWithDebInfo x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-buildAgainstOpenSimCoreInstall/build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: exampleMain, Configuration: RelWithDebInfo x64 ------
2>  Building Custom Rule C:/Users/tkuchida/Documents/GitHub/test-buildAgainstOpenSimCoreInstall/CMakeLists.txt
2>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-buildAgainstOpenSimCoreInstall/build/CMakeFiles/generate.stamp is up-to-date.
2>  TugOfWar1_CreateModel.cpp
2>c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\Component.h(2121): warning C4068: unknown pragma
2>c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\Component.h(2122): warning C4068: unknown pragma
2>c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\Component.h(2125): warning C4068: unknown pragma
2>c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\PropertyDblVec.h(145): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
2>  c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\PropertyDblVec.h(141): note: while compiling class template member function 'std::string OpenSim::PropertyDblVec_<3>::toString(void) const'
2>  c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\Scale.h(57): note: see reference to class template instantiation 'OpenSim::PropertyDblVec_<3>' being compiled
2>  exampleMain.vcxproj -> C:\Users\tkuchida\Documents\GitHub\test-buildAgainstOpenSimCoreInstall\build\RelWithDebInfo\exampleMain.exe
3>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
3>  Building Custom Rule C:/Users/tkuchida/Documents/GitHub/test-buildAgainstOpenSimCoreInstall/CMakeLists.txt
3>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-buildAgainstOpenSimCoreInstall/build/CMakeFiles/generate.stamp is up-to-date.
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
</pre>

**Comment by tkuchida** [comment]
CMake warnings fixed in PR #1846.

**Comment by tkuchida** [comment]
Most warnings were fixed by @chrisdembia in #1868, but I still get a C4996:
<pre>
1>------ Build started: Project: ZERO_CHECK, Configuration: RelWithDebInfo x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-exampleMain/build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: exampleMain, Configuration: RelWithDebInfo x64 ------
2>  Building Custom Rule C:/Users/tkuchida/Documents/GitHub/test-exampleMain/CMakeLists.txt
2>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-exampleMain/build/CMakeFiles/generate.stamp is up-to-date.
2>  TugOfWar1_CreateModel.cpp
2>c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\PropertyDblVec.h(145): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
2>  c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\PropertyDblVec.h(141): note: while compiling class template member function 'std::string OpenSim::PropertyDblVec_<3>::toString(void) const'
2>  c:\users\tkuchida\documents\github\opensim-core-install\sdk\include\opensim\common\Scale.h(57): note: see reference to class template instantiation 'OpenSim::PropertyDblVec_<3>' being compiled
2>  exampleMain.vcxproj -> C:\Users\tkuchida\Documents\GitHub\test-exampleMain\build\RelWithDebInfo\exampleMain.exe
3>------ Build started: Project: ALL_BUILD, Configuration: RelWithDebInfo x64 ------
3>  Building Custom Rule C:/Users/tkuchida/Documents/GitHub/test-exampleMain/CMakeLists.txt
3>  CMake does not need to re-run because C:/Users/tkuchida/Documents/GitHub/test-exampleMain/build/CMakeFiles/generate.stamp is up-to-date.
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
</pre>

**Comment by chrisdembia** [comment]
Simbody deals with this warning by ignoring it: https://github.com/simbody/simbody/search?p=2&q=4996&type=&utf8=✓

**Comment by tkuchida** [comment]
> Simbody deals with this warning by ignoring it

Perhaps I should do the same.

**Comment by aseth1** [comment]
I also don't see the harm in us using `sprintf_s instead` as recommended.

**Comment by chrisdembia** [comment]
I think it is difficult to use `sprintf_s` in a cross platform way (https://stackoverflow.com/questions/3976306/using-snprintf-in-a-cross-platform-application); I think the standard has `snprintf`.

**Comment by tkuchida** [comment]
CMake and Visual Studio no longer display any warnings when generating/building ExampleMain.
