### ISSUE TITLE
SimTK::Vec6 is not exposed to PropertyHelper

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1847]
Inertia in 4.0 stream has introduced the first property of type SimTK::Vec6, the type has not been handled similar to Vec3 in PropertyHelper class used for display/editing in GUI.

**Comment by aymanhab** [comment]
Should be addressed by PR #1853

**Comment by tkuchida** [comment]
Fixed by #1853 :racing_car:
