### ISSUE TITLE
No access to the integrator through python

### ISSUE THREAD

**Issue by kidzik** [opensim-org/opensim-core#1849]
I can get
```python
    manager.getIntegrator()
```
but I can't cast it to anything and in particular I can't call `setAccuracy()`. This would be very helpful for our NIPS challenge.
Any hack (not requiring recompiling with the desired accuracy) will be good enough and very appreciated by the participants of the challenge :)

**Comment by jenhicks** [comment]
@aseth1 @aymanhab  ... any ideas? @kidzik I'd also feel free to stop by chat about it.

**Comment by kidzik** [comment]
Thanks! Sure, I will do that. I'm just out of office this week.

**Comment by aymanhab** [comment]
@kidzik SimTK::Integrator class(es) are not exposed, exposing them is not trivial and will require rebuilding the stack. What are you using to integrate? If Tool then there're method(s) to set integration error tolerance, if using Manager then we can add method to wrapping to set tolerance and it wouldn't require rebuilding the OpenSim/SimTK stack but will require rebuilding the bindings.  Please let us know.

**Comment by aseth1** [comment]
A possible hack would be to hijack the `ForwardTool` to take advantage of the Tools having the ability to set these on the integrator as @aymanhab mentioned. You can setup the `ForwardTool` to load the model of interest and set the `<integrator_error_tolerance>` property  (really it is the accuracy). You must then `run()` the `ForwardTool` which will create the `Manager` with your model and desired integration accuracy. Then you can call `getManager()` on the `ForwardTool`. You can wrap this ugliness in a python method like `createIntegrationManager(model, accuracy)` or something like that and warn users to do prior to the optimization loop. You can make the actual duration of the Tool tiny so it takes a step or two at most. Let me know if you need more details.

I cannot think of another way around this issue without exposing the `Integrator` class or adding a method to `Manager`.

**Comment by kidzik** [comment]
Sounds great, I will try it out! Thank you so much!

**Comment by chrisdembia** [comment]
The ability to alter integrator settings from the API has been requested multiple times, and we should support it. To start with, we might be able to wrap only the base Integrator class (https://simtk.org/api_docs/simbody/3.5/classSimTK_1_1Integrator.html). This would allow altering integrator settings but would not allow choosing a specific integrator to use. There are only a handful of functions that would be harder to wrap (e.g., `getEventTransitionsSeen()`).

**Comment by carmichaelong** [comment]
Depending on how we want the `Manager` to be used, we could add methods/constructors to 1) choose integrator type through a string on enum and 2) add only a few core methods (i.e., `setAccuracy` and `getAcurracy`). Doing this would allow the `Manager` to be a little more friendly for scripting users while avoiding too much added complexity.
