### ISSUE TITLE
[doxygen] "More…" links for inherited member functions are broken

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1852]
For example, go to the page for [Millard2012EquilibriumMuscle](http://myosin.sourceforge.net/1846/classOpenSim_1_1Millard2012EquilibriumMuscle.html), expand the "Public Member Functions inherited from OpenSim::Muscle" section, and click "More…" beside one of the methods. The "More…" links should jump to the detailed documentation for the corresponding methods, but the "More…" links work only if the detailed documentation appears on the current page. For example, the link beside `get_max_isometric_force` (a method inherited from Muscle) is
<pre>
http://myosin.sourceforge.net/1846/
classOpenSim_1_1Millard2012EquilibriumMuscle.html
#a1dd6fec51c75d0628fe2b8f130e4e4fc
</pre>
but it should be
<pre>
http://myosin.sourceforge.net/1846/
classOpenSim_1_1Muscle.html
#a1dd6fec51c75d0628fe2b8f130e4e4fc
</pre>
(the head and tail are correct but the thorax is not). Clicking on the method name itself works, so perhaps just remove the "More…" links if that's possible/easy?

**Comment by chrisdembia** [comment]
@jenhicks reported this here: https://github.com/opensim-org/opensim-core/pull/478

What version of doxygen do you have?

I created a doxygen bug report for this a while ago: https://bugzilla.gnome.org/show_bug.cgi?id=753574

I don't remember if I determined that this bug still occurs with a minimal example.

**Comment by chrisdembia** [comment]
I don't know if this other doxygen bug is related: https://bugzilla.gnome.org/show_bug.cgi?id=514557

**Comment by tkuchida** [comment]
> What version of doxygen do you have?

The links above refer to myosin, which uses 1.8.10. I happen to have 1.8.8 on my ~doorstop~ laptop.

> I created a doxygen bug report for this a while ago

Status still says "NEW" :frowning_face:

> I don't know if this other doxygen bug is related

According to the comments on that thread, the issue was resolved in "the latest version of doxygen" as of 2015-02-23 which, [as far as I can tell](ftp://ftp.stack.nl/pub/users/dimitri/), would have been version 1.8.9.1 < 1.8.10.

**Comment by chrisdembia** [comment]
> The links above refer to myosin, which uses 1.8.10. I happen to have 1.8.8 on my doorstop laptop.

Oh right.

> According to the comments on that thread, the issue was resolved in "the latest version of doxygen" as of 2015-02-23 which, as far as I can tell, would have been version 1.8.9.1 < 1.8.10.

Where do you see it say that this issue was fixed in more recent doxygen versions? To my knowledge, this issue is not yet fixed. We merged #478 despite the presence of this bug.

**Comment by tkuchida** [comment]
> Where do you see it say that this issue was fixed in more recent doxygen versions?

You posted two comments to this thread. My reply "According to the comments on that thread…" was in response to your (quoted) comment "I don't know if this other doxygen bug is related", where "this other doxygen bug" is [this one](https://bugzilla.gnome.org/show_bug.cgi?id=514557). Here are the comments I see on that thread, from which I hypothesize (1) that "this other doxygen bug" has been resolved and (2) the resolution appeared in version 1.8.9.1 which precedes the version used on myosin.

![doxygen](https://user-images.githubusercontent.com/4203505/28868803-6c365956-772f-11e7-9339-27854914cfcb.png)

My reply "Status still says 'NEW' " was in response to your first comment about [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=753574).

> To my knowledge, this issue is not yet fixed.

I agree.

**Comment by chrisdembia** [comment]
Ah okay; I got confused. Sorry about that.

**Comment by jenhicks** [comment]
This seems to be fixed on the posted doxygen ... closing.
