### ISSUE TITLE
ScaleTool not scaling ligaments

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#186]
ScaleTool doesn't handle ligaments as PathActuators. They are treated as any other force and are not scaled. The entire ligament class is causing some confusion and probably requires a redesign in the long run. However,  what would be the best option for this bug?

(a) release a 'patch' plugin asap?
(b) Address the bug in a 3.3 release?
(c) Describe an API workaround (from Glenn Litchwark) on confluence and just fix for 4.0?

**Comment by aymanhab** [comment]
Will be fixed by PR #538

**Comment by aseth1** [comment]
I agree it will be "fixed" in the sense that Ligaments will now be scaled (as necessary for 3.3), but the fact that Muscle and Ligaments are treated specially by Model scares me. It points out that anything else (e.g other Forces)  that  span two or more bodies will not be scaled. 

We still need a solution that addresses the broader problem.

**Comment by jenhicks** [comment]
@aseth1 I think that Issue #557 captures the remaining problems (if not, please add additional comments). Given that, I'm closing this one.
