### ISSUE TITLE
Convert OpenSim numeric types to MATLAB matrices

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1882]
Converting OpenSim Vectors into MATLAB matrices is challenging but is a common task.

MATLAB supports converting java arrays to matrices:

```
cell2mat(cell(javaArray))
```

We already have a converter from `Vec3` to a java array here: https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/swig/java_simbody.i#L20.

This means that one can do the following right now in MATLAB:

```
cell2mat(cell(vec3.getAsJavaArray()))
```

This is still very verbose, but perhaps we could create a utility function `osimMakeMatrix()` or something like that.

@tkuchida and I just looked into this together.

Links:

- https://www.mathworks.com/help/matlab/matlab_external/access-elements-of-java-array.html
- https://www.mathworks.com/help/matlab/ref/javaarray.html
- https://www.mathworks.com/help/matlab/matlab_external/how-matlab-represents-java-array.html
- https://www.mathworks.com/matlabcentral/newsreader/view_thread/169936

**Comment by jimmyDunne** [comment]
This is very cool. I can prototype it if that's okay?

**Comment by chrisdembia** [comment]
> I can prototype it if that's okay?

Yay! We might need to discuss with the group about what interface would be best, etc., but prototyping is definitely in order.

We could also add a similar `getAsJavaArray()` for `Vector` (or `VectorBase` or something) in the SWIG interface files.

It's also possible that MATLAB has even nicer conversion functions than having to call both `cell2mat()` and `cell()`. Maybe we should ask on the MATLAB forums.

**Comment by chrisdembia** [comment]
By the way, going from a MATLAB matrix to an OpenSim Vector should be easier, based on those links above; we simply need to add a constructor to Vector that takes a java array, and MATLAB will automatically convert a MATLAB matrix to a java array for us. That means it should be possible to do:

```
v = Vector(matlabMatrix)
```

**Comment by tkuchida** [comment]
I don't see a `Vec3::getAsJavaArray()` method in OpenSim 3.3, but this hack works:
```
v = Vec3(1,2,3);
matlabVec = eval(v.toString().substring(1));
```

**Comment by scrum2a** [comment]
@aseth1 Allow getting a single table column as a Matlab matrix.

**Comment by carmichaelong** [comment]
Check out section 25.8.3 at the following link (Wrapping C arrays with Java arrays): http://www.swig.org/Doc3.0/Java.html#Java_typemaps_c_to_java_types
