### ISSUE TITLE
Add comment to Component::getAbsolutePathName() about computational expense

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1883]
[The doxygen for `Component::getAbsolutePathName()`](http://myosin.sourceforge.net/1879/classOpenSim_1_1Component.html#a88a3212416a4d5a9387e395e54d4d8ae) doesn't indicate that [it assembles the absolute path on-the-fly](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L641). Issues:

1. `getAbsolutePathName()` is close to `getName()`; the latter is "free" so users may expect the former to be "free" as well. The cost of calling `getAbsolutePathName()` is a function of the depth of the ownership tree (the Model's ownership tree should be flattened as much as possible to optimize performance).
2. `getAbsolutePathName()` creates a `std::vector<std::string>` and prepends parent names using `insert()` until the root node is reached, which is more work than might be expected. Prepending is particularly expensive (from http://www.cplusplus.com/reference/vector/vector/insert/: "Because vectors use an array as their underlying storage, inserting elements in positions other than the vector end causes the container to relocate all the elements that were after position to their new positions.").

In the past, names were (assumed to be) unique and were "free" to retrieve so were ideal for using as unique IDs (e.g., keys into maps). The unique ID is now the absolute path name but it isn't "free" to retrieve so using it as a key will be inefficient—particularly important for users doing optimization.

I suggest adding a note to the doxygen for `Component::getAbsolutePathName()` indicating that it shouldn't be used if efficiency is critical. In the future, the absolute path name could be cached.

**Comment by chrisdembia** [comment]
I think it would be nice to actually just speed it up using a linked list or something instead of an `std::vector`.

**Comment by tkuchida** [comment]
> I think it would be nice to actually just speed it up using a linked list or something instead of an `std::vector`.

That would be good, too, but if the absolute path name isn't being cached, I think the doxygen should warn users that it isn't free like `getName()`. I think it's natural to just replace `getName()` with `getAbsolutePathName()` since the former is no longer guaranteed to be unique, but these methods aren't really interchangeable if efficiency is important.

**Comment by carmichaelong** [comment]
`std::deque` may also be an option here.

**Comment by carmichaelong** [comment]
I did testing to benchmark performance. 

**Setup**
Using `testComponentInterface.cpp`, I created a `Component` with a depth of 5 as follows:
```
    TheWorld* A = new TheWorld();
    TheWorld* B = new TheWorld();
    TheWorld* C = new TheWorld();
    TheWorld* D = new TheWorld();
    TheWorld* E = new TheWorld();
    A->setName("a");
    B->setName("b");
    C->setName("c");
    D->setName("d");
    E->setName("e");

    A->add(B);
    B->add(C);
    C->add(D);
    D->add(E);
```

**Benchmark**
Called `Component::getAbsolutePathName()` on each level, repeated 1 million times.
```
    std::clock_t loopStartTime = std::clock();
    int numLoops = 1000000;
    for (int i = 0; i < numLoops; ++i) {
        A->getAbsolutePathName();
        B->getAbsolutePathName();
        C->getAbsolutePathName();
        D->getAbsolutePathName();
        E->getAbsolutePathName();
    }

    std::clock_t loopEndTime = std::clock();
    double loopClocks = loopEndTime - loopStartTime;
    cout << "getAbsolutePathName elapsed time = " << loopClocks / CLOCKS_PER_SEC << "s" << endl;
```

**Results**
- As is (`getAbsolutePathName()` fills a `std::vector`, `Path` backed by `std::vector`): 3.9 seconds
- `getAbsolutePathName()` fills a `std::deque`, `Path` backed by `std::vector` (note that this involves an extra `std::copy` step): 5.8 seconds
- `getAbsolutePathName()` fills a `std::list`, `Path` backed by `std::vector` (note that this involves an extra `std::copy` step): 5.4 seconds
- `getAbsolutePathName()` fills a `std::deque`, `Path` backed by `std::deque` (no extra copy): 7.1 seconds
- `getAbsolutePathName()` prepends using only `std::string`: 0.8 seconds

Results seem to indicate that construction/destruction is the biggest overhead (and that moving all elements in an `std::vector` for only 5 elements is small compared to construction/destruction).

**Comment by chrisdembia** [comment]
So thorough! 

If you back the `Path` with `std::deque` and add a `Path::prependPathElement()`, I wonder if you could avoid the copy and achieve similar speed as prepending to an `std::string`. Though I think it is nice to have the `Path(const std::vector&)` constructor.

Also, you might be able to use a move constructor to avoid the copy (by defining a custom copy constructor, the move constructor is deleted).

**Comment by tkuchida** [comment]
I thought that `std::deque` would be fastest since it doesn't require contiguous memory, but it looks like a plain `std::string` is faster. I don't know the details of how memory is allocated for storing `std::string`s, but I could imagine a small increase in time if the Component names are long (in which case the new concatenated string might not fit in the old memory).

**Comment by carmichaelong** [comment]
> I thought that std::deque would be fastest since it doesn't require contiguous memory

I thought so too, so these results surprised me. It does point to the strength of an `std::vector` that it's pretty cheap to destruct, even in comparison to `std::deque`. Seems that some things I didn't even expect to be an issue become an issue in containers with very few elements.

**Comment by aseth1** [comment]
I think `std::string` can maintain short strings internally without additional allocation as part of *short string optimization*. You may retry your test with longer names.

Did a quick test in IDEONE:
Output:
```
Success	#stdin #stdout 0.08s 15240KB
string append elapsed time = 0.08322s to produce '/a/b/c/d/e'.

Success	#stdin #stdout 0.18s 15240KB
string append elapsed time = 0.184341s to produce '/abcdefghijklmnopqrst/bcdefghijklmnopqrstu/cdefghijklmnopqrstuv/defghijklmnopqrstuvw/efghijklmnopqrstuvwx'.
```

Code:
```cpp
int main() {
    vector<string> names{
    	"a", //bcdefghijklmnopqrst"
    	"b", //cdefghijklmnopqrstu"
    	"c", //defghijklmnopqrstuv"
    	"d", //efghijklmnopqrstuvw"
    	"e", //fghijklmnopqrstuvwx"
    };
	
    std::clock_t loopStartTime = std::clock();
    int numLoops = 1000000;
    string abcde{};
    
    for (int i = 0; i < numLoops; ++i) {
        abcde = "";	
        for (auto& name: names) {	
	abcde += ("/" + name);
        }
    }

    std::clock_t loopEndTime = std::clock();
    double loopClocks = loopEndTime - loopStartTime;
    cout << "string append elapsed time = " << loopClocks / CLOCKS_PER_SEC << "s ";
    cout << "to produce '" << abcde <<"'." << endl;
  
    return 0;
}
```

**Comment by carmichaelong** [comment]
Good point. I've extended the names to be 20 characters long (i.e. `"a2345678901234567890`). I also wanted to get at the construction/destruction of a container problem more closely, so I avoided using the `ComponentPath` interface altogether and just using one container (i.e., `vector`, `deque`) in `getAbsolutePathName()`.

Times are averaged over 10 trials:
- `string` only: 2.6 seconds
- Store elements in `deque`, then write out to `string` (access through [] operator): 7.2 seconds
- Store elements in `vector`, then write out to `string` (access through [] operator): 6.1 seconds

**Comment by tkuchida** [comment]
@carmichaelong Have you compared the speed of `getName()` and `getAbsolutePathName()`? The difference is the speedup we would expect from caching the absolute path (and the cost of replacing `getName()` with `getAbsolutePathName()` in user code).

**Comment by aseth1** [comment]
@tkuchida out of curiosity, what was the the time frame for your solver to find an optimal fit (solution) and about how many objective function evaluations does it take, approximately?

**Comment by tkuchida** [comment]
Okay, I see your point @aseth1. I will work on improving my algorithm.

**Comment by aseth1** [comment]
@tkuchida  I was thinking more to tune the  @carmichaelong's benchmark to match approximately the same number of "bodies" and number of evaluations and compare that time to your total time. I have no idea what fraction it would account for, but if it is in the order or 1-2% or less, then perhaps caching is not warranted?

**Comment by carmichaelong** [comment]
For a feel of caching, I ran this benchmark:

```
    double avgTime = 0;
    int numTrials = 10;
    int numLoops = 1000000;
    for (int trial = 0; trial < numTrials; ++trial) {
        std::clock_t loopStartTime = std::clock();
        for (int i = 0; i < numLoops; ++i) {
            A->getAbsolutePathName();
            B->getAbsolutePathName();
            C->getAbsolutePathName();
            D->getAbsolutePathName();
            E->getAbsolutePathName();
        }
        std::clock_t loopEndTime = std::clock();
        double loopClocks = loopEndTime - loopStartTime;
        avgTime += loopClocks / CLOCKS_PER_SEC;
    }

    cout << "getAbsolutePathName avgTime = " << avgTime / numTrials << "s" << endl;

    avgTime = 0;
    for (int trial = 0; trial < numTrials; ++trial) {
        std::clock_t loopStartTime = std::clock();
        for (int i = 0; i < numLoops; ++i) {
            A->getName();
            B->getName();
            C->getName();
            D->getName();
            E->getName();
        }
        std::clock_t loopEndTime = std::clock();
        double loopClocks = loopEndTime - loopStartTime;
        avgTime += loopClocks / CLOCKS_PER_SEC;
    }

    cout << "getName avgTime = " << avgTime / numTrials << "s" << endl;
```

Output is as follows:
```
getAbsolutePathName avgTime = 2.5922s
getName avgTime = 0.0087s
```

I think this means that even if we don't get to a solid caching mechanism for this release, it should be a priority for future releases.

**Comment by tkuchida** [comment]
> @tkuchida I was thinking more to tune @carmichaelong's benchmark to match approximately the same number of "bodies" and number of evaluations and compare that time to your total time. I have no idea what fraction it would account for, but if it is in the order or 1-2% or less, then perhaps caching is not warranted?

I fundamentally disagree with making an API design decision based on my specific use case. I don't know what percentage of time is spent fetching absolute paths, but I am designing my code to avoid calling `getAbsolutePathName()` since I know it isn't free (my suggestion at the top of this Issue was simply to add a note to the documentation so other developers know this, too). Fetching a unique ID seems sufficiently common to be concerned about its efficiency, particularly when the old method via `getName()` was free. It seems like caching the absolute path would be in line with the design philosophy behind `finalizeFromProperties()` and `finalizeConnections()`, but I'm sure there's a good reason for generating absolute paths on-the-fly.

**Comment by tkuchida** [comment]
I noticed that `getAbsolutePathName()` is called only 10 times in opensim-core, so unless the GUI or typical user code is substantially different, this Issue may be much ado about nothing.

**Comment by aymanhab** [comment]
It is called by the GUI when creating the visualization (these are the names you see on the scene graph in Expert mode) but these calls are made once per object during construction, afterwards the GUI creates a unique UUID to use from then on.

**Comment by aseth1** [comment]
> I suggest adding a note to the doxygen for Component::getAbsolutePathName() indicating that it shouldn't be used if efficiency is critical. In the future, the absolute path name could be cached.

I agree with adding a comment that says "the AbsolutePathName is generated by traversal and is not free".

**Comment by tkuchida** [comment]
> I agree with adding a comment that says "the AbsolutePathName is generated by traversal and is not free".

I will do this. The methods that call `getAbsolutePathName()` (including `findComponent()`, `traversePathToComponent()`, `connect()`, `markAsPropertySubcomponent()`, and `Model::createMultibodyTree()`) all seem to be intended for pre-simulation use where speed isn't critical anyway.

**Comment by tkuchida** [comment]
Thanks for the analyses, @carmichaelong! Please reopen if you think this Issue should be tracked.

**Comment by aseth1** [comment]
In dev meeting yesterday @carmichaelong proposed implementing a getAbsolutePath() to replace places in the code where the ComponentPath is being created from the absolute path name based on discussion with @chrisdembia . We also agreed that the getAbsolutePathName() should use strings since using the intermediate data structures is a hidden implementation detail. The comment in doxygen is still valid. @carmichaelong is that still on your agenda?

**Comment by carmichaelong** [comment]
@aseth1 Yes, I was still planning on doing this. Seems like it would still be useful to go along with the extra documentation merged earlier.
