### ISSUE TITLE
method MarkerSet.addMarker is broken and should be removed.

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1888]
Encountered in GUI upgrade to latest API, also mentioned in recent forum post using 3.3 
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=8150&p=0&start=0&view=&sid=ddcb954dec2305a20593deb46d5514ba

**Comment by tkuchida** [comment]
@aymanhab Please let me know if my response to the Forum question is incorrect. If so, I will delete my response. Thanks.

**Comment by aymanhab** [comment]
Your response is perfectly fine, I think the user problem is primarily  caused by not using references (&)  resulting in copies of Body, MarkerSet. Your proposal fixes both problems. Thanks @tkuchida

**Comment by tkuchida** [comment]
😌 Thanks, @aymanhab

**Comment by aseth1** [comment]
`MarkerSet::addMarker()` uses `Marker::setFrameName()` and it likely related to #1889. I agree it should go since no other "Set<C>" has an addC() method AFAIK. It also redundant with `Model.addMarker()`.

**Comment by aseth1** [comment]
closed by #1898
