### ISSUE TITLE
testCMCWithControlConstraintsRunningModel in Debug times out on Travis CI

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#1891]
Seems to be happening more frequently now.

**Comment by aseth1** [comment]
This isn't critical for 4.0 but would be good to address quickly so CI can pass consistently.

**Comment by chrisdembia** [comment]
IMO We should just exclude this test for now.

**Comment by aseth1** [comment]
> IMO We should just exclude this test for now.

Sure. Let's do that.
