### ISSUE TITLE
Confusing message on component renaming

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1904]
Trying to run testContext test case I got the message below in the console. Is this expected?

GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathwrap_0'. The duplicate was renamed to 'pathwrap_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathwrap_1'. The duplicate was renamed to 'pathwrap_1'.

**Comment by aseth1** [comment]
Closed by #1906
