### ISSUE TITLE
RuntimeError: std::exception in 'OpenSim::Storage::Storage(std::string const &)': Storage: ERROR- failed to open file <file>.sto

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#1905]
Hi all 

I'm trying to make a function that returns the states trajectory in my models doing IK inside the function, as presented above:
```
def IK(model, IK_setupfile, IK_results):
    ## Inverse Kinematics
    iktool = osim.InverseKinematicsTool(Dir + IK_setupfile)
    iktool.setModel(model)
    iktool.setOutputMotionFileName(IK_results)
    iktool.run()
    model.initSystem()
    sto = osim.Storage(IK_results)
    states = osim.StatesTrajectory.createFromStatesStorage(model,sto)
    return states
```

Unfortunately, I got the next error: 

> RuntimeError: std::exception in 'OpenSim::Storage::Storage(std::string const &)': Storage: ERROR- failed to open file <file>.sto

I've tried to call directly and results are the same, I checked that the file read really exist and I don't know why this error is produced. 

Thanks.

**Comment by nikorose87** [comment]
I based on the examples in the doxygen for `StatesTrajectory`

**Comment by chrisdembia** [comment]
The error message indicates that the value of the `IK_results` variable is `.sto`.

**Comment by nikorose87** [comment]
Yes Chris, in fact, this routine creates the `.sto` after IK, and after verifying it, I don't know why `Storage` produce this error if the file exist in the format given by IK

**Comment by nikorose87** [comment]
This is a more complete description of the error: 
```
IO.OpenInputFile(const string&,openmode mode): failed to open IK2354APIresults.sto
Traceback (most recent call last):
  File "/home/nikorose/Dropbox/PythonProjects/Opensim_clean_algorithm.py", line 59, in <module>
    InvKinematics = IK(model, IK_setupfile, IK_results)
  File "/home/nikorose/Dropbox/PythonProjects/Opensim_clean_algorithm.py", line 37, in IK
    sto = osim.Storage(IK_results)
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/common.py", line 3815, in __init__
    this = _common.new_Storage(*args)
RuntimeError: std::exception in 'OpenSim::Storage::Storage(std::string const &)': Storage: ERROR- failed to open file IK2354APIresults.sto

Process finished with exit code 1
```

**Comment by nikorose87** [comment]
I was able to do it with ID, but not with IK. Is it because IK file is in degrees and ID in radians?

**Comment by nikorose87** [comment]
I found my error, It didn't read the local directory, I should specify all the dir location.
