### ISSUE TITLE
Joint::scale() makes assumption about parent/child frame type that is inconsistent with the definition of its parent_frame and child_frame properties

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1913]
[`Joint::scale()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Joint.cpp#L297) assumes the parent_frame and child_frame are of type `PhysicalOffsetFrame` but [they can actually be any `PhysicalFrame`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Joint.h#L115). The convenience constructor [creates `PhysicalOffsetFrame`s](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Joint.cpp#L85), but any concrete `PhysicalFrame` (i.e., `PhysicalOffsetFrame`, `Body`, or `Ground`) could be used as the parent_frame or child_frame. In some situations, this inconsistency could cause `Joint::scale()` to either throw an exception or have unexpected behavior (note that `SimTK_DYNAMIC_CAST_DEBUG` becomes `static_cast` in Release mode).

**Comment by tkuchida** [comment]
The same code (and assumption) appears in `TwoFrameLinker::scaleFrames()`.

**Comment by aseth1** [comment]
To be fair, the `Joint` only attempts to scale frames that it owns. These are the frames created by the `Joint` to represent the parent and child frames when offsets (location, orientation) are provided, which are exclusively `PhyscialOffsetFrames`. There is a possibility of adding other `Frame`s to a `Joint` but they would have to have the same name as the name as the parent or child.

I agree that his could be cleaner and we could that simply by using `getComponent<PhysicalOffsetFrame>(parentName)` instead for doing a find and a cast.

**Comment by tkuchida** [comment]
> To be fair, the `Joint` only attempts to scale frames that it owns.

It looks inconsistent to me, but I see your point.

**Comment by aseth1** [comment]
I agree it is inconsistent and worth fixing. There is still a bug that if manually adding a `Body` to the `Joint` (which is unusual but possible) and then setting the parent or child `Socket` to that frame the `SimTK_DYNAMIC_CAST_DEBUG` would fail or have unexpected behavior.

**Comment by tkuchida** [comment]
I looked into this again and the Joint's `frames` list property ([here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/Joint.h#L105)) as well as the `parent_frame` and `child_frame` properties are allowed to be any `PhysicalFrame`. I don't understand your response "To be fair, the `Joint` only attempts to scale frames that it owns." Perhaps we can discuss why the current design is correct. I will try to write a test for this to support my argument.

**Comment by aseth1** [comment]
That's  why I kept it open as a bug. What I meat by my initial comment was that the current implementation is *not as bad* as one might expect. I would expect from your description that if I connected a`Joint` to a `Body`  that I would get a failure during scale. This is not the case in general. It can only fail if the `Body` is added to the `Joint` and it is also either the parent or child frame.

**Comment by tkuchida** [comment]
> What I meant by my initial comment was that the current implementation is *not as bad* as one might expect. I would expect from your description that if I connected a`Joint` to a `Body`  that I would get a failure during scale. This is not the case in general.

I'm sorry my description was misleading. I have edited the title and description of the Issue. testScale passes, so of course `Joint::scale()` must be working in the typical cases.

> It can only fail if the `Body` is added to the `Joint` and it is also either the parent or child frame.

Yes, this is what I was attempting to do in my code. I believe other modeling software (e.g., MSC Adams) *always* introduces new parent/child frames for joints, so it seems like it would be okay (preferable, in my opinion) to always attach a Joint's parent_frame and child_frame Sockets to PhysicalOffsetFrames (even if the offset would be zero relative to the base Frame). This approach might introduce a few extra PhysicalOffsetFrames, but the topology of the Model would be consistent and predictable. It would also be easier to adjust the location of a Joint (would require changing only the offset property, not the topology).

**Comment by aseth1** [comment]
I don't think it is necessary to require `Socket<PhysicalOffsetFrame>`. Just using `getComponent<PhysicalOffsetFrame>` and limiting the `frames` to properties to be `PhysicalOffsetFrame` eliminates the problem.

**Comment by tkuchida** [comment]
> I don't think it is necessary to require `Socket<PhysicalOffsetFrame>`.

I agree. I wasn't claiming that it is necessary to change the type of the parent_frame and child_frame Sockets to address this Issue, but I think that design might offer advantages. All Joints would always attach two objects of the same type, leading to consistency in the API and user interaction/mental model. Adjusting the position of a Joint requires a different process if its parent or child Frame happens to be a Body or Ground rather than a PhysicalOffsetFrame. Thus, in some cases, the process will depend on an arbitrary decision made by the modeler (e.g., whether they used the convenience constructor when creating the Joint), the age of the model, etc., which I think is undesirable. In general, it will be necessary to create a PhysicalOffsetFrame even if attaching to a Body's origin in order to correctly orient the Joint, so it doesn't seem like we would lose much by prohibiting direct attachment to a Body or Ground.

I apologize for belaboring this point, but the meaning and definition of parent and child frames is a common source of confusion; consistency might be helpful.
