### ISSUE TITLE
Model.formStateStorage doesn't handle inDegrees

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1924]
The method Model.formStateStorage assumes that the provided Storage object is in Radians, and provides no warning if that wasn't the case. Trying to use it from the GUI on a Storage built from .mot file produces wrong motion. Solution is to either document this behavior, or warn if inDegrees is true on input (with suggestion for how to fix).

**Comment by jenhicks** [comment]
@aseth1 Will document and throw that the storage passed in should be in internal units (radians).
