### ISSUE TITLE
Can't import opensim 

### ISSUE THREAD

**Issue by zzd1992** [opensim-org/opensim-core#1933]
I work on ubuntu 14.04. I install opensim from source. I follow "On Ubuntu using Unix Makefiles" step by step and everything looks OK. But when I run
```
python -c "import opensim"
```
It simply returns
```
ImportError: No module named opensim
```
I am sure I add PATH variable correctly. So what's wrong?

**Comment by chrisdembia** [comment]
Try copying this script into your terminal: https://github.com/opensim-org/opensim-core#for-the-impatient-ubuntu

**Comment by chrisdembia** [comment]
Also, make sure to set LD_LIBRARY_PATH to contain the location to OpenSim's `.so` files.

**Comment by jenhicks** [comment]
Closing since we did not hear back from the user. Please let us know if you are still having issues.
