### ISSUE TITLE
Add transformColumns() method to DataTable<vec3>

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1936]
Addresses enhancement discussed in #1925.

Adding a C++ side method to rotate data stored in Vec3 Tables would improve the ease of transforming marker a force data between coordinate systems with additional speed benefits. 

Ajay suggested a method like;
>DataTable<Vec3>::transformColumns(const SimTK::Transform& X)

**Comment by nickbianco** [comment]
> with additional speed benefits.

I'm currently using the `osimC3D.m` utility and I'm finding that rotating a C3D file with data collected for longer than a few seconds is too long to be practical. So this speed up will be appreciated :)

**Comment by nickbianco** [comment]
And by "longer than a few seconds", I mean I've tried files ~60 seconds long
