### ISSUE TITLE
SWIG bindings should work with Java 9

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1953]
In the short term, we can update the README to say `brew cask install java8`, perhaps in a new "For Mac OSX 10.13 High Sierra" section.

**Comment by chrisdembia** [comment]
In my brief testing, `brew cask install java8` doesn't work because the "java8" cask doesn't exist. Also, I think the issue is that CMake does not yet support finding Java 9 on macOS. I propose we wait a little bit to see if CMake makes a release soon that supports Java 9.

**Comment by jimmyDunne** [comment]
https://stackoverflow.com/questions/26252591/mac-os-x-and-multiple-java-versions

```
brew tap caskroom/versions
brew cask search java
brew cask install java8
```

**Comment by chrisdembia** [comment]
Ah; thanks.

**Comment by chrisdembia** [comment]
CMake 3.10 will have a fix for this.

https://gitlab.kitware.com/cmake/cmake/issues/17325
