### ISSUE TITLE
Need ScaleTool to write intermediate files to user specified directory

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1957]
Running Scale on the gait2354 model using provided setup files on Windows in GUI produced the following files in the OpenSim installation folder:

- subject01_simbody
- subject01_static_output
- Unassigned (file with Markers)
- subject01_scaledOnly
- subject01_scaleSet_applied.

On osx the working directory is the root folder and so is not writable. Need to

1. Decide what files are useful and need to write based on users feedback
2. A way to specify where the files are written

**Comment by jenhicks** [comment]
Don't output Unassigned. 

Default of the tool: write to the same folder as set-up file. If tool is run in from the GUI, will prompt.

**Comment by aymanhab** [comment]
@aseth1 will check

**Comment by aseth1** [comment]
closed by #2003

**Comment by tkuchida** [comment]
From @aymanhab via https://github.com/opensim-org/opensim-gui/issues/401: "We need to decide behavior if files are specified in xml or else why the failure on osx." :apple:

**Comment by aymanhab** [comment]
@aseth1 Using the latest osx build with the supposed fix does not write the intermediate files to the directory of the setup file, instead it fails with 

Exception:
  SimTK Exception thrown at Xml.cpp:115:
  Error detected by Simbody method Xml::writeToFile(): Failed to write to the
  Xml file 'subject01_scaledOnly.osim' with error ' (line=1, col=1)'.
  (Required condition 'saveOK' was not met.)

  In Object '<no-name>' of type ModelScaler.
  Thrown at ModelScaler.cpp:332 in processModel().
  line= 0


can you please explain if it should have worked or if the files (included in Modesl/Gait2392_Simbody) need an update? Thanks.

**Comment by aseth1** [comment]
Are you able to confirm that it isn't trying to write to the setup file directory? It isn't clear to me where it is trying to write instead.
