### ISSUE TITLE
Expose Rotation methods in Matlab

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1958]
Biomechanical frames are computed from vectors derived from experimental marker locations. I would like to use these vectors to define a `Rotation()` object in Matlab. The method that looks most likely to help me is `setRotationFromTwoAxes()`, however this seems to not be wrapped. The `Unitvector()` object also is needed and doesn't seem to be callable in Matlab.

**Comment by jimmyDunne** [comment]
`setRotationFromTwoAxes()` is in SWIGSimTK/Rotation.h, but it isn't functioning in Matlab. @aseth1 Could you give me a hint on the problem and I can try to fix?

**Comment by chrisdembia** [comment]
I just created a PR to wrap `setRotationFromTwoAxes()`.

`UnitVec3` should be available.

**Comment by jimmyDunne** [comment]
[You're the best!](https://www.youtube.com/watch?v=oomCIXGzsR0&feature=youtu.be&t=60)
