### ISSUE TITLE
Update NOTICE file to reflect GUI change to Apache license

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1960]
If you use the OpenSim GUI, you must acknowledge the OpenSim project where
appropriate, by citing the following paper. If you only use the OpenSim API, you
are not required to acknowledge us, but we would be extremely grateful if you
did so anyway.

**Comment by chrisdembia** [comment]
@aseth1 did you express interest in doing this? Let me know; otherwise, I'll propose a revision.

**Comment by aseth1** [comment]
@chrisdembia please go ahead and propose a revision. I would like us to include relevant publications since the 2007 paper is quite outdated with regards to the API including Simbody. I can add that.
