### ISSUE TITLE
Matlab ctest failure unless Model() called

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1969]
Seen in #1967 

I have to instantiate a model or ctest will record a faiure for this test. The test script works without issue if run stand-alone in Matlab. 

test:
```
%% clear working space
clear all;close all;clc;
%% import opensim libraries
import org.opensim.modeling.*
% Adding a call to Model(). If Model() is not instantiated, the test fails.
m = Model();
%% Define an abriatory an OpenSim Vec3 instance
ov = Vec3(2,3,4);
% Convert to a Matlab Vector
mv = osimVec3ToArray(ov);
 % Convert back to an OpenSim Vec3
n_ov = osimVec3FromArray(mv);
% Convert back to an OpenSim Vec3 Type
n_mv = osimVec3ToArray(n_ov);

%% Test the changes for consistency
% Test OpenSim Vec3() instances
if n_ov().get(0) ~= ov().get(0) | n_ov().get(1) ~= ov().get(1) | n_ov().get(2) ~= ov().get(2)
    error('OpenSim Vec3s are different. Should be the same')
end
% Test Matlab Vector instances
if ~isequal(mv,n_mv)
    error('Matlab arrays are not equal between conversions')
end
disp('Test Passed!')

```

exception if line 6 of test (m = Model()) is commented out:
```
107: An exception has been thrown during the execution
107:   JavaException with properties:
107: 
107:     ExceptionObject: [1x1 java.lang.UnsatisfiedLinkError]
107:          identifier: 'MATLAB:Java:GenericException'
107:             message: 'Java exception occurred: ...'
107:               cause: {}
107:               stack: [1x1 struct]
107: 
```
If line is 6 is not commented out, the test passes (and prints 'Test Passed' to console in verbose mode).

**Comment by aymanhab** [comment]
The loadLibrary call that actually loads the JNI dynamic library is invoked in the static block (and is invoked) only if you instantiate an OpenSim type of object, I don't think it's specifically Model, we can add a similar block for the Simbody "module" if it makes sense.

**Comment by chrisdembia** [comment]
This issue is fixed now:

https://github.com/opensim-org/opensim-core/blob/443db92bf5393e0390b5af90f4993adb27392236/Bindings/Java/swig/java_preliminaries.i#L3-L43
