### ISSUE TITLE
Handle unsupported mesh files more gracefully

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1976]
@aymanhab commented on [Thu Aug 03 2017](https://github.com/opensim-org/opensim-gui/issues/354)

As of now the SimTK::PolygonalMesh::loadVtpFile method throws an exception that is not propagated to Java, which results in models failing to visualize at all if they have one invalid (e.g. binary vtp) mesh file. This seems too drastic. It should be skipped over if the exception is handled correctly and is passed to GUI as checked exception. Example models (Rajagopal2015, Hamner2010).

---

@tkuchida commented on [Sat Aug 05 2017](https://github.com/opensim-org/opensim-gui/issues/354#issuecomment-320455737)

Where possible, we should replace binary vtp files with geometry that can be loaded, particularly for these popular models. [Sports.osim](https://simtk.org/projects/simgym) is another example (mentioned in #334).

---

@chrisdembia commented on [Thu Aug 31 2017](https://github.com/opensim-org/opensim-gui/issues/354#issuecomment-326391750)

Python script to convert file formats with VTP: https://gist.github.com/thomasballinger/1281457

**Comment by aseth1** [comment]
closed by #1997.  Added [issue ](https://github.com/opensim-org/opensim-models/issues/38) to Models repo to convert binary vtp files to ascii format for existing models.
