### ISSUE TITLE
testComponents: Coordinate does not pass

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#198]
I played around a little with trying to get Coordinate through testComponents. The issue is that Coordinate::finalizeFromProperties() does error-checking on Coordinate's properties, but it is called in it is called in Component::Component(), before Coordinate::constructProperties() is called.

Here are possible issues, with their solutions:
1. finalizeFromProperties() should not be checking errors for the properties (out of bounds, etc.). Solution: the error checking should be placed somewhere that is called after Coordinate::constructProperties().
2. Coordinate::constructProperties() should be called before Coordinate::finalizeFromProperties(). Solution: Let subclasses call finalizeFromProperties on their own?
3. Constructors should not call virtual methods (Component::Component() calls the virtual finalizeFromProperties()). Solution: I'm not sure...

It seems that (3) is the issue, given prior discussion related to constructInfrastructure(). In that case, we should figure out another way for subclasses to get constructed properly before addressing this specific issue.

**Comment by jenhicks** [comment]
@chrisdembia If you are still having issues with this that are affecting your work, let us know and we could elevate.

**Comment by chrisdembia** [comment]
No need to elevate.
