### ISSUE TITLE
Print .log files to OpenSim Home Dir rather than working directory

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1980]
If you have multiple projects you end up getting .log files printed in every working directory you use. I did a search of my system and found 50 unique OpenSim generated log files. Is it possible to have an option to restrict all .log files to be kept in the OpenSim home dir?

**Comment by chrisdembia** [comment]
I have mixed feelings about the log files. On one hand, I find them to be valuable recordkeeping of runs of OpenSim I've done in the past, and for them to persist, it's useful for them to be written in the directory in which I ran the tool.

On the other hand, they can be cluttering and unexpected.

I would also like to change their names to `opensim.log` and `opensim.err`.

What about if the command-line tool had a flag for whether or not to write the log files at all (what should the default be)?
