### ISSUE TITLE
Edit the constructor to Storage() so that it can read version 2 storage file.

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1983]
STOFileAdapter() prepends `Version=2' in output header info when writing to file. When used by InverseDynamicsTool(), an exception is thrown because (apparently) version (2) files aren't supported. 

 ```
Storage: file=/Users/projects/xxxx/mocap-subject03/data/HS_1.mot (nr=6000 nc=19)
InverseDynamicsTool Failed: Error: File version (2) not supported. Use STOFileAdapter instead.
Java exception occurred:
java.io.IOException: InverseDynamicsTool Failed, please see messages
window for details...
	at
        org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.InverseDynamicsTool_run(Native
        Method)
	at
        org.opensim.modeling.InverseDynamicsTool.run(InverseDynamicsTool.java:117) 
```
If the version row is deleted, the tool runs as expected.

**Comment by chrisdembia** [comment]
I don't see an issue for it, but we've agreed on editing the constructor to `Storage()` so that it can read version 2 storage file.

**Comment by jenhicks** [comment]
@chrisdembia Shall I change the title of this issue to reflect that?

**Comment by chrisdembia** [comment]
Yeah, I think that's a good idea.

**Comment by jimmyDunne** [comment]
@chrisdembia do you know if there is a PR somewhere that deals with this?

**Comment by chrisdembia** [comment]
Not that I know of. I could try working on this.

**Comment by jimmyDunne** [comment]
@aseth1 @aseth1 @jenhicks The beta shouldn't be released until this is fixed.

**Comment by chrisdembia** [comment]
I've started working on this.
