### ISSUE TITLE
Exception messages should not show an absolute path from the developer's machine.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1984]
Right now, OpenSim exception messages show an absolute path name to a source file, and the absolute path might contain something like `/Users/chris/...`. It's not ideal to reveal this path on a user's computer. Simbody exception messages show only the file name, not the full path. We should do the same.

**Comment by tkuchida** [comment]
Sounds good. There are two files named "scale.cpp" (in Applications/Scale and OpenSim/Common), but I don't think there are many cases where the filename alone would be insufficient.
