### ISSUE TITLE
PathPoint's "location" property is redundant with Station's "location" property

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1986]
PathPoint owns a Station as a subcomponent and should use Station's "location" property rather than maintaining its own property of the same name that contains the same data. For example, PathPoint's `setLocation()` method sets its own location as well as the location of the Station that it owns.

**Comment by chrisdembia** [comment]
This would require exposing the Station. The duplication of properties is similar to what we do with member subcomponents in the muscle classes.

**Comment by tkuchida** [comment]
Okay, I will try to come up with a workaround that retains this duplication yet adheres to the design that @aseth1 and I discussed for scaling.
