### ISSUE TITLE
WrapObject derives from ModelComponent but lists Component in its DECLARE_ABSTRACT_OBJECT macro

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1990]
See [WrapObject.h#L46](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Wrap/WrapObject.h#L46):
```cpp
class OSIMSIMULATION_API WrapObject : public ModelComponent {
OpenSim_DECLARE_ABSTRACT_OBJECT(WrapObject, Component);
```
Presumably, `Component` should be `ModelComponent` on the second line. If `Component` is correct, there should be a comment here to explain why WrapObjects are unique.

**Comment by tkuchida** [comment]
@aseth1 I'll change the second line to ModelComponent for now so I can use `Super`. Please let me know if "Component" was necessary for some reason.

**Comment by aseth1** [comment]
@tkuchida thanks for finding. Yes, please go ahead and fix. It definitely was not intentional on my part!
