### ISSUE TITLE
The "standard" model against which ligament scaling is tested contains correct path points but incorrect `resting_length`s

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1993]
I provide a detailed description of the issue below because the resolution involves changing a "standard" test model.

This issue concerns the following files in the [Applications/Scale/test](https://github.com/opensim-org/opensim-core/tree/master/Applications/Scale/test) directory:
- [testScale.cpp](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/testScale.cpp)
- [toyLigamentModel.osim](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/toyLigamentModel.osim) (the original model)
- [std_toyLigamentModelScaled.osim](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/std_toyLigamentModelScaled.osim) (the "standard" model)
- [toyLigamentModel_Setup_Scale.xml](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/toyLigamentModel_Setup_Scale.xml) (the ScaleTool setup file)

In [testScale.cpp, line 244](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/testScale.cpp#L244), the `scaleModelWithLigament()` method uses the ScaleTool (with the toyLigamentModel_Setup_Scale.xml setup file) to scale the "block" and "block1" bodies in toyLigamentModel.osim by `(2, 2, 2)`. The "standard" model (std_toyLigamentModelScaled.osim) contains the correct GeometryPath points, but the `resting_length`s are incorrect. Here are the values of the `resting_length`s in the original and "standard" models:

**Table 1**

| Ligament | `resting_length` in original model | `resting_length` in "standard" model
| --- | --- | ---
| "lateralLigament" | 0.14 | 0.14
| "MedialLigament" | 0.14 | 0.14
| "internalLigament" | 0.04 | 0.06
| "crossLigament" | 0.147 | 0.289196876423888

The Ligament's [postScale() method](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Ligament.cpp#L224) indicates that the `resting_length` should be multiplied by `scaleFactor = {path length after scaling} / {path length before scaling}`, so the table above suggests that "lateralLigament" has not changed length; however, this is not the case.

I opened the original model and "standard" models, and used the following script to read the lengths of the ligaments in the default pose:
```
model = getCurrentModel();
s = model.initSystem();
modeling.Ligament.safeDownCast( model.getForceSet().get(0) ).getLength(s);
```
Here are the lengths:

**Table 2**

| Ligament | Length in original model | Length in "standard" model
| --- | --- | ---
| "lateralLigament" | 0.14 | 0.28
| "MedialLigament" | 0.14 | 0.28
| "internalLigament" | 0.04000000000000002 | 0.08000000000000004
| "crossLigament" | 0.1469693845669907 | 0.2939387691339814

I drew a sketch of the bodies and frames, and confirmed that "lateralLigament" should have doubled in length as a result of scaling the bodies by `(2, 2, 2)`. Ligament's `postScale()` method should have updated the `resting_length`s by computing `scaleFactor = {path length after scaling} / {path length before scaling}`; in the case of "lateralLigament", `scaleFactor = 0.28 / 0.14 = 2` (per Table 2) and `resting_length` should have doubled (not remained the same length, as shown in Table 1).

Not sure why [the ASSERT on line 291](https://github.com/opensim-org/opensim-core/blob/master/Applications/Scale/test/testScale.cpp#L291) doesn't currently throw, but I'm confident that the "standard" model is incorrect.

**Comment by tkuchida** [comment]
Here's a screencap of the ligaments in the original model (blue) and "standard" scaled model (green). None of the ligaments remain the same length.

![ligamenttest](https://user-images.githubusercontent.com/4203505/32212513-54831c0e-bdd4-11e7-8910-acf2695e4425.png)

**Comment by chrisdembia** [comment]
I don't see an issue with updating this standard. Is there anything from the archaeology to suggest otherwise?

**Comment by tkuchida** [comment]
> Is there anything from the archaeology to suggest otherwise?

I found a comment from @aymanhab in #538: "The test case is validated against manual inspection for a simple block with attached ligaments. There's no existing code that would have scaled ligament resting length properly, the scaling of geometryPath for this model is trivial and has been visually verified by @jimmyDunne and myself." I'm investigating on master now…

**Comment by tkuchida** [comment]
On master, the correct scale factors are calculated (and, consequently, testScale fails) if `s = _model->initSystem();` is inserted [in SimbodyEngine.cpp after scaling joints](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp#L853). Without `initSystem()` here (i.e., currently on master), Ligament gets incorrect path lengths in its `postScale()` method. The lengths are correct after `Model::scale()` returns (presumably because of the `s = initSystem();` [on line 1504](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Model.cpp#L1504)), as reported using the 3-line script shown above. I haven't been able to determine exactly what's going on (possibly outdated cache, e.g., in [GeometryPath::computePath()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/GeometryPath.cpp#L836)?), but I think the current "standard" file is incorrect and hypothesize that it was generated using OpenSim rather than analytically.
