### ISSUE TITLE
Constructing properties, connectors, inputs and outputs and their documentation

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#200]
The API for specifying these key attributes is still tricky and not consistently (automatically) documented. Properties with macros do appear in the header and their description is present so that is nice, but even for properties it requires calling specialized `construct...` methods in the components constructor. This requirement leads to general problems of enforcement (not part of an enforceable interface) and lacks a required presence (and documentation) in the header. Inputs and Outputs are particularly useless if no one knows they are there. It should appear automatically in Doxygen and in a prominent way. I think this will be critical for scripting to take-off.

The goal should be to list properties, connectors, inputs and outputs as distinct sections (tables) in the header and have everything else about their construction be handled automatically. 

The question is how to achieve this and at what expense?

Two approaches so far: 1) Statically define the contents of corresponding property, connector, ... tables (as strings, or structs) in the header and have the constructor initialize the corresponding table (instance) members from this template. 2) Apply/develop more macro magic to define each attribute and auto implement private virtual constructProperties, constructConnectors, ... which are invoked by base constructInfrastructure() and apply a discipline to call constructInfrastructure().

@sherm1, @aymanhab, @chrisdembia. @msdemers please add your ideas/concerns. Thanks.

**Comment by jenhicks** [comment]
#85 and #86

**Comment by chrisdembia** [comment]
Related: #574

**Comment by chrisdembia** [comment]
Macro for outputs: #806 
Macro for inputs: #815 

Macros for connectors are more troublesome and run into issues of forward declaration; see this branch for a first attempt: https://github.com/opensim-org/opensim-core/tree/in-class-connectors
