### ISSUE TITLE
MarkersReference: add accessor for the TimeSeriesTableVec3; allow interpolating.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2004]
For the direct collocation code, it would be great if `MarkersReference` allowed accessing the `TimeSeriesTableVec3` within the reference, and if it allowed interpolating the marker positions in time. Alternatively, the reference could support resampling the data at provided times.

**Comment by chrisdembia** [comment]
cc @nickbianco

**Comment by chrisdembia** [comment]
In the dev meeting we decided to bring in @nickbianco's new table accessor method for `MarkersReference`.  We also decided that the class should internally build a spline set and that the splines should be used when ` getValues()` is invoked, rather than getting the nearest row in the table.

@tkuchida can you confirm that these changes would be fine for your project?

@nickbianco said he's willing to make these changes. The accessor for the table is of a higher priority than the splining for the direct collocation project.

Ideally, the splining could be delegated to a shared utility function, as described in #2014 .

**Comment by tkuchida** [comment]
> can you confirm that these changes would be fine for your project?

I actually need to go the other way and have implemented a stratified sampling algorithm to do the downsampling. If it's no longer possible to retrieve data with zero overhead, I will lean toward retrieving it once and caching it in my code. I can profile and report back once I've had time to get back into the code.

**Comment by chrisdembia** [comment]
Okay that's useful to know. What's stratified sampling?

**Comment by tkuchida** [comment]
> What's stratified sampling?

http://lmgtfy.com/?q=what+is+stratified+sampling 😉
If I'm selecting `n` rows from a table of length `N`, `n << N`, it's preferable to randomly select one point from each of `n` mutually exclusive sets ("strata", each of size `N/n`). I'm guaranteed to have a "representative" from each part of the gait cycle. The slightly tricky bit was guaranteeing randomness when `N` isn't divisible by `n`.

**Comment by chrisdembia** [comment]
[Ah thanks](http://lmgtfy.com/?q=gifs+of+people+thanking+the+viewer). @nickbianco perhaps we should chat with @tkuchida before proceeding with using splines within MarkersReference to ensure the class remains useful for everyone.

**Comment by nickbianco** [comment]
Agreed. I'll go ahead and create the PR for the table accessor in the meantime, as we discussed.

**Comment by chrisdembia** [comment]
Cool.
