### ISSUE TITLE
[Doxygen] Unsupported xml/html tag warning

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2005]
"`<results_file_name>`" interpreted as invalid tag in [OutputReporter.h#L52](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/OutputReporter.h#L52).

**Comment by chrisdembia** [comment]
Ah. It would be good to write that as `<results file name>` or `<results file name>` so it doesn't get confused for an XML tag (property) or variable name.
