### ISSUE TITLE
ContactGeometry is visualized even if not associated with any contact force

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2011]
In 3.3, ContactGeometry was only visualized if it was associated with a contact force. Now, all ContactGeometry is shown (in the GUI), regardless of if it is part of any contact force. I'm fine with either scheme, but perhaps this should be documented in the CHANGELOG.

**Comment by aymanhab** [comment]
Expected new behavior, needs to be in changelog. Would be good to change color (if not user provided) to gray to indicate that the ContactGometry is not in effect.

**Comment by aseth1** [comment]
> Would be good to change color (if not user provided) to gray to indicate that the ContactGometry is not in effect.

Any ideas how you would do this? Should the default be gray and only when then ContactGeometry is connected to a Force, its color is update to cyan?

**Comment by aymanhab** [comment]
Is there an aPI that ContactGeometry can utilize to find out if connected to a Force or not? If so then this can be built into the generateDecorations method

**Comment by aseth1** [comment]
No there isn't anything in the API that allows the `ContactGeometry` to know which `Force`(s) if any it used by. The easiest way is to modify the existing `Force::extendAddToSystem` to also update  the appearance of the `ContactGeometry` when the underlying `SimTK::Force is created`.
