### ISSUE TITLE
Ubuntu missing dependency

### ISSUE THREAD

**Issue by extraymond** [opensim-org/opensim-core#2022]
Hi! I've followed the instruction for installing opensim on ubuntu 16.04.
Upon install complete, I tried launching the opensim-cmd but the following error occurred:

```
opensim-cmd: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
```

This can be solved by installing libopenblas-base on ubuntu. It would be nice to mention this in the manual. Thx

**Comment by chrisdembia** [comment]
@extraymond I'm happy that you were able to build and run OpenSim with little hassle. The instructions assume you will use libblas-dev, not libopenblas. Were you installing on a fresh copy of Ubuntu 16.04? Is there a chance that you had previously installed openblas on your machine?

**Comment by extraymond** [comment]
Thx for your quick reply. It seems libopenblas is installed by conda(conda-forge channel to be specific)!

So if I understand this correctly, the build process will try to look for both libblas and libopenblas but not choose one over another right?

**Comment by chrisdembia** [comment]
Yes, you can satisfy Simbody's BLAS requirement with either libblas or libopenblas. Maybe CMake found libopenblas in conda even though it wasn't on your library path.

**Comment by extraymond** [comment]
Thx for the headsup! I've indeed added conda lib to my library path. you can close this since it's not of normal encounter.
