### ISSUE TITLE
c3d reading of moments is incorrect. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2025]
C3DFileAdapter() uses btk to read a c3d file and produce an OpenSim table with (apparently) forces, COP and moments. Typically, you would want the ground reaction forces, moments, and COP but you (btk) can output the forces, wrenches, and point of wrench application (PWA). If you want to compute the free moment, you would need the forceplate forces, moments, and COP— not the wrenches. 

Unfortunately, we seem to be using the wrenches in our output table. 

``` C++
// Get ground reaction wrenches for the force platform.
        auto ground_reaction_wrench_filter = 
            btk::GroundReactionWrenchFilter::New();
        ground_reaction_wrench_filter->SetInput(*platform);
        auto wrench_collection = ground_reaction_wrench_filter->GetOutput();
        ground_reaction_wrench_filter->Update();
        
        for(auto wrench = wrench_collection->Begin();
            wrench != wrench_collection->End(); 
            ++wrench) {
            // Forces time series.
            fp_force_pts->InsertItem((*wrench)->GetForce());
            // Moment time series.
            fp_moment_pts->InsertItem((*wrench)->GetMoment());
            // Position time series.
            fp_position_pts->InsertItem((*wrench)->GetPosition());
```

I don't think this is the correct thing to do. Users would expect the forceplate moments and COP not the wrenches and PWA. 

I would like to;
i) Change the standard output table to use forceplate COP and forceplate moments
ii) Add check to automatically convert mm and Nmm to m and Nm
iii) Compute forceplate free moment from forceplate data and include in output table
iv) Add a method to output a flattened table (save users on scripting side from flattening)

If possible, I would like someone to double check my interpretation of what we are currently doing in [C3DFileAdapter](https://github.com/opensim-org/opensim-core/blob/307eb6ecf3f91efd73e5b23f28fb1cb74d779e24/OpenSim/Common/C3DFileAdapter.cpp) and offer feedback on my proposed steps to improve this class. Perhaps @aseth1 or @tkuchida if you have time?

**Comment by aseth1** [comment]
@jimmyDunne 
In i) do you mean the force-plate moments that result in the equivalent wrench at the COP, or the moment readings from the force-plate (usually about a corner of the force-plate? I think we should always provide the same effective wrench and make sure that if we provide include the COP that the moments are about that point. 

For ii) I was thinking we should always convert to Nm (internal units) as a rule, based on the units in the file. If no units are provided we interpret the data to be in standard units (m, rad, N, kg, s)

In iii) I'm afraid that having multiple wrenches in the same force file will be confusing and prone to errors. Would it be less confusing if we provided either the wrench at the force-plate origin OR the wrench acting on the COP (which yields the free-moment) but not both (at least not at the same time)?

**Comment by tkuchida** [comment]
> I'm afraid that having multiple wrenches in the same force file will be confusing and prone to errors. Would it be less confusing if we provided either the wrench at the force-plate origin OR the wrench acting on the COP (which yields the free-moment) but not both (at least not at the same time)?

I agree that it would be confusing to mix wrenches. Could we just generate two files by default—one wrt the COP and one wrt the force plate origin (with meaningful suffixes on the filenames)? An optional argument (e.g., enum) could be used to suppress one or the other if, e.g., there's a lot of data and writing an extra file would be burdensome.

**Comment by aseth1** [comment]
@jimmyDunne technically the wrench should be a dynamically equivalent form of the recorded forceplate forces and moments (w.r.t fixed origin) transformed to (non-stationary) PWA (which should be very close if not identical to the COP). Furthermore, the vertical component of the moment @ PWA should be the "free moment". Have you characterized the difference? What led you to suspect the calculation was wrong?

Today in the dev meeting we discussed writing out only the raw forceplate measured forces and moments about the origin of the forceplate (with the origin as part of the table metadata) with no COP. Then we would implement a separate COP + free moment calculator in future release. For now, we would use exiting scripts to do the conversion, which is less than ideal but may be less error prone if we are not getting correct answers from BTK. Do you agree with this?

Looking at the BTK code, there are things that seem dubious, but I am hesitant to say it is wrong without some test cases.

**Comment by jimmyDunne** [comment]
Thanks, Ajay for the great update. I will add some questions to this thread as they come up. First Question:

In Matlab, I am trying to change the ForceLocation once the C3DFileAdapter instance has been created. The setForceLocation() doesn't take integers— I can change the location in a roundabout way but I my guess is that you didn't anticipate someone creating an instance of the C3DFileAdapter and then trying to change the force location. 

I instinctually tried to do something like this;

```
c3d = C3DFileAdapter()
c3d.setForceLocation(2)
data = c3d.read('filepath')
```
Is there a way of making setForceLocation a private method? If users can see it as an option in Matlab, they may try to use it (like I did). I think in the documentation we should encourage everyone to use the adapters as static methods `data = Adapter.read('path2file')` so it would be good if we could hide any and all methods from people like me :)

**Comment by aseth1** [comment]
@jimmyDunne we can have a wrapped variant that uses integers, in the same we extended the constructor. That was definitely an oversight of this use case. Thanks for finding it.
