### ISSUE TITLE
Python interface no longer in sync with code

### ISSUE THREAD

**Issue by atypic** [opensim-org/opensim-core#2026]
Hello,

it seems master and the swig-interface of the code is no longer in sync. For example, Manager no longer has function setFinalTime, but SWIG interface claims it has.

**Comment by chrisdembia** [comment]
Hello @atypic. That sounds unlikely to me because we do not manually specify the functions to wrap, only the header files (in general). Have you tried building everything from scratch?

**Comment by chrisdembia** [comment]
How are you building the SWIG interface, which language are you using (MATLAB, Java, Python), what platform are you on?

**Comment by aymanhab** [comment]
This is likely an issue with build getting out of sync. I'd rebuild completely from scratch or in a new build folder.

**Comment by atypic** [comment]
Mm. Sorry. You guys are right of course. I managed to confuse myself somehow. The only problem I had was that public functions on Manager was removed between Alfa and beta of 4.0.

**Comment by chrisdembia** [comment]
Look at the CHANGELOG.md file for a guide on how to adapt your code to the most recent interface for the Manager.
