### ISSUE TITLE
setMinimumStepSize for MATLAB in OpenSim 4.0

### ISSUE THREAD

**Issue by hkimpara** [opensim-org/opensim-core#2027]
We would like to use setMinimumStepSize function on 4.0 with MATLAB to shorten CPU hours with reasonable accuracy. 
Current SimbodyUtils cannot extract this method on MATLAB because Integrate classes are not accessible from MATLAB.
Could you add setMinimumStepSize and associate methods into MATLAB access?

**Comment by aymanhab** [comment]
Possible solutions are to expose Integrator or have a method on Manager to push accuracy down (rather than step size which should be left alone).

**Comment by tkuchida** [comment]
Which integrator are you using? Note from [the Simbody doxygen for `setMinimumStepSize()`](https://simtk.org/api_docs/simbody/3.5/classSimTK_1_1Integrator.html#a4390d1685ca2bb7ea5b75ed009b4bb94) that "Some integrators may not support this option." You may have better luck relaxing the accuracy as @aymanhab suggested. Alternatively, you could try removing the components of the model that are generating high-frequency dynamics if these details aren't important for answering your research question.

**Comment by hkimpara** [comment]
We use just normal integrator in current.  It's RungeKuttaMersonIntegrator.
