### ISSUE TITLE
Lacking time data on Inverse Kinematics (IK) tool

### ISSUE THREAD

**Issue by hkimpara** [opensim-org/opensim-core#2028]
Inverse Kinematics (IK) tool is sometimes missing to pick up time from marker data.  
One example, IK analysis for data (0.10 to 0.15 [s]) creates IK outputs for 0.10 to 0.14 [s].  The last one was missing.
I assume this may relate with some numerical bugs.

Here is the example model and associated files.
[https://drive.google.com/open?id=1s0JMDU7eabVBnM2LXl6DkI9EnJtepJ_f](url)

Thank you, Hide

**Comment by aseth1** [comment]
@hkimpara thank you fore reporting this issue. We are unable to access your archive on google drive. Please attach the files here.

**Comment by hkimpara** [comment]
[Setup_IK_R_Leg_link_pedal_002.zip](https://github.com/opensim-org/opensim-core/files/1684260/Setup_IK_R_Leg_link_pedal_002.zip)
I tried to make access to the Google drive again.
Could you try to access following link?
[https://drive.google.com/open?id=1s0JMDU7eabVBnM2LXl6DkI9EnJtepJ_f](url)
Or could you use attached zip file?

**Comment by aseth1** [comment]
The attached zipped works.

**Comment by tkuchida** [comment]
Fixed by #2077
