### ISSUE TITLE
Add MATLAB test for TableReporterSpatialVec

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2029]
Both of the reaction outputs from joint are SpatialVec() and reporters for SpatialVecs are not available in Matlab and need to be added. [Relevant Forum post](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=8469&p=0&start=0&view=&sid=a45e1f2241009f5c5160189d4d106852).

**Comment by aymanhab** [comment]
@jimmyDunne will beef up an existing matlab test case
