### ISSUE TITLE
More Integrator options in Python/MATLAB

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#2041]
The biggest feedback from the NIPS challenge was to have more control over the Integrator, and, especially the accuracy or tolerance. Some possible options (could do multiple):
1) Add new methods to `Manager` to add some simple options. For instance, a new `setIntegrator()` method that takes a `string` to specify the type of integrator, and `setAccuracy()` to specify the accuracy of the internal integrator.
2) Wrap the base `Integrator` class.
3) Wrap the individual `Integrator`s.

**Comment by chrisdembia** [comment]
+1

1 is probably the easiest interface for most users but results in code duplication.

**Comment by aseth1** [comment]
Another option is to add an `OpenSim::Integrator` component with sub-classes that wrap the SimTK::Integrators. Then we could support different integrator types with different parameters (properties) without forcing the Manager to contain these properties and/or enumerate Integrator types. This would fit with our move towards composing studies and analyses.

**Comment by chrisdembia** [comment]
Discussion with @aseth1 @carmichaelong @nickbianco:

- Remove the ability to pass an integrator into the Manager.
- Use an enum to specify an integrator type (use strings in Python/Matlab).
- Document that the string version should be used in scripting.
- Add `Manager::setIntegratorAccuracy()`.
- Do not wrap any SimTK classes.

**Comment by chrisdembia** [comment]
I noticed that I get different behavior between the following two pieces of code:

A:
```cpp
        Manager manager(model);
        manager.setIntegratorAccuracy(1e-5);
        manager.initialize(state);
        state = manager.integrate(1.0);
```

B:
```cpp
        Manager manager(model, state);
        manager.setIntegratorAccuracy(1e-5);
        state = manager.integrate(1.0);
```

I think what's happening is that in (B), the integrator accuracy I specify is not being used.

It seems important to document that `initialize()` must be called after setting integrator settings.

**Comment by carmichaelong** [comment]
Hm, I think that this deserves a closer look than just documentation. That behavior does not seem great. Have you tested if B is equivalent to:
```
        Manager manager(model);
        manager.initialize(state);
        manager.setIntegratorAccuracy(1e-5);
        state = manager.integrate(1.0);
```

**Comment by chrisdembia** [comment]
> Have you tested if B is equivalent to:

I just tried this and yes, B is equivalent.

I don't see anything in Simbody's doxygen that says that changes to integrator settings must occur before calling `initialize()`, so perhaps you're right about a closer look.

**Comment by carmichaelong** [comment]
Perhaps the last thing to check would be to see if using an `RungeKuttaMersonIntegrator` and `TimeStepper` yields the same behavior? This could be a quick check to let us know whether or not a deeper dive is warranted.

**Comment by chrisdembia** [comment]
Good idea. I tested the following. D and E are equivalent, while F is different from D/E. So the issue is not with Manager.

D

```cpp
        SimTK::RungeKuttaMersonIntegrator integrator(model.getMultibodySystem());
        SimTK::TimeStepper ts(model.getMultibodySystem(), integrator);
        ts.initialize(state);
        ts.stepTo(1.0);
```

E
```cpp
        SimTK::RungeKuttaMersonIntegrator integrator(model.getMultibodySystem());
        SimTK::TimeStepper ts(model.getMultibodySystem(), integrator);
        ts.initialize(state);
        integrator.setAccuracy(1e-5); 
        ts.stepTo(1.0);
```

F
```cpp
        SimTK::RungeKuttaMersonIntegrator integrator(model.getMultibodySystem());
        SimTK::TimeStepper ts(model.getMultibodySystem(), integrator);
        integrator.setAccuracy(1e-5); 
        ts.initialize(state);
        ts.stepTo(1.0);
```

**Comment by carmichaelong** [comment]
Cool. Seems like this could just take a documentation change in `Manager` and perhaps an issue should be posted in the Simbody repo? A bigger change would be to introduce some `initialized` bool in `Manager` and throw exceptions if settings are changed after initialization, but I don't think that would be necessary?

**Comment by chrisdembia** [comment]
🎆
