### ISSUE TITLE
Add DataTable::getColumn() shorthand

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2043]
To access a column of a data table, we use `getDependentColumn()`. This name is very verbose, and it's difficult to write a call to this function that fits on one line. Could we consider adding shorthand method `getColumn()` that calls `getDependentColumn()`?

**Comment by chrisdembia** [comment]
It would also be nice to have a version of `getIndependentColumn()` that returns a `SimTK::Vector`.

**Comment by tkuchida** [comment]
`getDependentColumn()` is unambiguous whereas `getColumn(0)` could return the independent column or the first dependent column. Perhaps you could use a function alias locally?
