### ISSUE TITLE
Build Install Failure using Xcode IDE 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2048]
Building Install on Mac using the Xcode IDE returns the below error. Any suggestions for troubleshooting?

<img width="1183" alt="screen shot 2018-01-08 at 9 14 36 am" src="https://user-images.githubusercontent.com/5296507/34682694-8951cbae-f454-11e7-8b29-42d5f8bb835d.png">

<img width="344" alt="screen shot 2018-01-08 at 9 14 49 am" src="https://user-images.githubusercontent.com/5296507/34682697-8d2f09bc-f454-11e7-9df5-d80f733e5c25.png">

**Comment by chrisdembia** [comment]
My hunches are that you either need to use a different Simbody commit or that the Simbody and OpenSim build types do not match.

**Comment by jimmyDunne** [comment]
Thanks, will look into it. FYI though, this is using superbuild.

**Comment by chrisdembia** [comment]
@jimmyDunne can I close this?
