### ISSUE TITLE
Where is plugins folder for OpenSim 4.0 beta?

### ISSUE THREAD

**Issue by clnsmith** [opensim-org/opensim-core#2049]
I was able to load a plugin through the GUI Jython console. :+1:

Is there a place like the "plugins" folder in 3.3 that I can put the library so it loads automatically in the beta GUI?

**Comment by aymanhab** [comment]
Thanks for trying this out @clnsmith, that's encouraging that you were able to load the plugin. Nothing has changed regarding plugin loading so if you create a plugins folder under the top level installation directory and place your plugin into it, the process should work exactly as in 3.3. Please let us know if that works so we can address or document. Thanks

**Comment by clnsmith** [comment]
So now I am having trouble loading my plugin into the 4.0 beta gui. It loads fine in C++ code with the OpenSim 4.0 I have built from source (both on a computer using VS 2015 for OpenSim4.0 and the plugin and a computer using VS 2017 for OpenSim and Plugin). 

Using the beta 4.0 gui available here: https://simtk.org/frs/index.php?group_id=91
Beta for OpenSim Workshop Win64
OpenSim-4.0.Beta_032718-win64.exe 

I get the an error "Error trying to load library WISCO_Plugin. Library failed to load". I get a similar error if I try to load it using the ScriptingShellWindow (which I thought I had working in an older version of the Beta, ie comment above, but now I get the same error there too).

If I go into the "C:\OpenSim 4.0 Beta\bin" folder and run the following command:
opensim-cmd -L "C:\Users\csmith\github\wisco_opensim\install\plugin\WISCO_Plugin.dll" run-tool

I get this error:
![image](https://user-images.githubusercontent.com/1234687/39995500-ae94f39c-577c-11e8-9ec1-ac56d776600e.png)

I am thinking this is something to do with the GUI being built with a different version of Visual Studio than I am using to build my plugin. Can you let me know the version you are using for the 4.0 Beta? Or any other thoughts on what is going on?

Thanks,
Colin

**Comment by chrisdembia** [comment]
To build the plugin, are you using the SDK that comes with OpenSim or your own separate build of opensim-core? This looks to me like you're building with a header that declares `toStringForDisplay()` but running with an older DLL (from the GUI?) in which the function is not defined.

You can try using builds of the GUI from AppVeyor; here's the latest: https://ci.appveyor.com/project/opensim-org/opensim-gui/build/1.0.1309/artifacts. These builds use VS 2018.

**Comment by chrisdembia** [comment]
Ah. @aymanhab do plugins search for their dependencies using the Path?

**Comment by aymanhab** [comment]
Since they use system call, they must be using system Path.

**Comment by clnsmith** [comment]
Thanks for the help. 

Building against the opensim-core I built myself using the github repo. I will look into the PATH issues and and will try the AppVeyor GUI in the next couple of days.

**Comment by clnsmith** [comment]
The AppVeyor GUI loaded my plugin correctly (using a Plugin built with VS 2017 against OpenSim 4.0 source from the master branch using VS 2017). On this computer I don't have any OpenSim in the path (new computer), so I think it must have been a conflict with OpenSim 4.0 beta version I was originally using not being built with VS 2017. 

So everything is working now for me, feel free to close this issue (or I can). Thanks again. 

On a side note, I defended and moved to ETH Zurich. So finally getting back to OpenSim development, so you will (fortunately or unfortunately :) ) be seeing more github activity from me again.

**Comment by chrisdembia** [comment]
> So everything is working now for me

Good. It would be good to build your plugin against the API that comes with the GUI. This should also be more convenient for you; you don't have to build opensim-core from source. In your own CMake project, add the OpenSim install directory to the `CMAKE_PREFIX_PATH` CMake variable.

> On a side note, I defended and moved to ETH Zurich. So finally getting back to OpenSim development, so you will (fortunately or unfortunately :) ) be seeing more github activity from me again.

Fantastic! Congratulations :)

**Comment by chrisdembia** [comment]
We should maybe leave this open because I'm still not sure if there's a Plugins folder (especially on Mac).

**Comment by tkuchida** [comment]
> On a side note, I defended and moved to ETH Zurich.

@clnsmith Congratulations!! :fireworks:
