### ISSUE TITLE
Model and kinematics of normal walking from 3.3 visualize with incorrect hip kinematics in 4.0

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2062]
I tried visualizing kinematics of normal walking using Apoorva Rajagopal's model (both originally from 3.3) in 4.0, and I get the following (both in the GUI and with the API in simbody-visualizer):

![pastedgraphic-2](https://user-images.githubusercontent.com/846001/35467090-918996ac-02bf-11e8-8904-e47830e24125.png)
<img width="189" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/846001/35467091-919c17e6-02bf-11e8-85e6-1b96d9136342.png">

In the 3.3 GUI, this motion looks like normal walking. However, in 4.0, the left hip (only the left hip) seems to undergo incorrect hip abduction/rotation. Ajay says "my guess is that there is a bug in the assignment of the coordinate values from the data from file."

**Comment by chrisdembia** [comment]
I'm pretty sure the issue is that the adduction and rotation DOFs for the left leg are treated as having motion type Coupled instead of Rotational, because their custom joint transform axis slope is -1, not 1, and the code below checks for a slope of 1.0 (not -1.0):

https://github.com/opensim-org/opensim-core/blob/cda2c0026ba1d568e6851bf132ddd3ed1fa495c4/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L176-L190

**Comment by chrisdembia** [comment]
Changing `lf->getSlope()` to `std::abs(lf->getSlope())` fixes the bug for me.

@aseth1 I'm happy to write a test case and submit a PR if you have suggestions for a simple test case and can guide me to where it should go.

**Comment by tkuchida** [comment]
Aren't L176–183 merely a convenience? It seems like it should be possible to treat all coordinates as coupled (possibly with all but one contribution being zero), but that L176–183 are intended to catch the degenerate cases. For example, I would expect one of the test cases to ensure that the results are identical when a degenerate CustomJoint is treated as Rotational vs. Coupled.

**Comment by aseth1** [comment]
`Coordinate::MotionType` is only used to convert rotational coordinates to/from degrees.  I am OK with your fix to accept a scaling of -1 to still be considered a pure rotational coordinate (acting opposite to its sense), but IMHO this isn't how a `CustomJoint` should be used. The axis should be defined in the opposite direction, for example, and in this case a simpler joint type could be used.

Feel free to include your fix,  just add the left sided condition to `testMotionTypesForCustomJointCoordinates` to make sure a -1 scaling is not interpreted as `Coupled`.

Modeling the hip in this case does not require a `CustomJoint` and it could easily be specified as a `GimbalJoint`. It would perform a bit better as well.  I think we should also update the model to serve as a better example of how to construct an OpenSim model.

**Comment by tkuchida** [comment]
@aseth1 The check is for `lf->getSlope() == 1.0`. Based on your comment, it sounds like the situation `lf->getSlope() == 0.9999` will (and is intended to) produce a very different result. Is that correct?

**Comment by aseth1** [comment]
Yes. Anything other than a factor than 1 (-1) does not have internal units of radians and should not be converted to degrees IMHO.

**Comment by tkuchida** [comment]
Ok, thanks for clarifying. It seems like we should be checking for `lf->getSlope() == 1.0 || lf->getSlope() == -1.0` in a preprocessor and asking the user whether they want the joint automatically converted to a revolute. I'm also not a fan of branching statements based on checking for equality to a float since roundoff (e.g., during deserialization) would cause the condition to evaluate to false. Another potential issue is that an optimizer could happen to step on 1.0 and lose its footing.

**Comment by chrisdembia** [comment]
Thanks @aseth1. I think @apoorvar got rid of a lot of custom joints in her model. I'm interested in fixing the bug wherein I get different behavior in 3.3 vs 4.0. Apoorva's model is widely disseminated and it would be difficult to propagate a change to the joint definition in the model.

I'll edit the test in testMotionTypesForCustomJointCoordinates.

I don't see how we could easily convert this joint to a revolute joint in an automated way given that it's part of a multi-DOF joint. I think we should simply encourage users to not use CustomJoint (but we still cannot allow regressions like this for those still using CustomJoint).

**Comment by aseth1** [comment]
@chrisdembia I agree.

**Comment by aseth1** [comment]
Added [opensim-models #45](https://github.com/opensim-org/opensim-models/issues/45) to update models.
