### ISSUE TITLE
CustomJoint's behavior is not guaranteed to be preserved through serialization

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2066]
CustomJoint treats a Coordinate differently if its SpatialTransform is a LinearFunction with a slope of 1 (see [`CustomJoint::constructCoordinates()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L176)). For programmatically generated models, the current logic can cause the behavior to change if a model is serialized/deserialized first. Here is an example using a slope of `1.0 + 1e-6`:

```cpp
Model model;
auto body = new OpenSim::Body("body", 1., Vec3(0), Inertia::brick(Vec3(1)));
SpatialTransform xform;
xform[0].setCoordinateNames(OpenSim::Array<std::string>("coord", 1, 1));
xform[0].setFunction(new LinearFunction(1.0 + 1e-6, 0.0));
auto joint = new CustomJoint("joint", model.getGround(), *body, xform);
model.addBody(body);
model.addJoint(joint);
const Coordinate::MotionType type1 = joint->getCoordinate(0).getMotionType();

model.print("testmodel.osim");
Model model2("testmodel.osim");
const CustomJoint& joint2 =
    static_cast<const CustomJoint&>(model2.getJointSet().get("joint"));
const Coordinate::MotionType type2 = joint2.getCoordinate(0).getMotionType();

std::cout << "Motion type is " << type1 << " after generating the model "
          << "programmatically and " << type2 << " after save/load"
          << std::endl;
```

Output:
<pre>
Loaded model model from file testmodel.osim
Motion type is 3 after generating the model programmatically and 1 after save/load
</pre>

This behavior seems to violate an implicit assumption that a model shouldn't be categorically different after save/load—though the situation is unlikely to occur in practice.

**Comment by chrisdembia** [comment]
Ah thanks for creating this example. I did not think this would be the behavior, and I do think it is problematic.

**Comment by aseth1** [comment]
@tkuchida in the serialized model file is the 1e-6 offset missing? That's an issue in our serialization.

While I think this behavior is bad, I think the odds of it being an issue (a desired coupling of 1.000001) is very low.  I am in favor of merging #2065.

**Comment by chrisdembia** [comment]
I ran @tkuchida's code above and here is the XML for the SpatialTransform:

```xml
<SpatialTransform>
	<!--3 Axes for rotations are listed first.-->
	<TransformAxis name="rotation1">
		<!--Names of the coordinates that serve as the independent variables         of the transform function.-->
		<coordinates>coord</coordinates>
		<!--Rotation or translation axis for the transform.-->
		<axis>1 0 0</axis>
		<!--Transform function of the generalized coordinates used to        represent the amount of displacement along a specified axis.-->
		<LinearFunction name="function">
			<coefficients> 1 0</coefficients>
		</LinearFunction>
	</TransformAxis>
</SpatialTransform>
```

I agree with @aseth1 that this is a bug in serialization. This bug prevents people from getting reproducible results.

**Comment by chrisdembia** [comment]
I think we might be able to fix this bug by upgrading `LinearFunction` to the new property system.
