### ISSUE TITLE
Rename "APIExamples" folder in the installation

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2068]
Now that the API is not justC++, I think the `APIExamples` folder in the installation should be renamed to `C++Examples` or something like that.

**Comment by aymanhab** [comment]
Ideally we do that while arranging folders in installation per issue 358 of GUI
https://github.com/opensim-org/opensim-gui/issues/358#issuecomment-361759257
Ideally the examples live in parallel folders or are laid out in a form that makes it easy to compare them.

**Comment by chrisdembia** [comment]
> Ideally the examples live in parallel folders or are laid out in a form that makes it easy to compare them.

@aymanhab can you explain a little more about what you mean?

**Comment by aymanhab** [comment]
As of now we have different examples in different bindings/languages mostly. If instead we have Tug-of-war in C++, Python and Matlab grouped together same folder or subfolders than users can map between the different languages and would be easier for them to translate/map future code or their own.

**Comment by chrisdembia** [comment]
Are you thinking of organizing the examples like this?

- Examples
  - TugOfWar
    - C++
    - Matlab
    - Python
  - DynamicWalking
    - C++

...

?

**Comment by aymanhab** [comment]
That would be great and we can get users to try convert/complete the ones that don't exist (e.g. DynamicWalking in Python). This may also help point out how capable are the interfaces in different languages but could be a fairly substantial undertaking (if we do it via CMake). Thoughts?

**Comment by chrisdembia** [comment]
The README example might be the only one that exists in multiple langauges
