### ISSUE TITLE
Hide ModelComponent::InvalidScaleFactors from SWIG

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2074]
The `ModelComponent::InvalidScaleFactors` member variable may unnecessarily clutter the SWIG interface, and since it seems unlikely that users need to access this member variable directly, we could consider either hiding it from SWIG or making it protected instead of public.

See https://github.com/opensim-org/opensim-gui/pull/503 for the initial discussion.

**Comment by tkuchida** [comment]
The question of whether `InvalidScaleFactors` should be protected was raised in PR #2006. Unfortunately, there are no answers there and I can't remember whether we discussed it.

**Comment by aseth1** [comment]
It seems fine to make it protected or even private since scale factors are returned as const reference. Client side can still test if the factors are NaN.

**Comment by chrisdembia** [comment]
Ah yes we should try to make both `InvalidScaleFactors` and `getScaleFactors()` as "private" as we can. Sorry I missed that question in #2006. 

@tkuchida I can try addressing this issue.

**Comment by tkuchida** [comment]
@chrisdembia Sure, gopher it; I'll review.
