### ISSUE TITLE
Exception thrown when optimal fiber length is zero (in GUI)

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2106]
When you (accidently) set optimal fiber length to zero in the GUI you get an (expected) exception. 

However, when you try to correct the error, you can't. Exceptions keep getting thrown and you can't change to a non-zero value

<img width="1440" alt="screen shot 2018-02-26 at 12 13 05 pm" src="https://user-images.githubusercontent.com/5296507/36693037-cb0022a6-1aee-11e8-9894-040cb5315e04.png">

**Comment by tkuchida** [comment]
@aseth1 The issue might be that `MuscleFixedWidthPennationModel::extendFinalizeFromProperties()` is being called before `Millard2012EquilibriumMuscle::extendFinalizeFromProperties()` has a chance to update the pennation model's properties:

https://github.com/opensim-org/opensim-core/blob/4fdace14ebf7428131eb7f6a2c7bbe0a1c74a4d9/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L150-L158

`MuscleFixedWidthPennationModel::extendFinalizeFromProperties()` throws here:
https://github.com/opensim-org/opensim-core/blob/4fdace14ebf7428131eb7f6a2c7bbe0a1c74a4d9/OpenSim/Actuators/MuscleFixedWidthPennationModel.cpp#L87-L91

**Comment by aseth1** [comment]
@tkuchida I think that is exactly what is happening.  In this case, I think we can put this:
https://github.com/opensim-org/opensim-core/blob/4fdace14ebf7428131eb7f6a2c7bbe0a1c74a4d9/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L175-L177

in a `try-catch` block after L158 and if it throws, then restore the properties (set by the muscle) on `penMdl` and re-throw exception.

**Comment by tkuchida** [comment]
> I think we can put this in a `try-catch` block after L158 and if it throws, then restore the properties (set by the muscle) on `penMdl` and re-throw exception.

:+1: Nice solution.
