### ISSUE TITLE
CMC Results for Strength Of Simulation (leg69) differ from 3.3

### ISSUE THREAD

**Issue by apoorvar** [opensim-org/opensim-core#2108]
Simulating leg69 in swing using CMC per tutorial instructions works smoothly (and quickly) in 3.3, but not in 4.0. In 4.0, CMC runs if we added reserve actuators. However, the simulation was still really slow (about an order of magnitude longer in 4.0 compared to 3.3).

@jryong  tested on Windows and I ran on OSX and we had similar results.

([https://simtk-confluence.stanford.edu/display/OpenSim/__40__Part+I%3A+Leg+Muscle+Force+Estimation+in+Swing])

**Comment by tkuchida** [comment]
Also see #2089. Presumably, the failure was encountered in #2089 because we need to add reserve actuators but this isn't specified in the instructions.

**Comment by apoorvar** [comment]
You're right, adding reserve actuators does allow the simulation to run in 4.0. However, these reserve actuators were not necessary for the simulation to successfully run in 3.3, so there seems to be something else going on too.

We checked that integration tolerances were the same b/w our attempts in 3.3 and 4.0.

**Comment by aseth1** [comment]
@apoorvar I was able to run on Mac without reserves but I had to lock the pelvis translations. I also got the CMC to perform 10x slower than identical run on 3.3 with dramatically different results.

Oddly running the gait2354_simbody example CMC results in CMC being a bit faster in 4.0. So my  guess is that there is something specific to the model. I will investigate.

**Comment by tkuchida** [comment]
Fixed by #2114. Potential performance issue noted for further investigation in #2129.
