### ISSUE TITLE
Add button to clear preferences (reset preferences to default values)

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2111]
Sometimes it's useful to clear preferences or to reset preferences to their default values. Right now, I've been telling users to open a Terminal and type `defaults delete org.opensim.utils`. It would be nice if the Preferences window had a button than runs this command or whatever the equivalent NetBeans/Java command is.

**Comment by aseth1** [comment]
@chrisdembia  should this be filed under the GUI repo as a feature request?

**Comment by chrisdembia** [comment]
Oh oops! Wrong place.

**Comment by chrisdembia** [comment]
Issue moved to [opensim-org/opensim-gui #570](https://github.com/opensim-org/opensim-gui/issues/570) via [**ZenHub**](https://www.zenhub.com/)
