### ISSUE TITLE
Inform user/GUI that a Component has been renamed or properties have changed

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2121]
[GUI #483](https://github.com/opensim-org/opensim-gui/issues/483) notes concern for changes to models upon loading that lead to load failures. Informing the user of changes can help them adapt/fix the model so they can load it OpenSim.

From discussion there:

> In the API we can change warnings to Exceptions, but GUI will have catch and throw up a dialog with the message. If there are many renames (e.g. dozens to hundreds of PathPoints) this could be very agitating. Would need away to "ignore all". 
> 
> Another option, is to add/return a flag that informs us if `finalizeFromProperties` has changed any property values, and in that case the GUI would show a single pop-up with a message to check the messages console for the list of the components that were renamed.

I am leaning towards the second option. @aymanhab @tkuchida @chrisdembia?

**Comment by chrisdembia** [comment]
The second option seems like a bit of a hack to me. `finalizeFromProperties()` might edit properties other than the name and thus the pop-up could be generated for a false flag.

The load failure that currently occurs seems to be the exception that is thrown if a socket cannot find its connectee. Could we add a note in that message saying "this may be because the non-unique component names were changed; see the Messages window"?

**Comment by aseth1** [comment]
@chrisdembia I was thinking the second option would be more general than just names. @tkuchida raised concerns with any values being updated by `finalizeFromProperties()` not just naming. For example, illegal mass properties get massaged by Body and it might be good to alert the user of those changes.

I also like your more direct fix for the unable to connect issue.

**Comment by chrisdembia** [comment]
> @chrisdembia I was thinking the second option would be more general than just names.

Ah okay, if the GUI pop-up is equally general, then that could be nice. Would you be able to use `isObjectUpToDateWithProperties()` to automatically determine with return value, so you do not rely on component developers to manually specify the return value? That is, ideally `extendFinalizeFromProperties()` continues to return `void`.

**Comment by aseth1** [comment]
I don't think that `isObjectUpToDateWithProperties()` can help us here since a user edit prior to `finalizeFromProperties` will still make the object dirty.  One proposal @tkuchida discussed with me at UEFS is to clone the properties in the base method, invoke the derived extend and the check if properties were edited. Perhaps we could even generically present which property was changed and from old to new value.
