### ISSUE TITLE
TimeSeriesTable constructor from filename should be explicit

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2124]
The following constructor should be explicit:

https://github.com/opensim-org/opensim-core/blob/5b758a8bc49df7bf9b7c295706f165c57db17146/OpenSim/Common/TimeSeriesTable.h#L197-L205

**Comment by tkuchida** [comment]
What problem did this issue cause? Is a test case missing as well?

**Comment by chrisdembia** [comment]
It's a convention that constructors like this are `explicit` to avoid implicit conversion from `std::string` to `TimeSeriesTable_`, which could be confusing for users. I don't think a test case is necessary; the fix would prevent a compile-time operation, and I'm not sure how we would easily test that a piece of code doesn't compile.

This is a minor issue.

**Comment by tkuchida** [comment]
Ah, okay thanks. I hadn't thought of trying this:
```cpp
TimeSeriesTable_ myTable = "filename.dat";
```

**Comment by chrisdembia** [comment]
Haha yeah. Another scenario were it could show up is passing a string to a function that takes a `TimeSeriesTable_`.
