### ISSUE TITLE
CMC is slower in 4.0 than 3.3

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2129]
In #2114 we fixed the issue of unnecessarily forcing an assembly of the model when setting the kinematic state of the `CMCActuatorSubsystem` but it exposed a bug in the previous implementation (3.3 and earlier) where kinematic constraints were not being strictly respected.  Although, the corrections are likely small, the fact is that when CMC was estimating muscle controls and integrating muscle dynamics, it was doing so with potential states that did not satisfy the model's kinematic constraints. A problem impossible to notice since the computed controls are then used to integrate the full model dynamics forward, which do satisfy the constraints. 

As #2114 documents well thanks to @tkuchida, the results are close (not identical) but CMC is performing twice as slow.  We should investigate how we can maintain correctness and at least restore performance to the 3.3 run time.

If a model has no kinematic constraints it is unlikely to result in a slowdown (needs to be verified).

**Comment by tkuchida** [comment]
:one: All tests were passing before #2114 was merged yet the example was failing, thus at least one test case is missing.

:two: The CMC tests were faster following merge of #2114 (see table, below), but we should compare current 4.0 master to 3.3 release.

| Test | Pre-2114 | Post-2114 |
| ---- | -------- | --------- |
| testCMCArm26_Millard | 29.98 sec | 25.50 sec |
| testCMCArm26_Thelen | 25.67 sec | 20.90 sec |
| testCMCEMGDrivenArm_Millard | 30.89 sec | 25.66 sec |
| testCMCEMGDrivenArm_Thelen | 27.97 sec | 22.56 sec |
| testCMCGait10dof18musc | 117.95 sec | 102.74 sec |
| testCMCSingleMuscle | 30.20 sec | 28.57 sec |
| testCMCSingleRigidTendonMuscle | 29.58 sec | 26.91 sec |
| testCMCTwoMusclesOnBlock | 43.09 sec | 40.14 sec |
| testCMCWithControlConstraintsGait2354 | 60.92 sec | 52.72 sec |
| testCMCWithControlConstraintsRunningModel | 106.20 sec | 88.68 sec |

Windows 8, Intel Core i7-4930K @ 3.4GHz

**Comment by aseth1** [comment]
Feedback @apoorvar from #2114:

>I was able to successfully run a CMC simulation of one gait cycle of walking using my model and this fix. The results were comparable to 3.3.

>Computation time was really slow, though there's a good chance it's because my VM was running slowly. It took 34 minutes to complete the simulation using this 4.0 build, but also took 20+ minutes using the 3.3 GUI.

These times do seem excessive.
