### ISSUE TITLE
testStorage fails with unhelpful message if "with BTK" box was not checked in CMake

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2130]
If the "with BTK" box is not checked in CMake, testStorage fails via [DataAdapter's `NoRegisteredDataAdapter` exception](https://github.com/opensim-org/opensim-core/blob/30300ef226826f47790db9319129c460944a1798/OpenSim/Common/DataAdapter.h#L52-L63). It would have been helpful if the exception message said something like "Ensure the 'with BTK' box is checked in CMake."

**Comment by tkuchida** [comment]
Supplanted by #2133 :seedling:

**Comment by chrisdembia** [comment]
Oops; I hadn't see this when I created #2133 (I haven't been getting all of GitHub's notification emails). I should have just updated this issue.
