### ISSUE TITLE
testStorage should pass even when WITH_BTK is OFF

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2133]
After #2127 was merged, `testStorage` requires `WITH_BTK` to be `ON` in order to pass. To fix this, we should use the `WITH_BTK` macro within `testStorage` to avoid reading C3D if `WITH_BTK` is `OFF`.

Reported by @tkuchida.

**Comment by tkuchida** [comment]
Fixed by #2177.
