### ISSUE TITLE
Reduce clutter of unusable methods available in Scripting

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2135]
Methods created by the property system macros are mostly not usable from scripting and so should be hidden from users to reduce clutter. This could be done using #ifdef SWIG macro inside or by making these methods Protected or Private where appropriate.

**Comment by chrisdembia** [comment]
We might have to resort to `#ifdef SWIG`, because the macro is not able to restore the visibility from above the macro, which means we should not be changing visibility within the macro.
