### ISSUE TITLE
Joint Reaction Analysis crashes when express_in_frame is different from apply_on_bodies

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2145]
@chrisdembia commented on [Mon Feb 26 2018](https://github.com/opensim-org/opensim-gui/issues/544)

### Steps to reproduce

1. Load model and Analyze setup file from Joint Reaction Analysis example.
2. Edit the JointReaction apply_on_bodies and express_in_frame fields (see example setup file: 
[setup_JointReaction.xml.zip](https://github.com/opensim-org/opensim-gui/files/1759786/setup_JointReaction.xml.zip)) and fix the path for forces_file to use forward slashes.
3. Run the analyze tool.

(It's probably just a generic GUI crashing issue, not specific to the steps below)

### Expected result

GUI runs Analysis with no crash.

### Actual result

GUI crashes. 

[Problem Report for OpenSim -- Crashed Joint Reaction Analysis copy.txt](https://github.com/opensim-org/opensim-gui/files/1759780/Problem.Report.for.OpenSim.--.Crashed.Joint.Reaction.Analysis.copy.txt)

### Environment and GUI version

Mac UEFS OpenSim 2416f17-2018-02-25

Related #462.

---

@chrisdembia commented on [Mon Feb 26 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-368601130)

On my computer, I loaded gait2354 and the analyze setup file and added a JointReactions analysis. Then I just let the GUI sit for a while and it eventually crashed:

[ChrisJointReactions.txt](https://github.com/opensim-org/opensim-gui/files/1759820/ChrisJointReactions.txt)

---

@aymanhab commented on [Mon Feb 26 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-368601969)

Stack trace has jointreaction::record. Very likely not generic.

---

@chrisdembia commented on [Mon Feb 26 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-368603186)

My crash log did not contain `record`; might have just been when the GC ran.

---

@aymanhab commented on [Mon Mar 26 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-376339939)

This looks like an API issue. Message below
Component 'subject01' could not find 'child' of type Frame. Make sure a component exists at this path and that it is of the correct type.
	Thrown at Component.h:739 in getComponent().

I was able to run SO out of the box without a hitch.

---

@aseth1 commented on [Tue Apr 03 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-378418909)

This looks like a legitimate user error if the Model could not find the frame named 'child'. This should not bring down the GUI. The message should be relayed to the user in the GUI. 

On the API side we did make it more flexible to express reactions in any frame, so perhaps where we used to accept *child* or *parent* we now expect a frame name. @carmichaelong can you check if that is the case. A quick fix for backward compatibility would be to get the child or parent of the Joint in the case *child* or *parent* are supplied instead of `Frame` names.

---

@carmichaelong commented on [Tue Apr 03 2018](https://github.com/opensim-org/opensim-gui/issues/544#issuecomment-378420355)

This is correct. The `expressedInFrame` input now takes a `Frame` name rather than just 'child' or 'parent'.

I think the best "quick fix" would be to revert to the previous iteration (i.e., only take 'child' or 'parent'). The trade-off here would be:
- (Bad) Users cannot express in any frame that they specify, which could be some meaningful frame for interpretation.
- (Good) This is a plus over allowing them to fill 'child', 'parent', or any `Frame` name since this would cause some major issues if a `Frame` happened to be named 'child' or 'parent'.
- (Good) Limiting what users can input could lead to fewer errors, especially if one has to look up a path to a `Frame`. A question would be whether or not limiting to 'child' and 'parent' covers most of normal use cases.

**Comment by tkuchida** [comment]
Fixed by #2200.
