### ISSUE TITLE
Resources/CodeExamples/C++ folder named improperly on Windows

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2154]
We now install C++ examples into `Resources/CodeExamples/C++` but the AppVeyor artifact renames the `C++` folder to `C%2B%2B`:

<img width="657" alt="screen shot 2018-04-23 at 6 32 50 pm" src="https://user-images.githubusercontent.com/846001/39161294-dee09c3a-4724-11e8-8f88-feea612a90f2.png">

**Comment by chrisdembia** [comment]
I'm not sure if this issue happens when building locally or is caused by how we package with NuGet. For anyone with local builds on Windows, do you see `C++` or `C%2B%2B`?

**Comment by aymanhab** [comment]
I'd lean to name it Cpp, which communicates the same effect and is less error prone. Not worth the fight with the whole stack of build systems AFAIK.

**Comment by chrisdembia** [comment]
Sounds good; I'd like to rename the folder to `Resources/Code/CPP`. This will require a change [here](https://github.com/opensim-org/opensim-gui/blob/a7059a50aba3d7f31fbcc5654ce60a255dc2808b/Gui/opensim/build.xml#L149) and [here](https://github.com/opensim-org/opensim-gui/blob/a7059a50aba3d7f31fbcc5654ce60a255dc2808b/Gui/opensim/build.xml#L70) in opensim-gui.
