### ISSUE TITLE
CorrectionController() causing FwdTool() to crash

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2164]
Running through the pipeline for both gait2392 and gait2354, the FwdTool sends an exception with the default setup files- there is no error message in the window or log files. When I remove the CorrectionController() from the setup file, it runs. This was done in the GUI, and I wasn't able to test in the Matlab API this evening, but I assume it is the tools issue and not the GUI.

**Comment by jimmyDunne** [comment]
I ran the tool on the command line this morning ` > opensim-cmd run-tool subject01_Setup_forward.xml`

The tool worked and results were printed to file. I tested again in the GUI and again I got an exception saying the tool had failed. 

![fwd_tool_error](https://user-images.githubusercontent.com/5296507/39587065-7d1c090e-4ead-11e8-9563-e8f416a613a0.png)

The error message in the Messages window and the out.log end like this;
![fwd_tool_error_message](https://user-images.githubusercontent.com/5296507/39587158-b25fa18e-4ead-11e8-8e0c-15c473757e7c.png)

When I run it in cmd line;
![fwd_tool_error_cmd](https://user-images.githubusercontent.com/5296507/39587456-6359567e-4eae-11e8-8a17-508c408ba97a.png)

**Comment by aymanhab** [comment]
Just in case it turns out to be useful, here's the stack trace:

java.io.IOException: _orderedSubcomponents specified, but its size does not reflect the the number of immediate subcomponents. Verify that you have included all immediate subcomponents in the ordered list.
	In Object 'correctioncontroller' of type CorrectionController.
	Thrown at Component.cpp:437 in componentsAddToSystem().
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.ForwardTool_run(Native Method)
	at org.opensim.modeling.ForwardTool.run(ForwardTool.java:117)
	at org.opensim.tracking.ForwardToolModel$ForwardToolWorker.construct(ForwardToolModel.java:133)
	at org.opensim.swingui.SwingWorker$2.run(SwingWorker.java:130)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aseth1** [comment]
closed by #2166
