### ISSUE TITLE
Tasks for creating the 4.0 release

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2170]
Here are some tasks for creating the 4.0 release.

opensim-core:

- [x] Update the Simbody commit hash in `dependencies/CMakeLists.txt` to 3.6.1.
- [x] Review/update the README.
- [x] Review/update the CHANGELOG.
- [x] Make 4.0 branch.
- [x] Make 4.0 tag.

opensim-gui:

- [x] Review/update the README.
- [x] Review/update the CHANGELOG.
- [x] Create 4.0 branch.
- [x] Create 4.0 tags for opensim-models, three.js, opensim-visualizer, opensim-gui.
- [x] Sign the mac installer (currently, must be done locally).
 
After the release is created:

- [x] Update the version number in `CMakeLists.txt` to 4.1.
  - [x] opensim-core
  - [x] opensim-gui
- [x] Post a zip of the source code (including BTK, docopt, simbody, etc.).
- [x] Post user doxygen webpage on SimTK.
- [ ] Update conda-forge for python bindings.

For reference, here is the list of tasks used for Simbody's 3.6 release: https://github.com/simbody/simbody/issues/606

**Comment by chrisdembia** [comment]
To discuss: how to handle `opensim-models`, `opensim-visualizer`, and `three.js`?

**Comment by chrisdembia** [comment]
@aymanhab do you have feedback on the list above?

**Comment by aymanhab** [comment]
Did we agree on the tag name?
Will likely use same tag for opensim-core and opensim-gui since they are not related as submodules

**Comment by chrisdembia** [comment]
I have a strong preference for `4.0`. See https://github.com/opensim-org/opensim-core/issues/2267

**Comment by aymanhab** [comment]
I guess that would work  even if the next one is 4.0.1 (alternatively we can use 4.0.0)

**Comment by aymanhab** [comment]
Any reason not to make the 4.0 branch and tag on opensim-core now?

**Comment by chrisdembia** [comment]
We need to merge a PR.

**Comment by aymanhab** [comment]
Also the osx installer should ideally be signed

**Comment by aseth1** [comment]
License (e.g. presented during Mac install) also needs to be updated from 2017 to 2018.

**Comment by chrisdembia** [comment]
We still need to make some of these changes (e.g., #2371).

**Comment by jimmyDunne** [comment]
I added the source zip to the SimTK page.

**Comment by jenhicks** [comment]
@chrisdembia or @tkuchida I tagged @aseth1 in a few questions (from the webinar Q&A). I don't think he had a chance to look at these before he left. Could you take a look and see if you're able to answer? We need to finalize this tomorrow so we can send out to participants. Thanks!

**Comment by jenhicks** [comment]
Here's a link to the google doc:
https://docs.google.com/document/d/12mnIIUsikUTOYgu6Z91TP4wzurSM8BKs5nmbnY76IbQ/edit?ts=5bf17d93#

**Comment by aymanhab** [comment]
Can you create the branches/tags to the models, visualizer repos or check if already done? Thank you @chrisdembia
