### ISSUE TITLE
Method Coordinate::isDependent(const SimTK::State& s) segfault

### ISSUE THREAD

**Issue by PatrickLaurin** [opensim-org/opensim-core#2178]
Hi, I've been using the OpenSim API for a while, but the method **Coordinate::isDependent(const SimTK::State& s)** segfaults because it can't find the definition for the method **get_is_free_to_satisfy_constraints()**. By doing a quick search, **get_is_free_to_satisfy_constraints()** is defined in opensim-gui. Any thoughts?

Thank you,
Patrick Laurin

**Comment by chrisdembia** [comment]
Hey @PatrickLaurin your question is better suited to the [forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). If we determine that there is indeed a bug, we can discuss that on GitHub.
