### ISSUE TITLE
Cannot update coordinates of a custom joint

### ISSUE THREAD

**Issue by DocVi** [opensim-org/opensim-core#2185]
Hi,

I tried to use the CustomJoint class following the examples provided in https://github.com/opensim-org/opensim-core/blob/0f3b6b998fe5eefa869e9730bb52ae771e17ac8b/OpenSim/Simulation/SimbodyEngine/Test/testJoints.cpp

I created a custom joint
Unfortunately i get the following error when updating the coordinates:
"SimTK Exception thrown at array.h:555:
Index out of range in ArrayViewConst_<T>::operator[](): expected 0 <= size_type(i) < 0 but size_type(i)=0."

Do you have any idea why? The same code is working for the other joint types (Ball, Free, Pin)

Thanks

![capture](https://user-images.githubusercontent.com/34538601/39879379-f5643954-547a-11e8-8a14-d2c298edc88f.PNG)

**Comment by chrisdembia** [comment]
Hey @DocVi your question is better suited to the [forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). If we determine that there is indeed a bug, we can discuss that on GitHub.

**Comment by DocVi** [comment]
Ok. Sorry. Will do. Thanks
