### ISSUE TITLE
openSim 4.0 documentation

### ISSUE THREAD

**Issue by idhamari** [opensim-org/opensim-core#2190]
The one available online is for [3.3](https://simtk.org/api_docs/opensim/api_docs). I have built openSim 4.0 successfully in my Ubuntu 16.04 machine but the html folder shows "My Project Documentation" web page.

**Comment by chrisdembia** [comment]
Can you explain what you mean by "the html folder shows "My Project Documentation" web page."?

Can you show a screenshot?

**Comment by idhamari** [comment]
It seems I should build the documentation after building openSim then build the install project.
Here are the steps. 
VS: select doxgen sub project then build project only. After that do the same for INSTALL sub project.
Ubuntu: make doxygen && make install

Documentation works now.
