### ISSUE TITLE
Error while running simple arm whose elbow is actuated by a muscle example using the C++ interface provided in the opensim-core readme

### ISSUE THREAD

**Issue by veerendrav** [opensim-org/opensim-core#2193]
I have built the opensim in ubuntu 16.04 successfully. But while running the example **(simple arm whose elbow is articulated by a muscle)**  using the C++ interface provided in the readme i got the following error.

**spinelab@Hogdkin:**~/osimproj/build$ make
[ 50%] Building CXX object CMakeFiles/elb.dir/elb.cpp.o
In file included from /home/spinelab/opensim_install/include/OpenSim/Common/Property_Deprecated.h:33:0,
                 from /home/spinelab/opensim_install/include/OpenSim/Common/PropertyDblVec.h:32,
                 from /home/spinelab/opensim_install/include/OpenSim/Common/PropertySet.h:37,
                 from /home/spinelab/opensim_install/include/OpenSim/Common/Object.h:39,
                 from /home/spinelab/opensim_install/include/OpenSim/Common/osimCommon.h:26,
                 from /home/spinelab/opensim_install/include/OpenSim/OpenSim.h:26,
                 from /home/spinelab/osimproj/elb.cpp:1:
/home/spinelab/opensim_install/include/OpenSim/Common/AbstractProperty.h:32:38: fatal error: SimTKcommon/internal/Xml.h: No such file or directory
compilation terminated.
CMakeFiles/elb.dir/build.make:62: recipe for target 'CMakeFiles/elb.dir/elb.cpp.o' failed
make[2]: *** [CMakeFiles/elb.dir/elb.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/elb.dir/all' failed
make[1]: *** [CMakeFiles/elb.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

even after including the path to the directory containing Xml.h, it is still showing the same error.
where did i go wrong? can someone help me.

**Comment by chrisdembia** [comment]
Your question is better suited to the [forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). If we determine that there is indeed a bug (or if you want to make a feature request), we can discuss that on GitHub. For now, we can continue discussion on yuor forum post (https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9080&p=24935&start=0&view=&sid=acb761fbeb132df6054e523a346de728).
