### ISSUE TITLE
Python interface: Directly working with state's Y value leads to crash

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2214]
This issue was originally created by @janEbert at https://github.com/simbody/simbody/issues/638. Here is what @janEbert said:

Using an OpenSim environment in Python, the program crashes when attempting to do anything with  `SimTK::State`'s `Y` value except for assigning it.

Setup:
```python
from osim.env import ProstheticsEnv
env = ProstheticsEnv(visualize=False)
env.reset()
```
What works:
```python
state = env.osim_model.get_state()
print(state.getY())

y = env.osim_model.get_state().getY()
```
What does not work:
```python
print(env.osim_model.get_state().getY())
list(env.osim_model.get_state().getY())
```

I am on Windows 10 using the latest version of OSim (with Python 3.6.1) and followed the installation instructions to a T.

**Comment by janEbert** [comment]
> I'm a little confused: did you run the "code that does not work" after having already run "what works"? Can you share the complete code that works and the complete code that does not work?

After executing the "setup code", once you - at any point - execute the "code that does not work", it crashes. Whether I execute the "code that works" before does not make a difference.

I have executed the code on a XUbuntu machine now and at least get an error message:
"Segmentation fault (core dumped)"

Minimal failing example:
```python
from osim.env import ProstheticsEnv
env = ProstheticsEnv(visualize=False)
env.reset()

print('Segfault incoming!')
print(env.osim_model.get_state().getY())
```

**Comment by chrisdembia** [comment]
This might be related to the fact that `env.osim_model.get_state()` returns a copy of the internal state, not a reference to the state: 

https://github.com/stanfordnmbl/osim-rl/blob/2d32e4b91e785499479ac4c7fa0198fae3bb7c3d/osim/env/osim.py#L242-L243

**Comment by janEbert** [comment]
Further investigation reveals:
```python
# setup
y = env.osim_model.get_state().getY()
print(y)
```
... fails. However,
```python
# setup
state = env.osim_model.get_state()
y = state.getY()
print(y)
```
... works fine.

**Comment by chrisdembia** [comment]
Thanks for investigating. This is what I think happens: In the former case, the new `opensim.State` returned by `get_state()` is deleted after the assignment `y = ...` because its reference count is 0. But Python doesn't know that the variable `y` points to memory within that now-deleted `opensim.State`.

The simplest fix is to add a docstring to `osim_model.get_state()` that says you must assign the returned state to a variable before using it.

I don't think there is an easy way to ensure that Python keeps the `opensim.State` around for the lifetime of `y`.

**Comment by aymanhab** [comment]
@chrisdembia we can inform our bindings whether the returned state owns its memory or not. Sounds like a possible wrapping/bindings bug.

**Comment by chrisdembia** [comment]
If we say the returned state does not own its memory, wouldn't that result in a leak?

**Comment by aymanhab** [comment]
@chrisdembia If it actually owns then yes that will leak, if not then it's the correct behavior and we just need to communicate the memory management behavior across the bindings. In general I would not expect a "get" method to return a copy  but that could be just misleading naming convention.

**Comment by chrisdembia** [comment]
That's a good point; @kidzik is it necessary to make a copy?

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
