### ISSUE TITLE
Translate "simple example" in README.md into MATLAB, Python, and Jython

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2216]
via discussion with users at WCB OpenSim booth

**Comment by tkuchida** [comment]
/Bindings/Python/examples/build_simple_arm_model.py isn't so visible. I recommend including the code below the C++ version in README.md.

**Comment by chrisdembia** [comment]
There is a note in the README that says "Let's simulate a simple arm whose elbow is actuated by a muscle, using the C++ interface (You can find a Python version of this example at Bindings/Python/examples/build_simple_arm_model.py):"

I was going to say that I don't really want to make the README too long, but it's already really long, so I suppose adding another example would be fine.

We could also put only the Python version in the README.

**Comment by tkuchida** [comment]
> There is a note in the README that says "Let's simulate a simple arm whose elbow is actuated by a muscle, using the C++ interface (You can find a Python version of this example at Bindings/Python/examples/build_simple_arm_model.py):" I was going to say that I don't really want to make the README too long, but it's already really long, so I suppose adding another example would be fine.

I think it would be good if the MATLAB, Python, and Jython code were right there with the C++ code on the home page. If you're concerned about the README being long/verbose, perhaps something like this:

<details open>
<summary>C++</summary>

```cpp
#include <OpenSim/OpenSim.h>
using namespace SimTK;
using namespace OpenSim;

int main() {
    Model model;
    ...
    return 0;
}
```

</details>
<details>
<summary>MATLAB</summary>
<pre>
% MATLAB code here
</pre>
</details>
<details>
<summary>Python</summary>
<pre>
# Python code here
</pre>
</details>
<details>
<summary>Jython</summary>
<pre>
# Jython code here
</pre>
</details>

**Comment by chrisdembia** [comment]
Awesome! I did not know you could create collapsible sections in Markdown.
