### ISSUE TITLE
Make link to OpenSim 3.3 doxygen easier to find

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2222]
Many users will continue using 3.3 for some time, so the 3.3 doxygen should be easy to find. I looked several places, including https://simtk.org/frs/?group_id=91 (under Previous Releases > OpenSim 3.3 > Documentation Links) and https://simtk-confluence.stanford.edu/display/OpenSim33/Documentation (the "Doxygen" link on the far right links to [the 4.0 doxygen](https://simtk.org/api_docs/opensim/api_docs/)).

I found the link by searching Confluence for "doxygen", going to [the "Guide to Using Doxygen" page](https://simtk-confluence.stanford.edu/display/OpenSim/Guide+to+Using+Doxygen), and hovering over the "Doxygen" link on the first line, which points to [the 3.2 doxygen](https://simtk.org/api_docs/opensim/api_docs32/); the 3.3 doxygen is at `api_docs33`.

**Comment by jenhicks** [comment]
@tkuchida I could add a link on this page:
https://simtk-confluence.stanford.edu:8443/display/OpenSim33/OpenSim+3.x+Documentation+Home
Other ideas?

**Comment by aymanhab** [comment]
@tkuchida If users have 3.3 there's a link from the application menu that takes them there directly if online, wouldn't that be the main pathway?

**Comment by chrisdembia** [comment]
I don't think I've used the in-app menu item to get to Confluence, although it's certainly a good idea.

**Comment by tkuchida** [comment]
@jenhicks The "Doxygen" link on [this page](https://simtk-confluence.stanford.edu:8443/display/OpenSim33/Documentation) should point to the 3.3 doxygen. It might be helpful to include a link on the SimTK project page under Previous Releases > OpenSim 3.3 > Documentation Links.
@aymanhab I don't think the application menu in the GUI would be the desired pathway for API users.

**Comment by jenhicks** [comment]
> @jenhicks The "Doxygen" link on this page should point to the 3.3 doxygen. It might also be helpful to include a link on the SimTK project page under Previous Releases > OpenSim 3.3 > Documentation Links.

Updated

**Comment by tkuchida** [comment]
Thanks, @jenhicks. A Google search for "opensim 3.3 doxygen" points to the 4.0 doxygen. Perhaps Google's spiders haven't found the new 3.3 page yet. If possible, it would be convenient if we could include a link like "Looking for the 3.3 doxygen? Click here!" at the top of the 4.0 doxygen.

**Comment by jenhicks** [comment]
The Google spiders seem to have found the new 3.3 page, so I'm going to close this.
