### ISSUE TITLE
Review and update additional portions of the User's Guide

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2225]
- [x] Review User's Guide and identify additional parts that need updating
- [ ] Outputs and Output Reporter:
  - [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Getting+Started+with+Analyses
  - [x] https://simtk-confluence.stanford.edu/display/OpenSim/Property+Editor+and+Outputs+List
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Welcome+to+OpenSim Update section about compatibility with SIMM
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Installing+OpenSim Add some notes about how to install on Mac
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Running+OpenSim
Add notes about how to run on Mac
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Using+Plugins Explain how to use plugins on Mac
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Menus Add Mac Shortcuts. Could update screengrab of preferences, but not super important on this page. 
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/User+Preferences Update with final list of prefs and defaults. (e.g. default marker size is wrong) ... make sure there is a description for all 
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Windows Topology view image is missing
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Creating+and+Naming+3D+Views
Update this page (remove note and just cut the text about multiple views)
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Navigating+the+Visualizer+Window make blue text black (not sure why it is blue)
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Opening%2C+Closing%2C+and+Saving+Models Add image showing where you can drag and drop
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Navigator+Tree+Nodes Is section on  Selecting Components up-to-date? @aymanhab
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Object-Specific+Commands Are mass center instructions (bottom of page) up to date? @aymanhab
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Marker+Editor Any updates needed here? @aymanhab
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Muscle+Editor Any updates needed here? @aymanhab
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Excitation+Editor Updates for Mac functionality? @aymanhab
- [x] https://simtk-confluence.stanford.edu:8443/display/OpenSim/Probes We may want to point people to outputs where possible.

**Comment by jenhicks** [comment]
@nickbianco @aymanhab I started to look through and note places that need an update. I got as far as the Coordinates View section so far.

**Comment by aymanhab** [comment]
@chrisdembia The plugins page suggests checking msvc version. Tis used to be 2015,2017 an dis now 14.1 (MSC_VER 1910) is this mapping documented somewhere? Thanks

**Comment by aymanhab** [comment]
@jenhicks I updated the plugins page with what we have as of today, the Matlab side was confirmed with Chris. Please let me know if I should mark it done. Thanks

**Comment by jenhicks** [comment]
Looks good ... I checked the box.

**Comment by chrisdembia** [comment]
@aymanhab the Visual Studio IDE version is now decoupled from the VC++ (cl) compiler version. For example, one can now use the the 2015 compiler with the 2017 IDE. So for determining compatibility  of plugins, I think the VC++ version will be more useful.

Wikipedia provides a good mapping: https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

**Comment by aymanhab** [comment]
@jenhicks I updated Opening/Closing/Saving models page, let me know what you think. Thanks

**Comment by jenhicks** [comment]
Looks good ... checked the box.

**Comment by aymanhab** [comment]
@jimmyDunne I updated the preview of experimental data page 
 https://simtk-confluence.stanford.edu:8443/display/OpenSim/Previewing+Motion+Capture+%28Mocap%29+Data
but I'm not sure about the latest in terms of mot file headers/labels? Has anything changed in that regard? Thanks

**Comment by aymanhab** [comment]
Motion capture and selecting nodes have been updated and ready for review

**Comment by aymanhab** [comment]
Object specific commands updated.

**Comment by aymanhab** [comment]
Marker Editor updated.

**Comment by aymanhab** [comment]
Muscle Editor updated.

**Comment by jenhicks** [comment]
Thanks @aymanhab . I checked all boxes you noted except the Previewing Motion Capture page, pending any feedback from @jimmyDunne

**Comment by aymanhab** [comment]
@jimmyDunne please review notes/questions above. Thank you

**Comment by jenhicks** [comment]
I updated the page about Probes

**Comment by aymanhab** [comment]
I updated the page on Property Editor and added Outputs.

**Comment by chrisdembia** [comment]
I looked over the Property Editor page and made a few minor changes. Which pipeline should we move this to?

**Comment by aymanhab** [comment]
I'd say Needs Verification, until @jenhicks gives it the stamp and can be closed.
