### ISSUE TITLE
ForwardTool's "Maximum number of steps" setting should have an effect

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2228]
Currently it appears that the "Maximum number of steps" for integrator settings in the `ForwardTool` has no effect. This could be cause the property is not being set properly or `SimTK::Integrator::setInternalStepLimit` does not do what we expecting.

**Comment by carmichaelong** [comment]
The `ForwardTool` uses the `Manager` to do integration, and for fixed step integrations, the Manager calls `stepTo()` for each fixed step. 

https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Manager/Manager.cpp#L662

`setInternalStepLimit`'s documentation says it controls total number of steps per `stepTo()` call, which may be why the desired/expected effect isn't observed and would be hard to test.
