### ISSUE TITLE
Users should be warned when 4.0 assigns a different MotionType to a Coordinate

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2240]
In 3.3  a `Coordinate`'s `MotionType` was user settable. The potential for labeling things Rotational was always present. When outputting .mot files we convert rotations (angles) into degrees. In the case of the model in https://github.com/opensim-org/opensim-gui/issues/617 that means all non-pelvis coordinates were specified to be `Rotational`. 

In 4.0 we eliminated the potential for `MotionType` inconsistencies by using the `Joint` type to determine the `MotionType`s of its coordinates.  For a `CustomJoint`,  a coordinate is considered `Rotational` (or conversely`Translational`) if and only if it is a pure rotation or translation along one of the corresponding six spatial transform axes, which means the relationship is 1 to 1 (e.g. linear function of slope +/-1). If the transform axis motion is any other function (besides that or Constant) it is interpreted as *Coupled* where  the motion about that axis is coupled to the generalized coordinate and it is not a physical measure of spatial motion (not an angle or displacement in Cartesian axes) of the joint's child frame.

The `SpatialTransform` for the *tib_pat_r* `Joint`  in the leg69 in https://github.com/opensim-org/opensim-gui/issues/617 with a *knee_angle_pat_r* coordinate has the rotation of the patella body as a spline function of *knee_angle_pat_r* and thus *knee_angle_pat_r* is not a `Rotational` coordinate.  Unfortunately, it was specified to be Rotational in 3.3 and in earlier model files. Now we have an inconsistency in the .mot files produced in 3.3 that has the coupled *knee_angle_pat_r* coordinate value converted to degrees in 3.3 but 4.0 does not interpret it as `Rotational` so it isn't converted back to internal units. This leads to the display issues in https://github.com/opensim-org/opensim-gui/issues/617.

**Comment by aseth1** [comment]
@jenhicks asked:
> ... if labeling the MotionType as rotational was incorrect in 3.3, why is that you get the same answers in both 3.3 and 4.0 as long as you run IK and SO in the same software versions? (i.e., what are the specific cases where labeling a couple motion as rotation gives incorrect answers?)

There only cases, that I can think of, were we will get incorrect answers is when we do not correctly remove unit conversions,  because Simbody's coordinates and generalize forces are self-consistent - their product is always work.  In general, we can multiply all coordinate values by any arbitrary factor as long as we remember to undo that factor when applying it to the state.

So the issue is one of interpretation. We choose to label coordinates as translations and rotations so we can interpret generalized forces in N and Nm (which have physical meaning), and convert angles into degrees.  When you interpret a coupled coordinate as a rotation then we are saying the generalized force is in Nm. That doesn't mean much until you try to compare your "torque" to a physical measure, in which case a coupled coordinate isn't in Nm! Furthermore you might divide this "torque" by a muscle's force to evaluate its moment-arm (in m) which would also be wrong.

You may also be interested in the equivalent torque of the coupler constraint, which by definition does no work, thus the work done on *knee_angle_r* and  *knee_angle_pat_r* cancel each other. *knee_angle_r* is a pure rotation and its value is in radians so its generalized force, f_knee, is in Nm. But, the torque applied to the patella is not -f_knee, only its generalized force is.  The joint motion is geared so for a given *knee_angle_pat_r* value the patella only rotates a fraction of that in radians and the physical torque is a scaled version of f_knee.

It definitely is a pain to have inconsistent behavior between 3.3 and 4.0.  But the fact is that we could label *knee_angle_r* as `Translational` in 3.3 and pelvis_tx as `Rotational` so at the very least we are getting rid of the arbitrariness of `MotionType`. I think a warning may go a long way in avoiding downstream confusion/frustration.

**Comment by jenhicks** [comment]
Thanks @aseth1 ... that makes sense. A warning makes sense and we should think about other ways to document and explain (e.g., maybe a simple example)

**Comment by aymanhab** [comment]
I'd also say the warning should include that result files from earlier versions would be problematic to use and may lead to incorrect results.

**Comment by aseth1** [comment]
Need #2264 and https://github.com/opensim-org/opensim-gui/pull/953 to be merged and then verified.

**Comment by clnsmith** [comment]
Hopefully this a good place to put this:

I am building a model in C++ code using the 4.0 source code from github I built yesterday. In the model I add a free joint, prescribed one coordinate and lock the other 5 (it is to test contact detection, so it just drives the tibia cartilage superiorly into the femur cartilage):

FreeJoint* tf_joint = new FreeJoint("tf_joint", *femur, Vec3(0), Vec3(0), *tibia, Vec3(0), Vec3(0));

LinearFunction tf_func = LinearFunction(0.02, 0.0);

tf_joint->upd_coordinates(4).setDefaultIsPrescribed(true);
tf_joint->upd_coordinates(4).setPrescribedFunction(tf_func);

tf_joint->upd_coordinates(0).setDefaultLocked(true);
tf_joint->upd_coordinates(1).setDefaultLocked(true);
tf_joint->upd_coordinates(2).setDefaultLocked(true);
tf_joint->upd_coordinates(3).setDefaultLocked(true);
tf_joint->upd_coordinates(5).setDefaultLocked(true);

model.addJoint(tf_joint);

This throws the following warning when I run the code:

![image](https://user-images.githubusercontent.com/1234687/44394301-2954ae80-a537-11e8-9736-aa1015933657.png)

I don't see a way to set the motion type (which fits the whole idea of motion type in 4.0), but how would I construct a free joint in 4.0 C++ code to not get this warning?

**Comment by aseth1** [comment]
@clnsmith you shouldn't be getting a message if there is no underlying XMLdocument or if it is an up-to-date version (in which case there is no past `MotionType` to compare with). I'll check on this. For now you can totally ignore the warning.

**Comment by clnsmith** [comment]
OK thats what I thought, just wanted to bring it to your attention.

Correct, there is no XML doc, just building a simple model from scratch in C++.

**Comment by aseth1** [comment]
@clnsmith thank you for pointing that out!

**Comment by chrisdembia** [comment]
The issue is that if the file does not contain a `motion_type`, then `_userSpecifiedMotionTypePriorTo40` is set to `Undefined`. We might need to add another enum value, perhaps `Unspecified`.
