### ISSUE TITLE
DataTable_::flatten() takes too long for reasonably-sized data files

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2244]
In #2237 @nickbianco said:

> The only issue I ran into was that for larger files (60+ seconds worth of motion data), the script got hung up [here](https://github.com/opensim-org/opensim-core/blob/81e1c285b5ef82ddecb3b34e22df634f6c9802f8/Bindings/Java/Matlab/Utilities/osimC3D.m#L210) where the TimeSeriesTableVec3 of the forces gets flattened. @jimmyDunne have you tested larger files, and if so, how long do they take to flatten the forces? In the meantime, I'll time the larger file I tried to see how long it actually takes.

> For the file I mentioned, it took ~18.9 minutes to write an MOT file for 60 seconds worth of data.

@aseth1:

> It is appending rows one by one, which resizes (and moves data). I had a fix for data reading that should be the same solution of preallocating the size and just updating the contents. Do you want to take a look @nickbianco?

This is the line @aseth1 is referring to: https://github.com/opensim-org/opensim-core/blob/c461d0290a9413e4552b32dc6a1f55d08fb15980/OpenSim/Common/DataTable.h#L389

**Comment by jenhicks** [comment]
@nickbianco Will file a new issue about scaling all the values of the matrix.

**Comment by nickbianco** [comment]
#2280 created for the DataTable fix.
#2281 created to capture the matrix scaling for unit conversion issue.

**Comment by chrisdembia** [comment]
I checked locally and `c3dExport` worked fine and I was able to preview the resulting GRF MOT file in the GUI. `c3dExport` is still fairly slow (35 seconds for [opensim-core/OpenSim/Tests/shared/walking5.c3d](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tests/shared/walking5.c3d)). Here's some profiling results:

![image.png](https://images.zenhubusercontent.com/549329337c6ccc6277a6ab20/46aa1df7-cb0d-448b-8d79-751718a8a15b)

@nickbianco is right that we should speed up `convertMillimeters2Meters` but it would also be good to speed up `osimTableToStruct`.

**Comment by nickbianco** [comment]
@aseth1 and I had an offline discussion a few weeks ago about improving vector/matrix operations in the Matlab and Python interfaces. We should consider changes to the bindings for a more comprehensive solution to these performance issues over quick individual fixes. Vector/matrix operations seem to be one of the biggest hang-ups users have working with the API in Matlab and Python, so it would be a big benefit there in addition to removing the need for more utility functions like these, which require their own development and up keep.
