### ISSUE TITLE
API Guide: Review and Cleanup

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2255]
https://github.com/opensim-org/opensim-core/blob/master/doc/APIGuide.md

Bring this page up to date and include a table of contents.
We will also need to update the posted doxygen.

**Comment by chrisdembia** [comment]
See https://github.com/opensim-org/opensim-core/pull/2275

**Comment by chrisdembia** [comment]
@aymanhab said we need to document, for XML users, the removal of `location_in_parent` etc for joints.

**Comment by scrum2a** [comment]
@aseth1 can you review https://github.com/opensim-org/opensim-core/pull/2284?
