### ISSUE TITLE
Update documentation regarding saving movies

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2259]
@aymanhab commented on [Tue Aug 14 2018](https://github.com/opensim-org/opensim-gui/issues/957)

https://simtk-confluence.stanford.edu/display/OpenSim/Taking+Snapshots+and+Making+Movies
Refers to camera dolly and AVI format from 3.3

---

@tkuchida commented on [Tue Aug 14 2018](https://github.com/opensim-org/opensim-gui/issues/957#issuecomment-413104702)

Also, images that have been embedded in the text do not appear.

**Comment by jenhicks** [comment]
I will take a look at the updates.

**Comment by jenhicks** [comment]
@aymanhab It looks like you updated the text, but I think it would also be helpful to update the screen grabs here. There are also a bunch of missing images that we either need to add back in or at least delete the broken images. 

I don't think it is necessary to recreate the pop out, but I would take a screengrab of what it looks like to select the cameras (for movies and images). On Mac you can use the Grab utility to time a screen grab at a certain time. Then you could overlay or include below a screengrab where the file utility is shown.

**Comment by jenhicks** [comment]
I would also add an image showing how to change snapshot quality.

**Comment by aymanhab** [comment]
Thanks Jen, I meant to ask you about the images/capture will try the screen grab in Mac. Thanks for the pointer.

**Comment by aymanhab** [comment]
@jenhicks Are the missing icons a generic problem that we can fix somewhere else or we need to update one by one? The 3D view page icons seem intact, do you know why?

**Comment by jenhicks** [comment]
I'm not sure what happened. It may just be a glitch from copying the pages for the new version of the software. There is not a general fix we can make that I know of, unfortunately.

**Comment by aymanhab** [comment]
I made the changes you suggested @jenhicks Please let me know what you think.

**Comment by jenhicks** [comment]
Looks good. Thanks!

**Comment by aymanhab** [comment]
Thanks @chrisdembia
