### ISSUE TITLE
Broken links in README for editing PATH

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2266]
The README currently says

> Note: Please add `<FULL-DIR>\opensim_install\bin` to your PATH variable as per [these instructions](#set-environment-variables).  

However, the `#set-environment-variables` link (and the `#set-environment-variables-2` link) doesn't exist.

**Comment by artin-f** [comment]
The GitHub flavor of Markdown automatically creates anchors for headings.  You can create links using: `[link](#dash-separated-lowercase-heading)`.  See [gist:3071099](https://gist.github.com/asabaylus/3071099) for reference. 

Both links you mentioned are currently functional using this method.  Does this resolve the issue?

**Comment by chrisdembia** [comment]
Hey, @artin-f. Yes that would resolve the issue.

**Comment by chrisdembia** [comment]
Ah they do seem to work...maybe I experienced the issue in Atom.

Thanks @artin-f
