### ISSUE TITLE
StatesTrajectory::createFromStatesStorage(): assembling a model with user set default coordinate values produces the wrong trajectory

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#2271]
This was observed while trying to visualize results from a direct collocation problem after converting the solution to a StatesTrajectory:

- If constraints were enforced, I could only visualize the correct solution if I commented out the lines that set the default values in my programmatically created model.
- If default coordinate values were set, I could only visualize the correct solution if I set the `enforceConstraints` argument to false. 

The option to assemble a model to enforce constraints was added in #1922.

**Comment by chrisdembia** [comment]
Nice detective work. I don't understand why explicitly setting the default value causes a change in behavior.

**Comment by chrisdembia** [comment]
I'm happy to look at this with you today.

**Comment by chrisdembia** [comment]
Thanks @aymanhab for the reminder but @nickbianco is using the simbody visualizer.

**Comment by chrisdembia** [comment]
@nickbianco checked and it's not that calling `setDefaultValue()` causes the issue; it's specifically when the default value is not 0.

**Comment by chrisdembia** [comment]
Perhaps `enforceConstraints` should be `false` by default. This would be consistent with the discussion in https://github.com/opensim-org/opensim-gui/issues/86

We should make this change before releasing 4.0, because it would be backwards-incompatible.

**Comment by nickbianco** [comment]
>@nickbianco checked and it's not that calling setDefaultValue() causes the issue; it's specifically when the default value is not 0.

In addition, the states that get created in the StateTrajectory's are always "locked" to a constant value at every time point. It seems like `assemble` is trying really hard to obey the constraint, to the point where it's not obeying the current state coordinate values.
