### ISSUE TITLE
Remove the model name from absolute component paths.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2276]
In discussion with @aymanhab and @carmichaelong 

- [x] Matlab HopperDevice (fix submitted)
- [x] C++ exampleHopperDevice
- [x] Matlab KneeReflex(_answers)
- [x] wiringInputsAndOutputsWithTableReporter
- [x] OpenSimCreateTugOfWarModel (fix submitted)
- [x] prescribeMotionInModel
- [x] setupAndRunAnalyzeBatchExample
- [x] setupAndRunIKBatchExample
- [x] strengthScaler

**Comment by chrisdembia** [comment]
For example: my hard drive is called `Macintosh HD`, but paths are `/Users/chris/...`, not `/Macintosh HD/Users/chris`. The first slash `/` indicates "root" and the hard drive name is not necessary.

**Comment by chrisdembia** [comment]
Try running Matlab examples (Dynamic Walker, Hopper Device).

**Comment by chrisdembia** [comment]
I'm making a PR for a fix for the Matlab HopperDevice example.

**Comment by chrisdembia** [comment]
The OutputReporter accepts a connectee path `/com_position` but the correct path is `/|com_position` (this is the column label from the output file of the OutputReporter).

**Comment by chrisdembia** [comment]
The OutputReporter does not use the proper syntax for input connectee paths. The output should be separated by a vertical line, `|`.

**Comment by jenhicks** [comment]
I can confirm this is the case. I also specified "bodyset/hand_r/position" which resulted in a file with the column labels bodyset/hand_r|position.

Why are we using the vertical lines and slashes? (I'm sure this has been discussed previously, but I don't recall)

**Comment by jenhicks** [comment]
(And it is weird to have a column label that leads with / | )

**Comment by chrisdembia** [comment]
The vertical line allows us to distinguish an output name from component names. We could use a slash but then it's not clear if the element after the last slash is supposed to be a component or an output.

**Comment by chrisdembia** [comment]
Perhaps we can discuss this in tomorrow's stand-up.

**Comment by aymanhab** [comment]
@chrisdembia Should I try to verify this in latest GUI build or are there loose ends in Path specification?

**Comment by chrisdembia** [comment]
There will be updates to OutputReporter but otherwise this is ready to verify.

**Comment by scrum2a** [comment]
James is working on updating Dynamic Walking.

**Comment by scrum2a** [comment]
Test prescribeMotionInModel.

**Comment by scrum2a** [comment]
@chrisdembia will test the remaining Matlab scripts.

**Comment by chrisdembia** [comment]
I tested the remaining Matlab scripts in opensim-core and submitted a small PR to improve support for UNIX.

**Comment by carmichaelong** [comment]
Tested on W10 Pro using OpenSim 4.0-2018-11-06-f8548147. Used bouncing_block model. Opened and saved it in v4, and doing a Find in the model file only found once instance of "toy_with_forces" in the Model tag itself.
