### ISSUE TITLE
IK tracker data not parsing correctly from .sto file when there is only one tracker

### ISSUE THREAD

**Issue by elijahlucey** [opensim-org/opensim-core#2278]
Can be recreated by attempting to run InverseKinematicsTool on a data set that meets the following criteria:

- File format is .sto
- Only one tracker 
- Column names: **time, t0_tx, t0_ty, t0_tz**

I think it's fairly safe to assume my column naming scheme is valid because if I extrapolate it to another tracker (adding `t1` columns), no error is thrown and IK behaves correctly.

Error is thrown at `datatable.h:335`: `Invalid Argument. Cannot guess the suffix from column label at index 0`

Also, not sure whether this case was meant to work or not, since IK with just one tracker is kind of pointless. I just discovered this when modifying the IK process and testing my own changes and it seemed like a bug to me.

**Comment by chrisdembia** [comment]
I'm not sure what you mean by tracker. Also, we typically use TRC files as input to IK. Can you try using a TRC file instead?

**Comment by elijahlucey** [comment]
Hopefully I can clarify some things. By tracker, I mean 3 columns of data with a common prefix in their respective header names whose data would correspond to the location of one OpenSim::Marker object.

As far as using TRC files instead goes, that's sort of specific to what I was trying to do, which was to allow (optionally) for marker orientation data to be utilized during the IK process. I was able to get this working, but only when the data (now with 6 columns instead of 3) is in STO format. There were some problems with getting it to work with TRC files, which would be useful to discuss when I eventually submit a pull request.

I wouldn't really expect this to be a priority to fix because IK doesn't make much sense to use with only one marker, and as you said, normally TRC files are used. It's not a particularly likely use case, unless you're making changes to the IK process and testing it like me.

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
