### ISSUE TITLE
Calling OpenSim methods in MATLAB loops is slow for reasonably-sized data files

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#2281]
The method `convertMillimeters2Meters()` in the `osimC3D` utility and the `osimTableToStruct` utility rely on calls to individual dependent column elements of the TimeSeriesTable (via `getDependentColumnAtIndex().getElt()`) in a loop within Matlab. This is quite slow: for ~60 seconds worth of data, it takes roughly 5 minutes just for the unit conversion when writing an MOT file with an `osimC3D` object.

An implementation for the unit conversion on the C++ side to avoid repeated calls to the TimeSeriesTable in Matlab would be much faster.

**Comment by nickbianco** [comment]
Depending on the change to the bindings, the utilities `osimTableToStruct` and `osimTableFromStruct` may not be necessary if the user could pass a Matlab array directly whenever a TimeSeriesTable object is needed on the OpenSim side.

**Comment by chrisdembia** [comment]
Related: #2559

**Comment by jenhicks** [comment]
This could be improved with the moco merge, but have to double check/test for Matlab.

**Comment by aymanhab** [comment]
@nickbianco is this still an issue after the moco merge? Is it relevant for TGCS?

**Comment by nickbianco** [comment]
@aymanhab I don't think this is an issue anymore, but we should explicitly test it to make sure.

**Comment by nickbianco** [comment]
@aymanhab actually, I'm confusing this issue with the pack/flatten issue that was fixed with #2280. Improving matrix scaling (which would speed up the unit conversion method on `osimC3D`) is still an open issue.

**Comment by nickbianco** [comment]
These lines, where the conversion utility iterates through all the rows to convert to meters, should be update: https://github.com/opensim-org/opensim-core/blob/fe4a2fe3bada5c49304b1e5ba0c18ad92c7f904f/Bindings/Java/Matlab/Utilities/osimC3D.m#L169.

@aymanhab mentioned that he would look into updating this script to use the newly exposed Vector scaling methods.

**Comment by aymanhab** [comment]
Thanks @nickbianco we should be able to elementwiseMultiply or elementwiseMultiplyInPlace of the Column but I need to set up my Matlab environment to test and update.
