### ISSUE TITLE
TRCFileAdapter does not accept MOtoNMS-generated TRC files, and GUI hangs when loading a MOtoNMS TRC file

### ISSUE THREAD

**Issue by vbotics** [opensim-org/opensim-core#2289]
I have been trying to scale the model using OpenSim4, But it looks like the execution happens in a loop, meaning it doesn't terminate. When I terminate the process in GUI, I get the following exception:

`java.lang.RuntimeException: Error reading MetaData in file '..\..\ExperimentalData\healthy_003Cal02.trc'. Incorrect number of keys. Expected = 8. Received = 7. 
	Thrown at trcfileadapter.cpp:83 in extendRead().
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.OpenSimContext_processModelMarkerPlacer__SWIG_0(Native Method)
	at org.opensim.modeling.OpenSimContext.processModelMarkerPlacer(OpenSimContext.java:305)
	at org.opensim.tracking.ScaleToolModel$ScaleToolWorker.construct(ScaleToolModel.java:349)
	at org.opensim.swingui.SwingWorker$2.run(SwingWorker.java:130)
[catch] at java.lang.Thread.run(Thread.java:748)`

I generated the trc file using MOtoNMS tool, And scaling did work in OpenSim3.3. May I know how to fix it. 

System details: Windows 10, 64bit

**Comment by chrisdembia** [comment]
Thanks @vbotics. Could you submit files that would allow us to reproduce the issue? Your TRC file may be missing information in its header. The 4.0 TRC file reader is more strict about the file format. What does the header of your TRC file look like?

**Comment by vbotics** [comment]
> Thanks @vbotics. Could you submit files that would allow us to reproduce the issue? Your TRC file may be missing information in its header. The 4.0 TRC file reader is more strict about the file format. What does the header of your TRC file look like?

Please find the trc file that was used for calibration attached. I generated it using [https://github.com/RehabEngGroup/MOtoNMS](MOtoNMS)

[healthy_003Cal02.zip](https://github.com/opensim-org/opensim-core/files/2378495/healthy_003Cal02.zip)

**Comment by chrisdembia** [comment]
Your TRC file has the following metadata:

- DataRate
- CameraRate
- NumFrames
- NumMarkers
- Units
- OrigDataRate
- DataStartFrame

[OpenSim requires the following data](https://github.com/opensim-org/opensim-core/blob/a837a156e348c82491e23de6d94f0ab9c8ab0085/OpenSim/Common/TRCFileAdapter.cpp#L21):

- DataRate
- CameraRate
- NumFrames
- NumMarkers
- Units
- OrigDataRate
- OrigDataStartFrame (different name than above)
- OrigNumFrames (missing above)

Can you try altering your metadata to conform to the list above?

**Comment by vbotics** [comment]
@chrisdembia Yes. you are right. I altered the metadata and it works! Thanks :)

**Comment by aymanhab** [comment]
@chrisdembia can we report which key is missing? trc files come from variety of tools and likely many more of them are not producing the "strict" syntax unless it's part of the format specification.

**Comment by chrisdembia** [comment]
> Is my understanding correct?

@vbotics I don't know. But I don't think the value for this metadata matters. I'm pretty sure it's ignored.

@aymanhab Good idea.

**Comment by vbotics** [comment]
@chrisdembia yes you are right it's ignored but I thought it would make some sense since it's already there in the metadata(guessing OrigNumFrames would mean the original number of frames in the file :D ) issue resolved thank you :)

**Comment by chrisdembia** [comment]
I'd like to keep this issue open, because we can improve the error message as @aymanhab suggested.

@vbotics would you be willing to report a bug to the MOtoNMS developers so that they produce a proper TRC file?

**Comment by vbotics** [comment]
@chrisdembia okay I'll keep it open. I have updated the script in MOtoNMS to generate proper TRC file and sent a pull request :)

**Comment by chrisdembia** [comment]
Awesome :)

**Comment by ruddbull** [comment]
Hi Chris,

I have the same issue when trying to use the scaling tool. I tried to rearranged the column but it worsened the situation. Now it only receive 3 keys instead of 8. Can you please take a look?

cheers
[Static_1.zip](https://github.com/opensim-org/opensim-core/files/4823282/Static_1.zip)

**Comment by ruddbull** [comment]
Please disregard previous message .... Problem solved :-)
