### ISSUE TITLE
Rename socket_parent_frame_connectee_name -> socket_parent_frame

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2293]

**Comment by scrum2a** [comment]
@chrisdembia is traveling so might not be able to finish this in the sprint.

**Comment by aymanhab** [comment]
@chrisdembia if not working on it can you point me to the branch if you did any work on this? Thanks

**Comment by chrisdembia** [comment]
https://github.com/opensim-org/opensim-core/tree/remove_connectee_name_from_tag

**Comment by carmichaelong** [comment]
Tested on W10 OpenSim 4.0-2018-09-27-d1326ea7. Chose a (pseudo)random subset of models from the distributed Models folder and saved them with the GUI. Checked by looking at the file output. Subset of results are below:

bouncingblock:
![socket-bouncingblock](https://user-images.githubusercontent.com/7455790/46174939-3adc5500-c25f-11e8-9165-bf5d272b10b7.JPG)

gait2354:
![socket-gait2354](https://user-images.githubusercontent.com/7455790/46174950-3f087280-c25f-11e8-8724-a9d04a835168.JPG)

leg39:
![socket-leg30](https://user-images.githubusercontent.com/7455790/46174967-43349000-c25f-11e8-9b48-ffd965c29ad0.JPG)

wrist:
![socket-wrist](https://user-images.githubusercontent.com/7455790/46174971-46c81700-c25f-11e8-8786-7e3e5b62c5e6.JPG)

**Comment by aymanhab** [comment]
Any reason this hasn't been closed @chrisdembia ?
