### ISSUE TITLE
TorqueActuator interface in python

### ISSUE THREAD

**Issue by ali1129** [opensim-org/opensim-core#2308]
Dear all,
Hi,
I am a beginner user of python and OpenSim APIs.
I want to write a Python program to use this TorqueActuator Class to add the actuator to my model.
I am wondering if you help me by providing some examples and manual to how should I write this program for running it on OpenSim GUI.
Bests,
Ali.

**Comment by chrisdembia** [comment]
This is a question for the forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
