### ISSUE TITLE
Moving BTK to ezc3d

### ISSUE THREAD

**Issue by pariterre** [opensim-org/opensim-core#2309]
Hi there!
Since BTK is kind of deprecated and won't be ported to Windows 10 (Mr. Barré is on other projects right now), I am now developing a new c3d reader/writer for c3d files called ezc3d (see on GitHub). I wanted to know if you would be interested in moving OpenSim c3d reader to ezc3d? If so, I can try to implement it. That is creating all the module that are required in OpenSim. I would PR the modifications on opensim-core afterward.
If you are not interested, I will continue to develop it by myself but not necessary in the directed needed for OpenSim. 
Thanks :)

**Comment by chrisdembia** [comment]
@pariterre our team has discussed this and our first question is whether you would consider continuing development of BTK. 

BTK already has a user base and picking up development of BTK could lend credibility and faster uptake, with a direct pipeline to OpenSim users.

Is there a convincing reason to start a new project?

**Comment by pariterre** [comment]
Hello! Thanks for your answer!

In my (very humble) opinion, BTK suffers from design problems. The structure forces to duplicate informations when reading a file, data is not so easy to parse, and even from Arnaud Barré's point of view this project must be rewrite from scratch. This is why he started a new project, but unfortunately didn't make it open source. Also the binders creates bunch of unnecessary libraries and is kind of hard to navigate, especially in Matlab.

I started this project because we needed a c3d parser at the lab and starting from scratch seemed easier than repairing BTK. Today, the ezc3d project is not fully mature yet, but c3d files from Vicon (and tested once on Qualisys) can be read, modified and wrote to a new file in C++ and Matlab. I'll push the python binding within the next days. 

I agree though the project needs to be more mature (mainly in terms of tested c3d files generated from different softwares), and therefore up to now, lacks in trustability. I'm testing it in different conditions in order to improve it ;)

Since I must prioritize the direction of the development, I thought you may be interested in a more up to date c3d reader/writer but may have specific requirements which could use for this development.

I hope this answer your question :)

**Comment by jimmyDunne** [comment]
I agree that BTK suffers from a lot of issues—It was non-trivial to incorporate it into OpenSim and improving on it in the future will be difficult. The issue for us now is that we invested a lot of time getting it working and we are close to release, so we haven't even thought about swapping it out for something else. 

If you are committed to generating ezc3d then I would be happy to help you test it and give you any feedback. Once ezc3d is in a more mature state, then we could totally look at swapping out BTK for your libraries, but I think that will take awhile. If you are able to make a straightforward API for ezc3d, then that should be relatively straight forward.

I will DM you and we can chat :)

**Comment by marnunez** [comment]
@pariterre I second the motion. I've been long trying to support BTK's successor, OpenMA. It's not closed source though, it's just not actively developed any more. It looked like a really promising project. I can add some BTS c3D files to your tests if you're interested.

**Comment by pariterre** [comment]
That would be awesome! 
I just finish to write tests for a very limited amount of c3d. I think I'll create a repo for the c3d files so it doesn't fill the main repo :)
You could push some test files into it if you want!

EDIT : 
I actually did it already, it is not linked yet to ezc3d, but it will be soon
https://github.com/pyomeca/ezc3d_c3dTestFiles

**Comment by pariterre** [comment]
@jimmyDunne and @chrisdembia 
I've just notice (by chance) that C3D standard has officially evolved towards being able to read larger files with potentially larger number of points and analog data. 

I therefore come back to you since BTK won't follow these modifications of the standard resulting in future c3d files not being properly read. Currently ezc3d is not reading these new features either (they were released today), but I am still actively developing ezc3d and therefore I could orient my development towards some need of OpenSim, if you guys are interested in my library.

**Comment by chrisdembia** [comment]
@pariterre would you be willing to help with integrating ezc3d into OpenSim? This could take some effort.

**Comment by pariterre** [comment]
@chrisdembia 

In the short term I have quite a few work to do, so it will be impossible for me to find the time for this. 
However, I would definitely be willing to help implementing during the next months, or even leading the implementation. If so, I think it would probably be a good idea that I join you guys for a short while, so I could focus on the implementation and have the resources nearby. Are you aware of such internship program to OpenSim?

Thanks for your interest :)
