### ISSUE TITLE
Fix to Scaling of mass must be verified in the GUI

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#231]
The fix to issue #223 (PR #230) required recreating a new system after property changes to evaluate the correct total mass. And then again to correctly post-scale actuator paths based on an up-to-date system.
@aymanhab pointed out concerns that the GUI might be negatively affected by these recreations. Thus we opened this issue as a reminder that we need to verify with a working GUI.

**Comment by jenhicks** [comment]
@apoorvar Could you also verify this one when testing scaling with the latest gui?

**Comment by jimmyDunne** [comment]
I have verified this. There are some design decisions we may have to make, while also updating the documentation. There are two binary options, preserved mass distribution and a target mass, that lead to four outcomes for mass scaling. 

**If PMD == 1, target mass > 0**
The mass of each body is proportionally scaled by the ratio of the target mass to original mass. The scaled model mass will equal the user defined target mass. 

**if PMD == 1, target mass =< 0** 
None of the body masses change. The scaled model mass will not have changed. 

**if PMD == 0, target mass > 0** 
Each body mass is scaled by the product of its own scale factors, then each body is scaled again by the ratio of the target mass to the sum of the scaled masses. The scaled model mass will equal the user defined target mass. 

**if PMD == 0, target mass =< 0** 
Each body mass is scaled by the product of its own scale factors. The scaled model mass will equal the the sum of all the newly scaled body masses. 

I will add documentation to the wiki to make this explicit to the User, but we should talk about how to make this more explicit in the GUI.

**Comment by tkuchida** [comment]
I don't think the user should be permitted (or expected to know via documentation, labels, etc.) to enter a target mass that is negative or zero. IMHO a better interface would be to have three widgets:
1. Checkbox for "preserve original distribution of body masses"
2. Checkbox for "specify target mass (if unchecked, [describe what will happen])"
3. Textbox that is enabled only if checkbox 2 is checked; must be a number strictly greater than zero

**Comment by jimmyDunne** [comment]
Opened issue on opensim-org/opensim-gui#746
