### ISSUE TITLE
Opensim python - Mac Anaconda Python 3

### ISSUE THREAD

**Issue by gattia** [opensim-org/opensim-core#2313]
Hi, 

Ive been having issues getting the python wrappings for opensim 4.0 working on Mac. Im able to build opensim and it passes all tests on ctest, expect for python tests it gives an error:

`***Exception: Child aborted`

I also was getting an error on the matlab c3d:

`Matlab_testOsimC3D ...............................***Failed`

However, I assume this is unrelated.

When I try to import opensim into python I get an error: 
```
Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6
```
I have had this problem before when cmake built the dylib of a program against the system python instead of the anaconda python. This doesnt seem to be the case here... I dont think. 

I have opensim installed within a virtual environment using Anaconda on Mac OS Sierra. I am using Python 3.5, and have setup the cmake (ccmake) file to build using python 3, and ccmake appropriately detected the location of the python within my virtual environment. When I check the .so files that are built with opensim they seem alright, to me. 

I have checked just the general info with otool -L: 
```
_actuators.so:
	@rpath/_actuators.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimTools.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimExampleComponents.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libpython3.6m.dylib (compatibility version 3.6.0, current version 3.6.0)
	@rpath/libosimAnalyses.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimActuators.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimSimulation.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimCommon.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libosimLepton.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libSimTKsimbody.3.6.dylib (compatibility version 3.6.0, current version 0.0.0)
	@rpath/libSimTKmath.3.6.dylib (compatibility version 3.6.0, current version 0.0.0)
	@rpath/libSimTKcommon.3.6.dylib (compatibility version 3.6.0, current version 0.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

Mostly to look and see where @rpath are actually pointing and to make sure that the appropriate files are where they should be, I also printed out more detailed info about the .so using otool -l:

```
_actuators.so:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    30       2864 0x00118085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 712
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x0000000000250000
  fileoff 0
 filesize 2424832
  maxprot 0x00000007
 initprot 0x00000005
   nsects 8
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000000000049d0
      size 0x00000000001b6926
    offset 18896
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000000001bb2f6
      size 0x000000000000308a
    offset 1815286
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x00000000001be380
      size 0x000000000000089e
    offset 1827712
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x00000000001bec20
      size 0x0000000000021f54
    offset 1829920
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000000001e0b80
      size 0x0000000000000891
    offset 1969024
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000001e1411
      size 0x000000000006b139
    offset 1971217
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000000024c54c
      size 0x0000000000003a5c
    offset 2409804
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x000000000024ffa8
      size 0x0000000000000058
    offset 2424744
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __DATA
   vmaddr 0x0000000000250000
   vmsize 0x0000000000020000
  fileoff 2424832
 filesize 126976
  maxprot 0x00000007
 initprot 0x00000003
   nsects 7
    flags 0x0
Section
  sectname __got
   segname __DATA
      addr 0x0000000000250000
      size 0x00000000000004a0
    offset 2424832
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 2071 (index into indirect symbol table)
 reserved2 0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x00000000002504a0
      size 0x0000000000000010
    offset 2426016
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 2219 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x00000000002504b0
      size 0x00000000000040b8
    offset 2426032
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 2221 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA
      addr 0x0000000000254568
      size 0x0000000000000008
    offset 2442600
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x0000000000254570
      size 0x0000000000000320
    offset 2442608
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000000254890
      size 0x0000000000019f4d
    offset 2443408
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x000000000026e7e0
      size 0x000000000000139c
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x0000000000270000
   vmsize 0x0000000000163000
  fileoff 2551808
 filesize 1453784
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 48
         name @rpath/_actuators.so (offset 24)
   time stamp 1 Wed Dec 31 19:00:01 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 2551808
    rebase_size 3344
       bind_off 2555152
      bind_size 4208
  weak_bind_off 2559360
 weak_bind_size 154424
  lazy_bind_off 2713784
 lazy_bind_size 12320
     export_off 2726104
    export_size 77840
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 2809496
   nsyms 25351
  stroff 3232280
 strsize 773312
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 23086
     iextdefsym 23086
     nextdefsym 1959
      iundefsym 25045
      nundefsym 306
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 3215112
  nindirectsyms 4292
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 0605D87A-0FC5-306B-ADCA-A1035BF5A1AC
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.12
      sdk 10.12
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimTools.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libosimExampleComponents.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libpython3.6m.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 3.6.0
compatibility version 3.6.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimAnalyses.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimActuators.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimSimulation.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimCommon.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libosimLepton.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 0.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libSimTKsimbody.3.6.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 3.6.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libSimTKmath.3.6.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 3.6.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libSimTKcommon.3.6.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 3.6.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 4.0.0
compatibility version 1.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 1238.60.2
compatibility version 1.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 307.5.0
compatibility version 1.0.0
Load command 24
          cmd LC_RPATH
      cmdsize 72
         path /Users/gattia/Programming/opensim_build/opensim_build (offset 12)
Load command 25
          cmd LC_RPATH
      cmdsize 104
         path /Users/gattia/Programming/opensim_build/opensim_dependencies_install/BTK/lib/btk-0.4dev (offset 12)
Load command 26
          cmd LC_RPATH
      cmdsize 56
         path /Users/gattia/anaconda2/envs/opensim/lib (offset 12)
Load command 27
          cmd LC_RPATH
      cmdsize 96
         path /Users/gattia/Programming/opensim_build/opensim_dependencies_install/simbody/lib (offset 12)
Load command 28
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 2803944
 datasize 5544
Load command 29
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 2809488
 datasize 8

```
Those paths all look appropriate to me, and to the right locations for the dylibs that opensim is built against. 

The only other comment or info I have is that at one point I wondered if it was a python 3 thing and I tried just building outside of a venv using the Anaconda 2 python that I've installed on my computer. This initially gave me some other error that I traced back to figure out that it was erroring because somehow it was trying to import something from the Opensim GUI that I have installed in my 
Applications folder. I was able to import opensim and use it by deleting the GUI version, but clearly this is not a long term solution. 

This made me wonder if somehow there was a path issue, but that doesnt seem to be it. My current path is: 

`/Users/gattia/google-cloud-sdk/bin:/Users/gattia/Programming/opensim_build/opensim_install/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin`

I did at one point have in by .bash_profile a DYLD_LIBRARY_PATH addition pointing to the GUI version of opensim, but this has been commented out for all of this current testing. 

If there are any thoughts at all on what the issue could be I would love to hear them, I've been stuck on this for quite some time. 

Thanks,

Anthony.

**Comment by chrisdembia** [comment]
Thanks for trying this out and for the thorough report.

Can you use the python bindings that come with the GUI, with the python2 that comes with Mac (not Anaconda)?

For your build from source, what's the value of the CMake variable `PYTHON_EXECUTABLE` (and of any other PYTHON CMake variable)?

**Comment by gattia** [comment]
Just wanted to provide an update. I have done a new build against python 2, using my Anaconda version of python, and everything seems to be working fine. I have built in the same fashion that I did the Py3 version, minus the python variables that are listed in the previous post, they all now are related to python 2 and point to the python within anaconda2/ and not the anaconda2/envs/opensim. On my previous run, when I had to delete Opensim to get the py2/anaconda build to work I may have had the DYLD_LIBRARY_PATH that pointed to the GUI application of python in my path. I assume that removing this is what fixed things, but I'm definitely not well versed in this area. 

I'm happy to use py2, I have historically done so with other applications. I just figured if I was starting to use a new package in python (opensim) I should migrate to py3, with py2 maintenance soon coming to an end. 

If you think this is a global issue with python 3 and opensim and have any thoughts or suggestions that would like me to try I am happy to proceed and try to get it resolved.

Thanks, 

Anthony.

**Comment by chrisdembia** [comment]
Great. 

I think the python3 bindings are used for the NIPS challenge, so they should work.

Do you think OpenSim 4.0 should ship with python3 or python2 bindings? One reason for using python2 is that macOS comes with python2 but not with python3, so if we use python3, it's not clear whose python we should build against (I suppose Anaconda3).

The ideal scenario would be that we push OpenSim packages to conda-forge and so users do not need to build from source to use python3 with OpenSim, but this would take time.

**Comment by gattia** [comment]
I assume that there is just something really weird going on in my environment that python 3 is not working. If I do sort it out I will report back so that it can hopefully help someone else in the future. In the meantime, I will be using the Anaconda2 version of python with opensim. 

That's a hard question (py2 vs py3), but I think that py3 is probably the right call, if not only because maintenance for py2 is set to stop in the relatively near future. Aside from that, I think that realistically, most people who are using OpenSim with python will want Anaconda because of the sheer number of scientific packages that come with it out of the box. Without numpy, matplotlib, scipy, jupyter, etc. etc. etc. scripting/programming with OpenSim/python would not be of much utility. Whenever I convert a colleague from matlab to python :), or introduce anyone to python, I directly point them directly to Anaconda. 

The biggest barrier from what you are saying is just getting everyone the same python 3 version. I noticed that there are instructions on the OpenSim website for installing Anaconda on Windows and then setting up OpenSim to work with it. I assume something basic like this could be added to help MacOS users who don't have Anaconda to navigate installing it alongside OpenSim - and requiring for Mac/Windows/Linux that Anaconda3 is installed. In the advent that someone already has Anaconda2 installed, a brief explanation of how to setup a virtual environment with Anaconda3 would suffice. If Anaconda3 is added with the Mac build, I would be more than happy to do a pull-request with some basic documentation of these processes.

**Comment by chrisdembia** [comment]
Thanks for the valuable input, @gattia, and for your willingness to contribute. This isn't high on our priority list right now, but after we release 4.0 it will be good to refine the python package.
