### ISSUE TITLE
External Loads applied multiple times - python API

### ISSUE THREAD

**Issue by gattia** [opensim-org/opensim-core#2317]
Hi, 

I apologize in advance as I've been making a few comments as of late. I have resolved this issue on my end, but the behaviour seemed odd to me, so I wanted to report it to make sure it isnt an issue, and at least make documentation for others to see.

I have built a script (python) that progresses through Scaling, IK, ID, and SO. It originally did so referencing the same model all along the way. I had been checking results against the GUI as I finished each step, and everything was fine upto SO. At that point, I was getting a failing of my model (not strong enough). Turned out that my model was applying the external loads twice during SO. 

Every time I re-run ID or SO it adds another copy of the external loads and uses all of the previous versions in the calculation. It seems to me that the culprit is this line of code 
`id_tool.setExternalLoadsFileName(os.path.join(location_motion_data, save_external_loads_name))`
which appears in the ID and SO tools. To me, it seems that this should only affect the tool, but it somehow adds the forces to the model. I did some playing around and each time you run ID or SO it just keeps adds another set of the external loads, and uses all of them in the calculations. 

My solution was pretty simple, I just saved the model to disk before running any of those tools and then re-loaded the model after running the tool. The fix is not a big deal, but I found it to be an unexpected behaviour. 

As a point of reference, I have attached most of the code I used to successfully get to the SO point in this[file](https://github.com/gattia/randome_code/blob/master/opensim_scale_ik_id_so.py). I have included the "fix" in that code.
 

Anthony.

**Comment by chrisdembia** [comment]
Related #2314

**Comment by gattia** [comment]
Thanks Chris. That definitely looks like the same problem. And from my testing appears to be present for both ID and SO.
