### ISSUE TITLE
Add support for Binder, online Jupyter notebooks

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2329]
If we put OpenSim in the Conda package manager, then we can have live webpages where users can edit and run OpenSim code, in either Python or C++.

- https://mybinder.org
- https://github.com/QuantStack/xeus-cling (C++ interpreter)

Here's an example of a C++ interactive notebook for the "symengine" package: https://mybinder.org/v2/gh/symengine/symengine/master?filepath=notebooks%2Fsymengine.ipynb

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/846001/47398287-51ec5680-d6e8-11e8-8e9c-677339269732.png">

**Comment by aymanhab** [comment]
@chrisdembia I received email from a user trying to do this with OpenSim 4.2. This seems like a good direction to go for future demos/teaching etc. Is there a documentation somewhere as to what is currently supported and how to test and/or upgrade with the next version or to test/use dev version. Thank you.

**Comment by chrisdembia** [comment]
Are you thinking for Python or for C++? I think we should first try to support Python. We need to create a Conda packge for OpenSim. Here's the latest on that: https://github.com/conda-forge/staged-recipes/pull/11894

**Comment by aymanhab** [comment]
Totally agree with Python.
