### ISSUE TITLE
TRCFileAdapter() sets overly strict formatting rules.  

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2345]
A user is having an issue with Scaling in 4.0 and it seems the error is occuring when the TRCFileAdapter() is reading data. TRCFileAdapter throws an error when the trc file column X,Y,Z labels aren't sequencel, starting from 1. 

``` java
java.lang.RuntimeException: Error reading column Labels in file '38_12N_01.trc'.
Unexpected column label. Expected = X1. Received = X5.
	Thrown at TRCFileAdapter.cpp:163 in extendRead().
	at org.opensim.modeling.opensimCommonJNI.TRCFileAdapter_read(Native
        Method)
	at org.opensim.modeling.TRCFileAdapter.read(TRCFileAdapter.java:54)
```

[This section](https://github.com/opensim-org/opensim-core/blob/2fc6dc1d23734f3b5f8d58c3b3833871e756c675/OpenSim/Common/TRCFileAdapter.cpp#L146-L165) of the TRCFileAdapter does the check. 

``` cpp
  // Read in the next line of column labels containing (Xdd, Ydd, Zdd)
    // tuples where dd is a 1 or 2 digit subscript. For example --
    // X1, Y1, Z1, X2, Y2, Z2, ... so on.
    // Check and ignore these labels.
    auto xyz_labels_found = nextLine();
    // erase blank labels, e.g. due to Frame# and Time columns
    IO::eraseEmptyElements(xyz_labels_found);

    for(unsigned i = 1; i <= num_markers_expected; ++i) {
        unsigned j = 0;
        for(auto& letter : {_xLabel, _yLabel, _zLabel}) {
            const unsigned ind = ((i - 1) * 3) + j++;
            const std::string expected{letter + std::to_string(i)};
            OPENSIM_THROW_IF(xyz_labels_found.at(ind) != expected,
                             UnexpectedColumnLabel,
                             fileName,
                             expected,
                             xyz_labels_found.at(ind));
        }
    }
```

It doesn't seem necessary to be so strict since the colomns already have a marker name that group them together. 

There are also issues with the MetaData keys causing problems— why do we need to have some of these keys? It is probably because of legacy, but I think that the TRCFileAdapter() should be smart enough to NOT return an exception if the OrigNumFrames key is not given.

**Comment by jimmyDunne** [comment]
@jenhicks @aseth1 @aymanhab Multiple people are now having this issue on the forum, [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9711&p=26621&start=0&view=) and [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9743&p=26821&start=0&view=) and should be addressed in the next update.

**Comment by jimmyDunne** [comment]
As a bandaid, I have posted a Matlab script to the forum post so Users have a way of 'fixing' a trc file. 

[TRCFileFixer.m.zip](https://github.com/opensim-org/opensim-core/files/2600708/TRCFileFixer.m.zip)

**Comment by jimmyDunne** [comment]
Needs discussion. Fix won't be in included for now. It is not clear how to deal with the labels.

**Comment by aymanhab** [comment]
@jimmyDunne should this be moved back to the product backlog then if no plan to fix now? Thanks
