### ISSUE TITLE
Online API documentation is out of date

### ISSUE THREAD

**Issue by idhamari** [opensim-org/opensim-core#2358]
An example, 

      Manager::setIntegrator(SimTK::Integrator)

it is already replaced by: 

      Manager::setIntegratorMethod(IntegratorMethod)

As mentioned [here](https://github.com/opensim-org/opensim-core/blob/master/CHANGELOG.md), but the [API online documentation](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Manager.html#a362530885fbe8c1b7eadef7e1bda9a49) is still using the old one.

A suggestion to solve this and similar problems is to have a tag for a stable version e.g. 4.0.01, 4.0.02, .. etc. The online documentation should represent the stable version. The stable version should be tested and bug-free (well, at least the build against specific OS with specific versions of tools).

**Comment by chrisdembia** [comment]
Thank you @idhamari. We will update the online documentation after the release.

**Comment by chrisdembia** [comment]
Fixed.
