### ISSUE TITLE
ForwardTool::run() caught exception MATLAB

### ISSUE THREAD

**Issue by vbotics** [opensim-org/opensim-core#2372]
I was trying to run the MATLAB scripts using OpenSim4.0. As shown in the [Scripting page](https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+with+Matlab#ScriptingwithMatlab-ExampleScripts)
`TugOfWar_CompleteRunVisualize.m`, When I try to run this script in the examples, I get the following error:
```
ForwardTool::run() caught exception 
SimTK Exception thrown at integrator.cpp:431:
  Integrator initialization failed apparently because:
SimTK Exception thrown at smallmatrixmixed.h:879:
  Error detected by Simbody method lapackInverse(Mat<>): Matrix is singular so can't be inverted (Lapack getrf info=1).
  (Required condition 'info==0' was not met.)
```

Also when I try to visualize the TugOfWar model in GUI, I do not see the anchors as shown below:
![image](https://user-images.githubusercontent.com/10283521/48421776-72df1f00-e75d-11e8-912d-c182aef0e13d.png)

May I know how to fix this please?

**Comment by chrisdembia** [comment]
Thanks for reporting. What platform are you on? Where did you obtain the 4.0 build? Do you know which commit it is?

**Comment by jimmyDunne** [comment]
On Mac, with the latest application release (from dropbox), I am seeing this error. Running the ForwardTool() through Matlab and the GUI gives the same simulation exception result. Matlab also returns messages that the Geometry can't be found (It is found in the GUI)

``` java
>> TugOfWar_CompleteRunVisualize
Loaded model TugOfWar from file tug_of_war_muscles_controller.osim
Couldn't find file 'ground.vtp'.
Couldn't find file 'anchor1.vtp'.
Couldn't find file 'anchor2.vtp'.
Couldn't find file 'block.vtp'.
Couldn't find file 'ground.vtp'.
Couldn't find file 'anchor1.vtp'.
Couldn't find file 'anchor2.vtp'.
Couldn't find file 'block.vtp'.
Running tool tugOfWar.
No external loads will be applied (external loads file not specified).
Couldn't find file 'ground.vtp'.
Couldn't find file 'anchor1.vtp'.
Couldn't find file 'anchor2.vtp'.
Couldn't find file 'block.vtp'.
MODEL: TugOfWar

numStates = 17
numCoordinates = 6
numSpeeds = 6
numActuators = 2
numBodies = 1
numConstraints = 0
numProbes = 0

ANALYSES (total: 0)

BODIES (total: 1)
body[0] = Block. mass: 20
              moments of inertia:  ~[0,0,0]
              products of inertia: ~[0,0,0]

JOINTS (total: 1)
joint[0] = free_Block. parent: ground, child: Block

ACTUATORS (total: 2)
actuator[0] = muscle1
actuator[1] = muscle2

STATES (total: 16)
y[0] = /jointset/free_Block/free_Block_coord_0/value
y[1] = /jointset/free_Block/free_Block_coord_0/speed
y[2] = /jointset/free_Block/free_Block_coord_1/value
y[3] = /jointset/free_Block/free_Block_coord_1/speed
y[4] = /jointset/free_Block/free_Block_coord_2/value
y[5] = /jointset/free_Block/free_Block_coord_2/speed
y[6] = /jointset/free_Block/free_Block_coord_3/value
y[7] = /jointset/free_Block/free_Block_coord_3/speed
y[8] = /jointset/free_Block/free_Block_coord_4/value
y[9] = /jointset/free_Block/free_Block_coord_4/speed
y[10] = /jointset/free_Block/free_Block_coord_5/value
y[11] = /jointset/free_Block/free_Block_coord_5/speed
y[12] = /forceset/muscle1/activation
y[13] = /forceset/muscle1/fiber_length
y[14] = /forceset/muscle2/activation
y[15] = /forceset/muscle2/fiber_length


Integrating from 0 to 3
ForwardTool::run() caught exception 
SimTK Exception thrown at Integrator.cpp:431:
  Integrator initialization failed apparently because:
SimTK Exception thrown at SmallMatrixMixed.h:879:
  Error detected by Simbody method lapackInverse(Mat<>): Matrix is singular so can't be inverted (Lapack getrf info=1).
  (Required condition 'info==0' was not met.)

Printing results of investigation tugOfWar to ./.
```

**Comment by jimmyDunne** [comment]
Seeminly related #1368 and #429

**Comment by aymanhab** [comment]
Other than Murphy's law, any conjecture what may have changed. Could it be
old/stale code? Can we reproduce in local environments?

**Comment by jimmyDunne** [comment]
Looks like the Inertia of the block isn't set when constructing via scripting. When non-zero inertia is set the simulation runs (just without Geometry being displayed)

@vbotics, you should be able to fix by replacing L59-L65 of OpenSimCreateTugOfWarModel.m with the code below and re-running. 
```
% Create a block Body with associate dimensions, mass properties, and DisplayGeometry
block = Body();
block.setName('Block');
block.setMass(20);
block.setMassCenter(zeroVec3);
% Need to set inertia
block.setInertia(Inertia(0.133,0.133,0.133,0,0,0));
% Set the Block Dispaly Geometry 
block.attachGeometry(Mesh('block.vtp'));
```

You could also edit the TugOfWar model directly to give it inertia. 
```xml
<!--The elements of the inertia tensor (Vec6) as [Ixx Iyy Izz Ixy Ixz Iyz] measured about the mass_center and not the body origin.-->
<inertia>0.13300000000000001 0.13300000000000001 0.13300000000000001 0 0 0</inertia>
```

**Comment by chrisdembia** [comment]
I think it's undoubtedly Murphy's law.

We should add this file to testing, here:
https://github.com/opensim-org/opensim-core/blob/5bd0f4324945d1213b669efeeb027f3b2cea4501/Bindings/Java/Matlab/tests/CMakeLists.txt#L83

**Comment by vbotics** [comment]
> Looks like the Inertia of the block isn't set when constructing via scripting. When non-zero inertia is set the simulation runs (just without Geometry being displayed)
> 
> @vbotics, you should be able to fix by replacing L59-L65 of OpenSimCreateTugOfWarModel.m with the code below and re-running.
> 
> ```
> % Need to set inertia
> block.setInertia(Inertia(0.133,0.133,0.133,0,0,0));
> ```

Thanks @jimmyDunne :+1: That worked!

@chrisdembia This was on the beta version, Running on Windows10-64bit. But I think its the same with new release example as well.
