### ISSUE TITLE
SIMBODY_HOME environment variable is ignored

### ISSUE THREAD

**Issue by yurivict** [opensim-org/opensim-core#2378]
```CMakeCache.txt``` has ```SIMBODY_HOME:PATH=/usr/local``` so it got the variable, but it still installs simbody's headers.

Please also print what ```simbody``` is going to be used.

**Comment by chrisdembia** [comment]
Is this for a downstream CMake project?

**Comment by chrisdembia** [comment]
Oh sorry I realize this is for `opensim-core`.

What do you mean "but it still installs simbody's headers"? I think you're looking to set `OPENSIM_COPY_DEPENDENCIES` to `OFF`.

**Comment by yurivict** [comment]
I see. ```OPENSIM_COPY_DEPENDENCIES``` is dubious when external dependencies are used, because why would you copy them if they are pre-installed. Ideally, bundled dependencies should be used internally, through static libs and internally used headers. I suggest you remove ```OPENSIM_COPY_DEPENDENCIES``` because it is confusing and unnecessary.

**Comment by chrisdembia** [comment]
We can consider changing the default value to `OFF`. We use the variable to package a distribution for Windows and Mac.
