### ISSUE TITLE
Do not use Flash on opensim.stanford.edu

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2381]
Flash support is dying down. We should try converting the video on opensim.stanford.edu to another format.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/846001/48638522-bb792100-e985-11e8-91e7-a7664415b48f.png">

**Comment by jenhicks** [comment]
Good point. I have the .swf and .fla files for the image sequence. But I don't have any of the adobe products that you can use to open and export. I tried an online converter (to gif), but it didn't work very well. I'm looking into finding the software we need, or we can reach out to Scott's brother.
