### ISSUE TITLE
Adding cloned component to a new model creates incorrect connectee path after prepend

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#2388]
`Component::prependComponentPathToConnecteePath()` assumes that the absolute path of the provided subcomponent is always valid, which is not the case for components added to a model that we're cloned from a different model.

**Comment by aymanhab** [comment]
@nickbianco you may want to check the build artifact of PR #2504 to see if the issue has been fixed. Thank you.

**Comment by nickbianco** [comment]
This one slipped by me. Confirmed that the fix works for DeGrooteFregly2016Muscle in Moco, where we originally encountered it.
