### ISSUE TITLE
Where is the 3.3 Release?

### ISSUE THREAD

**Issue by kruser** [opensim-org/opensim-core#2393]
Can you advise on how one would build the 3.3 release? I don't see a tag here: https://github.com/opensim-org/opensim-core/releases

**Comment by chrisdembia** [comment]
This repository cannot easily be used to build the OpenSim 3.3 libraries (API). You can obtain such source code on SimTK (
https://simtk.org/frs/download_confirm.php/release/1513?group_id=91). We encourage you to use 4.0, though, if possible.

**Comment by kruser** [comment]
Thanks @chrisdembia
