### ISSUE TITLE
Create conda package for OpenSim

### ISSUE THREAD

**Issue by romainmartinez** [opensim-org/opensim-core#2396]
Hi,

I noticed that you are planning to add OpenSim to conda-forge; this would greatly facilitate the use of OpenSim with Python.

I noticed that your team has already started [a conda recipe](https://github.com/opensim-org/conda-opensim/tree/python35/opensim), unfortunately, it doesn’t support the latest version of python and I had some problems building OpenSim with it.

We need this feature in our lab, so I’m ready to help if you want to. Do you have a new recipe that is in progress or should I start it from scratch?

**Comment by chrisdembia** [comment]
Hey @romainmartinez I emailed you. It would be great to work together on this. 

Please refer to https://github.com/conda-forge/staged-recipes/pull/4693 instead of the repo you mentioned.

**Comment by chrisdembia** [comment]
@romainmartinez it might be easier to chat over the phone about this.

**Comment by aymanhab** [comment]
I'm in the process of creating a conda package for OpenSim.

**Comment by aymanhab** [comment]
Once we decide how to publicize our conda package this can be closed.

**Comment by aymanhab** [comment]
Package has been created, leftover issues are described in #3167
