### ISSUE TITLE
LogManager: Make cerr & cout redirect optional

### ISSUE THREAD

**Issue by helmesjo** [opensim-org/opensim-core#2400]
Currently, the logging utility [automatically redirects all output](https://github.com/opensim-org/opensim-core/blob/70de9e7ae9f93bc7056d75779cd8532ba5cb1eff/OpenSim/Common/LogManager.cpp#L105) from `std::cerr` & `std::out` to the custom buffers, but also to files `err.log` & `out.log` respectively. 
There is no convenient way to disable this. In our case, we do not want the extra log files magically popping up in our current working directory.

Could this be changed from the hard-coded 1 to a preprocessor define?

**Comment by chrisdembia** [comment]
This would be great. As a workaround, I think you can disable this programmatically in C++ via the following:

```cpp
    std::cout.rdbuf(LogManager::cout.rdbuf());
    std::cerr.rdbuf(LogManager::cerr.rdbuf());
```

**Comment by helmesjo** [comment]
Unfortunately the files will be created non the less... We'll probably use a custom patch until this has been fixed.

Thanks anyways!
