### ISSUE TITLE
Cannot create new instances of ForceSet(string, boolean) from Matlab

### ISSUE THREAD

**Issue by besoft** [opensim-org/opensim-core#2401]
In OpenSim 4.0 it is no longer possible to instantiate ForceSet objects from xml files. 

Example:  newForceSet = ForceSet('myForceSetDoc.xml');
Error: No constructor 'org.opensim.modeling.ForceSet' with matching signature found.

I guess, the reason for that behaviour is that Ajay Seth, 4 months ago (August 23, 2018) replaced an explicit implementation of constructors by using inherited constructors, which is a C++ 11 feature, but SWIG tool does not support this feature. As a result, the constructors are no longer available from Matlab.

**Comment by aseth1** [comment]
The `Set` constructors are explicitly exposed by SWIG [here](https://github.com/opensim-org/opensim-core/blob/670e16f6d8cf37df86443a338a7b0d58e3e5974c/Bindings/common.i#L441-L449)
