### ISSUE TITLE
Conan Package

### ISSUE THREAD

**Issue by bmanga** [opensim-org/opensim-core#2407]
I was wondering if there are any plans to support a C++ package manager such as conan or vcpkg.

**Comment by chrisdembia** [comment]
That would be great, but we do not have plans of maintaining conan or vcpkg packages at this time. We would love if a community member would contribute and maintain such a package. Simbody needs to be packaged first.

We started creating a conda package: . We would welcome any help here as well. https://github.com/conda-forge/staged-recipes/pull/4693
