### ISSUE TITLE
Problem with DynamicWalkerModel

### ISSUE THREAD

**Issue by NataCalc** [opensim-org/opensim-core#2416]
Hi,

I am working with examples in OpenSim-core using cmake to generate the project and Xcode to build and compile. The BuildDynamicWalker example results seem not working. I enclosed .osim file and build-xcode folder to check it out. 

Thanks for help.

[DynamicWalkerModel.osim.zip](https://github.com/opensim-org/opensim-core/files/2903637/DynamicWalkerModel.osim.zip)
[build-xcode.zip](https://github.com/opensim-org/opensim-core/files/2903640/build-xcode.zip)

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
