### ISSUE TITLE
add setModelFileName to InverseKinematicsTool

### ISSUE THREAD

**Issue by marnunez** [opensim-org/opensim-core#2417]
I'm using the Python 3 bindings to modify setup XMLs that get afterwards run by the opensim-cmd.exe
However, I find no way to natively modify the `<model_file>` tag from the IK object binding. In the old Python2/OpenSIM 3.3 bindings, I used to use

```python
mf_property = iktool.getPropertyByName('model_file')
opensim.PropertyHelper_setValueString("test.osim", mf_property)
```
I see the PropertyHelper is gone, so is there anything I could use instead? IDTool and AnalyzeTool do have a setModelFileName method

**Comment by aymanhab** [comment]
PropertyHelper is not gone and there were no changes to InverseKinematicsTool in 4.0 stream in this regard, if you're creating your own custom bindings to use python3 I'd investigate that first. If the classes/properties exist in Python2 bindings/distribution they should also be in Python3 but we haven't tested that on our side and that's why we didn't publish (Python3 bindings) Please advise.

**Comment by marnunez** [comment]
Weird. Built it from master branch just yesterday, Python 3.6. Checking it out...

**Comment by marnunez** [comment]
I can only find a reference to PropertyHelper in the [current master Java JNI bindings](https://github.com/opensim-org/opensim-core/search?q=PropertyHelper&unscoped_q=PropertyHelper).

**Comment by aymanhab** [comment]
Thanks @marnunez, I assumed all along that PropertyHelper was in both Java and Python bindings. Apparently that is not the case. Is that intentional @chrisdembia ?

**Comment by tpauli** [comment]
Are there any news on the topic? I am currently running into the very same issue, and had to create a work-around by printing to XML, changing it as XML and print to file again, then reload using the InverseKinemtaicsTool.

**Comment by aymanhab** [comment]
@chrisdembia Two questions. 

1. Is it intentional that PropertyHelper is not available in Python? How are templatized methods/properties handled?
2. We could handle this more surgically, would you prefer that option?

@tpauli I see there's a setModel method on the tool, is there a reason you need to go through the xml file rather than create the model and call setModel on the tool using a script?

**Comment by chrisdembia** [comment]
> 1. Is it intentional that PropertyHelper is not available in Python? How are templatized methods/properties handled?

Not intentional. Templates are handled the same as with Java, I think.

> 2\. We could handle this more surgically, would you prefer that option?

Do we really want to support PropertyHelper in Python? My preference is to add `setModelFileName()`. Some people may want to use the API to simply edit the XML.

**Comment by tpauli** [comment]
@aymanhab It's interesting, I have tried to used that method before posting to this issue, but when trying to run the tool, it was complaining that the model `Unassigned` (as read from the XML) wasn't loaded. But I cannot reproduce this error any longer. The tool runs when called from a script and the model was set using the aforementioned method. However the model file path is still not printed to XML, even after setting it in the tool.

@chrisdembia In this particular case I prefer to add `setModelFileName()` as well, there's no need to use `PropertyHelper`.

In my opinion, `PropertyHelper` should still be supported. Currently I am working on a model that has a joint provided by a plugin, and I can't set this joint's properties by any method other than using PropertyHelper (or editing the XML file directly).

**Comment by aymanhab** [comment]
This came up recently on the forum. Should be easy to include PropertyHelper in Python as we do for Java. Tool's model filename was done as part of refactoring to use new Properties.
@carmichaelong @chrisdembia

**Comment by chrisdembia** [comment]
That sounds like a good idea to me.

**Comment by aymanhab** [comment]
Exposure of model_file property was done as part of the InverseKinematicsTool refactoring, and PropertyHelper was made available in Python already.
