### ISSUE TITLE
set_GeometryPath() is setting incorrect socket_parent_frame properties

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2418]
Bug [seen on the forum](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10117&p=0&start=0&view=&sid=2e38ed32d9c097bc1f6a8e3d6c27e673) and confirmed by me. 

Constructing a PathSpring Geometry Path from a Muscle Geometry Path object using set_GeometryPath() is causing an incorrect socket_parent_frame, which results in an error on loading the model or initSystem()

``` Matlab
% OpenSim: addPathSpring 
import org.opensim.modeling.*

% Get a handle to the current model and create a new copy 
model = 'gait2392_simbody.osim';

% Set geometry path for the path spring to match the gastrocnemius muscle
gastroc = model.getMuscles().get('med_gas_r');    

pathSpring = PathSpring('BiarticularSpringDamper', 0.4, 1000, 0.01);
pathSpring.set_GeometryPath(gastroc.getGeometryPath());

%% Add the spring to the model
model.addForce(pathSpring);

```

The expected `socket_parent_frame` property for the `pathSpring` should be;

``` Matlab
>>> pathSpring.getGeometryPath().getPathPointSet().get(0).getPropertyByName('socket_parent_frame')
/bodyset/femur_r
```

Instead the result is 

``` Matlab
>>> pathSpring.getGeometryPath().getPathPointSet().get(0).getPropertyByName('socket_parent_frame')
/forceset/BiarticularSpringDamper/bodyset/femur_r
```

Then, calling `model.initSystem()` results in the following exception
``` Matlab
Java exception occurred:
java.io.IOException: Failed to connect Socket 'parent_frame' of type PhysicalFrame
(details: Component '3DGaitModel2392' could not find
'/forceset/BiarticularSpringDamper/bodyset/femur_r' of type PhysicalFrame. Make sure a
component exists at this path and that it is of the correct type.
	Thrown at Component.h:764 in getComponent().).
	In Object 'med_gas_r-P1' of type PathPoint.
	Thrown at Component.cpp:312 in finalizeConnections().
	at org.opensim.modeling.opensimSimulationJNI.Model_initSystem(Native Method)
	at org.opensim.modeling.Model.initSystem(Model.java:848)
```

I have tried a few work around but havent solved it— any suggestions?

**Comment by jimmyDunne** [comment]
User posted about this issue on the [forum](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10559&p=29266&start=0&view=). The problem affects a tutorial so should be high priority for the next release.

**Comment by aymanhab** [comment]
Very likely issue is in prependComponentPathToConnecteePath invoked within addForce

**Comment by jimmyDunne** [comment]
@jimmyDunne add to changelog
