### ISSUE TITLE
Static Optimization fails to handle ignore_tendon_compliance flag

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2419]
From BJ Fregly,

Here is the problem we identified with the Rajagopal model when doing static optimization.

It turns out that some muscles in this model have compliant tendons by default. Compliant tendons mess up static optimization results. To make sure that all tendons in the muscle models are rigid, I told students to open the OpenSim model in their selected text editor and make sure that the field <ignore_tendon_compliance> is set to true for all muscles in the model. Setting this field to true will ensure that all muscles use a rigid tendon model.

After making this change, static optimization worked fine with this model.

**Comment by aseth1** [comment]
It is not at all clear from the title and the discussion what the problem is.  We run SO on models with compliant tendons all the time, since SO treats all muscles as rigid, regardless. What was the original failure and what were the inputs?

**Comment by jenhicks** [comment]
Thanks for reviewing this @aseth1 . I agree that this is a potential bug/issue that has not been fully verified. Perhaps static optimization has an issue with models that have a mix of rigid and compliant tendons? @aymanhab let us know if you have more information and files to reproduce the issue. I have put this in the "User requests and bugs" milestone until we get some more info to know whether there is something to fix or not.

**Comment by jenhicks** [comment]
@apoorvar Have you had any issues or heard of any using your model for static optimization?

**Comment by apoorvar** [comment]
I think the last time I used my model for Static Optimization was using OpenSim 3.2 (part of some speed testing for my paper). I didn't have any issues with the model then. Unfortunately, I haven't tested it since 4.0 was released.
