### ISSUE TITLE
DelimFileAdapter multiple definition error

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#2423]
Including `STOFileAdapter.h` in headers of exported Moco classes causes a multiple definition error for DelimFileAdapter:

![delim_file_adapter_error](https://user-images.githubusercontent.com/23224439/54307954-2defbb80-458a-11e9-9c1f-baede3f1609e.PNG)

Including `extern template class OpenSim::DelimFileAdapter<double>` in Moco class headers does not resolve the issue.

**Comment by jenhicks** [comment]
Thanks for filing @nickbianco . What is the priority/severity of this issue for you guys?

**Comment by nickbianco** [comment]
@jenhicks not a huge priority. We're able to use the base `FileAdapter` class as an alternative for now.

**Comment by aymanhab** [comment]
@nickbianco How do we reproduce?

**Comment by nickbianco** [comment]
I'm not sure if this issue only occurs when linking between Moco and OpenSim or if it could be reproduce in OpenSim only. I guess you could try including the `STOFileAdapter` header in a class outside of osimCommon and see if the error comes up.

**Comment by chrisdembia** [comment]
Thanks for creating this issue, @nickbianco . Note that this is a Windows-only issue.

**Comment by jenhicks** [comment]
@nickbianco Is this still an issue?

**Comment by nickbianco** [comment]
I believe so, although I haven't tested recently. Have there been changes in core to address this?

**Comment by chrisdembia** [comment]
This issue occurred before the change to the interface for reading/writing tables. So even if the issue still exists, it might be very unlikely that someone runs into it. Perhaps we can close for now.

**Comment by jenhicks** [comment]
OK ... will close for now. Thanks!
