### ISSUE TITLE
Error during IAA

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2435]
User reported bug [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10219&p=0&start=0&view=&sid=e53d8d4f2297969a1f06d33909213a9c)

If report_constraint_reactions == true, during IAA, then an error is returned;

![image](https://user-images.githubusercontent.com/5296507/56376876-0b7b3e80-61d7-11e9-93e1-2988fafa3400.png)

Testing files are attached. 

[InducedAccelerations.zip](https://github.com/opensim-org/opensim-core/files/3095387/InducedAccelerations.zip)

**Comment by aseth1** [comment]
Fixed by #2489
