### ISSUE TITLE
Search Box isn't showing up on the opensim website

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2440]
https://opensim.stanford.edu/support/index.html

**Comment by jenhicks** [comment]
I updated the code and it seems to be working again. If someone else is able to verify, I will close this issue. @jimmyDunne @aymanhab @carmichaelong .

I tested on Chrome, so would be good to test on a different browser.

**Comment by aymanhab** [comment]
Tested on Firefox and saw the search box as expected.

**Comment by tkuchida** [comment]
✔️ Verified on 🦊 and (shudders) IE.

**Comment by jenhicks** [comment]
Thanks @tkuchida !
