### ISSUE TITLE
Can't save markerset - 4.0 bug? 

### ISSUE THREAD

**Issue by gattia** [opensim-org/opensim-core#2442]
I've come across two bugs that I think I've figured out but are beyond me to fix.

First, saving markersets from a model: 

I had multiple old models (I believe they were all created using an opensim 4.0 beta release). I updated their connections using `updateSocketConnecteesBySearch(model)` to allow use with opensim 4.0. However, whenever I loaded it would never properly save a marketset. I could add markers to it and view them in the GUI, but when saved the markerset.xml file would have no markers inside - just:

```<?xml version="1.0" encoding="UTF-8" ?>
<OpenSimDocument Version="40000">
	<MarkerSet name="markerset">
		<groups />
	</MarkerSet>
</OpenSimDocument>
```

I would even *save as* the opensim model from the GUI to try and get a "new" model that would hopefully work properly, but this didnt work. I tried loading other/updated models from the opensim website and they worked fine for saving markersets. In the end I found that in the .osim xml file under the `<MarkerSet>` section there was no `<objects></objects>` section and adding this solved the problem. i.e. it was like: 
```
<MarkerSet name="markerset">
    <groups />
</MarkerSet>
```
instead of like this: 
```
<MarkerSet name="markerset">
    <objects>	
    </objects>
    <groups />
</MarkerSet>
```

Second, loading markersets: 

On a somewhat related note, I mostly came across this because I couldn't load markersets. Again, I believe these markersets were all created/saved using a beta release of opensim 4.0. What I did to fix these markersets was a changed the xml tag `<socket_parent_frame_connectee_name>` to `<socket_parent_frame>` and changing the reference within this tag from including `../body_name` to `/bodyset/bodyname`

I havent noticed these yet in the changelog or notes about the swap to opensim 4.0. Let me know if any other information will help in fixing these, or at least passing this info and the workarounds on to others.

**Comment by jenhicks** [comment]
Thanks for the detailed reporting @gattia . I think the issue you encountered is related to the fact that we made changes to the API between when you created the markerset in a preliminary OpenSim 4.0 beta and the final release of OpenSim 4.0. If you proceed as you did in updated the xml tags to match the official 4.0 release, that is the best workaround. We were hoping that people wouldn't run into this and are sorry that you did. Hopefully you don't have too many files where this is an issue.

I added a note here in case others encounter similar issues:
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Upgrade+Notes+for+OpenSim+4.0

@aseth1 and @aymanhab Please chime in if I missed anything.

**Comment by gattia** [comment]
@jenhicks Thanks for the update and for adding the notes for others to find. 
I'll close this as there is no ongoing issue, really just a report.
