### ISSUE TITLE
Opensim Load Plugin - Python

### ISSUE THREAD

**Issue by gattia** [opensim-org/opensim-core#2445]
Hi All, 

Im trying to load a Plugin (Synergies by Dr. Steele) into opensim 3.2  (Python, Linux). 

I can't figure out how this is supposed to be loaded. The LoadOpensimLibrary function is not compiled via swig, so I can't execute it from my python script.

Any suggestions at all? 

Thanks, 

Anthony.

**Comment by gattia** [comment]
I think I've "solved" this problem. However, the plugin isn't behaving as expected so Im not sure my solve caused more harm than good. 

The gist is, the pyWrapOpensim.i file (inside OpenSim32-source/OpensIm/Wrapping/Python/swig ), which specifies what classes/functions etc. to wrap in swig did not contain a line to *include* the LoadOpenSimLibrary() function. I added the following line: 

`%include <OpenSim/Common/LoadOpenSimLibrary.h>`

Including that line, and then re-running the build made the `LoadOpenSimLibrary` function available to the python api. I then used it to load a plugin - and there was no/error. I then tried to load some random string and it gave an error. I assume this means it worked :).

**Comment by GeorgiosGiarmatzis** [comment]
Hi Gattia!
I am also trying to load a plugin in python and although I did everything I read, still I get the error that there is no such attribute to the module opensim. I call the function as opensim.LoadOpenSimLibrary().
Do you have any idea what's wrong?
