### ISSUE TITLE
Enable calibrateModelFromOrientations() output model to be written to a file of user's choosing

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2446]
Calibrate models are printed using the input name and an appended string ('calibrated'). It would be great if there was some method to change the output model name to a custom string since a user may need to print multiple calibrated models, from multiple input orientation files, to the current directory.

**Comment by aseth1** [comment]
@aymanhab @jimmyDunne I was thinking that `OpenSenseUtilities::calibrateModelFromOrientations()` should simply return the calibrated model and should not write to file as part of the API. You can the always print the model to any file you like in scripting, etc... I prefer to minimize file reading/writing as part of the OpenSenseUtilities API.

I will maintain the command line behavior to write to `calibrated_<given_model_filenmae>.osim`

**Comment by aymanhab** [comment]
Agreed, this also allows for the GUI, eventually, to create a calibrated model for inspection without polluting the file system. For command line of opensense though, it would be good to allow users to pass in an output file name so the calibration can be done without programming/coding and to reduce the risk of model overwrite. Thoughts?

**Comment by aseth1** [comment]
> For command line of opensense though, it would be good to allow users to pass in an output file name so the calibration can be done without programming/coding and to reduce the risk of model overwrite. Thoughts?

I like that, but another command line argument is going to be excessive. For now, I say we leave it as is and create calibration settings (XML) that would include all the options and allow users to maintain/reuse them.
