### ISSUE TITLE
Profile IMU data readers

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2450]
In the past reading IMU data files was slow because of matrix resizing, not sure where are the bottleneck now if any. May help to parse data into the matrix directly rather than into a local stack allocated variable then copy into matrix. Need to make sure to initialize to NaNs. Arose from PR #2437

**Comment by jenhicks** [comment]
@aymanhab Is this issue still relevant?

**Comment by aymanhab** [comment]
No, can be closed. As much as file reading go this is perfectly fine now
