### ISSUE TITLE
Better handling of command line options in opensense

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2458]
Check for correct number of argument, warn if too few or too many and describe usage.

**Comment by jimmyDunne** [comment]
(Mac) I am getting errors using some of the command line tools with variable options. 

As an example;

```
>> opensense -Calibrate ModelPostFile.osim calibrationOrientations.sto
Segmentation fault: 11
```
The error seems to be coming from [this section](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L128-L142) of code— the argument values seem to be incorrect and when just the model file and orientation files are input, `argc = 4` . Locally I inserted some cout statements ;

``` Cpp
else if ((option == "-Calibrate") || (option == "-C")) {
                    
                    std::string modelCalibrationPoseFile{ argv[i + 1] };
                    std::string calibrationOrientationsFile{ argv[i + 2] };
                    std::string baseImuName{ "" };
                    
                    SimTK::CoordinateAxis imuHeading{ SimTK::ZAxis };
                    
                    cout << argc << endl;
                    cout << argv[0] << endl;
                    cout << argv[i] << endl;
                    cout << argv[i+1] << endl;
                    cout << argv[i+2] << endl;
                    cout << argv[i+3] << endl;
                    cout << argv[i + 4] << endl;
...

```

and got the following outputs (I have annotated using <- )

```
>>> opensense -C GenericModel.osim Calibration_Orientations.sto
4 <- number of inputs
opensense <- First input (0 index) 
-C <- second input (1 index) 
GenericModel.osim <- third input (2 index) 
Calibration_Orientations.sto <- fourth input (2 index) 
Segmentation fault: 11
```
It seems that that the code may determine teh number of input options differently on Mac than Windows? I was able to fix locally (Mac) by changing the index values for the -Calibrate option, but I don't know if that breaks it on Windows.

**Comment by tkuchida** [comment]
The code [here](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L128) indicates that, for option `-Calibrate` (or `-C`), and [`argc > 2`](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L133), you need to include the "baseImuName" (a string). When [`argc > 3`](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L136), you also need to include a letter (`x`, `y`, or anything else) to indicate the "imuHeading" axis. It looks like your `argc` is 4, so based on [this related example](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/test/testOpensense.cpp#L39), you probably need to use something like
```
opensense -C GenericModel.osim Calibration_Orientations.sto nameOfBaseIMU x
```

**Comment by jimmyDunne** [comment]
The think the design was intended so that you can submit only two inputs (model name and orientation file name) and perform the calibration. The remaining inputs, baseIMU and imuHeading, are optional inputs.

**Comment by tkuchida** [comment]
> The think the design was intended so that you can submit only two inputs (model name and orientation file name) and perform the calibration. The remaining inputs, baseIMU and imuHeading, are optional inputs.

Then [this line](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L133) and [this line](https://github.com/opensim-org/opensim-core/blob/c6372df7b5357be02fd401688f22a9a2b96cf622/Applications/opensense/opensense.cpp#L136) should be checking whether `argc > 4` and `argc > 5`.

**Comment by aymanhab** [comment]
Can this one be verified @jimmyDunne ?

**Comment by jimmyDunne** [comment]
In the latest build, I am able to vary the number inputs and it works as expected. Thanks!
