### ISSUE TITLE
Scaling models with Contact Mesh

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#246]
Additional problem: When you open a model with contact, the contact has to be in the current model dir. When scaled, the model doesn't have a current dir so where should the contact live?

**Comment by aymanhab** [comment]
Also reported on forum post here https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11359&p=31596&start=0&view=

**Comment by aymanhab** [comment]
@carmichaelong did you have a chance to check this with the fix to https://github.com/opensim-org/opensim-gui/issues/1182 Thanks

**Comment by carmichaelong** [comment]
I did not recall checking mesh, only the Geometry. Separately, seems like this issue also documents a separate issue about how some components are scaled and some are not (rather than just a visualization issue)?
