### ISSUE TITLE
GCVSplineSet constructor does not create functions for TimeSeriesTable with no column labels

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2460]
The GCVSplineSet constructor that takes a TimeSeriesTable does not handle tables with no column labels.

**Comment by jenhicks** [comment]
@chrisdembia Is this high or low priority?

**Comment by chrisdembia** [comment]
This is low priority. The workaround we used is to just give column labels. There is a potential for unexpected behavior, though. Perhaps a user is computing RMS error and loops through all columns in a table and doesn't realize that there are missing columns: the resulting error will be incorrectly low.
