### ISSUE TITLE
Enable more user options/settings for transforming data

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2463]
- [ ] IMU world to OpenSim ground transformation and Heading correction are part of a single conversion step from experimental quaternions (of rotations in sensor world) to rotation matrices expressed in OpenSim Ground fame. We should abstract out the expected sensor world definition (e.g. Z-up and X-magnetic north) 

- [x] Enable user to identify the base frame (e.g. the pelvis) and the sensor axis that represents its forward direction, which we use to realign the IMU data with the heading (forward direction) of the base frame of the model.

**Comment by aseth1** [comment]
We need to abstract out the builtin transform from IMU World to OpenSim ground because marker triads already transformed to OpenSim ground reference frame provide orientations in ground, so the additional transform is now an error. This is impacting Hannah, @malborno and team from producing results.

@jimmyDunne @aymanhab I will bump this up into the current sprint backlog.

**Comment by aseth1** [comment]
@aymanhab this change somehow affected `TimeSeriesTableRotation` such that calling `table. getMatrix.getElt()` no longer works. It seems as though `SimTK::Matrix_<Rotation>` is no longer wrapped.

**Comment by aymanhab** [comment]
@aseth1 Indeed you can't get the Matrix of Rotations directly per Sherm's feedback 
https://github.com/opensim-org/opensim-core/pull/2467#issuecomment-498876581, 
but there's a workaround. Take a look at the testcase Java_TestXsensDataReader and let me know if you can work around it.

**Comment by aymanhab** [comment]
We resolved the issue with access to matrix elements (also used in java test case).  @malborno can you comment if this is useful and should be merged in or not yet, and if not what the hold-up, thanks.
