### ISSUE TITLE
Weird Patella Coordinates results when viewed through OpenSim GUI

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2470]
After running through OpenSense Pipeline and not seeing an issue through the visualizer, if I open the calibrated model (Rajagopal model) and load the output motion, the patellas go crazy. In discussion with @aseth1, this may be caused by some assumptions about the coordinate type during the IK study.

**Comment by aseth1** [comment]
I'll tackle this ASAP.

**Comment by aseth1** [comment]
Can this be closed by #2473?

**Comment by jimmyDunne** [comment]
Yes thank you! Issue is fixed now
