### ISSUE TITLE
"NumMarkers" metadata isn't updated when dependent column appended to TimeSeriesTable

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2487]
### Python example

```
import opensim as osim
# read existing TRC file
markers = osim.TRCFileAdapter.read('origfile.trc')
# create and append new dependent column
newcol = osim.VectorOfVec3()
newcol.resize(markers.getNumRows())
newcol.setToZero()
markers.appendColumn('foo', newcol)
# write to file
osim.TRCFileAdapter.write(markers, 'newfile.trc')
# read from file
test = osim.TRCFileAdapter.read('newfile.trc')
```

### Expected result
File can be written and read back.

### Actual result
`IncorrectNumColumnLabels` exception (thrown from [here](https://github.com/opensim-org/opensim-core/blob/7e4f6ab1e3346f9e822a8a63e008ac16ec25b16d/OpenSim/Common/TRCFileAdapter.cpp#L121)).

### Workaround
It looks like the "NumMarkers" metadata key isn't being updated from its old value when `appendColumn()` is called, which is surprising since this key is created automatically if it doesn't exist (thus the user isn't aware of his/her responsibility to update it). Inserting
```
markers.removeTableMetaDataKey('NumMarkers')
```
before writing to file fixes the problem since the "NumMarkers" key will then be re-created automatically with the correct number of columns.

### Version
OpenSim 4.0 public release

**Comment by jimmyDunne** [comment]
TRCFileAdapter.write() should update the meta based on the data.

**Comment by jenhicks** [comment]
@jimmyDunne Need to add to changelog (under bug fixes)
