### ISSUE TITLE
IKTool.run() causes Matlab segfault if performed repeatedly 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2503]
### Steps to reproduce
(Testing data and script in attached zip)

Perform IK.run() repeatedly in Matlab. 
``` Matlab
ik = InverseKinematicsTool('ik_setup_run.xml');
for i = 1:5
    ik.run()
end
```

### Expected result
I should be able to keep performing run() without issue. 

### Actual result
Matlab segfault and complete crash (crash dump message attached). To fix the issue, I have to instantiate the IKTool on every loop. 

``` matlab
for i = 1:5
    ik = InverseKinematicsTool('ik_setup_run.xml');
    ik.run()
end
```

### Environment and GUI version
Mac. 
Tested on OpenSim 4.0 application release and current OpenSim master branch. 
[ik_bug_2.zip](https://github.com/opensim-org/opensim-core/files/3307707/ik_bug_2.zip)
[matlab_crash_dump.53230-1.txt](https://github.com/opensim-org/opensim-core/files/3307711/matlab_crash_dump.53230-1.txt)

**Comment by aymanhab** [comment]
We need to build the libraries debuggable to get more informative crash log. I suspect the issue has to do with trying to open the output files while they are locked/in-use by a previous iteration. If you add a line to wait for a keyboard input inside the loop we can easily check if this is the issue.

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
