### ISSUE TITLE
Matlab_testOsimC3D throws an exception while RUN_TESTS_PARALLEL run

### ISSUE THREAD

**Issue by mkjung99** [opensim-org/opensim-core#2507]
Hello,

After building the current latest master branch, and I performed the RUN_TEST_PARALLEL.
Then all tests passed except one,  Matlab_testOsimC3D.

Following is the log of that failure:
```
An exception has been thrown during the execution
  MException with properties:

    identifier: 'MATLAB:mir_cannot_index_function'
       message: 'Error: Functions cannot be indexed using {} or . indexing.'
         cause: {}
         stack: [1x1 struct]

    file: 'C:\WORKSPACE_DEV\opensim_core_source\Bindings\Java\Matlab\tests\testOsimC3D.m'
    name: 'testOsimC3D'
    line: 16
```

Environments: Current master build, Windows 10 x64, VS 2017 x64(v140 option), JDK 1.8.0_211, SWIG 3.0.9, Python 3.7.3 x64(Anaconda), MATLAB 2019b X64

Best regards,
Moon

**Comment by aymanhab** [comment]
@jimmyDunne I believe you run these tests locally on your machine, does this reproduce for you? I understand @mkjung99 is on Windows with possibly different Matlab version.

**Comment by jimmyDunne** [comment]
All Matlab tests, run locally, seem to pass. This may have been issue in June when the issue was posted but was subsequently fixed. 

![image](https://user-images.githubusercontent.com/5296507/68611588-7a2c2c00-0488-11ea-8f5f-2f0ffcb49e6b.png)

**Comment by aymanhab** [comment]
Thanks @jimmyDunne, Please check with the latest master and report back @mkjung99 so we can investigate further or close. Thank you

**Comment by jimmyDunne** [comment]
tests pass locally, including testOsimC3D. The issue can be closed.
