### ISSUE TITLE
Function Based Bushing does not apply rotational damping

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2512]
{Reported during workshop}

**Comment by aymanhab** [comment]
Thanks @jimmyDunne, Was there a sample model provided to work with?

**Comment by jimmyDunne** [comment]
I edited an existing model.

**Comment by jimmyDunne** [comment]
No, not that I am aware of.

**Comment by aymanhab** [comment]
fixed by PR #2514
