### ISSUE TITLE
Add Cube Analytical Geometry

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2513]
There is currently no cube analytical geometry

**Comment by aymanhab** [comment]
There's a Brick with arbitrary half-length(s) why is it not adequate?

**Comment by jimmyDunne** [comment]
> Abstract class for analytical geometry (e.g. surfaces of revolution) whose
>  rendering is optimized by the graphics library (e.g. threejs). Unlike other
>  geometry, property edits require a recreation of the AnalyticGeometry on
>  the renderer and not simple updates. AnalyticGeometry is the base class for
>  Sphere, Cylinder, Cone, Ellipsoid and Torus geometry.

There is no record of a brick so not sure how I was supposed to find it unless I knew it was called 'brick'. I don't think brick is a good name, it is not a supra-class of shape.
