### ISSUE TITLE
Add finalizeConnections() to multiple C++ Example files and throw exceptions on bad models

### ISSUE THREAD

**Issue by vinaym815** [opensim-org/opensim-core#2526]
Please add finalizeConnections() command to the the list of C++ examples that follows, as deserializing the saved model without it causes issue.

1) OpenSim/Examples/ExampleMain/OutputReference/TugOfWar_Complete.cpp   (line 289)
2) OpenSim/Examples/checkEnvironment/checkEnvironment.cpp  (line198)
3) OpenSim/Examples/CustomActuatorExample/toyLeg_example.cpp  (line 220)
4) OpenSim/Examples/MuscleExample/mainFatigue.cpp  (line 243)

**Comment by tkuchida** [comment]
The lines of code you have referred to are calling `Model::print()`. If these lines don't work, it likely means that you are trying to save the file to a directory where you do not have write access.

**Comment by vinaym815** [comment]
The printing works fine, but when I try to load the saved model in a different script and initialize it I face the  issue.

**Comment by tkuchida** [comment]
Ah, thanks for clarifying. Yes, it seems that it is necessary to call `Model::finalizeConnections()` before serializing, as in [this example](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Test/testForces.cpp#L627). A potential source of confusion is that `Model::initSystem()` calls the `finalize...()` methods under the hood, so an explicit call to `finalizeConnections()` is not necessary if `initSystem()` has been called (which is true in most situations).

**Devs:** Perhaps `Object::print()` should call `finalizeConnections()` automatically (or at least throw an informative exception for the user to call `finalizeConnections()` if it can't be called from `Object::print() const`).

**Comment by jimmyDunne** [comment]
Thanks, @vinaym815. Would you be willing to make the changes and submit a PR? We are always keen to get community contributions to improve the code 😉

**Comment by aymanhab** [comment]
I'd vote to have print call the method internally unless there's strong reason against it. This has the benefit of not exposing and requiring users to understand the rather complex internals of how models are wired which may undergo changes in the future.

**Comment by tkuchida** [comment]
@aymanhab Not sure that would be permitted/desirable since `Model::print()` is const, but I agree that it would be better if the user didn't need to worry about the internal details—at least in typical use cases.

**Comment by aymanhab** [comment]
@tkuchida from a  user perspective I find it troubling that I need to call finalizeConnections even though there's no explicit reference to any "connections" earlier, at least in some of these examples (e.g. checkEnvironment). Another reason an explicit staging would've been useful IMHO.

**Comment by aseth1** [comment]
@aymanhab in these examples the model is being edited-- components added and properties changed. While there is no explicit reference to "connections" I don't see it as unreasonable to still interpret that the interconnections of the model are changing. After all, components are being added to the Model.

We could also move the `print()` to after the System is initialized in many cases  as in `checkEnvironment.cpp`. 

For the same reason I disagree with `print()` updating the model and its properties under the covers. We went through some trouble of making `print` const and I don't want to see us unwind it.

I am happy to hear/see other solutions to the finalizing properties and connections.  Can you describe/propose your explicit staging mechanism with some example use cases?

**Comment by aymanhab** [comment]
@aseth1 there's already an open issue from 2 years ago by @tkuchida for this staging mechanism https://github.com/opensim-org/opensim-core/issues/1668

Similar to how we do explicit clone before we print in 
https://github.com/opensim-org/opensim-core/blob/840bfac5d28a70a16335f441950bf669407031e2/OpenSim/Simulation/Test/testContactGeometry.cpp#L174

We can keep print const and internally clone and finalizeConnections or just clone and embed finalizeConnections in clone() so we don't unwind anything but model files we print are not broken.

I know that for developers inside the team modifying the model means changing connections but for others introducing a new term ("connections") would be confusing and adds to the mystery of what methods do they need to call and when.

**Comment by aseth1** [comment]
@aymanhab #1668 is not a proposal, it is a request to introduce such a mechanism. What is your proposal for the mechanism? How would you introduce a  SimTK::Stage for model building and simulation in OpenSim? How would you leverage it to avoid the explicit calls to the current "staged" methods? How would this be different other than calling `Model::realize(Connections)`? If that is a more desirable interface, I can see us transitioning to it, but it doesn't change the number of calls or the fact that user's have to know about "connections". 

Staging is necessary in Simbody to manage a hidden cache in the State for an entire System. What is the analogous Cache that we need to keep up-to-date? It seems this would be properties themselves. Some properties (like Socket connections) can only be valid after other properties (list of subcomponents) are defined. There is another "staging" order  that involves the order in which the system is built and how dependencies are resolved, but that is another issue altogether (#413).

>We can keep print const and internally clone and finalizeConnections or just clone and embed finalizeConnections in clone() so we don't unwind anything but model files we print are not broken.

I'm not a fan of these solutions. They seem dirty to me. Printing should be clean, involve no computing, no cloning,  and be const and represent exactly what your model is. This is not the case and would introduce inconsistencies: 

1. model is edited (create and add Bodies and Joints)
2. `model.print()` (clones and finalizes the clone, which now has valid connections, but model does not)
3. `model.getComponent<Joint>("knee").getParentFrame();` // throws invalid connection, tells you to call finalizeConnections()
4. check the model XML file you printed. Hey! It says `socket_parent_frame` is satisfied by "femur_offset", what gives? 

I believe  this will lead us down the path of peppering `finalizeConnections` calls after every model editing call, which defeats the purpose of having explicit "stages". I rather have users call `finalizeConnections` if and when they change their model AND they want to serialize the connection status after resolving the connections. 

> I know that for developers inside the team modifying the model means changing connections but for others introducing a new term ("connections") would be confusing and adds to the mystery of what methods do they need to call and when.

What would you prefer to use other than "Connections?" Is your issue with the terminology or the fact you have to call any method before you print() when you want to capture the final inter-connectivity of your Model?

**Comment by aymanhab** [comment]
Thanks for the feedback @aseth1, I'll copy your comments regarding stages to issue #1668 so we can continue the discussion there.

1. Regarding the name finalizeConnections, I find it meaning very little, if you're constructing components and adding them to a model. Something like "finalizeEditing" would be more sensible for users to follow but again it's outside the scope of this PR.  Best if automated but if not then a user-friendly name would help.

2. My main concern here is sprinkling these finalizeConnections, where our users are already having a hard-time figuring out when to call initSystem.

@vinaym815 can you comment on how you ended up with these files, I ran into similar issue in testVisualization.cpp which was not on the list (so you can understand my concern in 2.)

**Comment by vinaym815** [comment]
After going through c++ examples, I was trying to edit gait2354 model, serialize it, deserialize it (another script) and run some simulations. However, I couldn't do so since none of the examples suggested the use of finalizeConnections before printing. When I tried to load the error-laden model in OpenSim Application, it gave me an error (Figure below) regarding finalizeConnections, and that's how I came through it.

<img width="488" alt="Error" src="https://user-images.githubusercontent.com/35987596/61385103-72d88580-a8cf-11e9-8b44-75d13a840784.PNG">

**Comment by aymanhab** [comment]
Thanks @vinaym815 for explaining, I was just trying to understand if the list of examples/fixes is exhaustive.  Thank you.

**Comment by vinaym815** [comment]
@aymanhab Sorry, it's not exhaustive. I just looked at some of the c++ examples.
Thank you

**Comment by aymanhab** [comment]
@chrisdembia I understand the reason for the try/catch block around "Object::warnBeforePrint", however this allowed examples and test cases to produce bad files that are going to cause problems downstream. I removed the try/catch locally and a few more test cases failed. 

What do you think about a 'strict' mode (where we run our examples/tests) without the try/catch block and lenient mode for users so at least we don't distribute broken code/examples.

**Comment by chrisdembia** [comment]
I’m fine with that.

**Comment by aymanhab** [comment]
I opened a PR to turn the warning to Exception so that we don't produce bad files in our examples and test cases. #2529

**Comment by jenhicks** [comment]
Need to update the changelog.

**Comment by jenhicks** [comment]
@aymanhab Can you update the changelog (for issue #2529)? Then I believe we can close this issue.

**Comment by aymanhab** [comment]
@jenhicks I don't think this rises to the level that interests users, we had bad examples that we fixed so they create correct model files. If you still think it's useful I'll add a note to the changelog so let me know.

**Comment by jenhicks** [comment]
Just to confirm, you don't think that PR #2529 warrants a note in the changelog? (I agree that the fix to the examples does not need to be noted in the changelog)

**Comment by aymanhab** [comment]
Good point, while the method warnBeforePrint is private, the change in behavior indeed affects the public print method so I'll add a note.

**Comment by jenhicks** [comment]
Thanks ... closing this issue.
