### ISSUE TITLE
Matlab tests don't seem to be working locally

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2533]
Matlab tests don't seem to be running locally out of the box. 

```
>> ctest -R Matlab_Simbody
No tests were found!!!
```

There was some previous work on setting the Matlab home dir in #1829

**Comment by aymanhab** [comment]
The magic line that makes the tests run follows 

> ctest --tests-regex Matlab --build-config release --extra-verbose

One test case fails for C3D but I think this is specific to this test since other tests open files/models without an issue. Same happens when you run "Matlab - run tests" target in MSVC. Please confirm eitherway @jimmyDunne

**Comment by jenhicks** [comment]
Try to create a shortcut on Mac.

**Comment by jimmyDunne** [comment]
This seems to work fine now (MacOS, Terminal, Make). I am not having issue. Thanks @aymanhab
