### ISSUE TITLE
CI builds are failing on latest linux

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2534]

**Comment by aymanhab** [comment]
PR #2531 in progress to address.

**Comment by aymanhab** [comment]
While not supporting latest linux (requires upgrade to btk and simbody) PR #2531 upgrades clang to version 5 (from 3.5) making it less urgent to migrate to latest Linux and clang.

**Comment by aymanhab** [comment]
This can be moved out of the sprint backlog once PR has been merged.
