### ISSUE TITLE
Distribute SWIG interface files

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2538]
For Moco, it'd be great if opensim-core's installation included SWIG interface files and any other SWIG inputs (`OpenSimHeaders_*.h`).

**Comment by chrisdembia** [comment]
I already created this issue :)

**Comment by aymanhab** [comment]
@chrisdembia The main problem here is that the SWIG wrapping uses the custom decorated version of SimTK headers that can be digested by SWIG. We don't want to distribute these files pending SWIG upgrades/improvements. Can we do without these files from Bindings\SWIGSimTK?

**Comment by chrisdembia** [comment]
Ah good point; I hadn't thought about that.

 The better solution is that we bring Moco into `opensim-core`. This issue would just be a temporary solution.

**Comment by jenhicks** [comment]
@chrisdembia Is this issue still relevant given our Moco integration plan?

**Comment by chrisdembia** [comment]
Nope.
