### ISSUE TITLE
Python's distutils fails to build bython bindings

### ISSUE THREAD

**Issue by yurivict** [opensim-org/opensim-core#2543]
https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/setup.py

```setup.py``` is supposed to be able to build the bindings by itself, but it fails:
```
===>  Building for py36-opensim-4.0.601
running build
running build_py
error: package directory 'opensim' does not exist
*** Error code 1
```

The point of ```setup.py``` is usually that it is able to build the python module just having the dependency software installed, regardless of anything else.

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
