### ISSUE TITLE
Please allow to build the python and Java bindings separately from the C++ library

### ISSUE THREAD

**Issue by yurivict** [opensim-org/opensim-core#2544]
Multiple python versions can be installed at the same time, while C++ librrary is just one package.

In order to allow multiple versions of python to use OpenSim there should be a way to build/install the Python binding separately.

For example, you can add the ```OPENSIM_PYTHON_ONLY``` cmake variable that would build the python module using the pre-installed OpenSim package.

**Comment by yurivict** [comment]
Same for the Java binding. I have to enable the Java binding for all users in the FreeBSD port, but people who don't need the Java binding should be able to install the C++ library without having Java.

**Comment by aymanhab** [comment]
Why do you have to @yurivict ? What issues/failures do you run into if you turn off both Java and Python bindings? and on what platform(s)?
