### ISSUE TITLE
Update any additional places where we use readFile

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2554]
Search for stoFileAdapter().readFile() or trcFileAdapter().readFile()

**Comment by jimmyDunne** [comment]
I haven't been able to find any uses of STOFileAdapter().read(*) or TRCFileADapter().read(*) in any Python or Matlab production code. I also checked the GUI repo in case of use in the GUI scripts (we don't). Seems like we tend to still use Storage() when reading in motion files. 

We should update the API documentation API Guide for reading and writing data (https://github.com/opensim-org/opensim-core/issues/2557)

**Comment by jenhicks** [comment]
Are you OK with closing this then?
