### ISSUE TITLE
Update API Guide for reading and writing data

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2557]
https://simtk.org/api_docs/opensim/api_docs/md_doc_APIGuide.html

See section on "Data Handling Classes"

**Comment by jenhicks** [comment]
@aymanhab can you take a first pass

**Comment by aymanhab** [comment]
Sure, where is it on confluence? can you post a link? Thanks

**Comment by jimmyDunne** [comment]
https://github.com/opensim-org/opensim-core/blob/master/doc/APIGuide.md
