### ISSUE TITLE
OpenSim 4.0 API Python 3

### ISSUE THREAD

**Issue by rampagedog12** [opensim-org/opensim-core#2566]
OS: Windows 10

My OpenSim is installed via binary file.
I get the error when using Opensim API in the python 3 environment.

```
Python 3.6.8 |Anaconda, Inc.| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OpenSim 4.0\sdk\Python\opensim\__init__.py", line 1, in <module>
    from .simbody import *
  File "C:\OpenSim 4.0\sdk\Python\opensim\simbody.py", line 18, in <module>
    _simbody = swig_import_helper()
  File "C:\OpenSim 4.0\sdk\Python\opensim\simbody.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\hwy19\Miniconda3\envs\dacaa\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.
```

There is no error when I switch to python 2.

I check the document, for python 3, I should build from source??
I get other errors building from source, when BUILD_PYTHON_WRAPPING and BUILD_JAVA_WRAPPING are checked.
```
NOTICE: Make sure all OpenSim dependencies are built with the same CMAKE_BUILD_TYPE (Linux) or CONFIGURATION (Xcode/MSVC) as OpenSim to avoid mysterious runtime errors.
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
  least version "3.0.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindSWIG.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Bindings/CMakeLists.txt:4 (find_package)

```
I conda install swig, but it doesn't work. Get the same error above.
How to make OpenSim 4.0 API Python 3 work?

One more question, to have a GUI like OpenSim 4.0 installed via binary file. I need to build opensim-core from source and then build opensim-gui from source?

**Comment by aymanhab** [comment]
Not sure what's your platform but latest build of master branch is now against Python 3.7, you may try that by following the links on github for Windows, can point you to the Mac osx build. We typically build and test against standard python from python.org not other pythons from vendors (Anaconda, Canopy ...) Since each one is built on top of low level system libraries/runtime there could be inconsistencies, so I'd try the standard python environment first.

**Comment by rampagedog12** [comment]
@aymanhab Sorry, I forgot to mention the system. It is Win 10. I didn't install Chocolatey, because I thought it may mess up.... Now I am installing Chocolatey and keep trying..

**Comment by aymanhab** [comment]
Try OpenSim 4.1 Beta from here [https://ci.appveyor.com/project/opensim-org/opensim-core/builds/27371266/job/bi3g1cdnt5yycgpm/artifacts] it comes with Python 3 wrapping provided and a few extra bug fixes, the build script uses python 3.7

**Comment by rampagedog12** [comment]
I got error when building 4.0.
```
       "C:\opensim_build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\opensim_build\Bindings\Java\JavaBindings.vcxproj" (default target) (4) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cm
       d.exe" exited with code 1. [C:\opensim_build\Bindings\Java\JavaBindings.vcxproj]

    34 Warning(s)
    1 Error(s)
```
I will try 4.1 later

**Comment by rampagedog12** [comment]
@aymanhab OK I made it.. I think the error may be caused by expiration of my MatLab.

**Comment by antoinefalisse** [comment]
Hi @aymanhab, I am having troubles getting Python 3.7 to work. I am on Win 10 and I built OpenSim from source (master branch) with Python 3 without troubles. I added the bin folder to the path and ran `python setup.py install` without issues. I now have an egg file `opensim-4.1-py3.7_old.egg` in my `anaconda3/Lib/site-packages`. Yet running `import opensim` within spyder gives me the following:

```
import opensim
Traceback (most recent call last):

  File "<ipython-input-2-d100d6ac66f2>", line 1, in <module>
    import opensim

  File "C:\Users\u0101727\AppData\Local\Continuum\anaconda3\lib\site-packages\opensim-4.1-py3.7.egg\opensim\__init__.py", line 1, in <module>
    from .simbody import *

  File "C:\Users\u0101727\AppData\Local\Continuum\anaconda3\lib\site-packages\opensim-4.1-py3.7.egg\opensim\simbody.py", line 13, in <module>
    from . import _simbody

ImportError: cannot import name '_simbody' from 'opensim' (C:\Users\u0101727\AppData\Local\Continuum\anaconda3\lib\site-packages\opensim-4.1-py3.7.egg\opensim\__init__.py)
```

I have tried other SWIG versions but without success (note that with 3.0.12 I had another issue). I am not sure how to debug. I have extracted the files in the egg file and I see for instance `_simbody.lib` and `_simbody.pyd`...

Any idea about what could go wrong? @rampagedog12, maybe you are familiar with this issue? Thanks!

**Comment by rampagedog12** [comment]
@antoinefalisse I am not sure... Could you test it in python 3.6? I remember my teammate has a problem when he used the newer version of python, but I don't remember the error message... Another problem I encountered was PYTHONPATH, but I don't think it causes the problem you mentioned.

**Comment by aymanhab** [comment]
@antoinefalisse can you try python 3.7 from python.org? We use this in our test environment with no issues for a few months already. Is there a chance you're using 32 bit version of python and loading x64 libraries or vice versa?

**Comment by nickbianco** [comment]
@antoinefalisse the issue could be a mismatch between Visual Studio versions used to build Python and OpenSim. Not totally sure though. I had a similar issue when using Moco through Python and I had to use a dependency walker tool to solve it (I was had built with SNOPT but hadn't included the snopt.lib file in my path).

**Comment by nickbianco** [comment]
I would also double check the Spyder is loading your Windows environment correctly. You may want to try importing OpenSim through Python a different way (i.e. command line or Powershell).

**Comment by chrisdembia** [comment]
The Python error is pretty vague. You can get a better sense of which library dependency is causing an issue by using either Dependency Walker http://www.dependencywalker.com or Dependencies https://github.com/lucasg/Dependencies

**Comment by antoinefalisse** [comment]
Thanks all for your help, I realized that typing `import opensim` in the IPython console was giving the error above, whereas running a script with `import opensim` saved in the `opensim-core-install\sdk\Python` folder was working. So I added the following lines on top my script:

```
osim_path = '.../opensim-core-install/sdk/Python'
sys.path.insert(0,osim_path)
import opensim
```

and it worked fine. Seems thus to be a path issue (note that `.../opensim-core-install/bin` is in my computer path). Maybe I need to add another path somewhere else? I just followed the instructions in the OpenSim documentation. I am fine with the current workaround, just surprised it works for others without any troubles (@carmichaelong).

**Comment by nickbianco** [comment]
I don't think you should need to include the location of the OpenSim Python libraries directly in your path, Anaconda should handle that for you after the .egg file is installed. It could be that Spyder (or IPython) is loading the wrong Python environment on start-up. I don't use either frequently, but when I've used Spyder, I try to launch it from Powershell with the conda environment I want activated already.

Glad you got it to work though, this is helpful for narrowing down the issue.

**Comment by carmichaelong** [comment]
It's definitely important to make sure that the right Anaconda environment is being used. Both of my installs have been with Spyder with the Anaconda package.

Depending on how annoying the workaround is, it might be worth trying to delete the folder that OpenSim installs into the python distribution (e.g., for my Anaconda3 install, it's located at `C:\Anaconda3\Lib\site-packages\opensim-4.0-py3.7.egg`) and re-doing the setup. While I didn't have issues with that on my recent installs with Python 3.7, I'm remembering that I've had to do that before on some previous versions, likely due to me not being careful with the Anaconda environments.
