### ISSUE TITLE
Visualizer does not display correctly first point of a muscle GeometryPath when using MovingPathPoint

### ISSUE THREAD

**Issue by modenaxe** [opensim-org/opensim-core#2569]
Hello, the visualiser does not seem to display correctly the first point of a muscle GeometryPath when the first point is defined using a MovingPathPoint (see image below). You can find here ([a model and motion file](https://github.com/opensim-org/opensim-core/files/3636998/bug_visualizer.zip)) to replicate the issue. If you load the osim file and the Walk.mot file, you will see a Thelen muscle model (gluteus medius) with first path point fixed in space, instead of moving as prescribed by the SimmSpline in the MovingPathPoint named "P_0".
![image](https://user-images.githubusercontent.com/7674529/65345195-9a024a80-dbd1-11e9-9de4-fb7f0fa7fdde.png).
Thank you, Luca

**Comment by aymanhab** [comment]
@modenaxe Thanks for reporting, but the moving pathpoint is expressed in ground frame is that the expected behavior? It sure will not move with the model regardless of the motion, am I missing something here?

**Comment by modenaxe** [comment]
@aymanhab the locations of all points in the muscle are expressed in ground frame as a (non-constant) function of the coordinate pelvis_tx of the motion trial. The expected behaviour should be a "normal" geometry path connecting pelvis and femur through many via points, as in figure below. We use this approach for visualizing muscles paths that we derive from another tool, and it worked in OpenSim v3.3. The issue is present when the model and the motion file are loaded normally, but if you select that "incorrect" first point using the GUI, and change the parent frame from ground to pelvis and back, OpenSim will update its locations to the correct one specified in the SimmSpline  (see figure below). Maybe that first point is not updated and goes to a default location?
![image](https://user-images.githubusercontent.com/7674529/65416405-a106a400-ddef-11e9-88a8-5ae429dc177e.png)

**Comment by aymanhab** [comment]
Issue moved to [opensim-org/opensim-gui #1141](https://github.com/opensim-org/opensim-gui/issues/1141) via [**ZenHub**](https://www.zenhub.com/)
