### ISSUE TITLE
Installation instructions should provide a recommendation for where to install OpenSim

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2571]
AFAIK we recommend that users install OpenSim to a folder for which their user account always has write access (i.e., a non-system directory). Perhaps we should alert users of this in the installation instructions since most people naturally install software to a system directory.

**Comment by tkuchida** [comment]
https://simtk-confluence.stanford.edu/display/OpenSim/Installing+OpenSim

**Comment by jenhicks** [comment]
@aymanhab What are the recommendations? I'm happy to add a note in the confluence doc.

**Comment by aymanhab** [comment]
@jenhicks On Windows, if you ask the installer to install into "C:/Program Files/OpenSim 4.0' for example, the installation will abort due to Error opening file for writing. The default given by the installer is C:\OpenSim 4.0 which is not a system folder. Yes, we should tell users to choose a folder that they can write to. Not sure the behavior on osx since I don't have my Mac with me today.

**Comment by jenhicks** [comment]
I added the following to the confluence page Tom linked to. Feel free to edit or add additional details.

> The next screen will ask you to select the folder in which to install OpenSim. You must choose a folder where OpenSim will be able to write to files  (e.g., on Windows, you cannot install to "C:/Program Files/OpenSim 4.0", since this is a system system folder). Choose the folder and click the Next button to continue.

**Comment by aymanhab** [comment]
Looks great, it would be good to check the osx limitations as well which I can try on my Mac later (worst case is if it allows the installation to go through but fails to open/operate properly afterwards).

**Comment by jenhicks** [comment]
@aymanhab were you able to try this out on your Mac?

**Comment by aymanhab** [comment]
@jenhicks The defaults offered are perfectly fine on osx I never needed to change it.
