### ISSUE TITLE
C3DFileAdapter exports only markers and external forces

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#2575]
c3d files contain a rich set of information, such as emg from analog sources. Currently, the C3DFileAdapter provides access only to the marker and external force measurements. As more and more people will start using this functionality, I recommend that at least we provide access either to the underlying btk object or export all the information into OpenSim's table objects.

**Comment by jimmyDunne** [comment]
We would love to support more data types but I don't think we will be able to address it until we decide when to remove BTK for a different C3D reading package. Will keep in the list.
