### ISSUE TITLE
Test #94: python_tests failed while building

### ISSUE THREAD

**Issue by dheerajakula** [opensim-org/opensim-core#2581]
os = windows10
cmake version = 3.11.0
ms-vs = visual studio 15 2017
python version = Python 2.7.16 32 bit
swig version = swigwin-4.0.1
BUILD_PLATFORM = Windows:x86

Followed the readme on **Building from the source code** **On Windows using Visual Studio**. Succesfully built dependencies using **Superbuild**. Opened _C:/opensim-core-build/OpenSim.sln_ succesfully built **ALL_BUILD**.  Build **RUN_TESTS_PARALLEL** fails.

1>------ Build started: Project: RUN_TESTS_PARALLEL, Configuration: RelWithDebInfo Win32 ------
1>Test project F:/Github_Workspace/opensim-core-build
1>      Start 94: python_tests
1>      Start 56: testOptimizationExampleRuns
1>      Start 54: testExampleMainRuns
1>      Start 60: testMuscleExampleRuns
1>      Start 52: testControllerExampleRuns
1>      Start 58: testCustomActuatorExampleRuns
1>      Start 62: testSimpleOptimizationExampleRuns
1>      Start 92: testOpensense
1> 1/95 Test #62: testSimpleOptimizationExampleRuns ............   Passed    0.77 sec
1>      Start 90: testCMCWithControlConstraintsRunningModel
1> 2/95 Test #58: testCustomActuatorExampleRuns ................   Passed    1.06 sec
1>      Start 85: testCMCGait10dof18musc
1> 3/95 Test #52: testControllerExampleRuns ....................   Passed    1.29 sec
1>      Start 76: testStaticOptimization
1> 4/95 Test #60: testMuscleExampleRuns ........................   Passed    5.75 sec
1>      Start 89: testCMCWithControlConstraintsGait2354
1> 5/95 Test #54: testExampleMainRuns ..........................   Passed   13.32 sec
1>      Start 77: testForward
1> 6/95 Test #94: python_tests .................................***Failed   14.02 sec
1>test_component_filter (test_access_subcomponents.TestAccessSubcomponents) ... Updating Model file from 20303 to latest format...
1>Loaded model arm26 from file F:\Github_Workspace\opensim-core-build\Bindings\Python\RelWithDebInfo\opensim\tests\arm26.osim
1>Couldn't find file 'ground_ribs.vtp'.
1>Couldn't find file 'ground_spine.vtp'.
1>Couldn't find file 'ground_skull.vtp'.
1>Couldn't find file 'ground_jaw.vtp'.
1>Couldn't find file 'ground_r_clavicle.vtp'.
.
.
.
1>======================================================================
1>CUSTOMBUILD : error : test_component_filter (test_access_subcomponents.TestAccessSubcomponents)
1>----------------------------------------------------------------------
1>Traceback (most recent call last):
1>  File "F:\Github_Workspace\opensim-core-source\Bindings\Python\tests\test_access_subcomponents.py", line 85, in test_component_filter
1>    comps = model.getMuscleList()
1>AttributeError: 'Model' object has no attribute 'getMuscleList'
1>
1>======================================================================
1>CUSTOMBUILD : error : test_component_list (test_access_subcomponents.TestAccessSubcomponents)
1>----------------------------------------------------------------------
1>Traceback (most recent call last):
1>  File "F:\Github_Workspace\opensim-core-source\Bindings\Python\tests\test_access_subcomponents.py", line 32, in test_component_list
1>    for body in model.getBodyList():
1>AttributeError: 'Model' object has no attribute 'getBodyList'
1>
1>----------------------------------------------------------------------
1>Ran 56 tests in 11.985s
1>
1>FAILED (errors=2)
1>
1>      Start 88: testCMCTwoMusclesOnBlock
1> 7/95 Test #88: testCMCTwoMusclesOnBlock .....................   Passed  120.62 sec
1>      Start 93: testCommandLineInterface
1> 8/95 Test #56: testOptimizationExampleRuns ..................   Passed  189.65 sec
.
.
.
99% tests passed, 1 tests failed out of 95
1>Total Test time (real) = 432.55 sec     
1>The following tests FAILED:
1>	 94 - python_tests (Failed)
1>Errors while running CTest
1>Done building project "RUN_TESTS_PARALLEL.vcxproj" -- FAILED.

**Comment by aymanhab** [comment]
The swig version you're using is more recent which can introduce unknowns. 

Good trying to test 32 bit environment, however we stopped supporting 32 bit a while ago. Can you build x64 instead so we can reproduce. Thanks

**Comment by dheerajakula** [comment]
Even if the tests got failed, I was able to build **INSTALL** and run the example code on **readme.md** in python. I think I may get problems down the line when using  model.getMuscleList() or model.getBodyList(). Anyways I will try to compile in 64-bit to be sure and update here.

**Comment by dheerajakula** [comment]
Got the same exact error with 64 bit version too. Using the same swig version.

1>======================================================================
1>CUSTOMBUILD : error : test_component_filter (test_access_subcomponents.TestAccessSubcomponents)
1>----------------------------------------------------------------------
1>Traceback (most recent call last):
1>  File "F:\Github_Workspace\opensim-core-source\Bindings\Python\tests\test_access_subcomponents.py", line 85, in test_component_filter
1>    comps = model.getMuscleList()
1>AttributeError: 'Model' object has no attribute 'getMuscleList'
1>
1>======================================================================
1>CUSTOMBUILD : error : test_component_list (test_access_subcomponents.TestAccessSubcomponents)
1>----------------------------------------------------------------------
1>Traceback (most recent call last):
1>  File "F:\Github_Workspace\opensim-core-source\Bindings\Python\tests\test_access_subcomponents.py", line 32, in test_component_list
1>    for body in model.getBodyList():
1>AttributeError: 'Model' object has no attribute 'getBodyList'
1>
1>----------------------------------------------------------------------

**Comment by aymanhab** [comment]
Please post description/log of your latest build environment. which version of python you're using, and where you got it from. Automated builds run regularly with python 3.7 from python.org on windows x64 machines. Build logs here https://ci.appveyor.com/project/opensim-org/opensim-core/builds/28701353

**Comment by frederico-klein** [comment]
Interestingly enough, I get this error with an:
Ubuntu 18.04 based docker running on a debian 11 system, with:
 
swig 3.0.8
cmake 3.6.0
python 3.6.9
`ctest -R python_tests -VV`

then on the end:

    95: ======================================================================
    95: ERROR: test_component_filter (test_access_subcomponents.TestAccessSubcomponents)
    95: ----------------------------------------------------------------------
    95: Traceback (most recent call last):
    95:   File "/opensim-core/Bindings/Python/tests/test_access_subcomponents.py", line 85, in test_component_filter
    95:     comps = model.getMuscleList()
    95: AttributeError: 'Model' object has no attribute 'getMuscleList'
    95: 
    95: ======================================================================
    95: ERROR: test_component_list (test_access_subcomponents.TestAccessSubcomponents)
    95: ----------------------------------------------------------------------
    95: Traceback (most recent call last):
    95:   File "/opensim-core/Bindings/Python/tests/test_access_subcomponents.py", line 32, in test_component_list
    95:     for body in model.getBodyList():
    95: AttributeError: 'Model' object has no attribute 'getBodyList'
    95: 


exact (?) same problem ?

---
sure enough, in python3 if I do:
`dir(m)` , where m is an opensim model, i have the list:
        
     ['PrintPropertyInfo', 'RegisterType', 'RenameType', 'SafeCopy', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__swig_destroy__', '__weakref__', '_has_output_com_acceleration', '_has_output_com_position', '_has_output_com_velocity', '_has_output_kinetic_energy', '_has_output_potential_energy', '_markAdopted', 'addAnalysis', 'addBody', 'addComponent', 'addConstraint', 'addContactGeometry', 'addController', 'addForce', 'addJoint', 'addMarker', 'addModelComponent', 'addProbe', 'addToSystem', 'appendToValidationLog', 'append_BodySet', 'append_ComponentSet', 'append_ConstraintSet', 'append_ContactGeometrySet', 'append_ControllerSet', 'append_ForceSet', 'append_JointSet', 'append_MarkerSet', 'append_ModelVisualPreferences', 'append_ProbeSet', 'append_assembly_accuracy', 'append_credits', 'append_force_units', 'append_gravity', 'append_ground', 'append_length_units', 'append_publications', 'applyDefaultConfiguration', 'assemble', 'assign', 'buildSystem', 'calcKineticEnergy', 'calcMassCenterAcceleration', 'calcMassCenterPosition', 'calcMassCenterVelocity', 'calcPotentialEnergy', 'cleanup', 'clearConnections', 'clearValidationLog', 'clone', 'computeControls', 'computeStateVariableDerivatives', 'connectToModel', 'constructProperty_BodySet', 'constructProperty_ComponentSet', 'constructProperty_ConstraintSet', 'constructProperty_ContactGeometrySet', 'constructProperty_ControllerSet', 'constructProperty_ForceSet', 'constructProperty_JointSet', 'constructProperty_MarkerSet', 'constructProperty_ModelVisualPreferences', 'constructProperty_ProbeSet', 'constructProperty_assembly_accuracy', 'constructProperty_credits', 'constructProperty_force_units', 'constructProperty_gravity', 'constructProperty_ground', 'constructProperty_length_units', 'constructProperty_publications', 'copyProperty_BodySet', 'copyProperty_ComponentSet', 'copyProperty_ConstraintSet', 'copyProperty_ContactGeometrySet', 'copyProperty_ControllerSet', 'copyProperty_ForceSet', 'copyProperty_JointSet', 'copyProperty_MarkerSet', 'copyProperty_ModelVisualPreferences', 'copyProperty_ProbeSet', 'copyProperty_assembly_accuracy', 'copyProperty_credits', 'copyProperty_force_units', 'copyProperty_gravity', 'copyProperty_ground', 'copyProperty_length_units', 'copyProperty_publications', 'deleteUnusedMarkers', 'disownAllComponents', 'dump', 'equilibrateMuscles', 'extendAddToSystem', 'extendConnectToModel', 'extendFinalizeFromProperties', 'extendInitStateFromProperties', 'extendSetPropertiesFromState', 'finalizeConnections', 'finalizeFromProperties', 'findComponent', 'formQStorage', 'formStateStorage', 'generateDecorations', 'getAbsolutePath', 'getAbsolutePathString', 'getActuators', 'getAllControllersEnabled', 'getAnalysisSet', 'getAuthors', 'getBodySet', 'getClassName', 'getComponent', 'getComponentsList', 'getConcreteClassName', 'getConnectee', 'getConstraintSet', 'getContactGeometrySet', 'getControllerSet', 'getControls', 'getControlsTable', 'getCoordinateSet', 'getCoordinatesInMultibodyTreeOrder', 'getCredits', 'getDebugLevel', 'getDefaultControls', 'getDefaultInstanceOfType', 'getDefaultSubsystem', 'getDescription', 'getDiscreteVariableValue', 'getDisplayHints', 'getDocumentFileName', 'getDocumentFileVersion', 'getForceSet', 'getForceSubsystem', 'getForceUnits', 'getGravity', 'getGravityForce', 'getGround', 'getInertiaAboutMassCenter', 'getInlined', 'getInput', 'getInputFileName', 'getInputNames', 'getJointSet', 'getLengthUnits', 'getMarkerSet', 'getMatterSubsystem', 'getMiscModelComponentSet', 'getModel', 'getModelingOption', 'getMultibodySystem', 'getMuscles', 'getName', 'getNumAnalyses', 'getNumBodies', 'getNumConstraints', 'getNumContactGeometries', 'getNumControls', 'getNumCoordinates', 'getNumInputs', 'getNumJoints', 'getNumMarkers', 'getNumMuscleStates', 'getNumOutputs', 'getNumProbeStates', 'getNumProbes', 'getNumProperties', 'getNumSockets', 'getNumSpeeds', 'getNumStateVariables', 'getObjectByTypeAndName', 'getOutput', 'getOutputNames', 'getOwner', 'getProbeSet', 'getPropertyByIndex', 'getPropertyByName', 'getPublications', 'getReferences', 'getRegisteredTypenames', 'getRelativePath', 'getRelativePathString', 'getRoot', 'getSerializeAllDefaults', 'getSimbodyEngine', 'getSocket', 'getSocketNames', 'getStateVariableDerivativeValue', 'getStateVariableNames', 'getStateVariableValue', 'getStateVariableValues', 'getSystem', 'getTotalMass', 'getUseVisualizer', 'getValidationLog', 'getVisualizer', 'getWarningMesssageForMotionTypeInconsistency', 'getWorkingState', 'get_BodySet', 'get_ComponentSet', 'get_ConstraintSet', 'get_ContactGeometrySet', 'get_ControllerSet', 'get_ForceSet', 'get_JointSet', 'get_MarkerSet', 'get_ModelVisualPreferences', 'get_ProbeSet', 'get_assembly_accuracy', 'get_credits', 'get_force_units', 'get_gravity', 'get_ground', 'get_length_units', 'get_publications', 'hasComponent', 'hasModel', 'hasOwner', 'hasProperty', 'hasSystem', 'hasVisualizer', 'initStateFromProperties', 'initStateWithoutRecreatingSystem', 'initSystem', 'initializeState', 'invalidateSystem', 'isA', 'isCacheVariableValid', 'isComponentInOwnershipTree', 'isControlled', 'isEqualTo', 'isKindOf', 'isObjectUpToDateWithProperties', 'isValidSystem', 'makeObjectFromFile', 'markCacheVariableInvalid', 'markCacheVariableValid', 'markControlsAsValid', 'newInstanceOfType', 'overrideAllActuators', 'postScale', 'preScale', 'printBasicInfo', 'printComponentsMatching', 'printControlStorage', 'printDetailedInfo', 'printInputInfo', 'printOutputInfo', 'printSocketInfo', 'printSubcomponentInfo', 'printToXML', 'readObjectFromXMLNodeOrFile', 'realizeAcceleration', 'realizeDynamics', 'realizePosition', 'realizeReport', 'realizeTime', 'realizeVelocity', 'registerType', 'removeAnalysis', 'removeController', 'removeProbe', 'renameType', 'safeDownCast', 'scale', 'setAllControllersEnabled', 'setAllPropertiesUseDefault', 'setAuthors', 'setControls', 'setDebugLevel', 'setDefaultControls', 'setDescription', 'setDiscreteVariableValue', 'setGravity', 'setInlined', 'setInputFileName', 'setModelingOption', 'setName', 'setPropertiesFromState', 'setPublications', 'setReferences', 'setSerializeAllDefaults', 'setStateVariableValue', 'setStateVariableValues', 'setUseVisualizer', 'set_BodySet', 'set_ComponentSet', 'set_ConstraintSet', 'set_ContactGeometrySet', 'set_ControllerSet', 'set_ForceSet', 'set_JointSet', 'set_MarkerSet', 'set_ModelVisualPreferences', 'set_ProbeSet', 'set_assembly_accuracy', 'set_credits', 'set_force_units', 'set_gravity', 'set_ground', 'set_length_units', 'set_publications', 'setup', 'storeControls', 'this', 'thisown', 'toString', 'updActuators', 'updAnalysisSet', 'updBodySet', 'updComponent', 'updConstraintSet', 'updContactGeometrySet', 'updControllerSet', 'updControls', 'updCoordinateSet', 'updDefaultControls', 'updDefaultSubsystem', 'updDisplayHints', 'updForceSet', 'updForceSubsystem', 'updGravityForce', 'updGround', 'updInput', 'updJointSet', 'updMarkerSet', 'updMatterSubsystem', 'updMiscModelComponentSet', 'updModel', 'updMultibodySystem', 'updMuscles', 'updOutput', 'updProbeSet', 'updPropertyByIndex', 'updPropertyByName', 'updSimbodyEngine', 'updSocket', 'updVisualizer', 'updWorkingState', 'upd_BodySet', 'upd_ComponentSet', 'upd_ConstraintSet', 'upd_ContactGeometrySet', 'upd_ControllerSet', 'upd_ForceSet', 'upd_JointSet', 'upd_MarkerSet', 'upd_ModelVisualPreferences', 'upd_ProbeSet', 'upd_assembly_accuracy', 'upd_credits', 'upd_force_units', 'upd_gravity', 'upd_ground', 'upd_length_units', 'upd_publications', 'updateAssemblyConditions', 'updateFromXMLNode', 'updateMarkerSet', 'updateXMLNode', 'writeMarkerFile']

Which does not have those 2 methods. I tried playing with the test to see if I could change it just enough to get working, but no bueno.

**Comment by frederico-klein** [comment]
I found out I was using someone else's fork, not this one. 

Latest commit 48ba9a0792c30b66bb2b97081f2546d1f627c2bc compiles if I disable tropter (I had some compiler issue with ipopt and fortran, I have no plans to use this optimizer, so I didn't bother fixing it) and java (I read you use automated builds for testing I am interested in knowing how you can actually compile something with java 7 nowadays without relying on non-free binaries from Oracle)
