### ISSUE TITLE
Force hasGeometryPath method usage

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2587]
API for Force has a method to check if the Force has a GeometryPath property however it provides no generic way to access this GeometryPath if it actually exists. For GUI usage to associate the Force with the visualization of the GeometryPath we end up using getPropertyByName() which is not very robust.

**Comment by aymanhab** [comment]
The fact that the method hasGeometryPath is virtual makes it possible to misuse by clients to return true without having a GeometryPath property. Could be better to declare the method "final".

**Comment by aseth1** [comment]
IMHO 'hasGeomtryPath()' should not be part of the API. Any Component can contain any other Component type including GeometryPath. Also there should be no requirement for Force to know what a GeometryPath is. The fact that we have to add this method to Force reflects a higher level issue. Perhaps we should revisit our visualizing logic.
