### ISSUE TITLE
SimTK::Array_<OpenSim::CoordinateReference> not wrapped for Matlab

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2589]
According to the [wiki](https://simtk-confluence.stanford.edu/pages/viewpage.action?pageId=34242607), `SimTK::Array_<OpenSim::CoordinateReference>` should be wrapped as `ArrayCoordinateReference` for Matlab. This doesn't seem to be the case, currently.

**Comment by jimmyDunne** [comment]
Seems to be available as `SimTKArrayCoordinateReference'. Is that intentional (and I should change the wiki documentation) or is the template name incorrect?

**Comment by aymanhab** [comment]
Since no namespace qualifier is specified, and since OpenSim::Array and simtk Array have different interfaces, I'd lean to change documentation rather than the code.
