### ISSUE TITLE
Risks exposed by OpenSim/Wrapping/SWIGSimTK

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#259]
Wrapping is maintaining copies of SimTK header files. PR #258 ran into this problem when an old unused method on Simbody was removed and the only reference to it was in a stale header (Sotation.h) file in OpenSim/Wrapping/SWIGSimTK.

**Comment by chrisdembia** [comment]
This issue has not been resolved. We still have a SWIGSimTK folder.

**Comment by chrisdembia** [comment]
Sorry; I see we have #592 to track that.
