### ISSUE TITLE
Opensim & Simbody online api reference docs are down

### ISSUE THREAD

**Issue by marnunez** [opensim-org/opensim-core#2593]
Just to let you all know. Guess I'll be dusting off some docs from previous builds.

**Comment by jenhicks** [comment]
Thanks for the heads up ... we will look into what is causing the issue.

**Comment by jenhicks** [comment]
The doxygen is up again. Can you confirm you are able to access as well?

**Comment by marnunez** [comment]
Confirmed, thanks!

**Comment by jenhicks** [comment]
Thanks again for reporting ... closing the issue.
