### ISSUE TITLE
Fix docopt issues for VS2019.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2601]
First noticed in #2596

**Comment by aymanhab** [comment]
Important since this VS2019 is the default from Microsoft now

**Comment by chrisdembia** [comment]
I don't have a Windows machine that's easy to use, so I would prefer if someone else could look into this.

**Comment by aymanhab** [comment]
@chrisdembia Can this safely be moved to done based on PR #2618 ?

**Comment by chrisdembia** [comment]
Yes!
