### ISSUE TITLE
Need Help with C3DFileAdapter - c3dExport.m Matlab

### ISSUE THREAD

**Issue by Justinemmerich** [opensim-org/opensim-core#2602]
Hey Guys,

I know this is not the right place to ask for help, but I did not found anyone else having the same problem. I am trying to convert a c3d-file with the provided c3dExport.m into trc or other kinematic file. The c3dExport.m file has to be placed in Bindings/Java/Matlab/Utilities to access osimC3D.m. 
Inside the osimC3D.m, C3DFileAdapter is used but could not be found.

**mathlab output:** 
> Unrecognized function or variable 'C3DFileAdapter'.
> Error in osimC3D (line 66)
> 			c3dAdapter =  C3DFileAdapter();
> Error in c3dExport (line 35)
> c3d = osimC3D(c3dpath,1);

Where does the C3DFileAdapter come from? Do I have to install it seperatly?

Would be great if you guys could help. Thanks!

**Comment by tkuchida** [comment]
Please see the documentation for the C3DFileAdapter class here: https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1C3DFileAdapter.html. There is an example of how to use it in Matlab under the heading "MATLAB example".

**Comment by Justinemmerich** [comment]
Hey Thanks for your quick response. 
I managed it now to do not get `Unrecognized function or variable 'C3DFileAdapter'.` Error by using the `configureOpenSim.m.` Silly me! 

Now I recognized that C3DFileAdapter() methods wants to export kinematics and forces. Kinematic in trc and forces in mot file. Is it possible to export trc file only, because the method tries to access the forces provided in the c3d, but there aren't any ?

**Comment by jimmyDunne** [comment]
> Is it possible to export trc file only, because the method tries to access the forces provided in the c3d, but there aren't any ?

This is a [known issue](https://github.com/opensim-org/opensim-core/issues/2421) and [has been  fixed](https://github.com/opensim-org/opensim-core/pull/2495). It will ship with the upcoming release or you could build locally using the current Master Branch.

**Comment by aymanhab** [comment]
Build is available here if you want to try it out
https://ci.appveyor.com/project/opensim-org/opensim-gui/builds/28187530/artifacts

Thank you

**Comment by marnunez** [comment]
> Build is available here if you want to try it out
> https://ci.appveyor.com/project/opensim-org/opensim-gui/builds/28187530/artifacts
> 
> Thank you

Good God, are those kept? Really, really nice. Newbie request here, but could artifacts be kept in every current build, so as to have https://ci.appveyor.com/project/opensim-org/opensim-gui/build/artifacts as a permanent link to the latest successful opensim-gui build?

**Comment by aymanhab** [comment]
Good idea @marnunez 👍  At the moment every build has a unique ID/URL but it could be possible to copy/upload it to a fixed place at the end of the build script. Will look into it when I have a chance.
