### ISSUE TITLE
Python example tests are failing because of the cma dependency

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2605]
I'm looking into this.

For future information, Python examples are tested, so we should not use `[ci skip]` (https://github.com/opensim-org/opensim-core/pull/2604).

This is in contrast to Matlab examples, which are not tested. Not until they make Matlab free 🤞 .

**Comment by chrisdembia** [comment]
I hope to submit a fix today.

**Comment by tkuchida** [comment]
> Python examples are tested, so we should not use `[ci skip]`

Sorry, I didn't remember examples are tested. We could just ignore the optimization example (albeit at the risk of decay).

**Comment by chrisdembia** [comment]
No problem. I’ll try that but it’s turning out to be not as straightforward as I hoped.

**Comment by tkuchida** [comment]
Perhaps:
```
import sys
try:
    import cma
except ImportError:
    print('cma package unavailable; exiting')
    sys.exit()
```

**Comment by chrisdembia** [comment]
That's a good strategy in general, but then if someone does have cma, the test will run. And a 3-minute test is a bit long.
