### ISSUE TITLE
Refactor OpenSense Utilities to reduce repeated code and aid troubleshooting

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2612]
Goals are to:
- [ ] Create unified code to compute and apply a heading correction
- [ ] Ensure for the heading correction that users can specify both a positive and negative axis for the heading direction
- [ ] For the heading correction, ensure that rotation occurs in the correct direction ... or alternately compute the necessary rotation (old code just computes an angle between two vectors)
- [ ] Remove heading correction from the IK step (assuming any desired rotations have been performed prior to running the tool)
- [ ] Add ability for users to specify heading direction and imu to opensim transform via xml

We would also like to maintain the ability for users to perform their own calibration algorithms and still run IK. I believe this is still the case after the refactoring, but just want to make sure.

**Comment by jenhicks** [comment]
@aymanhab Does this issue accurately reflect what you are working on or plan to work on for the refactor?

**Comment by aymanhab** [comment]
@jenhicks yes this is accurate. I'd add that we want to add the ability to specify heading direction and imu to opensim transform entirely in XML. Pre-refactoring there was no XML interface to calibration and the one for IKStudy was deficient.

**Comment by jenhicks** [comment]
Thanks ... I updated the list.

**Comment by aymanhab** [comment]
@jimmyDunne any updates on the testing so far before I make my next round of changes? Thank you
