### ISSUE TITLE
Cannot access method 'convertMillimeters2Meters()'

### ISSUE THREAD

**Issue by vbotics** [opensim-org/opensim-core#2641]
Hi @jimmyDunne 

I was using your example in `Bindings/Java/Matlab/examples/c3dExport.m` to convert a c3d file. 

I came across the following error while executing `c3d.convertMillimeters2Meters();`

Error: Cannot access method 'convertMillimeters2Meters' in class 'osimC3D'.

I dug in further to see that in class osimC3D, this function was called internally while calling `writeMOT()`.  

Thanks for the comments! It was mentioned it comment out the internal function if not required. I just thought of letting you know regarding this. :)

**Comment by jimmyDunne** [comment]
Hi, Vishal- 

Thanks for letting us know that you found an issue!

I am not sure if you are using the current OpenSim master branch or an older version? I updated the class a few months back to expose convertMillimeters2Metes() so it should be available in the latest version. The [current example](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/Matlab/examples/c3dExport.m) shows it being used and I just did a double check (locally) and it seems to be found. 

If you would prefer the latest version of osimC3D.m it will be part of the next beta release (very soon), but if you want to test now you could download the current osimC3D.m from github and replace the version in your Matlab utilities dir. 

I will keep this issue open and when you do get a chance to use OpenSim 4.1 if you could let us know if you see those changes? Any other suggested methods for osimC3D.m would also be great :)

Cheers!

**Comment by vbotics** [comment]
Oh yes, my bad. I was using the old osimC3D file. But I am glad because it was being handled internally. :) I'll download the new utility file and use it 👍 

I just had a question regarding `c3d.rotateData()`. Does it handle the rotation of Marker and Force data together? Does it rotate the force data separately? 

Thanks,
Vishal

**Comment by jimmyDunne** [comment]
Sounds good :)

> I just had a question regarding c3d.rotateData(). 

It does both forces and markers together. To me, that made more sense since you would always want to apply the same rotation to both. Is there perhaps a use case when you would want to do them separately?

Thanks for asking the question-- I just had a quick look at the code and realized that this may throw an exception now-- in 4.0, the C3DFileAdapter() couldn't read C3Ds that contained only one of either forces or markers.  We 'fixed' that, but I think now that would propagate an issue to the rotation call here since it seems that I expect both forces and markers during the rotateData() call.

**Comment by vbotics** [comment]
I was concerned if we had to rotate the markers and force plate axes separately because it looks like in the Mokka screenshot below: 
![image](https://user-images.githubusercontent.com/10283521/70909873-b534f880-200e-11ea-9732-a358bba79dbb.png)
But after rotating the lab coordinates to match with OpenSim coordinates both markers and force plate looks just as expected. So that's good even if individual operations are not required.

Since you were also asking further additions to osimC3D, it would be great if you could add a feature to write only selected markers in .trc file. Right now, I think it writes all the markers into the file. It is quite heavy if you have a lot of virtual markers in your c3d file. So maybe, by default, it could perform as it is being done now, and if we input a list of `wanted_markers` it could write them in the .trc file.

**Comment by jimmyDunne** [comment]
Do you think `wanted_markers` could be the OpenSim model of interest, since it has the model (should) contain a list of model markers you care about?

**Comment by vbotics** [comment]
Yes, I totally agree with that. It's just because the .trc file could become very heavy. In my case, Vicon created a lot of virtual markers. there were a total of 117 markers in the c3d file, and out of which 39 were used in the model and rest 78 markers were not of any use. 

Thanks a lot, James! It was very helpful :)
