### ISSUE TITLE
osimC3D may throw an exception during rotateData()

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2642]
The rotateData() method assumes there are both valid force and marker tables to be rotated. This was always true in 4.0, but an improvement in C3DFileAdapter() made it feasible to have empty tables if no data were collected. 

I will test with a force-less C3D and post a fix.

**Comment by aymanhab** [comment]
James, I fixed that already in 4.1 and empty tables ate returned if no
data. Please double check just in case.

**Comment by jimmyDunne** [comment]
That is totally true, Ayman. The issue may be in osimC3D.m. During the call to do rotations, I assume that there are valid force AND marker tables. We tested that the fixes you made return empty tables (they do), but I didn't test osimC3D to see how it deals with empty tables (the tests use a c3d with both markers and forces).
