### ISSUE TITLE
Clean up comments for IMU Placer settings

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2644]

**Comment by aymanhab** [comment]
@jenhicks Can you tell describe which specific comment needs cleaning/how? Thanks

**Comment by aymanhab** [comment]
![CaptureIMUPlacer](https://user-images.githubusercontent.com/3972208/71029136-9fcdd600-20c3-11ea-9e46-ac5c618d5c1a.PNG)
Doe sthis look fine (from latest master build)?

**Comment by jenhicks** [comment]
>  
There is a space missing before the last sentence.

>  
The last part should be: "IMU Space to OpenSim. Default (0, 0, 0)." So a period and space are missing.
