### ISSUE TITLE
osimC3D can't open files without forces

### ISSUE THREAD

**Issue by sebastianskejoe** [opensim-org/opensim-core#2666]
It appears that osimC3D is unable to read a C3D-file if the file doesn't contain force measurements. I've tested with the Vicon Motion Systems/TableTennis.c3d file from [Sample00](https://www.c3d.org/sampledata.html) which fails with the following error:
```
>> osimC3D('<path>\TableTennis.c3d', 0)
Error using osimC3D (line 65)
Java exception occurred:
java.lang.RuntimeException: invalid map<K, T> key

	at org.opensim.modeling.opensimCommonJNI.C3DFileAdapter_read__SWIG_2(Native Method)

	at org.opensim.modeling.C3DFileAdapter.read(C3DFileAdapter.java:82)
```

**Comment by jimmyDunne** [comment]
Are you using the current Master Branch of OpenSim or the 4.0 application? This was updated in #2495

**Comment by sebastianskejoe** [comment]
This was 4.0 - apologizes for not checking the issue tracker properly. Closing this issue.
