### ISSUE TITLE
Investigate integration of RTOsim into OpenSim

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2668]
The project https://github.com/RealTimeBiomechanics/rtosim holds some potential for handling live data and large data sets.

**Comment by aymanhab** [comment]
The steps needed will likely include:

- Compiling the code with OpenSim 3.3
- Make a branch to migrate to 4.1 code base
- Limit the scope if needed
- Run IK in parallel on marker data or long trials
- Run IK with IMUs on long trials

**Comment by jenhicks** [comment]
@aymanhab Is this something you still plan to investigate further or can we close?

**Comment by aymanhab** [comment]
We can move this to back burner, when we implement pipelines this may become relevant but not for now.
