### ISSUE TITLE
Update C3D-related Python, Matlab, and C++ examples

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2673]
As reported on [the Forum](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11502). [This example in the doxygen](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1C3DFileAdapter.html#ac2eb67cb6bac08281775988cd46fa604) doesn't seem to work, and [the examples in the User's Guide](https://simtk-confluence.stanford.edu:8443/display/OpenSim/C3D+%28.c3d%29+Files#C3D(.c3d)Files-ReadingC3DfilesthroughPythonandC++) need to be updated to reflect the recent changes to the API.

**Comment by jenhicks** [comment]
@aymanhab Is working on incorporating the examples into the build environment, so we don't need to maintain separately. When code is merged, we can update links in confluence to the correct branch/version of the code.

**Comment by jenhicks** [comment]
What if any documentation (confluence, doxygen) changes are still needed to mark this as done? @aymanhab

**Comment by aymanhab** [comment]
Confluence has some links to github code, the code changed from 4.0 to 4.1, now we include links to both by pointing to specific branches. Do we want to maintain that or stick with 4.1? if the former then we're done, if the latter, just remove the reference to 4.0 code/API

**Comment by jenhicks** [comment]
The current live confluence is for both 4.0 and 4.1. So let's leave as is and call this issue "Done".
