### ISSUE TITLE
TRCFileAdapter is very slow reading large files

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2674]
This was traced to using appendRow on every line of the data file. A similar fix was done for other readers and need to be ported to TRCFileAdapter

**Comment by aymanhab** [comment]
Working on a fix to help @malborno and Johanna

**Comment by jenhicks** [comment]
@aymanhab Is this issue Done?

**Comment by aymanhab** [comment]
Yes, and can be closed.
