### ISSUE TITLE
Muscle Wrapping With Multithreading

### ISSUE THREAD

**Issue by vinaym815** [opensim-org/opensim-core#2677]
I have modified the GitHub page example to include a wrapping cylinder. The muscle wrapping works correctly when the code is single-threaded but jumps around randomly when multithreading.

Example Code: https://github.com/vinaym815/OpenSimExample/blob/master/GitHubExample/src/main2.cpp

![Bug](https://user-images.githubusercontent.com/35987596/74709333-410f0f00-5262-11ea-9e19-38e334d089af.png)

**Comment by aymanhab** [comment]
@carmichaelong and @chrisdembia any thoughts on whether this is supposed to work? Thank you

**Comment by chrisdembia** [comment]
This should not work; the muscle wrapping code is not thread-safe. I don't know the exact details, but we ran into this issue back when adding parallelism to forces.

**Comment by vinaym815** [comment]
The bug is with opensim-core/OpenSim/Common/Mtx.cpp 
The shared variables in the class Mtx are responsible for the trouble. An easy fix would be allocated these variables on the stack within different functions. The functions that would require modifications are: Transpose, Multiply, and Invert.
Also, the Rotate(const double aAxis[3],......) have not been implemented

**Comment by aymanhab** [comment]
This should be fixed by the latest @adamkewley commit. The Mtx class has been removed and other incorrect references to model components from path wrapping code have been removed. Please verify and close as needed.

**Comment by vinaym815** [comment]
Thank you.
