### ISSUE TITLE
Scaling a model loses custom geometry/meshes 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2681]
Reported on forum and by many local users in the past
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11542&p=32299&start=0&view=

**Comment by aymanhab** [comment]
One easy fix that works is to create the model, give it a file/path at the same folder as the starting model. The downside is that if the user saves the model in a different folder the problem will re-occur.  but that's the same as any model with custom geometry

**Comment by aymanhab** [comment]
@jenhicks @tkuchida @carmichaelong @chrisdembia what are your thoughts? Do you typically save the model manually? Specify a destination model file name in the setup file?

**Comment by aymanhab** [comment]
Anybody else using Scaling workflow that would be interested in this discussion?

**Comment by aymanhab** [comment]
This came up a couple more times during the Match 20 workshop, so higher priority. Thoughts @jenhicks

**Comment by jenhicks** [comment]
I will put it in the sprint backlog for now so we can discuss how to prioritize.

**Comment by aymanhab** [comment]
Issue moved to [opensim-org/opensim-gui #1182](https://github.com/opensim-org/opensim-gui/issues/1182) via [**ZenHub**](https://www.zenhub.com/)
