### ISSUE TITLE
Matlab fails to create an OpenSim model from .osim file. Throws Java exception java.io.IOException

### ISSUE THREAD

**Issue by Student297241** [opensim-org/opensim-core#2688]
Good Afternoon,

I was trying to run the simpleOptimizerExample.m and example2DWalking.m (found in /opensim-moco-install-dir/Resources/Code/MatlabExamples).  Both scripts  gave me the following error:

Java exception occurred:
java.io.IOException: Object: Cannot open file "specific .osim filename here". It may not exist or youdo not have permission to read it.
	Thrown at Object.cpp:105 in Object().
	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_1(Native Method)
	at org.opensim.modeling.Model.<init>(Model.java:783) 

Can you advise me how I may get past this error?  I have successfully run the file configureOpenSim() 

I am working on a MacBook (2.6 GHz, 6 Core Intel Core i7, macOS Catalina version 10.15.3).  I am using OpenSim 4.1 and Matlab R2019b.

When I got the error, I ran this initial series of tests:

1). build_and_simulate_simples_arm.m

/OpenSim/4.1/Code/Matlab/Examples
This worked without error

2). OpenSimCreateTugOfWarModel.m
/OpenSim/4.1/Code/Matlab/Examples
This worked without error.  Successfully wrote the .osim file and I was able to open the .osim file in OpenSim and successfully run it.

3). pendulum_marker_positions.m
/OpenSim/4.1/Code/Matlab/Examples
This program ran successful. 
I was also able to add code to write the model to an .osim file. I was able to get the file to open successfully in OpenSim

The common factors with this failure are:
1). I had instantiated an open sim model using the model() class
2). I had identified a path to an .osim file
3). I tried to load the .osim file into the model() class with the command
		model1 = Model(‘file.osim’)

I am not sure how to go forward.  Googling the error did not help me solve it. 

Thank you for any help you can give me.

**Comment by aymanhab** [comment]
@chrisdembia Are there instructions somewhere about how to use these scripts? Obviously " "specific .osim filename here" needs to be replaced with an actual file name but I'm not sure if that is described elsewhere. Also, since 4.1 doesn't include Moco, I'm not sure if this is supposed t work.

**Comment by chrisdembia** [comment]
simpleOptimizerExample.m is part of opensim-core, but the Moco example should not be expected to run with OpenSim on its own.

I think @Student297241 edited the error message.

My guess is that @Student297241 must change the current directory appropriately before running the examples.

**Comment by Student297241** [comment]
Hi,

The scripts I am trying to run were provided with the Open Sim package - I downloaded them when I down loaded the package and installed it on my computer

Here are the specific scripts











I was trying to get familiar with the opensim matlab interface before trying to use Moco

**Comment by chrisdembia** [comment]
Please redirect your questions to the OpenSim or Moco forums. GitHub should be used for proven bugs or requested features, not for troubleshooting.

**Comment by aymanhab** [comment]
Thanks for the clearup, closing since no issue was actually reported here. Please post to user forum @Student297241 Thank you
