### ISSUE TITLE
Induced Accelerations can not be run when external loads are present

### ISSUE THREAD

**Issue by tnamayeshi** [opensim-org/opensim-core#2689]
When running "Induced Accelerations" analysis with "External Loads", OpenSim returns:

> External force expressedInBody ground not found.
> 
> Exception:
>   ArrayPtrs.get: Array index out of bounds.

As I investigated in the source code, this happens because OpenSim search for force body "appliedTo" and "expressedIn" in model body set and if the force applied to or expressed in "ground" it will fail to find it!

Error source is in "**applyContactConstraintAccordingToExternalForces**" function in "**InducedAccelerations.cpp**" file!

**Comment by aseth1** [comment]
@tnamayeshi thank you for reporting this issue. Can you please indicate what case you are trying run and what you are trying to achieve? The logic of InducedAccelerations is intended to replace the applied external (ground reaction) force at the point of application with a constraint. If the applied point is in Ground then the external force has has no affect on the model and should be ignored. I am not sure that is the case, but perhaps you could supply your use case so we can check. Thank you.
