### ISSUE TITLE
XSens exported quaternions differ from OpenSense converted ones

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2696]
Reported in March 20 workshop

**Comment by aymanhab** [comment]
This boils down to the method SimTK::Rotation.convertRotationToQuaternion() returning a Quaternion different from Xsens:
e.g. Matrix: {0.075197	-0.079913	0.993961	-0.573480	-0.818912	-0.022453	0.815761	-0.568328	-0.107408}
converts to q{0.19292,0.70737,-0.23092,0.63959} by the above method, while XSens conversion returns q{-0.192923	-0.707375	0.230922	-0.639591}
Since cos(a/2) is -ve in XSens result, this violates that rotations are in -180,180 range, any conjecture on what could be happening or how to fix @sherm1 ?

**Comment by aymanhab** [comment]
Thanks @sherm1, will dig deeper into how these quaternions are used downstream by our orientation tracking.

**Comment by jenhicks** [comment]
@aymanhab What is the status on this issue?

**Comment by jenhicks** [comment]
We were not able to track down the source of this issue. Could look at the data with new visualization tools, as time permits.

**Comment by PhilipKone** [comment]
what is the generic representation of quaternions in opensim
