### ISSUE TITLE
Distributed Matlab script crashes Matlab

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2697]
Reported as bug on simtk.org, the script in question is KneeReflex_answers.m and it crashes in initSystem call

**Comment by aymanhab** [comment]
@carmichaelong can you try to reproduce? @chrisdembia are you familiar with this example/issue?

**Comment by carmichaelong** [comment]
Just tried it with the 4.1 release and didn't run into any issues. On Windows 10 Pro, Matlab 2019a

**Comment by chrisdembia** [comment]
I'm not familiar.

**Comment by nickbianco** [comment]
This script was written for the Dynamic Walking workshop in 2018.

**Comment by aymanhab** [comment]
Thanks @carmichaelong, it crashed for me using stock 4.1, but didn't when I used my own build (ReleaseWithDebugInfo). Likely a bug that's hard to reproduce. Hopefully more granular logging can capture it.

**Comment by aymanhab** [comment]
Thanks @chrisdembia @nickbianco will leave open until we get to the bottom of it.

**Comment by chrisdembia** [comment]
Is this the same Visualizer crash we saw with BIOE485?

**Comment by zjulitong** [comment]
It seems to be an issue with the path of the script file (.m file, the "Current Folder" in Matlab), not the model file.

**Comment by jenhicks** [comment]
Please reopen if this issue is still occurring.
