### ISSUE TITLE
Documentation for Model.calcMassCenterPosition() not available 

### ISSUE THREAD

**Issue by stingjp** [opensim-org/opensim-core#2701]
The model method to calculate center of mass does not show documentation. It isn't clear what frame the center of mass is calculated in when looking at the API documentation.

**Comment by aymanhab** [comment]
Thanks @stingjp 

@chrisdembia The doxygen page https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Model.html doesn't claerify the frame while the cpp file has the info, is there a better way to document Outputs?

**Comment by chrisdembia** [comment]
We decided to not add documentation for Outputs because it would be redundant with the documentation for the function used by the Output. We should definitely add Doxygen documentation for `calcMassCenterPosition()`, etc.

**Comment by krish-narotam** [comment]
Hi, since then, it seems like the frame has not been added to the documentation. 

Or maybe have I looked in the wrong place. 
Thanks.

**Comment by nickbianco** [comment]
@krish-narotam this has been fixed in OpenSim 4.5: https://simtk.org/api_docs/opensim/api_docs45/classOpenSim_1_1Model.html#a937ccd739df45c80c48a308a90aaf4cd.
