### ISSUE TITLE
Report IMU tracking errors when running InverseKinematics on IMU data

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2710]

**Comment by jenhicks** [comment]
@aymanhab This was something that came up as useful info to help with the IMU project (with Mazen, Hannah).

**Comment by aymanhab** [comment]
Thanks @jenhicks for the heads up, PR #2733 has a fix.

**Comment by aymanhab** [comment]
@malborno Not sure if you can try PR #2733 to see if reporting is helpful or can be improved. No GUI build yet but can trigger one if needed, also maybe helpful to Hannah.
