### ISSUE TITLE
Move Moco's TableProcessor into opensim-core

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2713]
Moco's TableProcessor provides an XML-serializable pipeline of operations to TimeSeriesTables.

Moco's version does not yet support TimeSeriesTableVec3, but @nickbianco mentioned that perhaps a "flatten-operate-repack" approach might be sufficient.

**Comment by chrisdembia** [comment]
@carmichaelong this issue is a little bigger than #2712 because we want to templatize `TableProcessor`; there is some more information over at https://github.com/opensim-org/opensim-moco/issues/628.

**Comment by nickbianco** [comment]
Closing since the core of this issue is moving TableProcessor to opensim-core. Templatizing TableProcessor remains its own issue in opensim-org/opensim-moco#628.
