### ISSUE TITLE
Move Moco's ModelFactory into opensim-core

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2715]
Moco has a ModelFactory class for creating models such as N-link pendulums, and for modifying models by removing muscles, adding reserves, etc.

**Comment by chrisdembia** [comment]
@carmichaelong fyi the ModelProcessor/ModelOperators depend on the ModelFactory, so it may make sense to move the ModelFactory in the same PR.

**Comment by aymanhab** [comment]
@nickbianco There are a few issues with Moco label that may have been merged into master with the moco-feature branch merge, can you add comment as to what's left there if any? Thanks

**Comment by nickbianco** [comment]
Closing via #2895.
