### ISSUE TITLE
Move Moco's visualize() free function to opensim-core

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2717]
Moco has a very handy visualize() free function for animating a trajectory using the Simbody Visualizer.

Related: https://github.com/opensim-org/opensim-core/pull/2590

**Comment by aymanhab** [comment]
@chrisdembia I'm thinking of promoting this function to a utility program (that can be invoked thru opensim-cmd) that includes visualization of marker data and IMU data. Thoughts?

**Comment by chrisdembia** [comment]
That would be fantastic!

**Comment by jenhicks** [comment]
From @chrisdembia and @nickbianco : could call it "playback()" or "animate()".
