### ISSUE TITLE
Integrator step fails due to underflow (Required condition 't1>t0' was not met.

### ISSUE THREAD

**Issue by cversteeg** [opensim-org/opensim-core#2721]
I am trying to do some reinforcement learning to move an arm around with opensim-rl, but am encountering issues with two different models that I am trying.  From searching previous posts, I have found previous issues related to this where the culprit was an underflow on the integration step. The solutions advised previously have been tighter integration accuracies, but those haven't worked reliably to solve the issue.
Code Traceback

None
Training for 10000 steps ...

target: [-0.14297850108856178 -0.3447546757289524]
Interval 1 (0 steps performed)
Traceback (most recent call last):

  File "C:\Users\wrest_000\Documents\Github\opensim-rl\examples\train_arm3d.py", line 98, in <module>
    agent.fit(env, nb_steps=nallsteps, visualize=False, verbose=1, nb_max_episode_steps=100, log_interval=10000)

  File "C:\Users\wrest_000\AppData\Roaming\Python\Python36\site-packages\rl\core.py", line 177, in fit
    observation, r, done, info = env.step(action)

  File "C:\Users\wrest_000\anaconda3\envs\kerasEnv\lib\site-packages\osim\env\armMonk.py", line 124, in step
    obs, reward, done, info = super(Arm3DVecMonkEnv, self).step(action, obs_as_dict=obs_as_dict)

  File "C:\Users\wrest_000\anaconda3\envs\kerasEnv\lib\site-packages\osim\env\osim.py", line 347, in step
    self.osim_model.integrate()

  File "C:\Users\wrest_000\anaconda3\envs\kerasEnv\lib\site-packages\osim\env\osim.py", line 257, in integrate
    self.state = self.manager.integrate(self.stepsize * self.istep)

  File "C:\Users\wrest_000\anaconda3\envs\kerasEnv\lib\site-packages\opensim\simulation.py", line 38007, in integrate
    return _simulation.Manager_integrate(self, finalTime)

RuntimeError: std::exception in 'SimTK::State const & OpenSim::Manager::integrate(double)': SimTK Exception thrown at abstractintegratorrep.cpp:428:
  Integrator step failed at time 0 apparently because:
SimTK Exception thrown at abstractintegratorrep.cpp:547:
  Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 0.
  (Required condition 't1 > t0' was not met.)

The first model that I am trying is the MoBL simple arm model. This model runs fine for a few iterations, but invariably encounters this error. The second model is the Chan & Moran monkey arm model, which is unable to complete even a single time step before it throws this error. The simple opensim-rl model of the arm constrained to the sagittal plane does not encounter this error with my code.

I was wondering if there were any tips on how to keep the integration timestep larger? Are there any settings in the models which may be causing these issues?

Thanks!

**Comment by cversteeg** [comment]
Also, visualizing the model during the training process shows that it often fails at similar postures. Could there be something with the geometry that makes it especially stiff?

**Comment by cversteeg** [comment]
More info: Shrinking the muscle activations by a scalar seems to have made the problem less severe. I am able to get it to run consistently now. Perhaps excessive co-contraction in the model increased the stiffness about the joints to a point where it becomes unstable?

**Comment by chrisdembia** [comment]
By default, OpenSim uses Simbody's adaptive-step integrators. When the derivatives reported by the ordinary differential equations are large, the time step becomes very small. 

Simbody does provide fixed-step integrators, and you can also specify a minimum step size.

This seems to be an issue with a stiff model; your question might be more appropriate for the OpenSim forum. There, you can show the pose of your model and we or others can help pinpoint what's causing the differential equations to become stiff.

Related: https://github.com/simbody/simbody/issues/639

If you think we should re-open this issue, please let me know.

**Comment by cversteeg** [comment]
Thanks for the response! I have gotten the model to work for thousands of epochs, but it still invariably hits this issue. I tried to set a minimum step size for the integrator, but it seems like it is  encapsulated inside the Manager class in python. The methods for setIntegratorMinimumStepSize() aren't part of the class as they are in the C++ documentation. How do I ago about setting that parameter in python?
Thanks so much for the help!

**Comment by chrisdembia** [comment]
The opensim Python package should provide `Manager.setIntegratorMethod()`, `Manager.setIntegratorMinimumStepSize()`, `Manager.setIntegratorAccuracy()`. I'm not sure if these updates made it into `osim-rl`; do you know, @carmichaelong ?

**Comment by carmichaelong** [comment]
IIRC, the version of OpenSim that `osim-rl` uses didn't have those changes. I'm not sure when it was last updated. There might have been some changes into the specific branch of OpenSim that `osim-rl` uses that exposed only `setIntegratorAccuracy()`.
