### ISSUE TITLE
Visualize mocap and imu data in API

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2723]
There's no utility as of now to allow users to inspect mocap data or IMU data in the API, through Matlab or Python making debugging quite hard or next to impossible.

**Comment by aseth1** [comment]
@aymanhab this would be great to add to 4.2. We've had a previewer for marker data [here](https://github.com/opensim-org/opensim-core/blob/2fc6dc1d23734f3b5f8d58c3b3833871e756c675/OpenSim/Sandbox/futureMarkerPreview.cpp) and that has been integrated in OpenSense with `ExperimentalMarker` and was part of [`IMUInverseKinematicsTool`](https://github.com/opensim-org/opensim-core/blob/1e22b11c22feb6c29546f1b0148f4af331a95a41/OpenSim/Tools/IMUInverseKinematicsTool.cpp#L43-L92).  There is an analog to the Marker for IMU called [ExperimentalFrame ](https://github.com/opensim-org/opensim-core/search?q=ExperimentalFrame&unscoped_q=ExperimentalFrame )but unlike `ExperimentalMarker`s, visualizing them without some sort of way (Model) to position them in space makes it difficult to interpret the coincident rotating frames.

The main idea is that previewing is simply a case of `Component` visualization that provides convenience methods to add `ExperimentalMarker`s (Sensors, etc...) to an empty `Model` and they are visualized as the model is "simulated". Ideally we would have an `Environment`/`World`  top-level `Component`  where we can add Models as well as Experimental Markers, Sensors, External Forces, ...  to be simulated/visualized together. A "Data Previewer" in this case simply creates and adds the corresponding components to the Environment from Experimental Data (as Table columns) and wires them up to the data table.
