### ISSUE TITLE
Document CMake requirements on dependecies

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2724]
When incorporating new libraries into opensim-core, the library is assumed to have some specific layout (platform dependent). That typically includes "cmake" folder and have specific contents in this folder that defines include and lib paths etc. 
If this is documented somewhere that would be great (appreciate a link here for future reference), if not we need to document these requirements so that library integrators don't spend forever in CMake mazes trying to figure out our undocumented preferences.

**Comment by jenhicks** [comment]
@aymanhab Are there specific dependencies for which this is an issue? I'm having trouble understanding what the specific action items are. Thanks!

**Comment by aymanhab** [comment]
The specific action is documentation. There are variety of ways libraries can be included, @chrisdembia did the magic to help Ezc3d conform to a convention that's basically undocumented. That is unsustainable long term.

**Comment by jenhicks** [comment]
So you are asking @chrisdembia to document or provide a link to the documentation for the steps he took to integrate the ezc3d libraries?

**Comment by chrisdembia** [comment]
I can attempt this.

**Comment by jenhicks** [comment]
Thanks. The developing.md doc seems like the right place.

**Comment by aymanhab** [comment]
Thanks @jenhicks and @chrisdembia This came along during the review of a PR and I didn't want to put it on hold pending documentation. developing.md could be a good place indeed.

**Comment by chrisdembia** [comment]
See #2726

**Comment by jenhicks** [comment]
Would be helpful to do this before integrating spdlog ... Ayman can "test" the documentation
