### ISSUE TITLE
Build failure due to numpy headers

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2731]
Mac 10.15.4 (Fresh Machine)
Python 3.7 (Homebrew)
Numpy is installed in /usr/local/lib/python3.7/site-packages/numpy
Numpy arrayobject is found in /usr/local/lib/python3.7/site-packages/numpy/core/include/numpy

I am getting a build failure on a new machine seemingly related to numpy.

``` make
... 
[ 96%] Built target _simulation
[ 96%] Building CXX object Bindings/Python/CMakeFiles/_simbody.dir/python_simbody_wrap.cxx.o
/Users/jimmy/repository/opensim/build_opensim/Bindings/Python/python_simbody_wrap.cxx:3510:10: fatal error: 
      'numpy/arrayobject.h' file not found
#include <numpy/arrayobject.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [Bindings/Python/CMakeFiles/_simbody.dir/python_simbody_wrap.cxx.o] Error 1
make[1]: *** [Bindings/Python/CMakeFiles/_simbody.dir/all] Error 2
make: *** [all] Error 2
...
``` 

![image](https://user-images.githubusercontent.com/5296507/79084495-155c5280-7d02-11ea-9bd3-4e152bab4011.png)

**Comment by jimmyDunne** [comment]
@chrisdembia any suggestions on approaches I could use to fix?

**Comment by chrisdembia** [comment]
Just saw this issue; sorry about that. 

Try setting `PYTHON_NUMPY_INCLUDE_DIR` to `/usr/local/lib/python3.7/site-packages/numpy/core/include` (remove `/numpy` from the end).

**Comment by jimmyDunne** [comment]
Thanks, Chris. That solved it. Looking forward to using the new features :)
