### ISSUE TITLE
Move ScapulothoracicJoint into opensim-core

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2735]
https://github.com/opensim-org/ScapulothoracicJointPlugin

**Comment by joaobelo92** [comment]
I would really appreciate this feature. I don't have experience with C++, but if anyone wants to guide me I would spend time implementing this. 
I am a CS PhD student with experience in other programming languages.

**Comment by chrisdembia** [comment]
@aseth1 said he needs to make a few changes to the plugin before it's ready to include.

Have you been able to use the joint as a plugin?

If @aseth1 is interested in you leading the integration, I could provide any guidance.

Also, you can create a fork of opensim-core and try including the joint in your own build.

**Comment by joaobelo92** [comment]
Hi @chrisdembia. 
Although I am able to load the plugin successfullyon Windows, I get an error when trying to load it on mac:
```
dlerror: dlopen(/Users/joaobelo/ThoracoscapularShoulderPaperMaterials/ScapulothoracicJointPlugin40/MacOSX/libScapulothoracicJointPlugin40.dylib, 9): Symbol not found: __ZN7OpenSim14ModelComponent13extendConnectERNS_9ComponentE
  Referenced from: /Users/joaobelo/ThoracoscapularShoulderPaperMaterials/ScapulothoracicJointPlugin40/MacOSX/libScapulothoracicJointPlugin40.dylib
  Expected in: /Applications/OpenSim 4.1/OpenSim 4.1.app/Contents/Resources/OpenSim/sdk/lib/libosimSimulation.dylib
 in /Users/joaobelo/ThoracoscapularShoulderPaperMaterials/ScapulothoracicJointPlugin40/MacOSX/libScapulothoracicJointPlugin40.dylib
Failed to load library /Users/joaobelo/ThoracoscapularShoulderPaperMaterials/ScapulothoracicJointPlugin40/MacOSX/libScapulothoracicJointPlugin40.dylib
```

I also tried with OpenSim 4.0 and got the same issue.

> Also, you can create a fork of opensim-core and try including the joint in your own build.

Will do!

**Comment by aseth1** [comment]
@joaobelo92 and @chrisdembia I am happy to oversee the move. Please use the opensim_40_compatible branch to begin with. The big addition will be to add a corresponding test to *testJoints*.  Test joints compares Joints defined in OpenSim with mobilizers and/or constraints implemented directly in Simbody.  The Simbody side is basically what the joint does within `extendAddToSystem()`. It should also be automatically tested by *testComponents* once it is registered within *osimSimulation*. Thank you @joaobelo92!

**Comment by aymanhab** [comment]
I believe this has been merged by @adamkewley so we can close (assuming some testing was done post merge)
