### ISSUE TITLE
Doxygen warnings coming from ActivationCoordinateActuator.h

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2757]
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:56: warning: Conditional section with label                                                              does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:53: warning: Conditional section does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:50: warning: Conditional section does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:47: warning: Conditional section with label  developer  does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:56: warning: Conditional section with label                                                              does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:53: warning: Conditional section does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:50: warning: Conditional section does not have a corresponding \endcond command within this file.
1>D:/src/opensim-core/OpenSim/Actuators/ActivationCoordinateActuator.h:47: warning: Conditional section with label  developer  does not have a corresponding \endcond command within this file.
1>**/  /** This typedef might be useful within the member functions of this class. */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  typedef  ActivationCoordinateActuator  Self;  /** Use this typedef to refer to the superclass of this class.              */  /** Avoid using the explicit type name of the superclass; this would        */  /** introduce bugs if the superclass is changed.                            */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  typedef  CoordinateActuator  Super;  /** @endcond **/  public:   /** @name Auto-generated functions */   /** @{ */   /** For use in MATLAB and Python to access the concrete class. */   /** Example: `cObj = %ActivationCoordinateActuator.safeDownCast(obj)`. */   /** This is equivalent to `dynamic_cast<ActivationCoordinateActuator*>(obj)` in C++. */   static  ActivationCoordinateActuator * safeDownCast(OpenSim::Object *obj)   {   return dynamic_cast< ActivationCoordinateActuator  *>(obj);   }   /** @cond developer */   /** This allows copy assignment in the Java GUI. */   /** @throws Exception if the argument is not of type  ActivationCoordinateActuator. */   void assign(Object &aObject) override   {   if (safeDownCast(&aObject)!=0) {   *this = *(( ActivationCoordinateActuator *)(&aObject));   } else {   throw OpenSim::Exception(std::string("ActivationCoordinateActuator")+   "::copy() called with object (name = " + aObject.getName()   + ", type = " + aObject.getConcreteClassName()+").",   __FILE__,__LINE__);   }   }   /** @endcond */   /** @}*/;;  /** @name Auto-generated functions                                          */  /** @{                                                                      */  /** This returns "ActivationCoordinateActuator"                                        */  /** See getConcreteClassName() if you want the class name of the underlying */  /** concrete object instead.                                                */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  static const std::string& getClassName()  { static std::string name("ActivationCoordinateActuator"); return name; }  /** @}*/;  /** @name Auto-generated functions                                          */  /** @{                                                                      */   ActivationCoordinateActuator * clone() const override {return new  ActivationCoordinateActuator (*this);}  const std::string& getConcreteClassName() const override  { return getClassName(); }  /** @}*/  private:;;**/   /** @cond **/   PropertyIndex PropertyIndex_activation_time_constant ;   const Property< double >& getProperty_activation_time_constant () const   { return this->template getProperty< double >(PropertyIndex_activation_time_constant ); }   Property< double >& updProperty_activation_time_constant ()   { return this->template updProperty< double >(PropertyIndex_activation_time_constant ); }   /** @endcond **/   /** @cond **/   void copyProperty_activation_time_constant (const Self& source)   { PropertyIndex_activation_time_constant  = source.PropertyIndex_activation_time_constant ; }   /** @endcond **/   /** Get the value of the i-th element of the <b>  activation_time_constant  </b> property. */   const  double & get_activation_time_constant (int i) const   { return this->template getProperty< double >(PropertyIndex_activation_time_constant )[i]; }   /** Get a writable reference to the i-th element of the <b>  activation_time_constant  </b> property. */    double & upd_activation_time_constant (int i)   { return this->template updProperty< double >(PropertyIndex_activation_time_constant )[i]; }   /** %Set the value of the i-th element of <b>  activation_time_constant  </b> property.    */   void set_activation_time_constant (int i, const  double & value)   { this->updProperty_activation_time_constant ().setValue(i,value); }   /** Append an element to the <b>  activation_time_constant  </b> property.                 */   int append_activation_time_constant (const  double & value)   { return this->updProperty_activation_time_constant ().appendValue(value); }   void constructProperty_activation_time_constant (const  double & initValue) {   PropertyIndex_activation_time_constant  =   this->template addProperty< double >("activation_time_constant", "Larger value means activation changes more slowly (units: seconds; default: 0.01 seconds)." ,initValue);   }   /** @endcond **/   /** @name Properties (single-value)                                  */   /** @{                                                               */   /**  "Larger value means activation changes more slowly (units: seconds; default: 0.01 seconds)."                                                           */   /** This property appears in XML files under                         */   /** the tag <b>\<activation_time_constant\></b>.                                    */   /** This property was generated with                                 */   /** the #OpenSim_DECLARE_PROPERTY macro;                             */   /** see Property to learn about the property system.                 */   /** @see get_activation_time_constant(), upd_activation_time_constant(), set_activation_time_constant()           */   /* This macro below is explained above.                              */    Q_PROPERTY ( double ,  activation_time_constant )   /** @}                                                               */   /** @name Property-related functions                                 */   /** @{                                                               */   /** Get the value of the <b>  activation_time_constant  </b> property.                    */   const  double & get_activation_time_constant () const   { return this->getProperty_activation_time_constant ().getValue(); }   /** Get a writable reference to the <b>  activation_time_constant  </b> property.        */    double & upd_activation_time_constant ()   { return this->updProperty_activation_time_constant ().updValue(); }   /** %Set the value of the <b>  activation_time_constant  </b> property.                   */   void set_activation_time_constant (const  double & value)   { this->updProperty_activation_time_constant ().setValue(value); }   /** @}                                                               */;**/   /** @cond **/   PropertyIndex PropertyIndex_default_activation ;   const Property< double >& getProperty_default_activation () const   { return this->template getProperty< double >(PropertyIndex_default_activation ); }   Property< double >& updProperty_default_activation ()   { return this->template updProperty< double >(PropertyIndex_default_activation ); }   /** @endcond **/   /** @cond **/   void copyProperty_default_activation (const Self& source)   { PropertyIndex_default_activation  = source.PropertyIndex_default_activation ; }   /** @endcond **/   /** Get the value of the i-th element of the <b>  default_activation  </b> property. */   const  double & get_default_activation (int i) const   { return this->template getProperty< double >(PropertyIndex_default_activation )[i]; }   /** Get a writable reference to the i-th element of the <b>  default_activation  </b> property. */    double & upd_default_activation (int i)   { return this->template updProperty< double >(PropertyIndex_default_activation )[i]; }   /** %Set the value of the i-th element of <b>  default_activation  </b> property.    */   void set_default_activation (int i, const  double & value)   { this->updProperty_default_activation ().setValue(i,value); }   /** Append an element to the <b>  default_activation  </b> property.                 */   int append_default_activation (const  double & value)   { return this->updProperty_default_activation ().appendValue(value); }   void constructProperty_default_activation (const  double & initValue) {   PropertyIndex_default_activation  =   this->template addProperty< double >("default_activation", "Value of activation in the default state returned by initSystem() (default: 0.5)." ,initValue);   }   /** @endcond **/   /** @name Properties (single-value)                                  */   /** @{                                                               */   /**  "Value of activation in the default state returned by initSystem() (default: 0.5)."                                                           */   /** This property appears in XML files under                         */   /** the tag <b>\<default_activation\></b>.                                    */   /** This property was generated with                                 */   /** the #OpenSim_DECLARE_PROPERTY macro;                             */   /** see Property to learn about the property system.                 */   /** @see get_default_activation(), upd_default_activation(), set_default_activation()           */   /* This macro below is explained above.                              */    Q_PROPERTY ( double ,  default_activation )   /** @}                                                               */   /** @name Property-related functions                                 */   /** @{                                                               */   /** Get the value of the <b>  default_activation  </b> property.                    */   const  double & get_default_activation () const   { return this->getProperty_default_activation ().getValue(); }   /** Get a writable reference to the <b>  default_activation  </b> property.        */    double & upd_default_activation ()   { return this->updProperty_default_activation ().updValue(); }   /** %Set the value of the <b>  default_activation  </b> property.                   */   void set_default_activation (const  double & value)   { this->updProperty_default_activation ().setValue(value); }   /** @}                                                               */;*/   bool _has_output_statebounds_activation  {   this->template constructOutput< SimTK::Vec2 >("statebounds_activation", &Self:: getBoundsActivation ,  SimTK::Stage::Model )   };   /** @endcond                                                         */;**/  /** This typedef might be useful within the member functions of this class. */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  typedef  ActivationCoordinateActuator  Self;  /** Use this typedef to refer to the superclass of this class.              */  /** Avoid using the explicit type name of the superclass; this would        */  /** introduce bugs if the superclass is changed.                            */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  typedef  CoordinateActuator  Super;  /** @endcond **/  public:   /** @name Auto-generated functions */   /** @{ */   /** For use in MATLAB and Python to access the concrete class. */   /** Example: `cObj = %ActivationCoordinateActuator.safeDownCast(obj)`. */   /** This is equivalent to `dynamic_cast<ActivationCoordinateActuator*>(obj)` in C++. */   static  ActivationCoordinateActuator * safeDownCast(OpenSim::Object *obj)   {   return dynamic_cast< ActivationCoordinateActuator  *>(obj);   }   /** @cond developer */   /** This allows copy assignment in the Java GUI. */   /** @throws Exception if the argument is not of type  ActivationCoordinateActuator. */   void assign(Object &aObject) override   {   if (safeDownCast(&aObject)!=0) {   *this = *(( ActivationCoordinateActuator *)(&aObject));   } else {   throw OpenSim::Exception(std::string("ActivationCoordinateActuator")+   "::copy() called with object (name = " + aObject.getName()   + ", type = " + aObject.getConcreteClassName()+").",   __FILE__,__LINE__);   }   }   /** @endcond */   /** @}*/;;  /** @name Auto-generated functions                                          */  /** @{                                                                      */  /** This returns "ActivationCoordinateActuator"                                        */  /** See getConcreteClassName() if you want the class name of the underlying */  /** concrete object instead.                                                */  /** \internal This is generated by the `OpenSim_DECLARE_*_OBJECT` macros.   */  static const std::string& getClassName()  { static std::string name("ActivationCoordinateActuator"); return name; }  /** @}*/;  /** @name Auto-generated functions                                          */  /** @{                                                                      */   ActivationCoordinateActuator * clone() const override {return new  ActivationCoordinateActuator (*this);}  const std::string& getConcreteClassName() const override  { return getClassName(); }  /** @}*/  private:;;**/   /** @cond **/   PropertyIndex PropertyIndex_activation_time_constant ;   const Property< double >& getProperty_activation_time_constant () const   { return this->template getProperty< double >(PropertyIndex_activation_time_constant ); }   Property< double >& updProperty_activation_time_constant ()   { return this->template updProperty< double >(PropertyIndex_activation_time_constant ); }   /** @endcond **/   /** @cond **/   void copyProperty_activation_time_constant (const Self& source)   { PropertyIndex_activation_time_constant  = source.PropertyIndex_activation_time_constant ; }   /** @endcond **/   /** Get the value of the i-th element of the <b>  activation_time_constant  </b> property. */   const  double & get_activation_time_constant (int i) const   { return this->template getProperty< double >(PropertyIndex_activation_time_constant )[i]; }   /** Get a writable reference to the i-th element of the <b>  activation_time_constant  </b> property. */    double & upd_activation_time_constant (int i)   { return this->template updProperty< double >(PropertyIndex_activation_time_constant )[i]; }   /** %Set the value of the i-th element of <b>  activation_time_constant  </b> property.    */   void set_activation_time_constant (int i, const  double & value)   { this->updProperty_activation_time_constant ().setValue(i,value); }   /** Append an element to the <b>  activation_time_constant  </b> property.                 */   int append_activation_time_constant (const  double & value)   { return this->updProperty_activation_time_constant ().appendValue(value); }   void constructProperty_activation_time_constant (const  double & initValue) {   PropertyIndex_activation_time_constant  =   this->template addProperty< double >("activation_time_constant", "Larger value means activation changes more slowly (units: seconds; default: 0.01 seconds)." ,initValue);   }   /** @endcond **/   /** @name Properties (single-value)                                  */   /** @{                                                               */   /**  "Larger value means activation changes more slowly (units: seconds; default: 0.01 seconds)."                                                           */   /** This property appears in XML files under                         */   /** the tag <b>\<activation_time_constant\></b>.                                    */   /** This property was generated with                                 */   /** the #OpenSim_DECLARE_PROPERTY macro;                             */   /** see Property to learn about the property system.                 */   /** @see get_activation_time_constant(), upd_activation_time_constant(), set_activation_time_constant()           */   /* This macro below is explained above.                              */    Q_PROPERTY ( double ,  activation_time_constant )   /** @}                                                               */   /** @name Property-related functions                                 */   /** @{                                                               */   /** Get the value of the <b>  activation_time_constant  </b> property.                    */   const  double & get_activation_time_constant () const   { return this->getProperty_activation_time_constant ().getValue(); }   /** Get a writable reference to the <b>  activation_time_constant  </b> property.        */    double & upd_activation_time_constant ()   { return this->updProperty_activation_time_constant ().updValue(); }   /** %Set the value of the <b>  activation_time_constant  </b> property.                   */   void set_activation_time_constant (const  double & value)   { this->updProperty_activation_time_constant ().setValue(value); }   /** @}                                                               */;**/   /** @cond **/   PropertyIndex PropertyIndex_default_activation ;   const Property< double >& getProperty_default_activation () const   { return this->template getProperty< double >(PropertyIndex_default_activation ); }   Property< double >& updProperty_default_activation ()   { return this->template updProperty< double >(PropertyIndex_default_activation ); }   /** @endcond **/   /** @cond **/   void copyProperty_default_activation (const Self& source)   { PropertyIndex_default_activation  = source.PropertyIndex_default_activation ; }   /** @endcond **/   /** Get the value of the i-th element of the <b>  default_activation  </b> property. */   const  double & get_default_activation (int i) const   { return this->template getProperty< double >(PropertyIndex_default_activation )[i]; }   /** Get a writable reference to the i-th element of the <b>  default_activation  </b> property. */    double & upd_default_activation (int i)   { return this->template updProperty< double >(PropertyIndex_default_activation )[i]; }   /** %Set the value of the i-th element of <b>  default_activation  </b> property.    */   void set_default_activation (int i, const  double & value)   { this->updProperty_default_activation ().setValue(i,value); }   /** Append an element to the <b>  default_activation  </b> property.                 */   int append_default_activation (const  double & value)   { return this->updProperty_default_activation ().appendValue(value); }   void constructProperty_default_activation (const  double & initValue) {   PropertyIndex_default_activation  =   this->template addProperty< double >("default_activation", "Value of activation in the default state returned by initSystem() (default: 0.5)." ,initValue);   }   /** @endcond **/   /** @name Properties (single-value)                                  */   /** @{                                                               */   /**  "Value of activation in the default state returned by initSystem() (default: 0.5)."                                                           */   /** This property appears in XML files under                         */   /** the tag <b>\<default_activation\></b>.                                    */   /** This property was generated with                                 */   /** the #OpenSim_DECLARE_PROPERTY macro;                             */   /** see Property to learn about the property system.                 */   /** @see get_default_activation(), upd_default_activation(), set_default_activation()           */   /* This macro below is explained above.                              */    Q_PROPERTY ( double ,  default_activation )   /** @}                                                               */   /** @name Property-related functions                                 */   /** @{                                                               */   /** Get the value of the <b>  default_activation  </b> property.                    */   const  double & get_default_activation () const   { return this->getProperty_default_activation ().getValue(); }   /** Get a writable reference to the <b>  default_activation  </b> property.        */    double & upd_default_activation ()   { return this->updProperty_default_activation ().updValue(); }   /** %Set the value of the <b>  default_activation  </b> property.                   */   void set_default_activation (const  double & value)   { this->updProperty_default_activation ().setValue(value); }   /** @}                                                               */;*/   bool _has_output_statebounds_activation  {   this->template constructOutput< SimTK::Vec2 >("statebounds_activation", &Self:: getBoundsActivation ,  SimTK::Stage::Model )   };   /** @endcond                                                         */;

**Comment by chrisdembia** [comment]
This is fixed on the `feature_logging` branch:

https://github.com/opensim-org/opensim-core/blob/38937261eb39fcb6515747b0fcc0b2b328b6ffe2/OpenSim/Actuators/ActivationCoordinateActuator.h#L32-L45
