### ISSUE TITLE
I want to know about how to simulate when external force is applied.

### ISSUE THREAD

**Issue by daichi-3110** [opensim-org/opensim-core#2758]
I am using McKibbenActuator in OpenSim. Is it possible to find out how much the muscle resists when an external force is applied to the model and it is moved? If a constant external force is applied, it will continue to move. In reality, I think the muscles will resist and become immobile.
The model is https://simtk.org/projects/finger

**Comment by jenhicks** [comment]
Thanks for the question. This type of inquiry is best suited for our user forum, linked below. Please post your question there.

https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
