### ISSUE TITLE
python install error: from . import _simbody ImportError: libSimTKmath.so.3.7:

### ISSUE THREAD

**Issue by Prakyathkantharaju** [opensim-org/opensim-core#2763]
Hello, 
I am trying to install opensim for python3.8, using the instruction : 
https://github.com/opensim-org/opensim-core.
During the install 
`ctest -j8`
Only 2 python test is failing.
To debug this I performed following step:

- `sudo python3 setup.py install` in the opensim-core/lib/python3.8/site-packages
- `python3 -c "import opensim"`
I am getting following error:
`>>> import opensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prakyath/opensim-core/lib/python3.8/site-packages/opensim/__init__.py", line 1, in <module>
    from .simbody import *
  File "/home/prakyath/opensim-core/lib/python3.8/site-packages/opensim/simbody.py", line 13, in <module>
    from . import _simbody
ImportError: libSimTKmath.so.3.7: cannot open shared object file: No such file or directory
`
Please help me solve this issue;
I have attached my cmakefile 
[CMakeCache.txt](https://github.com/opensim-org/opensim-core/files/4608079/CMakeCache.txt)

**Comment by marnunez** [comment]
Hi! Try running make install before ctest. I use a python script (https://github.com/marnunez/opensim-build) to build the current master, check the environment variables as well. Ah, and make sure you either choose ezc3d or btk if you're planning on building the GUI

**Comment by aymanhab** [comment]
Your CMakeCache refers ro SWIG 4.0 which is not supported yet, please revert to use SWIG version 3.0.9 or 3.0.12, if that resolves the problem please close this issue. Thank you

**Comment by Prakyathkantharaju** [comment]
@aymanhab I tried with swig 3.0.12, which did not resolve the issue.

**Comment by aymanhab** [comment]
I would start at using python 3.6 from python.org as we build/test against that on every commit (log here: https://github.com/opensim-org/opensim-core/runs/690040928 (uses python 3.6 on ubuntu 18.04). Once you have this going, you should make changes, if necessary, one at a time to figure out what breaks the build since we can't reproduce all the variety of os/python-distribution combinations.

**Comment by Prakyathkantharaju** [comment]
@marnunez Thank you code worked for the python installation.
I am still figuring installation with GUI.
@aymanhab Thank you for your help.
