### ISSUE TITLE
How to use GUI on linux?

### ISSUE THREAD

**Issue by Linardos** [opensim-org/opensim-core#2768]
After successfully building from source, how can I open the GUI? Considering I am using an ubuntu machine.

**Comment by marnunez** [comment]
Hi! This repository is only for the core library, the GUI itself is in [opensim-gui](https://github.com/opensim-org/opensim-gui). Instructions on how to build it are in the docs, and there's a [full Linux installer](https://github.com/opensim-org/opensim-gui/pull/1181) now!

**Comment by chrisdembia** [comment]
Thanks for replying, @marnunez!
