### ISSUE TITLE
Failed tests and ModuleNotFoundError

### ISSUE THREAD

**Issue by annshorn** [opensim-org/opensim-core#2771]
Hi, there is another problem that I faced. I went through rules and on the step:
`ctest -j8`

I got this:

```
95% tests passed, 5 tests failed out of 106

Total Test time (real) = 252.03 sec

The following tests FAILED:
	 76 - testStaticOptimization (Failed)
	 94 - python_tests (SEGFAULT)
	 95 - python_examples (SEGFAULT)
	102 - Java_TestTables (Failed)
	106 - Java_TestXsensDataReader (Failed)
Errors while running CTest
```

My main goal is the opportunity to import OpenSim into Jupiter notebook. And after doing installation still can't import (ModuleNotFoundError: No module named 'opensim')

Is it because of not all tests passes?

**Comment by aymanhab** [comment]
test failures have no downstream effect, so unrelated but may indicate problems with your build/environment. Likely you didn't build C3D support, make sure you choose value other than None for OPENSIM_C3D_PARSER is using latest master branch, or turn on WITH_BTK if using 4.1 code base.  This likely will take care of the java test failures. Python failures likely due to using unsupported python, our continuous integration builds and tests against standard python 3.7 from python.org. If successful in importing into Jupiter notebook please open a PR to document the steps. Thank you

**Comment by annshorn** [comment]
In the "CMakeCache.txt" in opensim_build changed 

```
//Compile OpenSim with a C3D parser ? ezc3d or BTK provide C3D
// reading.
OPENSIM_C3D_PARSER:STRING=None
```

to

`OPENSIM_C3D_PARSER:STRING=WITH_BTK`

It gives:
```
96% tests passed, 4 tests failed out of 106

Total Test time (real) = 252.13 sec
The following tests FAILED:
	 94 - python_tests (SEGFAULT)
	 95 - python_examples (SEGFAULT)
	102 - Java_TestTables (Failed)
	106 - Java_TestXsensDataReader (Failed)
Errors while running CTest
```

About python actually I don't understand: I use python 3.7 from anaconda - is it not supported?

**Comment by chrisdembia** [comment]
Do you mean `OPENSIM_C3D_PARSER:STRING=BTK` (no `WITH_`)?

Python 3.7 from Anaconda is supported if you are building from source (as you are). The issue may be that you are trying to import the python libraries using a version of python different from the one that CMake found and used to build OpenSim's python library.

**Comment by aymanhab** [comment]
- You should use CMake GUI to make these changes rather than edit the cache: since you're using latest master, use BTK from the dropdown and point CMake to where this is located.
- As @chrisdembia pointed out, you need to make sure the same python used for building in (CMake)  is used for installing/running.

**Comment by annshorn** [comment]
"CMakeCache.txt":

<img width="715" alt="Снимок экрана 2020-05-14 в 21 32 27" src="https://user-images.githubusercontent.com/49962972/81971895-78efdd80-962a-11ea-9708-76b2fe62d852.png">

And screen of the calling Jupiter:

<img width="821" alt="Снимок экрана 2020-05-14 в 21 33 27" src="https://user-images.githubusercontent.com/49962972/81972033-ab99d600-962a-11ea-9a89-0580a6bc498e.png">

for me paths look the same, isn't not?

**Comment by annshorn** [comment]
<img width="850" alt="Снимок экрана 2020-05-15 в 18 40 10" src="https://user-images.githubusercontent.com/49962972/82069105-8b761f80-96db-11ea-9879-da3d13763590.png">

<img width="428" alt="Снимок экрана 2020-05-15 в 18 40 34" src="https://user-images.githubusercontent.com/49962972/82069132-94ff8780-96db-11ea-88e7-5fbb3af60418.png">

**Comment by chrisdembia** [comment]
Can you run `ctest --output-on-failure -R python_tests` and share the output?

**Comment by annshorn** [comment]
<img width="632" alt="Снимок экрана 2020-05-15 в 19 39 14" src="https://user-images.githubusercontent.com/49962972/82074660-c714e780-96e3-11ea-8888-17b6dc27538e.png">

**Comment by chrisdembia** [comment]
Hmm...I wonder why the `--output-on-failure` flag isn't helping to show more output from the test.

Perhaps we could address this quicker over a phone chat; you can email me (see my GitHub profile).

**Comment by annshorn** [comment]
Ok, wrote you, please check your spam (because maybe my mail can got into spam)

**Comment by chrisdembia** [comment]
@annshorn and I looked further into this...the segfault is related to Anaconda. If we use Homebrew's Python, there is no issue. I was able to reproduce the segfault locally.

**Comment by chrisdembia** [comment]
I think I've fixed this issue. Some background:

- https://github.com/pybind/pybind11/issues/1579
- https://github.com/shogun-toolbox/shogun/issues/4068
- https://github.com/deeptools/pyBigWig/issues/58
- https://github.com/djsutherland/shogun-feedstock/commit/657e9be019578c8fb7d1fd930d73707dea469ee2
- https://github.com/lisitsyn/shogun/commit/961f6109c2a8abab4941bcdde1a19dfe70c440f1
- https://github.com/Fluorescence-Tools/tttrlib/commit/5056add6d57b66ba754dc6f76520165da52d3591
