### ISSUE TITLE
Describe new logging capabilities in changelog for 4.2

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2785]

**Comment by jenhicks** [comment]
@nickbianco thinks that @chrisdembia may have started working on this ... should verify so we don't duplicate effort.

**Comment by aymanhab** [comment]
@jenhicks I started adding this but seems out of place in changelog since this is supposed to be permanent. Any suggestions for placement of detailed description (how to add another logfile, disable logging in Matlab, logging levels, formatting etc.) Developer's Guide seems better but wanted to check with you.
@carmichaelong @nickbianco Thoughts?

**Comment by jenhicks** [comment]
@aymanhab I think the changelog should include a brief description of the update. Then a more detailed description of logging would go in the documentation. https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+and+Development and/or doxygen.
