### ISSUE TITLE
Provide more details on OpenSense heading correction

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2787]

**Comment by aymanhab** [comment]
Confluence https://simtk-confluence.stanford.edu/display/OpenSim/OpenSense+-+Kinematics+with+IMU+Data

**Comment by aymanhab** [comment]
Code https://github.com/opensim-org/opensim-core/tree/master/OpenSim/Simulation/OpenSense

**Comment by aymanhab** [comment]
Did we lose the figure that @carmichaelong work on? I can't find it on confluence @jenhicks

**Comment by carmichaelong** [comment]
@aymanhab We didn't finalize it on confluence since I made that before you made some other changes to fix the heading correction for arbitrary default poses. I'm setting the figure over to you on email now. Perhaps we can also figure out what else would have to change about the figure to be representative of the current code?

**Comment by jenhicks** [comment]
@carmichaelong What's the status on this one?

**Comment by carmichaelong** [comment]
I haven't started on making any adjustments to the image yet. I just looked over the code again and want to double check with @aymanhab that my understanding is correct.

Previously, the IMUs were rotated based on the angle between the IMU base heading axis vs OpenSim world x-axis. I believe now that it actually uses the angle between the IMU base heading axis vs the model's base frame x-axis. @aymanhab if this is correct, let me know and I can re-do the image to convey this correctly.

**Comment by aymanhab** [comment]
@carmichaelong indeed your updated description is correct.

**Comment by carmichaelong** [comment]
Updated figure:
![heading_correction_crop](https://user-images.githubusercontent.com/7455790/95275330-0b249800-07fd-11eb-9698-b134527d24f3.png)

**Comment by aymanhab** [comment]
Beautiful figure, looks great. Thanks @carmichaelong
