### ISSUE TITLE
how to contact you?

### ISSUE THREAD

**Issue by BlackWolf734** [opensim-org/opensim-core#2788]
a team of russian developers are working on the new education project based on vr tecnologies. We are looking for specialists who can help us, join in our team or get some advices. I hope you are interested in this idea.
contact us:
email: khodzhaevvva@mail.ru
skype, telegram, whatsapp, tel.:+79013634227

**Comment by aymanhab** [comment]
You can contact us using simtk project page at https://simtk.org/projects/opensim or directly on github

**Comment by aymanhab** [comment]
Since this is not an actual issue, will close.
