### ISSUE TITLE
Support running IK on live data 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2791]
As of now, the InverseKinematicsSolver caches the data that it is solving for, this limits the ability of clients to provide data on the fly which is needed for live data processing.

**Comment by aymanhab** [comment]
One idea is to decouple the data producer (could be file/table or device) from the data consumer (solver) in this case. This approach was tried in https://github.com/RealTimeBiomechanics/rtosim.  A solution that enables the solver to read data from a Queue that could be populated from either a table or live data should solve this problem. Issues to consider:
- Thread safety /synchronization
- In case of multiple consumers with different speeds, how to make sure results are produced in order
- How to leverage the use of previous solution

**Comment by jenhicks** [comment]
@aymanhab Is this issue resolved with the merge of #2855? Have updates been noted in the changelog?

**Comment by jenhicks** [comment]
Waiting on feedback from Patrick
