### ISSUE TITLE
Specified motion of model without IK Tools

### ISSUE THREAD

**Issue by annshorn** [opensim-org/opensim-core#2792]
Hi :)

As I understand, the IK/ID tools allow analyzing the motion of the model with a specified motion file (.mot or .sto). 

Like I take a model, load tools, and run it - at this moment I can't "control" my model, I mean, I can only see how model simulates the movement from the loaded file. 

Example:
```
imuIK = osim.IMUInverseKinematicsTool();
 
# Set tool properties
imuIK.set_model_file(modelFileName);
imuIK.set_orientations_file(orientationsFileName);
imuIK.set_sensor_to_opensim_rotations(sensor_to_opensim_rotation)
imuIK.set_results_directory(resultsDirectory)

# Set time range in seconds
imuIK.set_time_range(0, startTime); 
imuIK.set_time_range(1, endTime);   

# Run IK
imuIK.run(visualizeTracking);
```

Is it possible to somehow make this movement from the file the default movement of the model? (this is for further using PrescribedController() and iterative changing the behavior of the model by applying force) 

Example:

```
osimModel = osim.Model(modelFileName)
state = osimModel.initSystem() 
manager = osim.Manager(osimModel)
state.setTime(0)
manager.initialize(state)
state = manager.integrate(10.0)
```

(So I get the same motion from file)

**Comment by aymanhab** [comment]
Hi, I don't think this belongs to the issues. There's ongoing work on tools that enable tracking of motion or IMU data directly (e.g. Moco) but this is outside the scope of openim-core as is. What do you think @chrisdembia @nickbianco ?

**Comment by chrisdembia** [comment]
CMC and Moco both seem appropriate here. @annshorn please ask this question in the forum: http://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
