### ISSUE TITLE
Linking OpenSim causes downstream applications to create a log file

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#2801]
Minor, non-breaking issue. Close it if it's intended/not big enough to address.

If I write a trivial C++ application that `#include`s the OpenSim headers:

```c++
// main.cpp
#include <OpenSim/OpenSim.h>

int main() {
  return 0;
}
```

And then compile + link it into an executable, followed by running the resulting executable:

```bash
# libraries built from: b0222c20bba068aa1abedde4b7d3ac7fba221629

g++ \
  -Iopensim-core-install/include \
  -Iopensim-core-install/include/simbody \
  -Iopensim-core-install/include/OpenSim \
  main.cpp \
  -o main \
  -Lopensim-core-install/lib \
  -losimCommon \
  -losimAnalyses \
  -losimSimulation \
  -losimTools \
  -losimActuators \
  -Wl,-rpath opensim-core-install/lib

./main
```

Then an empty `opensim.log` is created in the current working directory. 

My expectation is that linking, but not using, a library should have no side-effects until I start using it, or call some library-init function (e.g. `SDL_Init`, `glutInit`). Again, this is unlikely to break downstream unless it's reliant on a clean dir. However, some library integrators might be surprised when it happens.

**Comment by aymanhab** [comment]
@adamkewley Thanks for reporting. 
Basically the log file is useful to report/help-troubleshoot issues including loading of dynamic libraries which is done implicitly for you. Depending on log-level you may see messages there indicating what types of objects are available to the code etc. as such this is expected behavior, low-level integrators may do without this mechanism.

I'd also clarify that linking the libraries by itself has no side-effects however running a main program that links our libraries produce the log file.  This is the price for avoiding the need for explicit *_Init call which is not a cross-platform standard AFAICT, but let us know if you're aware of other solutions.

**Comment by adamkewley** [comment]
Sure, again, no biggie. 

The possible drawback of that architecture is that any application that links OpenSim is going to produce a `opensim.log` file in the current dir of the executing process. Fine enough when (e.g.) a desktop manager is always booting (e.g.) the GUI with the same working directory, but it can cause confusion for CLI developers, who typically use a range of working dirs.

For example, if I run `opensim-cmd --help`, it'll produce it a `opensim.log` file in the current dir. For CLI users, who are probably used to selecting output paths for programs, it'll be kind of annoying if one of their commands always pollutes `$PWD`. 

One (hacky) solution around this is to support an environment variable (e.g. `OPENSIM_LOG_LOCATION`) that callers can set to something absolute (e.g. `/tmp/opensim.log`).

---

> I'd also clarify that linking the libraries by itself has no side-effects however running a main program that links our libraries produce the log file.

Clearly, declaring a library at the compilation level has no side-effects, apart from declaring the library to the runtime dynamic linker. At runtime, the dynamic linker will load the library, which includes running all static initializers for the library,  and will link any undefined symbols, before calling `main`. 

The static initializer creating `opensim.log` is at `Common/Logger.cpp:39`, which is in the compilation unit of the library, not the downstream application, so any usage of the library (even with something like `RTLD_LAZY`) will cause this behaviour. E.g. I can make an application that has no compile-time dependencies on OpenSim dump `opensim.log` into `$PWD`:

```c++
// compile: g++ main.cpp -o main -ldl

int main() {
  dlopen("../opensim-core/opensim-core-install/lib/libosimCommon.so", RTLD_GLOBAL | RTLD_NOW);
  return 0;
}
```

So merely loading the library causes the behavior. Linking depends on loading, so  linking the library will *also* cause the behavior.

**Comment by aymanhab** [comment]
@adamkewley thanks for the feedback. I think we are in sync. regarding the current behavior. 

Considering the tradeoff between making it easy to log/troubleshoot vs. making it possible to not produce the log file I'd lean to leave the default behavior as is, close this issue and open a different one (or modify this one to something like) to: Enable loading OpenSim libraries without creating a log file, if you feel this is warranted. Thanks again for your feedback 👍

**Comment by chrisdembia** [comment]
We could introduce an environment variable to control the logging to file.

I think it is abnormal behavior for a library to log to a file by default, but this has also been OpenSim's behavior for a while; I wonder if our users now expect it. One improvement we made was renaming the log files from non-descript `out.log` and `err.log` files to `opensim.log`.

**Comment by adamkewley** [comment]
@aymanhab @chrisdembia , all sounds good and useful points. Feel free to close this off and I'll PR separately.

If I get a spare bit of time, I can try and PR for the environment variable change. I imagine it'll be something along the lines of `auto path = env_var_set ? path_with_fallback_mechanism : "opensim.log"` (not exactly that, but basically that). The main time consumption is probably going to be figuring out where the documentation for that feature should sit, such that it isn't just buried in the C++. 

Again, this issue isn't a biggie. If it's been normal behavior for a while then cool - it was just something I randomly noticed when I started using `opensim-cmd` in situations like the profiling scripts I'm gradually building up (which step into a bunch of different FD/IK directories containing osims and XML etc.). Probably not a standard use-case for most end-users.

**Comment by adamkewley** [comment]
@tgeijten just FYI - this was the issue related to log file creation (as mentioned yesterday).

I'll try and PR the following changes:

- Add a **compile-time** flag for disabling the behavior completely (i.e. just disable the statically-initialized log file). Discuss making this a default for all but debug/dev builds
  - I think Matt mentioned that the flag already exists, if it does, I'll just email you the details
  - If it doesn't I'll add it, but initially default it to "on" to match existing behavior
- Add a **run-time** environment for *either* disabling the behavior completely or, at least, the ability to write the log file somewhere else (e.g. `/dev/null`, or some windows temp dir)
  - This is so that downstream developers or release-users don't have to recompile in order to disable the behavior. They will just need to set an environment variable if they're calling `opensim-cmd`, or call their dynamically-linked executable with that environment variable set. This is easier to do on Linux/Mac, where any file can be "executable" and writing a wrapping bash script around a native ELF executable binary is normal. It is harder to utilize this on Windows, where directly calling the executable is the norm (so there's no opportunity to set the environment variable before the dynamic linker calls the static initializers).

**Comment by tgeijten** [comment]
Great -- even though I would make a separate PR with just the first one. It's a trivial change that doesn't affect anything if you leave it off by default, so it should be easy to get accepted.

The third option is also great and straightforward: just implement a `get_logger()` function with a local static -- much better design anyway. This _should_ also allow you to disable log file creation at runtime, if you lower the log level before the first log event.

Changing the path of the log file is something I would also prefer to do during runtime. As you mention, environment variables are not a platform independent solution, so we shouldn't rely on that. On the other hand, it could be omitted entirely with a sane default, such as `/temp/OpenSim/log/<DATE>-<TIME>.log`. Adding a timestamp with enough precision and/or doing a duplicate file name check also prevents the racing issues.

**Comment by adamkewley** [comment]
> On the other hand, this can be omitted entirely with a sane default, such as /temp/OpenSim/log/<DATE>-<TIME>.log. Adding a timestamp with enough precision and/or doing a duplicate file name check also prevents the racing issues. It also ensures a log file with important information doesn't get replaced with a newer one.

Bleh. In order to get around the static initialization fiasco of OpenSim we're now entering the realm of:

- Providing extra compile flags for downstream
- Dealing with multi-process race conditions
- (because of the above) dealing with log rotation to prevent runaway log file leaks (your suggestion will end up creating hundreds of log files in a single directory, and downstream users may end up having to trawl through them to figure out which of the hundreds of subprocesses logs contain a useful error)

Imho this static-init log should go to an fd that is 1:1 with the process and guaranteed to be temporary. It should also be runtime-overrideable with a custom stream (e.g. a GUI console logger). C++ already has something that fills the temporary and 1:1 requirement--`stdout` and `stderr`--and even provides the necessary abstraction to override those with an abstract output stream at runtime (`std::ostream`). 

Because switching to using standard output streams would break legacy stuff, the compromise is to go with "don't write the file until a static initialization error actually occurs". This should at least allow (e.g.) SCONE to statically initialize followed by, at runtime setting the log output stream to something more suitable (e.g. a GUI console) - provided you don't use the compile flag.

For multi-process situations, where some host application (e.g. `python`) is running a precompiled opensim application (e.g. `opensim-cmd`) there will be race conditions on the log. In order to deal with those, we either have to have a bunch of complicated race-condition-free logging+rotation code in opensim itself (that's just asking for other bugs, imho), or we can provide some basic runtime environment variables that can be checked at static init time (e.g. `OPENSIM_LOG_USE_STDIO`, `OPENSIM_LOG_PATH`).

Environment variables are quite platform-independent. All platforms support environment variables + args as part of a process's state. The main issue is *setting* them, which is hard to do when booting into a UI (e.g. SCONE) in Windows, because you effectively have to tell users to edit some Windows settings (eugh, no). However, it's easy to set environment variables on a subprocess (e.g. [native windows](https://docs.microsoft.com/en-us/windows/win32/procthread/changing-environment-variables), [python](https://docs.python.org/3/library/subprocess.html)), and subprocesses are where (I think) the worst race conditions are going to happen, so supplying a runtime method of changing the log behavior should hopefully handle that specific issue.

As an additional out, I'll also add the compile flag.

**Comment by tgeijten** [comment]
Ok, well, as long as there's a separate compile option (via a CMake flag) to disable logging altogether, I'm happy and able to proceed working OpenSim 4 support in SCONE. Hopefully this can be a separate (small) PR.

**Comment by aymanhab** [comment]
Based on the above I assume we're on agreement to go with a compile time flag so the change is surgical and doesn't affect default/legacy behavior. Please let us know if that's the plan as of now @adamkewley Thank you.

**Comment by adamkewley** [comment]
Yeah, that's it.

I'm not in agreement with the legacy behavior, but it's not a massive deal
breaker and there's no point breaking downstream over it. I think it's
probably best to keep behaviour as-is until a major release and maybe
consider alternatives then.

For now, I'll just add the compile flags and explore only opening the log
file on first write, which should be enough to keep most people happy. The
environment variables would be a nice-to-have for scripters who
multiprocess the cli

**Comment by tgeijten** [comment]
As discussed in the meeting September 22, 2020: this feature is required for OpenSim 4 support in SCONE.

**Comment by adamkewley** [comment]
@tgeijten sorry, I forgot about this issue. The feature has now been merged into `master`, here:

https://github.com/opensim-org/opensim-core/pull/2880

So if you pull `master` you should see an `OPENSIM_DISABLE_LOG_FILE` option available, which should disable the functionality

**Comment by adamkewley** [comment]
So, unless release testing encounters an issue, the next release *should* support what you need *and* also not create an `opensim.log` file until something needs to be written (if the compile-time flag is off, if you turn it on, it will not create the file at all - even if a message needs to be written).
