### ISSUE TITLE
opensim-cmd viz throws Regular Expression related exception and aborts on windows

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2807]
latest build on master, try opensim-cmd viz produces:

[error] regex_error(error_stack): There was insufficient memory to determine whether the regular expression could match the specified character sequence.

**Comment by chrisdembia** [comment]
Darn. I thought that restricting the Options descriptions to one line kept us safe from this issue. Could someone using Windows look into this?

**Comment by aymanhab** [comment]
@chrisdembia I can try but not sure what options/knobs to tune since the previous fix seemed like a result of a lucky observation. Any hints or pointers to avoid starting from scratch would be helpful.
