### ISSUE TITLE
Old model from OpenSim 3.2 distribution fails to open

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#282]
message while trying to load bouncing_block.osim

PointToPointSpring::connect() could not find component '' to satisfy Connector<Body> 'body1'.

**Comment by jenhicks** [comment]
@aymanhab Is this still a bug?

**Comment by aymanhab** [comment]
Yes, still occurs with latest code.

**Comment by jimmyDunne** [comment]
I tested with the models in opensim-org/models. Both bouncing_block.osim and bouncing_block_weak_spring.osim are instantiated without error. 

```
>> model = Model('bouncing_block_weak_spring.osim')
Updating Model file from 20303 to latest format...
Loaded model toy_with_forces from file bouncing_block_weak_spring.osim
 
model =
 
toy_with_forces
```

**Comment by jenhicks** [comment]
Fixed on master, but not on alpha that GUI
