### ISSUE TITLE
Not able to spawn the whole model issues in the model please help

### ISSUE THREAD

**Issue by crkaushik93** [opensim-org/opensim-core#2831]
![imp file](https://user-images.githubusercontent.com/53141800/87022362-4a2b5900-c1ce-11ea-96ef-9f4ed5588e39.PNG)

**Comment by chrisdembia** [comment]
Go to Edit > Preferences and update your Geometry Path setting.

**Comment by aymanhab** [comment]
Thanks @chrisdembia 
Since this is not related to his repo, and it belongs to the forum, I'll close the issue. Thanks for reporting @crkaushik93
