### ISSUE TITLE
C:\opensim-core-source\dependencies\BTK\Code\BasicFilters\btkMergeAcquisitionFilter.cpp(816): warning C4309: "??": ???? ? [C:\opensim-core-dependencies-build\BTK\build\Code\BasicFilters\BTKBasicFilters.vcxproj] 

### ISSUE THREAD

**Issue by sustliuyoufu** [opensim-org/opensim-core#2840]
Hey,Excuse Me,I have some question when i execute "cmake --build . --config RelWithDebInfo",There are some warning in my windows Poershell   such  as: 
 _c:\opensim-core-source\dependencies\ezc3d\include\Data.h(62): warning C4251: "ezc3d::DataNS::Data::_frames": class"std:
:vector<ezc3d::DataNS::Frame,std::allocator<_Ty>>"??? dll ??? class"ezc3d::DataNS::Data"?????? [C:\opensim-core-depende
ncies-build\ezc3d\build\ezc3d.vcxproj] [C:\opensim-core-dependencies-build\ezc3d.vcxproj]_

could   you  help me!!!

**Comment by chrisdembia** [comment]
If these are warnings, you can ignore them.

Your description is confusing because your title mentions BTK but your top comment mentions ezc3d.
