### ISSUE TITLE
BodyKinematics header always says angular velocity and acceleration are in body's frame

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#2842]
From a [forum post](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=12244&p=34707&start=0&view=):
User says that whether `express_results_in_body_local_frame` is True or False, the header does not change

**Comment by chrisdembia** [comment]
Wow, BodyKinematics is getting really popular.

**Comment by carmichaelong** [comment]
Issue has surfaced again on the forums affecting another user: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=13260
