### ISSUE TITLE
Optimizer failed to converge IK solutions in required iterations

### ISSUE THREAD

**Issue by AbhinavGupta121** [opensim-org/opensim-core#2848]
Hey! I received the following error msg while using IK tool on an open sim 3.3 model. 

"InverseKinematicsTool Failed: AssemblySolver::assemble() Failed: SimTK Exception thrown at Assembler.cpp:871:
  Method Assembler::assemble() failed because:
Optimizer failed with message: SimTK Exception thrown at InteriorPointOptimizer.cpp:261:
  Optimizer failed: Ipopt: Maximum iterations exceeded (status -1)
Assembly error tolerance achieved: 0.0229306492859652 required: 1e-006.".

I assume that optimizer couldn't find the optimum joint angles which minimize the marker error below a specified tolerance level. Can someone tell me how to remove this issue and still achieve accurate IK solutions?

**Comment by jenhicks** [comment]
Sorry you're having issues. Please post a question on our user forum, if you haven't already. 
https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
