### ISSUE TITLE
Tests broken on master branch when building in Debug mode

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#2851]
Looking into the cache variable fix, which I'll PR, but there seems to be other tests broken. Might also be related to the CV merge but they look like they're kind of unrelated, and might have slipped in from other merges.

I don't currently have time to bisect + rebuild + retest the master branch to figure out where these problems came in. I'll PR the cache variable fix, but these tests are still broken on current `master`, even after applying that fix.

It seems like most of the failures are because SimTK has a bunch of strict runtime assertions that are probably there to help developers do the right thing, but are only obvious *after* they have been triggered. We don't build debug in CI, and I imagine many devs build `RelWithDebInfo`, so these checks are not necessarily exercised regularly.

`testDataTable`
```
4/93 Test  #4: testDataTable ................................***Failed    2.83 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testDataTable is a Catch v2.12.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
TableUtilities::resample
-------------------------------------------------------------------------------
../OpenSim/Common/Test/testDataTable.cpp:884
...............................................................................

../OpenSim/Common/Test/testDataTable.cpp:893: FAILED:
  CHECK( resampled.getDependentColumnAtIndex(0)[0] == Approx(0.75) )
due to unexpected exception with message:
  SimTK Exception thrown at MatrixHelperRep.h:289:
    Error detected by Simbody method MatrixHelperRep::updElt(i): Matrix not
  writable.
    (Required condition 'm_writable' was not met.)

===============================================================================
test cases:   7 |   6 passed | 1 failed
assertions: 235 | 234 passed | 1 failed
```

`testActuators`:

```
1.1547005383792516842
1.1547005383792516842
 ********** Test Actuator Combination time = ********** 86.795ms

[info] Loaded model model from file Model_ActivationCoordinateActuator.osim
SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
  Integrator step failed at time 0 apparently because:
SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
  Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 0.
  (Required condition 't1 > t0' was not met.)

Done, with failure(s): (testActivationCoordinateActuator)
```

**Comment by adamkewley** [comment]
`testDataTable` fault is because a non-`const` operator overload is triggering some internal check in a Simbody matrix to think that it's being edited, which is disallowed on that particular matrix instance, so it dies. Easy fix: just `static_cast<const T>(...)` the temporary.

The actuator fault has been a huge pain in the ass because that error message is spurious. What I thought was happening was that `t1` was somehow overstepping over `t0`, maybe due to some funny maths in `AbstractIntegratorRep::takeOneStep`, but what's actually happening is that the call to `attemptDAEStep` keeps failing over and over, making the step size go smaller by a factor of 10 each time, until the step size eventually flattens to 0, at which point the assertion fails because `(t0 + step) > t0` is not true.

As for why integration fails over and over, it's because a `NaN` appears in some inertia matrix somewhere internally in SimTK (probably misconfigured OpenSim model or something). Because it's a debug build, this causes a range check to throw at `SimTK::Inertia_<double>::errChk`. Full stack for that exception:

```
1  __cxa_throw                                                                                     0x7ffff3d3aaf0 
2  SimTK::Inertia_<double>::errChk                             MassProperties.h               524  0x55555560ac7e 
3  SimTK::Inertia_<double>::Inertia_                           MassProperties.h               244  0x7ffff6f86bf2 
4  SimTK::UnitInertia_<double>::UnitInertia_                   MassProperties.h               707  0x7ffff59a5663 
5  SimTK::UnitInertia_<double>::reexpress                      MassProperties.h               814  0x7ffff59a4ec9 
6  RigidBodyNode::calcJointIndependentKinematicsPos            RigidBodyNode.cpp              75   0x7ffff59a1be8 
7  RigidBodyNodeSpec<1, false, true, true>::realizePosition    RigidBodyNodeSpec.h            287  0x7ffff59ba95a 
8  SimbodyMatterSubsystemRep::realizePositionKinematics        SimbodyMatterSubsystemRep.cpp  1135 0x7ffff5b20694 
9  SimbodyMatterSubsystemRep::realizeSubsystemPositionImpl     SimbodyMatterSubsystemRep.cpp  1071 0x7ffff5b1fde9 
10 SimTK::Subsystem::Guts::realizeSubsystemPosition            Subsystem.cpp                  280  0x7ffff4a7f3b6 
11 SimTK::MultibodySystemRep::realizePositionImpl              MultibodySystem.cpp            234  0x7ffff5979a7f 
12 SimTK::System::Guts::realizePosition                        System.cpp                     462  0x7ffff4a85301 
13 SimTK::System::Guts::realize                                System.cpp                     784  0x7ffff4a86fbf 
14 SimTK::System::realize                                      System.cpp                     171  0x7ffff4a83a44 
15 SimTK::IntegratorRep::setAdvancedStateAndRealizeDerivatives IntegratorRep.h                910  0x7ffff4ea50d0 
16 SimTK::RungeKuttaMersonIntegratorRep::attemptODEStep        RungeKuttaMersonIntegrator.cpp 108  0x7ffff4eac4be 
17 SimTK::AbstractIntegratorRep::attemptDAEStep                AbstractIntegratorRep.cpp      146  0x7ffff4e90f4d 
18 SimTK::AbstractIntegratorRep::takeOneStep                   AbstractIntegratorRep.cpp      552  0x7ffff4e91e4d 
19 SimTK::AbstractIntegratorRep::stepTo                        AbstractIntegratorRep.cpp      413  0x7ffff4e916db 
20 SimTK::Integrator::stepTo                                   Integrator.cpp                 65   0x7ffff4ea690d 
21 SimTK::TimeStepperRep::stepTo                               TimeStepper.cpp                128  0x7ffff4eafc8d 
22 SimTK::TimeStepper::stepTo                                  TimeStepper.cpp                81   0x7ffff4eaf96d 
23 OpenSim::Manager::integrate                                 Manager.cpp                    728  0x7ffff6d91993 
24 testActivationCoordinateActuator                            testActuators.cpp              962  0x5555555ec68c 
25 main                                                        testActuators.cpp              86   0x5555555e4709 
```

That exception goes missing because `AbstractIntegratorRep::attemptDAEStep` has a cute "feature", which is that it silently swallows any and all exceptions, incl. their error message, and just counts the entire thing as a "failure" and moves on:

```c++
    // AbstractIntegratorRep.cpp:146

    bool ODEconverged = false;
    try {
        numIterations = 1; // so non-iterative ODEs can forget about this
        ODEconverged = attemptODEStep(t1, yErrEst, errOrder, numIterations);
    } catch (...) {return false;}  // [bye bye debugging -adam]
```

I'll need to separately figure out why a NaN slips into this particular test, but @sherm1 , or someone who's familiar, long-term, with Simbody's internals, why on earth does the integrator eat every single exception? In industry, we call this "Pokemon exception catching":

https://www.hackterms.com/pokemon%20exception%20handling

Sometimes there's a reason for them (e.g. top-level of application wants to log any and all exceptions before blowing up) but in a middle-layer class like the integrator it seems out of place?

**Comment by sherm1** [comment]
Hi @adamkewley. In a variable step integrator, taking too large a step can (and frequently does) cause spurious exceptions. The right response in that case is to reduce the step size and retry rather than report the essentially meaningless exception. However, that is not supposed to go on forever! Once the step gets to a minimum size it should _not_ suppress the exception but report it as the cause of failure. The code snippet above does not appear to have that behavior. Also, it would be a nice debugging feature if suppressing exceptions could be turned off.

**Comment by adamkewley** [comment]
Thanks @sherm1 - makes sense. I've patched around it in OpenSim (to get it compiling + passing tests in debug mode again). 

I could have a quick look into simbody to see if there's some--probably, rather hacky--way of bubbling the correct exception. Maybe some lower limit on the step size (e.g. if the time delta is <1e-30 then throw up the exception). 

Another idea would be to count the exceptions' messages in an (e.g.) `unordered_map<string, int>` that, when the thing finally "pops" prints something like `n exceptions were detected: m: "Some NaN-related thing" o: "Some other exception"` etc.

I'll close off this particular issue though: thanks again
