### ISSUE TITLE
libspdlog.a(spdlog.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#2852]
Hi there, 

I am having troubles compiling opensim in my ubuntu 16.04 version, I have included BTK, Python and Matlab wrapping options. I have built simbody, docopt and spdlog (I compiled the latest versions). Simbody did all test good. There is an error  when building libosimCommon.so and is the following:

```
/usr/bin/ld: /usr/local/lib/libspdlog.a(spdlog.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libspdlog.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
OpenSim/Common/CMakeFiles/osimCommon.dir/build.make:1280: recipe for target 'libosimCommon.so' failed
make[2]: *** [libosimCommon.so] Error 1
CMakeFiles/Makefile2:2529: recipe for target 'OpenSim/Common/CMakeFiles/osimCommon.dir/all' failed
```
I have searched in the web and I found the following, however it did not work. 

[https://github.com/gabime/spdlog/issues/1405](https://github.com/gabime/spdlog/issues/1405)

To be more specific, I am including my installation script as follows

```
cd /home/nikorose/Workspace/
mkdir Opensim
cd Opensim

sudo apt-get update
sudo apt-get --yes install git cmake cmake-curses-gui \
                           freeglut3-dev libxi-dev libxmu-dev \
                           liblapack-dev swig python-dev \
                           openjdk-8-jdk

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
git clone https://github.com/opensim-org/opensim-core.git
mkdir opensim_dependencies_build
cd opensim_dependencies_build
cmake ../opensim-core/dependencies/ \
	-DCMAKE_INSTALL_PREFIX="../opensim_dependencies_install" \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DSUPERBUILD_BTK=ON \
	-DSUPERBUILD_simbody=OFF \
	-DSUPERBUILD_spdlog=OFF \
	-DSUPERBUILD_docopt=OFF \
make -j8
cd ..
mkdir opensim_build
cd opensim_build


cmake ../opensim-core \
      -DCMAKE_INSTALL_PREFIX="../opensim_install" \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DOPENSIM_DEPENDENCIES_DIR="../opensim_dependencies_install" \
      -DBUILD_PYTHON_WRAPPING=ON \
      -DBUILD_JAVA_WRAPPING=ON \
      -DWITH_BTK=ON \
      -DOPENSIM_DOXYGEN_USE_MATHJAX=ON \
      -DSIMBODY_HOME="/home/nikorose/Workspace/Opensim/simbody_install"

make doxygen
make -j8
ctest -j8
make -j8 install
```
Can you help me with this? Any advice?

Thanks

**Comment by aymanhab** [comment]
Any reason to set SUPERBUILD_spdlog=OFF? The baked in version of spdlog is regularly tested in continuous integration and works, it appears you're building your own version or have a different installation of spdlog that's built using a different set of flags and that causes the problem downstream. Please superbuild spdlog and make sure you link to the correct version and let us know.

**Comment by nikorose87** [comment]
Thanks @aymanhab 

I had to include the superbuild version of spdlog to make it work. Now, It's working so far. However, docopt and simbody do not need the superbuild mode, they can be included directly.

**Comment by chrisdembia** [comment]
Your build script doesn't show how you previously installed spdlog, but it seems like if you use the `-fPIC` flag when compiling spdlog, then your custom-built spdlog will work with OpenSim.
