### ISSUE TITLE
Problem with updating the OpenSim C++ v3.3 into v4.1

### ISSUE THREAD

**Issue by Sugiartowahyu** [opensim-org/opensim-core#2857]
Hello,

i have been strugling to updating/changing the codes of OpenSim C++ from v3.3 into v4.1. (i'm using OpenSim v4.1)
i still want to use the class and function "manager" to do my forward dynamic, but because the structure of the codes has been changed since the upgrade to v4.1, i have no idea until now how to have a same results after changing/updating the codes to v4.1.
the snapshot below is the header file
<img width="569" alt="EngineOpensim" src="https://user-images.githubusercontent.com/69356716/89731863-d25d8200-da4a-11ea-9e9e-f78b99d1dc04.png">
(FYI: m_model->buildSystem();
        m_state = m_model->initializeState(); )

Best regards
Wahyu

**Comment by tkuchida** [comment]
There might be some helpful code in [testManager.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Test/testManager.cpp). Also see the examples and explanations in the doxygen documentation for the [`Manager::integrate()`](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Manager.html#aadec36a0fcf34c2654d9737baf4a961d) method.
