### ISSUE TITLE
Inputing the values of the external torque per time step to the TorqueActuator while CMC Simulation in Simulink

### ISSUE THREAD

**Issue by Sugiartowahyu** [opensim-org/opensim-core#2858]
Hello,

Right now i want to do a CMC (Computed Muscle Control) simulation to get the needed muscle forces under consideration of external torque in simulink. So this external torque (as a function of the input kinematics) will help the osim model to tracking the given reference/input kinematics.
But i'm struggling to input the calculated external torque from my other simulink block to the CMC-block in simulink.
can anyone help me with it or give me a suggestion/an example to how to write the code to input the values of the calculated external torque per time step from my other simulink block to the CMC-block in simulink? 

Here is the force set from my osim-model: ('Torque_from_CableActuator')
<img width="282" alt="model with torque" src="https://user-images.githubusercontent.com/69356716/89938801-519fb100-dc17-11ea-92df-a426200bd368.png">

**Comment by jenhicks** [comment]
Thanks for filing the issue. This does not look like a bug report or feature request, so we ask that you post on our user forum if you haven't already.
