### ISSUE TITLE
Seems like InverseDynamicsTool is generating a XML version error

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#2864]
Hello,

I am generating all the inverse dynamic process in a series of trials in gait. I have a python script to generate automatically all XML files to perform from scaling to ID.

The script was behaving well until IDtool had to work. The error is the following:

> RuntimeError: std::exception in 'bool OpenSim::InverseDynamicsTool::run()': SimTK Exception thrown at Xml.cpp:820:
  Error detected by Simbody method Xml::Element::getAs(): The given Node was not an Element; it is a NoNode. Use Element::isA() to check before calling Element::getAs().
  (Required condition 'isA(node)' was not met.)

I have read that is something related to the XML document version. I have generated every specific file with templates found in the tutorials, they have different versions, but the only one that thrown an error was the IDtool. I am attaching all configuration files in case you need it.

Please do not hesitate if you need more information.
[osim_files_S01.zip](https://github.com/opensim-org/opensim-core/files/5113506/osim_files_S01.zip)

Thanks

By the way, I have not found a way to add the Geometry Path in order to load the `.vtp ` model files. I have tried with `sys.path` but It did not work. If you can write a piece of code to load this path I would appreciate it.

**Comment by nikorose87** [comment]
Thanks @aymanhab 
Unfortunately, It did not work. I added `nrows` and` ncolumns` to the header, changed the extension from `sto` to `mot`, but the error is still there.

**Comment by aymanhab** [comment]
So, did you change the ID Tool setup file to use an actual .osim model file rather than an .mot file under the tag <model_file>?

**Comment by nikorose87** [comment]
Thanks in advance @aymanhab. I was confused about the coordination file location. Now it works. Sorry
