### ISSUE TITLE
AttributeError: module 'opensim' has no attribute 'simulation' Error

### ISSUE THREAD

**Issue by itayco421** [opensim-org/opensim-core#2867]
hey, I am a new user at OpenSim just trying to import it to my py code (Via Conda env-Pycharm):

`C:\Users\itayc\anaconda3\envs\openSim\python.exe "C:/Users/itayc/ExoSkeleton Project/Python/Test_0.py"
Traceback (most recent call last):
  File "C:/Users/itayc/ExoSkeleton Project/Python/Test_0.py", line 1, in <module>
    import opensim
  File "C:\Users\itayc\anaconda3\envs\openSim\lib\site-packages\opensim-4.1-py3.7.egg\opensim\__init__.py", line 1, in <module>
    from .actuators import *
  File "C:\Users\itayc\anaconda3\envs\openSim\lib\site-packages\opensim-4.1-py3.7.egg\opensim\actuators.py", line 334, in <module>
    class CoordinateActuator(opensim.simulation.ScalarActuator):
AttributeError: module 'opensim' has no attribute 'simulation'

Process finished with exit code 1

when I tried running my code on Spyder, it worked fine... what could be the problem?

**Comment by jenhicks** [comment]
@nickbianco Any ideas?

**Comment by aymanhab** [comment]
This is the same symptom of python 3.8 not supported by our current version of SWIG as discussed elsewhere

**Comment by itayco421** [comment]
So after I have set the Specific environment for python 3.7, and install the OpenSim once again at the same specific env everything works for now...

**Comment by jenhicks** [comment]
Closing since we have the existing issue for Python 3.8
