### ISSUE TITLE
Having wrong results on IDtool with force platform Type 3

### ISSUE THREAD

**Issue by nikorose87** [opensim-org/opensim-core#2868]
Hi Opensim team.

I do not know If I should write in the forum, but probably, this could be also an API issue. I am coding an iterating process to calculate the Dynamic Joint Stiffness in human Gait (moments and angles). Also, my data has type-3 force platform information, so I had to built the API with one of latest versions of [ezc3d](https://github.com/pyomeca/ezc3d/tree/type1_3). After doing Scaling, obtaining the `trc` and `sto` files, either for static or moving cases, applying the `IKtool` and the `IDtool`. I am having some results:

The following are some results from the GRF using the `C3DFileAdapter`:
![Figure 2020-08-26 224026](https://user-images.githubusercontent.com/14098755/91381790-d250d680-e7ed-11ea-8974-d960fac44ffd.png)
![Figure 2020-08-26 224026 (7)](https://user-images.githubusercontent.com/14098755/91381800-daa91180-e7ed-11ea-8f31-3ec645beb40b.png)
![Figure 2020-08-26 224026 (6)](https://user-images.githubusercontent.com/14098755/91381778-c9f89b80-e7ed-11ea-9662-f334f64ba002.png)

So far the results are coherent unless they are not appropriately oriented.

With respect to the trajectories of the markers, which were written using the `TRCfileAdapter`. The following is an example of an ankle angle after applying `IKtool` :

![Figure 2020-08-26 224026 (3)](https://user-images.githubusercontent.com/14098755/91382264-f660e780-e7ee-11ea-966d-7eeeaf780eb0.png)

Previous plots look good for me, but according to the results obtained for moments, I do not know if they really are. The remaining variable (moments) was obtained through the `IDtool` but they threw bad results. This is an example of moments in both ankles:

![Figure 2020-08-26 224026 (4)](https://user-images.githubusercontent.com/14098755/91382341-26a88600-e7ef-11ea-9413-c711c0ac3189.png)

As you see this is like the tool was replicating the GRF, with very big numbers, they are not proportional among the limbs, and obviously, this is not the moment behavior for a sound ankle.

It is possible also that, something is missing or is not well configured in the ID xml files. I am appending in case something could be wrong.

[S01_0004_Gait.zip](https://github.com/pyomeca/ezc3d/files/5133990/S01_0004_Gait.zip)

Thanks for the patience and let me know if you need more information. 

Regards.

**Comment by jenhicks** [comment]
Thanks for the message and sorry that you are having issues. This indeed looks like it would be a better post for our user forum.

**Comment by nikorose87** [comment]
Thanks @jenhicks 

I will write also into the forum. However, I assume that this behavior is because Type 3 platforms are not configured yet, so I will wait if the cause is for this reason.

**Comment by nikorose87** [comment]
After doing some work with the data and, understanding what you do the `osimC3D.m` in Matlab. I have rotated and scaled the data. The inverse dynamics appear to be well calculated. Thus the integration of the Type-3 platforms with ezc3d does not affect the Opensim API.

This is an example of the ankle moment, calculated with inverse dynamics.

![Figure 2020-08-26 224026 (10)](https://user-images.githubusercontent.com/14098755/92335192-704c6880-f05a-11ea-8c3b-ead1abf01bc0.png)
