### ISSUE TITLE
inertia after non-uniform manual scaling 

### ISSUE THREAD

**Issue by fmatari** [opensim-org/opensim-core#2871]
Hi,

Our team is interested in migrating from version 3.3 to 4.1, we have noticed that there is a difference in inertia results when performing non-uniform manual scaling. After performing the scaling in a spreadsheet, we confirmed that version 3.3 provided correct results and 4.1 incorrect. The source code for 4.1 was looked into and after some cout statements and digging around, the issue was found. From body.cpp:scaleInertialProperties(),

        if (axis == 0) {
            rad_sqr = radius * (scaleFactors[1]) * radius * (scaleFactors[2]);
            inertia[0][0] = 0.5 * get_mass() * rad_sqr;
            inertia[1][1] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);
            inertia[2][2] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);

        } else if (axis == 1) {
            rad_sqr = radius * (scaleFactors[0]) * radius * (scaleFactors[2]);
            inertia[0][0] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);
            inertia[1][1] = 0.5 * get_mass() * rad_sqr;
            inertia[2][2] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);

        } else {
            rad_sqr = radius * (scaleFactors[0]) * radius * (scaleFactors[1]);
            inertia[0][0] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);
            inertia[1][1] = get_mass() * ((length * length / 12.0) + 0.25 * rad_sqr);
            inertia[2][2] = 0.5 * get_mass() * rad_sqr;
        }

We confirmed that the if statements are properly satisfied so the calculations should be performed. Though calculations are never performed and the problem is found to be in the inertia variable type. Inertia utilizes a symmetric 3 x 3 matrix and this matrix is not allowing the assignment of values to specific elements. Changing the variable type from a symmetric matrix to a regular matrix fixes this issue. 

    //SimTK::SymMat33 inertia = _inertia.asSymMat33();
    
    SimTK::Mat33 inertia = _inertia.toMat33();

The top commented line is the original and bottom is the suggested fix. We have not looked into why the symmetric matrix fails. 

Best regards,
Fouad

**Comment by dfrenkel101** [comment]
We tracked down the C++ reason for this issue (of broken non-uniform scaling in OpenSim 4.x) and described it in the second post to this thread in the OpenSim forum:

[](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=12413&p=0&start=0&view=&sid=55f629bd9702c4f4a952716a49d84eb0)
