### ISSUE TITLE
Error trying to add marker in MATLAB

### ISSUE THREAD

**Issue by g-racer** [opensim-org/opensim-core#2874]
I am trying to add markers to a model and get the following error. Help would be appreciated!!

Java exception occurred:
java.lang.RuntimeException: Warning in Model::print(): The following connections are not finalized and will not
appear in the resulting XML file. Call finalizeConnections() before print().
To ignore, set the debug level to at least 1 (e.g, by calling Object::setDebugLevel(1)) first.
  Socket 'parent_frame' in Marker at /markerset/RSHANK1

My code is:

import org.opensim.modeling.*
ku_model=('C:\OpenSim 4.1\Resources\Models\KULeuven_foot__8DoF_lessmarkers.osim')
omodel=Model(ku_model);

tibiaRbody = omodel.getBodySet().get('tibia_r')       %                  # Get a handle to the body

newMarker = Marker();
newMarker.setName('RSHANK1');
newMarker.setParentFrame(tibiaRbody)
newMarker.set_location(  Vec3(1,1,1));
omodel.addMarker(newMarker)

omodel.print('testModel.osim');

**Comment by tkuchida** [comment]
The error message says to "Call finalizeConnections() before print()." Did that not work?
```
...
omodel.finalizeConnections();
omodel.print('testModel.osim');
```
Also, I think this is a question for the [User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91) (GitHub Issues are for tracking development tasks).

**Comment by aymanhab** [comment]
Closing as the issue doesn't belong here. If the suggestion by @tkuchida doesn't work for you please post to the user forum so other users can benefit. Thank you.
