### ISSUE TITLE
[Bindings] Passing MarkersReference as argument causes error 

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#2889]
Another issue I've encountered after merging `master` into `moco` while working on #2805. 

Interacting with a MarkersReference object in the bindings works fine, until you try to pass it as an argument:

```
markerTracking = osim.MocoMarkerTrackingGoal()
markerTracking.setMarkersReference(markersRef)
```

This generates the following error:

```
*** TypeError: in method 'MocoMarkerTrackingGoal_setMarkersReference', argument 2 of type 'OpenSim::MarkersReference const &'
```

**Comment by aymanhab** [comment]
@nickbianco While refactoring InverseKinematicsSolver, I had to rearrange headers for the .i files to get proper types. Not sure how MocoMarkerTrackingGoal makes it into bindings but I can look into it if you point me in the right direction. First step would be to check the signature of the method after swig. It could be that I made changes in Java and not in python or the behavior of binding is slightly different.
