### ISSUE TITLE
Ubuntu/Debian opensim-core make failure during opensense build

### ISSUE THREAD

**Issue by ngolikov** [opensim-org/opensim-core#2899]
following instructions outlined in superbuild section, opensense is failing to build generating output below:

`
/app/opensim/opensim-dep-install/simbody/lib/libSimTKmath.so.3.7: undefined reference to `dgbtrs_'
/app/opensim/opensim-dep-install/simbody/lib/libSimTKmath.so.3.7: undefined reference to `cunmrz_'
/app/opensim/opensim-dep-install/simbody/lib/libSimTKmath.so.3.7: undefined reference to `zheevx_'
/app/opensim/opensim-dep-install/simbody/lib/libSimTKmath.so.3.7: undefined reference to `zsytrf_'
/app/opensim/opensim-dep-install/simbody/lib/libSimTKmath.so.3.7: undefined reference to `dlaic1_'
collect2: error: ld returned 1 exit status
Applications/opensense/CMakeFiles/opensense.dir/build.make:103: recipe for target 'opensense' failed
make[2]: *** [opensense] Error 1
CMakeFiles/Makefile2:805: recipe for target 'Applications/opensense/CMakeFiles/opensense.dir/all' failed
make[1]: *** [Applications/opensense/CMakeFiles/opensense.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

The related command that appears to be failing:

`
opensense: Applications/opensense/CMakeFiles/opensense.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/app/opensim/opensim-build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../../opensense"
`

Environment: 

Debian GNU/Linux 9 (stretch)      .. also same error observed when building on Ubuntu 18
cmake version 3.7.2

![image](https://user-images.githubusercontent.com/2593819/98897815-45c3c500-247a-11eb-993a-9ba644f9e048.png)

**Comment by ngolikov** [comment]
closing the issue as I was able to eventually build it on Debian GNU/Linux 10 (buster)

suspect the issue was with something being misconfigured. worked after installing cmake 3.19.0-rc3

In case anyone is interested, I did notice en error when building opensim 4.1 with [latest BTK](https://github.com/klshrinidhi/BTKCore/commit/ae0d2a43de0fe6c9ef2acce34a87c944dd113829) 
`
/usr/local/include/btk-0.4dev/Utilities/Eigen/src/Core/DenseCoeffsBase.h:56:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]
/opensim/opensim-core/OpenSim/Common/C3DFileAdapter.cpp: In member function ‘virtual OpenSim::DataAdapter::OutputTables OpenSim::C3DFileAdapter::extendRead(const string&) const’:
/opensim/opensim-core/OpenSim/Common/C3DFileAdapter.cpp:176:40: error: ‘class btk::GroundReactionWrenchFilter’ has no member named ‘setLocation’
         ground_reaction_wrench_filter->setLocation(
                                        ^~~~~~~~~~~
/opensim/opensim-core/OpenSim/Common/C3DFileAdapter.cpp:177:46: error: ‘Location’ is not a member of ‘btk::GroundReactionWrenchFilter’
             btk::GroundReactionWrenchFilter::Location(getLocationForForceExpression()));
                                              ^~~~~~~~
In file included from /usr/local/include/btk-0.4dev/Utilities/Eigen/Core:277,
                 from /usr/local/include/btk-0.4dev/btkConfigure.h:119,
                 from /usr/local/include/btk-0.4dev/Common/btkSharedPtr.h:39,
                 from /usr/local/include/btk-0.4dev/Common/btkObject.h:39,
                 from /usr/local/include/btk-0.4dev/Common/btkProcessObject.h:39,
                 from /usr/local/include/btk-0.4dev/IO/btkAcquisitionFileReader.h:40,
                 from /opensim/opensim-core/OpenSim/Common/C3DFileAdapter.cpp:3:
`

**Comment by aymanhab** [comment]
Thanks for reporting, our default now is to use ezc3d library instead of btk which is not maintained anymore. You can choose zc3d when building opensim-core using a CMake variable (OPENSIM_C3D_PARSER), along with superbuild ezc3d when building dependencies.
