### ISSUE TITLE
Saving previewed TRC experimental data sets units to mm by default

### ISSUE THREAD

**Issue by antoinefalisse** [opensim-org/opensim-core#2938]
When saving previewed experimental TRC data from the GUI (e.g., after applying a transform), the `Units` are set to `mm` even if the imported data were in `m`. The values are not adjusted accordingly, making the saved file unusable for IK for instance. Tested with OpenSim 4.2 beta.

**Comment by aymanhab** [comment]
I see that indeed and have a fix, can you send a trc file in meters to test? thank you

**Comment by antoinefalisse** [comment]
Sure, here is one:
[4test.zip](https://github.com/opensim-org/opensim-core/files/5912193/4test.zip)

**Comment by aymanhab** [comment]
Thanks @antoinefalisse the artifact from https://github.com/opensim-org/opensim-gui/pull/1265 should have the fix shortly.

**Comment by antoinefalisse** [comment]
Hi @aymanhab I tested that out and it worked fine on my machine.

(The GUI crashed the first time but I re-started it and it worked well - I re-tried a couple of times and it worked fine each time - not sure what happened but probably unrelated to this change).

**Comment by aymanhab** [comment]
Thank you @antoinefalisse
