### ISSUE TITLE
Remove lapack, etc. stuff from CMakeLists.txt

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#294]
Chris, what did you mean by this?

cc/ @chrisdembia

**Comment by sherm1** [comment]
@chrisdembia can you say more about this?

**Comment by chrisdembia** [comment]
There's a bunch of CMake commands in OpenSim's root CMakeLists.txt that seem to be copied from Simbody, like `BUILD_USING_OTHER_LAPACK`. These variables, etc. have no function in OpenSim, since they are controlled by Simbody.

This amounts to deleting a bunch of duplicate cmake code. It's easy, but I want to do it as part of #195. Progress on #195 is awaiting #229 though.
