### ISSUE TITLE
Test Strength of simulation CMC run

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2950]
Strength of simulation, running CMC fails in 4.2 Beta while running the same file(s) in 4.1 succeeds

**Comment by carmichaelong** [comment]
@aymanhab I'm seeing the same behavior as you. I'm not sure how to help debug since I'm not seeing any meaningful feedback on why it failed...

**Comment by carmichaelong** [comment]
Model uses Thelen muscles too, so shouldn't be related to initialization changes in Millard muscles

**Comment by aymanhab** [comment]
06/29/2020 Failed due to padding as in 4.2
06/23/2020 WORKED
Likely culprit is refactoring to padding when introducing the TableUtilities::Pad

**Comment by aymanhab** [comment]
Rolling back the change to the Pad function indeed fixes the problem, CMC runs to completion. I opened a PR with the roll-back while I look into the details. Will add a test case to exercise the example to make sure we don't break it down the road.

**Comment by nickbianco** [comment]
Kinda jumping in late here, but was the test just failing, or was CMC crashing? I could see how the padding change would change a reference solution, which would cause a fail. But in that case, we would just need to re-generate the reference solution.

**Comment by aymanhab** [comment]
@nickbianco Thanks for chiming in. There was no test, I'm adding one since this is an example we distribute. The Strength-of-Simulation example was failing to run CMC entirely because of this padding change. The latest code throws if the pad-size is larger than the signal while the old code handled it (by repeated padding). You may have insight as to why this was changed.

**Comment by aymanhab** [comment]
@carmichaelong I'm making the test case for Swing but would be good to include stance as well. Can you test Stance in version 4.1 to see if it works? Thank you

**Comment by nickbianco** [comment]
Ah I see. After looking at your PR the recent changes are a lot cleaner than what we had previously. We just need to add proper error messaging if the pad size is invalid. But for the purposes of getting 4.2 released, I think rolling back the changes temporarily is fine.

**Comment by carmichaelong** [comment]
Stance in 4.1 definitely worked previously. I had tested this before when we were removing kinematics for external loads because there's a setup file in the models repo with kinematics for external loads that I tested and removed
