### ISSUE TITLE
Access Inverse Kinematic Outputs Programmatically (Python)

### ISSUE THREAD

**Issue by steakerlife** [opensim-org/opensim-core#2957]
hi there - 
I am new to working with opensim and would like to run inverse kinematics on an arbitrary markerset via scripting in python. 

I am looking to input my marker data (which I have currently in json but I can convert it to a .trc file) and get out the IK Fit joint positions after running the optimization scheme via `InverseKinematicsTool()`. However, I have no desire to output files, as I will not actually be using them - instead, I'd like to just output my new fit positions in memory so that I can output them in a file format of my own design.

Is this possible? I looked around in the documentation, but everything seemed to indicate that I'd need to output a .mot file.

**Comment by aymanhab** [comment]
The solver returns a State object that contains coordinates which you can use through the API as desired, as such you don't need any files. The Tool(s) however operate on files as they are higher level abstractions. Please describe use case, don't know why this is opened as an issue to be looked at by dev team. If no specific issue/bug please close, if documentation please specify. Thank you

**Comment by jenhicks** [comment]
The best place to post general questions about using OpenSim is our user forum:
https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB

We use GitHub to track issues and bugs. Hope this helps clear things up!
