### ISSUE TITLE
Visualizer throws IndexOutOfBoundsException when a muscle wraps through a torus and over an ellipse

### ISSUE THREAD

**Issue by johnjdavisiv** [opensim-org/opensim-core#2981]
I have been working on reproducing the [Eng et al 2015](https://simtk.org/projects/iliotibialband/) IT band model in OpenSim 4.1 and ran into the following bug: when a muscle wraps through a torus, and over an ellipse (as happens in the Eng et al model), the visualizer throws an IndexOutOfBoundsException at joint angles that cause the muscle to wrap over both surfaces.  

I think it is purely a visualizer problem, because the Plotting tool will happily calculate and plot the moment arm of this muscle about the knee joint for its full range of motion without any errors.

I have created a minimal reproducible example [here](https://github.com/johnjdavisiv/wrapping-error-reprex) which contains a model that reproduces the problem, as well as the error log from when this error is generated on my computer (Windows 10, OpenSim 4.1).

**Comment by aymanhab** [comment]
@johnjdavisiv This should have been fixed in the latest build of the GUI, you can get it using the steps detailed [https://github.com/opensim-org/opensim-gui/wiki]
