### ISSUE TITLE
Create Synthetic IMU Data Reporter

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2983]
An abstraction of SyntheticIMUDataReporter would be useful in generating Synthetic IMU data post-hoc from a simulation. This could build on a Synthetic IMU objects that can be attached to a model. There are common properties of the Reporter (e.g. when-to-report/Sampling, what-to-report, noise-model etc.). Individual SyntheticIMU Objects could have attachment sockets and outputs that the reporter could leverage.

With a Reporter, we can run this on the thousands of simulations we have to create training data sets as needed.

There could be a few default built-in examples with commonly used settings (e.g. Report Orientations of all segments in Ground).

**Comment by nickbianco** [comment]
The synthetic IMU object could be an `IMUFrame` that derives from `PhysicalFrame` that provides an Output for a synthetic IMU signal (with added noise as an option). Then you could use it with an OutputReporter as-is.

The `IMUFrame` could potentially be used by `IMUPlacer`.

**Comment by aymanhab** [comment]
That could work though we can consider alternatives to PhysicalFrame and inheritance, for example we could just create a plain (Model)Component SyntheticIMU that connects to a Frame using a socket. That would separate the placement functionality (socket) from other native properties specific to the SyntheticIMU, the down-side is that we don't get the output from Frame for free but that could give us more control if we want to add noise for example or report quantities other than orientation. Just a thought

**Comment by nickbianco** [comment]
I guess deriving from PhysicalFrame isn't fully necessary since we're not really adding anything to PhysicalFrame.

**Comment by nickbianco** [comment]
Closing per #3002.
