### ISSUE TITLE
Error documentation Bhargava2004MuscleMetabolicsProbe?

### ISSUE THREAD

**Issue by antoinefalisse** [opensim-org/opensim-core#2992]
Hi,

Based on discussions with Ross Miller, I wonder if there is a documentation issue [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Bhargava2004MuscleMetabolicsProbe.h#L129):

It says: "passive force developed by the muscle fiber **velocity**", but I think it should be **length** instead. Looking into the implementation, it refers to `fiber_force_total` [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Bhargava2004MuscleMetabolicsProbe.cpp#L358), which is computed [here ](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Bhargava2004MuscleMetabolicsProbe.cpp#L296) as
```
const double fiber_force_total = fiber_force_active + fiber_force_passive;
```
`fiber_force_passive `is computed [here ](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Bhargava2004MuscleMetabolicsProbe.cpp#L293) as: `const double fiber_force_passive = m->getPassiveFiberForce(s);` and I believe `getPassiveFiberForce()` is for the passive force **length** (see [doxygen](https://simtk.org/api_docs/opensim/api_docs42/classOpenSim_1_1Muscle.html#ae5abfdcadee2ba771fe5607f34703fd2)).

@carmichaelong or @nickbianco can you confirm? Happy to fix this then.

Thanks.

**Comment by nickbianco** [comment]
Hi @antoinefalisse. This is what `getPassiveFiberForce()` returns on the base `Muscle` class: https://github.com/opensim-org/opensim-core/blob/b33c133e2ef08124c092d4735dd3972bc89baed8/OpenSim/Simulation/Model/Muscle.cpp#L423.

In both [DeGrooteFregly2016Muscle](https://github.com/opensim-org/opensim-core/blob/b33c133e2ef08124c092d4735dd3972bc89baed8/OpenSim/Actuators/DeGrooteFregly2016Muscle.cpp#L363) and [Millard2012EquilibriumMuscle](https://github.com/opensim-org/opensim-core/blob/b33c133e2ef08124c092d4735dd3972bc89baed8/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1010) `mdi.passiveFiberForce` includes both force-length and force-velocity dependent passive fiber force components. So the docs are more so incomplete than actually wrong.

**Comment by antoinefalisse** [comment]
I see, so the passive force-velocity component would come from damping?

**Comment by nickbianco** [comment]
Correct.
