### ISSUE TITLE
Bug: DeGrooteFregly2016Muscle properties not updated after scaling

### ISSUE THREAD

**Issue by SolaWeng** [opensim-org/opensim-core#2995]
Hi,

I was working on the scaling tool with gait_2d model bundled with Opensim Moco in Opensim 4.2 GUI. It appears that the optimal_fiber_length and the tendon_slack_length for DeGrooteFregly2016Muscle are not scaled even through the segment geometries scaled properly. 

I have verified with the Gait10dof18musc model (Millard2012EquilibriumMuscle) bundled with Opensim 4.2 and the muscle length properties are scaled with no issue.

Regards,
Sola

**Comment by nickbianco** [comment]
Hi @SolaWeng, thanks for raising this issue. It looks like with need to implement the `extendPostScale()` method for `DeGrooteFregly2016Muscle` that scales these muscle properties. 

Here's where it happens in the Millard muscle: https://github.com/opensim-org/opensim-core/blob/a8149263af8d7f9a5d81b1540eba6c8601b2debd/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L602

**Comment by nickbianco** [comment]
Hi @SepehrRamezani, I don't believe so. The calls to `extendPostScale()` (via `postScale()` and `Model::scale()`) are specific to the ScaleTool. I don't think these methods are supported in MATLAB. 

I'm currently working on implementing this fix anyway, so you can just download an updated OpenSim build once it's merged (if you don't want to wait for the next OpenSim release).

**Comment by nickbianco** [comment]
Closing per #3108.
