### ISSUE TITLE
Upgrade SWIG dependency to 3.0.2.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#300]
This would help resolve #259.

When we move to 3.0.2, we should modify common.h, as mentioned in #299.

We might want to wait to do this until @aymanhab has built the GUI again.

**Comment by chrisdembia** [comment]
I just tried out swig 3.0.5. There are a few backwards incompatible changes. Here's the one I noticed:

Swig-generated python methods (in opensim.py) have signatures like:

```python
def adoptAndAppend(self, *args):
    # ...
```

That is, every argument is passed in as `*args`.

With swig 3.0, the argument names match those from the C++ code:

```python
def adoptAndAppend(self, aForce):
    # ...
```

The backwards incompatibility comes with our pyWrapOpenSim.i file, in which we extend those swig-generated methods with the assumption that the arguments are `args`, not `aForce`, etc.

So, we can either:

1. Support 2.0.10 and 3.0, and add logic to pyWrapOpenSim.i to detect the swig version.
2. Support 2.0.10 and 3.0, perhaps by using the `-nomodern` flag for python wrapping, which should revert to the old-style signatures. However, the new-style signatures are kinda nice, and there could be other backwards-incompatibilities besides the one I mentioned above.
3. Support only 3.0 and update pyWrapOpenSim.i.
4. Support only 2.0.10.

Note that ubuntu 15.04 (the most recent long term release) still only supports up to 2.0.12. :( It would be *really* nice if we used a version of swig that is available in ubuntu's repositories.

I like option 2 the most.

**Comment by aymanhab** [comment]
@chrisdembia I tried 3.0.5 and the Java wrapping is identical except for one nested class that is now supported. I'd lean toward 3.0 since our headers are now heavily C++11 dependent which will fail earlier swig versions, so will do option 3. Per our discussion this will also allow us to try to reduce or eliminate our SWIG annotated version of SimTK headers.

**Comment by sherm1** [comment]
:+1: (swig 3.0)

**Comment by chrisdembia** [comment]
Great. @aymanhab let me know what you need from me.
