### ISSUE TITLE
[Moco] example2DWalking extremely slow after adding an additional opt parameter

### ISSUE THREAD

**Issue by alexxlzhou** [opensim-org/opensim-core#3003]
Hi all,

I am trying to add a hip SpringGeneralizedForce to the example2DWalking example and optimize the spring constant.
However, I noticed the solution iterations become extremely slow when compared to the case without the SpringGeneralizedForce.
Below are the changes I made to the example code, only to the gaitPrediction function.
For a quick demo, I did not run the tracking, commented out the initial guess, and set the max iterations to 5. 
In the code below, if I set the add_spring = false, the 5 iterations finish within 35 seconds; but when it set to true, the iterations finish over 22 minutes.
The program was run on a Win10 desktop machine.

Any ideas for the reasons behind it and possible solutions to speed up?
Thank you.

```

void gaitPrediction() {

    using SimTK::Pi;

    MocoStudy study;
    study.setName("gaitPrediction");
	
    // Define the optimal control problem.
    // ===================================
    MocoProblem& problem = study.updProblem();

	Model baseModel("2D_gait.osim");
	bool add_spring = true;
	if (add_spring) {
		auto* spring = new SpringGeneralizedForce();
		spring->setName("spring");
		spring->set_coordinate("hip_flexion_r");
		spring->setRestLength(0.0);
		spring->setStiffness(10.0);
		spring->setViscosity(0.0);
		baseModel.addComponent(spring);
	}
	baseModel.finalizeConnections();

	ModelProcessor modelprocessor = ModelProcessor(baseModel);
	//ModelProcessor modelprocessor = ModelProcessor("2D_gait.osim");
	problem.setModelProcessor(modelprocessor);

	if (add_spring) {
		problem.addParameter(
			"spring_stiffness", "spring", "stiffness", MocoBounds(0, 100));
	}

       //.....
       //....
  
        solver.set_optim_max_iterations(5);
        // Use the solution from the tracking simulation as initial guess.
        //solver.setGuess(gaitTrackingSolution);

        // Solve problem.
        // ==============
        MocoSolution solution = study.solve();
        if (!solution.success()) {
		    std::cout << "solution is unsuccessful but unsealed.\n";
		    solution.unseal(); // force access the solution
        }

       //.....
       //....
  
}
```

**Comment by alexxlzhou** [comment]
@tymo77 Yes, I use CasAdi solver. Thanks for pointing this out! 
For this example, switching to MocoTropterSolver failed because it does not support endpoint constraints.
But setting the parameters_require_initsystem property to false for the CasAdi solver indeed sped up the process greatly.
Thanks.

**Comment by nickbianco** [comment]
Thanks @tymo77, `set_parameters_require_initsystem(false)` is indeed the way to go here. The parameters of SpringGeneralizedForce don't require initSystem() calls. Other parameters, like mass and geometry parameters, that change the model topology or inertia do require initSystem calls.
