### ISSUE TITLE
trouble running getRecordValues in matlab

### ISSUE THREAD

**Issue by AffDk** [opensim-org/opensim-core#3005]
Hi,

I tried something like the following code in matlab and faced an error (matlab environment has been configured before and I could run a number of other methods):

import org.opensim.modeling.*
EnvModel = Model('Modelfile');
state = EnvModel.initializeState();
force = EnvModel.getForceSet.get(0);
values = force.getRecordValues(state);

Then I get the following error:

Java exception occurred:
java.lang.RuntimeException: SimTK Exception thrown at GeneralContactSubsystem.cpp:131:
  Expected stage to be at least Dynamics in GeneralContactSubsystemImpl::getContacts() but current stage was Velocity

	at org.opensim.modeling.opensimSimulationJNI.Force_getRecordValues(Native Method)

	at org.opensim.modeling.Force.getRecordValues(Force.java:121)

Any hint on what could be wrong?

Best regards,
Afshin

**Comment by tkuchida** [comment]
Perhaps `state = EnvModel.initSystem();` instead? P.S. Please post questions like this to the User's Forum (https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91); GitHub is intended for tracking software development tasks.

**Comment by AffDk** [comment]
Sorry for the inconvenience!
I have now reported the issue in the opensim forum:
https://simtk.org/plugins/phpBB/viewtopic.php?f=91&t=13475&sid=3bf0c6854ac2d449ab9a2f986803e3fe

I tried with initSystem with no difference.

Best,
Afshin

**Comment by tkuchida** [comment]
Resolved by @aymanhab on the Forum.
