### ISSUE TITLE
[Moco] Failed to generate solution when path constraints are used

### ISSUE THREAD

**Issue by SolaWeng** [opensim-org/opensim-core#3006]
Hi,

I have been working on 3D walking problem with Moco. I used path constraints to ensure minimum foot distance to avoid leg crossing. Here is how I defined the constraints:

```
% Prevent body penetration
distanceConstraint = MocoFrameDistanceConstraint();
distanceConstraint.setName('distance_constraint');
distanceConstraint.addFramePair(MocoFrameDistanceConstraintPair('/bodyset/calcn_l','/bodyset/calcn_r',0.10,100));
problem.addPathConstraint(distanceConstraint);
```

However, when the path constraints are used, the solution failed to be generated even though the optimization ran fine. The error is shown below: 

```
java.lang.RuntimeException: casVector should be 1-dimensional, but has size 0 x 0.
	Thrown at MocoCasOCProblem.h:108 in convertToSimTKVector().

	at org.opensim.modeling.opensimMocoJNI.MocoStudy_solve(Native Method)
```

I guess this is a bug with the Moco 1.0 release?

Thanks,
Sola

**Comment by nickbianco** [comment]
Closing since this is redundant with #3296.
