### ISSUE TITLE
How to generate model and do kinematics in opensim/opensense using only quaternion data from IMU sensors on the body

### ISSUE THREAD

**Issue by dpar21** [opensim-org/opensim-core#3011]
I am currently only reading in quaternion data (e.g. [w, x, y, z] format) from custom IMU sensors and wanted to use OpenSim and Opensense to generate a full body model from the data and also possibly perform inverse kinematics. I am unsure about how to perform this and I have looked over the XSens examples provided for Python but they don't seem to help when using custom IMU data.

**Comment by aymanhab** [comment]
This doesn't seem to be a development bug/issue but generally, we don't create a Model from the data, instead we use a prebuilt model with validated joint definitions, add IMUs on it (to model your custom IMUs) and use the data to pose the model or solve for kinematics using IK. As such I'll close this issue and point you to the docs at 
https://simtk-confluence.stanford.edu/display/OpenSim/OpenSense+-+Kinematics+with+IMU+Data

**Comment by dpar21** [comment]
Thank you for the link! If I have questions in regards to adding our custom IMUs to the prebuilt model where would be the best place to reach out? I don't want to ask them here due to exactly what you mentioned regarding it not being a dev bug/issue but wanted to know who to contact for assistance.

**Comment by aymanhab** [comment]
Hi,

You can use the user forum or privately on simtk.org, or comment/mention on
this closed issue if needed.

Best regards,
-Ayman
