### ISSUE TITLE
Using IMUDataReporter with CMC crashes

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3014]
Using gait10dof18musc files from the distribution, and modified CMC file:
[walk_Setup_CMC_imu.zip](https://github.com/opensim-org/opensim-core/files/6659246/walk_Setup_CMC_imu.zip)

Crashes both in GUI and with command line

@aymanhab

**Comment by aymanhab** [comment]
This is actually not an issue with the Reporter, the crash is due to being called with non-monotnically increasing timestamp .63,.63 maybe that's why we removed analyses from CMC?

**Comment by jenhicks** [comment]
Please re-open if this is still causing issues.
