### ISSUE TITLE
SimTK Optimizer ignores the clamped coordinate ranges

### ISSUE THREAD

**Issue by hjson6** [opensim-org/opensim-core#3019]
I'm trying to make an optimization model which lowering its COM as low as possible within the range of motion in the model but then every range of motion was ignored and ended up with a weird motion. I even tried redefine the range of motion and made it clamped inside the code but it still didn't work. I used actuators at hips, knees and ankles to control the model.

![image](https://user-images.githubusercontent.com/82976296/123022112-a22b9180-d418-11eb-9069-f337556b6a1f.png)

![image](https://user-images.githubusercontent.com/82976296/123022071-8f18c180-d418-11eb-81e4-185fc1f9d414.png)

![image](https://user-images.githubusercontent.com/82976296/123031137-27b63e00-d427-11eb-95c6-785a09fdba0e.png)

May I get any help from anyone who knows how to work with SimTK optimizer and range of motions?

**Comment by jenhicks** [comment]
Closing as this is a duplicate issue.

**Comment by glisca** [comment]
Could you please point the other issue, which this one duplicates?
