### ISSUE TITLE
Doxygen warnings/errors

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3029]
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h:40: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoAccelerationTrackingGoal.h:46: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h:109: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h:119: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h:126: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoContactTrackingGoal.h:33: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoControlTrackingGoal.h:85: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoControlTrackingGoal.h:94: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoControlTrackingGoal.h:100: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoGoal/MocoControlTrackingGoal.h:126: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoInverse.h:65: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoInverse.h:74: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoInverse.h:93: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoInverse.h:102: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoInverse.h:119: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoProblem.h:90: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoProblem.h:106: warning: found subsubsection command outside of subsection context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:36: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:36: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:41: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:71: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:79: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:100: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:113: warning: found subsection command outside of section context!
2>D:/src/opensim-core/OpenSim/Moco/MocoTrack.h:129: warning: found subsection command outside of section context!

**Comment by aymanhab** [comment]
@nickbianco I'm fixing these while trying to generate new doxygen for 4.3, do you know what's wrong there or should I dig into it? Does the generated Doxygen look ok despite these warnings? Thank you

**Comment by nickbianco** [comment]
Looks like it has to do with subsection headers starting with `###`: https://github.com/doxygen/doxygen/issues/5892.

You might be able to replace them with `\section subsubsect Header`.

**Comment by jenhicks** [comment]
@aymanhab Was this resolved?

**Comment by aymanhab** [comment]
Yes, resolved. There're other warnnings but not fatal and not Moco related.
