### ISSUE TITLE
[Moco and opensim-cmd] failed to compile

### ISSUE THREAD

**Issue by yaujunking** [opensim-org/opensim-core#3032]
Hi everyone!

I am compiling the opensim source code in ubuntu 16.04 after builded and installed all the dependencies (not by superbuild)
Then,when I compiling the opensim by command line"make -j4",some errors happen! 
I have screenshots in the forums, please check the link for details
[https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=13652&p=39194&start=0&view=](url)
We can see the errors are about Moco. Then I annotate in the Cmaklist.txt in order to not compile the Moco.
It works, but the opensim-cmd can not work with Moco, either.
How can I solve those problems?
Thanks.

**Comment by jenhicks** [comment]
Resolved on the forum ... closing.
