### ISSUE TITLE
Instruction for installing java on Mac is out of date

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3034]
`brew ask install java` doesn't work anymore.

https://github.com/Homebrew/homebrew-cask-versions/issues/7253
https://stackoverflow.com/questions/24342886/how-to-install-java-8-on-mac/55774255
https://github.com/AdoptOpenJDK/homebrew-openjdk

**Comment by jenhicks** [comment]
Resolved on the forum ... closing.

**Comment by jenhicks** [comment]
Reopening ... closed the wrong issue by mistake.

**Comment by AlbertoCasasOrtiz** [comment]
The new [build script for Mac](https://gist.github.com/AlbertoCasasOrtiz/25d16843669a94ea6e2ea2c7568b0342#file-opensim-core-macos-build-script-sh-L61) uses Java8 from Eclipse Temurin:

```bash
# Install Java 8 from temurin repositories.
brew tap homebrew/cask-versions
brew install --cask temurin8
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
echo $JAVA_HOME
```

**Comment by carmichaelong** [comment]
@AlbertoCasasOrtiz thanks, I'll close this issue. We'll have to do something similar for ARM builds, but I think the update satisfies this issue and that build script is already a helpful guide for the ARM build.
