### ISSUE TITLE
Docker image with OpenSim installed

### ISSUE THREAD

**Issue by RobertoRoos** [opensim-org/opensim-core#3039]
Is there a Docker image available with OpenSim installed? I couldn't find one. I figured it would be useful to have one.

To clarify, I'm not talking about a container to build OpenSim in, but a container we could use to build application that require OpenSim.

**Comment by RobertoRoos** [comment]
Trying to make one myself: https://hub.docker.com/repository/docker/be1et/opensim and https://bitbucket.org/ctw-bw/opensim-docker.

I've based this largely on the TL;DR Linux build instructions from the ReadMe.

But oh boy, as it builds for about an hour debugging it is difficult.

Are there binaries available for Linux x64?

**Comment by RobertoRoos** [comment]
I don't think are official binaries for Linux. I settled for a full build with a lot of patience: https://hub.docker.com/repository/docker/be1et/opensim

Use it with `FROM: be1et/opensim:4.1`

I'm currently building and pushing new version.

**Comment by aymanhab** [comment]
Thanks @RobertoRoos for working on this, I don't see the rationale at this point for duplicating the effort and for maintaining a community resource under a specific user account now that we have a docker image consistent with opensim-core:4.3 that we'll maintain moving forward. Unless there's a specific need it would probably be better for the community to consolidate all images in one place. If you can try the opensim-python image, here, that would be great:
https://hub.docker.com/repository/docker/stanfordnmbl/opensim-python

If you can try it out, give us feedback based on your use case that would be a good place to start, we'll definitely give you credit for your work/contributions. Please let me know what you think. Thank you 👍

**Comment by RobertoRoos** [comment]
Yes, you are definitely right. I just didn't know there were official images (being developed).

Is `opensim-python` the most complete OpenSim install? And will other versions be available too? I specifically need 4.1.

**Comment by aymanhab** [comment]
Thanks for starting the trail/issue, we had bits and pieces around by various developers many on dockerhub but never advertised so thank you for bringing this to the forefront. The use case I was trying to address was a backend application using python3.8 in 4.3 but definitely other variations  should be supported as needed (e.g. opensim-cpp, opensim-java) with appropriate tags. The repository for the docker files to create the images with more details is here 
https://github.com/opensim-org/conda-opensim.git
It'd be awesome if you can use it to open issues/PRs for the use cases you're aware of. 
Thanks again 💯

**Comment by aymanhab** [comment]
containers live in a separate repository now.
