### ISSUE TITLE
testPrescribedForce fails in Debug; bug in ForceSet & ModelComponentSet

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#304]
I ran the OpenSim tests in a VS2013 Debug build. testPrescribedForce failed at [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Test/testPrescribedForce.cpp#L135) when appending to a ForceSet with no associated model. That's because ForceSet has a bug at [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ForceSet.cpp#L193): `if((success)&&(&updModel()!=NULL))` where it expects to be able to get a _reference_ to a null model, which is illegal and is caught during Debug by `ReferencePtr`. Instead there should be a `hasModel()` method for it to call.

`updModel()` is inherited from ModelComponentSet and the exception is thrown [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ModelComponentSet.h#L115). There are a few steps to fixing this:
- [ ] if you look at `getModel()` in the same file you can see it properly checks for a NULL model [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ModelComponentSet.h#L101); updModel() should do the same thing. 
- [ ] there should be a `hasModel()` method to provide a clean way to check without blowing up
- [ ] ForceSet should be fixed to use `hasModel()`
- [ ] Are there other places where `updModel()` is being misused?

**Comment by chrisdembia** [comment]
ForceSet now uses `hasModel()`
