### ISSUE TITLE
Comment for `output_gen_force_file` property in InverseDynamicsTool should warn users not to provide full path

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#3042]
The comment for the `output_gen_force_file` property [here](https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/OpenSim/Tools/InverseDynamicsTool.cpp#L140) should include a comment like "Only a filename should be specified here (not a full path); the file will appear in the location provided in the `results_directory` property." Raised via [Forum Topic 13691](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=13691).

**Comment by aymanhab** [comment]
Thanks @tkuchida 👍 I also wanted to see if we can catch this at a lower level so that we don't fail silently.
