### ISSUE TITLE
AttributeError: module 'opensim' has no attribute 'Model'

### ISSUE THREAD

**Issue by Cynantares** [opensim-org/opensim-core#3044]
Hi, I'm a new user at OpenSim. I have installed OpenSim 4.2 and set the environment for python 3.7 and can successfully "import opensim" in the environment. However, when I'm trying to run the code in pycharm
```
import opensim
import osim
import os
import numpy as np
import matplotlib.pyplot as plt


model = opensim.Model(r'C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\arm2dof6musc.osim')

model.initSystem()

controller = opensim.PrescribedController()

model.setUseVisualizer(True)
model.initSystem()


muscleSet = model.getMuscles()

for j in range(muscleSet.getSize()):
    func = opensim.Constant(1.0)
    controller.addActuator(muscleSet.get(j))
    controller.prescribeControlForActuator(j, func)

model.addController(controller)

state = model.initSystem()

state = model.initializeState()
model.equilibrateMuscles(state)
state.setTime(0.08)

manager = opensim.Manager(model)
manager.setIntegratorAccuracy(1e-05)
manager.initialize(state)

brain = opensim.PrescribedController.safeDownCast(model.get_ControllerSet().get(0))
functionSet = brain.get_ControlFunctions()

for j in range(functionSet.getSize()):
    func = opensim.Constant.safeDownCast(functionSet.get(j))
    func.setValue(float(0.0))

for j in range(200):
    for k in range(functionSet.getSize()):
        func = opensim.Constant.safeDownCast(functionSet.get(k))
        func.setValue(float(0.0))
    model.realizeAcceleration(state)
    k = j+1
    state = manager.integrate(0.01*j)
```

it shows

C:\Users\fxgcy\Anaconda3\envs\py37\python.exe "C:/Users/fxgcy/PycharmProjects/OpenSim Random Activations/opensim.py"
Traceback (most recent call last):
  File "C:/Users/fxgcy/PycharmProjects/OpenSim Random Activations/opensim.py", line 1, in <module>
    import opensim
  File "C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\opensim.py", line 8, in <module>
    model = opensim.Model(r'C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\arm2dof6musc.osim')
AttributeError: module 'opensim' has no attribute 'Model'

Process finished with exit code 1

What's the problem and how to solve it?
Thank you so much!

**Comment by aymanhab** [comment]
When you import opensim keep it in its namespace "import opensim as osim" for example, then you can refer to osim.Model without ambiguity. Not clear what all the modules you import at the top bring to namespace. If that works please let us know and close issue. Thanks

**Comment by Cynantares** [comment]
I tried but the error still exists.

C:\Users\fxgcy\Anaconda3\envs\py37\python.exe "C:/Users/fxgcy/PycharmProjects/OpenSim Random Activations/opensim.py"
Traceback (most recent call last):
  File "C:/Users/fxgcy/PycharmProjects/OpenSim Random Activations/opensim.py", line 1, in <module>
    import opensim as osim
  File "C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\opensim.py", line 8, in <module>
    model = osim.Model(r'C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\arm2dof6musc.osim')
AttributeError: module 'opensim' has no attribute 'Model'

Process finished with exit code 1

**Comment by tkuchida** [comment]
Does the example in the README.md file on GitHub work ([here](https://github.com/opensim-org/opensim-core#simple-example), under "Simple example", expand the "Python" section below the C++ code)? This would rule out any specific issues with the code above. Also, [the "Scripting in Python" page in the documentation](https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+in+Python) has some suggestions (e.g., see "Add a folder to PYTHONPATH variable (needed for OpenSim 4.2)").

**Comment by Cynantares** [comment]
> Does the example in the README.md file on GitHub work ([here](https://github.com/opensim-org/opensim-core#simple-example), under "Simple example", expand the "Python" section below the C++ code)? This would rule out any specific issues with the code above. Also, [the "Scripting in Python" page in the documentation](https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+in+Python) has some suggestions (e.g., see "Add a folder to PYTHONPATH variable (needed for OpenSim 4.2)").

The example works. But I can't see what's wrong in my code :(

**Comment by tkuchida** [comment]
Please try deleting the "r" after the "(" on line 6:
```
model = opensim.Model(r'C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\arm2dof6musc.osim')
```
Please also see the examples. For instance, most use `import opensim as osim`, not `import osim` (I don't think `import osim` is doing anything). In the future, please use the [User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91) for debugging questions; GitHub is used to track development tasks.

**Comment by Cynantares** [comment]
> Please try deleting the "r" after the "(" on line 6:
> 
> ```
> model = opensim.Model(r'C:\Users\fxgcy\PycharmProjects\OpenSim Random Activations\arm2dof6musc.osim')
> ```
> 
> Please also see the examples. For instance, most use `import opensim as osim`, not `import osim` (I don't think `import osim` is doing anything). In the future, please use the [User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91) for debugging questions; GitHub is used to track development tasks.

By deleting the "r" the path will be incomplete because the backlash will be seen as an escape character. And I tried to use import opensim as osim but the error still exists. 
Thank you !!! I'll use the User's Forum then.
