### ISSUE TITLE
Enable Markdown support in Doxygen

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#305]
By default Doxygen supports Markdown syntax for comments, which is very nice. However, we have that [disabled at the moment](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/doc/Doxyfile.in#L263) due to a bug in Doxygen 1.8.5 and earlier that made it mess up our formatting. However, that is fixed in 1.8.6. Once we can require 1.8.6 for doxygen (currently at 1.8.8), we can re-enable Markdown. Can we do that now?

See simbody/simbody#314.

**Comment by jimmyDunne** [comment]
Doxygen 1.8.6 through 1.8.9.1 all seem to work well and without incident. 
The documentation still looks fine and the Markdown formatted text got processed correctly. There may be instances where an incorrect interpretation of old formatting occurs, but we will just need to be mindful of it and correct when we see it. .

**Comment by sherm1** [comment]
Fixed by PR #306.
