### ISSUE TITLE
Several small errors for the OpenSense Python script in OpenSim 4.3 Beta

### ISSUE THREAD

**Issue by Allwillcome** [opensim-org/opensim-core#3050]
- TRUE should be true; 
- pi should be called first before use; `import math` `pi = math.pi`
- Vector3 should be written into `osim.Vector3` , Not Vector3
`sensor_to_opensim_rotations = Vec3(-pi/2, 0, 0);# The rotation of IMU data to the OpenSim world frame`
When I guess the cause of these mistakes, Python's script changes directly from the MATLAB script because these errors are different in language syntax. This will happen to people who are not familiar with programs. If the next time you publish the Python script, you can find these problems first.

**Comment by aymanhab** [comment]
Thanks for reporting, I'll submit a fix. Please keep reporting any issues with Python scripts here so we can continue to fix/improve or open a PR with the fixes and we'll review

**Comment by Allwillcome** [comment]
> Thanks for reporting, I'll submit a fix. Please keep reporting any issues with Python scripts here so we can continue to fix/improve or open a PR with the fixes and we'll review

Ok, Thanks for your effort ! OpenSim is great!
