### ISSUE TITLE
New Moco Goal to minimize/maximize model's kinetic & potential energy.

### ISSUE THREAD

**Issue by DDavis-Biomech** [opensim-org/opensim-core#3055]
Hi all,

I used examplePrototypeCustomGoal.m to write a goal which calculates a model's final potential and kinetic energy, but I'm not well versed in C++ and was curious if it could be made into a plugin and eventual custom goal? In the zip file 'goalZip', I've included the osim model, and matlab code 'prototypeCustomGoal.m.' The code currently opens the model and evaluates the kinetic and potential energy of a guess solution (generated with solver.createGuess()). This is my first Issue, so if I need to change anything or submit elsewhere please let me know.

Thanks so much for your help,
Danny
[goalZip.zip](https://github.com/opensim-org/opensim-core/files/6926599/goalZip.zip)

**Comment by nickbianco** [comment]
Hi @DDavis-Biomech, I haven't looked over your MocoGoal prototype yet, but my instinct to address this is to make some improvements to MocoOutputGoal as outline in #3061. Take a look at that issue and the current MocoOutputGoal to see if that would cover your needs.

**Comment by DDavis-Biomech** [comment]
Hi @nickbianco, thanks for getting back to me. My aim is to work with the end value of the output (like enabling MocoOutputGoal to work in endpoint constraint mode), so #3061 doesn't expressly address this issue.

**Comment by nickbianco** [comment]
I see -- this functionality could be added as an option to `MocoOutputGoal` or easily implemented in a separate goal (e.g., `MocoFinalOutputGoal`).

**Comment by DDavis-Biomech** [comment]
Definitely! Please let me know if I need to change anything in my custom goal or if I should instead wait for these options/goals to be added. Thanks for your help!

**Comment by nickbianco** [comment]
@DDavis-Biomech, the recently added `MocoInitialOutputGoal` and `MocoFinalOutputGoal` now make it possible to minimize a model's initial/final potential energy, so I am going to close this issue. Give those a try and let me know if it does not fit your needs.
