### ISSUE TITLE
Possible typo in AbstractTool Class (setModelFilename)

### ISSUE THREAD

**Issue by SepehrRamezani** [opensim-org/opensim-core#3060]
When I tired to use `setModelFilename()` under `AbsrtactTool` and `DynamicsTool` classes, I figured out they have different spelling. 
for example for inverse dynamics it would be `InverseDynamics.setModelFileName` and for CMC is `CMCTool.setModelFilename`
I think  `setModelFilename()` under `AbsrtactTool` need to be  `setModelFileName()` (Capital "N" for name)
Just wanted to point it out, not sure how much it's important.

**Comment by aymanhab** [comment]
Thanks for reporting @SepehrRamezani, in reality the two tools have totally different class hierarchy so the difference in naming while unfortunate is not bug (where a wrong function is called). Will leave this open as a reminder for us to consider a cleanup in the future but noting that API changes may break users' code so must be done sparingly.
