### ISSUE TITLE
Can't get Report orientation erros in OpenSense

### ISSUE THREAD

**Issue by Allwillcome** [opensim-org/opensim-core#3062]
I tried changing false to true in the XML, checked the control panel to `report orientation errors`, and even created an Ikresulat file, but the output did not contain `Report orientation erros`.

All operations are based on Opensense example documents——Models\Rajagopal_OpenSense. 

- system：windows system 
- systerm version：10.0.19043
- OpenSimVersion=4.3-2021-07-13-51ee73d
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<OpenSimDocument Version="40000">
	<IMUInverseKinematicsTool>
		<!--Name of the directory where results are written. Be default this is the directory in which the setup file is be  executed.-->
		<results_directory>IKResults</results_directory>
		<!--The time range for the study.-->
		<time_range>10.5 17</time_range>
		<!--Name of the resulting inverse kinematics motion (.mot) file.-->
		<output_motion_file>walking_motion.sto</output_motion_file>
		<!--Flag (true or false) indicating whether or not to report errors from the inverse kinematics solution. Default is true.-->
		<report_errors>true</report_errors>
		<!--Space fixed Euler angles (XYZ order) from IMU Space to OpenSim. Default to (0, 0, 0).-->
		<sensor_to_opensim_rotations>-1.5707963267948966 0 0</sensor_to_opensim_rotations>
		<!--Name/path to a .sto file of sensor frame orientations as quaternions.-->
		<orientations_file>walking_orientations.sto</orientations_file>
	</IMUInverseKinematicsTool>
</OpenSimDocument>
```
![image](https://user-images.githubusercontent.com/35840764/129658277-fc53a3ca-0a15-44ea-822e-1d32d604e179.png)
Looking forward to your reply！

**Comment by aymanhab** [comment]
Thanks for reporting @Allwillcome Please check the artifact of the PR here 
https://github.com/opensim-org/opensim-gui/pull/1312 
to verify that the issue has been fixed. Thank you

**Comment by Allwillcome** [comment]
Yeah，I want to verify that the issue，but I don't know how to verify it. I can't find the release after PR.  Need I download the GUI source code and build it on my computer?

**Comment by aymanhab** [comment]
Please check the nightly build on ci, available at this link: 
https://github.com/opensim-org/opensim-gui/actions/runs/1140297823

Thank you

**Comment by Allwillcome** [comment]
I succeeded to get the `walking_motion.sto_orientationErrors.sto`  after checking the control panel to report orientation errors, 
But when I only tried changing false to true in the XML, I failed.
Ps, the filename of walking_motion.sto_orientationErrors.sto The file name has more .sto.
Thank you！

**Comment by aymanhab** [comment]
Thanks @Allwillcome for sending over the files. I recreated the ik setup from your files and it ran to completion even though I don't know if the motion is correct (considering that you have IMUs on one leg only). It's great that you have scripts to convert from one XSens format to the one we use in OpenSense, if you're willing to donate these to help the community let me know and I'll setup a mechanism for sharing so that you get proper credit and the community can benefit.

**Comment by Allwillcome** [comment]
Thank you for testing my files, and if you can run my data successfully on your computer as I configured it, then it’s not OpenSim, it’s probably my own computer configuration.
I’m so excited to share my code, to contribute to the OpenSim open source code, to do my part, I Can’t sleep.
There are a few problems with the current code, though, and I’ve tried to make some changes:
XDOT has two modes, one is real-time storage, which uses quaternions to store joint angle information. The other is offline storage, which uses Euler angles to store data in a slightly different code format that converts to a rotation matrix.
In addition, I made comments in English to help more people understand the code.
I have two questions about my own code that I’m not sure about, and I need your help.
Xsens Dot only has free accelaration data, and I default free accelaration data to accelaration data. But in the calculation of joint angle in OpenSim, the rotation matrix is mainly involved in the calculation, which has little effect on the result, right?
I simulated IMU Data to add the following attribute information to the XDOT Data, otherwise an error would be reported
> RuntimeError: std::exception in 'OpenSim::DataAdapter::OutputTables OpenSim::DataAdapter::read(std::string const &) const': Table does not have metadata for 'header'.
Thrown at XsensDataReader.cpp:94 in extendRead().


What does the header here mean?

**Comment by Allwillcome** [comment]
> Thanks @Allwillcome for sending over the files. I recreated the ik setup from your files and it ran to completion even though I don't know if the motion is correct (considering that you have IMUs on one leg only). It's great that you have scripts to convert from one XSens format to the one we use in OpenSense, if you're willing to donate these to help the community let me know and I'll setup a mechanism for sharing so that you get proper credit and the community can benefit.

Hello，I have put my python script in github in https://github.com/Allwillcome/XsensDot2Mtw4OpenSense ，I hope it can help more people，I still haven't implemented the XSens Dot  offline mode conversion. I'll keep trying. I hope others will share their code
