### ISSUE TITLE
Feature request: Adjust bodies' mass after RRA

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3079]
Dear Experts

I see that RRA reports the "Recommended mass adjustments" for each segment (body), but it generates a model without these modifications and extra work needed by users to change them (whether manually or by a script). It would be great if the setup file has a Flag (true or false) specifying whether adjust the mass of all bodies or not. 

Regards,
Mohammadreza

**Comment by jenhicks** [comment]
Closing as this is a duplicate.
