### ISSUE TITLE
Method calcInextensibleTendonActiveFiberForce marked as deprecated but still in use

### ISSUE THREAD

**Issue by spahrm** [opensim-org/opensim-core#3082]
Hello this is my first issue for opensim,

I found some marking in the code which is for me a bit unclear and led to confusion:
The method `calcInextensibleTendonActiveFiberForce` is implemented in all Muscle models of OpenSim. In the three, (in my opinion) mostly used models (`Millard2012EquilibriumMuscle`, `Millard2012AccelerationMuscle` and `Thelen2003Muscle`) this method is labeled as deprecated within the code. 
For people (like me) who want to create new muscle models within OpenSim it seems like this method is not worth implementing. 
If one does not implement this method in its muscle model, there is also no error.
Unfortunately this method is still in use and called within the `StaticOptimizationTarget.cpp` class making Static Optimization simulations not possible. 

It would be very helpful especially for new users and muscle model developers to mark this function not as deprecated anymore in the specific muscle models.

Best,
Mike

**Comment by tkuchida** [comment]
Hi Mike- Welcome! :zebra: I don't see where `calcInextensibleTendonActiveFiberForce()` is labelled as deprecated… are you referring to the `ActivationFiberLengthMuscle_Deprecated` class?

**Comment by spahrm** [comment]
Hello @tkuchida,

thanks for the fast reply. I'm referring for example to the class `Millard2012EquilibriumMuscle`. Here inside the `.cpp` file the multiple methods are inside the deprecated section: 
https://github.com/opensim-org/opensim-core/blob/96257e9449d9ac430bbb54e56cd13aaebeee1242/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1659-L1873

The same goes for the `.h` file:
https://github.com/opensim-org/opensim-core/blob/96257e9449d9ac430bbb54e56cd13aaebeee1242/OpenSim/Actuators/Millard2012EquilibriumMuscle.h#L445-L484

Thanks for looking into this.
