### ISSUE TITLE
add data_source_name to TableMetaData

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3086]
Hi,

I created a force file using `STOFileAdapter`. I also added the 'DataRate', 'nRows', 'nColumns' and to the table as meta data before writing. In GUI (e.g ID tool), when I select this file as force date for External Loads and assign columns to each foot, I get this in messenger:

ExternalForce::left Data source being set to DataRate=1080
ExternalForce::right Data source being set to DataRate=1080

It seems that OpenSim selects the first line of the force file as `data_source_name` and in this case "DataRate=1080" was set. Is there function to add the name only (string) to TableMetaData? I couldn't find any in API.

`addTableMetaDataString` needs "string" and "key", it adds "=" between them automatically and cannot be used for name only (string only).

Regards,
Mohammadreza

**Comment by jenhicks** [comment]
Please post questions over on our user forum.

**Comment by tkuchida** [comment]
> Hi, TimeSeriesTable doesn't have any method to add name to the file.

I thought this was possible (at least at some point)… perhaps try setting the table's metadata? There's an example in [testDataTable.cpp#L141](https://github.com/opensim-org/opensim-core/blob/a67074f3e87a96c30c2480202ce7a21a3e72cb74/OpenSim/Common/Test/testDataTable.cpp#L141).

**Comment by mrrezaie** [comment]
Thank you, `addTableMetaDataString` requires one `key` and one `value` and it puts `=` between them. Actually it's not bad:
![image](https://github.com/opensim-org/opensim-core/assets/38867713/1461cb95-700a-448d-a2d1-188a06e0f820)
If you create another decorator for `addTableMetaDataString` with only one argument, it will be possible to add comment to the file as well as the name, the same as current motion/storage files:
![image](https://github.com/opensim-org/opensim-core/assets/38867713/a98820c4-8428-4b41-8c4e-71397ab9211e)
