### ISSUE TITLE
MATLAB error: No constructor 'org.opensim.modeling.PiecewiseConstantFunction' with matching signature found.

### ISSUE THREAD

**Issue by 1sabel4** [opensim-org/opensim-core#3090]
Hi, is it possible to script the 'Millard2012EquilibriumMuscle' with a function that is not the StepFunctio? I am trying to do it with the PiecewiseConstantFunction, but when i run the code, it shows 
`'No constructor 'org.opensim.modeling.PiecewiseConstantFunction' with matching signature found.'`

**Comment by 1sabel4** [comment]
Hi, I defined `biceps` above what I sent, and it still does not work. The error keeps showing in this part
`brain.prescribeControlForActuator('biceps',...
                                   PiecewiseConstantFunction(temp_lim_min_u, tempo_max_u, min_u, max_u));`

**Comment by tkuchida** [comment]
Please see the example I linked to in my previous post.

**Comment by 1sabel4** [comment]
I am trying to understand it. Thank you :)
