### ISSUE TITLE
Issues with marker tracking using MocoTrack

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3094]
Two different users posted on the forum ([here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=1815&t=13959&p=40371&start=0&view=) and [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=1815&t=14007&p=0&start=0&view=&sid=cde0446c29c788167532a3fd23274058)) stating that they're having issues solving marker tracking problems with MocoTrack. 

We should re-test these examples to make sure nothing is broken. Probably worth re-testing anyway considering that we fixed the MarkersReference issue recently too.

@jenhicks is it too late to add this to the 4.4 milestone?

**Comment by BiboyLin** [comment]
Because some functions like **OrientationsReference** , **InverseKinematicsSolver** re-refer to a new one, the Opensense code is not working too.

**Comment by nickbianco** [comment]
@BiboyLin, could you clarify how the OpenSense issues are related to this one? Is it something to do with the MarkersReference changes?

**Comment by aymanhab** [comment]
@BiboyLin If there're specific API calls that are not working please add a snippet to the test case involving MocoMakerTrackingGoal so that we can fix and make sure it doesn't break moving forward.

**Comment by BiboyLin** [comment]
> @BiboyLin, could you clarify how the OpenSense issues are related to this one? Is it something to do with the MarkersReference changes?
Here is the IK part of Opensense, the **MarkersReference** is not useful but  **InverseKinematicsSolver** refer to the new one:
```
 # Initialize simulation
        quatTable = osim.TimeSeriesTableQuaternion(sto_filename)
        orientationsData = osim.OpenSenseUtilities.convertQuaternionsToRotations(
            quatTable)
        oRefs = osim.OrientationsReference(orientationsData)
        init_state = model.initSystem()
        mRefs = osim.MarkersReference()
        coordinateReferences = osim.SimTKArrayCoordinateReference()
        model.initSystem()
        s0 = init_state
	# BUG here
        ikSolver = osim.InverseKinematicsSolver(
            model, mRefs, oRefs, coordinateReferences, np.float64(constraint_var))
	# Changing to this, it will go but got wrong at
        # ikSolver = osim.InverseKinematicsSolver(model, mRefs, coordinateReferences, constraint_var)
        ikSolver.setAccuracy = accuracy
        s0.setTime(0.)
        ikSolver.assemble(s0)
        print("Initialization of Model Simulation Completed!")
```

I think **InverseKinematicsSolver** is the API got problem as the #3017 
![image.png](assets/image-20211129150229-mv0u196.png)


I will try to test your newest version, and try my best to provide a python script after I get familiar with Moco. @aymanhab

Thank you for your work again！

**Comment by nickbianco** [comment]
@carmichaelong I've isolated the issue to MocoTrack. Marker tracking works fine if you add a `MocoMarkerTrackingGoal` to a problem directly.

**Comment by nickbianco** [comment]
The issue is related to filtering the marker data when using `MocoTrack::setMarkersReferenceFromTRC()`. A quick fix would be to remove filtering as an option.

**Comment by hwarner** [comment]
@nickbianco I have been following this conversation and doing my own testing. I would like to suggest that the issue is not the filtering within MocoTrack::setMarkersReferenceFromTRC() but the scaling from millimeters to meters.

**Comment by nickbianco** [comment]
Hi @hwarner, did you test this directly or is this just a suggestion? I tried testing these separately and it seemed like the filtering step was the culprit, not the scaling. (The scaling can be removed anyway, since the MarkersReference class handles it automatically.)

**Comment by nickbianco** [comment]
Ah okay, thanks for the clarification. Let me try to reproduce on my own. I thought I had the opposite results but maybe I flipped them in my head -- totally possible, as I did it fairly quickly.

**Comment by nickbianco** [comment]
Just re-tested and confirmed @hwarner's results. Good catch! I must have flipped the results in my head. This is much better, I was wondering why filtering was causing the problem, it didn't seem likely. I think the real issue is that I was scaling the marker data and then it as being scaled again through the MarkersReference class.
