### ISSUE TITLE
How to get the value of rotation and transform of Frame via Python API

### ISSUE THREAD

**Issue by hwy1992129** [opensim-org/opensim-core#3102]
I think I can get the Transform and Rotation from the member functions, but I don't know how to print the value and convert it into numpy array.
[Opensim API 4.3 Frame](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Frame.html#a55ff36184aa8e8ff36b94a42c24f8a97)
I use the functions like getRotationInGround(), getTransformInGround().
getRotationInGround() returns [SimTK::Rotation](https://simbody.github.io/simbody-3.6-doxygen/api/classSimTK_1_1Rotation__.html)
getTransformInGround() returns [SimTK::Transform](https://simtk.org/api_docs/molmodel/api_docs22/Simbody/html/classSimTK_1_1Transform__.html)
I also use asMat34(), asMat33()... I can't figure out how to get the numpy array from the Transform class and Rotation class..................
I can't even print the value in the console.........

**Comment by aymanhab** [comment]
Since these are not issues but questions, they belong to the user forum so others can benefit. Please post there. Thank you
