### ISSUE TITLE
AddStateVariable not in Python API

### ISSUE THREAD

**Issue by chalgand** [opensim-org/opensim-core#3104]
We want to take over the Afferent project ( https://simtk.org/projects/afferents OpenSim 3.3 compatible ) but OpenSim has evolved and we have decided to recode it in Python. Unfortunately the AddStateVariable method ( https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L2406 ) is missing in the Python API. We would very much like this method to be integrated with Python wrapping. Is this a mower difficulty ? We are happy to work on helping you bring this option to the Python API/ Could you help us with this issue ?

**Comment by aymanhab** [comment]
@chalgand The reason these methods are not exposed to the Python API is that these are not public methods in the Component class/interface which implies that they should not be called from an arbitrary context but from subclasses of Component. What you can do is split your work into C++ side that has access to protected methods and a python side. If you provide more context about what the classes/project is doing we maybe able to suggest other solutions/workarounds.

**Comment by jenhicks** [comment]
Please let us know if you have updates and open any issues as relevant.
