### ISSUE TITLE
ScaleTool: loading model or market set file can fail if specified as absolute paths

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3109]
In MATLAB (also in C++):
1. if the model file in the setup file is given as an absolute path (e.g., `C:\project\model.osim`)
2. AND the ScaleTool object is constructed from a setup file using an absolute or relative path, either of the following:
 `scale = ScaleTool("C:\project\setup_scale.xml")`
`scale = ScaleTool("project\setup_scale.xml")`
3. Then I get the error that no model is specified.

If the setup file is in the same folder as the working directory (e.g., I choose the working directory to be where the setup file is and use `scale = ScaleTool("setup_scale.xml")`), then it runs correctly.

If the model file in the setup file is given as a relative path (e.g., the model file is in the same directory as the setup file, and specified as `model.osim` , then you can construct the ScaleTool in any way (absolute, relative, etc) and it runs fine.

Also, when looking through the code to fix, the marker set file also looked to susceptible to the same problem.

**Comment by aymanhab** [comment]
If this was verified by others in release/master build the issue can be moved along
