### ISSUE TITLE
Adding display geometry to model results in EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3126]
In the Moco example [exampleTracking.cpp](https://github.com/opensim-org/opensim-core/blob/48ba9a0792c30b66bb2b97081f2546d1f627c2bc/OpenSim/Examples/Moco/exampleTracking/exampleTracking.cpp#L83), adding the display geometry results in a EXC_BAD_ACCESS when trying to build the model.

The error occurs [here](https://github.com/opensim-org/opensim-core/blob/48ba9a0792c30b66bb2b97081f2546d1f627c2bc/OpenSim/Common/Component.h#L3378), during when the Socket owned by the PhysicalOffsetFrame `b0_center` tries to establish the Socket connection with body `b0`. Specifically, the error seems to occur at `connecteePath.toString()`, but I'm not sure why.

**Comment by aymanhab** [comment]
@nickbianco is this reproducing in existing code already or when you add a snippet, if the latter can you include the offending line(s), thank you

**Comment by nickbianco** [comment]
It's reproduceable in the existing code, at least on my Mac (macOS Monterey).

**Comment by aymanhab** [comment]
Didn't produce for me in Debug build on Windows but I'll step through the
code anyway to see if something stands out as suspect.

**Comment by adamkewley** [comment]
@nickbianco / @aymanhab did either of you get to the bottom of this one? Any time I see potentially a bug that may be caused by `ComponentPath` I get nervous :D

**Comment by nickbianco** [comment]
Just re-tested this on a recent master build without issue. I can't remember what build I was using when posting this issue, it might have been some test build I was working on and not master. Considering this and Ayman's lack of issues when testing on Windows, I'm closing this issue.
