### ISSUE TITLE
CSVFileAdapter has no read method

### ISSUE THREAD

**Issue by itbellix** [opensim-org/opensim-core#3128]
Hi,
I am trying to use an instance of the class CSVFileAdapter to read data from a `.csv` file. However, it seems that the method `read()` is not exposed, while it should be according to the [API](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1CSVFileAdapter.html).

I have an installation of OpenSim4.3, and I am running Matlab 2021b.
The following script throws an error on the last line (I used it to make sure that the `read()` method was present for other `FileAdapter` subclasses):
```matlab
% example
import org.opensim.modeling.*

adapter_c3d = C3DFileAdapter();
tab_c3d = adapter_c3d.read('myfile.c3d');

adapter_trc = TRCFileAdapter();
tab_trc = adapter_trc.read('myfile.trc');

adapter_csv = CSVFileAdapter();
tab_csv = adapter_csv.read('file.csv');
```

The error is `Check for incorrect argument data type or missing argument in call to function 'read'.`, related to the `adapter_csv` object.

Is there something I am missing?

Kind regards,
Italo

**Comment by nickbianco** [comment]
Hi @itbellix, the `read()` method does exist (indicated by the error message), there's just an error with the input arguments (somehow). What does `methodsview CSVFileAdapter` show for the `read()` method? Perhaps there's an issue with the bindings.

**Comment by aymanhab** [comment]
A related question is what do you want to do with the result of read (which is a map of tables of arbitrary types and keys). Typically we construct properly typed tables from the file rather then read a random file and guess what types of data is in it as we don't have a rich interface to query/extract.

**Comment by itbellix** [comment]
Hi @nickbianco @aymanhab, thank you for your answers.

>  What does methodsview CSVFileAdapter show for the read() method? Perhaps there's an issue with the bindings.

In the following image you can see the output of `methodsview(CSVFileAdapter)`, running it from Matlab command window:

![image](https://user-images.githubusercontent.com/50029203/152125613-532be205-9e0c-43f5-9f4b-61c6fca547f9.png)

Some methods are listed, but `read()` is missing as well as other methods indicated in the API. Also, those are the only methods that are suggested when I press the Tab key, to get Matlab suggestions for autocompleting a call to the methods of a `CSVFileAdapter` object.

> A related question is what do you want to do with the result of read (which is a map of tables of arbitrary types and keys).

I am just attempting to use the method to import correctly some marker data (that I have saved as `.csv` files) into Matlab, to then convert them into `.trc` files that I can load and visualize in the OpenSim GUI. I ended up using the `readtable()` function provided by Matlab, in the meanwhile.

**Comment by nickbianco** [comment]
I don't see anything in the bindings that would explain why this class doesn't have `read()` but the others do.

However, what I think @aymanhab is alluding to is this: just read in your `.csv` file into a `TimeSeriesTableVec3` and then use the `TRCFileAdapter` write the table to a `.trc` file. If it's unclear how to do this let us know.

**Comment by jenhicks** [comment]
Please re-open if this is still causing issues.
