### ISSUE TITLE
Bodies initialized with zero inertia matrix in Readme.md file

### ISSUE THREAD

**Issue by samsuys** [opensim-org/opensim-core#3132]
In lines 12 and 13 of the sample C++ code in the Readme.md file, the humerus and radius are initialized with a zero inertia matrix. This is unrealistic and leads to errors if the model is used to be scaled.

While still not fully realistic, I believe the simplest solution would probably be to treat them as thin rods, which would give an inertia matrix of [1/3 0 1/3 0 0 0] given that the center of mass is placed at the end of the member.

**Comment by tkuchida** [comment]
:+1: Could also treat as [ellipsoids](https://en.wikipedia.org/wiki/Ellipsoid#Dynamical_properties), and perhaps adjust the definitions of the joints so the center of mass is in the middle of each body segment. 🐧
