### ISSUE TITLE
OpenSim::Frame::getRotationInGround() gives a `Rotation` object that doesn't have accessible methods in scripting

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3134]
From issue seen by @gurchiek

Steps to reproduce:
- Build a model (e.g., use `OpenSimCreateTugOfWarModel.m` in MATLAB, `build_simple_arm_model.py` in Python)
- Grab a body (e.g., `body = model.getBodySet().get(0)`)
- Use `body.getRotationInGround(state)` to get `SimTK::Rotation` object

In both MATLAB and Python, methods can't be called. `methodsview` from MATLAB shows the following
![image](https://user-images.githubusercontent.com/7455790/153053452-3a0b8c07-3ca6-4ff0-934f-248a8482e286.png)

Creating a `Rotation` object in MATLAB (e.g. `r = Rotation()`) and Python (e.g., `r = opensim.Rotation()`) both give an object that does have accessible methods.

**Comment by nickbianco** [comment]
As a temporary fix, does creating a copy of the `Rotation` returned from `getRotationInGround()` work?

**Comment by nickbianco** [comment]
Closing via #3135.
