### ISSUE TITLE
some weird error occured when I built opensim from source

### ISSUE THREAD

**Issue by 22strongestme** [opensim-org/opensim-core#3143]
I follow the readme document and was on the step below 
![image](https://user-images.githubusercontent.com/55016895/154841573-7cd2a615-c168-45b0-b334-22760914e31a.png)
then error happen
![Screenshot 2022-02-20 200252](https://user-images.githubusercontent.com/55016895/154841503-75e86d67-b4e8-4529-ae61-0c16ad93f55e.jpg)

**Comment by jenhicks** [comment]
Closing given readme updates; please re-open if issues remain.
