### ISSUE TITLE
Order of Object::registerType() calls erases previous distinct object

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#315]
The new predictive sim code that @carmichaelong and I are working on consists of an opensim plugin. In the RegisterTypes cpp file for the plugin, we have some code like this:

```cpp
Object::registerType(PGaitCMAESSolver());
...
Object::registerType(PGaitSimpleCMAESSolver());
```

If one calls `Object::getDefaultInstanceOfType("PGaitCMAESSolver")`, one gets back `nullptr`. If one then comments out `Object::registerType(PGaitSimpleCMAESSolver());`:

```cpp
Object::registerType(PGaitCMAESSolver());
...
//Object::registerType(PGaitSimpleCMAESSolver());
```

then `Object::getDefaultInstanceOfType("PGaitCMAESSolver")` returns a `PGaitCMAESSolver*`. I think the issue has something to do with [this area of code](https://github.com/opensim-org/opensim-core/blob/204cbb87131e55aa30f1df057fc57502dc230b58/OpenSim/Common/Object.cpp).

This only happens in visual studio (2013, 64bit). I tried to see if this was an issue with maps, but I don't think it is:

```cpp
std::map<<std::string, Object*> map;
map["PGaitCMAESSolver"] = new PGaitCMAESSolver();
map["PGaitSimpleCMAESSolver"] = new PGaitSimpleCMAESSolver();
std::map<std::string, Object*>::const_iterator it = map.find("PGaitCMAESSolver");
return it != map.end();
```

returns `true`.

I don't think we should bother to fix this bug, but I still wanted to create the issue since I ran into it.

**Comment by sherm1** [comment]
Any possibility both classes were accidentally given the same name strings?

**Comment by chrisdembia** [comment]
I wish. I didn't supply a name string myself anywhere. `Object` would have had to modify the name strings and I didn't see anything like that. I just double-checked my `OpenSim_DECLARE_CONCRETE_OBJECT` calls for both classes, and the arguments to those macros are correct. Also, my gut thinks that if name strings were the same anywhere, that would be an issue on linux too; there is no issue on linux.

**Comment by sherm1** [comment]
Oh, I didn't catch that it was working on Linux. Sounds like another ugly Visual Studio problem :-1:

**Comment by chrisdembia** [comment]
Completely ignore this issue. Almost everything above is false. It was my fault for not calling `LoadLibrary` for explicit linkage on windows.
