### ISSUE TITLE
macOS blocks .dylib files from downloaded GitHub artifacts

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3152]
Reported from @gurchiek

On macOS, when using a downloaded GitHub artifact, all .dylib files are blocked by macOS's Gatekeeper. This can be triggered by the two test lines:
```
import org.opensim.modeling.*
m = Model();
```
The second line will trigger Gatekeeper. At this point, you have to go through and click on each .dylib file to 

### Workaround:
After unzipping the .zip file to a folder, open the Terminal and use the following line to delete quarantine info recursively in the folder (replacing the last argument with the real path):
`sudo xattr -r -d com.apple.quarantine /path/to/opensim/folder`

Enter your password to complete this step.

Some other notes:
- This can be done even after running `configureOpenSim.m`
- If this is done while MATLAB is open, you may have to restart MATLAB for the changes to take effect (especially if you have triggered Gatekeeper in that session)

### Other notes
- This is not an issue with the distributions posted on SimTK
- While this is much less of an issue with the distributions on SimTK, it would save users a step if we correctly sign off on these official releases (https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution)

**Comment by nickbianco** [comment]
We had to use the same workaround when we posted intermediate Moco releases a couple years ago.

**Comment by jenhicks** [comment]
@carmichaelong Was this one resolved?
