### ISSUE TITLE
Document dependencies for Moco builds 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3156]
With the introduction of Moco we got a long list of dependencies introduced into OpenSim build, it is not clear what combinations of them work/make-sense or how to disable them altogether if we don't use Moco or want  a build without it to avoid the bloat.

- [] Eigen
- [] Colpack
- [] ipOpt
- [] casadi
- [] adolc

In addition, these dependencies are in a separate build/project from OpenSim which has two additional flags: OPENSIM_WITH_TROPTER, OPENSIM_WITH_CASADI

Trying the different combinations of mix and match is not manageable and doesn't seem efficient. One solution would be to have one OPENSIM_WITH_MOCO flag that controls other options but that doesn't solve the dependencies build mix/match issue.

**Comment by nickbianco** [comment]
I think an OPENSIM_WITH_MOCO flag is a great idea for this. In addition, I think we could talk about turning off the OPENSIM_WITH_TROPTER flag for most builds, since tropter isn't used by most users. The CasADi solver will get the most support going forward too.

**Comment by aymanhab** [comment]
Thanks @nickbianco I think the dependencies project should not expose the various Superbuild options, instead remove the above 5 superbuild options and have one Superbuild_Tropter_dependencies and another Superbuild_Casadi_dependencies or reuse the names OPENSIM_WITH_TROPTER, OPENSIM_WITH_CASADI where turning both off means no MOCO at all. At least the set of flags is managed internally rather than guessed by developers. Thoughts?

**Comment by nickbianco** [comment]
I'm fine with using OPENSIM_WITH_TROPTER and OPENSIM_WITH_CASADI to handle the Moco dependencies, makes ense to me.

**Comment by aymanhab** [comment]
The solution is implemented in https://github.com/opensim-org/opensim-core/pull/3173
