### ISSUE TITLE
Renaming default branch to `main`

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3158]
https://github.com/github/renaming

**Comment by carmichaelong** [comment]
Helpful info from the link

> Renaming a branch will:
> 
>     Re-target any open pull requests
>     Update any draft releases based on the branch
>     Move any branch protection rules that explicitly reference the old name
>     Update the branch used to build GitHub Pages, if applicable
>     Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
>     Show a notice to contributors who git push to the old branch
>     Redirect web requests for the old branch name to the new branch name
>     Return a "Moved Permanently" response in API requests for the old branch name
> 
> Learn more about [renaming a branch](https://docs.github.com/github/administering-a-repository/renaming-a-branch).

**Comment by aymanhab** [comment]
Thanks @carmichaelong
