### ISSUE TITLE
A cmake wrong in windows11

### ISSUE THREAD

**Issue by PANDIOR** [opensim-org/opensim-core#3161]
PS C:\opensim_build> cmake ..\opensim-core -G"Visual Studio 16 2019" -A x64  -DCMAKE_INSTALL_PREFIX="..\opensim_install" -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install" -DBUILD_JAVA_WRAPPING=ON -DBUILD_PYTHON_WRAPPING=ON -DWITH_BTK=ON
>>
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30141.0
-- The CXX compiler identification is MSVC 19.29.30141.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NOTICE: Make sure all OpenSim dependencies are built with the same CMAKE_BUILD_TYPE (Linux) or CONFIGURATION (Xcode/MSVC) as OpenSim to avoid mysterious runtime errors.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.35.1.windows.2")
-- Found Matlab: D:/Matlab/extern/include (found version "9.12") found components: MAIN_PROGRAM
CMake Warning at CMakeLists.txt:520 (message):
  Matlab found is 64-bit but C++ compiler chosen is 32-bit.  Matlab arch and
  OpenSim binaries arch have to be same.

-- Found Python3: C:/Python310/python.exe (found suitable version "3.10.2", minimum required is "3.6") found components: Interpreter Development NumPy Development.Module Development.Embed
Python3_FOUND:TRUE
Python3_VERSION:3.10.2
Python3_Development_FOUND:TRUE
Python3_LIBRARIES:C:/Python310/libs/python310.lib
Python3_Numpy_Include:C:/Python310/Lib/site-packages/numpy/core/include
Python3_Numpy_VERSION:1.22.3
-- Attempting to use dependencies from C:/opensim_dependencies_install
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at Vendors/tropter/CMakeLists.txt:74 (find_package):
  Could not find a package configuration file provided by "ColPack"
  (requested version 1.0.10) with any of the following names:

    ColPackConfig.cmake
    colpack-config.cmake

  Add the installation prefix of "ColPack" to CMAKE_PREFIX_PATH or set
  "ColPack_DIR" to a directory containing one of the above files.  If
  "ColPack" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "C:/opensim_build/CMakeFiles/CMakeOutput.log".
See also "C:/opensim_build/CMakeFiles/CMakeError.log".

----------------------------------------------------------------
I am very confused how to install the colpack in windows. 

[CMakeError.log](https://github.com/opensim-org/opensim-core/files/8259920/CMakeError.log)
[CMakeOutput.log](https://github.com/opensim-org/opensim-core/files/8259921/CMakeOutput.log)

**Comment by aymanhab** [comment]
Unless you need to build opensim-Moco you can disable the build of colpack, eigen, adolc, casadi and your build will go through. I see a message about using 32 bit compiler but not sure if that's related. We build nightly with VisualStudio 2019 so not sure if the Windows SDK version is an issue on Windows 11. Let me know.

**Comment by PANDIOR** [comment]
> 

Thank u, Here is some questions. 
1. Why you recomnmend python2 before installing. and what is real need is py3.
2. I follow your instruction for impatient, but i found this error that i don't have the colpack package with cmake. I don't know what is the difference between you and I. I also found lots of information about opensim installation on the Internet but no person have my error. That's very confused.
3. As for the command line for impatient, `-G"Visual Studio 16 2019 Win64"  ` is outdated. We need to use `-G"Visual Studio 16 2019" -A x64` in new version cmake for vs2019 or more latest.

For your interest,
1. The 32 bit complie is mingw32. I also don't know if it is related. 
2. My windows version is 10.0.22000 which is more than VS2019 windows 10 SDK. But I also try win11 sdk 11.0.22000 and it don't work.

By the way, I find I needn't install source code in my windows 11 for developing in matlab after one day's exploration. I am idiot.

**Comment by aymanhab** [comment]
I don't think we support mingw based builds, if there're no other issues or you can build with VisualStudio as recommended then please close. Thank you
