### ISSUE TITLE
How to make CMC work.

### ISSUE THREAD

**Issue by SietseAchterop** [opensim-org/opensim-core#3162]
L.S.

I have asked this before, also on the forum. I simplified as much as possible but the model still becomes unstable when using CMC.
The model and all other files can be found in this zip file:

[CMC_simple.zip](https://github.com/opensim-org/opensim-core/files/8260798/CMC_simple.zip)

It is simplified as much a possible, but you can recognize a torso and an upper arm that are sitting on a slider.
The osim-file (generated from bootbaan_CMC.py) and trajectory.mot says it all.
No muscles of forces.
After 0.25 seconds the arm starts spinning wildely in CMC, see the small video bb_simple.webm.

I assume that such a basic model is suppose to work, isn't it?
My guess is that there is something wrong with CMC, maybe that there are no muscles involved, or the separate PD controllers are to simple for a proper control? Playing with the PD values of the arm does not make any difference, with is strange in itself.
I am willing to try to get to the bottom of this, but I really need some help here.
I already read the articles from Thelen c.s. from 2003 and 2006 and looked into CMCTool.cpp.

Anyone with an idea no how to approach this?

 Thanks in advance, Sietse

**Comment by SietseAchterop** [comment]
In the end the problem was the sampling rate of the trajectory.
After changing it from 50 Hz to 100 Hz the instabilities were gone.
The issue can be close, thanks. Sietse.

**Comment by aymanhab** [comment]
Thanks @SietseAchterop if there's any clues messages that would have been helpful to embed in the code let us know so other users who get stuck are not stumped. All the best.

**Comment by SietseAchterop** [comment]
I assume that the sampling rate in CMC is determined by the trc-file. It is probably better to mention that more explicitly in the documentation, e.g. in "How CMC works".
(The sampling rate of the experimental data (if used) is not necessary the same as that needed for the used model)
