### ISSUE TITLE
conda compatibility issues

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3167]
@aymanhab 

Using this channel: https://anaconda.org/opensim-org/opensim

On MacOS, works with python=3.9 but not another version (e.g., python=3.7).
- Works with an environment whose python version is 3.9
```
conda create -n opensim-py39 python=3.9
conda activate opensim-py39
conda install -c opensim-org opensim
```
- Does not work with an environment that isn't python=3.9
```
conda create -n opensim-py37 python=3.7
conda activate opensim-py37
conda install -c opensim-org opensim
```
This pulls the incorrect build for opensim:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/7455790/158899320-5817b913-a96a-4af5-bf71-dd61aa36a6a7.png">
which fails on `import opensim`
<img width="520" alt="image" src="https://user-images.githubusercontent.com/7455790/158899414-54259126-1e87-4188-925b-f936a32069a1.png">

**Comment by aymanhab** [comment]
@moorepants @chrisdembia @kidzik or @adamkewley any idea why conda would pull the wrong build for the python version? What version conda did you use @carmichaelong so we're all in sync? Thanks.
There're builds for py37,39 on windows, mac, linux and the latter is consistent with google colab env
<script src="https://gist.github.com/aymanhab/7f3e73d507cdd8a72eb763cbe6d54b58.js"></script>

**Comment by carmichaelong** [comment]
conda 4.11.0 installed using the miniconda installer for python 3.9 (Miniconda3-py39_4.11.0-MacOSX-x86_64.sh)
