### ISSUE TITLE
cmake can't  build on windows

### ISSUE THREAD

**Issue by SamJalali** [opensim-org/opensim-core#3171]
hi 
I try to build openSim via Cmake but there were always an error on Cmake. I not very familiar with this staff could someone help me what to do in simple way :)
I sent an image of what show on Cmake when I configure source code. and also I install simbody like reedme and it worked, but i have some problems with installing OpenSim

![image](https://user-images.githubusercontent.com/102421672/160277995-70eb1d1c-3d07-474f-b758-67f4a8b44399.png)

**Comment by aymanhab** [comment]
Closing since this appears to be a non-bug, otherwise please re-open.
