### ISSUE TITLE
Errors while running CTest - Ubuntu 20.04

### ISSUE THREAD

**Issue by pablitodane** [opensim-org/opensim-core#3175]
Hi everyone,
I am following the instructions at this [link](https://github.com/opensim-org/opensim-core#on-ubuntu-using-unix-makefiles) to install opensim on linux, my OS is Ubuntu 20.04.

Everything goes smoothly till the point where I am actually supposed to run the tests.
In the terminal I type:

_$ ctest -j8_ 

and all I get is :

_98% tests passed, 2 tests failed out of 120_

_Total Test time (real) = 430.43 sec_

_The following tests FAILED:_
	_119 - python_tests (Failed)_
	_120 - python_examples (Failed)_
_Errors while running CTest_ 

I checked the python version, but it should be fine, since I am running the 3.8.

I tried following the instructions once more from the very beginning, but with no success. The problem remains the same.

What am I doing wrong?

I am not at all an expert, so please accept my apologies in case I'm doing something really silly.

Thanks a lot in advance for your help!

**Comment by Anhuaqiao** [comment]
Just happen to have the same issue. 
Did you check that whether you check the BUILD_PYTHON_WRAPPING while cmake?

**Comment by aymanhab** [comment]
The ci build script sets 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/opensim_dependencies_install/simbody/lib
to enable loading the shared libraries in the test environment. The script in full for all platforms is here:
https://github.com/opensim-org/opensim-core/blob/master/.github/workflows/continuous_integration.yml

**Comment by pablitodane** [comment]
Dear @aymanhab 

Thank you for the helpful response! I was able to fix this problem by appending the path (see below) to the simbody libraries to LD_LIBRARY_PATH in my bashrc file. I attempted to edit the line directly in the 3 continuous_integration.yml files that appear in the source directory, but this didn't work. Is there a way to fix this problem without modifying the bashrc file? It might happen in the future that I'm working with multiple OpenSim versions, in which case the bashrc solution will cause problems.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/paolo/github/OpenSimRoot/opensim_dependencies_install/simbody/lib

Yours,

Paolo

**Comment by aymanhab** [comment]
Dear @pablitodane It's important to distinguish between build environment and installed environment. The test cases run in build environment as such need the LD_LIBRARY_PATH to check the code runs without polluting the build machine. In normal usage, you either have one install as described here 
https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+in+Python
or you can use conda (e.g. https://anaconda.org/opensim-org/opensim) where all the libraries are packaged together and copied into environments, in which case you can have multiple versions installed in different environments. If there're no more issues to address here please close this issue. Thank you
