### ISSUE TITLE
McKibbenActuator is not a registered Object

### ISSUE THREAD

**Issue by nathantpickle** [opensim-org/opensim-core#3176]
I'm trying to create a model that contains a `McKibbenActuator`, but when I try to load the model in the OpenSim 4.3 GUI I get the following error:

`Object::newInstanceOfType(): object type 'McKibbenActuator' is not a registered Object! It will be ignored.`

I get the same error when trying to load the model programmatically using the Python API.

I did notice that `McKibbenActuator` is missing from RegisterTypes_osimActuators.cpp - perhaps that is why I get the error?

**Comment by aymanhab** [comment]
Thanks for reporting, follow up question: Do you need this in Matlab, or Python or both?

**Comment by nathantpickle** [comment]
Not a problem, thanks for looking into it. I only need this functionality in Python.

**Comment by aymanhab** [comment]
The type registration is actually only needed if you're serializing-to/deserializing-from files. The McKibben actuator is already exposed to python as evident on this jupyter notebook
https://colab.research.google.com/gist/aymanhab/402c9cc984046cfdeaf07a4721a78776/testopensimcolabpy37.ipynb

**Comment by nathantpickle** [comment]
Ok, good to know. I do need to be able to do file serialization/deserialization from Python rather than adding these actuators programmatically. I saw that there is an MR in progress with the fix - I'll test it out once the build artifact is ready.

**Comment by nathantpickle** [comment]
I tested the build and was able to load a `McKibbenActuator` from file successfully using the Python API.
