### ISSUE TITLE
Retire instructions on README 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3178]
These are stale and intimidating at the same time. 
Use links to ci, scripting and platform specific instructions on confluence maybe better

**Comment by carmichaelong** [comment]
- Reduce length by pointing to different pages on confluence
- Clarify how to correctly fill certain cmake options (e.g., swig executable, for java fill in `JAVA_INCLUDE_DIR` first, which can fill in the other entries, for java need JDK 8 which is confusing with instructions that note version 1.8)
- For each platform, first provide a set of instructions that is likely best for most users building from source (probably superbuild). Then perhaps have other pages for building in different ways (e.g., wanting to use some different version of a dependency that the user grabbed/built themselves)

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Wiki for opensim-core shows only instructions for windows, can you upload the instructions or scripts for the remaining platforms when you have a chance. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I have just created a new page with the updated instructions for Windows and Linux. I am going to test them right now just in case there is any problem with them.
