### ISSUE TITLE
Induced acceleration analysis

### ISSUE THREAD

**Issue by tnamayeshi** [opensim-org/opensim-core#3184]
I am having trouble validating the output of IAA toolbox. The contributions of 3 muscles seem to be incorrect. Gastrocnemius and soleus should be contributing the most to the vertical acceleration of the center of mass during the second half of the stance phase whereas IAA shows they peak at the first half of the stance phase.
Another problem is Gluteus Maximus's contribution to the vertical acceleration of the CoM should be positive, whereas the IAA toolbox shows it as negative! 
There are other minor issues with the magnitude as well. I tried this for 6 young healthy subjects and all results are similar.
 @aseth1 @aymanhab

**Comment by tnamayeshi** [comment]
I keep asking this question almost every year on forum, via email and now here. nobody seems to have an answer for it. 

Since there has been no publication with opensim muscle induced acceleration analysis (IAA to the CoM). Considering IAA toolbox used to have a bug and could not read the GRF data, shouldn't there be a model/example or something to prove this is working correctly? In some directions the results are opposite to Dorn's plugin's results!!!

**Comment by jenhicks** [comment]
Thank you for asking this question over on the user forum. Please add any additional details there. You could also apply for an upcoming office hours to potentially have a more in-depth discussion.
