### ISSUE TITLE
MATLAB constructors for InverseKinematicsSolver changed between 4.0 and 4.3

### ISSUE THREAD

**Issue by CVHammond** [opensim-org/opensim-core#3185]
We are updating our codebase to run on OpenSim 4.3/4.4. I am running into issues where the `InverseKinematicsSolver` doesn't have the reference to `MarkersReference` as registered types in MATLAB. The `MarkersReference` object is showing up as `org.opensim.modeling.SWIGTYPE_p_std__shared_ptrT_OpenSim__MarkersReference_t` and the `InverseKinematicsSolver` as a result throws an error when attempting to initialize.

Furthermore, do you have recommendations on how to debug the changes from 4.0 to 4.3 in anticipation of these functionality changes being implemented in 4.4 for public release? At this point, we can't switch to 4.3 for development because of bugs (such as the one listed above), but would like to push through the bugs to ensure the NMSM Pipeline works with 4.4 on release. Would you also be able to point me in the direction to a tutorial that shows how to use the GitHub Actions Artifacts in a Windows environment to test branches?

**Comment by aymanhab** [comment]
Any update on this issue @CVHammond ?

**Comment by CVHammond** [comment]
Sorry for the delayed response, I had family visiting. I have OpenSim's main branch running w/MATLAB functionality, so I should be able to pull any OpenSim branch and test it with our project. With that being said, what is the best way to communicate to you about changes in MATLAB signatures? We have extensively used `MarkerReference(java.lang.String)` in the JSP module, but it doesn't appear to be a signature any longer.

**Comment by aymanhab** [comment]
@CVHammond The change to include MarkerReference as argument was introduced in 2019, it's unlikely we have a full exhaustive log of what API were changed over the last 3 years, my suggestion would be to open issues for API changed that break code from 4.3 so that users can adapt. In this case building a MarkerWeightSet would be the appropriate change. Hope this helps and again if there's no more issue with the Solver interface we can close this issue. Thank you

**Comment by aymanhab** [comment]
@CVHammond I'll close this issue since the specific issue doesn't exist anymore. Please feel free to reopen or create new issues as needed.
