### ISSUE TITLE
simbody-visualizer not linked to libSimTKcommon.so.3.8 after superbuild install

### ISSUE THREAD

**Issue by fbailly** [opensim-org/opensim-core#3188]
Is that intended ?
Am I supposed to provide a custom path to my LD_LIBRARY_PATH env var for instance ?
Thanks !

**Comment by aymanhab** [comment]
Not sure what settings you used but the simbody-visualizer executable needs libSimTKcommon.so indeed, and unless they end up in the same folder you need LD_LIBRARY_PATH

**Comment by jenhicks** [comment]
Please re-open with additional info if issues still remain.
