### ISSUE TITLE
IKCoordinateTask is not fully accessible from Matlab API

### ISSUE THREAD

**Issue by itbellix** [opensim-org/opensim-core#3190]
Hi,
I would like to report what I think is a bug of the OpenSim API in Matlab. It appears not to be allowed to change some parts of a IK setup file from script: in particular, I am working with a setup file that includes several tasks (`IKMarkerTask` and `IKCoordinateTask`), of which I give a snapshot below:
```xml
<IKCoordinateTask name="scapula_abduction">
	<!--Whether or not this task will be used during inverse kinematics solve, default is true.-->
	<apply>false</apply>
	<!--Weight given to the task when solving inverse kinematics problems, default is 0.-->
	<weight>0</weight>
	<!--Indicates the source of the coordinate value for this task.  Possible values are default_value (use default value of coordinate, as specified in the model file, as the fixed target value), manual_value (use the value specified in the value property of this task as the fixed target value), or from_file (use the coordinate values from the coordinate data specified by the coordinates_file property).-->
	<value_type>manual_value</value_type>
	<!--This value will be used as the desired (or prescribed) coordinate value if value_type is set to manual_value.-->
	<value>0</value>
</IKCoordinateTask>
```
Using the following piece of code, I hope to modify some parts of this task (that is the i-th in the list of IK tasks):
```matlab
ikTool = InverseKinematicsTool(ikSetupFile);
ikTool_coordinate_task = ikTool.getIKTaskSet.get(i-1);

% setting the apply flag to 'true'
ikTool_coordinate_task.setApply(true);

% setting the weight
ikTool_coordinate_task.setWeight(1);
``` 

The provided script works, however no method is exposed to modify the other two fields of the `IKCoordinateTask`: `value_type` and `value`.  I can read their value (e.g. with `ikTool_coordinate_task.getPropertyByName('value_type')`) but I cannot find a way to modify them. 
It would be nice since I would benefit from changing the `value` field on the fly, in an automatic fashion.

I am usign Matlab R2021b and OpenSim4.3 under Windows 10.

Thank you!

**Comment by aymanhab** [comment]
Thanks for reporting @itbellix According to the latest codebase, the class has the required methods exposed:
https://github.com/opensim-org/opensim-gui/blob/master/Gui/opensim/modeling/src/org/opensim/modeling/IKCoordinateTask.java

When you do 'getIKTaskSet.get(i)' you get a base class reference, you'll need to safeDowncast it to an IKCoordinateTask similar to the top on this page
https://simtk-confluence.stanford.edu/display/OpenSim/Matlab+Resources+for+the+Advanced+User+Workshop

If that works please go ahead and close the issue, otherwise please refine to a more specific bug/issue. Thank you

**Comment by itbellix** [comment]
Thank you very much for the quick and precise answer @aymanhab!
It works, I will put here the exact lines of code in case it is useful for someone else in the future:

```matlab
ikTool = InverseKinematicsTool(ikSetupFile);
ikTool_coordinate_task = ikTool.getIKTaskSet.get(i-1);

% setting the apply flag to 'true'
ikTool_coordinate_task.setApply(true);

% setting the weight
ikTool_coordinate_task.setWeight(1);

% setting the property in value field to user_value
IKCoordinateTask.safeDownCast(ikTool_coordinate_task).setValue(user_value)
```

Thank you again!
