### ISSUE TITLE
Switching the order of coordinates in a joint changes the joint definition

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3191]
To reproduce with model Gait2354 (gait2354_simbody.osim): 

If you switch the order of the coordinates hip_flexion_r (lines 377-394) and hip_adduction_r (lines 395-412) in the CoordinateSet via modifying the XML file, and reload the model in the GUI, the coordinate slider for flexion controls adduction and the one for adduction controls flexion. 

Reported by Jennifer Maier.

**Comment by aymanhab** [comment]
Reproduced in local environment, investigating...

**Comment by aymanhab** [comment]
This is actually more prevalent than initially assumed, you can switch rotational with translational coordinates and motion-type is ignored. Identified the problematic call, testing a fix but worry about the scope considering prevalence.
