### ISSUE TITLE
Feature Request: Provide varying weights to different actuators in static optimization

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3194]
Hello,

I'm already aware of custom static optimization in MATLAB (https://github.com/stanfordnmbl/MatlabStaticOptimization), but it would be great if StaticOptimization in OpenSim API has a function to change the weight of the muscles\actuators in the following equation:
![image](https://user-images.githubusercontent.com/38867713/165882156-ebe1d695-ba32-414f-a13c-7e6c1568260e.png)
I suppose OpenSim already sets `c` (integer weighting constant) to 1 for all. 

This feature can be added to the GUI as well.

Ref:
Steele, K. M., Demers, M. S., Schwartz, M. H., & Delp, S. L. (2012). Compressive tibiofemoral force during crouch gait. Gait & posture, 35(4), 556–560. https://doi.org/10.1016/j.gaitpost.2011.11.023
https://simtk.org/projects/synergy
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=14556&p=0&start=0&view=&sid=ee032bc98ffe227345ae8a76a535470f

**Comment by jenhicks** [comment]
Closing given capabilities and work on OpenSim Moco
