### ISSUE TITLE
Feature Request: Moment-matching approach in Static Optimization

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3198]
Hi, Based on the documentations, StaticOptimizationTool in OpenSim currently matches the joint accelerations generated from muscle forces to joint accelerations computed from motion data (acceleration-matching approach). It would be great if you let users to choose moment-matching approach in StaticOptimizationTool too. This could be a property in the tool to whether or not use acceleration-matching approach (Default).

https://simtk-confluence.stanford.edu:8443/display/OpenSim/Custom+Static+Optimization+in+MATLAB#CustomStaticOptimizationinMATLAB-OpenSimImplementation

**Comment by jenhicks** [comment]
This is not on our radar given capabilities of OpenSim Moco.
