### ISSUE TITLE
Nested classes are not documented

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#320]
The documentation for HuntCrossleyForce::ContactParameters shows up in the documentation for HuntCrossleyForce. For example:

![image](https://cloud.githubusercontent.com/assets/846001/5732863/9325d0ba-9b4e-11e4-935a-2cb1624fe32c.png)

Related issue: #238. Right now, nested classes are not documented. #238 restores them but still might not fix this issue.

**Comment by jenhicks** [comment]
@chrisdembia Is this fixed?

**Comment by chrisdembia** [comment]
Yes!
