### ISSUE TITLE
Inverse Kinematics does seems to use the scaled model. 

### ISSUE THREAD

**Issue by roundangler** [opensim-org/opensim-core#3207]
I used got MOtoNMS to create a Hip joint virtual marker pair (L/R ) inserted to the static.trc file. This is used to in conjunction with the scale factor - measurement set in the 2nd tab of the scale tool menu. So that we can scale model accordingly. The scaling and static pose seems to go fine. When I go into Inverse Kinematics, seems that Opensim is not using the scaled model. The model lower limbs are too long. So it bending to walk with the pelvis tilting forward/backward - side to side. 

How can get Opensim - Inverse Kinematics to use the scaled model with the motion of the movement trc/mot files. As I am able to get the virtual HJC markers int the movement trc files, post static. Seems that Inverse kinematics has in the menu a tab to set the weightage for the virtual HJC markers if I have them.

Is there any way I can get round this problem ? Or there is something I can setup.

Many thanks.

**Comment by jenhicks** [comment]
Please post questions over on our user forum. Thanks!
https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
