### ISSUE TITLE
Update ezc3d Version in Conda Package

### ISSUE THREAD

**Issue by teliason** [opensim-org/opensim-core#3209]
There is an incompatibility issue when both opensim and ezc3d are installed in the same environment and the ezc3d version does not match what opensim was built with (https://github.com/pyomeca/ezc3d/issues/220).  

From my testing it looks like the current conda opensim package was built with ezc3d 1.4.7.  If possible it would be super helpful if the conda package could be updated with the current ezc3d version 1.4.9. 

Thank you for putting opensim together as a  conda package.  It has been great for streamlining integrating opensim into our python workflow.

**Comment by pariterre** [comment]
Hi @teliason, 
I can push an update to the opensim software, but it won't be available to the actual software until further release (unless you are building OpenSim for yourself). 

@aymanhab 
To my knowledge, there isn't any breaking changes from 1.4.7 to 1.4.9. If you want, I can push an update

**Comment by aymanhab** [comment]
If not breaking we can go to latest released version, we have no reason to
stay behind official released versions.

**Comment by teliason** [comment]
When I built OpenSim with ezc3d 1.4.9 everything worked as expected.  I don't think the new version should break anything on the OpenSim side but I have not extensively tested it.  @aymanhab that would be great if you could update to the latest, while I have it working by building OpenSim ourselves, the conda package is very convenient when sharing our pipeline internally and getting others who are less familiar with OpenSim set up.

**Comment by pariterre** [comment]
@teliason  That is actually on me, but it only consists in updating the commit number and the version number in the dependencies folder. I wanted to build it myself before, but did not have time to do so. Since you tell me that it does not produce error (which I am actually not surprised), I will simply push the modif and trust the merge test on GitHub :)

**Comment by aymanhab** [comment]
Conda package was published with ezc3d 1.5, thanks for the help @pariterre Closing
