### ISSUE TITLE
MuscleAnalysis producing empty moment arm files

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#321]
The option 'compute_moments' is unchecked by default. Yet (empty) moment arm files are generated for each coordinate. 

Can we either (a) check compute_moments by default or (b) not print files when unchecked?

**Comment by chrisdembia** [comment]
Related but distinct: #292

**Comment by chrisdembia** [comment]
See [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/MuscleAnalysis.cpp#L241) and [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/MuscleAnalysis.cpp#L779).
