### ISSUE TITLE
Q: Is it legal to copy-assign states to copy-constructed models?

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#3211]
I'm investigating a weird bug I have been wrestling with this afternoon. The context is that there's a feature in `opensim-creator` where a muscle plot is dynamically recomputed whenever the user changes (e.g.) a property. You can try it out by downloading a recent-ish release, right-click a muscle, `plot vs coordinate` or similar. An earlier version of the source code that does this is [here](https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/0.1.6/src/Widgets/ModelMusclePlotPanel.cpp#L379).

The feature requires sending an `OpenSim::Model` + `SimTK::State` across thread boundaries. For the sake of argument, you can imagine that `baseModel` in the example below is "some source model, probably from UI storage". The state assignment is necessary because there may be further modifications to UI's copy of the state (e.g. coordinate edits).

The following code snippet fails if `fixBug = false`, but passes if `fixBug = true`. The "bug" is that the first value produced by computing a moment arm on the model copy (`model`) produces an invalid value. Recomputing the moment arm a second time then produces a correct value, which then causes the assertion to fail.

Is the bug in the snippet that states can't be straightforwardly assigned to model copies? That is, is it *strictly* required that I go through the process of pulling out state names, match them on source+destination, map the indices, etc. (i.e. as required for reading `sto` files a model?). Is there a reason why `computeMomentArm`, which is `const` on all arguments and the `GeometryPath`, causes a mutation that then causes subsequent calls to work?

Full repro snippet (uses `arm26.osim`, fails if `fixBug = false` on OpenSim 4.3):

```c++
#include <OpenSim/Common/ComponentPath.h>
#include <OpenSim/Simulation/Model/Model.h>
#include <OpenSim/Simulation/Model/Muscle.h>
#include <OpenSim/Actuators/RegisterTypes_osimActuators.h>

#include <gtest/gtest.h>

#include <filesystem>

TEST(OpenSimModel, ProducesCorrectMomentArmOnFirstComputeCall)
{
	// ensure muscles are available
	RegisterTypes_osimActuators();

	// data sources
	std::filesystem::path modelPath{R"(C:\\Users\\adamk\\OneDrive\\Desktop\\opensim-creator\\resources\\models\\Arm26\\arm26.osim)"};
	OpenSim::ComponentPath coordinatePath = "/jointset/r_shoulder/r_shoulder_elev";
	OpenSim::ComponentPath musclePath = "/forceset/BIClong";

	// load osim into a base copy of the model
	OpenSim::Model baseModel{modelPath.string()};
	baseModel.buildSystem();
	baseModel.initializeState();
	baseModel.equilibrateMuscles(baseModel.updWorkingState());

	// copy-construct the model that's actually simulated
	OpenSim::Model model{baseModel};
	model.buildSystem();
	model.initializeState();
	model.updWorkingState() = baseModel.getWorkingState();  // is this technically illegal?

	// take a local copy of the state
	SimTK::State st = model.getWorkingState();

	// lookup components
	OpenSim::Coordinate const& coord = model.getComponent<OpenSim::Coordinate>(coordinatePath);
	OpenSim::Muscle const& musc = model.getComponent<OpenSim::Muscle>(musclePath);

	// setting `fixBug` to `true` makes this test pass
	if (bool fixBug = false)
	{
		musc.getGeometryPath().computeMomentArm(st, coord);
	}

	// compute two moment arms at one particular coordinate value
	coord.setLocked(st, false);
	double values[2];
	double newCoordVal = coord.getValue(st) + 0.01;  // just ensure the coord changes from default
	coord.setValue(st, newCoordVal);
	for (int i = 0; i < 2; ++i)
	{
		st.invalidateAllCacheAtOrAbove(SimTK::Stage::Instance);
		model.equilibrateMuscles(st);
		model.realizeDynamics(st);
		values[i] = musc.getGeometryPath().computeMomentArm(st, coord);
	}

	ASSERT_EQ(values[0], values[1]);
}
```

Example error:

```text
[----------] 1 test from OpenSimModel
[ RUN      ] OpenSimModel.ProducesCorrectMomentArmOnFirstComputeCall
[info] Updating Model file from 20303 to latest format...
[info] Loaded model arm26 from file C:\\Users\\adamk\\OneDrive\\Desktop\\opensim-creator\\resources\\models\\Arm26\\arm26.osim
[info] ControllerSet 'Controllers' was renamed and is being reset to 'controllerset'.
[info] ComponentSet 'MiscComponents' was renamed and is being reset to 'componentset'.
C:\Users\adamk\OneDrive\Desktop\opensim-creator\tests\TestOpenSim.cpp(58): error: Expected equality of these values:
  values[0]
    Which is: 0.0232791
  values[1]
    Which is: 0.021558
[  FAILED  ] OpenSimModel.ProducesCorrectMomentArmOnFirstComputeCall (35 ms)
```

**Comment by aymanhab** [comment]
@adamkewley My first impression is that this is illegal and that we make no promises as to the layout/traversal order of any internal structures, while the state maybe copied, the maps internal to the model may not be identical. My recollection is that we deal with these issues in the GUI by keeping two separate copies and using name lookup, which works on states from relatively distinct models (e.g. with/without muscles, external loads, as those created by various tools) It maybe possible to do what you want but I don't recall we've done it in our codebase. 🤷

**Comment by adamkewley** [comment]
Ah, thanks @aymanhab :) 

I'll write a routine that closely mirrors the GUI and/or tools (e.g.) and write a container (or similar) for safely throwing state data around (or use `Storage`). I have a fairly large amount of use-cases for moving/copying states around the UI and, given the other little bugs (pointer stuff, thread safety, etc.) it might be valuable to create a wrapper line `StateData`, `StateSequenceData`, or similar, where they just safely hold the state vars, rather than handling the edge-case stuff (cache vars, etc.)!

**Comment by aymanhab** [comment]
Thinking about it a bit more, and the fact that results after first point
are correct, I think you may only need to realize after making the copy of
the state since the cache is wiped out on copy. Maybe worth trying.
