### ISSUE TITLE
analyzeMocoTrajectory() is implemented incorrectly in the bindings

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3219]

**Comment by aymanhab** [comment]
Hi @nickbianco do you have a PR in the pipe for this or should I dig into it? Thanks

**Comment by nickbianco** [comment]
@aymanhab the fix is pretty simple, but I haven't gotten around to it yet. In the following lines, we need to replace `analyze<T>` with `analyzeMocoTrajectory<T>`:

https://github.com/opensim-org/opensim-core/blob/6c5e81551e2352b2c07a446615f692d5d326af97/Bindings/moco.i#L142-L144
