### ISSUE TITLE
OpenSimConfig.cmake assumes an install directory.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#323]
Right now, we have a mechanism for people who want to use OpenSim as a library for their own C++ project: OpenSimConfig.cmake.

However, this mechanism only works if OpenSim is installed in the location specified during the build process. This is fine for people building from source, b/c they know their install directory ahead of time (during building).

However, when we distribute OpenSim binaries as part of a release, we don't know where users will choose to install OpenSim (perhaps `C:/myApps/OpenSim`). I did not account for this when I created the OpenSimConfig.cmake. 

Therefore, we need an additional mechanism, likely a FindOpenSim.cmake file, that OpenSim users can use.

**Comment by chrisdembia** [comment]
Another option is that the OpenSim GUI installer can write the appropriate OpenSimConfig.cmake file once it knows where the user will install opensim.

**Comment by aymanhab** [comment]
@chrisdembia The GUI doesn't know where it's installed, it's the installer script.

**Comment by chrisdembia** [comment]
Ah thanks for clarifying.

**Comment by chrisdembia** [comment]
Aha! The OpenSimConfig.cmake file just shouldn't have the installation path in it. It should deduce the installation prefix from its OWN location using http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_CURRENT_LIST_FILE.html

**Comment by chrisdembia** [comment]
I've proposed a fix for this in simbody: https://github.com/simbody/simbody/pull/339
