### ISSUE TITLE
Enabled getCoordinatesInMultibodyTreeOrder

### ISSUE THREAD

**Issue by CVHammond** [opensim-org/opensim-core#3254]
We are trying to step through a `.mot` file and record information at each time point. Looking at how InverseDynamics achieves model positions, we are modifying the Q vector in `state.setQ(newVector)`. The issue is understanding which coordinate is associated with each position in the Q vector requires `model.getCoordinatesInMultibodyTreeOrder()`. Would it be possible to implement a version of that function call such that even just an `org.opensim.modeling.StringVector` is returned?

If not, what is the recommended way to put the model into a specific pose?

**Comment by tkuchida** [comment]
You can set positions and velocities using the [`Coordinate::setValue()`](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Coordinate.html#ae8cef6efdccd30cb8135f1f2e88d7c42) and [`Coordinate::setSpeedValue()`](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Coordinate.html#a4c8444829038c452d64d3fdd7a8febd3) methods. Please note the third argument to `Coordinate::setValue()`. 🦉

**Comment by CVHammond** [comment]
How do I get a mutable version of the coordinate of interest? `model.getCoordinateSet().get(coordName)` returns an immutable reference correct?

Example:
```
>> model.getCoordinateSet().get(1).setValue(state, 5)
>> model.getCoordinateSet().get(1).getValue(state)

ans =

    1.5708
```

**Comment by tkuchida** [comment]
My guess is that the Coordinate is an angle and it has a limit ("clamp") of 90 degrees = 1.5708 radians, or perhaps it is locked. You can turn off clamping and make sure it's unlocked:
```
coord = model.getCoordinateSet().get('coord_name')
coord.setClamped(state, False)
coord.setLocked(state, False)
coord.setValue(state, 5.0)
```
GitHub is generally used to report and track development of the software. Questions about using OpenSim are typically posted to the [OpenSim User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91).

**Comment by aymanhab** [comment]
No need for Coordinate to be non-const as the change of value only changes the state not the coordinate definition.
You may want to look into StateTrajectory class for help/usage

**Comment by jenhicks** [comment]
Please post additional questions over on the user forum. Thanks!
