### ISSUE TITLE
How To Disable Certain Dependencies If Not Using Opensim Moco

### ISSUE THREAD

**Issue by dpar21** [opensim-org/opensim-core#3272]
Hello, 

I am trying to build the latest opensim package for python via a docker image and am running into the following error: 

![Screen Shot 2022-07-29 at 5 16 14 PM](https://user-images.githubusercontent.com/37747637/181852526-8f53d242-93ff-4c2c-bfac-159b41c13c4a.png)

Is there a way to disable the dependencies I don't need since I am not using Opensim Moco? Specifically in Ubuntu. 

Thank you.

**Comment by aymanhab** [comment]
On opensim-core side.  Turn off both Opensim_with_tropter and opensim_with_casadi

**Comment by aymanhab** [comment]
If this worked @dpar21 please let us know so we can update the documentation/cmake instructions and close this issue.
@AlbertoCasasOrtiz Let's make sure this is documented in the build instructions on all platforms that you worked on. Thank you

**Comment by dpar21** [comment]
Yes, this worked! Thank you @aymanhab!

**Comment by dpar21** [comment]
Apologies, I did have one more issue when attempting to import opensim in python following only building Opensim without Moco:

![Screen Shot 2022-08-08 at 10 47 35 AM](https://user-images.githubusercontent.com/37747637/183458902-ec9cd36e-1ee7-4ee1-9fad-6a39d6124dd0.png)

Was wondering @aymanhab if this is happening because I have built Opensim without Moco functionality?

**Comment by dpar21** [comment]
FROM ubuntu AS builder

# MAINTAINER Christopher Dembia

ARG BRANCH=master

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula \
        select true | debconf-set-selections

# Set DEBIAN_FRONTEND to avoid interactive timezone prompt when installing
# packages.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        git \
        build-essential libtool autoconf \
        cmake \
        doxygen \
        gfortran \
        wget \
        pkg-config \
        libopenblas-dev \
        liblapack-dev \
        python3 python3-dev python3-numpy python3-scipy \
        python3-pip \
        python3-matplotlib \
        python3-setuptools \
        openjdk-18-jdk \
        ttf-mscorefonts-installer \
        swig4.0

ENV JAVA_HOME /usr/lib/jvm/java-18-openjdk-amd64/
RUN  echo $JAVA_HOME

# Matplotlib's default backend requires a DISPLAY / Xserver.
RUN mkdir -p ~/.config/matplotlib && \
    echo 'backend : Agg' >> ~/.config/matplotlib/matplotlibrc && \
    echo 'font.sans-serif : Arial, Helvetica, sans-serif' >> ~/.config/matplotlib/matplotlibrc

RUN git clone https://github.com/opensim-org/opensim-core.git /opensim-core \
        && cd /opensim-core \
        && git checkout 18481117fc692a4ec04723e749a7817c321e5cdb

RUN cd /opensim-core \
        && mkdir ../opensim_dependencies_build \
        && cd ../opensim_dependencies_build \
        && cmake ../opensim-core/dependencies \
            -DSUPERBUILD_ezc3d=on \
            -DOPENSIM_WITH_CASADI=off \
            -DOPENSIM_WITH_TROPTER=off \
            -DSUPERBUILD_casadi=off \
            -DSUPERBUILD_eigen=off \
            -DSUPERBUILD_colpack=off \
            -DSUPERBUILD_adolc=off \
        && make --jobs $(nproc) -i \
        # && echo "/opensim_dependencies_install/adol-c/lib64" >> /etc/ld.so.conf.d/opensim.conf \
        # && echo "/opensim_dependencies_install/ipopt/lib" >> /etc/ld.so.conf.d/opensim.conf \
        && ldconfig \
        && rm -r /opensim_dependencies_build

RUN cd / \
        && mkdir build \
        && cd build \
        && cmake ../opensim-core \
            -DOPENSIM_WITH_CASADI=off \
            -DOPENSIM_WITH_TROPTER=off \
            -DOPENSIM_DEPENDENCIES_DIR=/opensim_dependencies_install \
            -DBUILD_PYTHON_WRAPPING=on \
            -DBUILD_JAVA_WRAPPING=off \
            -DBUILD_TESTING=off \
            -DBUILD_EXAMPLES=on \
            -DOPENSIM_INSTALL_UNIX_FHS=off \
        && make --jobs $(nproc) install -i \
        && echo "/opensim-core-install/sdk/lib" >> /etc/ld.so.conf.d/opensim.conf \
        && echo "/opensim-core-install/sdk/Simbody/lib" >> /etc/ld.so.conf.d/opensim.conf \
        && ldconfig \
        && cd /opensim-core-install/sdk/Python && pip3 install . \
        && rm -r /build

  ^^ My Docker build for reference

**Comment by aymanhab** [comment]
Instead of building from scratch or using custom scripts, I suggest you use the official images published on dockerhub at 
https://hub.docker.com/repository/docker/stanfordnmbl/opensim-python
Both 4.4 and 4.4-with-moco tags are available. 
Please let us know if they work for you so we can create a robust repository of images for the whole community.

**Comment by dpar21** [comment]
Hi @aymanhab, I have been using a modified version of the docker image that is also on dockerhub, but the issue still persists that I am unable to import opensim in python due to an ImportError.

**Comment by aymanhab** [comment]
I would start from the image on dockerhub linked to above, test/verify it works out of the box, then gradually apply your changes. If something breaks you'll know what it is and you can tell us, at this point we can either fix/document or suggest a workaround/alternatives. Debugging a container in the dark is a bit hard especially when we didn't create it in the first place. I've seen these errors in other iterations of the container for a variety of reasons including using the wrong compilers/libraries/flags/python, Path/rpath/ld_library_path etc.

**Comment by dpar21** [comment]
Hi @aymanhab - I have copied the dockerfile exactly as what is seen on DockerHub but for some reason I am still getting the same error having to do with _simbody.so. I am not sure exactly what it is I am missing.

**Comment by aymanhab** [comment]
Can you download the image as is (stanfordnmbl/opensim-python:4.4) and run python3.8, import opensim ?
If not then we have a more fundamental issue to deal with since that's what docker is made for so we don't worry about different OS versions, python versions, PATH etc. all these are accounted for.

**Comment by dpar21** [comment]
Hi @aymanhab - I found the issue. I was utilizing a multi-stage docker build where the GNU Libc versions were mismatched. I was able to resolve the problem and am successfully able to import opensim! Thank you for your help!
