### ISSUE TITLE
Not easy to apply ExternalLoads if integrating directly with Manager (instead of ForwardTool).

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#328]
Right now, the Tools accept an ExternalLoads object, which is a set of force elements that the ExternalLoads object helps organize. The ExternalLoads object also adds functionality: allowing the use of an IK motion to modify where the ExternalForce is applied. The Tool (e.g, ForwardTool) is responsible for adding the ExternalLoads' force elements to the Model; see [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/AbstractTool.cpp#L558). What does one do if they want to use ExternalLoads with the Manager, without the ForwardTool? You can't "add" an ExternalLoads object to the Model.

Part of the issue is that ExternalForce does not have a serializable field for the sto file, so it really has trouble standing on its own.

I think this is somewhat low priority, and would perhaps be fixed by new components we create for the new component interface.

**Comment by sherm1** [comment]
Ajay says this will be moot in 4.0.
