### ISSUE TITLE
Replace macos-10.15 with  macos-11 or latest 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3289]
macos-10.15 will be retired in 12/22 on github actions

**Comment by carmichaelong** [comment]
@aymanhab also looks like MATLAB 2022b is discontinuing support for 10.15: https://www.mathworks.com/support/requirements/matlab-mac.html

**Comment by aymanhab** [comment]
PR in progress to add to ci PR #3295

**Comment by aymanhab** [comment]
Build succeeds with osx-11 but fails to load/run without library path setting, PR in the pipe
https://github.com/opensim-org/opensim-gui/pull/1389

**Comment by jenhicks** [comment]
Thanks for catching that!

**Comment by aymanhab** [comment]
Done a while ago, closing
