### ISSUE TITLE
How to set IMUs orientation weights for IK through Python scripting?

### ISSUE THREAD

**Issue by mluacnunes** [opensim-org/opensim-core#3298]
Hi,

I'm having difficulties in setting IMUs orientation weights while performing IK through Python scripting.  As far as understood, I should construct a XML file with the desired configurations and pass it as an input to the IMUInverseKinematicsTool class set_orientation_weights function. Can you share an example of XML file to define the IMUs orientation weights?

**Comment by jenhicks** [comment]
Please post questions over on our user forum. Thanks!
