### ISSUE TITLE
Segfault when opening an `osim` with unusual socket connections

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#3299]
Opening this modified `Rajagopal2015.osim` file:

- https://gist.github.com/adamkewley/153f60406472e14b14bde1f507d05fff

In OpenSim4.4 will trigger a segfault that causes the whole process to crash. "Whole process" can mean (e.g.) a scripting environment, GUI, or (non-forking) server process.

The file was created by:

1. Loading the original OpenSim3 `Rajagopal2015.osim` model
2. Re-saving it as an OpenSim4 model ([link](https://gist.github.com/adamkewley/ee34b2ba0adf2aec076382c6fe6ceec0))
3. Changing `/jointset/hip_r/socket_child_frame` from `femur_r_offset` to `/ground`

i.e. the diff is (between the OpenSim4 and segfaulting version):

```diff
3222c3222
<                                       <socket_child_frame>femur_r_offset</socket_child_frame>
---
>                                       <socket_child_frame>/ground</socket_child_frame>
```

Relevant parts of the backtrace:

- This line segfaults: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/SimbodyEngine/Body.cpp#L422
- `_slaves` looks invalid in a debugger, so the `Body` pointer has probably been mis-read
- The caller is: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/Model/Model.cpp#L844
- Probably whatever is looking up the body is mis-casting `Ground` as a `Body` or similar

The relevance of this bug is that it can be triggered from a file input (i.e. `osim`), and it makes the socket API potentially-segfaulting for any downstream code (e.g. scripts, OpenSim Creator's socket editor, etc.).

---

Bug initially identified in OpenSim Creator: https://github.com/ComputationalBiomechanicsLab/opensim-creator/issues/382 . I have manually confirmed that the bug also exists in OpenSim4.4 GUI by loading the above osim file in it.

**Comment by tkuchida** [comment]
> Probably whatever is looking up the body is mis-casting `Ground` as a `Body` or similar

Appears to be the case here at least: [Model.cpp#L899](https://github.com/opensim-org/opensim-core/blob/0e9fedc9039284fa94fe9d1cfbe1fc4d27cd0234/OpenSim/Simulation/Model/Model.cpp#L899) (`parent` will be of type `PhysicalFrame` but not necessarily `Body`… a similar assumption was likely made elsewhere).

**Comment by adamkewley** [comment]
A bare-minimum API repro would be:

```c++
OpenSim::Model m;
OpenSim::PhysicalFrame const& groundFrame = m.getGround();

auto pelvis = std::make_unique<OpenSim::Body>("pelvis", 1.0, SimTK::Vec3{}, SimTK::Inertia{});
OpenSim::PhysicalFrame const& pelvisFrame = *pelvis;
m.addBody(pelvis.release());

m.addJoint(new OpenSim::PinJoint{"ground_pelvis", groundFrame, pelvisFrame});
m.addJoint(new OpenSim::PinJoint{"pelvis_ground", pelvisFrame, groundFrame});

m.finalizeFromProperties();
m.finalizeConnections();  // segfaults
```

**Comment by adamkewley** [comment]
The segfault for this issue is now fixed. There is still an outstanding runtime exception, but that's kind of separate (because this bug only happens with unusual graph topologies and merely showing the exception error message is _probably_ enough to prompt an end-user to change something - even if the underlying graph maker thing is also a bug).

Thanks again @nickbianco
