### ISSUE TITLE
Linux: Build process killed by system

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3303]
When you build opensim-core on Linux, you can get this error:

`killed: signal terminated program cc1plus`

I got the error while building opensim-core on an Ubuntu 22.04 virtual machine with 8Gb of RAM and using 8 jobs (`-j8`) to build it. Other processes were consuming RAM too (e.g., web browser).

If you check the Linux kernel buffer with the command `sudo dmesg | grep cc1plus`, it shows the following line (among others):

`Out of memory: Killed process <process-number> (cc1plus)...`

This indicates that the process was killed by the system because it is consuming all of the virtual memory available.

A solution to this is to either increase the machine's memory or decrease the number of jobs used to build opensim-core. Turns out that using too many jobs increases memory usage.

**Comment by AlbertoCasasOrtiz** [comment]
A similar error appears in Debian:

`virtual memory exhausted: Cannot allocate memory`

**Comment by aymanhab** [comment]
In the past this was specific to bindings, does the problem happen without building the bindings?

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I haven't tried installing it without bindings, but every time this error appears is while building the bindings.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab In the build instructions, in the [troubleshooting section for Linux](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions#troubleshooting-1), I have described this error and included instructions to identify and solve this.

Should we close this issue?
