### ISSUE TITLE
3D model import

### ISSUE THREAD

**Issue by liminghaoaa** [opensim-org/opensim-core#3304]
![cfeb3db458ba004ebb37df86e206cef](https://user-images.githubusercontent.com/116700646/197929754-48fa2b63-81dd-4ca4-8860-d941d21b3f32.jpg)

**Comment by aymanhab** [comment]
Please provide the model and geometry files/folder and the version you're trying to use so that we can investigate, otherwise we'll close the issue as we have no way to reproduce and thus fix the issue.
