### ISSUE TITLE
On macOS 11+, `libcoinmumps` may incorrectly depend on `libgcc`

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3320]
@AlbertoCasasOrtiz 

Related PR: https://github.com/opensim-org/opensim-gui/pull/1387

With artifact `opensim-core-4.4.1-2022-08-25-41f28cb9a` and before:
```
dyld_info -dependents libcoinmumps.1.dylib            
libcoinmumps.1.dylib [x86_64]:
    -dependents:
        attributes     load path
                       @rpath/libcoinmetis.1.dylib
                       @rpath/libgfortran.5.dylib
                       @rpath/libquadmath.0.dylib
                       /usr/lib/libSystem.B.dylib
                       /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
```

With artifact `opensim-core-4.4.1-2022-09-08-de6854033` and after:
```
dyld_info -dependents libcoinmumps.1.dylib            
libcoinmumps.1.dylib [x86_64]:
    -dependents:
        attributes     load path
                       @rpath/libcoinmetis.1.dylib
                       @rpath/libgfortran.5.dylib
                       @rpath/libquadmath.0.dylib
                       /usr/lib/libSystem.B.dylib
                       /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
                       /usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib
```

Note that the last entry `/usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib` now appears as a dependency for `libcoinmumps.1.dylib` while it didn't in the previous artifact.

This shows up when loading the GUI as the following error message:
<img width="2979" alt="Screenshot 2022-11-17 at 10 28 52 AM" src="https://user-images.githubusercontent.com/7455790/202584505-25c0ba21-3830-4689-be99-8acee7c2f471.png">

Some possibly helpful info copied over from the GUI related PR:

I've seen libgcc_s.1.* before in various places in CMake. A couple of places are located here:
- https://github.com/opensim-org/opensim-core/blob/524cb877dcea6d67ce7e68ad994792623c80663a/Vendors/tropter/cmake/CMakeLists.txt
- https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/Vendors/tropter/cmake/tropter_install_mac_dependency_libraries.cmake.in

The file `tropter_install_mac_dependency_libraries.cmake.in` in particular catches my eye.

**Comment by aymanhab** [comment]
Necessary to make ci builds usable on osx

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I am going to self assign this issue since I've been working on it for the last few days.

**Comment by aymanhab** [comment]
Sure, thanks @AlbertoCasasOrtiz

**Comment by carmichaelong** [comment]
@carmichaelong test artifact on m1 machine and reopen if necessary

**Comment by carmichaelong** [comment]
GUI artifact OpenSim-4.4-2023-01-09-db1271b-mac opens without any library issues. Also tested that the gait10dof18musc CMC example ran to completioin.
