### ISSUE TITLE
Update animation in README using the new 4.0 visualizer

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#3327]

**Comment by aymanhab** [comment]
@tkuchida since we have no new visualizer I assume you mean to recreate the animation with latest build (maybe because colors or axes locations have changed).

**Comment by tkuchida** [comment]
It looks like [the animation](https://github.com/opensim-org/opensim-core/blob/main/doc/images/opensim_running.gif) was generated using OpenSim 3.3. The visualizer in OpenSim 4.x looks much better. Not a high priority, but this animation is the main thing you see on the GitHub homepage.

**Comment by aymanhab** [comment]
Will crop so there's no jump on repeat but wanted some initial feedback before proceeding

**Comment by tkuchida** [comment]
Definitely an improvement 😎
