### ISSUE TITLE
Outputs for StateVariables are created after construction; inconsistent. Also, outputs duplicated in Coordinate.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#333]
In #21 we created an output for every state variable. However, this is problematic because the state variable outputs are created during the "add to system" phase of building, while the rest of the outputs are created during an individual object's construction.

Also, Coordinate currently has explicit outputs for their value, speed, and acceleration. However, the Coordinate SHOULD already have value and speed outputs, since they are state variables.

**Comment by chrisdembia** [comment]
A related issue is that the dependsOn stage for the Coordinate "value" and "speed" outputs should be `Stage::Model`.

**Comment by sherm1** [comment]
Per discussion: Outputs should be defined with the Component, but they can't be hooked up to the state until addToSystem().

**Comment by sherm1** [comment]
Chris & Ajay think this means we can (and should) remove the "hidden" flag. Now if you don't create an output -- it's hidden!

**Comment by chrisdembia** [comment]
I'm wondering how much of an issue this actually is, since you can't use *any* outputs until you have a state, and having a state means you've already called `addToSystem()` on the Model, right?

I originally raised this issue because testComponents checks your list of Output's before `addToSystem()` is called, and thus the outputs for the state variables weren't appearing.

**Comment by chrisdembia** [comment]
My in-progress work for fixing this issue is in this branch: https://github.com/opensim-org/opensim-core/tree/remove-statevar-outputs
