### ISSUE TITLE
What happend to the method Manager::setDT() ?

### ISSUE THREAD

**Issue by Pipoderoso** [opensim-org/opensim-core#3330]
The method is mentioned in various placed on the comments from the class Manager in main branch. However it is not implemented. Is there another way to set a constant DT while integrating?

**Comment by aymanhab** [comment]
The set of methods that set/get/use DT have been updated in 2016. Please read the documentation here https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Manager.html
