### ISSUE TITLE
Animation does not appear at the bottom of the new API Example page

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#3331]
https://github.com/opensim-org/opensim-core/wiki/OpenSim-API-Example

![](https://user-images.githubusercontent.com/4203505/206344988-81f0e673-bd70-452a-b70a-668f4f747c28.png)

**Comment by AlbertoCasasOrtiz** [comment]
I just solved this one, looks like changing the main branch name from "master" to "main" changed the link to the animation file.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz The follow up question is whether other links to code snippets e.g. from confluence or user forum will continue to work. Any idea @carmichaelong based on the github documentation of branch rename?
