### ISSUE TITLE
Develop muscle wrapping test for variety of objects

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#3333]

**Comment by aymanhab** [comment]
So far we have tests for cylinders, spheres and ellipsoids but none for torus which is rarely used and actually is replaced by a custom cylinder at the point of contact in the current implementation. Also the tests do not cover the case where the path touches the cap of a cylinder or seam of a quadrant as these may end up problematic and unsupported. @nickbianco for your reference

**Comment by nickbianco** [comment]
Thanks @aymanhab. Where is the test for spheres?

**Comment by aymanhab** [comment]
It's the second black of the test case  under review
