### ISSUE TITLE
Create movie/animation "file" from model+states/motion

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3337]
Many local users would prefer to not load a model and a results file, start animation, save etc. while babysitting an application especially for many many results/simulations.

**Comment by aymanhab** [comment]
Requested in person by multiple local researchers

**Comment by neha191091** [comment]
If you want to do this programmatically using the opensim API, a very hacky workaround I found is to modify the [simbody](https://github.com/simbody/simbody) visualizer code (in <simbody-source>/Simbody/Visualizer/simbody-visualizer/simbody-visualizer.cpp) such that it ALWAYS saves the video in a path specified by an environmental variable, whenever the visualizer is opened by your (C++/matlab/python) application. 

Then recompile simbody following instructions in [simbody github repo](https://github.com/simbody/simbody) and finally copy the binary  <SIMBODY_INSTALL_DIR>/libexec/simbody/simbody-visualizer to <OPENSIM_INSTALL_DIR>/libexec/simbody/simbody-visualizer. You may want to save the original simbody-visualizer first.

Then in your application, you can copy/rename the generated video directory. 

Here is a minimally modified version of simbody-visualizer.cpp that can allow you to do this:
[simbody-visualizer.zip](https://github.com/opensim-org/opensim-core/files/10294961/simbody-visualizer.zip)
I set two environment variables that allow for saving the videos:
SAVE_OSIM_VID : set as 1 to save a video everytime the visualizer is ran.
PATH_OSIM_VID : set the absolute path of the directory where you want the video to be saved. 

There may occur issues when using multi-processing, multi-threading etc.  that have to be handled in your application.
Original Source: https://github.com/spMohanty/simbody/blob/master/Simbody/Visualizer/simbody-visualizer/simbody-visualizer.cpp

**Comment by aymanhab** [comment]
Thanks much for the sugestion @neha191091 that was along  the lines of what I was thinking. Thanks for providing your implementation as well. If we end up incorporating a variant of that in the codebase we'll definitely acknowledge your contribution. Thanks again 👍
