### ISSUE TITLE
Missing way to normalize joint angles in OpenSim

### ISSUE THREAD

**Issue by lkkraemer** [opensim-org/opensim-core#3343]
Hi,
I'm currently searching for a way to normalize joint angles in OpenSim before running inverse kinematics.

To make the issue more clear:
I am trying to avoid the need to subtract baseline joint angles, taken from a static standing measurement, from the actual inverse kinematics result from e.g. a running trial.
To compare kinematics between subjects with different baseline joint angles in a 'neutral' position, the normalization is still needed and to me currently requires post-processing steps of the inverse kinematics results from OpenSim trough Matlab code.

I would be pleased to see if there is any way to adjust(normalize) the joint angles or joint coordinate systems already in OpenSim.

Kind regards

**Comment by jenhicks** [comment]
Thank you for the comment. Please post to the forum for suggestions from other users about how they have tackled this problem, as this looks like something folks typically achieve using a matlab or other script.
