### ISSUE TITLE
The term 'C:\Python310\python.exe' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by haolee21** [opensim-org/opensim-core#3346]
Error The term 'C:\Python310\python.exe' is not recognized as the name of a cmdlet pops up when building the opensim-core in Windows. 
It does not make sense for users to install python in a specific path like this, I wonder if it can be changed to an env variable?

**Comment by AlbertoCasasOrtiz** [comment]
Hi @haolee21. I think you are right, it should be an env variable.
