### ISSUE TITLE
IMUDataReporter gives identical angular velocity outputs regardless of IMU frames

### ISSUE THREAD

**Issue by TheOne-1** [opensim-org/opensim-core#3366]
@carmichaelong 
Hi Carmichael,

I was using IMUDataReporter + AnalyzeTool to generate IMU signals. The strange behavior is that when I changed IMU frame orientation, synthetic accelerometer data changed accordingly whereas synthetic gyroscope data remained the same. I suspect angular velocity is reported in the body segment frame instead of the IMU frame.

Here is a code to reproduce the bug.
[IMU_generate_identical_angular_vel_bug.zip](https://github.com/opensim-org/opensim-core/files/10462624/IMU_generate_identical_angular_vel_bug.zip)

**Comment by nickbianco** [comment]
Hi @TheOne-1, the gyroscope signals are reported in the ground frame. We should add the option to express angular velocities in the IMU frames to `IMU` and `IMUDataReporter`, since this is what is done for the accelerations. For now, you could re-express the signals in the IMU frame yourself using `Frame::expressVectorInAnotherFrame`.

**Comment by TheOne-1** [comment]
Thanks Nick!

**Comment by carmichaelong** [comment]
> We should add the option to express angular velocities in the IMU frames to IMU and IMUDataReporter, since this is what is done for the accelerations.

@nickbianco I'm inclined to reopen based on this (and IIRC, there may have been a couple posts on the forum awhile ago at least tangentially related to this). Thoughts?

**Comment by nickbianco** [comment]
I made a new issue to specifically address the change: #3367. I guess I could have just reopened this one though.

**Comment by carmichaelong** [comment]
All good, thanks for making the other issue to track!
