### ISSUE TITLE
Report angular velocities expressed in the `IMU`'s frame

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3367]
Real inertial sensors report angular velocities in the frame associated with the sensor. Currently, `IMU` does not do this, but rather reports angular velocities expressed in ground. We should reported quantities expressed in the `IMU` frame by default, and perhaps have an option to report quantities expressed in ground. 

Reported by @TheOne-1.

**Comment by carmichaelong** [comment]
Related: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=15282&p=0&start=0&view=&sid=1c15f4dac7405e3562c35e98a6499375
