### ISSUE TITLE
Windows build script fails at Java bindings step

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3372]
Discovered while working with Jenny Maier to create an OpenSim on her Windows 10 machine.

We received an error that the Matlab and OpenSim architectures are the same. Thrown here:
https://github.com/opensim-org/opensim-core/blob/7d8fb7badd58536dce566444984eb65db62dbe7b/CMakeLists.txt#L516

This shouldn't be an issue since the [build script](https://gist.github.com/AlbertoCasasOrtiz/9ce33c82173f1ff273de0987d34bc3f9#file-opensim-core-windows-build-script-ps1) specifies 64-bit architecture using the `-A x64` flag. 

My suspicion was first that `CMAKE_GENERATOR` was not providing the correct architecture value. [`CMAKE_GENERATOR` is set using the cmake -G flag](https://cmake.org/cmake/help/latest/envvar/CMAKE_GENERATOR.html#envvar:CMAKE_GENERATOR), but [`CMAKE_GENERATOR_PLATFORM` is set by the -A flag](https://cmake.org/cmake/help/latest/envvar/CMAKE_GENERATOR_PLATFORM.html#envvar:CMAKE_GENERATOR_PLATFORM). Part of the fix might involved replacing `CMAKE_GENERATOR` with `CMAKE_GENERATOR_PLATFORM`, but issues occurred with CMake finding the Java libraries occurred when we tried this. The JDK seemed to be installed correctly on her machine, so it's unclear if that was a separate or related issue.

**Comment by nickbianco** [comment]
@aymanhab -- I've run out of ideas for this debugging this issue. I've tried changing the CMake variable names, but that doesn't seem to work (building the JavaBindings project in VS still fails).

Any ideas here would be much appreciated.

**Comment by aymanhab** [comment]
No worries @nickbianco I'll take a look

**Comment by aymanhab** [comment]
CMAKE_GENERATOR issue is fixed by PR #3373 no more warnings are issued locally. Need to figure out the separate java issue if any.

**Comment by nickbianco** [comment]
After testing locally and checking that the CI builds still pass, I'm closing this issue.
