### ISSUE TITLE
Using backslashes in SIMBODY_HOME CMake variable causes Simbody to not be found on Windows.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#338]
Reported by @JustinSi

**Comment by JustinSi** [comment]
Actually it is that when you build Simbody using CMake, you have to make sure that your install directory does not use backslashes. Otherwise it will cause parsing error for other projects that use Simbody since they will use Simbody's cmake configuration file

**Comment by chrisdembia** [comment]
Ah thanks for clarifying. I thought CMake allows people to combine both types of slashes, but maybe they are being used as escape characters?

**Comment by JustinSi** [comment]
I think you are right, when CMake parse some file, it will treat backslash as escape characters

**Comment by chrisdembia** [comment]
I found an email thread that suggested we do:

```
STRING(REGEX REPLACE "\\\\" "/" CMAKE_INSTALL_DIR ${CMAKE_INSTALL_DIR})
```

to the path.

**Comment by sherm1** [comment]
*Four* backslashes? I would have thought that would translate to `\\`.

**Comment by chrisdembia** [comment]
See [here](http://public.kitware.com/pipermail/cmake/2005-August/007149.html).

**Comment by sherm1** [comment]
Weird, but since it's CMake that might be right. But that thread is 10 years old and CMake has changed quite a lot since then.

**Comment by chrisdembia** [comment]
Yeah. I still don't like this solution; I feel it shouldn't be necessary. Maybe this needs some testing. I think it's fairly important though, since I think most of our users on Windows are likely to use backslashes in CMake variables.

**Comment by jimmyDunne** [comment]
This may be an issue with cmake variable being in quotes.
