### ISSUE TITLE
Design class layout for new wrapping algorithm based on geodesic variations

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3391]
We will implement [Andreas Scholz's algorithm based on geodesic variations](https://link.springer.com/article/10.1007/s11044-015-9451-1) to replace the current geometry-based wrapping algorithm. We will essentially copy the same structure in the Matlab code provided by Andreas, with minor changes needed to hook into the OpenSim API. 

This will mean introducing several new classes to handle the math for parametric surfaces, wrapping obstacles assigned to each path, and the wrapping algorithm itself. Some of these new classes will be somewhat redundant  in purpose to existing geometry classes (e.g., `WrapCylinder`), but we are keeping this new algorithm completely separate from the existing algorithm to keep development streamlined and to make it easier to deprecate the existing algorithms in the future. 

This planning issue is intended to cover all needs for implementing the wrapping algorithm within the `opensim-core` API, and not other follow tasks such as model path conversion, initial guess creation, etc. 

## Design needs
- Unit testing and benchmarking. Ideally, benchmarking can be performed along with unit tests in CI via GitHub Actions.
- A method for integrating the geodesic equations, either via the `Component` interface to leverage Simbody's integrators, or a custom integrator (e.g., 4th order Runge-Kutta) with the minimum set of features we need (e.g., adaptive step size based on path error).
- Path and surface visualization. Surface visualization should be generic to any type of parametric or implicit surface ([this may be helpful](https://github.com/simbody/simbody/blob/589e931f4a127830a5876ee4dd8f327b47361504/SimTKcommon/Geometry/src/PolygonalMesh.cpp#L740)).
- Serialization to XML and GUI compatibility.

## Proposed changes
- If not using Simbody integrators, a RK4 integrator (e.g., `/OpenSim/Common/RungeKutta4`).
- Implement `WrapSurface` class and all derived classes (i.e., `Cylinder`, `Ellipsoid`, etc.). This class could support parametric, implict, and analytic surfaces. 
- Implement `WrappingObstacle`, which connects to a `WrapSurface` via a `Socket` and is responsible for creating a geodesic (via a shooting algorithm)
- Implement `GeodesicGeometryPath`, which contains properties for the origin and insertion points of the path, manages a list of `WrappingObstacles` , and handles the gradient-descent algorithm for determining the path for the current configurations

**Comment by nickbianco** [comment]
@pepbos here's the wrapping design issue.

**Comment by pepbos** [comment]
Starting with cylinders sounds great. Do we already have a touchdown-liftoff behavior defined (for the initial) wrapping?
I liked the idea mentioned that you start from a no-wrapping scenario: so a straightline from start to end. And then add the first surface you intersect, etc.

But perhaps there are other ideas? And for liftoff?

**Comment by nickbianco** [comment]
Andreas' algorithm supports touchdown-liftoff behavior, but the plan for now is to implement the basic algorithm first and then add that feature in later. Most users won't need that feature, mostly because its never available to them, so that's lower on the priority list. But we should make sure that we can support that feature in our development plans.

**Comment by nickbianco** [comment]
FYI @anscholz
