### ISSUE TITLE
No constructor 'org.opensim.modeling.ExternalLoads' with matching signature found.

### ISSUE THREAD

**Issue by F2AGLAXY** [opensim-org/opensim-core#3393]
Hi,
I am running the tutorial based on https://simtk.org/projects/spine_ribcage.

Use MATLAB API for running static optimization. it shows 'No constructor 'org.opensim.modeling.ExternalLoads' with matching signature found.'

Does anyone know how to solve this?

Thank you in advance!

**Comment by nickbianco** [comment]
Hi @F2AGLAXY, this question is better suited for the [OpenSim forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). Post your question there and we can help you out.

-Nick
