### ISSUE TITLE
Find a place to locate the build scripts

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3397]
The build scripts referenced on the [wiki](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions) are currently gists created and located on my personal profile. Looks like organizations cannot create gists, so creating opensim-org gists is not an option. 

Any ideas of where we can place these scripts in an accessible and usable way? @aymanhab @jenhicks @carmichaelong @nickbianco

**Comment by nickbianco** [comment]
I know including them in the repo makes them harder to download, but most users will need to clone the repo before building anyway. We've kept build scripts [here ](https://github.com/opensim-org/opensim-core/tree/main/.github) before, but we could find a more visible location.

**Comment by adamkewley** [comment]
It's fairly (imo) common to have something like a `scripts/` directory in a repo, where any project-related scripts (incl. build, one-time scripts, asset packers, etc.) get dumped. Revealing my bias, `opensim-creator` does exactly that:

https://github.com/ComputationalBiomechanicsLab/opensim-creator/tree/main/scripts

(although you can see one problem, which is that all kinds of crap tends to build up in there over time)

**Comment by AlbertoCasasOrtiz** [comment]
Thank you @nickbianco for looking into this. I think we should do the same, but controlling which kind of scripts end up in the folder and organizing them. Should I locate the build scripts into `scripts/build/`, so every new script is created inside of `scripts/`, and we can organize into folders as new ones are created?

This way, as suggested by @aymanhab some time ago, we can also have a `scripts/contributions/` folder or something like that with scripts created by users, with a disclaimer saying that those scripts were created by users and we are not maintaining them.

**Comment by aymanhab** [comment]
I like the idea of having a scripts folder as well. I'd keep these for development purposes (inspired by @adamkewley list). Not sure what else is available to individual users and not organizations but it may make sense to make a github user e.g. opensim-dev and use that account for situations that an "official" opensim account is required.

**Comment by AlbertoCasasOrtiz** [comment]
Solved by adding build scripts to /scripts folder in both `opensim-core` and `opensim-gui`.
