### ISSUE TITLE
Problem building for Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by flamerten** [opensim-org/opensim-core#3405]
I am currently trying to repurpose a Raspberry Pi 4 to replicate the results from [OpensenseRT](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Wearable+and+Real-time+Kinematics+Estimates+with+OpenSense). As I was not able to boot up the Raspberry Pi from the images provided, I flashed a 32GB SD card with Ubuntu Desktop, and followed the [build instructions for linux](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions#build-instructions-1), by running the [build script](https://gist.github.com/AlbertoCasasOrtiz/a391f46cbc0ed8808aca4af546810e16) provided. However, I have faced issues, when trying to install opensim for both Ubuntu 20.04 and Ubuntu 22.04. For both images, the installation stopped under LOG: BUILDING OPENSIM-CORE DEPENDENCIES.  

For Ubuntu 20.04

`[ 40%] Built target colpack`
`make: *** [Makefile:84: all] Error 2`

For Ubuntu 22.04

`[ 68%] Built target simbody`
`make: *** [Makefile:91: all] Error 2`

I'm not too sure what I am doing wrong, given the build instructions stated that the script was tested on the distros, and I simply need to run the script. The only thing that this is a Raspberry Pi, though the creators of OpenSenseRT used the same hardware, so I am not sure why I am facing the issue.

**Comment by aymanhab** [comment]
Not sure the build script would run out of the box on PI but we'll need more info to troubleshoot or help you troubleshoot. the colpack error suggests you're trying to build with moco which is unused by OpenSenseRT and requires massive resources/dependencies. You should turn that off (please read the documentation/usage of the build script for instructions).

**Comment by flamerten** [comment]
Hi thanks for your help. It helped greatly and I referenced other codes to continue to debug.

I set OPEN_SIM_WITH_CASADI and OPENSIM_WITH_TROPTIER to be OFF, installed eigen3 and also manually set the Java environment variables. However, during the build, I had the error:
'Out of memory: Killed process 43066 (cc1plus) Does this mean that given the Raspberry Pi's RAM, i cannot build OpenSim? Or could there be another reason that I got the Out of memory error. Note that I have tried to minimize ram usage by installing the server version without a GUI, which is what was done for OpenSenseRT

**Comment by SietseAchterop** [comment]
The amount of ram probably is too small, but if you increase the swapsize enough, it should work abeit extreemly slow.
Google for "rpi swapfile".

**Comment by halleysfifthinc** [comment]
I would recommend cross-compiling for the Pi on a desktop instead of compiling directly on the Pi. Cross-compiling has the advantage that it should be much faster, and shouldn't have any out-of-memory issues.

**Comment by aymanhab** [comment]
You also should turn off java wrapping since it's not needed for opensenseRT.

**Comment by flamerten** [comment]
As a progress update, i tried increasing the swap file and decreasing the number of jobs. Installation progresses further than before but its quite slow. 

@SietseAchterop Thank you so much for the help, increasing the swapfile to 4GB helped, though the installation is quite slow.
@halleysfifthinc could you elaborate on this? How could i cross-compile for PI on a desktop? Would it be using a VM, and then jus transferring the files over to the microSD card on the PI
@aymanhab may i know how i could turn it off? I do not see that configurable option in the Linux build instructions

Thanks everyone once again for your help.

**Comment by halleysfifthinc** [comment]
Check out [these](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html) [links](https://www.kitware.com/cross-compiling-for-raspberry-pi/) about cross-compiling with CMake. It will be more complex to setup, so depending on your familiarity with building software in general, it may not be worth it (especially if you don't anticipate needing to build opensim again).

To turn off the Java wrapping, you'll need to remove `-DBUILD_JAVA_WRAPPING=on` or change it to `OFF` on [line 181](https://gist.github.com/AlbertoCasasOrtiz/a391f46cbc0ed8808aca4af546810e16#file-opensim-core-linux-build-script-sh-L181) of the build script. 

Also, if building on the Pi, you should set the number of jobs `-j` argument in the build script to 1, if you're not already doing so, as this will help decrease the RAM usage. (And also likely speed up the build, despite no longer being parallel, since swapping is horrifically slow.)

**Comment by flamerten** [comment]
@halleysfifthinc Thank you for your help, it worked, although it took around 8 hours of building. Overall I was able to install opensim on the raspberry pi, which runs on ubuntu 20.4. However, I did face some issues during the installation, which i intend to document and submit as a pull request.

**Comment by flamerten** [comment]
@Hari-techi-96 please refer to https://github.com/opensim-org/opensim-core/wiki/Build-Instructions#build-instructions-1 and build from there. In this issue I have documented a few configurations that worked which can be found in the comments above.

Directly booting with the OS provided will not work, you boot the raspberry pi with Ubuntu and build opensim using the build script provided.

**Comment by Hari-techi-96** [comment]
@flamerten Thanks for the replay , I followed the build instructions you have provided , but ended up with an error : 
For Ubuntu 22.04.3 LTS

[ 73%] Built target simbody
make: *** [Makefile:91: all] Error 2

as per the suggestions given i turned off " -DBUILD_JAVA_WRAPPING=off" java wrapping and set the number of jobs -j as 1. 
After running the command for updated file , i got  an error, and don't know what is reason for this.
![WhatsApp Image 2023-12-10 at 2 39 19 PM](https://github.com/opensim-org/opensim-core/assets/68151626/9c3313ac-9223-4f7e-9b37-102c4187d6c1)
![WhatsApp Image 2023-12-10 at 2 39 18 PM](https://github.com/opensim-org/opensim-core/assets/68151626/98b991b4-502f-47bc-a6f4-8e1ca0d87771)

**Comment by Hari-techi-96** [comment]
@flamerten  Thank you for Replaying , I followed the instructions , even after making some changed mentioned above in the build scripts  i ended up with an error ,
![new_error](https://github.com/opensim-org/opensim-core/assets/68151626/6bc7a34a-a7db-4521-8f83-5e01b1d6e2f3)

I don't know what to do after this. can you please suggest some solution for this.

**Comment by flamerten** [comment]
@Hari-techi-96 Im not too sure, I didn't encounter this error, but I can give you a quick rundown of what I remember doing. Its been a few months and i'm relying on my own documentation. Bear in mind this is for my specific use case which is OpensenseRT which does not need all parts of Opensim.

Firstly, I installed Ubuntu 20.04 server, **without** the Desktop GUI. I'm not sure if this helps but I know the GUI takes up some RAM, which is necessary for opensim installation.

From the error I see, it looks like you might be enabling Moco dependencies. So i disabled it by calling this build script.

`./opensim-core-linux-build-script.sh -s0`

I also disabled Tropter and Casadi by adding the below lines to `/home/ubuntu/opensim-workspace/opensim-core-source/CMakeLists.txt`

```
set(OPENSIM_WITH_CASADI OFF)
set(OPENSIM_WITH_TROPTER OFF)
```

I ran into an Eigen3 error and I installed it with sudo. `sudo apt install libeigen3-dev`

Lastly, JNI could not be found. To solve this, I set the Java Environment Variable
```
update-java-alternatives -l #check java location
export JAVA_HOME=/path/to/location
```

These are the list of issues I documented. I'm not sure if this is the best approach and my experience is rather limited [cc @aymanhab as one of the contributors to opensim, as he might provide more helpful insights if needed]. Also I highly recommend adding a heat sink and fan to the raspberry pi as it get REALLY HOT.

**Comment by Hari-techi-96** [comment]
@flamerten Thank you so much for the suggestions, I'll Implement these changes

**Comment by Hari-techi-96** [comment]
@flamerten Thank you for giving the right suggestions, build was successful and i can run opensim-cmd in terminal.
Thank again.

**Comment by aymanhab** [comment]
Thanks @flamerten for helping out @Hari-techi-96 
Before we close, can you point to where you got the build instructions for OpenSenseRT so we can clarify that:
1. You don't need Moco dependencies, how to turn off
2. You don't need to build the Java Bindings altogether
3. You don't need a GUI build or installation as you don't need the GUI, and we don't publish one anyway
4. You shouldn't need Eigen either as it should be needed only by Moco dependencies AFAICT.
Thank you
