### ISSUE TITLE
libopenblas.so.0 missing in Ubuntu

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3412]
I have tested the CI artifacts on Ubunty 18.04, 20.04 and 22.04 and when trying to execute `opensim-cmd` it is throwing the following error:

    ./opensim-cmd: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

The library libopenblas.so.0 is not present in the `opensim-core/sdk/lib` folder. After installing openblas with `sudo apt install libopenblas-base` it seems to work.

**Comment by AlbertoCasasOrtiz** [comment]
I haven't detected any problem with the rest of the libraries.

**Comment by aymanhab** [comment]
I don't think we distribute this or other low level libraries stdc++ etc., these need to be installed outside in standard system locations.

**Comment by AlbertoCasasOrtiz** [comment]
Should I add this to [troubleshooting section](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions#troubleshooting-1) in the wiki then?

**Comment by aymanhab** [comment]
Sure. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
Thank you. I have just updated the wiki. I close this issue.
