### ISSUE TITLE
Error while importing opensim python API: 'DLL load failed while importing simbody'

### ISSUE THREAD

**Issue by dvm-mi** [opensim-org/opensim-core#3417]
Hello Guys, I am facing an issue using opensim APIs
I have installed Python 3.11 version with and imported Opensim4.4 using pip commands sucessfully on my Microsoft VSCode (version- 1.76) 
However when I try to run scripts importing the opensim, it shows a dll error and simboy import error. Pasting the error here for reference.

File "d:\python opensim\examples\varyingjointangles.py", line 2, in <module>
    import opensim
    ^^^^^^^^^^^^^^
  File "C:\Users\divya\AppData\Roaming\Python\Python311\site-packages\opensim\__init__.py", line 9, in <module>
    from .simbody import *
  File "C:\Users\divya\AppData\Roaming\Python\Python311\site-packages\opensim\simbody.py", line 13, in <module>
    from . import _simbody
ImportError: DLL load failed while importing _simbody: The specified module could not be found.

**Comment by Aleph-Zero0** [comment]
Hello, I have a similar issue. Were you able to solve it? If yes, can you share the solution?

**Comment by Aleph-Zero0** [comment]
@dvm-mi It helped, thank you very much!
