### ISSUE TITLE
Colab tutorials not working on Google Colab

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3424]
Google Colab has upgraded Python version to 3.9, and the version of the current opensim conda package is built to work with only Python 3.8.

More information here:
- https://github.com/googlecolab/colabtools/issues/3450
- https://twitter.com/GoogleColab/status/1633535850456703000?cxt=HHwWsICz5e-MvqstAAAA

**Note:** the temporal solution mentioned in the first link is only available until mid-March, so we cannot rely on it.
**Note 2:** We should follow these updates because in the first link they say they have _plans to upgrade to more modern versions in the future_ (Python 10 and Python 11).

**Comment by AlbertoCasasOrtiz** [comment]
The condacolab team has investigated our issue (thank you) and looks like it is a problem with our package. We have an open python dependency, so conda is detecting it instead of the correct version. Here there is the full explanation of the error: https://github.com/conda-incubator/condacolab/issues/51#issuecomment-1492967958. @ayman, is this something we can easily fix?

**Comment by aymanhab** [comment]
Sure, thanks for the investigation, I'll update the info for the old packages to restrict python. The issue shouldn't exist for opensim_admin though which has no unrestricted python packages, does that work out of the box?

**Comment by AlbertoCasasOrtiz** [comment]
Thank you @aymanhab, looks like everything is working fine now in both `opensim-org` and `opensim_admin` channels. I'm closing this issue.
