### ISSUE TITLE
InverseKinematicsTool_run filed

### ISSUE THREAD

**Issue by LiangliangXiang** [opensim-org/opensim-core#3432]
Hi, could anyone tell me what is the problem here. I'm using opensim 4.3 and python 3.8.

  File "E:\Software_1\OpenSim 4.3\Resources\Models\Gait2392_Simbody_10\OpenSim\IK.py", line 56, in <module>
    ikTool.run()

  File "E:\Software_1\OpenSim 4.3\sdk\Python\opensim\tools.py", line 4215, in run
    return _tools.InverseKinematicsTool_run(self)

RuntimeError: std::exception in 'bool OpenSim::InverseKinematicsTool::run()': InverseKinematicsTool Failed, please see messages window for details...

**Comment by nickbianco** [comment]
Hi @LiangliangXiang, this question is better suited for the [OpenSim forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). Please post your question there and we will respond to help find a solution.
