### ISSUE TITLE
`CoordinateCouplerConstraint` does not handle multiple independent coordinates properly

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3435]
`CoordinateCouplerConstraint` should support multiple independent coordinates since the property `independent_coordinate_names` is a list property. However, the function that computes the coordinate coupling error only takes into account the first two coordinate in the total list of coordinate, whether or not they are independent or dependent:

https://github.com/opensim-org/opensim-core/blob/22af32b0191a20eef50940574bbfcd21bd93c972/OpenSim/Simulation/SimbodyEngine/CoordinateCouplerConstraint.cpp#L47

**Comment by bfregly** [comment]
We would like to be able to have two (or more!) independent coordinates as inputs to a coordinate coupler constraint as well. Please let us know when this capability is available. You will probably need to add the ability to handle a <coupled_coordinates_function> that is defined analytically, like sqrt(x^2/2+y^2/4) where dependent coordinate z is an analytical function of independent coordinates x and y.
