### ISSUE TITLE
TimeSeriesTable getRowAtIndex returns incorrect values

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3439]
Hi, 

I think there is a bug in `getRowAtIndex`. I would expect to get the entire values of each row based on the index, but it returns the values in columns. Please see this example:
[test.zip](https://github.com/opensim-org/opensim-core/files/11304795/test.zip)
![image](https://user-images.githubusercontent.com/38867713/233862838-4f17f1a3-1bdb-48c8-b755-7da62a9fe407.png)
```python
In [1]: file = osim.TimeSeriesTable('test.sto')
In [2]: file.getRowAtIndex(0).to_numpy()
array([18.1, 21. , 16.9,  7.5,  0.1, -2.5])

In [3]: file.getDependentColumnAtIndex(0).to_numpy()
array([18.1, 21. , 16.9,  7.5,  0.1, -2.5, -1.1,  2.5,  6.3, 11.2, 15.3])
```
This is the same for `updRowAtIndex`, `getRow`, `updRow`, `getNearestRow`, and `updNearestRow`. Is it a correct behavior?

Thank you,
Mohammadreza

**Comment by tkuchida** [comment]
The same strategy seems to be used in test_simbody.py ([here](https://github.com/opensim-org/opensim-core/blob/68b37e1d2b327cdb7629f910d614ce45193d7272/Bindings/Python/tests/test_simbody.py#L114))… not sure why test_simbody.py passes but the example above doesn't.

**Comment by mrrezaie** [comment]
@tkuchida, this is a Python specific issue. I just checked MATLAB equivalent and it works fine:
```
clc, clear all
import org.opensim.modeling.*

table = TimeSeriesTable();
labels = StdVectorString();
labels.add('a');
labels.add('b');
table.setColumnLabels(labels);
table.appendRow(0.0, RowVector.createFromMat([1.5, 0.5]));
table.appendRow(1.0, RowVector.createFromMat([2.5, 2]));

disp(table.getRowAtIndex(0).getAsMat())
disp(table.getRowAtIndex(1).getAsMat())
```
```
1.5000    0.5000
2.5000    2.0000
```

**Comment by tkuchida** [comment]
@mrrezaie Not sure what the underlying cause is, but a workaround is to create a RowVector from the RowVectorView that is returned by `getRowAtIndex()`:
```py
import opensim as osim
table = osim.TimeSeriesTable()
table.setColumnLabels(['a', 'b'])
table.appendRow(0.0, osim.RowVector([1.5, 0.5]))
table.appendRow(1.0, osim.RowVector([2.5, 2.]))
r0 = table.getRowAtIndex(0)
#print(r0.to_numpy())
r0vec = osim.RowVector(r0)
print(r0vec.to_numpy())
```

**Comment by mrrezaie** [comment]
Good workaround! How `osim.RowVector(r0)` can fix it while `r0` contains different values?

**Comment by tkuchida** [comment]
> Good workaround! How osim.RowVector(r0) can fix it while r0 contains different values?

[`getRowAtIndex()`](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1DataTable__.html#ae3b74d696f4a7c0b4e3b1d5be6c0674e) returns a [RowVectorView](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1DataTable__.html#a9fbf4475d85a4b5352300a75ace1e6e4) which should work the same as a RowVector from the user's perspective. Additional information about the RowVectorView can be found [here](https://simtk.org/api_docs/simbody/3.5/singletonSimTK_1_1RowVectorView__.html#details). The workaround constructs a RowVector from the returned RowVectorView; the Python interface for RowVector seems to be working as expected.

**Comment by mrrezaie** [comment]
Thank you.

**Comment by mrrezaie** [comment]
Hi, any plan to fix this bug for the new release?

**Comment by nickbianco** [comment]
@mrrezaie, since there's a reasonable workaround for this I don't think this will be high on our priority list for now. `RowVectorView` is basically a `const` reference to a `RowVector`, and I wonder if [the wrapping code that handles the conversion to NumPy](https://github.com/opensim-org/opensim-core/blob/eec8be7cb706c8fa1264e3a2900a4e8a6851e1f7/Bindings/Python/swig/python_simbody.i#L226) accesses the data differently when you have a `RowVectorView` (or any other `View`-type structure) in Simbody.

My guess is that the fix would need to happen somewhere in python_simbody.i (linked above).

**Comment by mrrezaie** [comment]
> since there's a reasonable workaround for this I don't think this will be high on our priority list for now.

Hi @nickbianco, thanks for your response. Perhaps this known bug should be on top of the list. Because it took me several days to figure out what was wrong with my code when I was trying to reproduce the results of a MATLAB code with Python, and I ended up finding this bug. So, this might be confusing for users who are not aware of this workaround. Thank you.

**Comment by nickbianco** [comment]
@mrrezaie, I did a little digging, and [this appears to be a bug in Simbody](https://github.com/simbody/simbody/issues/768).

**Comment by mrrezaie** [comment]
@nickbianco, I appreciate the time and effort you put into this, thank you.
