### ISSUE TITLE
Problem encountered when setting up Matlab Scripting Environment in Linux server.

### ISSUE THREAD

**Issue by ExtremelyDullCoder** [opensim-org/opensim-core#3443]
After installing OpenSim-core on the Linux server as instructed, I tried to set up Matlab Scripting Environment as I did on Windows machine. However, no matter which folder I chose, the configureOpenSim() function responded with the error message indicating that it was not the folder where the opensim-core was installed. I have tried the opensim-core-main folder and every folder named "OpenSim" within it, as well as the /usr/.conda/envs/opensim folder, where the environment was set. And I have already changed the path of libstdc++ to make it consistent with MATLAB. I am wondering which folder should I choose or whether I have made some mistakes when installing. The photos of the problem is attached.
![1](https://user-images.githubusercontent.com/131533176/235471560-3e1e2114-c6ce-486a-940b-e9b4dadd6923.png)
![2](https://user-images.githubusercontent.com/131533176/235471574-71770251-ec09-4f02-8377-ad439da43526.png)
![3](https://user-images.githubusercontent.com/131533176/235471580-4ea24594-d113-4f95-ad2f-01ddd519ea13.png)
![4](https://user-images.githubusercontent.com/131533176/235471585-09f91446-a802-4c90-bc99-e768d7114322.png)
![5](https://user-images.githubusercontent.com/131533176/235471594-d973cf08-ce5d-4fdd-befc-fbde5eb369a9.png)
![6](https://user-images.githubusercontent.com/131533176/235471624-0f8945a3-d406-4f99-ba7d-161d8fc3afda.png)
 If further information is needed, I will upload it as quickly as possible. Thank you for all your suggestions!

**Comment by aymanhab** [comment]
There're two steps to packaging opensim (and most other packages):
1. Compiling the source into libraries
2. Installation which rearranges the libraries, headers and other resources into a specific layout and makes the code relocatable so it can be placed on machines other than the machine used for compilation.

Matlab expects a layout produced by installation while you're pointing it to a folder used for building so has a different layout. Execute the install step to a specific folder and use that instead. If that works please close this issue, if not please point the specific issue. Thank you
