### ISSUE TITLE
osimC3D.m Java exception: "Type 5 is not supported yet"

### ISSUE THREAD

**Issue by lavancig** [opensim-org/opensim-core#3446]
My pipeline exports C3D files from Qualisys, and I`m trying to convert those into OpenSim-compatible files. When I try to run the osimC3D function in MATLAB R2022b, I get the following error.

>     c3d = osimC3D(filename,1);
> 
> Error using osimC3D
> Java exception occurred:
> java.lang.RuntimeException: Type 5 is not supported yet, please open an Issue on github for support
> 	at org.opensim.modeling.opensimCommonJNI.DataAdapter_read(Native Method)
> 	at org.opensim.modeling.DataAdapter.read(DataAdapter.java:80)
> 
> Error in trialsToOsim (line 17)
>     c3d = osimC3D(['Qualisys/' char(folder) '/' fileList.name],1);
> 
> 

The error occurs when `tables = c3dAdapter.read(path2c3d);` is called at osimC3D.m, line 68.

**Comment by halleysfifthinc** [comment]
That error is thrown by the C3D library, ezc3d, which does not yet support that type of force plate. I'm sure they would appreciate it if you could open an [issue](https://github.com/pyomeca/ezc3d/issues/new/choose) and send them a c3d file that they could use to develop and test support for that type of force plate.

In the meantime, I would try to export the data as trc/mot directly from the Qualisys software (I know Vicon can export as trc/mot, but am not familiar with Qualisys's capabilities). Alternately, if you don't need the force data, you could try to re-export the c3d files from Qualisys without the force data, which should avoid that error.
