### ISSUE TITLE
VectorVec3 does not support to_numpy()

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3448]
Hi, VectorVec3, and RowVectorVec3 do not support `to_numpy()`.
```python
trc = osim.TimeSeriesTableVec3('static.trc')

vv3 = trc.getDependentColumn('R.ASIS') # VectorViewVec3
vv3.to_numpy() # DOESN'T WORK and I have to use getElt

trc = trc.flatten(['_x','_y','_z']) # convert to TimeSeriesTable
v = trc.getDependentColumn('R.ASIS_x') # VectorView
v.to_numpy() # works well
```
I'm looking forward this functionality, thank you.

**Comment by tkuchida** [comment]
Related to #3439

**Comment by nickbianco** [comment]
`VectorVec3` and `RowVectorVec3` are unique data structures that don't have an immediate equivalent in Python. Is there a specific reason why the current approach (i.e., `flatten`, then call `to_numpy`) doesn't make sense for your workflow?

**Comment by mrrezaie** [comment]
Hi, I have done what you said but VectorVec3 to numpy would be much convenient. This option, however, is available for MATLAB users through `getAsMat`:
https://github.com/opensim-org/opensim-core/blob/ffce474882a5ebac3a565bb77157660a787a7d5c/Bindings/Java/Matlab/examples/matrixConversions.m#L50-L61

**Comment by mrrezaie** [comment]
I think you are right, feel free to close this issue.

**Comment by nickbianco** [comment]
It looks like [`getAsMat()` does some automatic flattening](https://github.com/opensim-org/opensim-core/blob/ffce474882a5ebac3a565bb77157660a787a7d5c/Bindings/Java/swig/java_simbody.i#L26) to return a Matlab matrix for you. Does `to_numpy()` return the expected NumPy array after flattening manually? If so, then I think we can close this.
