### ISSUE TITLE
move generateDecorations method from ModelComponent into Component

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#347]
This has been agreed upon with @sherm1 and @aseth1 to enable Geometry to draw itself rather than have ModelComponent draw its Geometry. This issue is a place holder to discuss the side effects when the move is done in the code. Potential issues:
- ModelComponent has access to getModel while Component doesn't.

Will update as we go.

**Comment by aseth1** [comment]
I guess that is a good test if something is a ModelComponent or not. If you need to `getModel()` to access the Model you belong to, then you are a ModelComponent. If you can draw yourself or compute something without the notion of being a part of a Model (e.g. you only add yourself to and require the underlying system) then you are a plain Component.

Things that are clearly not ModelComponents are: Solvers, Operators, Functions ... do we ever expect these to have Geometry? Frames are locations of interest on Models, so I think we made the right call making the ModelComponents. If Geometry depends of being attached to a Frame, which is a ModelComponent, maybe Geometry only makes sense as being a part of a Model too? Geometry seems to be a very fundamental component of a Model, not simply a computational component.

**Comment by sherm1** [comment]
> Geometry seems to be a very fundamental component of a Model, not simply a computational component.

I would be happy with Geometry as a ModelComponent. I guess a separate question is whether Solver, Operator, Function, etc. Components might want to generate some displayed information and if so should they do it with `generateDecorations()`. Decorations can include screen text, lines, and other simple things.

**Comment by aseth1** [comment]
> Components might want to generate some displayed information and if so should they do it with generateDecorations(). Decorations can include screen text, lines, and other simple things.

Sure. I hadn't thought about that. I guess you could even have a Component like an Oscilloscope whose only job would be draw an Input as a waveform on screen. That wouldn't be a ModelComponent either.

**Comment by aymanhab** [comment]
This has been done with the geometry branch merge, I think this issue can be closed.
