### ISSUE TITLE
conda packaging (linux, mac-arm, moco)

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3479]
- [x] double check current state of windows moco conda packages (some reported issues using these)
- [x] mac arm64 packages (without moco)
- [ ] mac arm64 package with moco
- [ ] linux packages (for jupyter notebooks, colab, etc.)

**Comment by aymanhab** [comment]
a package for python 3.10, 3.11 was posted on the opensim_admin channel (arm64). Can you give it a spin when you have a chance @carmichaelong ? Thank you

**Comment by carmichaelong** [comment]
looking good to me! importing and constructing a model worked for both 3.10 and 3.11 using something like:

```
conda create --name opensim_py311 python=3.11
conda activate opensim_py311
conda install -c opensim_admin opensim
```

and can confirm it was pulling osx-arm64:
```
The following NEW packages will be INSTALLED:

  libblas            conda-forge/osx-arm64::libblas-3.9.0-17_osxarm64_openblas
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-17_osxarm64_openblas
  libcxx             conda-forge/osx-arm64::libcxx-16.0.5-h4653b0c_0
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-12_2_0_hd922786_31
  libgfortran5       conda-forge/osx-arm64::libgfortran5-12.2.0-h0eea778_31
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-17_osxarm64_openblas
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.23-openmp_hc731615_0
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-16.0.5-h1c12783_0
  numpy              conda-forge/osx-arm64::numpy-1.23.5-py311ha92fb03_0
  openblas           conda-forge/osx-arm64::openblas-0.3.23-openmp_hf78f355_0
  opensim            opensim_admin/osx-arm64::opensim-4.4-py311np123
  python_abi         conda-forge/osx-arm64::python_abi-3.11-3_cp311
```

**Comment by aymanhab** [comment]
Awesome, that's exciting, thank you 👍 I'll try to find an open issue and have another tester (just because you know too much about this stuff @carmichaelong ) and if all ok will upload to opensim-org, then start on the moco adventure ;)

**Comment by aymanhab** [comment]
@nickbianco or @gattia or anybody else who has apple M1 and running python would be helpful to test if this conda package works for you from the opensim_admin channel or I can move to opensim-org since it has no osxarm64 anyway.

**Comment by aymanhab** [comment]
opensim-moco packages for windows (python 3.9, 3.10, 3.11) are now available on opensim_admin channel.

**Comment by aymanhab** [comment]
@malborno This maybe of interest to you based on your forum posts as well.

**Comment by gattia** [comment]
I installed using the same commands as @carmichaelong & tested by loading model and initializing states: 

```
model = opensim.Model('path')
states = model.initSystem()
```

No issues for me on M2 Macbook Air with macOS Ventura (13.3.1)

**Comment by carmichaelong** [comment]
@aymanhab Alan tested the opensim-moco package on opensim_admin using Windows 11 and python 3.11. He was able to run a moco example

**Comment by nickbianco** [comment]
@aymanhab A conda package on Linux that includes Moco would be helpful for AddBiomechanics development. I know you're working towards that, but if I can assist with development or testing to help prioritize that, let me know.
