### ISSUE TITLE
Fix `PointToPointSpring` explodes when both ends are socketed onto the same body

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#3485]
Found by @itbellix. Original issue is downstream in opensim-creator: https://github.com/ComputationalBiomechanicsLab/opensim-creator/issues/680

Reproduction:

- Open `WalkerModel.osim`
- Add `PointToPointSpring` and set both sockets to `Pelvis`
- Simulate
- BUG: Model is visible at `t = 0` and then disappears at `t > 0`

Throwing an error message at `finalizeFromProperties` time along the lines of "tut tut, you can't attach a spring this way" or similar might be enough to at least prevent users from doing this (unless there's an argument to permit this?).

**Comment by tkuchida** [comment]
> unless there's an argument to permit this?

I don't think so… ensuring body1 and body2 point to a different `getMobilizedBody()` makes sense. (There's also a `PointToPointActuator` whose bodyA and bodyB must presumably be different.)
