### ISSUE TITLE
[Feature request] expose more Simbody methods

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3490]
Hi, there are several simbody methods that are not exposed in OpenSim API, e.g.:
[◆ ](https://simbody.github.io/3.7.0/classSimTK_1_1MultibodySystem.html#a1e84e26c6f4e1a8396a65b58faff680a)getRigidBodyForces()
[◆ ](https://simbody.github.io/3.7.0/classSimTK_1_1MultibodySystem.html#ace048e31c9fdc622d3b737026df2e6e5)getMobilityForces()
[◆ ](https://simbody.github.io/3.7.0/classSimTK_1_1Force_1_1Gravity.html#aaa6761c58727d65ff8265a9f2e78b1ee)getBodyForces()

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=16623&p=0&start=0&view=&sid=5747e9621b5b8c57854568d6d447f3b2

And it would be great if you could define these methods directly into OpenSim::Model class.

Thank you.

**Comment by aymanhab** [comment]
@nickbianco these are other methods to potentially consider from the dev planning meeting
