### ISSUE TITLE
"MocoCasADiSolver is not available" in Conda Python 3.10 package

### ISSUE THREAD

**Issue by BullAJ** [opensim-org/opensim-core#3506]
As the title says, the MocoCasADiSolver does not appear to be available when using the installed Conda package for Python 3.10. Here is the error:
![image](https://github.com/opensim-org/opensim-core/assets/26511954/08b6bd7c-3ba1-47dc-b764-142cf3e06fe5)

Is the exampleSlidingMass.py not  intended to be used with the conda packages?

**Comment by mrrezaie** [comment]
Hi, there is another package specifically for OpenSim Moco:
https://anaconda.org/opensim-org/opensim-moco

**Comment by BullAJ** [comment]
Thanks, the demo works with that package installed. I am working with [motion capture data](https://www.nature.com/articles/sdata2018133), but I don't see any additional packages on the Anaconda website, is there anything else I would need?

**Comment by aymanhab** [comment]
There's nothing specific to motion capture data other than various example scripts included in the distribution and some documentation here 
https://simtk-confluence.stanford.edu:8443/display/OpenSim/Common+Scripting+Commands

If the issue has been resolved, please feel free to close. Thank you
