### ISSUE TITLE
Remove deprecated instructions from wiki

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3507]
In the wiki, there is a page with the old instructions (the ones previously in the readme), that I left there just in case someone had problems with the new build instructions. Should we remove it? @aymanhab There are many outdated things in that page.

https://github.com/opensim-org/opensim-core/wiki/Build-Instructions-(Old-deprecated)

**Comment by aymanhab** [comment]
Hi Alberto, indeed I'd remove old/stale instructions and if there's an
issue with the new instructions fix them. Especially github should stay
current with latest code base/instructions.
