### ISSUE TITLE
make a 4.4.1 version for TGCS

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3511]
We'll need some features added after 4.4 for the TGCS workshop, so it would be good to do make 4.4.1 packages for the following:

- [ ] Binaries with Moco (for MATLAB) (Windows, Mac x64)
- [x] Conda packages with Moco (Windows)

@aymanhab How long would it take you to make these?

**Comment by aymanhab** [comment]
I'll get started on it asap. The conda packages are straightforward, the binaries with Java bindings a bit out of the box since we typically package only with GUi. Will keep you posted but I expect to have some artifacts before the end of the week.

**Comment by aymanhab** [comment]
Considering the versions in changelog and make files are set to 4.5 already, any preference to using 4.4.1 vs 4.5 (we can label it beta)? thoughts @jenhicks

**Comment by carmichaelong** [comment]
> the binaries with Java bindings a bit out of the box since we typically package only with GUi. Will keep you posted but I expect to have some artifacts before the end of the week.

Can we tag one of the commits to be the new version and then use the artifacts directly from Actions?

**Comment by aymanhab** [comment]
We can use artifacts from actions, difference from releases are in that:
- splash screen, welcome page, what's new
- links in documentation, doxygen etc.
- version numbers include commit tags so they look messy.

**Comment by nickbianco** [comment]
> version numbers include commit tags so they look messy

If we post the binaries directly to the confluence page, then we could edit the name of the zip file to make it look cleaner.

**Comment by aymanhab** [comment]
Sure would be perfectly fine to use 4.4.1 we just need to update the changelog and cmake files accordingly so that the documentation and build are correctly aligned regardless of when or whether a 4.5 is released.

**Comment by aymanhab** [comment]
Artifacts are available here  https://github.com/opensim-org/opensim-core/actions/runs/5549848330
Doxygen has been sent for review, link here https://drive.google.com/file/d/1SPb54ydtfiHgf40znudG89HvjQKp7Jvs/view?usp=drive_link
opensim-moco conda packages for windows are on anaconda.org, channel opensim_admin pending more testing and other platforms
