### ISSUE TITLE
DLL load failed while importing _simbody: The specified module could not be found

### ISSUE THREAD

**Issue by Star-Sky-18** [opensim-org/opensim-core#3517]
Hello, I followed the tutorial `Step-by-step instructions when using Anaconda with OpenSim 4.3+` in [Scripting in Python](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python) and successfully created the conda env `opensim_scripting`. However, when I tested it by `import opensim`, I got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\opensim_scripting\lib\site-packages\opensim\__init__.py", line 9, in <module>
    from .simbody import *
  File "C:\ProgramData\Anaconda3\envs\opensim_scripting\lib\site-packages\opensim\simbody.py", line 13, in <module>
    from . import _simbody
ImportError: DLL load failed while importing _simbody: The specified module could not be found
```
 Installing opensim and setting path variable were done previously.
 could you give me any idea to fix this?

**Comment by mrrezaie** [comment]
Hi, this post might be helpful: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=15999&p=45508&start=0&view=

**Comment by nickbianco** [comment]
Hi @Star-Sky-18, if you are still encountering difficulty when setting up scripting with Python, please post a question to the [OpenSim forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). We can assist you there.
