### ISSUE TITLE
A typo in TGCS 2023 documentation

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3518]
Hi, in section 2.3.3 in [ISB Technical Group on Computer Simulation (TGCS) 2023 OpenSim Workshop](https://simtk-confluence.stanford.edu:8443/display/OpenSim/ISB+Technical+Group+on+Computer+Simulation+%28TGCS%29+2023+OpenSim+Workshop):
`(base) C:\Users\me> conda activate tgcs2023` > `conda activate addbio-processing`

**Comment by nickbianco** [comment]
Thank you for catching this! Note that this page is a work-in-progress until next week, so we'll still be making changes and fixing typos for the next couple of days.
