### ISSUE TITLE
Should I be able to integrate a model if !isObjectUpToDateWithProperties()?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#352]
I tried the following:
1. model.initSystem() and integrate
2. change a property value
3. model.initializeState and integrate

For object for which I changed a property, its `extendFinalizeFromProperties()` method was not invoked upon performing (3). This means that I was able to integrate a model that was not finalized from its new properties.

I apologize if I'm missing some crucial piece of information here about how people are supposed to use the API.

**Comment by aymanhab** [comment]
@chrisdembia The convention used by the GUI when editing and that has been advocated (verbally at least) is to call initSystem again whenever a property value changes rather than initializeState since some property changes may potentially change the state layout.

**Comment by chrisdembia** [comment]
Thanks @aymanhab. That's what I have chosen to do. Since we have infrastructure to detect if properties have changed, do you think we should automate that call to initSystem or to finalizeFromProperties? Or at least throw an exception in the Manager or somewhere?
