### ISSUE TITLE
Problems trying to analyse kinetic and kinematic data with Anaconda + Python

### ISSUE THREAD

**Issue by JesusOlivaresJ** [opensim-org/opensim-core#3520]
Good morning,

I open this issue because I have unsuccessfully tried to conduct kinetic and kinematic analyses from OpenCap using Python.

First, I download Anaconda from the website, in the version for windows: [https://www.anaconda.com/](url).

Then, I carried out, step-by-step, every of the install requirements explained here, without experiencing any kind of issue in the process: [https://github.com/stanfordnmbl/opencap-processing](url).

The problem comes when I try tu run the examples **example.py** or **example_kinetics.py** through Spyder. In the former, specifically, when I run the first two lines of code, no problem in `import os`, but when I run the next one `import utilsKinematics,` it returns the next message:

`ModuleNotFoundError: No module named 'utilsKinematics'`

I tried some of the potential solutions provided here: [https://github.com/opensim-org/opensim-core/issues/3124](url), but the issue remains the same.

The version of the programmes I have installed are as follows:
Anaconda: **Anaconda3 (Python 3.11.3 64-bit)**
Python: **Python 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)] on win32**
OpenSim: **4.4-2022-08-12-dcf8e2cb1**
Visual Studio: **Visual Studio Community 2022**

I am really interested in conducting some analyses in a group of professional football players, but I am becoming a bit disappointed because I unsuccessfully tried them many times. Sure there is something I am doing wrong, but have no idea of what. I have some notions of programming in R, so I feel great with code, but am not familiarized with Python and its logic. That may be the reason.

Thank you in advance for your time and for the potential solutions provided.
Best regards,

**Comment by nickbianco** [comment]
Hi @JesusOlivaresJ, could you please post this issue to [stanfordnmbl/opencap-processing](https://github.com/stanfordnmbl/opencap-processing) since it is directly relevant to that repository? 

Closing the issue here.
