### ISSUE TITLE
opensim python API documentation 

### ISSUE THREAD

**Issue by alexsalguero** [opensim-org/opensim-core#3523]
I've been looking for python api documentation other than the examples, If you guys can point me to the right direction on where to find the opensim python api for developers would be appreciated.

**Comment by tkuchida** [comment]
- The Doxygen can be found here: https://simtk.org/api_docs/opensim/api_docs/
- Some Python-specific information can be found in the documentation on Confluence, specifically on the ["Common Scripting Commands"](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Common+Scripting+Commands) and ["Scripting in Python"](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python) pages

**Comment by alexsalguero** [comment]
Thank you! Hopefully they make a dedicated Python page. Another question how do you convert OpenSim c++ to OpenSim Python? For more advanced scripts.

**Comment by aymanhab** [comment]
@alexsalguero Typically users map the calls between the two languages because the control structures, iteration, syntax and the ecosystem is different, but we're open to ideas. In the meantime definitely now that we have a critical mass of users on python we should have a dedicated Python page.
