### ISSUE TITLE
Type mismatch between Input and Output throws cryptic exception, not the intended one.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#353]
When calling `getInput("a").connect(getOutput("b"))` and the types for the input and output don't match, I get a `std::bad_cast` which is not too helpful. I see that `Connector` has a type check and a useful exception [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/ComponentConnector.h#L165), but `Input` doesn't use this method for connecting [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/ComponentConnector.h#L225). Any reason?

**Comment by jenhicks** [comment]
Exception is there, but no test.
