### ISSUE TITLE
Ubuntu container build error: error: unmappable character for encoding ASCII 

### ISSUE THREAD

**Issue by cribe78** [opensim-org/opensim-core#3540]
I am attempting to build opensim-core in a Ubuntu based apptainer container for use on our RHEL based HPC system.  I have created an [apptainer definition file](https://github.com/cribe78/opensim-core/blob/main/scripts/build/Apptainer) based on [scripts/build/opensim-core-linux-build-script.sh](https://github.com/opensim-org/opensim-core/blob/main/scripts/build/opensim-core-linux-build-script.sh).  

When attempting to build the container, the "BUILDING OPENSIM-CORE" step reaches 100% before failing with these errors:

> [100%] Built target osimJavaJNI
> [100%] Compiling Java sources and creating jar archive.
> org/opensim/modeling/DeGrooteFregly2016Muscle.java:76: error: unmappable character for encoding ASCII
>  * Muscle Redundancy Problem. Annals of Biomedical Engineering, 44(10), 1???15.<br>
>                                                                          ^
> org/opensim/modeling/DeGrooteFregly2016Muscle.java:76: error: unmappable character for encoding ASCII
>  * Muscle Redundancy Problem. Annals of Biomedical Engineering, 44(10), 1???15.<br>
>                                                                           ^
> org/opensim/modeling/DeGrooteFregly2016Muscle.java:76: error: unmappable character for encoding ASCII
>  * Muscle Redundancy Problem. Annals of Biomedical Engineering, 44(10), 1???15.<br>
>                                                                            ^
> org/opensim/modeling/EllipsoidJoint.java:14: error: unmappable character for encoding ASCII
>  * mobilities ??? coordinated rotation and translation along the surface of an ellipsoid<br>
>               ^
> org/opensim/modeling/EllipsoidJoint.java:14: error: unmappable character for encoding ASCII
>  * mobilities ??? coordinated rotation and translation along the surface of an ellipsoid<br>
>                ^
> org/opensim/modeling/EllipsoidJoint.java:14: error: unmappable character for encoding ASCII
>  * mobilities ??? coordinated rotation and translation along the surface of an ellipsoid<br>
>                 ^
> org/opensim/modeling/SmoothSphereHalfSpaceForce.java:49: error: unmappable character for encoding ASCII
>  * Transactions on Neural Systems and Rehabilitation Engineering, 1???1.<br>
>                                                                    ^
> org/opensim/modeling/SmoothSphereHalfSpaceForce.java:49: error: unmappable character for encoding ASCII
>  * Transactions on Neural Systems and Rehabilitation Engineering, 1???1.<br>
>                                                                     ^
> org/opensim/modeling/SmoothSphereHalfSpaceForce.java:49: error: unmappable character for encoding ASCII
>  * Transactions on Neural Systems and Rehabilitation Engineering, 1???1.<br>
>                                                                      ^
> 9 errors
> gmake[2]: *** [Bindings/Java/CMakeFiles/JavaBindings.dir/build.make:83: Bindings/Java/src/org-opensim-modeling.jar] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:2437: Bindings/Java/CMakeFiles/JavaBindings.dir/all] Error 2
> gmake: *** [Makefile:146: all] Error 2

**Comment by nickbianco** [comment]
Hi @cribe78, it seems like there an issue with the file encodings in the Java bindings, specifically for the en-dash character. You should be able to manually set the encoding to UTF-8 in your environment [via the environment variables](https://github.com/opensim-org/opensim-core/blob/aeaaf93b052d598247dd7d7922fdf8f2f2f4c0bb/scripts/docker/ubuntu18.04/Dockerfile#L11).

**Comment by aymanhab** [comment]
Alternatively you can tell SWIG to ignore the comments in the source files so that they're not processed altogether.  The flag is SWIG_DOXYGEN and if you set it to false this issue should be fixed though you may have other issues downstream. Worth a try though

**Comment by cribe78** [comment]
Thanks, I have added the locale-gen command and the environment variables to the apptainer definition file and have successfully built the container.
