### ISSUE TITLE
Add `ModelOperator` for adding `PrescribedMotion` constraints to model coordinates based on data stored in a file

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3559]
Based on discussions with @bfregly.

**Comment by AllisonJohn** [comment]
https://github.com/opensim-org/opensim-core/blob/8b7acc3d5f7e7b6581467adf49f9d16d7b80de06/OpenSim/Moco/Test/testMocoConstraints.cpp#L719
- convert coordinates to functions w gcv splineset
