### ISSUE TITLE
Support for pip

### ISSUE THREAD

**Issue by joshgalvan** [opensim-org/opensim-core#3568]
OpenSim should be easily installable into any python environment via pip. The steps to currently get opensim working in Python are convoluted, and should be as simple as:
```
conda create --name opensimdev python=3.8
pip install opensim 
```
Or whichever Python version is required. I'm not even sure which one is needed because I haven't been able to successfully `import opensim` yet, but I believe it's 3.8.

I don't know enough about the project to know why it's *not* done this way, but I believe there should be an effort to get this to happen. The current way of running scripts found in install directories and cd-ing around and potentially modifying PATHs is abnormal.

**Comment by aymanhab** [comment]
Although we may support pip in the future, we currently support anaconda which is slightly different but less python centric. Please check this page for the differences https://www.anaconda.com/blog/understanding-conda-and-pip
and here's the page to install the opensim conda package 
https://anaconda.org/opensim-org/opensim

**Comment by joshgalvan** [comment]
Thank you! I'm unsure if all of the previous steps of running certain scripts in certain directories helped or not, but after conda installing the package I was able to successfully import opensim. I'm not sure how I missed the alert about conda support at the top of [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python#ScriptinginPython-SettingupyourPythonscriptingenvironment). But thank you again!

I'd say supporting conda in this way is just as useful as pip, and was the heart of opening the issue in the first place, so I'm okay with this being closed.
