### ISSUE TITLE
[Feature Request] Expose getCoordinatesInMultibodyTreeOrder() for Python/MATLAB users

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3569]
Hi, I'm trying to get the coordinates in multibody tree order (not CoordinateSet order), but I get this Swig object which means [getCoordinatesInMultibodyTreeOrder()](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Model.html#a31ba542fd1461f1533bd0813adbeec39) is not exposed yet.
`<Swig Object of type 'std::vector< SimTK::ReferencePtr< OpenSim::Coordinate const >,std::allocator< SimTK::ReferencePtr< OpenSim::Coordinate const > > > *' at 0x000001B5680FB300>`
And sometimes it prints:
`swig/python detected a memory leak of type 'std::vector< SimTK::ReferencePtr< OpenSim::Coordinate const >,std::allocator< SimTK::ReferencePtr< OpenSim::Coordinate 
const > > > *', no destructor found.`

In general, I think it would be great if OpenSim uses same order in all its tools. For example, the InverseDynamics tool uses multibody tree order, whereas InverseKinematics, BodyKinematics, RRA output, and etc. use CoordinateSet order.

**Comment by mrrezaie** [comment]
Hi @aymanhab, Thanks for adding this feature.

I just tested this method in version `4.5-2023-11-26-efcdfd3eb` via Conda package and the output is a tuple of `opensim.simulation.ReferencePtrCoordinate` objects. When I call `getName()` in any of them, Python crashes. I tried to convert it to an `opensim.Coordinate` object using `safeDownCast`, but this error appears:

```python
for i in model.getCoordinatesInMultibodyTreeOrder():
	# i.getName() # interrupts Python
	coordinate = osim.Coordinate.safeDownCast(i) # rises error


Traceback (most recent call last):
  Cell In[6], line 2
    coordinate = osim.Coordinate.safeDownCast(i)
  File F:\Python311\Lib\site-packages\opensim\simulation.py:6477 in safeDownCast
    return _simulation.Coordinate_safeDownCast(obj)
TypeError: in method 'Coordinate_safeDownCast', argument 1 of type 'OpenSim::Object *'
```
I don't know how to use it.

Thank you!!!

**Comment by aymanhab** [comment]
Thanks for testing @mrrezaie, the type system suggest that you get a list of ReferencePtrCoordinate which has mutiple methods to get the Coordinate 
https://github.com/opensim-org/opensim-gui/blob/cfbf426585be7310e7f4a8168a96a8ff747415f0/Gui/opensim/modeling/src/org/opensim/modeling/ReferencePtrCoordinate.java#L123
I'll check if any of these methods is available and works in python.

**Comment by mrrezaie** [comment]
@aymanhab Thanks for your response. I just tested this one and the output is nothing:

```python
tree = model.getCoordinatesInMultibodyTreeOrder()
item1 = tree[0].get()
print( type(item1) )

NoneType
```
