### ISSUE TITLE
Unable to do Kinematics with IMU data tutorial with OpenSense via Python, error is given

### ISSUE THREAD

**Issue by joshgalvan** [opensim-org/opensim-core#3571]
The tutorial I'm referencing and trying to complete is [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/OpenSense+-+Kinematics+with+IMU+Data#OpenSenseKinematicswithIMUData-HowtoSetuptheOpenSenseTools).

I specifically am unable to complete step 2 in Python. The OpenSim forum topic I opened explaining the issue is [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=17014&p=0&start=0&view=).

Essentially, when calling:
 `osim.STOFileAdapterQuaternion.write(quaternionTable, [xsensSettings.get_trial_prefix(), '_orientations.sto'])`

I get the error:
`TypeError: in method 'STOFileAdapterQuaternion_write', argument 2 of type 'std::string const &'`

The MatLab example in the tutorial wraps `xsensSettings.get_trial_prefix()` with `char()`, so perhaps the function is expecting a char array, which is not doable in Python as far as I know. Anyone know how I am supposed to do this in Python?

My full script is here:
```python
import opensim as osim
import os

ROOT = "C:\OpenSim 4.4\Resources\Code\Python\OpenSenseExample"

xsensSettings = osim.XsensDataReaderSettings(os.path.join(ROOT, 'myIMUMappings.xml'))
xsensReader = osim.XsensDataReader(xsensSettings)

tables = xsensReader.read(os.path.join(ROOT, 'IMUData', ''))
quaternionTable = xsensReader.getOrientationsTable(tables)

osim.STOFileAdapterQuaternion.write(quaternionTable, [xsensSettings.get_trial_prefix(), '_orientations.sto'])
```

And again, fails due to the last line.

**Comment by joshgalvan** [comment]
While I'm here, and although this is slightly unrelated, am I able to do kinematics with IMU data straight from quaternion values? I have the quaternion values of my IMUs already, and I don't need them to be created for me, is there a way to do this?

**Comment by aymanhab** [comment]
Is there a reason you can't write the files and proceed starting from Step3 onward (calibration)? I believe the interface from the tool requires files but it's possible to interface with the underlying API functions using Tables (in memory). This seem to belong to the forum discussion as no specific issue to address here. 
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=17014&p=0&start=0&view=&sid=dfcfa7233f2782438922c50521776141

**Comment by joshgalvan** [comment]
Yes, the resolution to my problem is in the forum post. I had to create the variable before passing it into the function, which ideally wouldn't make a difference.

And yes again, I see that the STO file is practically just a CSV which I can replicate, but the file extension suggests otherwise. I feel it would be better to just use CSVs instead of creating a STO filetype.

**Comment by aymanhab** [comment]
Thanks for reporting. The standard csv format typically have one delimiter, for the case of quaternions for example, we store groups of four numbers that are comma separated to represent one quaternion. We can (and probably will at some point) handle this grouping in the header but as of now our parsers are custom built  to handle specific element types/formatting.
