### ISSUE TITLE
Conda installs wrong OpenSim package

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3574]
Hi, in my system (Win10), this command `conda install -c opensim-org opensim-moco` leads to installing `opensim-moco-4.4-py37np120`, while I'm using miniconda with Python 3.11. So, I have to use `conda install -c opensim-org opensim-moco=4.4.1=py311np123`. I think something is wrong here. Thank you.

**Comment by nickbianco** [comment]
Hi @mrrezaie,

The conda installer does not automatically detect which Python version your environment has, so you must specify the version in the install command (as you have done above). So nothing is wrong here :)

**Comment by aymanhab** [comment]
I'd just clarify that the package name on https://anaconda.org/opensim-org/opensim-moco/files has a little "i" next to the file name for info next to it that indicates what dependencies it has. Conda uses these to solve for a python/numpy/other version of packages that it needs. If you need a python 3.7 version with moco, you should create that plain python 3.7 conda environment and try to install opensim-moco package in it, if that works as expected then it must be other packages in your environment that cause the wrong solve.

**Comment by nickbianco** [comment]
(Perhaps I closed this too early...)

@aymanhab, I think the issue is that @mrrezaie was expecting the OpenSim/Moco version built with Python 3.11 to be installed into his Python 3.11 environment. If it's possible to make that happen in conda so users don't have to look up the install command for every environment, that would be nice upgrade.

**Comment by mrrezaie** [comment]
Thanks for your response. Yes, I was expecting the latest (4.4.1) and **compatible (py311)** version, not an outdated (4.4.0) and **incompatible (py37)** one. Thanks again.

**Comment by mrrezaie** [comment]
@aymanhab @nickbianco I just checked Pandas for py311 and it defines the Python dependency as follows:

![image](https://github.com/opensim-org/opensim-core/assets/38867713/9f57e8c2-ad3e-4c33-9386-6f974ed56c55)

This may help!!!

**Comment by aymanhab** [comment]
The problem actually is not with the new 4.4.1 packages which specify python versions correctly but rather with the old packages (4.4 for python 3.7, 3.8, 3.9) which didn't specify a python version altogether thus misleading conda-solve to think that they would work with any python version including 3.11. I'll update the manifest of these old packages to make sure they don't get in the way. In the mean time you can try the channel for opensim_admin which doesn't have these old/bad packages to see if you get the correct opensim-moco package for your python.

**Comment by aymanhab** [comment]
@mrrezaie The old packages of opensim-moco on opensim-org channel have been updated, please retry and let us know if this problem has been solved so that we can close the issue. Thanks for reporting and testing

**Comment by mrrezaie** [comment]
Thanks @aymanhab. Now it picks the correct version.

**Comment by mrrezaie** [comment]
@aymanhab the python dependency of [osx-64/opensim-4.4-py37np121](https://anaconda.org/opensim-org/opensim/files) package doesn't have any version either. This may cause problem for macOS users.
