### ISSUE TITLE
python_opensim API ：  Integrator step failed at time ，how solve it? thanks

### ISSUE THREAD

**Issue by chenyaru-dear** [opensim-org/opensim-core#3582]
It is the issues:

Integrator step failed at time 1.0129351827410737 apparently because:
SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
  Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 1.01294.
  (Required condition 't1 > t0' was not met.)

**Comment by nickbianco** [comment]
Hi @chenyaru-dear, I think the integrator encountered stiffness in your problem and began taking very small timesteps until it failed. Unless you think this is a software bug, please post this issue to the OpenSim forum with more details about your simulation, and we can help you further there.
