### ISSUE TITLE
No clear method to set the units for marker data table

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3589]
Basically metadata in tables have been not exposed to scripting intentionally, and the custom method added to workaround this are all getters, we need a method to set units meta data from matlab.python.

**Comment by nickbianco** [comment]
Does [`addTableMetaData`](https://github.com/opensim-org/opensim-core/blob/81c2455e13f953b4d83bc988107b60ebc3071889/OpenSim/Common/AbstractDataTable.h#L220) not work in scripting?

**Comment by aymanhab** [comment]
Not really, either throws that the key doesn't exist or takes a key, value pair but later ignored and the header is unaffected.

**Comment by aymanhab** [comment]
I think this should be fixed in 4.5
