### ISSUE TITLE
Serialization of Connections is verbose

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#359]
Connections can be serialized as glorified Properties from the XML side with exactly three attributes: type, name and connected_to_name, instead of the current xml representation:

```
 <connectors>
    <Connector_PhysicalFrame_ name="frame">
        <!--Name of the component this Connector should be connected to.-->
        <connected_to_name>ground</connected_to_name>
    </Connector_PhysicalFrame_>
</connectors>
```

An example simpler syntax,

```
<Connector type="PhysicalFrame" name = "frame" connected_to="ground" />
```

would do the job, and avoids making up syntax to serialize templates.

It'd be good to investigate this before we propagate connections all over our xml files.

**Comment by chrisdembia** [comment]
@aymanhab, `<` and `>` seem to have some special meaning in Markdown. I edited your post so that we can now see your code samples (put code samples between pairs of 3 backticks: 

![image](https://cloud.githubusercontent.com/assets/846001/6312766/e0b5175a-b93a-11e4-92e0-e0823b00f15c.png)

**Comment by chrisdembia** [comment]
+1

I agree that the current syntax is very verbose, and I really like the proposed syntax.    Is it possible? What about a type with multiple template arguments?

**Comment by sherm1** [comment]
+1
Nice syntax!

**Comment by aymanhab** [comment]
Thanks @chrisdembia and @sherm1 for the feedback. I think it's possible, I just wanted to start the discussion to see how others feel about it, then we can discuss the pros, cons and implementation.

**Comment by aseth1** [comment]
I also agree the brevity of the proposed syntax is nice. @aymanhab How easy is it for you to make the change? Would you the have a Connector factory to create the concrete type?

If we didn't require people to build models via XML editing, would the verbosity even matter?

**Comment by chrisdembia** [comment]
> If we didn't require people to build models via XML editing, would the verbosity even matter?

Not as much but yes, to view their model. Also, I think if we support a plain-text serialization format, we should support it well. I actually wasn't thinking of the verbosity in terms of having to type up all of that when creating XML; I just thought it was too much to look at when reading XML. I like the idea that one line of XML contains roughly one unit of useful information.

**Comment by aymanhab** [comment]
@aseth1 I think the implementation "should" be straightforward (basically after deserialization, pass XML into a Factory that creates the concrete class) but I may need some template gymnastics help from the template-jedi-master @sherm1), do you think that's feasible, @sherm1 ?

The issues that triggered this are:
1. When converting a frame_name property into a frame connector for geometry, comparing the files before and after was quite messy and sifting through tags to find the relevant attributes/values was time consuming (similar to what @chrisdembia suggested). This will be similar issue for other developers doing similar conversions as we realize the benefits of connections.
2. Converting old files code gets more complicated by the extra tags/levels, this will get harder to maintain.
3. I'm hoping this can eliminate the need to register Connector<T>() for every type that needs to be used as a connector which doesn't scale easily.

It's true that eventually most of the XML maybe hidden behind the GUI but we know this will take sometime before it's completely adopted by all users.

**Comment by sherm1** [comment]
> do you think that's feasible, @sherm1?

Not knowing any of the specifics, I would say: of course!

**Comment by aseth1** [comment]
@aymanhab @chrisdembia these are all good points! I agree that registering concrete Connectors is a pain! I would really love to see that go away. It seems like you have a plan - so go for it!

**Comment by aymanhab** [comment]
Update on this issue:

- getDefaultInstanceOfType(tag) (need to be replaced by a Factory that takes the XML element) not-bad one step toward decoupling Objects from XML.
- (de)serialization of connected_to as an attribute rather than element is unsupported since this's handled now by base class.
One option is to make Connector into a special Property and override read/write to XML but seems quite invasive and diverting the overall Properties mechanism. Reporting and tracking changes mechanism.

**Comment by chrisdembia** [comment]
It seems like we might want to be able to support using tags more generally. Then, people could have the option of using the more concise syntax above for any property:

<Body name="pelvis" mass_center="0 1 0.5"><some_property>hello</some_property></Body>

The syntax that Ayman presented above is what MuJoCo uses for its XML serialization (everywhere).

**Comment by aseth1** [comment]
I somewhat disagree that we should support readable text serialization. We've been forced down that path because we don't have other ways of editing. I wonder if it is a productive use of time to compress 3 lines to 1 of XML at the expense of viewing and building models in the GUI. The current format should have no bearing on model building. If you can make connections in the GUI you don't need to edit XML. Even from the XML structure perspective there are other more pressing issues in this regard with respect to Body Inertia taking 6 lines, the use of Sets with objects and groups, VisualObject and DisplayGeometry and precedence of transforms, ... that both take up a lot of real-estate and are unclear in terms of redundancy, unused flags, etc...

My 2 cents is that we could use our time more effectively addressing other issues, especially since this change seems more complicated than anticipated.

**Comment by sherm1** [comment]
> I somewhat disagree that we should support readable text serialization.

Good points!

**Comment by aymanhab** [comment]
Although I support readable, less cluttered text format, for developers in the short term and for users in the intermediate/long term but this requires significant changes and should be handled in a more general revamp of serialization that decouples serialization from modeling abstractions. I just wanted to document my findings for the next time we tackle this issue and I'll move it to the icebox.

Thanks all for the feedback.
