### ISSUE TITLE
RuntimeError when closing the visualizer window

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3597]
Hi, when I close the visualizer window, a RuntimeError would be displayed in the console:

<code>File F:\Python38\Lib\site-packages\opensim\simulation.py:35977 in showMotion
return _simulation.VisualizerUtilities_showMotion(arg1, arg2)
RuntimeError: std::exception in 'void OpenSim::VisualizerUtilities::showMotion(OpenSim::Model,OpenSim::TimeSeriesTable)': SimTK Exception thrown at VisualizerProtocol.cpp:603:
   Error detected by Simbody method VisualizerProtocol: An attempt to write() 4 bytes to pipe 10 failed with errno=22 (Invalid argument).
   (Required condition 'status!=-1' was not met.)</code>

However, it doesn't interrupt anything, and the Python session remains interactive. There is similar error posted here but at different circumstances: https://github.com/opensim-org/opensim-core/issues/2586, https://github.com/opensim-org/opensim-core/issues/3144

Windows 10
OpenSim 4.4.1
Python 3.8

**Comment by nickbianco** [comment]
Hi @mrrezaie, to exit the visualizer without error, you need to hit the Esc key twice while the visualizer is the current window. While I agree, it would be nice to simply exit the window without error, this has been the behavior for some time and we don't have any current plans to change it.

**Comment by mrrezaie** [comment]
> to exit the visualizer without error, you need to hit the Esc key twice while the visualizer is the current window.

Great, thank you.
