### ISSUE TITLE
CreateForceSetOfCoordinateActuatorsForModel causes segmentation fault through Python API

### ISSUE THREAD

**Issue by itbellix** [opensim-org/opensim-core#3598]
Hi,
I am running into troubles when using the method [CreateForceSetOfCoordinateActuatorsForModel](https://github.com/opensim-org/opensim-core/blob/bf77d327bfbc2f00bdeba6610078071387abc08d/OpenSim/Simulation/Model/Model.cpp#L620) for a `CoordinateActuator` object in the Python API.

The script that reproduces the error for me is the following: 
```python
model = opensim.Model(pathOpenSimModel)     # for example, the arm26.osim model
state = model.initSystem()

# append generalized forces to the model
coordActDummy = opensim.CoordinateActuator()    # dummy coordinate actuator to access required function
optimalForce = 1                                # optimal force [N or N/m] for every new actuator
includeLockedAndConstr = False                  # actuators are not created for locked and constrained coordinates
coordActDummy.CreateForceSetOfCoordinateActuatorsForModel(state, model, optimalForce, includeLockedAndConstr)
```

I have tested it with the `arm26.osim` model, but also with other models that I have, and the last line appears problematic (even when changing the `includeLockedAndConstr` to `True`). When running the the provided script, I have a segmentation fault error. However, this does not happen always (i.e., I was able to run the provided code once or twice, but not consistently).

I am using OpenSim in Ubuntu 20.04, through Python, and I see the same problem if I use a [custom build](https://github.com/opensim-org/opensim-core/wiki/Build-Instructions#linux) of OpenSim, or if I use the [conda package](https://anaconda.org/opensim-org/opensim).

**Comment by nickbianco** [comment]
Hi @itbellix, thanks for the bug report. Not sure where the segfault is without setting up a build, but if you're looking for a way to add a set of `CoordinateActuators`s to a model, you could use a `ModelProcessor` with `ModOpAddReserves`:

```python
import opensim as osim

modelProcessor = osim.ModelProcessor(pathOpenSimModel)
optimalForce = 1
modelProcessor.append(osim.ModOpAddReserves(optimalForce))

model = modelProcessor.process()
```

This simply adds a set of `CoordinateActuator`s to the model (for coordinates that do not already have an actuator associated with it), and doesn't mess around with `ForceSet` ownership or invalidating the system like `CreateForceSetOfCoordinateActuatorsForModel` does.

**Comment by itbellix** [comment]
Hi @nickbianco, thank you very much for your quick reply! Indeed, the code you provided has the behavior that I was trying to get, without resulting in errors :)

**Comment by nickbianco** [comment]
Great! We can hold on to this issue to decide what to do with `CreateForceSetOfCoordinateActuatorsForModel`. My preference would be to remove it, but we'd need to discuss if that would break a lot of legacy code.

**Comment by nickbianco** [comment]
It turns out `CreateForceSetOfCoordinateActuatorsForModel` is used by `InverseDynamics` and `StaticOptimization`, so we can't outright remove it without modifying those tools.

@itbellix you were probably getting a segfault because that function returns a raw pointer to a new `ForceSet` objects and the memory was not handled properly.
