### ISSUE TITLE
Moco :Java exception occurred: It may not exist or you do not have permission to read it. 

### ISSUE THREAD

**Issue by ranakp** [opensim-org/opensim-core#3599]
Hi,
I am new to Moco. I was trying to run the Moco Matlab example, example2DWalking.m, in Windows and it gave me the following permission error. I was wondering if anyone knows where those permissions can be edited.
I'd appreciate help! 

Java exception occurred:
java.lang.RuntimeException: Object: Cannot open file 2D_gait.osim. It may not exist or you do not have permission to read it.
	Thrown at Object.cpp:105 in Object().

	at org.opensim.modeling.opensimMocoJNI.MocoTrack_initialize(Native Method)

	at org.opensim.modeling.MocoTrack.initialize(MocoTrack.java:695)

**Comment by nickbianco** [comment]
Hi @ranakp, where did you install OpenSim on your machine? You could try installing in a different directory that doesn't require permissions.

**Comment by aymanhab** [comment]
@nickbianco Can we check if this runs for you in installation, and if so close as potential environment issue? If installation in another folder fixes the problem then it's install issue. Please let us know @ranakp

**Comment by nickbianco** [comment]
@aymanhab, it seems like an installation issue to me. I'm fine closing this if we get no response.

**Comment by ranakp** [comment]
Thank you both, @nickbianco and @aymanhab! It was an installation path issue, it is working now. Thanks for the prompt responses
