### ISSUE TITLE
Add message logging/handling service

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#36]
OpenSim and its Component builders need a way to provide debug and other component messages in a systematic way. Users should be able to choose the level of messaging from non to the most fine Optimizer details. I propose that Component could maintain the messages with an assigned priority/verbosity level which the Component builder can specify using `addMessage(string msg, level)` like methods we have for Output, StateVariable, etc...  One of the advantages of this approach is that it would make it easy to have selective verbosity- for example having only Muscles running with full verbosity to debug muscle related issues.

- [x] Common (@chrisdembia )
  - [x] Reporter (@chrisdembia )
- [x] Simulation (@aymanhab )
- [x] Actuators
- [x] Analyses (@nickbianco)
- [x] Tools (@nickbianco )
- [x] Applications (@carmichaelong )
- [x] Change logging level with command-line flag. (@nickbianco )
- [x] Adding/removing custom sinks.
- [x] Test logging in Matlab on Windows. (@aymanhab )
- [x] Test logging in Matlab on Mac. (@aymanhab )
- [x] Disable/remove old logging infrastructure (LogManager, etc.)
- [x] Test logging in GUI on Mac (@chrisdembia )
- [ ] User documentation for how to change the log level in CONTRIBUTING.md (@chrisdembia )
  - [ ] Create private Confluence page.
- [x] Find and replace usages of cerr, cout, and printf. (@chrisdembia )

**Comment by sherm1** [comment]
Nice that the easylogging++ guy is responsive! I filed an issue there to see if he'll fix his use of illegal identifier names (standard prohibits leading underscores): easylogging/easyloggingpp#239.

**Comment by mkhan3189** [comment]
Legal identifiers are successfully implemented from [Easylogging++ v9.79](https://github.com/easylogging/easyloggingpp/releases/tag/v9.79)

**Comment by sherm1** [comment]
> Legal identifiers are successfully implemented from Easylogging++ v9.79

Thanks, Majid!

**Comment by chrisdembia** [comment]
What do y'all think about renaming the output files?

```
out.log -> opensim_output.log
err.log -> opensim_error.log
```

**Comment by tkuchida** [comment]
>What do y'all think about renaming the stream output files?

:+1:

**Comment by chrisdembia** [comment]
Another 1-header logging library: https://github.com/emilk/loguru.

Getting component-level logging seems like the most challenging part of all of this; I'd advocate getting just *some* logging working, then we can worry later about improving it.

**Comment by chrisdembia** [comment]
In TODO, @aseth1 said:

> The validationLog log mechanism as implemented by Model is not sufficient to relay messages generated by Components of the Model. As it stands a Component is able to complain (throw an Exception) if its properties are invalid and in its extendFinalizeFromProperties it throws or handles them but there is not mechanism to write to a common validationLog and certainly no way to get access to the Model's log.

> In the case of duplicates they are renamed automatically and we can write a message to the console, but the Model's validation log is not accessible by the Component. Component is not and should not be aware of concrete types so I rejected the idea of traversing up the ownership tree to get the Model to append to its log.

> Pushing validationLog down to Component is possible but then the issue is handling the fact that every Component has a log and composing them is not trivial (and a potential waste). We could make validationLog a singleton shared by all Components. Then the same log can be accessed by different components, which may not be desirable.

> @aymanhab @chrisdembia @tkuchida how would you like the messaging to work (at first)? @aymanhab i think your intention was to keep it very simple and have a direct way for Model to relay warnings to users during loading, but it seems to me we might want to control what bubbles up to users and what doesn't based on a warning/messaging level, and in that case it seems what is in place will not work.

**Comment by chrisdembia** [comment]
There's a nice new logging library `spdlog` that is either header-only or just 2 files:

https://github.com/gabime/spdlog

**Comment by sherm1** [comment]
We've been happy users of spdlog in Drake for a long time.

**Comment by chrisdembia** [comment]
Oh that's useful to know! Do you use the `spdlog` namespace as-is or do you modify it somehow to fit better within Drake? Do you copy the source code or bring it in as a third-party dependency?

**Comment by sherm1** [comment]
Drake has dozens of external dependencies and almost never incorporates the code locally. Instead we use Bazel to pull the code from its repo and build it locally, specifying a particular SHA and then upgrading those frequently to stay current. Here is the Drake directory containing the instructions for fetching the external: https://github.com/RobotLocomotion/drake/tree/master/tools/workspace/spdlog

In the code we just use the `spdlog::` namespace as-is.

**Comment by aymanhab** [comment]
Thanks @sherm1 for chiming in, definitely looks very promising.

**Comment by chrisdembia** [comment]
Chris: Actuators, Analyses
Nick: Tools
Carmichael: Applications folder

**Comment by chrisdembia** [comment]
List the print() functions and decide whether or not this is logged.

**Comment by chrisdembia** [comment]
I'll take ExampleComponents.

**Comment by chrisdembia** [comment]
I'll leave Simulation to someone else, though I am creating a PR soon in which I did update ControlSet.cpp.

**Comment by chrisdembia** [comment]
I'm also working on Common.

**Comment by chrisdembia** [comment]
I updated the checklist in the top post based on our dev meeting today.

**Comment by aymanhab** [comment]
Tested logging in Matlab/Windows. Default behavior is nothing to shell, all messages go to opensim.log, changing level indeed changes what's written to the file. What else to test?

**Comment by chrisdembia** [comment]
Run the following and ensure that you see output in the Matlab Command Window.

```
import org.opensim.modeling.*;
m = Model();
m.print('testing.osim');
Model('testing.osim');
disp('pre');
Logger.addSink(JavaLogSink());
Model('testing.osim');
```

Ensure that you only see OpenSim output after `pre`

**Comment by aymanhab** [comment]
Thanks @chrisdembia this worked as described 👍 

Separately I tried to call Logger.addFileSink and that didn't create a file but this seems unrelated to Matlab so I'd mark Matlab testing done.

**Comment by chrisdembia** [comment]
Great!
