### ISSUE TITLE
ComponentListIterator() is potentially costly due to dynamic casting.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#361]
Ajay and I discussed renaming getComponetList<T>() to formComponentList<T>(), but that wouldn't help, b/c the dynamic cast occurs when incrementing the iterator.

**Comment by aymanhab** [comment]
@chrisdembia as far as I can tell, to do selection you have to do visiting which is inherently order n for any data structure that contains n elements. The only optimization that can be done is caching lists of particular type, if type is fixed, but then maintenance becomes harder. If somebody needs to access same list over and over, he/she can build the cache themselves but I'm open to other suggestions.

**Comment by chrisdembia** [comment]
Okay I agree. Maybe we can close this.

**Comment by aymanhab** [comment]
@chrisdembia One thought that occurred to me is to create a BufferedIterator that internally caches the objects it iterates over. Should be pretty easy to implement and could be done lazily as well.

**Comment by chrisdembia** [comment]
Great idea. We should definitely do some profiling and find out if it's worthwhile.
