### ISSUE TITLE
Fix debug builds 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3610]
Following errors are reported in debug build on windows (not exercised by ci):
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0167	argument of type "const ConstantCurvatureJointImpl *" is incompatible with parameter of type "const OpenSim::Object *"	osimSimulation	D:\dev\src\opensim-core\OpenSim\Simulation\SimbodyEngine\ConstantCurvatureJoint.cpp	681	
Multiple times due to calling OPENSIM_ASSERT_FRMOBJ from non OpenSim::Object, ConstantCurvatureJointImpl in this case.
Other compilation failures in the same file due to invoking OPENSIM_ASSERT_FRMOBJ  from static methods

**Comment by nickbianco** [comment]
@aymanhab, should we include this fix for the 4.5 release? If so, I could handle it.

**Comment by aymanhab** [comment]
Sure, thank you @nickbianco
