### ISSUE TITLE
unable to connect to github.com

### ISSUE THREAD

**Issue by 123-one** [opensim-org/opensim-core#3641]
when i run "git clone https://github.com/opensim-org/opensim-core.git"
it shows"unable to connect to github.com"

**Comment by tkuchida** [comment]
Some suggestions can be found here: https://stackoverflow.com/questions/16298986/unable-to-connect-to-github-com-for-cloning

**Comment by nickbianco** [comment]
Closing, since this is not an issue with this repo.
