### ISSUE TITLE
Can setObjectIsUpToDateWithProperties() be private?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#365]
Maybe components shouldn't be allowed to tell the base Component that they are up to date; that perhaps can be managed completely by the base Component. This came up in #364. 

Right now, there are three "places" that this method is used: in MillardMuscle-related classes, in StaticOptimization, and in Model. It seems very likely that MillardMuscle and StaticOptimization don't need to call this method. It's not clear if Model needs to or not.

**Comment by sherm1** [comment]
Ajay sez: Protected yes, private no. Do you want to close this now, Chris?

**Comment by jimmyDunne** [comment]
wud up @chrisdembia ? wat u wanna do?
