### ISSUE TITLE
Wrap PhysicalOffsetFrame for use in python, etc., and write tests

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#368]
Right now, Frame and PhysicalFrame are.

**Comment by aseth1** [comment]
Yes, PhysicalOffsetFrame is going to be a key part of defining Joint and muscle attachment locations, etc..

**Comment by aymanhab** [comment]
@chrisdembia Definitely. I've been updating the wrapping for Java to use in GUI (the changes have been on geometry_v2 branch), I was planning to update both Java & python wrapping before merge. Please let me know if you need it faster.

**Comment by chrisdembia** [comment]
Nope, no rush.

**Comment by aymanhab** [comment]
@chrisdembia This should be closed with the merge of geometry branch. Please confirm.

**Comment by chrisdembia** [comment]
Good to know. Are there tests? At least for python, I think we should wait to merge this until we have tests.

**Comment by chrisdembia** [comment]
At least in the python tests, we should try constructing some joints with the PhysicalOffsetFrames.
