### ISSUE TITLE
Model Loading error 

### ISSUE THREAD

**Issue by clodICL** [opensim-org/opensim-core#3720]
OpenSim does not open a model I modified and I get the following error: 'Joint::getMotionType() given an invalid CoordinateIndex
	Thrown at Joint.cpp:224 in getMotionType().'

How do I identify the joint ??

Thanks!

**Comment by tkuchida** [comment]
(1) You may have a kinematic loop of body-joint-body-joint... ending up back at the first body. In that case, the issue wouldn't be with a <i>particular</i> joint; replacing any joint in the loop with a constraint would resolve the issue (theoretically). (2) Additional context about what model you are using and how you modified it would be helpful. (3) Finally, questions like this should be posted to the [User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91), not GitHub which is for development-related tasks.
