### ISSUE TITLE
Matlab scripting - Java Exception Error on Mac (m3)

### ISSUE THREAD

**Issue by GianCarp** [opensim-org/opensim-core#3721]
Hi, 

I get the following error when following the steps on [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+with+Matlab) for setting up scripting in matlab. 

>> org.opensim.modeling.opensimCommon.GetVersion()
Java exception occurred:
java.lang.NoClassDefFoundError: Could not initialize class org.opensim.modeling.opensimCommonJNI
	at org.opensim.modeling.opensimCommon.GetVersion(opensimCommon.java:25)

Running mac m3 chip. Any advice appreciated. 

Cheers

**Comment by aymanhab** [comment]
Please use the Intel Mac distribution of matlab rather than native apple Silicon as this is the architecture published in the official opensim distribution.

**Comment by GianCarp** [comment]
> Please use the Intel Mac distribution of matlab rather than native apple Silicon as this is the architecture published in the official opensim distribution.

Thanks, working now!
