### ISSUE TITLE
Add opencap models to list of available models

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3723]

**Comment by nickbianco** [comment]
@AlbertoCasasOrtiz, I think the default models might live the AddBiomechanics S3 bucket somewhere under a directory called "PresetSkeletons" (e.g., `/PresetSkeletons/Rajagopal2015_ViconPlugInGait.osim`). Could you confirm that for me? I'll ask Antoine about the OpenCap models.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @nickbianco, looks like that is the case, at least that is how it is referenced in multiple places of the code like [here](https://github.com/keenon/AddBiomechanics/blob/6c9f0340c8e6a503d15d778610b70b93720d073c/server/engine/src/subject.py#L246).

**Comment by AlbertoCasasOrtiz** [comment]
Wrong repository, this is an AddBiomechanics issue.
