### ISSUE TITLE
opensim CMC  result question

### ISSUE THREAD

**Issue by 123-one** [opensim-org/opensim-core#3736]
![屏幕截图 2024-03-12 140158](https://github.com/opensim-org/opensim-core/assets/54674049/9d01d298-71c8-44df-9d25-7fb96623547b)
![屏幕截图 2024-03-12 140213](https://github.com/opensim-org/opensim-core/assets/54674049/982438fc-bbf6-45c2-8c3f-e2b6e16e32f6)
![屏幕截图 2024-03-12 140224](https://github.com/opensim-org/opensim-core/assets/54674049/3108aaad-faec-4672-a0e7-500a05e069eb)
![屏幕截图 2024-03-12 140235](https://github.com/opensim-org/opensim-core/assets/54674049/847cc878-2318-473a-8310-4166c30dbca6)
![image](https://github.com/opensim-org/opensim-core/assets/54674049/a4b3088a-51ba-4668-893c-d62f42e21641)
![image](https://github.com/opensim-org/opensim-core/assets/54674049/43411b4f-50ab-41e3-a225-350e0a464f44)

The screenshot of my CMC simulation operation is as above, but the result of my operation shows that the muscle force of wearing exoskeleton in the medial muscle of the femur is too low, while the part of wearing exoskeleton in the semimembrane muscle is too high. May I ask what caused it?

**Comment by tkuchida** [comment]
Perhaps you could ask your question on the [User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91). GitHub Issues are intended for tracking tasks related to the development of the software.
