### ISSUE TITLE
Wrong OpenSim path in all cpp files

### ISSUE THREAD

**Issue by hmejbri** [opensim-org/opensim-core#3737]
All cpp files include the wrong path to the OpenSim folder "OpenSim/.." which in my case should be "/home/ubuntu/dw/opensim-core/OpenSim/..."

So when i execute `g++ -o opensim-visualize opensim-visualize.cpp -lOpenSim`

I get the error 
`opensim-visualize.cpp:33:10: fatal error: OpenSim/Common/IO.h: No such file or directory
   33 | #include <OpenSim/Common/IO.h>
`

**Comment by nickbianco** [comment]
Hi @hmejbri, you can try pointing to the OpenSim headers you want to include via an include path in your GCC command:

`g++ -o opensim-visualize opensim-visualize.cpp -I/home/ubuntu/dw/opensim-core -lOpenSim`

**Comment by nickbianco** [comment]
Since this is not really a bug or an issue with our build system, I am closing this issue.
