### ISSUE TITLE
Error on low activated DeGroote muscles at specific poses

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3739]
Hi, following [this post on forum](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=17655&p=0&start=0&view=&sid=93997b64b73fa82a86093a0f9c63d275) in which the error occurred when working with API, here is an example to reproduce the error in GUI as well:
1. replace the muscles of Rajagopal model with `DeGrooteFregly2016Muscle` (or download this already converted one: [DeGroote.zip](https://github.com/opensim-org/opensim-core/files/14606818/DeGroote.zip))
2. in GUI, set `hip_flexion_r` coordinate to a value more than `80` (or less than `-10`)
3. open plotter and plot `tendon force` of `semiten_r` muscle against `knee_angle_r`
4. set `Activation override` to `0.2`

![image](https://github.com/opensim-org/opensim-core/assets/38867713/0e7be5b4-4bd8-4c6c-8fc6-7673d0f1e803)
`AnalyzeTool::run() unable to equilibrate muscles at time = 0.0. Reason: Model::equilibrateMuscles() Function has same sign at bounds of 0.0 and 5.0.
	Thrown at CommonUtilities.cpp:164 in solveBisection()..
DeGrooteFregly2016Muscle 'recfem_r' is exceeding maximum contraction velocity at time 0.0 s.
`
As you see in this example, the error is related to an other muscle, `recfem_r`.

**Comment by nickbianco** [comment]
Hi @mrrezaie, I will address this question on the forum, since I don't see a clear bug here yet. This is probably explained by differences in how these muscles handle muscle-tendon equilibrium.

If we do find a bug, we can reopen this later.
