### ISSUE TITLE
Array.rfindIndex is broken

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3743]
This was reported as a GUI issue https://github.com/opensim-org/opensim-gui/issues/1496
Stepping through the code it showed that Array.rfindIndex is returning incorrect index/different from legacy version. While the GUI was changed to workaround this (by using findIndex which should yield same answer if there're no duplicates as is the case here though probably more expensive?), however the function needs to be fixed for potential clients or removed and documented as a possible breaking change on the opensim-core side.

**Comment by aymanhab** [comment]
@adamkewley while not blocking now I'm thinking this slipped through the cracks along with PR #3678 I tested rfindIndex at the scripting shell and it returned an index past the end. Not urgent but good to fix before the next release.

**Comment by adamkewley** [comment]
Ah crap, sorry about this @aymanhab - it looks like the original algorithm operated a little bit differently from how I would've figured!

I'll have a look into fixing it
