### ISSUE TITLE
ControlDistributor class is not included in bindings

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3747]
While this may not be immediately useful, the fact that it's a ModelComponent is lost from bindings which may have downstream loss of functionality

**Comment by nickbianco** [comment]
Since this is easy to fix and related to my current work, I'm going to add it to my current sprint tasks.

**Comment by nickbianco** [comment]
I am choosing (for now) to exclude `ControlDistributor` from the user API and instead keep it only as an internal class for Moco.
