### ISSUE TITLE
Build system for Apple OS X needs cleanup.  Fails out of the box

### ISSUE THREAD

**Issue by msdemers** [opensim-org/opensim-core#375]
It looks like the cmake rules for OS X haven't been updated in a while and are long obsolete.  Some legacy hacks dating back to OS X 10.6 Snow Leopard and Xcode 4 (year 2009) are breaking the build out of the box on modern OS X systems, regardless of whether GNU Make or xcode are used.

Specifically:
1. -m32 is explicitly defined for Apple only.  Causes make to ignore the system default and developer preferences.  This was a hack because of old OS X issues and is obsolete.
2. vestigial LIB64 variable is unnecessary now. we always install libraries to /lib, even on 64 bit systems. simbody build system has already been corrected.
3. policy for MACOSX_RPATH is unspecified on some targets, so cmake is activating by default

**Comment by chrisdembia** [comment]
+1

**Comment by msdemers** [comment]
Removing the following lines (all outdated or redundant with general GNU make or clang rules) patches the release build.

>>IF( APPLE )
    SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mmacosx-version-min=10.8 -m32" )
    SET( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mmacosx-version-min=10.8 -m32" )
   SET( LIB64  )
   SET(ARCH64 OFF) 
ENDIF( APPLE )

However, debug build is still failing.  Probably related to issue #372 and issue #373

**Comment by chrisdembia** [comment]
I'll try to set up osx on travis to test this.

**Comment by chrisdembia** [comment]
Ack...travis isn't offering osx support for new repositories for now. http://docs.travis-ci.com/user/multi-os/

**Comment by chrisdembia** [comment]
Matt, maybe change these lines as well? https://github.com/opensim-org/opensim-core/blob/master/CMakeLists.txt#L315

**Comment by msdemers** [comment]
Those lines could either stay or go.  They aren't doing any harm.  However, we could omit the -m32 or -m64 flags and let the defaults for the build system serve.  If the developer sets clang or gcc defaults to build 32, ok.  64 ok. As long as the same default was conserved between building Simbody and OpenSim, all is good.

To me, that means that if we remove explicit -m32 or -m64 flags in OpenSim's build setup, then we really should remove them from Simbody's build setup too.

**Comment by sherm1** [comment]
I don't think Simbody has any weird OSX flags left. Any reason we can't just model OpenSim's treatment after Simbody's?

**Comment by msdemers** [comment]
No reason. I just double checked and simbody never uses the -m32/64
explicitly. Instead, it defines a variable for instruction set and
references it throughout. These eventually resolve to -m32/64 flags.
OpenSim's flags are the same, bet are set in logical flow if else
statements based on a similar variable. Result is the same.

**Comment by sherm1** [comment]
> simbody never uses the -m32/64 explicitly. Instead, it defines a variable for instruction set 

If you are referring to `BUILD_INST_SET` that is for choosing the level of SIMD parallelism to use (like sse2 or avx), it doesn't turn into m32/64.

**Comment by msdemers** [comment]
I thought I saw. ${GCC_INST_SET} in the flags as well. Maybe I'm mistaken
or GCC_INST_SET is copied/modified version of BUILD_INST_SET?

**Comment by sherm1** [comment]
> GCC_INST_SET

Yeah, it's confusing because gcc uses -m to specify all machine-dependent options, including `-msse2` for the sse2 instruction set, which is what Simbody is using it for. `GCC_INST_SET` is just `-m${BUILD_INST_SET}`.

**Comment by chrisdembia** [comment]
Related: #91

**Comment by chrisdembia** [comment]
@msdemers can we close?

**Comment by msdemers** [comment]
Sure can. Will do.
