### ISSUE TITLE
An issue related to `TimeSeriesTable::trim`

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3751]
Hi, I think something is wrong with [trim](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1TimeSeriesTable__.html#a3afa0406d029170edb03b2b549709556) method.

I'm using the following piece of script to apply low-pass filter on `TimeSeriesTable`. After removing the pads using `trim`, it suppresses a row from the table.

```python
timeColumn = table.getIndependentColumn() # time
osim.TableUtilities().filterLowpass(table, 10, padData=True)
table.trim(timeColumn[0], timeColumn[-1]) # remove padding
```
It often works well but not always and it interrupts my workflow. Perhaps the issue is somehow related to round-off error in the time column. Is there any better and more robust way to remove the pads (in Python)? 

In API, a better alternative would be the combination of [getNearestRowIndexForTime](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1TimeSeriesTable__.html#a71a91acf29d9a14c1b8712ed02e81da2) and [trimToIndices](https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1TimeSeriesTable__.html#a504fad31e0db9a6aeed8a6865015d328), but the later one has not been exposed yet for Python. I was wondering if you could expose `trimToIndices`, or integrate the _'search for the nearest time'_ with `trim` method.

Thank you in advance.

**Comment by nickbianco** [comment]
Hi @mrrezaie, the docs say:
```
Uses getRowIndexAfterTime to locate first row and getNearestRowIndexForTime method to locate last row.
```
so the trimming might not be inclusive to the first time point. You could try providing a time value just before your initial time to include the first time index.

I'm not sure we will change this functionality, but regardless we should expose `trimToIndices` so you have more control over the start time index.

**Comment by mrrezaie** [comment]
Hi @nickbianco, thanks for your response, and exposing `trimToIndices`. 

> `Uses getRowIndexAfterTime to locate first row and getNearestRowIndexForTime method to locate last row.`
so the trimming might not be inclusive to the first time point. You could try providing a time value just before your initial time to include the first time index.

Not sure if `trim` is functioning as documented. In this example, it is including the first time. 
```python
import opensim as osim
import numpy as np

times = np.linspace(0,1,11)
# [0. 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9, 1. ]
col = np.arange(0,11, dtype=float)
# [0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10.]

table = osim.TimeSeriesTable(times)
table.appendColumn('col', osim.Vector(col))

table.trim(0.1,0.9)
print(table.getDependentColumn('col').to_numpy())
# [1. 2. 3. 4. 5. 6. 7. 8. 9.]
```
And if some sort of rounding error occurs, the output might be unreliable:
```python
error = 1e-12
times = np.linspace(0,1,11) - error
...
table.trim(0.1,0.9)
[2. 3. 4. 5. 6. 7. 8. 9.]
``` 
```python
times = np.linspace(0,1,11) + error
...
table.trim(0.1,0.9)
[1. 2. 3. 4. 5. 6. 7. 8.]
```
But `getNearestRowIndexForTime` always returns the correct index. Thank you.

**Comment by tkuchida** [comment]
> Not sure if `trim` is functioning as documented.

IMHO the behavior in your examples is correct: trimming based on time points will always be sensitive to numerical noise. The `trim` method guarantees that all returned points are within the specified range. If what you're trying to do is find the time point closest to a specified value, then `getNearestRowIndexForTime` is the right idea. As @nickbianco suggested, a `trimToIndices` method would be good if there's currently no way to do this. 🐴

**Comment by mrrezaie** [comment]
Thanks for your explanation. So, I'll be looking forward to `trimToIndices` method. Thanks for your time.
