### ISSUE TITLE
Add .trc file to scaleTool in python

### ISSUE THREAD

**Issue by hmejbri** [opensim-org/opensim-core#3757]
I need to add perform scaling but I cant seem to find how and the documentation is not clear. This is what I came up with : 

`
    # Load model
    model = opensim.Model(model_file)

    # Load scaling setup
    scale_tool = opensim.ScaleTool(scaling_file)

    # Add .trc file 

    # Run scaling
    scale_tool.run()

    # Save scaled model
    scaled_model_file = "scaled_model.osim"
    model.printToXML(scaled_model_file)
`

**Comment by nickbianco** [comment]
@hmejbri, unless there is a bug to report, please post these types of questions to [the OpenSim forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB).
