### ISSUE TITLE
Can we remove ARCH64 and LIB64 cmake variables?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#377]
Related: #375

**Comment by msdemers** [comment]
At first glance, it looks like LIB64 definitely can go.  We can use ARCH64 to specify 64 bit or 32 bit compiler flags, but I suppose we don't have to.

**Comment by jenhicks** [comment]
@chrisdembia Can this issue be closed? If not, is it necessary for Hackathon?

**Comment by chrisdembia** [comment]
Yes, this issue has been fixed.
