### ISSUE TITLE
Update to new CasADi Jacobian sparsity interface

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3801]
CasADi changed how the Jacobian sparsity needs to be provided in a recent version (summarized in [this issue](https://github.com/casadi/casadi/issues/3713)). In order to update to the most recent version of CasADi (i.e., in order to use the new FATROP solver), we will need to use this interface.

**Comment by aymanhab** [comment]
Good job digging into this @nickbianco, let me know if you need help upgrading or building

**Comment by nickbianco** [comment]
I have a working fix on this branch: https://github.com/opensim-org/opensim-core/tree/update_casadi_sparsity_detection.

I'll clean it up and make a PR soon.
