### ISSUE TITLE
Add sqrt and/or expression based OpenSim Function child class

### ISSUE THREAD

**Issue by cvhammond** [opensim-org/opensim-core#3812]
Spoke to @nickbianco about adding a square root function, but also a general 'expression' based function could be valuable as well

**Comment by cvhammond** [comment]
Are there any plans to address this item? We have a journal manuscript that we will submit shortly that could use this feature.

**Comment by nickbianco** [comment]
@cvhammond we might be able to add this in an upcoming development sprint. How high of a priority is this for your manuscript?

**Comment by cvhammond** [comment]
We really need this feature, but we aren't able to wait for the manuscript submission for it. If this feature could be made available in the next month or so we can update the submission with the new results at revision to show better results.

**Comment by nickbianco** [comment]
@cvhammond, this feature has now been merged. You can download a recent artifact from the "Actions" tab to give it a try.
