### ISSUE TITLE
File names shown in frontend as expected by backend and not as expected by users

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-core#3815]
For example, all marker files are shown as "marker.trc" independently of the name of the trial, if an user downloads multiple trials, that could be confusing. Same with custom models.

**Comment by aymanhab** [comment]
Does this issue belong in this repo?

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab This is an Addbiomechanics issue, I created it using zenhub and must have assigned the wrong repository.

**Comment by aymanhab** [comment]
No worries @AlbertoCasasOrtiz you can just transfer the issue, but thanks for taking care of this
