### ISSUE TITLE
Create 4.5.1 API release

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3829]
Create an API release to publish new features needed for the upcoming CMBBE 2024 conference. This release should include:

- [x] A GitHub release with downloadable build artifacts attached
- [ ] API documentation hosted on SimTK
- [x] A new conda package for the release

**Comment by aymanhab** [comment]
@nickbianco Do we have close to everything to create a 4.5.1 branch for the release and conda packages?

**Comment by nickbianco** [comment]
Yes, just one small issue to address: https://github.com/opensim-org/opensim-core/issues/3783. I'll get that done in the next couple of days so we can create a release by next week.

**Comment by aymanhab** [comment]
Last step is to review doxygen, which I already passed by Jon Stingel
