### ISSUE TITLE
Create separate user vs dev doxygen.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#383]
In user doxygen, do not show protected or private functions.

**Comment by jimmyDunne** [comment]
@chrisdembia can do dev version, I can do user version.

**Comment by chrisdembia** [comment]
For user (scripting) documentation it might be very useful to show all inherited public methods as well. That is, ForceSet should show all the public methods it inherited from Set, without having to click any drop downs.

**Comment by chrisdembia** [comment]
@jimmyDunne I got a start on this here: https://github.com/opensim-org/opensim-core/tree/user-and-dev-doxygen

For the user doxygen I use your previous doxygen-layout.xml

Running `make doxygen` will make both user and developer doxygen. I prefer this over having separate `doxygen_user` and `doxygen_developer` because it runs fast enough and I think discovering the `doxygen` target is easier than discovering the other two.
