### ISSUE TITLE
The CMC-tool failed to calculate.

### ISSUE THREAD

**Issue by Baliencasia** [opensim-org/opensim-core#3832]
Hello all,
been struggling with this for quite some time. The CMC-tool crashes immediately with this model(hand_model_simtk [https://simtk.org/projects/hand_muscle](url) ).
[hand_model_with_geometry_files.zip](https://github.com/user-attachments/files/16062578/hand_model_with_geometry_files.zip)
the files used for cmc cal could be find in the attach files.
I used cmc-tool in opensim 4.5 to get the muscle activation with a extremely simple motion(motion.mot), there is only one motion degree of freedom(elbow_flexion).
But the operation will fail, there is an error message like this.
![image](https://github.com/opensim-org/opensim-core/assets/135498414/76340407-7c7b-4b41-9153-53ac4f6e8b2a)
The message window will display the following content 
`Storage: read data file = C:\Users\Lenovo\Documents\OpenSim\4.5\Models\hand_model_simtk\subject01_mani.mot (nr=96 nc=28)
Running tool '1'.
No external loads will be applied (external loads file not specified).
TaskSet size = 28.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'DELT1' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'DELT2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'DELT3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'SUPSP' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'INFSP' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'SUBSC' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'TMIN' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'TMAJ' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PECM1' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PECM2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PECM3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LAT1' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LAT2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LAT3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'CORB' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'TRIlong' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'TRIlat' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'TRImed' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'ANC' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'SUP' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'BIClong' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'BICshort' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'BRA' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'BRD' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'ECRL' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'ECRB' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'ECU' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FCR' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FCU' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PL' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PT' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'PQ' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDS5' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDS4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDS3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDS2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDP5' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDP4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDP3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FDP2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EDC5' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EDC4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EDC3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EDC2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EDM' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EIP' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EPL' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'EPB' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'FPL' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'APL' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'RI2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LU_RB2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'UI_UB2' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'RI3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LU_RB3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'UI_UB3' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'RI4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LU_RB4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'UI_UB4' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'RI5' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'LU_RB5' has been reset to 0.02.
CMC::extendAddToSystem: CMC cannot compute controls for muscles with muscle controls less than 0.02.
CMC::extendAddToSystem: The minimum control limit for muscle 'UI_UB5' has been reset to 0.02.
`
What could be the cause for this crash?
Thanks a lot.

**Comment by nickbianco** [comment]
@Baliencasia could you please post this issue to [the OpenSim forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB) instead?

**Comment by Baliencasia** [comment]
ok，thanks
