### ISSUE TITLE
OpenSim 4.0 should provide a comprehensive list of API changes

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#384]
and provide the user with the updated method or official call sequence that now stands in its place.
These include:
1. Virtual Component interface methods (e.g. `finalizeFromProperties()`, `connect()`, `addToSystem()`, `initStateFromProperties()`, `setPropertiesFromState()`, `computeStateVariableDerivatives`,  were renamed to `extend<ComponentMethod>` for the purpose of derived classes extending those behaviors. `Super::extend<ComponentMethod>` is required at the beginning of any extension implementation.
2. `finalizeFromProperties()` (and companion extension method `extendFinalizeFromProperties()`) was added to the Component interface to support building, loading internal data structures once from properties (e.g. deserialization) and not being forced to (re)build/deserialize them during connect() and or addToSystem().
3. `Body& Model::getGroundBody()` was replaced by `const Ground& Model::getGround() const` and `Ground& Model::updGround()`.

...

**Comment by chrisdembia** [comment]
+1

**Comment by chrisdembia** [comment]
related but different: #239

**Comment by jimmyDunne** [comment]
change log is here 
https://github.com/opensim-org/opensim-core/compare/changelog

**Comment by jimmyDunne** [comment]
This issue will be used to draft the changes and once we have solid list before publishing to the change log

**Comment by idhamari** [comment]
It would be more nice if the changed added to the API documentation, something like: "this function replaced getGround ()" .

This helps when search for an old function to get the new one.
