### ISSUE TITLE
Add new `MocoOutputGoal` that depends on multiple Outputs

### ISSUE THREAD

**Issue by AllisonJohn** [opensim-org/opensim-core#3848]
Create a new class MocoCompositeOutputGoal in MocoOutputGoal.h that can combine two outputs with addition, subtraction, division, or multiplication. 

Add more instance variables to store second output info and update calcOutputValue.

also make initial and final versions -> now included with base class

and do the same for output constraint

**Comment by nickbianco** [comment]
> update calcOutputValue

I think you might want a new separate helper function for `MocoCompositeOutputGoal` since the logic for addition, subtraction, etc. will be different from the current `calcOutputValue`.
