### ISSUE TITLE
Create macro/facility for deprecating functions

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#385]
We could use a macro that allows cross-platform deprecating. Even though the language doesn't support it till C++14, the compilers we support already have their own deprecation feature: http://stackoverflow.com/questions/295120/c-mark-as-deprecated/295229#295229

This would not be for the 4.0 release; it'd be just to have in general.

**Comment by sherm1** [comment]
The C++14 feature is really nice -- you can include a message that comes out at compile time, like "this method replaced by nicer method xxx()" see http://josephmansfield.uk/articles/marking-deprecated-c++14.html.

Also here is a somewhat simpler workaround: http://stackoverflow.com/questions/295120/c-mark-as-deprecated/21265197#21265197
We could use this in 4.0 but if so we should add a message. That could be made to work now with `#warning` I think and later could be passed to `[[deprecated(msg)]]` in C++14.

**Comment by chrisdembia** [comment]
Ah good idea. How should we distinguish between methods for which we should rip the bandaid off vs deprecate for now?
