### ISSUE TITLE
Complete matrix of conda packages for 4.5.1 including tropter on all platforms

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#3870]
As of now both windows and osx are complete AFAIK linux is missing tropter. Also osx required a more recent metis 5, need to consolidate to minimize overhead moving forward.

**Comment by aymanhab** [comment]
Do we need to continue building/supporting non-arm64 on osx?

**Comment by nickbianco** [comment]
We probably want to keep x64 builds for not. (At least until I replace my laptop :grin:)

**Comment by aymanhab** [comment]
@nickbianco @carmichaelong Please let me know if any of the osx packages need a rebuild off the latest 4.5.1 branch or just publish exiting packages to opensim-org and be done with this issue. Thank you.

**Comment by nickbianco** [comment]
Nothing has changed on `opensim_451` except the recent Metis PR since the workshop. So if that's included, I think you're free to push the packages to opensim-org!

**Comment by carmichaelong** [comment]
Yes that all sounds good to publish the packages. Sorry I had forgotten we had an issue tracking this. Nick and I verified the osx packages and posted our results on slack instead of on here!
