### ISSUE TITLE
Deprecate or remove utilties for converting between SIMM and OpenSim

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3876]
Utilities currently exist for [converting between SIMM and OpenSim models](https://github.com/opensim-org/opensim-core/tree/main/OpenSim/Utilities/simmToOpenSim) we can be triggered by the CMake flag `BUILD_SIMM_TRANSLATOR`. 

It's unlikely that these utilities are being used or even work at all. This [older PR that removed a lot of SIMM-related code](https://github.com/opensim-org/opensim-core/pull/2490) seems to confirm this.

**Comment by nickbianco** [comment]
@aymanhab thoughts?

**Comment by aymanhab** [comment]
I tried to turn on the flag and it failed to compile anyway, the last commit dates back to 2015, we moved way far from there so I'd remove the flag and the code itself, we have some incarnation on github anyway. I'll make a PR to do this
