### ISSUE TITLE
Super::extendFinalizeFromProperties() not called from OffsetFrame method

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#388]
OffsetFrame::extendFinalizeFromProperties() does not call Parent class method which causes mysterious crashes downstream. Fixed on geometry_v2 branch.

**Comment by jimmyDunne** [comment]
@aseth1 as this fixed on his local machine. Will check in.

**Comment by jenhicks** [comment]
@aseth1 Is this issue fixed?

**Comment by aseth1** [comment]
Yes.
