### ISSUE TITLE
[Feature Request] track free moment and center of pressure in `MocoContactTrackingGoal`

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3900]
Hi, I'm writing to ask for a new option in `MocoContactTrackingGoal`. If I understand correctly, the goal doesn't take account of free moment and center of pressure data. In my simulations, the forces are tracked really well, but I see significant deviations in other components:
![graph_grf](https://github.com/user-attachments/assets/dca536eb-6b8c-4876-bf65-e086e75e3f7c)

Given that the force plate data are probably the most reliable and accurate measurements among the experimental data, and that an inaccurate center of pressure could propagate errors to the proximal joints, it would be great to have this option in the `MocoContactTrackingGoal` to whether or not track the other components.

Thank you in advance.

**Comment by nickbianco** [comment]
@mrrezaie, this is on our TODO list and we already have an issue open for it: https://github.com/opensim-org/opensim-core/issues/3688. 

Closing since duplicate.
