### ISSUE TITLE
Throw an exception if equilibrate method fails in Millard2012*Muscle

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#391]
Currently, the `computeInitialFiberEquilibrium()` method in `Millard2012AccelerationMuscle` and `Millard2012EquilibriumMuscle` sets the fiber length to `optimal_fiber_length` if the initialization routine fails. Throwing an exception may be a safer alternative.

**Comment by chrisdembia** [comment]
+1
