### ISSUE TITLE
SIMM translator support

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#392]
We have code for a SIMM translator that doesn't have any tests. It's possible and likely that changes to API will break it. We need to drop support for it or add test case(s).

**Comment by jimmyDunne** [comment]
The decision for this needs to be made by 4.0. We should outsource to the biomechanics community.

**Comment by jenhicks** [comment]
Drop Simm_translator from 4.0 and advise people to use an older version of OpenSim to import SIMM models.

**Comment by jenhicks** [comment]
We will also have to figure out what to do with the export to SIMM option.

**Comment by aymanhab** [comment]
Did we figure out what to do here with SIMM support for 4.0?

**Comment by chrisdembia** [comment]
The last discussion seemed to favor dropping support, but I think there was mention of asking Scott what he thinks.

**Comment by aymanhab** [comment]
Current plan is to drop export support and make importer part of the build system. We may need to take out the code for simmfilewriter out as dead code.

**Comment by jenhicks** [comment]
I double checked with Scott today and he is OK with this plan.

**Comment by jenhicks** [comment]
@aseth1 will assess situation. Will not add new SIMM versions for 4.0

**Comment by jenhicks** [comment]
@aseth1 Any updates on looking into this? If it isn't possible, we are leaning towards removing the option.

**Comment by tkuchida** [comment]
Remove from beta @aymanhab
