### ISSUE TITLE
Debug test failures

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#393]
- [x] testMomentArms
- [x] testInitState
- [x] testPrescribedForce #304 
- [x] testAssemblySolver
- [x] testModelCopy
- [x] testComponents
- [x] testIterators

Tested on Ubuntu 14.04 clang 3.4.

Timeouts:
- testOptimizationExampleRuns (testOptimizationExample also fails, likely b/c this one times out).
- testCMCArm26
- testCMCSingleMuscle
- testCMCSingleRigidTendonMuscle

_Note added by tkuchida:_
See [travis.yml L128](https://github.com/opensim-org/opensim-core/blob/master/.travis.yml#L128) for list of excluded tests.

**Comment by jimmyDunne** [comment]
Break up and start going through the list.

**Comment by aymanhab** [comment]
As of 08/10, on windows x64 and VS 2013 Debug builds
testMomentArms passes
testInitState passes
testPrescribedForce passes
testAssemblySolver fails
testModelCopy passes
testComponents passes

Not clear if the fixes were intentional and work cross-platform or coincidental!

**Comment by chrisdembia** [comment]
Woohoo! We should fix all our bugs this way..just wait :)

**Comment by jenhicks** [comment]
Can we close?

**Comment by chrisdembia** [comment]
I think we should leave open. There are still a number of debug failures the last time I checked. At least now we are running the debug tests on travis, so we won't get *new* failures.

**Comment by jenhicks** [comment]
@aymanhab Can you update the list to the latest?

**Comment by chrisdembia** [comment]
We run the debug tests on travis now, and I have omitted the ones that fail or that take too long in debug (https://github.com/opensim-org/opensim-core/blob/master/.travis.yml#L125). The list could still be outdated though.

**Comment by aymanhab** [comment]
Updated list on Windows 7 Pro x64, VS 2015 community on 3/7/2016:
The following tests FAILED:
1>  	 14 - testAssemblySolver (Failed)
1>  	 15 - testContactGeometry (Timeout)
1>  	 38 - testOptimizationExampleRuns (Timeout)
1>  	 39 - testOptimizationExample (Failed)
1>  	 49 - testWrapping (Timeout)
1>  	 50 - testAnalyzeTutorialOne (Timeout)
1>  	 51 - testInducedAccelerations (Failed)
1>  	 53 - testStaticOptimization (Failed)
1>  	 58 - testCMCArm26 (Timeout)
1>  	 59 - testCMCEMGDrivenArm (Timeout)
1>  	 60 - testCMCGait10dof18musc (Failed)
1>  	 61 - testCMCSingleMuscle (Timeout)
1>  	 62 - testCMCSingleRigidTendonMuscle (Timeout)
1>  	 64 - testCMCWithControlConstraintsGait2354 (Timeout)
1>  	 65 - testCMCWithControlConstraintsRunningModel (Timeout)

**Comment by aseth1** [comment]
It isn't clear why OSX-clang builds on Travis are timing out. It cannot be because of `testWrapping` because the logs indicate that `testWrapping` completed and passed. @chrisdembia @klshrinidhi is there a straightforward way to extend the timeout time on OSX?

**Comment by chrisdembia** [comment]
Note: the OSX build is not Debug, so this issue may not be related.

@tkuchida mentioned that travis terminates a build that doesn't produce output for 10 minutes. Travis provides a mechanism (`travis-wait`) to deal with commands that may not produce output for 10 minutes: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received. This could be a temporary fix. The better option is to improve the runtime of our tests, and investigate if there have been recent regressions in performance.

**Comment by aseth1** [comment]
Yes, the best outcome is to improve quality and speed of the tests. But we should also understand what changed to cause the failure. Similarly, why are we disabling tests if they had been passing in the past.  If it was never passing and we had to disable to add to CI that's fine initially, but that from that point on we should be bringing tests back in. I also agree that his discussion does not belong here. Sorry for that.

**Comment by chrisdembia** [comment]
> Similarly, why are we disabling tests if they had been passing in the past.

I regret that I started ignoring testWrapping. However, it is very frustrating to hear that a build fails when it was for some reason like a test timing out, and I'm not necessarily able to spend time on addressing that separate issue right now. I'm also more okay with ignoring tests just for Debug (testWrapping is only ignored for Debug), since we still test that it passes in Release. I would *not* have wanted to disable testWrapping across all CI configurations.

**Comment by tkuchida** [comment]
[testContactGeometry timeout](https://travis-ci.org/opensim-org/opensim-core/jobs/142975868#L1955) (clang in Debug mode)

**Comment by klshrinidhi** [comment]
I am not able to reproduce problem with `testContactGeometry` taking long time with clang in Debug.

**Comment by chrisdembia** [comment]
See [this branch](https://github.com/opensim-org/opensim-core/tree/fix_tests_in_debug) for progress on this issue.

**Comment by chrisdembia** [comment]
I am able to get all tests to pass on Windows in debug except for testOptimizationExample(Runs), which times out. However, @aseth1 has shortened this test in #1548 . Therefore, I am closing this issue.

**Comment by aseth1** [comment]
Woohoo! Thank you @chrisdembia .

**Comment by tkuchida** [comment]
:fireworks:

**Comment by jenhicks** [comment]
Awesome! Thanks @chrisdembia
