### ISSUE TITLE
Add accessors for the angular momentum of a `Body`

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3937]
Simbody has methods for calculating the angular momentum of an individual body (e.g., [`MobilizedBody::calcBodyMomentumAboutBodyOriginInGround()`](https://simbody.github.io/3.7.0/classSimTK_1_1MobilizedBody.html#afc4029646b0e89372c37eb12a7f63c4c)). [PhysicalFrame provides accessors to the underlying MobilizedBody](https://simtk.org/api_docs/opensim/api_docs45/classOpenSim_1_1PhysicalFrame.html#aa08607ac64e7cf0085492107913ea1bc), but the momentum methods are not wrapped by SWIG  and therefore accessible via scripting in Matlab or Python (reported by Hannah Heigold).

An easy solution would be to wrap the Simbody-level methods in PhysicalFrame, which would then make them available via SWIG.

**Comment by aymanhab** [comment]
Sure, would it make sense to utilize these as outputs?

**Comment by nickbianco** [comment]
No reason not to add `Output`s for these as well!
