### ISSUE TITLE
Reduce runtime of testOptimizationExample

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#394]
Consider loosening the convergence tolerance (`opt.setConvergenceTolerance()`), but ensure this doesn't cause different solutions to be found on different platforms.

**Comment by jimmyDunne** [comment]
Fix the number of iterations. Investigate some ways of making it faster (ie rigid tendons? reduce the number of muscles? reduce DoF's?).

**Comment by chrisdembia** [comment]
testOptimizationExampleRuns's runtime has jumped from 220ish seconds to 550ish seconds with #378. Over in my silly redundant #396, I suggested "How about just using a fixed pennation angle of 0 for this optimization?"

**Comment by jenhicks** [comment]
@tkuchida Can we close this issue now?

**Comment by tkuchida** [comment]
Reduced runtime of testOptimizationExampleRuns from 411s to 63s (MSVC). See #416.
