### ISSUE TITLE
Add Mac Arm64 builds to the CI

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3944]
Now that our build system supports Arm64 builds on Mac, it would be a good time to update [the continuous integration script](https://github.com/opensim-org/opensim-core/blob/main/.github/workflows/continuous_integration.yml) to add an Mac Arm64 job.

**Comment by nickbianco** [comment]
I realized that after [recently upgrading the CI to use `macos-14` runner images](https://github.com/opensim-org/opensim-core/blob/edbc2e48db065e87f7b986be2aa2171fa1087b15/.github/workflows/continuous_integration.yml#L373), we're actually already [creating MacOS Arm64 builds](https://github.com/actions/runner-images/tree/main). We need to use `macos-14-large` for an x64 build.

**Comment by nickbianco** [comment]
@aymanhab, I'm going to get a start on this since I want to do some clean up of the performance analysis workflows anyway.

**Comment by aymanhab** [comment]
Alright, thanks @nickbianco I can pickup next week when I'm back if there's anything left.
