### ISSUE TITLE
Ho to process the trc file data faster by iktool

### ISSUE THREAD

**Issue by zhejing672** [opensim-org/opensim-core#3947]
I would like to process real-time updated trc file data by inverse kinematics analysis, however, it takes too long to start ik_tool.run every time, and I would like to know if there are other inverse kinematics functions that can process the data faster.

**Comment by aymanhab** [comment]
I don't think this belongs in the github/issues category but maybe you can explain your workflow and post to the user forum https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
If there's a specific issue/bug to address including performance please provide details and re-open. Thank you
