### ISSUE TITLE
`InverseKinematicsSolver::computeCurrentMarkerError()` might crash due to incorrect handling of marker list order

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#3951]
`InverseKinematicsSolver::computeCurrentMarkerError()` crashes when used, and will crash at different times when using either the function that refers to markers by integer and by string. It doesn't look like a test uses this, but there's a test that uses the very closely named `InverseKinematicsSolver::computeCurrentMarkerErrors()` (note the extra `s` at the end).

There are similarly named functions (e.g., `computeCurrentMarkerLocation()`, `computeCurrentSquaredMarkerError()`) that may have the same issues.

See zip for Python code and data for testing.

[test_computeCurrentMarkerError.zip](https://github.com/user-attachments/files/17513783/test_computeCurrentMarkerError.zip)

**Comment by aymanhab** [comment]
# Model has 50 markers while trc file has only 46, how are these consolidated? you should not iterate through the model markers  and assume data exists in trc file since trying to compute errors will crash.

# markerList[14] is r_mknee which is not in the trc file
