### ISSUE TITLE
Update python wrapping for new sets (FrameSet, JointSet)

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#402]
Right now the python swig.i file contains some manual handling of memory ownership for BodySet, ForceSet, etc. We must extend this memory handling to FrameSet and JointSet

**Comment by jenhicks** [comment]
@chrisdembia We think this is done, but please reopen if not.

**Comment by chrisdembia** [comment]
Yes, this is done: https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/swig/python_simulation.i#L67
