### ISSUE TITLE
ctest on mac failing

### ISSUE THREAD

**Issue by nishbo** [opensim-org/opensim-core#403]
Hi everyone,
Building OpenSim3.2 on SimBody3.3.1 using macports-installed latest versions of GNU C compiler:
```gcc version 4.9.2 (MacPorts gcc49 4.9.2_1)```
After altering cmake according to issue #375 and building (`make`), `ctest` fails on all tests except for the first one (`testLeptone`). Others throw `***Exception: Other`. I think that this may be an issue of wrong working directories. I tried tests manually (copying all libs, model files, etc.), they seem to be working.
Did not try to build it as an XCode project, reason for latest gcc - future alterations of the code, optimization, C++14, etc.
ADD:
When I built it again from scratch, `ctest` passed for `testCMCWithControlConstraints` for some reason, too.

ADD:
Building current git HEADs of OpenSim (last commit Mar 12, 2015) and SimBody (last commit Mar 16, 2015), same problem.

**Comment by chrisdembia** [comment]
Thanks for creating an issue for this. When you tried to build OpenSim 3.2, are you building it from this repo (perhaps the OpenSim32 branch)? If so, I'm surprised it's working at all; the OpenSim32 branch in this repo is just for reference, and shouldn't be functional. That's because we used to store our repo in SVN along with the GUI source code. In this repo, the GUI source code has been removed from each commit. This causes the CMake files invalid, since they refer to a Gui folder that doesn't exist.

What version of cmake are you using? What is your CMAKE_BUILD_TYPE? Debug or Release, etc.? Did you have any issues with simbody?

Please run the tests using `ctest -V` and post the error messages here. 

> Did not try to build it as an XCode project, reason for latest gcc - future alterations of the code, optimization, C++14, etc.

This is just a side comment but if you use XCode, you'll be using clang, which is usually ahead of gcc in terms of C++14 support, etc. Also, clang gives smaller compile times. Anyway, gcc 4.9 should still work.

**Comment by nishbo** [comment]
I am building OpenSim 3.2 Release from https://simtk.org/project/xml/downloads.xml?group_id=91, OpenSim-3.2-source.zip. I don't see any GUI references in cmake files.

```cmake version 3.2.1```
CMAKE_BUILD_TYPE Release
Simbody did not have any issues.

I post only part of output, because all other tests show same:
```
$ ctest -V
UpdateCTestConfiguration  from :/Users/user/simtk/OpenSim32-build/DartConfiguration.tcl
Parse Config file:/Users/user/simtk/OpenSim32-build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/user/simtk/OpenSim32-build/DartConfiguration.tcl
Parse Config file:/Users/user/simtk/OpenSim32-build/DartConfiguration.tcl
Test project /Users/user/simtk/OpenSim32-build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: testLepton

1: Test command: /Users/user/simtk/OpenSim32-build/testLepton
1: Test timeout computed to be: 1500
 1/52 Test  #1: testLepton ...................................   Passed    0.04 sec
test 2
      Start  2: testFunctionAdapter

2: Test command: /Users/user/simtk/OpenSim32-build/testFunctionAdapter
2: Test timeout computed to be: 1500
2: dyld: Library not loaded: libSimTKcommon.3.3.dylib
2:   Referenced from: /Users/user/simtk/OpenSim32-build/testFunctionAdapter
2:   Reason: image not found
 2/52 Test  #2: testFunctionAdapter ..........................***Exception: Other  0.07 sec
test 3
```
It seems to be an error of linkage, too.

OK, I use gcc because of Stallman :)

**Comment by chrisdembia** [comment]
I've never seen "image not found"! Were the SimTK libraries copied into your build directory for OpenSim? Otherwise, did you add SimTK's lib dir to your DYLD_LIBRARY_PATH? You shouldn't need to though... Can you try using CMake 2.8.8?

**Comment by chrisdembia** [comment]
Cmake 3.2 might have new policies regarding rpath? IDK.

**Comment by chrisdembia** [comment]
@nishbo any new discoveries about this failure?

**Comment by aymanhab** [comment]
@chrisdembia from the error message it sounds like a symbolic link was found but it wasn't pointing to a valid "image". We'll need some context to check/verify if that's the case.

**Comment by tkuchida** [comment]
@chrisdembia I have encountered a similar problem on Windows 7 (59 tests failed out of 65). Here's the output:

<pre>
[...]
1>  Errors while running CTest
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files (x86)\CMake 3.2.3\bin\ctest.exe" --force-new-ctest-process -C Release
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 8.
</pre>

I just upgraded to CMake 3.2.3 (for Visual Studio 2015 support). I'll try an older version.

**Comment by chrisdembia** [comment]
Did you try both RUN_TESTS and RUN_TESTS_PARALLEL? Do both fail?

**Comment by tkuchida** [comment]
> Did you try both RUN_TESTS and RUN_TESTS_PARALLEL? Do both fail?

Yes, both fail.

**Comment by chrisdembia** [comment]
> 1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 8.

I wonder what "code 8" is.

**Comment by tkuchida** [comment]
@chrisdembia: It seems that I was encountering a different issue than nishbo, so probably shouldn't have posted to this thread (though I had some of the same symptoms: `testLepton()` and a few other tests were passing; the rest were either segfaulting or returning `Exception: Other`). Unfortunately, I don't know what resolved the issue---perhaps Windows Update needed to upgrade something in my recently installed VS2015? :scream: The only other thing I can think of is that I've run ALL_BUILD more than once now. Any reason it should be necessary to run ALL_BUILD more than once?

**Comment by chrisdembia** [comment]
I can’t think of a reason :/

**Comment by jenhicks** [comment]
@chrisdembia Is this issue still relevant? Does it apply to opensim-core or just previous releases?

**Comment by chrisdembia** [comment]
I think it applies only to previous releases.
