### ISSUE TITLE
Building from source on OSX with GNU compiler

### ISSUE THREAD

**Issue by nishbo** [opensim-org/opensim-core#404]
For some reason, when building opensim with a gcc compiler instead of a native one on OSX, unrecognized option `-stdlib=libc++` produces an error instead of a warning. Possible fix: replace line 270 in `CMakeList.txt` with:

```
            IF(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
                SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
            ELSE()
                SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
                SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
            ENDIF()
```

There is a same issue with shorter fix: simbody/simbody#350

**Comment by chrisdembia** [comment]
Thanks @nishbo. Would you be interested in submitting a PR? I'd prefer the fix that @scpeters suggested (with a comment explaining the logic). If you choose to fix this PR; the same code appears in the examples (e.g., https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Examples/ExampleMain/CMakeLists.txt#L14). If not, I'll take care of it.
