### ISSUE TITLE
Source distribution of OpenSim 3.2 is broken under VS 2013

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#407]
OpenSim 3.2 source distribution should include simbody 3.5.1 rather than 3.3.1 Current posted source causes problems (signbit) when building using VS2013 Express.

**Comment by sherm1** [comment]
What is VS2013 Express complaining about? I don't see any obvious difference between the 3.3.1 handling of `std::signbit` and 3.5.1.

**Comment by aymanhab** [comment]
Sherm, the change is in common.h, the commit in simbody repository  explains.

**Comment by sherm1** [comment]
Oh, got it, thanks. Making that same patch to 3.3.1 would be a less-drastic alternative if you wanted that. 3.5.1 is probably OK though.

**Comment by chrisdembia** [comment]
Sounds like the fix to this is to update the table on this confluence page: http://simtk-confluence.stanford.edu:8080/display/OpenSim/Building+OpenSim+from+Source

**Comment by chrisdembia** [comment]
@aymanhab do the 3.2 tests pass with simbody 3.5.1?

**Comment by aymanhab** [comment]
@chrisdembia Full build of OpenSim 3.2 and simbody 3.5.1 passes all tests on windows with VS2013Pro but introduces unknowns for other compilers/platforms so I'd lean toward posting a patch of 3.3.1 instead as Sherm suggested  (since it appears 3.5.1 has more significant changes).

**Comment by aymanhab** [comment]
This issue can be fixed as well since our source distribution has been tested against VS 2013

**Comment by jenhicks** [comment]
OK .. Closing
