### ISSUE TITLE
For SimTK measures, should OpenSim classes hold onto handles (e.g., Measure_<T>) or indices (e.g., MeasureIndex).

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#411]
See #398.

**Comment by jenhicks** [comment]
@sherm1 Either way will work and Sherm likes using the Measure handle. Closing, but feel free to reopen if this does not resolve the issue.

**Comment by chrisdembia** [comment]
Okay I like handles as well.
