### ISSUE TITLE
When wiring an output to an input, there is no type checking

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#412]
I tried wiring a Vec3 Output to a Real Input and I ended up with an uninformative `std::bad_cast`. There's a type check for `Connector`, but not for `Input`.

**Comment by jenhicks** [comment]
Is this still unresolved? @chrisdembia @aseth1  It sounds like a test is missing as well.

**Comment by chrisdembia** [comment]
Unresolved as far as I know.

**Comment by jenhicks** [comment]
@aseth1 or @chrisdembia Is this fixed with any of the recent commits?
