### ISSUE TITLE
extendFinalizeFromProperties method is never invoked on Ground

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#420]
Ground component is added to the model but the initialization sequence to finalizeFromProperties() etc. is never invoked. Would be great to use this opportunity to document where these calls need to be made.

**Comment by aseth1** [comment]
You should not need to make these calls explicitly. When `finalizeFromProperties()` is called on the root Component (usually Model) it should propagate.

**Comment by aseth1** [comment]
@aymanhab is this still an issue?

**Comment by aymanhab** [comment]
@aseth1 Nope, it was a side-effect of deserialization issue that didn't create a proper model with Ground, once serialization was fixed, the method was called on Ground. Sorry for the false alarm.
