### ISSUE TITLE
When and where to mark Components as subcomponents is not clear.

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#421]
There are a couple of issues here:

1. Components should only be marked as subcomponents during `finalizeFromProperties()` (e.g. your Component's `extendFinalizeFromProperties()`. The marking of a component simply adds a reference to that component to a list. If where the Component lives (in memory) changes (due to array resizing which allocates and copies) then that reference becomes invalid. That is one of the issues raised in #417.
2. This fact is not well documented and furthermore there are instances e.g. [here in Model](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Model.cpp#L835)  where `addComponent()` is being used (incorrectly) but seems completely sensible. Model was getting away with it because it was explicitly clearing and rebuilding the subcomponent list in its `extendFinalizeFromProperties()`.

I propose we:
- [ ] remove all calls to `addComponent()` that exist outside of an `extendFinalizeFromProperties()` implementation.
- [ ] rename `addComponent` to `markAsSubcomponent()` which is more consistent with its documentation and clearly state it should only be called from the component's `extendFinalizeFromProperties()` and add a similar comment there to call `markAsSubcomponent()`.

**Comment by sherm1** [comment]
:+1:

**Comment by jenhicks** [comment]
This currently being adressed by @aseth1
