### ISSUE TITLE
Standard naming convention for new List-style properties

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#422]
OpenSim has many Set(s) that map to a single object/Set and so has been following the convention of CamelCase naming. Need to agree on a naming convention for lists that do not correspond to a single Object/Class. The use case is a set of Geometry objects. As of now I use GeometrySet but that seems confusing. Possible names:
Geometry_set (atypical since there's no supporting class)
geometry_set (not clear that it's a list of Geometry objects)

**Comment by aymanhab** [comment]
There seem to be an agreement on <geometry> as the tag for the list. 
Attending @sherm1 @aseth1 @tkuchida 

Please let us know if you disagree @chrisdembia @jenhicks 

The result in XML will look like:
<geometry>
<Mesh>....</Mesh>
<Sphere>...</Sphere>
<Cylinder>.... </Cylinder>
.....
</geometry>

**Comment by sherm1** [comment]
Could also use a more regular word like `<shapes>`.

**Comment by chrisdembia** [comment]
I like `<geometry>`

**Comment by jenhicks** [comment]
<geometry> also seems good to me.

**Comment by aymanhab** [comment]
Thanks all for the feedback, I changed to <geometry>. Doesn't set a general precedent though since "geometry" can be used as a plural but that maybe hard to reproduce in other scenarios.
