### ISSUE TITLE
Should finalizeFromProperties() be called from Model constructor?

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#424]
Per discussion with Sherm & Ajay this call should have been unnecessary, however removing the call causes numerous test failures.  One hypothesis is that it's due to the caching mechanism for Muscles being invoked only during the call so downstream code fails but could be something more subtle as well.

**Comment by jenhicks** [comment]
@aymanhab Can we close? @aseth1 can clarify with more comments, as needed.
