### ISSUE TITLE
Warning about nonzero inertia for massless body is emitted even if inertia is zero.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#427]
For the DynamicWalker model I just got the warning "Body 'Pelvis_massless' is massless but nonzero inertia provided. Inertia reset to zero. Otherwise provide nonzero mass" even though this body has zero inertia.

**Comment by nikorose87** [comment]
I've got the same error with some models

**Comment by chrisdembia** [comment]
Thank you for reporting.

**Comment by tkuchida** [comment]
This issue pertains to [`Body::getInertia()`](https://github.com/opensim-org/opensim-core/blob/4446724f558fb15a4fb4fd6a2dbd2df3c20f9d6a/OpenSim/Simulation/SimbodyEngine/Body.cpp#L124), which is performing checks that should probably reside in `Body::extendFinalizeFromProperties()` (and an `OPENSIM_THROW_IF_FRMOBJ(!isObjectUpToDateWithProperties(), ...)` should be at the top of `getInertia()`).

**Comment by chrisdembia** [comment]
Related PR: #225

**Comment by chrisdembia** [comment]
@nikorose87 I reproduced this warning with the model you provided in #1716:

```
Body 'talus_r' is massless but nonzero inertia provided. Inertia reset to zero. Otherwise provide nonzeromass.
Body 'toes_r' is massless but nonzero inertia provided. Inertia reset to zero. Otherwise provide nonzero mass.
Body 'talus_l' is massless but nonzero inertia provided. Inertia reset to zero. Otherwise provide nonzeromass.
Body 'toes_l' is massless but nonzero inertia provided. Inertia reset to zero. Otherwise provide nonzero mass.
```

I actually think your issue here is related to your issue in #1716, related to seeing commas where periods are expected, because the model you provided in #1716 has the following for the mass and inertia fields:

```xml
                    <!--The mass of the body (kg)-->
                    <mass>0,10000000000000001</mass>
                    <!--The location (Vec3) of the mass center in the body frame.-->
                    <mass_center>0 0 0</mass_center>
                    <!--The elements of the inertia tensor (Vec6) as [Ixx Iyy Izz Ixy Ixz Iyz] measured about the mass_center and not the body origin.-->
                    <inertia>0,0012396438758032777 0,0012396438758032777 0,0012396438758032777 0 0 0</inertia>
```

**Comment by nikorose87** [comment]
The problem was solved in my case just changing the locale settings to US. Thank you.

**Comment by chrisdembia** [comment]
Thank you for the update.
