### ISSUE TITLE
[scripting] Using ForceSet::append() causes MATLAB to crash

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#432]
This was brought up by @jimmyDunne in an email on May 7, 2015.

@jimmyDunne:

> Hi Guys-
If someone has 5 minutes could they test the matlab function attached (just run 'runScript'). It reads in a model and spits out an actuator file. 
Im having an issue with it randomly crashing Matlab. It looks like its an issue with the OpenSim but not clear if its my local setup or universal. 
Cheers,
-j

@aseth1:

> Hi James,
It runs, creates the actuatorFile.xml (which is identical to the reference) and then crashes MATLAB. From the stack trace it is blowing up when deleting the ForceSet.
That is because when appending to the ForceSet the ForceSet is taking ownership of the Actuator but that Actuator only has local scope. If I change append() to cloneAndAppend() it can delete the copies it owns.
Cheers,
Ajay

@jenhicks:

> We may have had this discussion before. Should both append and cloneAndAppend be accessible through scripting? I can certainly see how this would create confusion. 
Jen

I like the idea of removing `append`. There might be a use case for using `append` or `adotpAndAppend`, though: if the user wants to continue modifying the item that they added to the set (or for performance reasons). Ayman and I had similar issues with python scripting. Ayman and I solved it by using SWIG to telling one of the objects that it no longer owned the object. See https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Wrapping/Python/swig/pyWrapOpenSim.i#L280 for the swig code. Here's the same swig code but for sets: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Wrapping/Python/swig/pyWrapOpenSim.i#L850.

We also have corresponding tests https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Wrapping/Python/tests/test_swig_additional_interface.py#L153. 

That append method only exists on ForceSet. It invokes ModelComponentSet::adoptAndAppend, which might be the cause of the issue. https://github.com/opensim-org/opensim-core/blob/aa8dd913ca5685967943d44914a8e1c3fd496901/OpenSim/Simulation/Model/ForceSet.cpp#L189. It seems like this append method is useful, as it does more than just adoptAndAppend or cloneAndAppend (for as long as we plan on using a ForceSet that contains an ActuatorSet, etc.).

**Comment by chrisdembia** [comment]
I created a branch to test ForceSet::append in scripting and it fails, presumably for the same reason James hit an issue. https://github.com/opensim-org/opensim-core/tree/scripting-ap

https://travis-ci.org/opensim-org/opensim-core/jobs/61696578

**Comment by chrisdembia** [comment]
I know there is a higher level discussion about what functions should exist, etc. but I am also trying to fix this specific bug. I am currently trying something with the python scripting and we can see if it works via this test: https://travis-ci.org/opensim-org/opensim-core/jobs/61709017.

**Comment by chrisdembia** [comment]
My fix for python did not work :/ (https://travis-ci.org/opensim-org/opensim-core/jobs/61727291).

**Comment by aymanhab** [comment]
@chrisdembia The build failure is due to swig error in the configuration file. In general, for scripting users, I'd rate  stability higher than potential performance benefits.

**Comment by aymanhab** [comment]
@chrisdembia I think what you want to do here is to modify ForceSet::append  on the scripting side to communicate to the scripting environment that the object ownership has been transferred.

**Comment by aymanhab** [comment]
@chrisdembia I tried the %pythonappend and it didn't make it to the wrappers, so I resorted to the rename and replace method we use in Java wrapping. Can you take a look at the .py file and tell me what's the problem reported by Travis? Thanks.

**Comment by chrisdembia** [comment]
I just pushed a commit.
