### ISSUE TITLE
Most MarkerSet() methods have disappeared in python wrapping

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#437]
In 3.2, the following methods are available for MarkerSet:

![image](https://cloud.githubusercontent.com/assets/846001/7552416/7dd43ab6-f667-11e4-9205-58e300d0e988.png)

In master, here's MarkerSet and ForceSet:
![image](https://cloud.githubusercontent.com/assets/846001/7552414/6a2e9f06-f667-11e4-9ac8-363115712fb7.png)

Where did the methods go???

**Comment by aymanhab** [comment]
This has been fixed in build based on Alpha. Please confirm @chrisdembia 
![capturemarkersetmethods](https://cloud.githubusercontent.com/assets/3972208/21912961/384a414c-d8de-11e6-9a4b-02c4ed407eaf.JPG)

**Comment by chrisdembia** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/846001/21913035/a34e8278-d8de-11e6-9201-77e2280e8537.png)

**Comment by aymanhab** [comment]
Thanks 🎆
