### ISSUE TITLE
Investigate and fix potentially faulty logic in external loads

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#440]
Reported at the workshop.

**Comment by jenhicks** [comment]
@aymanhab Did this get backported?

**Comment by aymanhab** [comment]
@jenhicks Nope, since this part will be redone. The implementation in 3.3 relies on VTK heavily so will need to be revisited anyway.

**Comment by jenhicks** [comment]
OK - this is a GUI issue anyways -- can you make an appropriate issue in the GUI repo (to check that external loads are visualized properly), then I will close this one.

**Comment by jenhicks** [comment]
Moved this issue to opensim-gui, so closing here.
