### ISSUE TITLE
What is the right version number for the next OpenSim release?

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#444]
Putting on my marketing hat, I think we might want to call this OpenSim 3.3 rather than OpenSim 3.2.1. With significant user-meaningful fixes I think it deserves more than a patch number.

/cc @jenhicks @aseth1 @aymanhab  @jimmyDunne

**Comment by chrisdembia** [comment]
I agree, since we are requiring C++11 on linux now.

**Comment by chrisdembia** [comment]
Relatedly, I think we should bump up the version number on the master branch to 4.0. Otherwise, the version number in master will be less than that in the 3.2.1/3.3 code base, which could confuse users of the master branch.

**Comment by jenhicks** [comment]
Per discussion at Dev Team meeting: If we include include changes to how ligament is scaled or operation of static optimization flags, we will use version 3.3. Otherwise, we'll use version 3.2.1

**Comment by jenhicks** [comment]
Ayman committed a change to how ligaments are scaled ... so this makes it OpenSim 3.3.
