### ISSUE TITLE
InverseDynamicsTool forces_to_exclude "ALL" even excludes the external loads.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#447]

**Comment by jenhicks** [comment]
Putting in the icebox since desired behavior can be achieved by specified the specific forces to exclude.

**Comment by chrisdembia** [comment]
I think we could close this issue if we just add to the documentation for this property.

**Comment by chrisdembia** [comment]
Let me know if you all agree with this solution, and I'll do it.

**Comment by jenhicks** [comment]
That sounds great to me!

**Comment by sherm1** [comment]
:+1:
