### ISSUE TITLE
Does the method Component::getSystem() need to be public.

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#45]
While trying to SWIG wrap the new class OpenSim::Component (needed since it's a base class for ModelCompoenent) I ran into the public method 
   
   /**
     * Get the underlying MultibodySystem that this component is connected to.
     */
    const SimTK::MultibodySystem& getSystem() const
		{ return *_system; } 

which wraps into an unusable method since SimTK::MultibodySystem is not SWIG wrapped either and so it is impossible to use in scripting.The main question is whether this method should actually be protected (and so will be removed from wrapping) or if the SimTK::MultibodySystem is used more across the API and will need to be wrapped for scripting purposes.

**Comment by jenhicks** [comment]
Should be public, but hide from Matlab (i.e., don't wrap).
