### ISSUE TITLE
improve testStaticOptimization

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#452]
See https://github.com/opensim-org/opensim32/issues/17

**Comment by aymanhab** [comment]
@jenhicks @jimmyDunne @aseth1 I received an example that has a model with a CoordinateLimitForce (i.e. passive Force) called AnkleLimitSpringDamper. In version 3.2 it fails to solve on every frame but in addition it produces an activations file with entry for AnkleLimitSpringDamper and bogus control value of practically 0, and also include the AnkleLimitSpringDamper  in the forces output (non-zero). I plan to modify the code so it only computes and outputs controls, activations and forces for Actuator(s) only. Please let me know if you have other ideas.

**Comment by jimmyDunne** [comment]
>  plan to modify the code so it only computes and outputs controls,
> activations and forces for Actuator(s) only.


Is't that what its doing now?

**Comment by aymanhab** [comment]
@jimmyDunne Nope, running your files out of the box I get a bogus almost-zero "activation" for the passive-force, and non-zero value for the passive-force in the forces-file. GRF forces (left, right) show up in the title only for both activation and forces!

**Comment by jimmyDunne** [comment]
Ah, sorry, I was getting confused.

**Comment by aymanhab** [comment]
Addressed by #546
