### ISSUE TITLE
link error when building in debug

### ISSUE THREAD

**Issue by mjhmilla** [opensim-org/opensim-core#462]
The build system has come a long way! Although building OpenSim in release mode is smooth,  building in debug (a x64 version using VS2013 Pro running on Windows 8.1) is causing a bunch of link errors ('error LNK 1104: cannot open file ...') for these libraries:

osimCommon_d.lib
osimLepton_d.lib
osimSimulation_d.lib
osimTools_d.lib

The odd thing is that these libraries exist in both the correct build (opensim-core-build\Debug) and install directories (opensim-core\bin), and the install bin folder is on the path (and I've checked this from the command line). I'm not sure what's causing these link errors - any ideas?

**Comment by sherm1** [comment]
Matt, are you building from opensim-core's master branch or an earlier version?

**Comment by mjhmilla** [comment]
I think I'm working on opensim-core's master branch: I cloned the repository from the link provided on the github page (https://github.com/opensim-org/opensim-core.git).

**Comment by sherm1** [comment]
I tried it and I'm seeing the same thing. This may be from a recent build system change -- @chrisdembia would be interested but I think he is traveling. I'll investigate.

**Comment by mjhmilla** [comment]
Sherm you're awesome!

**Comment by sherm1** [comment]
Matt, here is a workaround you can use until @chrisdembia can weigh in on the correct way of fixing this. Just add this line to the top-level `CMakeLists.txt` file:
```
LINK_DIRECTORIES(${BUILD_BINARY_DIR})
```
I think you can put it anywhere, I added it at line 51 where the executable and library paths are set to the same value. Please try that and post whether it fixes the problem for you.

**Comment by sherm1** [comment]
With this workaround I still had two failures at the end: testForward and testScale examples didn't link correctly. I'm not sure if that is related to this same problem. But at least the rest built.

**Comment by sherm1** [comment]
@mjhmilla, PR #464 should have fixed this in the master branch now. Please update your repo (pull), run CMake again, and you should get a clean build in Debug including testScale and testForward. Let us know what happens.

**Comment by chrisdembia** [comment]
Thanks for reporting this issue, @mjhmilla . I'm not sure why LINK_DIRECTORIES(${CMAKE_BINARY_DIR}) is necessary and we should find a way to remove this line. Let's leave this issue open as a reminder to remove this line.

**Comment by mjhmilla** [comment]
Thank you for the fix Sherm. As requested by Chris I'll leave this as an open issue.

**Comment by elen4** [comment]
I think that the proper solution would be to fix the CMakeLists for all the failing tests so that they only list the target name of libraries to link instead of explicitly providing the optimized/debug names. This way, CMake automatically resolves dependencies based on which configuration is being built, instead of falling back to looking for libraries with the debug-version name in the list of link directories (which is why adding the `link_directories` command fixes compilation).

For example, in `Vendors/lepton/test/CMakeLists.txt` you could put:

```cmake
TARGET_LINK_LIBRARIES(${TEST_ROOT} osimLepton)
```

(also removing the deprecated `link_libraries` command :smiley: )

**Comment by chrisdembia** [comment]
Thanks @elen4 ; I agree with you. #395 solves the first issue, but not the deprecated `link_libraries` issue; that's fixed with your PR in Simbody, right? We should get that tested and merged.

**Comment by elen4** [comment]
I think that #395 solves the deprecated `link_libraries` issue (in your new macro, you use `target_link_libraries` instead), and it should solve the need for the deprecated `link_directories` command introduced in 0be9d08f7600 . I only had a quick look at it (not tested it), but I saw that you correctly use target names to specify the dependencies.
The need for the 

```cmake
LINK_DIRECTORIES("${Simbody_LIB_DIR}")
```
line in the main CMakeLists file still remains, and if I remember correctly my PR in Simbody doesn't fix it (at least on Windows, you still need that command to find blas/lapack libraries :disappointed: )

**Comment by chrisdembia** [comment]
> if I remember correctly my PR in Simbody doesn't fix it (at least on Windows, you still need that command to find blas/lapack libraries  )

Ohh right right.. I forgot. Darnit!!
