### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#463]
Start a running list of develop-oriented notes describing changes for 4.0. We'll need to  then retroactively review closed PRs. This will help us then create a user-facing set of release notes (on confluence) at the time of release.

**Comment by sherm1** [comment]
Good idea! Simbody has one of these [here](https://github.com/simbody/simbody/blob/master/CHANGELOG.md) in case it works as an example.

**Comment by jenhicks** [comment]
@chrisdembia - I noticed an old branch that has a change log file. Is this worth merging or recreating and merging? Then I/we can start updating

**Comment by chrisdembia** [comment]
This issue is related to #384 and #237. It's up to you; my suggestion is we merge that branch (through a PR) and then we can continue to update it. I don't think the CHANGELOG.md in that branch says anything incorrect.

**Comment by jenhicks** [comment]
I agree that we should merge the branch and then continue to update the doc. You might note at the top of the change log that it is under construction.
