### ISSUE TITLE
Fixed markers get un-fixed during scaling. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#465]
When importing markers from an external file during scaling, markers that where checked as fixed becoming unchecked in the output model. 

 [Related simtk forum post](https://simtk.org/forums/viewtopic.php?f=91&t=5665&p=14336#p14336). Was confirmed in 3.2 64-bit windows

**Comment by chrisdembia** [comment]
Is this GUI or C++?

**Comment by jimmyDunne** [comment]
I have only tested it in the GUI. However, I would assume its the
scaletool/genericModelmaker functions. I don't have matlab on my linux
machine so haven't been able to test yet.

**Comment by chrisdembia** [comment]
Can you try using the scale tool from the command line? I import markers frequently and I run scale from the command line. I haven't noticed this behavior but I wasn't necessarily looking closely.

**Comment by jimmyDunne** [comment]
I can get to it tomorrow morning. Will update you then.

**Comment by jenhicks** [comment]
Add fixed option back to Marker. Investigate source of the bug

**Comment by aymanhab** [comment]
"fixed" flag has been restored, need files to reproduce/debug the issue.

**Comment by jenhicks** [comment]
@jimmyDunne Do you have any files to that Ayman can use?

**Comment by jenhicks** [comment]
Or I see you already submitted a PR @aymanhab. Are you still looking for files?

**Comment by jenhicks** [comment]
@jimmyDunne Can you provide a file?

**Comment by jenhicks** [comment]
@jimmyDunne Did you have a chance to check whether this bug was fixed or not?

**Comment by jimmyDunne** [comment]
I did tested the tool through the API and found that 'fixed' is maintained through adding a markers to a model, ModelScaler(), and MarkerPlacer()

```
import org.opensim.modeling.*

model = Model('gait2392_simbody.osim');

%% add markers to model
set = MarkerSet(model,'gait2392_Scale_MarkerSet.xml');
model.updMarkerSet().assign(set);

%% use the scaletool. 
tool = ScaleTool('subject01_Setup_Scale.xml');

%% scale
scale = tool.getModelScaler();

scale.processModel(model, tool.getPathToSubject(), tool.getSubjectMass());

%% register model
register = tool.getMarkerPlacer();

register.processModel(model, tool.getPathToSubject());

%% read the scaled and moved model into memory
smodel = Model('subject01_simbody.osim');

% get if the marker is fixed (fixed == 1)
marker = model.getMarkerSet().get(4).get_fixeed()
>> 1

% get if the marker is fixed (fixed == 1)
smarker = smodel.getMarkerSet().get(4).get_fixeed()
>> 1
```

**Comment by jenhicks** [comment]
Ok -- I will add this to "need verifying" and we can double check everything works as expected in the GUI, as well (seems like it should).

**Comment by jimmyDunne** [comment]
Works as expected on GUI and CMD line.
