### ISSUE TITLE
Potentially remove duplicate Linux build instructions

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#466]
http://simtk-confluence.stanford.edu:8080/pages/viewpage.action?pageId=5114489

**Comment by jimmyDunne** [comment]
Agreed, I didn't realize they were there.

**Comment by jimmyDunne** [comment]
@chrisdembia is there any info you see on this page that could be included in the newer documentation? Or we can just :fire:

**Comment by jenhicks** [comment]
I agree ... that info is in the wrong spot. I vote :fire: as well

**Comment by chrisdembia** [comment]
:fire: :fire: :fire:!

It'd be nice to reference http://simtk-confluence.stanford.edu:8080/display/OpenSim/Building+OpenSim+from+Source from the "Supported platforms" page

**Comment by jimmyDunne** [comment]
We are a bunch of firestarters!

**Comment by jenhicks** [comment]
I removed the duplicate page and added a reference to building from source on the Supported Platforms page. Closing the issue ....
