### ISSUE TITLE
calling printMuscleCurveToCSVFile() of ActiveForcLengthCurve prints a file with the incorrect file name

### ISSUE THREAD

**Issue by mjhmilla** [opensim-org/opensim-core#474]
When printMuscleCurveToCSVFile() is called on any of the new muscle functions the file name does not match the name of the curve. This happens if you make a new ActiveForceLengthCurve, rename it, and then call printMuscleCurveToCSVFile()

**Comment by chrisdembia** [comment]
@aseth1 @klshrinidhi should this method be replaced by the data interface so that users can decide the format in which they want the curves?

**Comment by mjhmilla** [comment]
Sorry, is the 'data interface' an actual interface in OpenSim? I just looked around for one and didn't see one. I agree that the correct approach is to make the muscle curves implement a standard interface.

For the muscle curves that use the SmoothSegmentedFunction class it would be great to have an interface that would have enough functions for a SmoothSegmentedCurveReporter to print/display/fetch useful information about the curves. This would give users the chance to get useful information (like the control points) that is currently not accessible through the muscle curve classes. Perhaps a prototype for this interface might be the following virtual functions:

Vec2 getCurveDomain()
string getCurveDerivativeUnits(Vec_<int> order)
string getCurveArgumentName();
string getCurveDerivativeName(Vec_<int> order)
string getCurveDerivativeValue(arg, Vec_<int> order)

This interface would provide all of the necessary information to unambiguously display or print a SmoothSegmentedFunction.

**Comment by chrisdembia** [comment]
> Sorry, is the 'data interface' an actual interface in OpenSim?

It's under development; #456.
