### ISSUE TITLE
Calling Thelen2003Muscle's printCurveToCSVFile only prints curves to the 1st derivative

### ISSUE THREAD

**Issue by mjhmilla** [opensim-org/opensim-core#475]
Calling Thelen2003Muscle's printCurveToCSVFile only prints curves to the 1st derivative - I'd like to have the curve value, the 1st derivative, and the 2nd derivative.

**Comment by chrisdembia** [comment]
What if the method took an argument for the derivative order?

**Comment by mjhmilla** [comment]
I have an updated version of Thelen2003Muscle here (https://github.com/mjhmilla/opensim-core/tree/muscleCurveUpdate) which does just that. However, Ajay brought up a point earlier: all of the code for the muscle curves, and the muscle models now have separate code in them to print useful quantities. That each individual object has its own code to print information doesn't scale well.

I think what is even better than what is implemented in the prototype is:
1. Perhaps Muscle.h should include two pure virtual functions like: 
     double getMuscleCurveDerivativeValue(arg, derOrder, curveType)
     Vec2    getMuscleCurveDomain(curveType)
     String  getMuscleCurveDerivativeUnits(arg, derOrder, curveType)

    -curveType would be defined in Muscle.h as well perhaps? 
    -This would enforce a standard interface for these two functions, 
    -The guts of the curves could still be kept private, as they should
    -The units would be clear - this is important when dealing with normalized curves.

This standardization of these two making it possible to write one reporter to grab this information and print it. This would also make it possible to include curve plots (or a curve editor) in the GUI at some point.
