### ISSUE TITLE
Appearance class names and hierarchy need improvement

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#480]
In the past OpenSim GUI was capable of displaying surfaces only. The new Geometry interface allows for more general objects (e.g. made of line-segments, text, maybe others). Appearance specification should expose all-and-only-relevant properties for the corresponding type of Geometry.

**Comment by aymanhab** [comment]
Discussion from geometry integration PR #417 
Besides the big picture above here is a summary of issues:

-  The BaseAppearance class should just be the Appearance.
- Appearance should define Representation (currently still DisplayPreference) not Geometry.
The current Appearance class should be SurfaceAppearance since textures can only be applied to surfaces.
- DisplayPreference Enum should be renamed Representation since properties and accessors refer to “representation”. All use of DisplayPrefence (including comments) should be eliminated.
Eliminate “Draw” from the enumerated types of Representation. The Draw prefix adds little. “Hidden’, “Vertices”, “WireFrame”, “Surface” seem clear enough. Why is an explicit Default required is that not implied if one is not specified?
- The Appearance::Representation name (string) should be serialized (e.g. Hidden, Vertices, etc…) (as in the case of Coordinate::MotionType) opposed to its integer value.

**Comment by jenhicks** [comment]
@aymanhab Is this issue still relevant? Or is there another related issue based on the latest PR?

**Comment by aymanhab** [comment]
@jenhicks The arguments have been revised and rediscussed since then in-person, in dev. meeting and ongoing with latest PR of Geometry/Appearance.
