### ISSUE TITLE
Does python wrapping cooperate with python on windows, now that we are using c++11?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#481]
@peastman said that openmm can't use C++11 until python on windows is built with VS2013. So, are we able to use our C++11 python wrapping on windows?

**Comment by sherm1** [comment]
And for OpenSim 3.3 we want to be able to say we support VS2015 also.

**Comment by chrisdembia** [comment]
Right, thanks for adding this. Also, @msdemers has successfully used python wrapping when building opensim with VS2013.

**Comment by aymanhab** [comment]
My understanding is that it depends on the availability of python distributions built with these compilers. From @chrisdembia comments above it seems that this has been done for VS2013. I don't know if anybody has built and packaged python built with VS2015.

**Comment by chrisdembia** [comment]
@peastman was saying all python 2.7 for windows is built with VS2008. The issue might only come into play when using C++11 features? Though not sure that makes sense, since VS versions don't have a "C++11" flag.

**Comment by peastman** [comment]
See https://stackoverflow.com/questions/12028762/what-version-of-visual-studio-and-or-mingw-do-i-need-to-build-extension-modules.  For the official builds from python.org, 2.6, 2.7, 3.1, and 3.2 are all built with VS 2008.  3.3 and 3.4 are built with VS 2010.

I've also used the Anaconda build of Python 3.4, and that was also compiled with VS 2010.  You could compile it yourself with a newer version, but then you might run into problems with a lot of 3rd party modules not working unless you recompiled them too.

**Comment by chrisdembia** [comment]
I just tried to use python 2.7.9 (64bit) with our python wrapping built with vs2013 (64bit). I tried building both as Release and as RelWithDebInfo. In both cases I get this error:

![screen shot 2015-06-08 at 4 46 57 pm](https://cloud.githubusercontent.com/assets/846001/8047753/01592d76-0dfe-11e5-842e-091abdc5c339.png)

**Comment by chrisdembia** [comment]
Thanks @peastman. We can at least try compiling our own python to ensure we know what the issue is.

**Comment by chrisdembia** [comment]
Investigating this on the appveyor-wrapping branch.

**Comment by chrisdembia** [comment]
Our python wrapping still works on windows, so I think we can close this. See #502.

**Comment by chrisdembia** [comment]
@sherm1 @msdemers @peastman I found a good stackoverflow post about using VS2013 to build python extensions:

> Your [VS2013] extension module mustn't access any C runtime objects created by the Python interpreter, nor may it pass any C runtime objects it creates to the interpreter. In particular you can't use any FILE * or file descriptor objects provided by Python. You can still read and write to files in your module, just not files that Python has opened.

http://stackoverflow.com/questions/24708248/can-i-develop-c-extensions-for-python-2-7-through-3-1-on-windows-without-insta

What's an example of writing files in our module that python has opened? How about this:

```
f = open('mymodel.osim')
m = opensim.Model('mymodel.osim')
```

I was able to do the above and still play around with the Model.

However, if I do:

```
f = open('mymodel.osim', 'w')
m = Model('mymodel.osim')
```

I get an error:

```
This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.
```

and a pop up "python.exe has stopped working."

I guess it's conceivable that someone would want to open a model file that they already opened through python. But I think it's fine to discourage such actions. So there are definitely **some** issues with mixing the runtimes. @sherm1 was spot on. I guess I don't really know what "C runtime objects" are, aside from the `FILE*` example given.

Can anyone think of any really bad scenarios? Possibly related to building a GUI in python? @msdemers ?
