### ISSUE TITLE
Be a public member of opensim-org

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#484]
@opensim-org/admin @opensim-org/owners @opensim-org/dev-team 

When someone visits the github opensim-org site, they see a list of the members of opensim-org. But they only see the members who have made themselves "public". So right now, people only see me, @aseth1 , and @jimmyDunne:

![screenshot from 2015-06-10 14 15 37](https://cloud.githubusercontent.com/assets/846001/8094380/983d717e-0f7b-11e5-83e3-872c7ee4b724.png)

 It'd be neat if everyone made themselves public in opensim-org by clicking the dropdown next to their name on this page: https://github.com/orgs/opensim-org/people

**Comment by msdemers** [comment]
Cool thanks!

**Comment by jenhicks** [comment]
Thanks for pointing this out. Done!

**Comment by chrisdembia** [comment]
I'm going to close this, but @apoorvar @carmichaelong @jryong you should go public too!
