### ISSUE TITLE
Ensure and advertise that users can load C++ plugins via python and matlab scripting

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#485]
The code to do so is currently commented out: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Wrapping/Python/swig/pyWrapOpenSim.i#L403

**Comment by jenhicks** [comment]
And matlab?

**Comment by chrisdembia** [comment]
> And matlab?

It's already possible in MATLAB :). The same feature just needs to be carried over to Python. This would be easy to do; we just haven't done it yet.

**Comment by chrisdembia** [comment]
Oh but I don't know if we *advertise* the ability in MATLAB. Okay I'll add MATLAB.
