### ISSUE TITLE
Will there or can there be automatic tracking of units in the new component and data interfaces?

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#489]
Inputs/outputs are required to have a time stamp, as I understand it. Can units be specified as well?

What about the DataTable or DataSource components? Of course, units could be tracked via the metadata, but that doesn't seem as clean as a dedicated mechanism of tracking units.

Apologies if there was already a discussion about this and I missed it!

**Comment by chrisdembia** [comment]
In #499, @aseth1 said:

> I would eventually put support for column units in AbstractDataTable as well.
