### ISSUE TITLE
Update example "From the Ground Up: Building a Passive Dynamic Walker Model" for 4.0

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#494]
Right now, The DynamicWalkerBuild example has errors in it. Notably, it tries to use the names joints when construction CoordinateLimitForces (instead of using the names of coordinates). This example should be tested under a continuous integration system.

This was discovered by Neil Dhir.

**Comment by ndhir** [comment]
The tutorial is provided here, in **section C**: http://simtk-confluence.stanford.edu:8080/display/OpenSim/Part+II%3A+Building+a+Passive+Dynamic+Walker+Model

Where it states

>In order to enforce the coordinate limits set in the joint definitions, we will create a CoordinateLimitForce >for the hip and knee joints that will apply a force similar to a spring and damper to enforce the joint limits.

which would suggest **(?)** that it should be coded as such:


```c++
        //// Coordinate limiting force

        // Define force parameters
        double cordstiffness = 1E6, corddamping = 1E5, cordtransition = convertDegreesToRadians(5);

        // Hip forces
        OpenSim::CoordinateLimitForce* leftHipCordForce = new OpenSim::CoordinateLimitForce(
            "LeftThighToPelvis",
            cordstiffness,
            convertDegreesToRadians(100),
            cordstiffness,
            convertDegreesToRadians(-100),
            corddamping,
            cordtransition,false);
        OpenSim::CoordinateLimitForce* rightHipCordForce = new OpenSim::CoordinateLimitForce(
            "RightThighToPelvis",
            cordstiffness,
            convertDegreesToRadians(100),
            cordstiffness,
            convertDegreesToRadians(-100),
            corddamping,
            cordtransition,
            false);
        // Add force
        osimModel.addForce(leftHipCordForce);
        osimModel.addForce(rightHipCordForce);

        // Knee forces
        OpenSim::CoordinateLimitForce* leftKneeCordForce = new OpenSim::CoordinateLimitForce(
            "LeftShankToThigh",
            cordstiffness,
            convertDegreesToRadians(0),
            cordstiffness,
            convertDegreesToRadians(-100),
            corddamping,
            cordtransition,
            false);
        OpenSim::CoordinateLimitForce* rightKneeCordForce = new OpenSim::CoordinateLimitForce(
            "RightShankToThigh",
            cordstiffness,
            convertDegreesToRadians(0),
            cordstiffness,
            convertDegreesToRadians(-100),
            corddamping,
            cordtransition,
            false);
        // Add force
        osimModel.addForce(leftKneeCordForce);
        osimModel.addForce(rightKneeCordForce);
```

**Comment by chrisdembia** [comment]
Building upon #1697:

- [ ] Update Tim's "Plugin Lecture Slides" for 4.0, recent compilers, and non-Windows platforms (https://simtk-confluence.stanford.edu/display/OpenSim/From+the+Ground+Up%3A+Building+a+Passive+Dynamic+Walker+Model)
- [ ] Student feedback from BIOE 485: dynamic walker lab was disappointing because nothing exciting happened at the end; perhaps include some sort of optimization and/or replace with TGCS 2017 hopper example (could also just give students the "magic" initial conditions so they get the satisfaction of seeing the model walk a couple steps)

**Comment by tkuchida** [comment]
Also see #1775

**Comment by chrisdembia** [comment]
Oops. Thanks @tkuchida. I'll use that issue instead.
