### ISSUE TITLE
Create cmake macro to autogenerate CMakeLists for API examples

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#497]
Discussion with @klshrinidhi and @aseth1 . We can get rid the separate "example tests" and "examples" directories in OpenSim-Core. We will have just one directory called "examples", which will function like the old "tests" directory. Then, when you install the project, we will use an OpenSIm Cmake macro `OpenSimGenerateClientCMakeLists(SOURCES RESOURCES)` that can automatically generate the necessary client-side CMakeLists.txt

**Comment by chrisdembia** [comment]
@klshrinidhi, do you want to take this on (eventually)?

**Comment by sherm1** [comment]
Does this proposal still leave a clear distinction between regression tests and user-friendly pedagogical examples?

**Comment by chrisdembia** [comment]
Yes. Sorry for being unclear. This proposal does not affect anything that is run via "ctest" or "RUN_TESTS." This proposal is to clean up pedagogical examples.
