### ISSUE TITLE
Install fail on Windows 8.1

### ISSUE THREAD

**Issue by fcanderson** [opensim-org/opensim-core#507]
I'm running Visual Studio 2013 Community Edition.

OpenSim (Debug x64) built just fine for me.  However, I got the following error when installing (i.e., right clicking on Install and choosing build):

2>------ Build started: Project: INSTALL, Configuration: Debug x64 ------
2>  -- Install configuration: "Debug"
2>  CMake Error at cmake_install.cmake:31 (file):
2>    file cannot create directory: C:/Program Files/OpenSim/bin.  Maybe need
2>    administrative privileges.

My Windows account is an Administrator account.  In Windows 8.1, being an Administrator is not enough for an application (e.g., Visual Studio) to create directories.  Apparently, the application itself needs to be given Administrative privileges. 

I got passed the above problem in two ways (the 2nd being better).
1.  I created all the needed directories myself (tedious).
2.  I started Visual Studio by right clicking Visual Studio and choosing "Run as Administrator".  This means you can't start Visual Studio by double clicking the .sln file, however.  You have to start Visual Studio using "Run as Administrator" and then navigate to .sln file.

There is probably a third way... Setting Visual Studio to always run with Administrator privileges.  I haven't tried that. 

Not sure there is something that could be done on the OpenSim side.  However, some additions to the GitHub readme where it gives directions for Installing might help some users get past this minor hitch. 

(By the way, I encountered the same error when installing Simbody.  So, this issue surely has to do with how I installed Visual Studio 2013 Community Edition.)

**Comment by chrisdembia** [comment]
We could override the default CMAKE_INSTALL_PREFIX on Windows to be something like `C:\OpenSim-Core`, or `C:\Users\<username>\OpenSim-Core`. Would that work? Where do people typically choose to install OpenSim?

**Comment by aymanhab** [comment]
Yes, I always change the install location. Usually a build directory and a
separate install directory side by side and off program files which is for
development tools and third party apps.

Yes we should have a better default.

Thanks for reporting Clay.

Ayman

**Comment by chrisdembia** [comment]
Please submit suggestions! I vote `C:\OpenSim-Core-4.0` (we can insert the version number into the default).

**Comment by chrisdembia** [comment]
Actually, I don't think we should insert the version number, since any arbitrary commit on github in general does not have a version number.

**Comment by sherm1** [comment]
> Actually, I don't think we should insert the version number

I agree but also because people would then have to change their `PATH` settings on Windows whenever the version number changed.

**Comment by fcanderson** [comment]
I third leaving out the version number.

Concerning the directory, I like the idea of putting the install in a directory that is local to the user.  These days, it is not common for more than one user to use a particular computer, but it might happen (e.g., at a university in a lab).  If we put the install in a directory like c:\OpenSim-Core, then multiple users could step on each other's builds.

How about something like the following?
 c:\Users\<username>\SimTK\OpenSim-Install 

I had the same install issue with Simbody, so the same could be done with Simbody.
c:\Users\<username>\SimTK\Simbody-Install

Assuming "c:\Users\<username>\" is probably not full proof though.  It is possible for users to organize their drives differently if they want to.  However, such advanced users should realize that they need to override default location.

**Comment by chrisdembia** [comment]
I like that.

**Comment by aymanhab** [comment]
I'd like to avoid having SimTK appear anywhere, our users are confused by
the relation between simbody, opensim and Simtk already. I'd suggest
something like Dev or any other generic name. It'd also need to be platform
dependent, what's common on Linux and Mac.

**Comment by chrisdembia** [comment]
Then why don't we just leave out `Dev` and just put it in `C:\Users\<name>`?

On Linux, we can put it in `~\opensim-core`

**Comment by fcanderson** [comment]
Good point about SimTK Ayman, though Dev would be kind of confusing also I think.  A user wouldn't know who created Dev or be able to tell what's inside it (unless they looked).  So, I'm liking Chris' suggestion.  If I've got it right...

On Windows:
c:\Users\<username>\OpenSim-Core-Install
c:\Users\<username>\Simbody-Install

On Linux and Mac:
~/OpenSim-Core-Install
~/Simbody-Install

I don't know what the cap convention is that the dev team has come to use.  I like tacking "Install" on the end like Ayman does so that the install directories can be easily distinguished from the source and build directories.

**Comment by chrisdembia** [comment]
On Windows, caps are fine (especially b/c the file system is case-insensitive). On UNIX, most conventions are to use lowercase.

**Comment by aymanhab** [comment]
I really didn't like Dev either and I was hoping other names would come up. I just didn't want to pollute the directory structure with too many directories, but that may be ok. I agree with @chrisdembia on case sensitive on Windows and lowercase otherwise.

**Comment by fcanderson** [comment]
Maybe the cleanest solution is to do what Ayman does:  put the install next to the source and build directories.  Permissions would not an issue; the user would certainly know where he/she had chosen to put the source, and this would reduce directory clutter.  So, for example...

c:\Users\fca\GitHub\opensim-core
c:\Users\fca\GitHub\opensim-core-build
c:\Users\fca\GitHub\opensim-core-install

My user name is 'fca', and I put all my source in a directory called 'GitHub'.

I don't know if this could be done in CMake however.  Can CMake be made to put the install directory along side the source directory by default, just as it does for the build directory?

**Comment by chrisdembia** [comment]
Okay I pushed a branch with these changes (for opensim). It can't be merged yet until one of my existing PR's is merged, so I'll wait until that's merged before making a new PR.

**Comment by sherm1** [comment]
Sorry, late to the party. Not clear to me that non-English machines will have a "Users" directory, but everyone has a "C:". We have the same problem with the "Program Files" directory but there is a standard environment variable for finding it in the local language.
