### ISSUE TITLE
Consider operator syntax for connecting inputs and outputs

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#508]
Right now, the line of code to wire an output to an input is:

```
compA.getInput("foo").connect(compB.getOutput("bar"));
```

It'd be really neat to be able to do that connection via:

```
compB.getOutput("bar") >> compA.getInput("foo");
```

**Comment by aymanhab** [comment]
Indeed that would be nice, but as always a functional equivalent should continue to exist to accommodate non c++ users.

**Comment by chrisdembia** [comment]
> Indeed that would be nice, but as always a functional equivalent should continue to exist to accommodate non c++ users.

Completely agree. The neat operators should be implemented using such code.

**Comment by sherm1** [comment]
> compB.getOutput("bar") >> compA.getInput("foo");

It is easy to get carried away with operator overloading. I think this might be one of those cases! That might be nice to write but I think it will be confusing for most programmers to read. It is easily misinterpreted as some kind of input operation.

**Comment by chrisdembia** [comment]
Aww okay :(

**Comment by chrisdembia** [comment]
We could alternatively use `operator>>=`.
