### ISSUE TITLE
Address clang-detected bugs related to "++start, end - start"

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#513]
https://github.com/opensim-org/opensim32/pull/58

**Comment by sherm1** [comment]
Also see this one that slipped past: opensim-org/opensim32#68

**Comment by aymanhab** [comment]
All instances of the method getStateVariableSystemIndex were already removed from opensim-core. :fire:

**Comment by sherm1** [comment]
Yay! Should this be closed then?

**Comment by aymanhab** [comment]
There's one item related to Geometry path moment arm solver which uses
reference pointer incorrectly, I can add reference there and close.

**Comment by aymanhab** [comment]
Method GeometryPath::computeMomentArm has improper use of ReferencePtr that needs to be fixed per #528 so will not backport fix in 3.3 since ReferencePtr will be removed altogether #528
