### ISSUE TITLE
Find out how to distribute Geometry, since it is no longer contained in this repository.

### ISSUE THREAD

**Issue by cjblack** [opensim-org/opensim-core#515]
Hi,

  I recently compiled and built OpenSim on OS X, and run my setup through terminal.  I can get the example models to show up and run; however, I have a pre existing osim model with the appropriate geometry files, but when I build the project and run it all I see through the visualizer is super imposed axes with no geometry/animation.

I am sure I am doing something wrong, but I am not sure exactly what C++ I should implement to visualize a pre existing model.  Any help would be greatly appreciated, thanks!

cjblack

**Comment by chrisdembia** [comment]
Hey @cjblack are you working off of the master branch of this repository (or a released version of OpenSim, like v3.2)? In order to help you I think we'd need to see the model you're trying to use. You can use a service like pastebin to share it here.

**Comment by cjblack** [comment]
So, I don't have the model on me right now.  But I can tell you I am using
the master branch.  I'm just not sure if there is some boiler plate code
that I need?

**Comment by chrisdembia** [comment]
Oh! I think I know what this is. In the transition from OpenSim 3.2 to OpenSim 4.0 (this opensim-core repo), we're in a bit of a limbo. This OpenSim 4.0 repo does not contain the geometry files that are used in most of the models we distribute with OpenSim. In order for the geometry to show, you need to set the OPENSIM_HOME environment variable to the location of an OpenSim 3.2 installation, basically. I suggest you download the OpenSim 3.2 source distribution, unzip it to say `~/opensim32`, which will contain a `Geometry` folder. If you set `OPENSIM_HOME` to `~/opensim32`, then the geometry should show up.

By the time we release OpenSim 4.0, this issue will be resolved.

**Comment by chrisdembia** [comment]
Please let me know if that is indeed the problem. If so, we can rename this issue to "Find out how to distribute Geometry, since it is no longer contained in this repository."

**Comment by cjblack** [comment]
Thanks!

I've tried installing the OpenSim 3.2 version, but I'm now running into a
Simbody problem.  Cmake doesn't seem to accept the 3.5 version of
simbody...there is an issue of finding the Simbody_INCLUDE_DIR, even though
I know everything is set correctly.  So I have tried setting it up with the
Simbody version 3.3; however, now it registers the following error:

MACOSX_RPATH is not specified for the following targets:

SimTKcommon
SimTKmath
SimTKsimbody



Any suggestions?

**Comment by cjblack** [comment]
You were right, chrisdembia, it was a versioning issue.  I was able to get it working from some older source code, although I am not exactly sure what branch/when this was done.  Thank you for the help though!

**Comment by chrisdembia** [comment]
@cjblack sorry for being unclear but you wouldn't need to build OpenSim 3.2. You only need the Geometry folder from the source code.

**Comment by jenhicks** [comment]
Geometry is in the opensim-models repo which we can make public at the time of the release, so I am closing this issue.

**Comment by chrisdembia** [comment]
I guess there is still an issue of how we exactly distribute content in the models repo. We also will have to deal with paths related to geometry. I think it's fine to close this issue though.

**Comment by aymanhab** [comment]
Yes, we have an issue with how to assemble a distribution out of the multiple repositories (API, GUI, models) and byproducts of builds, examples, scripts but probably that doesn't belong to this issue which was specific to geometry.
