### ISSUE TITLE
Update Doxygen for Property.h to account for existence of Connectors

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#517]
The Property.h doxygen says

> If you want to reference another Object from within a property, use a string property to reference it by name; the result is a simple property

but I think this should be revised to account for the existence of Connectors.

Thanks @sherm1 for prompting me to realize this via #478.

**Comment by chrisdembia** [comment]
We also need to update the example `ActuatorWorkMeter` example in Property.h so that it doesn't contain an example of referencing another object via a string name.

**Comment by jenhicks** [comment]
@chrisdembia Can this be closed?

**Comment by chrisdembia** [comment]
Not yet.
