### ISSUE TITLE
Serialization of 2nd level derived class with properties

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#519]
It is not really an issue because there is a workaround. I had an abstract class A that derives from ModelComponent and have some properties. Next I have some concrete class B that derives from A with some extra properties. When print method (to xml) is called only the properties of class A are stored. I had to explicitly call setSerializeAllDefaults(true) before calling print in order to store the rest of the properties of B. Is this behavior correct?

**Comment by chrisdembia** [comment]
If a property is set to its default value, it is not serialized (each property keeps track to see if it is set to the default value). Try changing all the property values (to something other than the default), then try serializing. You should then *not* need `setSerializeAllDefaults(true)`.

In fact, if you serialize class A without changing any properties, the resulting serialization should be empty:

```xml
<A name="thename">
</A>
```

**Comment by mitkof6** [comment]
Thank you for the reply. As you said, when I set the property, and serialize the class this property is included.

**Comment by chrisdembia** [comment]
Excellent!
