### ISSUE TITLE
Replace contact getRecordValues() with Output mechanism.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#520]

**Comment by aymanhab** [comment]
This issue has been moved to backlog but a user at the Virtual Workshop needs to hook a ContactForce to a TabelReporter and is stuck with this issue. Any work around is appreciated.
@chrisdembia @aseth1 @carmichaelong

**Comment by chrisdembia** [comment]
If using MATLAB/Python, the following should work:

```
states = StatesTrajectory.createFromStatesStorage(sto);
for i = 0:states.getSize() - 1
    arrayDbl = force.getRecordValues(states.get(i));
    % do something with arrayDbl; convert to MATLAB.
end
```

**Comment by aymanhab** [comment]
Thanks @chrisdembia but the difficulty is not in extracting the values but rather in wiring a reporter so that results are reported at meaningful intervals.  My understanding is that reporters need outputs rather than values, unless there's a way to create an "Output" on the fly.

**Comment by chrisdembia** [comment]
I don't know of a way to create outputs on the fly.
