### ISSUE TITLE
OpenSim should print a more detailed message upon loading of a plugin.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#521]
Right now it prints a generic message like

> Loaded library

It'd be nice if it printed

> Loaded library 'larrysPlugin'

**Comment by aymanhab** [comment]
Agreed, but some context please. e.g. Is this from API programs, GUI, python, all-of-the-above?

**Comment by chrisdembia** [comment]
Sorry; API programs.
