### ISSUE TITLE
Turn deprecated warnings back into errors in Travis

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#532]
Because of unresolved issue #528 we are getting expected "deprecated" warnings about `ReferencePtr` usage. We run Travis CI builds in "warnings are errors" mode, so this prevents those builds from succeeding. In PR #510 I allowed just the "deprecated-declarations" warning for now so the builds will succeed.

As soon as issue #528 is resolved we should disallow these warnings again.

**Comment by jenhicks** [comment]
@chrisdembia Can this be closed?

**Comment by chrisdembia** [comment]
Yes
