### ISSUE TITLE
Member variable name convention: `_name`, `m_name`, `name_`

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#533]
In #530, @sherm1 said:

> Trailing underscore to indicate member variables does not match the OpenSim coding guidelines, which specify leading underscore. Personally I hate leading underscore since it is borderline non-compliant with the C++ standard. Much more common (and conformant) is the m_ convention which I have been moving to in Simbody. We should discuss to see whether the OpenSim team would be amenable to using m_, otherwise I think you have to stick with leading underscore. I don't think we should introduce a third convention in any case.

I'm opening this issue to start this discussion.

I personally really like `m_`. It looks professional to me. I am in favor of allowing `_name` and `m_name`, as long as only one convention is used in any given class.

**Comment by sherm1** [comment]
> I am in favor of allowing _name and m_name, as long as only one convention is used in any given class.

I like that idea. I would propose that we formally make `m_` the "preferred" convention for new code, and encourage gradual switching to that convention whenever a class undergoes major hacking.

**Comment by chrisdembia** [comment]
> I like that idea. I would propose that we formally make m_ the "preferred" convention for new code, and encourage gradual switching to that convention whenever a class undergoes major hacking.

+1

**Comment by klshrinidhi** [comment]
I would like OpenSim to follow Google C++ Style Guide:
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html

I know it is very important to stick to one convention for readability and maintainability. I don't like some things about the OpenSim coding conventions. I am suggesting the above style guide because it comprehensive, it is updated regularly, and a lot of projects follow it. C++ developers are used to seeing that convention in other open source projects. There will be things in that style guide that some of us don't like but I think it is a very good compromise.

**Comment by sherm1** [comment]
Google's is a nice style guide, but not uniformly revered. For example, I think this would be awkward for us (from the section on Exceptions):
> We do not use C++ exceptions.

**Comment by klshrinidhi** [comment]
I think exceptions are the only thing they don't cover because I heard that internally Google does not use exceptions in their code. But because exceptions are tiny classes, we can apply class conventions to exceptions too.

**Comment by sherm1** [comment]
Google's style guide is a lot more comprehensive than ours, but still can't cover everything we need (for example, Property names). We could consider saying that anything we don't cover explicitly in ours should follow theirs. That's what our Open Source Robotics Foundation colleagues do (see [this page](http://www.gazebosim.org/tutorials?tut=contrib_code&cat=development), scroll down to "Style" section). They don't agree with Google on naming and many other things, but they still punt to Google "in general".

**Comment by klshrinidhi** [comment]
I basically agree. There will be things specific to our project and we can have conventions for those to closely resemble Google's but we have to keep it very minimal. There will be things in the style guide that some of us will not like but I think it is a good compromise considering that many projects use it.

**Comment by sherm1** [comment]
I don't see it as a compromise. We should have our own standards for things that matter to us, and then could refer to Google's for areas that we haven't specified. I don't think we should change any of our existing standards to theirs without team discussion. In particular, I think we should continue to use exceptions and our own naming conventions.

**Comment by klshrinidhi** [comment]
I don't think we should have our own primary conventions and use Google's style guide as secondary. I would like to follow Google's style guide as primary and have our conventions at some necessary places and document it.
We should discuss this soon in a meeting.

**Comment by jenhicks** [comment]
This was on the list for today's meeting, but we ran out of time. We can discuss at a future meeting.
