### ISSUE TITLE
Need test to verify that components in older formats are deserialized correctly

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#535]
Most components are verified by virtue of older model files being used by other test cases. But in many test cases (esp. Joints, Constraints and Forces) models are built programmatically (without loading a model from file) and the serialization loop is tested only in the latest version.

In order to ensure that the content of older models is preserved they must be verified to contain the same content in the latest version of the model.

**Comment by aymanhab** [comment]
Agreed, combine with #206 opened earlier.

**Comment by jenhicks** [comment]
I added Ajay's comment to the existing issue. I'm closing this issue since it is a duplicate.
