### ISSUE TITLE
Using C++14 and moving to newer C++ standards in general

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#537]
I think we have had conversations about this before but I wanted to get this written down.

Here is the compiler support for latest C++: http://en.cppreference.com/w/cpp/compiler_support

I want to make:
- A list of challenges to switch to using newer C++ standards as they come out.
- A list of suggestions on overcoming the challenges.

Challenges:
- Python/Matlab wrapping is one I recall people mentioning often. 
- doxygen documentation may get cryptic.
- [Solved] Continuous integration needs to have the latest compilers and tools to build OpenSim.

**Comment by sherm1** [comment]
From the table it looks like we're in pretty good shape with MSVC 14 (2015) and clang even at 3.4 (which is widely available). Looks like gcc has to be a level 5.0 though; hopefully that will be widely available soon.

One challenge is that we need to be able to use continuous integration during development. That means we have to have our Travis and AppVeyor build systems set up to succeed in compiling OpenSim 4.0 and running its tests.

**Comment by chrisdembia** [comment]
> One challenge is that we need to be able to use continuous integration during development. That means we have to have our Travis and AppVeyor build systems set up to succeed in compiling OpenSim 4.0 and running its tests.

I think we can get gcc 5.0 on travis fairly easily now. I think the challenge is moreso about users who might be using Ubuntu 12.04, or a cluster that has an old version of gcc (red hat linux on the sherlock cluster). Either @carmichaelong or I should see if we can use gcc 5 on the sherlock cluster.

**Comment by chrisdembia** [comment]
It seems like the sherlock cluster's latest gcc is 4.8 (http://sherlock.stanford.edu/mediawiki/index.php/Software). The staff that manages the cluster is very responsive, and so I think they would install 5.0 at our request. However, this wouldn't help other users of ours whose cluster management isn't so responsive.

**Comment by carmichaelong** [comment]
Emailed Sherlock support asking what their plans for GCC 5 was. Sounds like they are waiting for GCC 5 to stabilize out a bit before moving forward, and they want to do a bit of testing before adding it officially to the module list. They're looking at mid-August to early September.

**Comment by chrisdembia** [comment]
Awesome; thanks @carmichaelong .

**Comment by klshrinidhi** [comment]
GCC 5.2 was released yesterday (07/16). Try to upgrade to at-least GCC 5.1 when you do.

Are there any suggestions for overcoming the following ?
* Python/Matlab wrapping.
* doxygen not keeping up with latest C++ so it ends up producing cryptic documentation.

**Comment by sherm1** [comment]
> doxygen not keeping up with latest C++ so it ends up producing cryptic documentation

Since we only use doxygen on the user-visible part of the API we can just avoid using the latest features there until our whole toolchain can support them. Also our API users are generally biomechanists first, and not the most advanced programmers or C++ experts. It is important to have some sympathy for them and not to confront them with unfamiliar constructs.

Internally we can do anything we want that can make it through all of our supported compilers.

**Comment by sherm1** [comment]
> Python/Matlab wrapping

Problem here are also restricted to the API, in fact just a subset of the API. I think they are also best handled by employing some discretion and a focus on what will best serve the end users. This is probably a good reason to look at scripting use cases early on to make sure our designs are suitable for our actual users.

**Comment by chrisdembia** [comment]
> This is probably a good reason to look at scripting use cases early on to make sure our designs are suitable for our actual users.

+1; I don't think we do this enough. We need to play with connectors, outputs, inputs and iterators through scripting soon.

**Comment by sherm1** [comment]
> We need to play with connectors, outputs, inputs and iterators through scripting soon.

Everyone was very excited at Thursday's meeting about your idea of doing pseudo-code walkthroughs and we scheduled two of them.

**Comment by chrisdembia** [comment]
Yay! I'm looking forward to it. I hadn't thought of including scripting in the pseudo-coding but I think it's a good idea.
