### ISSUE TITLE
Where do python and matlab scripts live in the new repo layout?

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#539]
We need to port over the new scripts that @jimmyDunne added in OpenSim 3.3

**Comment by aymanhab** [comment]
OpenSim\Wrapping\Python has tests subdirectory and can add an examples or scripts directory next to it, similar to how the Java side has a Matlab subdirectory.

**Comment by chrisdembia** [comment]
That's one possibility, but I'd like to discuss this in person. Another option is the opensim-models/examples repo.

**Comment by jenhicks** [comment]
Where are the matlab and gui scripts for now? The GUI repo? I need to make an issue to port over the updates and changes that James made for 3.2

**Comment by chrisdembia** [comment]
Matlab scripts (opensim-core): https://github.com/opensim-org/opensim-core/tree/master/OpenSim/Wrapping/Java/Matlab

GUI scripts (opensim-gui): https://github.com/opensim-org/opensim-gui/tree/master/Gui/opensim/Scripts

**Comment by jimmyDunne** [comment]
An alternative is for the scripts to live in the Models and Examples repo. Especially Python scripts since we will be able to use Travis to test.

**Comment by jenhicks** [comment]
@jimmyDunne Can you make issues or PRs to merge the scripts you created or updated in 3.3?

**Comment by jimmyDunne** [comment]
:+1:

**Comment by jimmyDunne** [comment]
#541
