### ISSUE TITLE
[wrapping] Name of ComponentList classes.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#551]
Thanks @aymanhab for wrapping the ComponentList. You've created classes like:

```
ComponentList
ComponentIterator
FramesList
FrameIterator
BodiesList
BodyIterator
```
I want to discuss two things:

1. Can we rename the `*List` classes to the singular form? e.g., `BodyList`. I think this is important since if I'm searching for all classes related to "Body", then "BodiesList" would not show up.
2. Is it necessary to wrap the iterator classes? Have you tried to use them in python? If so can you point me to an example? The way I envision using the iterator I think does not involve exposing the c++ iterator to the user.

**Comment by aymanhab** [comment]
@chrisdembia I don't mind using the singlular name for the "List", I avoided it since I expected that our Sets (e.g. BosySet) will be migrated at some point to (BodyList) when we switch to "List" properties but we can do this now and resolve the naming when/if the migration occurs.

**Comment by aymanhab** [comment]
Here's an example for how BodiesList is used in the latest version of the GUI
'''
            BodiesList bodies = model.getBodiesList();
            BodyIterator bi = bodies.begin();
            ......
            while (!bi.equals(bodies.end())) {
                .....
                bi.next();
            }
        }

**Comment by chrisdembia** [comment]
> I avoided it since I expected that our Sets (e.g. BosySet) will be migrated at some point to (BodyList) when we switch to "List" properties but we can do this now and resolve the naming when/if the migration occurs.

Oh good point I didn't think about that.

It's neat to see how you can directly use the C++ iterator in Java. In python, I don't want users doing what you have; I want them to be able to write
```
for body in model.getBodiesList();
```

**Comment by aymanhab** [comment]
@chrisdembia Sweet. Python code is definitely simpler but it'd be also good if the other syntax also works so users can go between examples/scripting environments smoothly. Thoughts?

**Comment by chrisdembia** [comment]
That's fine with me.

**Comment by sherm1** [comment]
I also like `BodyList` rather than `BodiesList`. The latter sounds like a double-plural to me, like a list of lists.

**Comment by aymanhab** [comment]
Sure, if it gives incorrect connotation then let's change the names (luckily this's all in the .i files)

**Comment by chrisdembia** [comment]
I'm willing to wait until we resolve the list properties/sets design issue.

**Comment by aymanhab** [comment]
@chrisdembia The sooner the better for me since the GUI uses those and I'd like to have users/developers switch to using iterators for new code soon to avoid rewrites.

**Comment by chrisdembia** [comment]
Should we finalize the decision at this week's dev meeting then? It would be nice if we could discuss this along with the discussion about property lists vs sets as well.

**Comment by jenhicks** [comment]
@chrisdembia What's the status on this issue?

**Comment by chrisdembia** [comment]
I don't think we've taken any action on the issue (BodiesList is still named BodyList), though I think we have had some related discussion. I think this issue should still stay open. If we want to split this into short-term and long-term tasks, I'd like if in the short-term we use the singular form for lists, and in the future when we figure out a consistent design for the use of list properties/sets, we can revisit the scripting side.

**Comment by jenhicks** [comment]
@aymanhab can you review status, particular ComponentsList/ComponentList
