### ISSUE TITLE
Need help testing the confluence upgrade

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#556]
Henry has migrated our confluence server to the latest version, available (for review and testing) here:

http://simbios-ff:8080/

Please check it out, and let me know if you see issues (a list of known things to do is at the bottom of this comment). You'll need to be on the Stanford network.

When we're done testing, this version will become the new live version. So please also suspend making any major edits to the live confluence site, for now. If there are minor corrections or additions to make on the live confluence server, feel free to implement these and we can replicate on the test server. (If we find major issues during the testing process that will delay its release, we could take another snapshot of the current confluence version, if needed.)

I'm thinking we could roll this out fairly quickly (say next week), but let me know if you have other thoughts/opinions on timing

Things To Do:
- [x] Make any updates since snapshot taken on 7/15
- [x] Fix the icon sizing
- [x] Find out if there's a new version of the latex equation renderer
- [x] Check for other plug-ins we're actively using
- [x] Update pages with latex equations to use the new macro
- [x] Remove the contributing to confluence page and replace with link to confluence documentation

**Comment by chrisdembia** [comment]
@jenhicks I turned your todo list into a checklist.

**Comment by jenhicks** [comment]
Thanks @chrisdembia 

I also should have added: cc @jimmyDunne

**Comment by chrisdembia** [comment]
The footer on the new confluence takes up more screen space than the live confluence. It's not a big deal but it would be nice to keep the footer as minimal as possible. Ideally we would remove the bottom-most footer, as it is somewhat redundant with the one mentioning the community license.

**Comment by chrisdembia** [comment]
The OpenSim icon in the title to each page is now a circle, which cuts off the OpenSim icon (e.g. on this page http://simbios-ff:8080/display/OpenSim/Introduction+to+the+OpenSim+API)

**Comment by jimmyDunne** [comment]
"This webpage is not available" :frowning:

**Comment by chrisdembia** [comment]
The images on the [Contributing to the OpenSim documentation](http://simbios-ff:8080/display/OpenSim/Contributing+to+the+OpenSim+Documentation) page might need to be updated:

The image of the editing toolbar is no longer accurate:
![image](https://cloud.githubusercontent.com/assets/846001/8919278/e88c244c-3472-11e5-911f-775bd220974b.png)

Furthermore, links are no longer underlined, so the text links within the edit box look like one line. We could fix this by making a bulleted list within the edit box. I'd make this change but I don't know where to do it.

**Comment by jenhicks** [comment]
(1) The icon issue is noted in the list -- will try a different size or see if we can change how it's displayed

(2) I think we can eliminate the how to contribute to doc page and refer to the confluence documentation here: https://confluence.atlassian.com/display/DOC/Pages+and+Blogs

**Comment by chrisdembia** [comment]
> (1) The icon issue is noted in the list -- will try a different size or see if we can change how it's displayed

Oops! Sorry.

Jen, did you mean the LaTeX equation editor?

**Comment by chrisdembia** [comment]
Related to the equation rendering: equations on [this page](http://simbios-ff:8080/display/OpenSim/Pulling+Out+the+Stops%3A+Designing+a+Muscle+for+a+Tug-of-War+Competition) are not rendered.

**Comment by chrisdembia** [comment]
This is an issue on the live confluence as well: the "From the Ground Up" example has weird formatting in which the page contents is squished: http://simbios-ff:8080/display/OpenSim/From+the+Ground+Up%3A+Building+a+Passive+Dynamic+Walker+Model. The page definitely wasn't always like this though.

I'm done looking through the new confluence. It looks great.

**Comment by jenhicks** [comment]
Thanks @chrisdembia ! And my oops .. I did mean LaTeX.

**Comment by jenhicks** [comment]
I updated the Latex content on this page:
http://simbios-ff:8080/display/OpenSim/Millard+2012+Muscle+Models

Let me know if you see any issues. Note that it takes a few seconds to render.

**Comment by sherm1** [comment]
> I updated the Latex content ...

Looks great in Chrome and Internet Explorer on Windows 8.1.

**Comment by chrisdembia** [comment]
I found a small typo; just fixed it. As for the equation rendering taking a few seconds: if we put a copy of MathJax on our server, we might be able to get rid of that delay.

**Comment by chrisdembia** [comment]
I used Firefox on Ubuntu and the page looks good. Much better than it used to, also! The parentheses used to be so huge.

**Comment by jimmyDunne** [comment]
Got through the list. Should be good to now check.

**Comment by jenhicks** [comment]
Thanks @jimmyDunne 

Looks good. The only think I noticed was that I think you need to attach and reinsert the images for Kate Saul and Matt Millard to the OpenSim Fellows page.

**Comment by jenhicks** [comment]
To clarify my comment above -- the images appear, but I think they are being pulled from the live simtk website and when we make the switch those images might disappear.

**Comment by jenhicks** [comment]
One remaining issue -- there are 4 users who have created an account since we made the snapshot used to create the version on simbios-ff. Once the upgraded version is live, we can create accounts for them on the upgraded version and they'll get an email to change their password. (Again, will have to wait until the upgraded version is live to do this so that they'll get a link to the new version that actually works for non-stanford people)

**Comment by jimmyDunne** [comment]
Attached and reinserted jpg's.

**Comment by jenhicks** [comment]
Thanks @jimmyDunne 

Please suspend editing of simbios-ff this morning -- Henry is upgrading the memory allocated.

Then we'll make the switch later today (2pm) or on Monday morning.

cc @chrisdembia @sherm1 @tkuchida

**Comment by chrisdembia** [comment]
Would it be a good idea to leave the old site up in some hidden location in case we find some other weird things in the next month?

**Comment by jenhicks** [comment]
Yes -- the old site will live at simbios-ff (current test server) for a while.

**Comment by jenhicks** [comment]
The new site just went live. Let me know if you see any issues.

**Comment by chrisdembia** [comment]
:fireworks:

**Comment by chrisdembia** [comment]
Could we use this as an opportunity to update the URL for the wiki so that people can use `simtk-confluence.stanford.edu` without the `:8080`?

**Comment by jenhicks** [comment]
I don't have the bandwidth for this at the moment. You could file a separate issue.

**Comment by chrisdembia** [comment]
So I know that we should use the new "Math Block" and "Math Inline" macros instead of the old "Math Formula" macro. However, is that old macro gone? We still have pages that use the Math Formula macro and the equations show up as latex source. Could we reinstall the Math Formula macro until we convert all equations?

**Comment by chrisdembia** [comment]
![screenshot from 2015-11-04 16 02 20](https://cloud.githubusercontent.com/assets/846001/10956108/d9e1e1ae-830d-11e5-9d80-bc45dc716388.png)

When previewing edits on confluence, the OpenSim logo is huge!

**Comment by jenhicks** [comment]
I can't reproduce the large logo issue. I'm using Chrome. Maybe it's a browser issue?

Also, regarding equations -- the goal was to convert everything. Are there other places that we missed?

**Comment by chrisdembia** [comment]
> Maybe it's a browser issue?

I used Firefox. @klshrinidhi can you test with Firefox?

> Are there other places that we missed?

I'm not sure (I don't know an easy way to do a comprehensive check), but it seems likely since I was able to find some pages that weren't converted. I *did* convert all the pages that I saw.
