### ISSUE TITLE
Visualization Requests

### ISSUE THREAD

**Issue by fcanderson** [opensim-org/opensim-core#568]
Ayman and I had a discussion last week (on Wed 7/29, I believe) about some features that would be good to have in the Visuals for 4.0.  He suggested I create an issue so that visualization requests could be tracked.

There may be a number of requests that accumulate.  I will get the list started with an item that came up during my work on the Stiffness Controller.

SPRINGS
It would be nice to have a Spring Primitive, for which the following could be specified
a) loops per unit length (i.e., thread count - how many loops it makes per meter, for example),
b) coil diameter (i.e., the diameter at which the spring orbits its axis),
c) wire diameter (i.e., the diameter of the wire used to make the spring), and
b) length (i.e., the length of the spring along its axis).

Functionality for the Spring Primitive
a) specify an origin and insertion, or more generally a path (e.g., a sequence of line segments),
b) specify a color that can change over time (e.g., to reflect activation level or force level),
c) display an indicator of rest-length (e.g., a disc along the length of the spring).

**Comment by fcanderson** [comment]
CAMERA CONTROL
I find the camera control cumbersome.  Here are some specifics:
1. The rotation point is always the global origin.  It would work better (I think) if the rotation occurred about the center of the view.  In this way, you could translate the model so that whatever you wanted to look at was at the center of the view.  Then rotations would leave what you wanted to look at in place.
2. The view perspective cubes in the upper right of the 3D view (i.e., the cubes with the red, green, and blue faces) when pressed translate the scene so that the global origin is at the center of the view.  This translation frequently takes what I wanted to view out of the view.  It would be better (I think), if the view perspective cubes simply changed the rotation and did not translate.
3. It is difficult to rotate about the vertical axis of the view.  Spinning the model around most often makes the model wobble.  It would be handy to have a modifier key (or different mouse model) so that the view can be made to rotate purely about the Y-axis of the scene.   Perhaps there is a modifier that I don't know about.

**Comment by chrisdembia** [comment]
> It would be better (I think), if the view perspective cubes simply changed the rotation and did not translate.

I partially agree. Sometimes I click a cube to just change rotation and then I need to use the scroll wheel to zoom back in. However, sometimes I use those buttons to put everything back into view (to zoom out). So if we change the function of these buttons, I'd like an additional "Zoom out" button that puts everything in view.

**Comment by chrisdembia** [comment]
Along these lines, a toggle-able diagram that shows the key bindings would be useful.

**Comment by jenhicks** [comment]
Issue moved to [opensim-org/opensim-gui #28](https://github.com/opensim-org/opensim-gui/issues/28) via [**ZenHub.io**](https://www.zenhub.io/)
