### ISSUE TITLE
Coordinate::MotionType should not be exposed

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#583]
Whether or not a Coordinate represents Rotational, Translational or Coupled motion should not be user settable. It should be predetermined by the Joint type. Coordinates should:
1.  be allocated by concrete Joint types and belong to a fixed sized property list of Coordinates (no more CoordinateSet)
2. have their motion type set by the Joint
3. be accessible (to set its name, set default value and ranges) immediately after creation of the Joint. Currently this is done in Joint::extendFinalizeFromProperties which seems too late and awkward to have to call finalizeFromProperties.

**Comment by jenhicks** [comment]
@aseth1 Please check if this can be closed.

**Comment by aseth1** [comment]
Closed by #589, #894 and #1404.
