### ISSUE TITLE
Properties that are List of "Objects" do not support search by name 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#584]
To use the LIST property and make it a viable replacement for OpenSim::Set it needs to support search by name.

**Comment by jenhicks** [comment]
@aymanhab any status updates on this issue?

**Comment by aymanhab** [comment]
Yes, @jenhicks that has been fixed by PR #588 we can close.

**Comment by jenhicks** [comment]
Thanks @aymanhab ... closing.
