### ISSUE TITLE
AssemblySolver should catch a more specific exception than std::exception

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#590]
Also, the normal control flow right now is to throw and catch an exception when calling `Model::assemble()`. Perhaps this could be reworked so that exceptions are not normally thrown.

**Comment by aymanhab** [comment]
@chrisdembia I totally agree. Exceptions are normally thrown in Error situations. Failing to assemble because we're starting from a configuration not close to solution doesn't sound like an Error to me.

**Comment by chrisdembia** [comment]
I was unaware of that case. I was speaking of [this catch block](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Model.cpp#L425).

**Comment by aymanhab** [comment]
Yes, that's what I mean too. the call to "track" on line 423 succeeds or fails depending on starting state, so not converging and calling assemble on line 428  is not an error. Whether failing to meet constraints to a tolerance is an error, is up for debate. If we consider it an error it should throw its own specific exception as you suggested.

**Comment by aseth1** [comment]
I agree the exception should be specific. Thanks.
