### ISSUE TITLE
Remove SWIGSimTK folder (copies of SimTK headers for wrapping)

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#592]
@aymanhab @sherm1  I've given a first shot at this and there are only 4 issues holding us back now, all of which are deficiencies in swig's parser:

(1) https://github.com/simbody/simbody/blob/master/SimTKcommon/include/SimTKcommon/internal/common.h#L785

``` cpp
static const bool Is64BitPlatform = sizeof(size_t) > sizeof(int);
```

We could fix this via:

``` cpp
constexpr bool Is64BitPlatform() {return sizeof(size_t) > sizeof(int);}
```

(2) https://github.com/simbody/simbody/blob/master/SimTKcommon/SmallMatrix/include/SimTKcommon/internal/Vec.h#L248

``` cpp
    enum {
        NRows               = M,
        NCols               = 1,
        NPackedElements     = M,
        NActualElements     = M * STRIDE,   // includes trailing gap
        NActualScalars      = CNT<E>::NActualScalars * NActualElements,
        RowSpacing          = STRIDE,
        ColSpacing          = NActualElements,
        ImagOffset          = NTraits<ENumber>::ImagOffset,
        RealStrideFactor    = 1, // composite types don't change size when
                                 // cast from complex to real or imaginary
        ArgDepth            = ((int)CNT<E>::ArgDepth < (int)MAX_RESOLVED_DEPTH 
                                ? CNT<E>::ArgDepth + 1 
                                : MAX_RESOLVED_DEPTH),
        IsScalar            = 0,
        IsULessScalar       = 0,
        IsNumber            = 0,
        IsStdNumber         = 0,
        IsPrecision         = 0,
        SignInterpretation  = CNT<E>::SignInterpretation
    };
```

(3)
https://github.com/simbody/simbody/blob/master/SimTKcommon/SmallMatrix/include/SimTKcommon/internal/Mat.h#L128

``` cpp
    enum {
        NRows               = M,
        NCols               = N,
        MinDim              = N < M ? N : M,
        MaxDim              = N > M ? N : M,    <---------
        RowSpacing          = RS,
        ColSpacing          = CS,
        NPackedElements     = M * N,
        NActualElements     = (N-1)*CS + (M-1)*RS + 1,
        NActualScalars      = CNT<E>::NActualScalars * NActualElements,
        ImagOffset          = NTraits<ENumber>::ImagOffset,
        RealStrideFactor    = 1, // composite types don't change size when
                                 // cast from complex to real or imaginary
        ArgDepth            = ((int)CNT<E>::ArgDepth < (int)MAX_RESOLVED_DEPTH 
                                ? CNT<E>::ArgDepth + 1 
                                : MAX_RESOLVED_DEPTH),   <--------------
        IsScalar            = 0,
        IsULessScalar       = 0,
        IsNumber            = 0,
        IsStdNumber         = 0,
        IsPrecision         = 0,
        SignInterpretation  = CNT<E>::SignInterpretation
    };
```

So swig has some trouble evaluating `x ? y : z` within enums.

(4) https://github.com/simbody/simbody/blob/master/SimTKcommon/Simulation/include/SimTKcommon/internal/Stage.h#L284

``` cpp
    RealizeCheckFailed(const char* fn, int ln, Stage g, 
                       int subsystemId, const char* subsystemName,
                       const char* fmt ...) : Base(fn,ln)
```

This can be fixed by editing the variable argument syntax by adding a comma: `const char* fmt, ...`.

---

I don't know what to do for (2) and (3). We could insert `#ifdef SWIG`'s into simbody's source code? I don't know if I want to wait for a bug fix in SWIG.

**Comment by sherm1** [comment]
> I don't know what to do for (2) and (3). We could insert #ifdef SWIG's into simbody's source code?

Maybe we could use the constexpr trick there too? (Define some auxiliary constexpr functions that generate the right values and then use those in the enums.) #ifdef SWIG would be fine too if it doesn't cause downstream failures due to undefined enums or whatever.

**Comment by aymanhab** [comment]
Thanks @chrisdembia for getting this going. Having done the exercise in SWIG 2.0x the main problem was really the handling of type-aliases and nested classes, now that nested classes are advertised as supported, things would hopefully be better. Just a heads up since we can get SWIG to to process all the headers and endup with non-working wrapping. I'd #ifdef SWIG out the problem blocks for now to see if there're other bigger problems downstream.

**Comment by chrisdembia** [comment]
Oh okay good point...I was just generating the wrappers, not trying to compile them.

Thanks Sherm for the suggestions. The #ifdef SWIG shouldn't cause downstream failures because it's what's used right now.

**Comment by aymanhab** [comment]
Regarding the #ifdef SWIG, if the code if-def'd out is not used by the generated wrapping code then there should be no problem to anybody. Outside SWIG it should be no-op since SWIG will not be defined. It's just a matter of polluting some headers a little bit and making sure the Doxygen isn't affected adversely.

**Comment by chrisdembia** [comment]
The issue I'm running into now is that there are a bunch of typedefs within classes in SimTK that are private. SWIG tries to use these typedefs but can't. @sherm1, what is the reason for the private typedefs? (for example, `typedef P RealP;` in `UnitVec3`).

**Comment by sherm1** [comment]
> what is the reason for the private typedefs? (for example, typedef P RealP; in UnitVec).

Just a bad idea from long ago, I think. I would prefer now just to use the template parameter `P` ("precision", i.e. float or double) directly and get rid of `RealP` altogether. That would be better than making the typedefs public I think; they are not really suitable for human consumption.

**Comment by aymanhab** [comment]
Thanks Sherm, that's actually what I ended up doing in our version of the files. Would be great to unify.

**Comment by chrisdembia** [comment]
Thanks; that works for UnitVec but I'm not sure what to do for other cases:

The issue mainly arises I think for private typedefs that still appear in the public interface as return types or arguments for public methods. Sounds like such typedefs could reasonably be moved to the public section, since the user sees them anyway (e.g., in doxygen)?

Here's an example (https://github.com/simbody/simbody/blob/master/SimTKcommon/Mechanics/include/SimTKcommon/internal/Rotation.h#L1283):

```cpp
template <class P>
class InverseRotation_ : public Mat<3,3,P>::TransposeType {
typedef P               RealP;
typedef Rotation_<P>    RotationP;
typedef Mat<3,3,P>      Mat33P; // not the base type!
typedef SymMat<3,P>     SymMat33P;
typedef Mat<2,2,P>      Mat22P;
typedef Mat<3,2,P>      Mat32P;
typedef Vec<2,P>        Vec2P;
typedef Vec<3,P>        Vec3P;
typedef Vec<4,P>        Vec4P;
typedef Quaternion_<P>  QuaternionP;
.
.
.
SimTK_SimTKCOMMON_EXPORT SymMat33P 
reexpressSymMat33(const SymMat33P& S_BB) const;

/** We can invert an InverseRotation just by recasting it to a Rotation at 
zero cost. **/
//@{
const RotationP&  invert() const 
{return *reinterpret_cast<const RotationP*>(this);}
RotationP&        updInvert() {return *reinterpret_cast<RotationP*>(this);}
```

In this case it doesn't make sense to remove the typedef, but perhaps we could make the necessary typedefs public?

**Comment by sherm1** [comment]
> Sounds like such typedefs could reasonably be moved to the public section, since the user sees them anyway (e.g., in doxygen)?

I think the right fix is to remove those private typedefs altogether. The templatized types should be used directly. That is already being done in many places, even with those same classes. See for example [here](https://github.com/simbody/simbody/blob/master/SimTKcommon/Mechanics/include/SimTKcommon/internal/Rotation.h#L1467).

If you want to make those changes, please feel free. Otherwise if you point me at the offending classes I'll be glad to get rid of that unnecessary typedef clutter.

**Comment by chrisdembia** [comment]
This isn't done yet; is there another reason you closed this @jenhicks ?

**Comment by jenhicks** [comment]
I must have misread the comments on the Merged PR. Will reopen.

**Comment by chrisdembia** [comment]
There is a PR related to this (#605 ) but it is not merged yet. Thanks for reopening.
