### ISSUE TITLE
Reduce duplication of swig interface files

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#593]
As of now (09/15) the Python and Java bindings use two unrelated swig interface files, it would be good to have them share resources (e.g. common includes when possible) so addition/removal/instantiation of classescan be done in one place, and we can easily support more bindings (e.g. Matlab, Go, C# or whatever). The target language specific parts should stay in separate files to avoid confusion and limit scope of changes.

**Comment by chrisdembia** [comment]
+1
