### ISSUE TITLE
Connector::findAndConnect() should be removed.

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#610]
Currently connector dependencies are found by traversing from a root Component. This is incorrect and leads to potential name collisions (non-unique names)  for Components that have locally unique named subcomponents. If the connectee_name is not a qualified pathname, then it MUST be a subcomponent of this component (the one with the Connector).

**Comment by chrisdembia** [comment]
@klshrinidhi suggested a single `connect()` method with overloads for `Object` and `std::string`. `connect(string)` will do what `findAndConnect()` had done.
