### ISSUE TITLE
User option to reverse a Joint should be eliminated

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#611]
Model is now capable of deciding what topology is best by using the `SimTK::MultibodyGraphMaker` which also takes into consideration closed Loops and other Constraints. Only the Model needs the ability to set this flag. The `reverse` property of  the Joint and its accessors should now be removed.

**Comment by jenhicks** [comment]
Need to remove the property for the joint reverse.

**Comment by jenhicks** [comment]
Add a test and throw an assertion when reading an old model that has a reverse tag.

**Comment by jenhicks** [comment]
OR give a warning

**Comment by jenhicks** [comment]
See discussion in #1424

**Comment by tkuchida** [comment]
Related to #1406

**Comment by jenhicks** [comment]
@tkuchida Will do some initial exploration to see how long this task will take. @aseth1 is ok with making the change now and resolving backward compatibility issues later.

**Comment by tkuchida** [comment]
Fixed by #1567 and #1577
