### ISSUE TITLE
Better organization for test cases

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#614]
As of now some folders e.g. Applications/Analyze/test contain multiple test cases (4) and multiple models (9), and tens of XML, sto files that are used by some combination of these tests. This is problematic because:
- Models are mostly redundant (from distribution) 
- Repository bloat due to duplication of large data files.
- Data files, setup files are potentially entangled. 
  We should clean this up so that test cases are self contained and do not duplicate models or files if using off the shelf ones.

**Comment by chrisdembia** [comment]
+1.

I also agree with your AOI that tests should have their own "workspace"; they should not be executed in the same directory as any other test, to avoid accidentally loading in the wrong resources of the same name, etc. At least I think this was your point in an email. We can address this via some changes to the OpenSimMacros.cmake file.

We can reduce repository bloat using the [OpenSimCopySharedTestFiles](https://github.com/opensim-org/opensim-core/blob/master/cmake/OpenSimMacros.cmake#L147) cmake macro I wrote (though this is only a beginning)

**Comment by aymanhab** [comment]
Perfect, we can start with Applications/Analyze/test as a poster child for this confusion after #546 goes in.
