### ISSUE TITLE
Model migration issue testStaticOptimization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#622]
After merging from master, the test case for testStaticOptimization fails due to the following exception:
SimTK Exception thrown at TransformAxis.cpp:92:
  Internal bug detected: CustomJoint (ground_pelvis) rotation1 axis has no function but has coordinates.
  (Assertion 'coordNames.size() == 0' failed).
  Please file an Issue at https://github.com/simbody/simbody/issues.
  Include the above information and anything else needed to reproduce the problem.

**Comment by chrisdembia** [comment]
Does this imply that travis builds will fail after merging #546?

**Comment by aymanhab** [comment]
Yes @chrisdembia and that's why I haven't merged yet, pending @aseth1 resolution/input.

**Comment by aymanhab** [comment]
Model is subject01.osim under Applications/Analyze/test. Joint/SpatialTransform in question follows (versoin 1.9 model format)
```
		<SpatialTransform name="">
                      <TransformAxis name="rotation1">
                        <function/>
                        <coordinates> pelvis_tilt </coordinates>
                        <axis>       0.00000000       0.00000000       1.00000000 </axis>
                      </TransformAxis>
                      <TransformAxis name="rotation2">
                        <function/>
                        <coordinates> pelvis_list </coordinates>
                        <axis>       1.00000000       0.00000000       0.00000000 </axis>
                      </TransformAxis>
                      <TransformAxis name="rotation3">
                        <function/>
                        <coordinates> pelvis_rotation </coordinates>
                        <axis>       0.00000000       1.00000000       0.00000000 </axis>
                      </TransformAxis>
			<TransformAxis name="translation1">
                        <function/>
                        <coordinates> pelvis_tx </coordinates>
                        <axis>       1.00000000       0.00000000       0.00000000 </axis>
                      </TransformAxis>
                      <TransformAxis name="translation2">
                        <function/>
                        <coordinates> pelvis_ty </coordinates>
                        <is_rotation> false </is_rotation>
			<axis>       0.00000000       1.00000000       0.00000000 </axis>
			</TransformAxis>
			<TransformAxis name="translation3">
                        <function/>
                        <coordinates> pelvis_tz </coordinates>
			<axis>       0.00000000       0.00000000       1.00000000 </axis>
			</TransformAxis>
		</SpatialTransform>

**Comment by aseth1** [comment]
I am not sure how this ever worked without any Functions. We must have assumed a linear function or updateFromXML inserted it. As far as I can tell models version 20302 and onward have a function listed.

**Comment by jenhicks** [comment]
@aymanhab Can we close this issue?

**Comment by aymanhab** [comment]
We can close this if we declare support for version 1.9 and earlier is dropped and that users need to use version 3.3 to upgrade.

**Comment by jenhicks** [comment]
I will close, given that there is another issue regarding support of old version. I believe that is the plan.
