### ISSUE TITLE
How do I upload a document?

### ISSUE THREAD

**Issue by silderam** [opensim-org/opensim-core#656]

**Comment by silderam** [comment]
![Uploading MountStHelens2015_ 007.JPG…]()

**Comment by chrisdembia** [comment]
Hello @silderam! I think you needed to wait a little longer for the image to upload before clicking "Comment"

**Comment by silderam** [comment]
Hello chrisdembia! I thought it had failed to upload, and I am indeed not very patient. 
Its also good to know that things I "close" still show up in the public pages to view! I'm working on figuring out how to upload a file into the same place where you uploaded some a few weeks ago.

**Comment by chrisdembia** [comment]
I uploaded a file a few weeks ago???
