### ISSUE TITLE
MarkerPlacer() having issues with mot file inputs 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#664]
forum thread can be found [here](https://simtk.org/forums/viewtopic.php?f=91&t=5975).

**Comment by chrisdembia** [comment]
I think the issue is here:

> calculated for a single frame

The spline requires at least 5 or so frames of data. Can the user try providing an input static trial that has multiple frames? This is just a guess; I'm not sure this will solve their issue (in the short term).
