### ISSUE TITLE
In Java/MATLAB, when Model.LoadOpenSimPlugin fails to load a proper library, there is no error 

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#669]
@aseth1 ran into this issue.

Relatedly, there should be a better error when XML parsing hits an unrecognized/unregistered type.
Also I think we should move Model.LoadOpenSimPlugin to be a global method (maybe that's not possible in Java?)

**Comment by aseth1** [comment]
:+1: 

And we should make sure that it is documented. All the documentation I could find on loading a plugin library in MATLAB discussed using MATLAB's `loadlibrary()` which requires configuring *mex* with compatible compiler, which is completely unnecessary when OpenSim can load the library.

**Comment by jenhicks** [comment]
Should add a more informative error message. Move load OpenSim plugin method to the OpenSim namespace.

**Comment by aymanhab** [comment]
There's no global namespace, we can make a class call it OpenSimUtilities for example and use it to invoke the load plugin. We should definitely improve the documentation and warn against using MATLAB's native loadLibrary which follows completely different workflow and doesn't work with our libraries.

**Comment by chrisdembia** [comment]
At least in python, we could just have a free function. Are you saying this wouldn't be possible for Java?

**Comment by aymanhab** [comment]
There's nothing global in Java, you can define a public static method in a class and it becomes available everywhere but the call goes thru the class qualification. I suggested OpenSimUtilities for such a class but others would do. Class names  traditionally start with Uppercase.

**Comment by chrisdembia** [comment]
Okay. For the sake of a consistent interface in different languages, then I don't think we should use `opensim.loadPlugin()` in Python.

**Comment by jenhicks** [comment]
@chrisdembia will verify if this is still an issue
