### ISSUE TITLE
Formatting of Class Diagrams in Doxygen using **dot**

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#673]
The introduction of another class (`TwoFrameLinker`, #649) into the `Force` hierarchy caused resulting derived Forces (specifically `BushingForce`'s) to disappear from Force class diagrams. This was not due to confusion interpreting the mixin (e.g. `WeldConstraint` appears to derive from `TwoFrameLinker` just fine) but how diagrams are auto formatted so the depth of the hierarchy in the case of the Forces was truncated.

Using Doxygen with  **dot** installed, which is part of the [*graphviz*](http://www.graphviz.org) utilities allows us to have more control on how the diagrams appear and I think they look better too.

For example one can get a complete view of Forces in OpenSim:
![classopensim_1_1force__inherit__graph](https://cloud.githubusercontent.com/assets/6494122/10403283/601a4a84-6e7f-11e5-9e06-719bd1151c32.png)

Or something much simpler from the `BushingForce` perspective:

![classopensim_1_1bushingforce__inherit__graph_no_template_relation](https://cloud.githubusercontent.com/assets/6494122/10408217/1126b4d0-6eac-11e5-9dee-3e40311958a7.png)

I propose using **dot** to render OpenSim's diagrams in Doxygen. We can discuss pros/cons and implementation here.

**Comment by chrisdembia** [comment]
I think we agreed on this already but `dot` should be optional, but we should use dot for whatever gets uploaded to the internet.

Down the line, I think our online doxygen should be uploaded through travis/appveyor, so that means getting dot on travis/appveyor. This is surely easy to do (`apt-get graphviz`).

**Comment by sherm1** [comment]
> I think we agreed on this already but dot should be optional, but we should use dot for whatever gets uploaded to the internet.

I think everything will still work without dot but every developer should install dot so that we can check in our own builds that doxygen is formatting things correctly.

**Comment by chrisdembia** [comment]
I like that.

I think we should set up cmake to search for dot so we can give a warning/message to people telling them that they might want to get dot.

**Comment by tkuchida** [comment]
> give a warning/message to people telling them that they might want to get dot

Have you installed dot? I think you have not. We like it a lot, so give it a shot!

**Comment by chrisdembia** [comment]
perfect!

**Comment by sherm1** [comment]
:smile_cat: Dr. ~~Uchida~~ Seuss!
