### ISSUE TITLE
Revisit Appearance class

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#674]
In discussion around PR #616 there were some open questions regarding how the Appearance class will be used and or potentially expanded in the future. Please refer to the discussion there for a starting point. In general Appearance sits on the interface between API and GUI and we'd like API users to have some control over how their components get displayed by default.

**Comment by jenhicks** [comment]
@aymanhab Should we leave this open? If so, what are the specific issues/tasks?

**Comment by aymanhab** [comment]
Practically will need to address these issues before 4.0 but mechanisms/solutions have evolved since the issue was opened, I'd be ok with closing.
