### ISSUE TITLE
Exceptions in OpenSim

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#678]
This issue is to track/discuss the improvements to exception throwing/handling in OpenSim. Discussions about this started on PR #628, which has taken few steps:
- Using an exception hierarchy to throw specific exceptions and not throw OpenSim::Exception.  
  Use -- To allow handling(`catch`) these exceptions if desired.
- Exceptions carry more information -- file-name, line-number, function-name, specific error message with  some details including numbers.  
  Use -- When uncaught, these exceptions terminate the program with the error message that can help debug the problem to some extent.
- Functions document exceptions that they think the caller should know.  
  Use -- Tied to first bullet above, documentation is the way to let callers (of functions throwing exceptions) know about the exceptions thrown by the function so they can choose to (or not to) handle them.

Problems to be tackled include but not limited to:
- The new code introduced by PR #628 uses specific exceptions but existing code uses OpenSim::Exception directly. 
- Error messages from new code include information mentioned above while the existing code (more often than not) does not.
- Error messages from new code are formatted while those from existing code are not.
- Changes have to be introduced to existing code over time by starting with classes that will benefit the most.  
  [Chris's comment below] See #337.
- [Ayman's comment below] It is also important to understand how Exceptions are propagated through the scripting layer since Native (C++) exceptions that are not caught will cause the Python interpreter and/or Matlab & Java to crash. This's handled now by a blanket try/catch in the swig interface file that catches std::exception and maps it to an exception on the scripting side. This should at least continue to work or gets improved for more detailed exceptions where appropriate.  
  [Chris' comment below] Oh good point. For python, here's how we handle exceptions: https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/swig/pyWrapOpenSim.i#L41. You can also see just below that how we'd prefer to handle exceptions, but that prohibitively increases the size of the wrapper code.
- [Sherm added] What formatting flexibility is required? Should formatting be different for end users than for developers, or in Release vs. Debug builds? What about if the messages are intended to go into a logging system? If we collect a hierarchy of messages through catch and re-throw, should that be reflected in formatting, with indentation or some other method? I think derived classes should provide at most markup information (e.g. paragraph separation, end user vs debug info, level-of-detail), with formatting decisions made separately.

**Comment by chrisdembia** [comment]
:+1:

**Comment by chrisdembia** [comment]
> Changes have to be introduced to existing code over time by starting with classes that will benefit the most.

See #337

**Comment by sherm1** [comment]
:+1: Thanks, Shrinidhi!

**Comment by aymanhab** [comment]
It is also important to understand how Exceptions are propagated through the scripting layer since Native (C++) exceptions that are not caught will cause the Python interpreter and/or Matlab & Java to crash. This's handled now by a blanket try/catch in the swig interface file that catches std::exception and maps it to an exception on the scripting side. This should at least continue to work or gets improved for more detailed exceptions where appropriate.

**Comment by chrisdembia** [comment]
Oh good point. For python, here's how we handle exceptions: https://github.com/opensim-org/opensim-core/blob/master/Bindings/Python/swig/pyWrapOpenSim.i#L41. You can also see just below that how we'd *prefer* to handle exceptions, but that prohibitively increases the size of the wrapper code.

**Comment by chrisdembia** [comment]
In #854, @klshrinidhi mentioned:

>  It will be good to create a hierarchy under Exception to represent various kinds of invalid model failures.

This is related to the StatesTrajectory::IncompatibleModel exception.

**Comment by tkuchida** [comment]
Assigning a unique number to each error message might also be useful when searching for similar issues on [the Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?f=91).
