### ISSUE TITLE
Doxygen -->> DoxyPress ???

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#679]
DoxyPress is a fork of Doxygen and claims to be built for C++11. 
Maybe worth looking at it -- http://www.copperspice.com/docs/doxypress/index.html

**Comment by chrisdembia** [comment]
I saw this a while ago, but felt like it didn't make sense to use yet. You mean it has better support for documenting C++11 constructs? There was a discussion on reddit criticizing the project for needlessly forking a project and changing its input (the input is xml instead of the current simpler format). It would be much better for doxygen to provide better C++11 support.

**Comment by chrisdembia** [comment]
sphinx seems to be getting pretty popular for general documentation (even though it was initially for python).

**Comment by klshrinidhi** [comment]
I am not sure of anything actually. 
They claim to have improved Doxygen source code significantly and improved C++ support to catch up to latest standards. One plus side of DoxyPress is that it does not need anything from our side. It is compatible with Doxygen completely (or they say it is). Sphinx may need a change to markdown/tags in the comment. It is hard to keep up with developments in C++. Not sure which one will support and keep doing it as more C++ standards come out.

**Comment by sherm1** [comment]
Support for DoxyPress would be a worry, I think. This appears to be a side project for the two developers at copperspice who are mostly working on a monstrous fork of Qt. Doxygen has a long history of upgrades and bug fixes and a huge user base. 

Are there particular features you want doxygen support for that are currently missing? I think the fastest way to get those would probably be to ask Dimitri (primary doxygen maintainer) to put them in. He has been very responsive to our bug reports and feature requests. He monitors stackoverflow doxygen questions also and is very helpful.

**Comment by agserm** [comment]
We would like to thank everyone for their interest in DoxyPress.  We have uploaded the source for DoxyPress and DoxyPressApp to github (https://github.com/copperspice/doxypress).

I would like to confirm that DoxyPress is indeed compatible with source code commented using the Doxygen syntax. You will not need to make any changes although we have added a few more tags to the project file you may wish to leverage.

We are currently working on enhancements to DoxyPress which will use libclang to parse C and C++. This will provide full support for C++11/14/17 parsing and allow us to keep up with the C++ standard with minimal changes.

Ansel Sermersheim
CopperSpice and DoxyPress project cofounder
