### ISSUE TITLE
Pop-up for updating an old model

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#684]
When opening an old Model in the latest GUI, a new window my be opened that has the function of (i) alerting the User that OpenSim is making changes to the Model (ii) Gives the User the choice of things to update. 

A use case could be for updating a Models joint limits to Rigid Contact Joint-Stops. The User would have the option of upgrading, and we could link to some information which explains the ramifications.

Few people read the message window and so this would provide an alert that the Model is being changed.

**Comment by aymanhab** [comment]
Good idea @jimmyDunne but:
1. In the past there were usually no options to not upgrade (other than telling the user to go use older version).
2. The dialog intervention/paradigm works fine in the GUI but not in the API or Matlab/Scripting where a user has no chance to give feedback.
Just a couple things to keep in mind, though as of version 4.0 plans we may have options to either keep or migrate Contact, enforce Joint Stops, ... etc.

**Comment by sherm1** [comment]
This could be an argument for a separate model-conversion tool. The API could then refuse to run on old models until after they have been converted.

**Comment by jimmyDunne** [comment]
It should be very obvious to Users that their model is getting 'updated' (changed). If the GUI is going to be able to work on Mac and Linux then the API refusing old models shouldn't be an issue. The User could just open the model in the GUI, select the things they (don't) want changed, and then save it. This process would only have to be done once.
