### ISSUE TITLE
Can loadLibrary("osimJavaJNI") use more information to avoid the need for setting PATH / DYLD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#701]
See [here](https://github.com/opensim-org/opensim-core/blob/master/Bindings/Java/swig/javaWrapOpenSim.i#L267).

**Comment by aymanhab** [comment]
Not sure what you mean by that @chrisdembia Embedding a hard coded absolute path in compiled code seems less flexible. Using environment variables is usually not recommended (vs. System properties) but I'm open to suggestions now that we can run on non-windows machines..

**Comment by chrisdembia** [comment]
Perhaps a hard-coded relative path that is platform-dependent would work. It could be part of a search; PATH would override the setting. We could use similar logic as that used to find simbody-visualizer in a platform-specific way.

**Comment by aymanhab** [comment]
@chrisdembia is the goal to avoid setting PATH, DYLD_LIBRARY_PATH or both and on what platform(s)? The reason I'm asking is that this's probably not the only scenario where we need to set these PATHs, so some big picture context helps. In general the fewer things we need to set the better, but I'd prefer a PATH that we can view/check/troubleshoot over one hidden in the code unless bullet proof.

**Comment by chrisdembia** [comment]
On Ubuntu and OSX, we will almost certainly be able to avoid having users set *any* environment variables (perhaps except for PATH to access command line executables). I'm not sure about Windows. We can achieve this on OSX by using RPATH, and on Ubuntu by installing into system-wide directories.

On Windows, it's somewhat common for installers to modify the system/user PATH globally, but this is not common on OSX, and is only common on Ubuntu for non-GUI applications.

The ability to troubleshoot is a good point that I had not thought of...I think hardcoding a relative path might reduce confusion if done properly, since right now, if someone tries to open the GUI but has set the PATH to refer to different libraries (say, open 3.3 GUI with PATH set to 3.2 libraries), you might get confusing error messages.

I don't have an exactly plan yet; perhaps it will require a few iterations to get it right.

AFAIK, these are the reasons for setting environment variables (PATH, (DY)LD_LIBRARY_PATH):

* **Accessing the command line executables from a terminal or cmd window.**
  * _Ubuntu_: executables are on the PATH since they will be in /usr/bin or /usr/local/bin. The libraries that these execuables need are also already locatable since they will be in /usr/lib or /usr/local/lib.
  * _OSX_: executables will be in either `/Applications/OpenSim 4.0/Contents/MacOS` or `/Applications/OpenSim 4.0/Contents/Resources/bin`, neither of which are on the path. If we use an installer, we can add a symlink from `/usr/local/bin`, etc. If we do not use an installer (and users simply copy OpenSim into the Applications dir.), then users would need to set PATH on their own. (I'm still thinking about this). As for how the executables find the libraries, the executables will be hard-coded with relative paths to the libraries; this would be bullet proof.
  * _Windows_: users must set the PATH variable to access the command-line executables from any directory; I don't think there is a way around this.
* **GUI**
  * _Ubuntu_: opensimModelJNI will load osimJavaJNI, which will be in `/usr/local`, and so will the libraries it needs. Don't need to set any environment variables.
  * _OSX_: opensimModelJNI will need a hard-coded relative path to find osimJavaJNI. However, osimJavaJNI will know that its dependencies are adjacent to it.
  * _Windows_: opensimModelJNI will need a hard-coded relative path to find osimJavaJNI. Does windows look for dependency dlls in the same directory? If so, we don't need to set PATH. If not, then we do. Or, perhaps, we can hard-code `java.library.path` in `opensimModelJNI` to find the other dlls.
* **Access to API through MATLAB** (`prefdir` is a MATLAB command to find the preferences directory; usually something like `~/.matlab/R2015a/`)
  * _Ubuntu_: I don't know where the jars would live but we edit `prefdir/javaclasspath.txt` to point to the bindings jar file. We don't need to edit `prefdir/javalibrarypath.txt` or `LD_LIBRARY_PATH` since the libraries, including osimJavaJNI, will be in `/usr/lib` or `/usr/local/lib`.
  * _OSX_: We edit `prefdir/javaclasspath.txt` to point to the bindings jar file. We don't need to edit `prefdir/javalibrarypath.txt` because we will know the relative location of `libosimJavaJNI.dylib`, and this will be hardcoded into the `loadLibrary` command. We don't need to set MATLAB's path or `DYLD_LIBRARY_PATH` because osimJavaJNI will know that its dependencies are adjacent to it.
  * _Windows_: We edit `prefdir/javaclasspath.txt` but not `prefdir/javalibrarypath.txt` (same reason as above), However, osimJavaJNI won't know where to find its dependencies, so we must set MATLAB's path. To avoid this, we could statically link OpenSim API libraries into osimJavaJNI.
* **Access to API throuh Python**
  * _Ubuntu_: nothing to do. swig finds `_opensim.so` within the python package, which can find the other libraries are in `/usr/lib`, etc.
  * _OSX_: `_opensim.so` has the location of the OpenSim libraries hard-coded. This may only work if the user installs OpenSim into the default location; if they put OpenSim elsewhere, they'll need to set DYLD_LIBRARY_PATH, but that's fine since that's the purpose of having the environment variable. Or, we could statically link the OpenSim libraries into `_opensim.so`.
  * _Windows_: We must either set PATH or statically link.

**Comment by chrisdembia** [comment]
This probably isn't useful: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx

**Comment by jenhicks** [comment]
For 4.0, release should not use environment variable on OSX.

**Comment by aymanhab** [comment]
Answer is yes! closing, other issues address specifics.
