### ISSUE TITLE
Handling OpenSim dependencies for building from sources.

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#702]
As OpenSim grows and uses more libraries (like BTK is being used now; catch/gtest, glog etc hopefully coming soon), handling dependencies is something we have to address. @chrisdembia and I have talked about this for a while.

For the purpose of this issue, OpenSim community is classified into two groups:

1. People who **do not edit** OpenSim sources. This set includes people who use OpenSim from Python/Matlab/C++ to write their own code but they don't intend to edit OpenSim code itself. This also includes people who intend to write plugins for OpenSim. [Estimate = 95% of OpenSim community.]
For this group, OpenSim will release binaries for Windows, Mac OS X and Linux.

2. People who **do edit** OpenSim sources. This set is mainly *OpenSim developers* -- people who intend to edit (and maybe contribute to) OpenSim-core. This set also includes some unfortunate people with platforms we don't have binaries for. We can encourage these people to either:
 * host binaries if/when they have successful builds and submit just the *links* to us for hosting on OpenSim website.
 * submit the binaries to us for hosting on OpenSim website.
  
 These people will be compiling OpenSim sources. This issue is mostly about this group.
For this group, we could use CMake *super-build* to resolve dependencies. The advantages:
 * We control where to download the dependency from.
 * We control which version of the dependency to use.
 * We control what build parameters to use when building the dependency.
 * Potentially reduce number of build related questions and therefore our time in answering them.

 Here is how it could work:
 * Building OpenSim will be two-step procedure, which can be wrapped into one step for most users in this group.
 * Step one is -- *DownloadAndBuildDependencies*. This is handled by CMake *super-build* using the Cmake module named *ExtenalProject*. For advanced users, this step can be configured to skip/include certain dependencies.
 * Step two is -- *BuildOpenSim*. At this point dependencies are already in place and it is just about passing correct paths to the dependencies for OpenSim build.

 In step one, dependencies are downloaded. We could host binaries for dependencies for most (if not all) platforms. The download step will check if binaries are available and proceed to compiling sources only if no pre-built binaries are available. For making the dependency sources available, the alternatives are:
 * Copy the sources from the dependency repo into Opensim. 
   *  :+1: No risk of losing access to sources. Links can die.
    *  :-1: We have to re-copy if we want to use newer versions of the dependency.
    * :-1: Dependencies get downloaded with OpenSim whether they are needed or not.
    * :-1: May not be a good idea for larger dependencies with lots of source files as it may cause bloat.  

 * Download the sources directly from dependency repo.
   * :-1: Links to the repos can die. 
    * :+1: Just update the commit-id or version number to checkout newer versions of the dependency.
    * :+1: Download a dependency only if needed.
    * :+1: Great for large dependencies with lots of source files.

 * Hybrid solution -- use links to original repo if reliable (like GitHub) and fork the repo into GitHub if link to original repo is unreliable. Try hard not to fork.
   * :+1: We make sure links to repos don't die using careful decision making on a case by case basis.

Any more pros/cons you see with above ?
Any more ideas ?

**Comment by jimmyDunne** [comment]
Awesome Summary!  

> Just update the commit-id or version number to checkout newer versions of the dependency.

Newer versions may require upkeep by us or introduce unforeseen bugs. Wouldn't we want to make sure a new version works or is stable before we checkout?

Just my two cents. Otherwise it all sounds sweet!

**Comment by sherm1** [comment]
Well said, Shrinidhi! 

Do you have in mind that we would use the longer procedure for our CI builds? That would ensure we spot problems quickly but would add build time. If not, what are your thoughts for CI?

**Comment by klshrinidhi** [comment]
@jimmyDunne 
Yes. We would update the commit-id only after testing the new version of the dependency.

**Comment by klshrinidhi** [comment]
@sherm1 
That is a good point. How about hosting pre-built binaries for most (if not all) dependencies for all platforms ? This could be used both by CI and manual builds alike. I will update the steps to include this.

**Comment by chrisdembia** [comment]
What about a user (non-developer, but has some C++ knowledge) who wants to use an older version of OpenSim on a newer machine for which the original binary distribution is broken?

**Comment by chrisdembia** [comment]
Thanks for the awesome summary. I think an automated procedure for downloading and building our dependencies is useful *no matter what* solution we choose. If we choose to copy binaries of BTK, etc into OpenSim, the automated script is *still* useful to developers when we need to update the version of BTK that we have copied into OpenSim. Same holds for if we coy *sources* of BTK, etc into our own repos.

**Comment by chrisdembia** [comment]
> We can encourage these people to either:
> 
>     host binaries if/when they have successful builds and submit just the links to us for hosting on OpenSim website.
>     submit the binaries to us for hosting on OpenSim website.

I don't fully understand this part. Could you explain?

**Comment by klshrinidhi** [comment]
@chrisdembia 
> What about a user (non-developer, but has some C++ knowledge) who wants to use an older version of OpenSim on a newer machine for which the original binary distribution is broken?

I think this person would belong to group B -- he/she will have to build the sources. The dependency download step will realize that binaries are not available for this platform and so will download the sources, checkout the right version of dependency and compile them. See any problem ?

>> We can encourage these people to either:
>> 
>>     host binaries if/when they have successful builds and submit just the links to us for hosting on OpenSim website.
>>     submit the binaries to us for hosting on OpenSim website.
>
>I don't fully understand this part. Could you explain?

This is for people who wish there were OpenSim binaries available for their platform but don't see them on the OpenSim website, which means we didn't build OpenSim for their platform. These people will have to build OpenSim anyway. Once they have done so successfully, they can send us the binaries so we can host them on OpenSim website (with an acknowledgement & caveat of-course).

**Comment by chrisdembia** [comment]
Okay thanks for explaining.

**Comment by chrisdembia** [comment]
Another use case to consider: people installing OpenSim on a (UNIX) computing cluster (e.g., @carmichaelong). Perhaps if clusters start to support containers, we can provide an OpenSim container?

**Comment by chrisdembia** [comment]
http://mesonbuild.com/

**Comment by sherm1** [comment]
Meson looks very promising!

**Comment by aymanhab** [comment]
Great summary @klshrinidhi What I found missing is the implication on the distribution/installation. Having seen apt-get happy environment(s) leading to impossible to distribute products that basically required users to build new on every machine is something we should be aware of and to avoid for our user base. 

Also although a general policy is useful, in many cases the decision will be on a case-by-case basis. Examples: we absorbed tinyxml, and ipopt but were using prebiuilt xerces libraries, and continue to use prebuilt vtk in the GUI, CFSQP was a different approach due to license. Would be good to discuss these use-cases and learn what worked and what didn't.

**Comment by klshrinidhi** [comment]
@aymanhab 
I agree. I think the hybrid solution I mention is a good idea -- in cases where the links can be unreliable (like ipopt), forking the dependency into a separate project on GitHub under OpenSim organization would be a good idea. I think dependencies should not be part of our version controlled repository. I think we should keep the dependency sources separate and let CMake handle the build.

In our next meeting, we could go over all the dependencies and make a decision for each one. I can then implement the *super-build* in CMake.

**Comment by klshrinidhi** [comment]
From today's meeting, the group's conclusion is that *super-build* is a good idea. Here is the summary of what else was discussed:

|||
|-----------|-----------|
Feature | Ability to create a compressed file containing all of the sources -- OpenSim & its entire dependency graph.
Why ? | To make standalone versions of the sources that can be distributed with every OpenSim release. This will allow users to build older versions of OpenSim without dependency issues.
Who will use it ? | Just us. Once every release.

Let me know if I am missing anything.

**Comment by sherm1** [comment]
Good summary, Shrinidhi -- thanks.

**Comment by chrisdembia** [comment]
> Who will use it ? 	Just us. Once every release.

Ideally, travis/appveyor will do the source zipping for us whenever we make a release (upon release, you can have travis/appveyor run additional commands). Sporadically, we'll have to test the source zipping on local machines to ensure travis will succeed at it.

**Comment by chrisdembia** [comment]
@klshrinidhi can you look into Hunter? https://github.com/ruslo/hunter/ It seems to be very similar to what you've done, using ExternalProject.

**Comment by chrisdembia** [comment]
@klshrinidhi do you think this can be closed?

**Comment by klshrinidhi** [comment]
Yes. Closing now.
