### ISSUE TITLE
Simplify Matlab import call

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#704]
Matlab import is 

```
import org.opensim.modeling.*
```

While in python it's

```
import opensim
```

Any chance we could make the Matlab import call the same as Python?

**Comment by chrisdembia** [comment]
I would prefer this as well. @aymanhab how much would the GUI repo need to be restructured if `org-opensim-modeling.jar` became `opensim.jar`?

**Comment by aymanhab** [comment]
@chrisdembia and @jimmyDunne I don't think the name of the jar is the problem, we can definitely rename it to opensim.jar with very little side-effects. The import however is for a java package not a jar file. Java packages typically have these layout/names (general.specific.more-specific) that you almost never find one package that doesn't start with com, org, or java to make sure the name/spaces don't collide. If the visualizaion is self-contained we'll probably have org.opensim.visualization at some point. Hope this explains.

**Comment by jimmyDunne** [comment]
Thanks for clarifying :)

**Comment by chrisdembia** [comment]
Hmm... would `org.opensim` be possible (the GUI could use a separate layout if necessary)? If we split into more packages, it would be nice if the split matched the different C++ library names, etc.

**Comment by aymanhab** [comment]
@chrisdembia possible for what specifically? The GUI and Matlab both use the same jar file and so the same package name. I agree ideally we have meaningfully different packages that map to meaningful C++ libraries that can be swig wrapped and used separately but that's not he case now. We should start at Simbody but that never got off the ground.

**Comment by chrisdembia** [comment]
> @chrisdembia possible for what specifically?

Would it be possible for `import org.opensim.*;` to achieve the same thing as `import org.opensim.modeling.*;` achieves today?

If we separated the swig wrapping into common, simulation, etc., then if you did `import org.opensim.*;`, you'd only be able to access the classes with `simulation.Model`, etc., right?

Python has a `__init__.py` that gives you a level of indirection between the package structure that others see and what the true package structure is. So even if we have `opensim.common`, opensim.modeling`, etc. for python, the user would still see a flat list of classes when doing `import opensim`. Is there a similar mechanism for "remapping" that we could use with Java, or just MATLAB?

**Comment by chrisdembia** [comment]
> We should start at Simbody but that never got off the ground.

I know, but I think we are still planning on doing it, right? Previously, I had thought the first step in this process would be to remove the SWIGSimTK headers, but now I think that can wait until after the modularization. I may start looking at this again soon.

**Comment by aymanhab** [comment]
Well, yes eventually, if not on the team schedule (which is pretty full already) I'm assuming nobody is working on it but you're absolutely welcome to start on it and I'd by very happy to help you. You'll have to deal with the same issues that plagued the removal of SWIGSimTK headers branch though which is that you may get a wrapping littered with unusable classes/interfaces but you have to start somewhere..

Good point about the "stack-like" behavior of libraries in C++, I'm hoping we'll not need a separate import for simbody if we separate it, but will definitely need to test it to make sure we're not making things more complicated for ourselves and our users.
