### ISSUE TITLE
testComponents failing regularly on Appveyor, related to "memory leaks"

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#708]
I think this is related to @aseth1's recent changes to how the memory is checked (`instanceSize`, etc.).

**Comment by klshrinidhi** [comment]
I am not able to reproduce this problem on Windows 10. All the tests are passing on `master`.

**Comment by chrisdembia** [comment]
Thanks for checking. Any suggestions?

**Comment by tkuchida** [comment]
testComponents failed on 64-bit build in #921 (see output [here](https://ci.appveyor.com/project/opensim-org/opensim-core/build/3163/job/6nvjy0jertwtea8q#L624)).

**Comment by klshrinidhi** [comment]
Thanks.
I will build the branch of #921 locally and get back.

**Comment by aseth1** [comment]
I am almost certain it will not be reproducible. `getCurrentRSS()` seems to intermittently and randomly yield garbage (leak is 1208695552165.990234%) .  I haven't been able to get it to fail locally on Windows 7 or 10 since this was reported.

**Comment by klshrinidhi** [comment]
I could not reproduce the problem on Windows 10, again.

**Comment by chrisdembia** [comment]
Try running it like 50 times.

**Comment by chrisdembia** [comment]
(I have never tried to run testComponents on Windows, so I can't say anything about its reproducibility)

**Comment by tkuchida** [comment]
> Try running it like 50 times.

If the problem is infrequent and benign, perhaps the test case should detect suspicious `getCurrentRSS()` behavior and re-run if the reported leak is unreasonably large.

**Comment by aseth1** [comment]
> If the problem is infrequent and benign, perhaps the test case should detect suspicious getCurrentRSS() behavior and re-run if the reported leak is unreasonably large

:+1:

**Comment by tkuchida** [comment]
Fixed by #1020. Subtraction of unsigned ints was wrapping through zero (heap space was being freed automatically, causing the memory footprint to _decrease_ during the test).
