### ISSUE TITLE
The naming convention for the inputs/outputs of the components

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#714]
The access of the inputs and outputs requires the knowledge of the names that the developer of the component has defined in the implementation. The user of the component does not need to know the them explicitly. I do suggest that the developer of the component should define a static qualifier that can be used to access them in a convenient way, so this can be transparent to the user of the component. For example, StepResponse::INPUT, Muscle::INPUT_EXCIATION, Muscle::OUTPUT_FORCE, DummyComponent::INPUT_X, DummyComponent::INPUT_Y.

The following is a quote from @chrisdembia suggestion:

"For this I suggest doing the same thing as with properties: using a macro to generate functions with the names of the inputs/outputs embedded."

**Comment by sherm1** [comment]
If you have to know the names of the static symbols, why is that an improvement over having to know the names as strings? Either way the names should be part of the Component's documented interface, and using strings requires less infrastructure. Also the strings are necessary for introspection, for example if the GUI wants to make a list of a component's inputs and outputs, so we can't get rid of them.

I do agree with @chrisdembia that we would have to enforce this discipline with macros, but I don't yet see why that would be a good thing; macros are usually a last resort for the desperate.

**Comment by mitkof6** [comment]
> If you have to know the names of the static symbols, why is that an improvement over having to know the names as strings?

It is just a suggestion. When you connect two components A and B you have to know the names of their inputs/outputs. It seems more convenient if the components are used apart from the developer e.g. B.getInput(B::INPUT_FORCER).connect(A.getOutput(A::OUTPUT_FORCE)) instead of B.getInput("input_a").connect(A.getOutput("input_dasda")).

**Comment by chrisdembia** [comment]
@mitkof6, it seems you are looking for the benefits of enums over strings?

**Comment by mitkof6** [comment]
> it seems you are looking for the benefits of enums over strings?

Yes probably.

Also, I was thinking that it would be nice if we connect the components by operators. Something like:

A >> B or A << B. 

And based on their internal names to match and connect the components automatically. And if this is impossible to have the connect method.

**Comment by chrisdembia** [comment]
> Also, I was thinking that it would be nice if we connect the components by operators.

I suggested this in https://github.com/opensim-org/opensim-core/issues/508.

**Comment by jenhicks** [comment]
Closing given age, but feel free to re-open if there are high priority issues.
