### ISSUE TITLE
Getting rid of the need for __declspec(dllexport) macro OSIMCOMMON_API

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#728]
I had not realized until recently(today actually) that none of the classes I have added to OpenSim are available in the DLL library created on Windows. This is because I forgot to *adorn* the classes using the macro `OSIMCOMMON_API`. This macro enables MSVC specific extension attribute `__declspec(dllexport)` to export symbols when creating DLL.

From CMake 3.4 and up, it is possible to set a default of *export all symbols* when creating a DLL using the CMake variable [CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.4/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html) eliminating the need for explicitly exporting symbols/names on Windows. Using this variable, we can eliminate the need for the macro OSIMCOMMON_API.

See this article for a details: http://www.kitware.com/blog/home/post/939

:+1: Setting the default for the CMake variable allows to forget about this macro and write platform independent code.
:-1: We will have to require users to have CMake 3.4 or up. Since we require VS2015 for OpenSim 4.0, this may not be too much to ask.

Please let me know your thoughts.

**Comment by sherm1** [comment]
I would definitely try this for a new port to Windows to avoid having to modify the source code. But there may be some drawbacks:
- It may take a substantial amount of time for CMake to go through all the `.obj` files to extract the symbols, and our build times are already pushing the limits of our CI vendors. (That was mentioned in the blog post above.)
- As I recall, there is a run time performance cost if Visual Studio doesn't know that symbols are being imported. I don't know if that is still true in VS2015. The current scheme marks DLL classes `__declspec(import)` when *using* the OpenSim headers as opposed to when building the libraries. The new CMake scheme handles export properly but doesn't deal with import. 
- DLL data still requires explicit macros. I'm not sure whether OpenSim has any; Simbody does.

For now I think it would be easier and safer just to add the missing macros.

**Comment by klshrinidhi** [comment]
@sherm1 
It looks like except for global data symbols, the `OSIMCOMMON_API` macro may not be needed. So the macro is not completely eliminated but its need can be reduced.

> It may take a substantial amount of time for CMake to go through all the `.obj` files to extract the symbols, and our build times are already pushing the limits of our CI vendors. (That was mentioned in the blog post above.)

I would like to see how much extra time are we actually looking at. Because gcc & clang automatically export all symbols unless stated otherwise by programmer, it would be good to get *effectively* same behavior from MSVC through this workaround.

> As I recall, there is a run time performance cost if Visual Studio doesn't know that symbols are being imported. I don't know if that is still true in VS2015. The current scheme marks DLL classes `__declspec(import)` when *using* the OpenSim headers as opposed to when building the libraries. The new CMake scheme handles export properly but doesn't deal with import. 

CMake documentation [here](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) says `__declspec(dllimport)` is required for global data. Everything else will be automatically imported.

> DLL data still requires explicit macros. I'm not sure whether OpenSim has any; Simbody does.

Yes. It looks like the `__declspec` attribute is required for global DLL data. Because global data is not as common as classes and functions, I think it will still be an improvement.

Existing code *does not* need to change if we use CMake to handle exports for DLL. New code can use the macro only for data symbols.

**Comment by sherm1** [comment]
@klshrinidhi, you misunderstood my comment:
> As I recall, there is a run time performance cost if Visual Studio doesn't know that symbols are being imported.

This is not a functionality issue; it is a code generation issue. The code generated with `__declspec(dllimport)` avoids one level of indirection required if the compiler doesn't know the symbol comes from a dll, according to Microsoft [here](https://msdn.microsoft.com/en-us/library/aa271769(v=vs.60).aspx) and [this 2005 blog post](http://blogs.msdn.com/b/russellk/archive/2005/03/20/399465.aspx). Here is a quote from the Microsoft page:

>You do not need to use __declspec(dllimport) for your code to compile correctly, but doing so allows the compiler to generate better code. The compiler is able to generate better code because it knows for sure whether a function exists in a DLL or not, so the compiler can produce code that skips a level of indirection that would normally be present in a function call that crossed a DLL boundary. However, you must use __declspec(dllimport) in order to import variables used in a DLL.

These are both old sources and it could be that they have figured out how to generate good code in VS2015 without dllimport. However, I couldn't find anything that said so. It might be best to try some experiments and look at the generated code done either way.

**Comment by sherm1** [comment]
Here is the [documentation on this topic](https://msdn.microsoft.com/en-us/library/zw3za17w.aspx) for VS 2015. It explains the difference in code generation with and without `__declspec(dllimport)` for function calls. Apparently nothing has changed.

**Comment by klshrinidhi** [comment]
@sherm1 
I have been referring to documentation [here](https://msdn.microsoft.com/en-us/library/3y1sfaz2(v=vs.140).aspx). It does not explicitly say there is a performance hit for not using dllimport. It does mention briefly about a *thunk*. Maybe they are not consistent in their documentation. Also they don't say anything about importing classes, which make most of our exports/imports.

CMake documentation says it does import symbols automatically but does not say if is equivalent to `__declspec(dllimport)` (it is probably not).

 
* `__declspec(dllexport)` is required in order make symbols available in a DLL.  This can be done through CMake variable without using the macro. Classes and functions we write need not use the macro to export.
* `__declspec(dllimport)` is optional. The headers we expose to clients or for internal use across DLLs will benefit from this.

My understanding now is that with the CMake 3.4 variable, the macro `OSIMCOMMON_API` becomes *optional* and is only for possible performance benefit. Whether the macro will benefit imported classes is not clear.

**Comment by chrisdembia** [comment]
If possible, it would be nice if the CMake version we use is available in Ubuntu's package manager for the latest LTS release. I think we are already violating that rule, though.

**Comment by chrisdembia** [comment]
OOPS sorry, I forgot that we require different versions of CMake for MSVC versus other generators. We can very easily require CMake 3.4 for MSVC (since it's natural to get the latest CMake on Windows) and a different lower version for other generators. Though I don't know if the importing/exporting is specific to MSVC or to Windows (i.e., what about mingw?).
