### ISSUE TITLE
Component::getStateVariableNames() returns empty Array if initSystem() hasn't been called.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#729]
Either `getStateVariableNames()` should throw an exception if `!hasSystem()`, or the requirement on the system should be removed. I think @aseth1 is planning the latter solution.

**Comment by sherm1** [comment]
I would think state variable names are part of the Model and shouldn't require a System.

**Comment by chrisdembia** [comment]
I might have filed this bug prematurely...I'm looking into it.

**Comment by chrisdembia** [comment]
Okay the bug does exist.

**Comment by chrisdembia** [comment]
`getStateVariableValue()` also doesn't behave in a reasoanble way when `initSystem()` has not been called. The exception I get says that the state name I specified is not a state in the model; it would be better to get an exception that `initSystem()` has not been called.

**Comment by tkuchida** [comment]
@aseth1: Is it your intention to demand that only `Component::finalizeFromProperties()` has been called before calling `Component::getStateVariableNames()`? Currently, calling `finalizeFromProperties()` is insufficient: `isObjectUpToDateWithProperties()` can be `true` at the top of [Component::getStateVariableNames()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L765) yet state variable names are not returned unless `Model::initSystem()` has been called.

**Comment by aseth1** [comment]
My intention has always been to have state variables and their names be available after `initSystem()` not before. My take-away from this issue is that exceptions should be thrown whenever we try to access states or their names and there is no system. State variables are not allocated until `addToSystem()` and I think it is premature to attempt to access their names, since modeling options can change how many state variables are necessary.

**Comment by tkuchida** [comment]
> My take-away from this issue is that exceptions should be thrown whenever we try to access states or their names and there is no system.

There's a contradictory opinion above, but this design seems reasonable. Thanks for the ruling; I'll add the checks.
