### ISSUE TITLE
Issues related to subcomponents management and traversal

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#748]
PR #740 addressed the issue of marking subcomponents as properties and enabling immediate traversal of those subcomponents. But several issues remain:

1. Subcomponents that are data members are being lost because the list of subcomponents is being redefined in finalizeFromProperties. 

2. Dynamically allocated subcomponents are being leaked. 

3. The traversal tree is being rebuilt on every call to getComponentList and it is faking being a const method.

The solution to these are coupled and I propose tackling them in the following way:

1. Create an internal (my) subcomponents iterator that traverses three internal component lists: members, properties, and adoptees (of dynamically allocated components during processing of properties and/or wiring up (connecting) the Component and does not modify its properties).  The iterator is valid over the duration that the Component is not modified. We can then remove the list of subcomponents since figuring out when to generate the complete list (e.g. mark) and maintain its validity is confusing/error prone. Access to the iterator is protected. The adoptees are owned and destroyed. The markAsSubcomponent() method would be eliminated.

2. A public ComponentList iterator to traverse all subcomponents including those of the belonging to subcomponents will use the the internal iterators and call each recursively to traverse the complete tree live. No tree or data structure is created or cached. The Component::_nextComponent pointer can then be removed and getting the iterator is const.

**Comment by klshrinidhi** [comment]
Iterator class to traverse a list of containers as if they were concatenated.

https://github.com/opensim-org/opensim-core/blob/container_chain_iterator/OpenSim/Common/ContainerChainIterator.cpp

**Comment by sherm1** [comment]
> Iterator class to traverse a list of containers as if they were concatenated.

Sweet! One question: could the initializer list take references rather than pointers?
