### ISSUE TITLE
[superbuild] need git on path; dll-copying function generates error

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#749]
See @aseth1

**Comment by klshrinidhi** [comment]
*I think I had commented on this before but the comment seems to have disappeared.*

On a fresh installation of Windows 10, I followed the following steps. It worked for me.
* Get **Visual Studio Community** from [here](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx).
 * Choose *Custom' installation*.
 * Choose *Programming Languages* -> *Visual C++*.
* Get **git** from [here](https://git-scm.com/downloads).
 * Choose *Use Git from the Windows Command Prompt*.
* Get **CMake** from [here](https://cmake.org/download/).
 * Choose *Add CMake to the system PATH for all users*.
* In **PowerShell** --
 * `git clone https://github.com/opensim-org/opensim-core.git`
 * `mkdir opensim_dependencies_build`
 * `cd .\opensim_dependencies_build`
 * `cmake ..\opensim-core\dependencies -DCMAKE_INSTALL_PREFIX="..\opensim_dependencies_install"`
 * `cmake --build . --config RelWithDebInfo -- /maxcpucount:8`
 * `cd ..`
 * `mkdir opensim_build`
 * `cd .\opensim_build`
 * `cmake ..\opensim-core -DCMAKE_INSTALL_PREFIX="..\opensim_install" -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install"`
 * `cmake --build . --config RelWithDebInfo -- /maxcpucount:8`
 * `ctest -C RelWithDebInfo --parallel 8`
 ```
The following tests FAILED:
         53 - testStaticOptimization (Failed)
         60 - testCMCGait10dof18musc (Failed)
```

I don't see any dependency problem here.
Only thing I notice here is that the build from source instructions have to be updated to say that **git** has to be on the PATH for superbuild to work. If not using superbuild, this can be ignored.

**Comment by chrisdembia** [comment]
Yeah I agree. It might be helpful for the instructions to also communicate that users might not need to add git *manually* to the path, if their git installation procedure did it for them.

**Comment by chrisdembia** [comment]
I wonder if something like `FindGit.cmake` would alleviate the need for git to be on the path. Does ExternalProject_Add use `git` explicitly, or something like `GIT_COMMAND`?

Also, @elen4 mentioned that `cmake` should appear as `${CMAKE_COMMAND}` in the dependencies CMakeLists.txt.

**Comment by elen4** [comment]
`FindGit.cmake` is already used in ExternalProject (see https://cmake.org/gitweb?p=cmake.git;a=blob;f=Modules/ExternalProject.cmake;h=249658d62044e7b91ce4825089835f21680a793b;hb=HEAD#l1755  for the current version - might be different in older releases)
@lucaTagliapietra tried out the superbuild with CMake 3.5.0-rc1 and Visual Studio 2015 Community and had no git-related issues, even if git was not in the system path

**Comment by chrisdembia** [comment]
Hmm...that's good to know. Maybe it has been fixed in more recent versions of CMake? @klshrinidhi that might mean we can close this PR. Thank you for reporting, @elen4. Let us know if you have any other feedback about the build process.

**Comment by lucaTagliapietra** [comment]
Wouldn't it be better to turn off the compilation of simbody tests to speed up opensim-core-dependencies' compilation? It took quite a lot of time.
I've just finished building and installing everything and I have no other feedback so far :wink:

**Comment by klshrinidhi** [comment]
#768 addresses @lucaTagliapietra's comment.

This issue can be closed if there are no more comments.
