### ISSUE TITLE
Inconsistent naming between `Component::getInput()` and `Component::updConnector()`

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#762]
If I have a component that has an input and a connector, I might use the following code to connect up both of these (from hopper device example):

```cpp
controller->getInput("activation").connect(controller->getOutput("constant"));
controller->updConnector<OpenSim::Actuator>("device").connect(*pathActuator);
```

These two calls are inconsistent; I believe `getInput()` here should have to be `updInput()`. Is `const` being violated?

Also, why can `getInput()` be untemplatized while `updConnector()` is templatized? It appears that both should be untemplatized or that both should be templatized.

**Comment by chrisdembia** [comment]
Relatedly, this would allow us to remove `const` from `Input::connect` and remove `mutable` from `connectee`.

**Comment by jenhicks** [comment]
Captured in dev prop regarding input/output/connector naming.

**Comment by chrisdembia** [comment]
Oh this had already been addressed in the prep for one of the workshops earlier this year.
