### ISSUE TITLE
Making BTK optional when building OpenSim 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#766]
As of now getting BTK and building it is streamlined, nevertheless it adds a dependency that some users may not need or want (e.g. to follow the API examples, some tutorials or build your own controller or optimization). With the potential of supporting other formats in the future (e.g. Microsoft Kinect) it would be good to not require building all interfaces that are mutually exclusive.

**Comment by klshrinidhi** [comment]
I will try to get this done soon.

**Comment by chrisdembia** [comment]
What should happen when trying to load a C3D file when BTK is not integrated? Should the C3D adapter still be compiled and registered in the file registry, or no? Would it be possible to generate a useful error message that basically says "Your OpenSim needs to have been compiled with BTK to read C3D files"?

**Comment by klshrinidhi** [comment]
@chrisdembia 
Right now BTK is *required*. So OpenSim will not even finish *configuring* without BTK.

I think it is good to keep BTK optional. Will start a PR about it soon.

**Comment by chrisdembia** [comment]
I know; I'm talking about what should happen when it's optional and not included (I'm talking about a runtime error).

**Comment by klshrinidhi** [comment]
Got it.
In that case, since there will be no registered adapter for "c3d" extension, 
* an exception will be thrown when using the generic `FileAdapter` class, and
* compiler will error when attempting to use nonexistent C3DFileAdapter class.

**Comment by aymanhab** [comment]
@chrisdembia Assuming there's a runtime registry of readers that handle specific file extensions then you should get a message like ".c3d" is an unsupported extension, and probably a link or page that describes what formats are supported and how, which would help users add support for new formats as needed.

**Comment by chrisdembia** [comment]
An alternative is to still provide the C3DFileAdapter class even if OpenSim was not compiled with BTK, because all that users need to do is drop in a BTK shared library and it'll work. Right? This would be similar to what Simbody does for CFSQP.

**Comment by klshrinidhi** [comment]
>An alternative is to still provide the C3DFileAdapter class even if OpenSim was not compiled with BTK, because all that users need to do is drop in a BTK shared library and it'll work. Right? This would be similar to what Simbody does for CFSQP.

C3DFileAdapter class needs BTK binaries to compile. It will be more work to get to dynamically check and load BTK binaries and enable C3D functionality.

**Comment by chrisdembia** [comment]
> and probably a link or page that describes what formats are supported and how

I like this idea.
