### ISSUE TITLE
Ground should only be constructible by a Model

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#776]
It doesn't make much sense to allow people to create their own Ground body; they might try to add it to a model.

**Comment by tkuchida** [comment]
May also need to disallow renaming ground body (raised in Advanced User Workshop for OpenSim 3.3).

**Comment by chrisdembia** [comment]
I like both are good ideas. The situation has definitely improved since 3.3. Ground is no longer in the ForceSet, but we could make ground an Unnamed property.

**Comment by chrisdembia** [comment]
Furthermore, the Ground property now appears at the top of XML files, above other elements like `<publications>....` I think it makes more sense to put the Ground property next to the BodySet, etc.

**Comment by jenhicks** [comment]
@chrisdembia This issue is currently slated for post-4.0. But if ground is appearing at very top of xml file, we probably should address for 4.0. Perhaps a separate issue is warranted?
