### ISSUE TITLE
Removal of Joint `reverse` property: backwards compatibility with pre-4.0 model files.

### ISSUE THREAD

**Issue by ANKELA** [opensim-org/opensim-core#781]
Hi, 

I'm using OpenSim 4.0 through the MATLAB interface. I'm trying to reverse a joint and run the InverseKinematicsTool. The joint gets reset to the default "false" when running the tool. 

I've traced the problem to initSystem(), and I think it is happening in buildSystem()- either setup() or createMultibodySystem(), not sure which. 

If this is an easy fix, I would love if someone could let me know, I've been stuck for a couple weeks now. 

Thanks
-Andy

**Comment by chrisdembia** [comment]
Here's the line where your setting is overriden: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Model.cpp#L688.

Are you sure you need to reverse the joint manually?

This doxygen page has a little bit of information about how the choice of reversal occurs: https://simtk.org/api_docs/simbody/3.5/classSimTK_1_1MultibodyGraphMaker.html

**Comment by ANKELA** [comment]
Thanks for the links!

I don't need to reverse it manually, I just need it to be reversed for the model I'm using. If the model is saved how I want it, it opens fine but then disregards the reversal.  

I'll dig through the simbody doxygen.

**Comment by chrisdembia** [comment]
The issue is one of two things: (1) you want control over whether or not a joint is reversed, or (2) you want OpenSim to properly load older model files (backwards compatibility). (2) is definitely a bug, while (1) might be a feature that is being removed in 4.0.

@aseth1, if we are getting rid of the ability for users to set whether a joint is reversed, how can we ensure that we are backwards-compatible with models that previously specified whether or not a joint is reversed? Perhaps we have to swap `parent` and `child` and the transform.

**Comment by ANKELA** [comment]
I've tried both ways, neither are working. 
Calling from MATLAB I set the joint by calling: 
model.getJointSet.get('socket').set_reverse(true);

then calling: 
model.getJointSet.get('socket').get_reverse() 
it returns 1. 

then calling: 
model.initSystem(); 
model.getJointSet.get('socket').get_reverse()
it returns 0. 

I'm not worried about backwards compatibility as long as I can control the model from my script, either way it's not working... Won't swapping parent and child mean that one of the bodies will have two parents?

**Comment by chrisdembia** [comment]
> as long as I can control the model from my script

I think we are planning to get rid of this ability in 4.0, and I'm not sure it'd be easy to hack something together to get this control. Can you explain if it is useful to you?

**Comment by ANKELA** [comment]
Yes. I have been working on a model of a lower limb amputee, where the tibia is cut in half, and connected to a prosthesis via a 6 DoF joint representing the socket. We need access to all 6 degrees of freedom, need to be able to lock certain degrees of freedom, and look at the different motions in the socket reference frame. One example would be allowing the socket joint to rotate about z and translate in y (the predominant motions within the socket). If the joint is not reversed, it will rotate, and then translate in the limb reference frame, and not the socket reference frame. We need all motion to be relative to the socket reference frame, and have the ability to lock out different degrees of freedom within the socket frame.   

I made a workaround where I created a separate low mass body that connected to the limb with a joint for rotation in front of the existing prosthesis body that connected with a joint for translation, both joints with the same center. This puts the translation into the correct frame, but the rotations are still in the limb reference frame. It works for one rotation and one translation, but for more rotational DoF it doesn't give the correct results.

**Comment by aseth1** [comment]
The Model builds the underlying multibody tree and the decision to reverse or not reverse the tree is up to the tree builder. The flag to reverse the joint will be removed before 4.0 is released. There should be no reason to manually reverse a joint - that is only for the internal representation of the joint in the multibody tree. If you need the motion of the tibia in the socket, define the joint to be socket to tibia and not tibia to socket.

**Comment by chrisdembia** [comment]
You can also use a new 4.0 feature--Frames--to make it easy to arrange the joint whatever way is convenient for you. Look at the PhysicalOffsetFrame class. Joints now connect between PhysicalFrames, not Bodies, and you can attach any number of PhysicalFrames to your bodies.

**Comment by ANKELA** [comment]
Sounds like I have a couple options. I'll first try redefining the joint, and then using the Frames feature if that doesn't work. I'll post back tomorrow or the day after to let you know how it's going. 

Thanks for your help!

**Comment by aseth1** [comment]
No problem. We haven't documented the change so far and still are testing its abilities.
Ideally the new scheme will allow you to define the Frames and the joints according to the parent->child relationship that makes sense to you. For example the motion of a frame rigidly attached to the socket in relation to the prosthesis. The Joint defines its internal coordinates according to the user specification, but the Model builds the multibody tree so it can decide to reverse the joint or not and it depends on what else is connected and to what. For example, if the foot is joined to the floor the tree may be built from the ground up the leg (instead of down from the pelvis). In either case, the coordinates should remain identical to how they were defined regardless if the joint is reversed or not.

There is a test case for this in testJoints where the two models are compared: in one condition the foot is joined to the floor using a WeldJoint and the other the foot is constrained to the floor with a WeldConstraint and the pelvis is on FreeJoint w.r.t ground. When simulated the produce identical kinematics at the knee where the knee is reversed when the tree is built from the ground up.

Perhaps you could contribute your model as another test?

**Comment by ANKELA** [comment]
I'd be happy to contribute it. We'll be putting all our work on our SimTK page also, we're finally getting around to submitting a paper on this model.

**Comment by chrisdembia** [comment]
Cool!

**Comment by ANKELA** [comment]
Hey guys, problem solved! All it took was switching the joint parent and child names. Everything works great! I wrote a quick script to apply it to all previous models I'm comparing, but still use the old models with a reversed joint for visualization of the results in the GUI since I didn't build the 4.0 GUI. 

Thanks so much for your help, I wouldn't have been able to figure this out on my own. I must say, the new architecture is confusing at first, but I can see how incredibly powerful it is now that I have wrapped my head around it. It should make other aspects of this project like our device design much easier too! 

One other comment: I modified the InverseKinematicsTool.cpp file to output a file for the marker error. I've seen that other users have wanted the same functionality, which prompted me to just modify and build the source code myself. I just used the same methods that you guys wrote for writing a marker location file, so I didn't have to create any new classes. I think it would be a great thing to include in future versions of OpenSim, it's very useful for model sensitivity studies.  If you want my code to save a few minutes of coding, I'd be happy to share it. 

Thanks again!
-Andy

**Comment by chrisdembia** [comment]
> I must say, the new architecture is confusing at first, but I can see how incredibly powerful it is now that I have wrapped my head around it.

It'd be great to have your feedback on the documentation of the new features, once it's ready. Or, feel free to open a PR to improve the doxygen documentation (if your change will be big, it's a good idea to create an issue describing what you intend to do first).

> One other comment: I modified the InverseKinematicsTool.cpp file to output a file for the marker error.

Awesome. Would you like to open a PR to contribute this back to the source code?

**Comment by chrisdembia** [comment]
I think we should leave this PR open so that we can fix any potential backwards-compatibility issues (if they exist).

**Comment by ANKELA** [comment]
> It'd be great to have your feedback on the documentation of the new features, once it's ready.
I'd be happy to, send me a message anytime. 

> Would you like to open a PR to contribute this back to the source code?
Not a problem. It's a little specific to my project as is, but I will make it more generic so that it's a better fit for general use. 

I was thinking about a solution for backwards compatibility. When initSystem() is called on an older model, there could be some code that automatically switched the parent and child names for a joint if the old model contained a true reverse flag for that joint. I'm not sure if this fits with the new architecture since you're doing away with the reverse flag, but it seems like you'd at least need to maintain the ability to read the old properties.

**Comment by chrisdembia** [comment]
I think your solution makes sense. Though this wouldn't occur during `initSystem()`. See the [DEVELOPING.md](https://github.com/opensim-org/opensim-core/blob/master/DEVELOPING.md#backward-compatibility-of-file-formats) for a description of the mechanism used for backwards compatibility. Your solution would still work I think, but it'd just be done at the XML level in `Joint::updateFromXMLNode()`.

**Comment by ANKELA** [comment]
Cool, XML level makes a lot of sense. I'll poke through the code and see if I can make something work. If I can, I'll open a separate PR for that too!

**Comment by chrisdembia** [comment]
Awesome; thank you!

**Comment by chrisdembia** [comment]
Related to #611.
