### ISSUE TITLE
When defining a custom copy constructor for Component, make sure to copy any member-subcomponents in the initializer list

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#782]
We now have the ability to create subcomponents as member variables using an in-class member initializer. If a Component has its own custom copy constructor, and the initializer list for the copy constructor does _NOT_ mention the subcomponent member variable, it will be created fresh, instead of being copied. Of course, if someone is writing a custom copy constructor, they may not _want_ the subcomponent member variable to be copied, but they probably do. So we need to document that you should copy subcomponent member variables in the initializer list of a custom copy constructor.

``` cpp
class MyComp : public Component {
private:
    // Subcomponent member variable
    MySubComponent _sub { constructSubcomponent(...); }
public:
    MyComp(const MyComp& source) : _sub(source._sub) {}
};
```

This will also apply to inputs and outputs, when we eventually start using in-class member initializers for them.

**Comment by jenhicks** [comment]
@chrisdembia Same for this one ... still relevant?
