### ISSUE TITLE
SO (Shared Object) Version needed for library targets.

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#783]
Library targets currently don't have their version associated with them. Versioning is important if:
- OpenSim libraries are treated as dependencies so that correct version of the OpenSim libraries can be found and linked to by external projects or user code.
- Packaging OpenSim to be distributed through package managers. Package managers in Linux use so-name of the libraries. [reference](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html)

Simbody and BTK already have this implemented.

It is just about using the CMake variables `OPENSIM_*_VERSION` directly or indirectly (by creating another variable) in `set_target_properties` to set the property named `SOVERSION` for library targets.

**Comment by chrisdembia** [comment]
Related to #195.
