### ISSUE TITLE
example{1|2}DataTable should reside in the Examples folder

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#785]
![solutionexplorer](https://cloud.githubusercontent.com/assets/4203505/13372278/6a69c726-dcf2-11e5-9769-b4d1290209fc.png)

**Comment by chrisdembia** [comment]
Yes.

**Comment by tkuchida** [comment]
This issue was addressed by #786. Thanks for merging, @chrisdembia. :penguin:
