### ISSUE TITLE
initState fails on Xcode builds due to memory leaks

### ISSUE THREAD

**Issue by msdemers** [opensim-org/opensim-core#789]
Xcode builds from master branch fail within testInitState, specifically during testMemoryUsage(). The test initializes a state on the model 100 times, checks the change in memory, then compares this memory leak size to the size of the model. The test requires leak < 0.5% of model memory, and I'm consistently seeing 0.8 to 1.6%.

Anyone building on OS X with a different build system? Perhaps gcc or clang with Unix make?  If so, are you passing testMemoryUsage and testInitState?  Error below.

> *********************** testMemoryUsage ***********************
> MODEL: arm26.osim uses 1144KB
> 1284KB change in memory use after 100 state initializations.
> Approximate leak size: 12.8398KB or 1.12236% of model size.
> Average initialization time: 1.54117ms
> testInitState failed: 
> Exception:
>   testMemoryUsage: state initialization leak > 0.5% of model memory
>   footprint.
>   file= /Users/matt/Development/opensim-org/opensim-core/source/OpenSim/Simulation/Test/testInitState.cpp
>   line= 220
> 
> 
>

**Comment by chrisdembia** [comment]
See #473 

I've spent a lot of time trying to fix this, and I think the best solution is to not use `getRSS()`. We don't run testInitState on travis.

**Comment by msdemers** [comment]
Aha. Will close this redundant issue.
