### ISSUE TITLE
Wrapping step not executing when headers are edited

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#790]
I am having this issue on Linux currently. Haven't checked on OS X and Windows.

Editing the headers (I am currently editing `Bindings/SWIGSimTK/BigMatrix.h`) and compiling (`make`) again does not re-run the *wrapping* step and ends up just compiling the previously generated wrapper-code. Right now, I delete the wrapper code file (`Bindings/Java/OpenSimJNI/OpenSimJNI_wrap.cxx`) to make sure it is generated again.

**Comment by chrisdembia** [comment]
The best solution would be to use `swig -M` to automatically detect the files that the wrapping depends on. `swig -M` generates a Makefile that lists all the dependencies. We'd have to write a script to clean up the Makefile to just get a simple list of filenames.

**Comment by chrisdembia** [comment]
Thank you Jen.
