### ISSUE TITLE
extendFinalizeFromProperties() is not being propagated to non-serialized subcomponents

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#804]
[`Component::finalizeFromProperties()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L127) calls the following:
```cpp
markPropertiesAsSubcomponents();
extendFinalizeFromProperties();
componentsFinalizeFromProperties();
```
The `_components` Array is cleared at the top of [`Component::markPropertiesAsSubcomponents()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L832) to ensure pointers to old properties are removed; however, this also clears pointers to _non-serialized_ subcomponents that were added by [`Component::constructSubcomponent()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.h#L934) (as in [this example](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Test/testComponentInterface.cpp#L118)). Pointers to properties are then restored in `Component::markPropertiesAsSubcomponents()` by iterating through the properties; however, the pointers to _non-serialized_ subcomponents are not recovered. Thus, the subsequent call to [`Component::componentsFinalizeFromProperties()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Common/Component.cpp#L138) does not get propagated to non-serialized subcomponents (because the `_components` Array no longer contains pointers to these Components).

Proposed fix to #687 requires resolution of this issue.

**Comment by tkuchida** [comment]
To resolve #687, I'll temporarily call `extendFinalizeFromProperties()` explicitly on non-serialized subcomponents. :blue_car:

**Comment by chrisdembia** [comment]
I think this is mentioned in #748.

**Comment by tkuchida** [comment]
Thanks @chrisdembia. I didn't know this was an open issue.
