### ISSUE TITLE
Component API Refinement List

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#811]
PR #810 addresses a few major issues that makes the current API unusable (see #748) but several tasks remain for making it robust and ready for the 4.0 release (i.e after the Hackathon) . These include:
- [x] implement a Component name validater (e.g ComponentPathName) to centralize name checking and to address #596
- [x] Strict enforcement against nameless Components. Many models and components have subcomponents without names (e.g. the GeometryPath of a PathActuator, Muscle). I am currently assigning a name instead of firing the `ComponentHasNoName` exception.
- [ ] Strict enforcement of component path naming for connectors (i.e. Connectors `connectee_name`). Currently the `ComponentNotFoundOnSpecifedPath` exception is being trapped by `Connector::findAndConnect()` and `findComponent()` is invoked.
- [ ] In both cases above, we need a mechanism to allow a "lenient" mode so older models can be read in and made to comply. This could take the form of a static OpenSim::NamingStrictness enum
- [ ] Optimizing the subcomponent iterators (e.g. cache the tree or other data structure) such that the traversal tree is not rebuilt on ever `getComponent` call.
- [x] Getting access to connectors, inputs, outputs and state variables should follow the same naming convention and use the same traversal methods
- [x] providing macros to construct subcomponents and automatically provide accessors (e.g. by wrapping access by index, similar to properties) OR find a way to preserve subcomponents as data members who's `owner` is automatically reset to the new copied component and not stale or reset to `nullptr`.

**Comment by tkuchida** [comment]
- [ ] Either `findComponent()` is misbehaving or the warning message should be reworded. The hopper example reports

> Model'bouncing_leg'::findComponent()  Found '/bouncing_leg/ground_block/yTranslation' as a match for:  Component '/bouncing_leg/ground_block/yTranslation' of type Coordinate, but it is not on specified path.

which sounds like it can't find _A_ but it found _A_ instead.

**Comment by tkuchida** [comment]
Related to naming: see #390. There was also some discussion about assigning a unique unsigned int to each Component upon creation (to ensure connections are preserved even if a Component's full path changes); if so, a unique name (e.g., "component[uniqueComponentID#]") could be assigned by default.

**Comment by jenhicks** [comment]
@aseth1 Can you review the list and close issue if everything is fixed or tracked with a separate issue elsewhere?
