### ISSUE TITLE
Calling DataTable_::getColumnLabels() on a new data table gives an exception about a missing "labels" key

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#821]
What if DataTable_'s are default-constructed to have a "labels" metadata already? Or was I doing something wrong?

Not for the hackathon, though.

**Comment by klshrinidhi** [comment]
I don't think this is a bug. It was designed that way. `DataTable` is not assumed to contain labels at all times. One has to add labels to metatdata first in order to retrieve them.

**Comment by chrisdembia** [comment]
What do you think about having an easy way to query if the table has column labels, then? I think the easiest way to check currently is via:

```cpp
const auto& keys = _table.getDependentsMetaData().getKeys();
if (std::find(keys.begin(), keys.end(), "labels") != keys.end())
```

**Comment by klshrinidhi** [comment]
Yes. That is currently the only way to check if a key exists in metadata.

**Comment by jenhicks** [comment]
@klshrinidhi Can you check the wording of the exception? Maybe add a hasColumnLabels check.
