### ISSUE TITLE
Connectee name property for inputs

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#825]
Right now, Connectors automatically perform connection during `initSystem()` because the names of the connectees are stored in an XML property. The same should be done for inputs.

@aseth1 and I also talked about using two different verbs for `Connector::connect()` (like `set_connectee()`) and for `Component::connect()`. We discussed that the `connectee_name` property could be more completely hidden from the API.

**Comment by aseth1** [comment]
The API would be a lot cleaner and consistent if names (strings) were not used to make connections, but used instances to connect directly. The exception would be from deserialization which would then use the (path) name to locate the dependency and satisfy the connectee.

That requires that every Component that is constructed via the API has a valid name (so it can be serialized). Once there are instances of components around those instances are used to make connections for connectors and inputs.

The main barrier to achieving this are:
 1. that the vast majority of Components have properties with the dependency names exposed (a subset converted to Connector->connectee_name)

 2. the API is littered with dependency names in constructors and public accessors.
  
 3. the multitude of examples and test cases that explicitly use names to identify their dependencies

It would take a big and concerted effort to make components satisfy their connections directly and use (path) names strictly for serialization, but it would make the API and its examples less confusing. The current API is trying to do both (use instances and/or names) but for many components it seems to work one way or another depending on what was necessary to conform to test cases and examples. It is probably about time that the test cases and examples were updated to reflect the API.

We should discuss doing this after the hackathon.
