### ISSUE TITLE
Move example*FileAdapter projects to Examples folder

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#826]

**Comment by chrisdembia** [comment]
Could you explain? It looks like they are already in the examples folder.

**Comment by aseth1** [comment]
In VS the projects for the examples appear in the top level solution and not in the Examples folder. Is that what you mean Tom?

**Comment by tkuchida** [comment]
![solutionexplorer](https://cloud.githubusercontent.com/assets/4203505/13725895/8cabbfd2-e865-11e5-889f-0a3a212f076e.png)

I think the projects in the blue rectangle should appear in the "Examples" folder.

**Comment by chrisdembia** [comment]
Ah okay.

**Comment by tkuchida** [comment]
Addressed by #841 :rabbit:
