### ISSUE TITLE
Use UNNAMED properties for Appearance's SurfaceProperties and CurveProperties properties?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#833]
This might make the XML format a little more compact.

**Comment by aymanhab** [comment]
Good point @chrisdembia, Will do for now until the next rev. of Appearance post hackathon.

**Comment by chrisdembia** [comment]
Of course; not a priority.

**Comment by jenhicks** [comment]
@aymanhab Is this still planned for 4.0?

**Comment by aymanhab** [comment]
Yes, planned and should have little to no effect on API. Appearance management is one of the few new pieces of functionality we agreed to implement in 4.0 so this an done along with that change.
