### ISSUE TITLE
Hard to use Inputs, Outputs and Connectors from Scripting

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#837]
As of now the only way to cycle thru outputs is an iterator that returns 
SWIGTYPE_p_std__mapT_std__string_SimTK__ClonePtrT_OpenSim__AbstractOutput_t_t__const_iterator getOutputsBegin()

Also AbstractOutput is available through scripting but concrete subclasses are not.

**Comment by chrisdembia** [comment]
@aymanhab I'd like to work on this a little with you. Keep me up to date if you do anything with regard to this.

**Comment by aymanhab** [comment]
@chrisdembia Wrapping concrete subtypes is easy, wrapping the iterator type is way too complicated and not worth it in my opinion. If we can iterate through names and then use the name to recover Output we'll be home free. I'll create a branch to work on it.

**Comment by chrisdembia** [comment]
Okay. Just to be clear, I think you're adding a method `std::vector<std::string> Component::getOutputNames() const`, right?

**Comment by chrisdembia** [comment]
I'll let you work on that then, sounds good to me.

I'm still working on a bunch of other stuff for the wrapping; it'd be good to chat about it if you're in tomorrow.

**Comment by aymanhab** [comment]
@chrisdembia Yes, I'll be in tomorrow and we can discuss. If you have other ideas for exposing outputs please let me know. Don't know about inputs, may not need them for now.

**Comment by chrisdembia** [comment]
I do have another idea (well, it's just wrapping the iterator), but it's probably more amenable to Java and Python; not MATLAB.

**Comment by aymanhab** [comment]
Beefing up and changing the name of the issue to address the more general access to Components, Inputs, Outputs in scripting which is now possible only through template methods.
