### ISSUE TITLE
All throw sites should probably use the macros in Exception.h

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#842]
It will be good to go over all the throw sites (by text search) and change them to use the macros `OPENSIM_THROW_<>` in `Exception.h`. This will:
- Have an immediate effect of adding _file-name_, _function-name_, _line-number_ and in many cases, _object-name_ and _class-name_.
- Allow us to control the format of all exception messages from `Exception.h`, which was the original idea behind these macros and new constructors.

**Comment by chrisdembia** [comment]
:+1:
