### ISSUE TITLE
Create a Input list property in Component, just like for Connectors

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#848]
Right now, Inputs don't get serialized because they are not stored as properties in Component; they are stored in a std::map. But, in order for input-output connections to persist across saving/loading XML files, Inputs should be properties.

**Comment by aseth1** [comment]
We can treat them the same as Connectors and make the list property private too. Let's do that after the hackathon.

**Comment by chrisdembia** [comment]
:+1:

**Comment by aseth1** [comment]
closed by #1340
