### ISSUE TITLE
Todo list to help developers learn/adopt the new component interface

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#85]
Components look like a very promising approach to the development of modeling and simulation abstractions and flexible end user applications Some hurdles need to be resolved first:
1. Lack of clear definition and limited examples of inputs/connectors makes deciding between inputs & connectors,  the distinction between Components and ModelComponents is more clear though not complete.
2. Lack of base/starting Component or ModelComponent (provide PlaceHolderModelComponent and PlaceHolderComponent  with minimal clutter)

Separate issues for implementation specific questions/hurdles will be submitted.

**Comment by jenhicks** [comment]
See #200 and #85

**Comment by chrisdembia** [comment]
We should also document our conventions for memory management.
