### ISSUE TITLE
Give an error when trying to create a property, inputs, outputs, connectors with the same name as one in a super class

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#859]
Right now, a subclass can have a property with the same name as a superclass (if the superclass's property is protected). We could maybe give a warning when creating two properties with the same name in the same class.

**Comment by chrisdembia** [comment]
This should also be done for outputs, inputs, connectors.

**Comment by chrisdembia** [comment]
This shall be fixed by #1340, when it gets merged.

**Comment by aseth1** [comment]
closed by #1340
