### ISSUE TITLE
Cleanup warnings

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#864]
Way too many warnings are produced building master because of exceptions that are unused. While ok to leave something in the code till after the hackathon, we should clean warnings as it's almost impossible to see the real/new warnings when making changes.

**Comment by aymanhab** [comment]
I'm making a few minor changes to take care of this.

**Comment by klshrinidhi** [comment]
I have a [branch](https://github.com/opensim-org/opensim-core/tree/unreferenced_local_variable_warning_in_componentoutput_h) for this.

**Comment by aymanhab** [comment]
Great, please make a PR since the clutter is making it hard to proceed. Thanks.

**Comment by chrisdembia** [comment]
:+1:

**Comment by aymanhab** [comment]
Any update @klshrinidhi ?

**Comment by klshrinidhi** [comment]
The build for my branch is in the queue. I am not sure if I will start a PR in next few hours.

**Comment by aymanhab** [comment]
Ok, thanks.

**Comment by jenhicks** [comment]
@aymanhab @klshrinidhi Is this issue resolved?

**Comment by aymanhab** [comment]
Most warnings now are not in our code but in BTK and in SWIG generated code, some warnings are turned off on build machine by command line options but I think we can close this very general one.

**Comment by jenhicks** [comment]
Thanks @aymanhab for the update
