### ISSUE TITLE
API Programs should not rely on Path names to do connections

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#872]
It was evident in hackathon that using names/fullPathName(s) to establish connections is error prone (typos, tree/scope, case-sensitivity). This is particularly avoidable in the case when the user/devloper already has a reference to the object(s) that they're connecting to. We should look for alternatives.

**Comment by aseth1** [comment]
I agree. If you have a reference you should always be able to satisfy a connection with it and not specify its name. There are many constructors and accessors that  require names and these would have to change.
