### ISSUE TITLE
Hackathon Feedback => Developer Week Example and Lecture Materials TODOs

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#876]
Initial comments by @jenhicks but please feel free to add!

**Example Issues**
- [x] Get example working consistently in release and debug on all supported platforms: "it was a bummer that the example didn't work correctly for a lot of us" (PR #894) 

- [x] Would be helpful to have an overview of the model and functions used in the example. It was hard to get oriented to the various functions. It could even be something that participants draw themselves with some guidance. If we had to draw a picture of the connectors, inputs/outputs, and frames work before trying to write code (or reviewed one on slides, or a handout), it would really help reinforce the concepts.

- [ ] It would be cool to use Luxo geometry, if we can (if not the full mechanism).   
- [x] Include instruction to run the example target after building OpenSim so we "Have participants test getting the example running  beforehand"
- [ ] The mix of pointers and references can be confusing. Depending on audience, may want a primer or cheat-sheet for those whose primarily language isn't C++
- [x]  Example requires a lot of code before compiling -- would be helpful to break it into smaller pieces. 
- [x] Split the code into separate files (device, controller, etc.) with meaningful comments at the top of each to help organize. Would also reduce the need to scroll around when showing answers to the class (which is difficult to follow). (Tom)
- [x] Include more information in the "TODO" comments (e.g., what code needs to be added, why we need to add it, what the code will do). (Tom)
- [x] Brace "TODO" code blocks in the answer sheet; collapse blocks beforehand and expand to reveal answers to the class. This would avoid copy-and-paste errors and allow you to concentrate on explaining things. (Tom)

**Notes on the lecture** (many of them are minor style comments):

- [x]  Conceptual overview slide can be simplified: "does it need to be 3d? Hard to read some parts of the figure"
- [x]  keep in the challenges of current OpenSim -- people can relate to them
- [ ]  Reusability concept: can you give a better example of meaning in OpenSim (or at least for coding)
- [ ] Overview component diagram: maybe use colors or some other mechanism to give the notion that inputs/outputs have different types?
- [x] Connectors (detail slide that followed): rotate so it's the same orientation as the intro figure (to reinforce that connectors and inputs/outputs are different)
- [x] Would be helpful to give an overview of new frames at some point; lecture assumed people knew what these were
- [ ] Can we provide a guide/table to help people different stages? Maybe on cheat-sheet?
- [ ] Clarify what is meant by "Sources and reporters" -> Flip one
- [ ] It might be helpful to provide an example of how to migrate an old component to the new interface
- [ ] Lecture needs a wrap-up to summarize and reiterate main points: could do this via an intro to the example. 
- [ ] Might be helpful to use a concrete Component or ModelComponent example throughout (e.g., to describe changes from 3.x, Connectors/Inputs/Outputs, what finalizeFromProperties does). (Tom)

**Comments on the handout:**
- [ ] Connectors and Inputs/Outputs: Is the whole diagram the model? Or can we notate the model within it?
- [ ] "Writing your own component" : It's not clear visually how the right and left blocks fit together. A heading for each part might be helpful
- [ ] Overview of classes: maybe gray out the Tool and AbstractTool to deemphasize? (maybe remove altogether?)

**Comment by aseth1** [comment]
@tkuchida :+1:

**Comment by tkuchida** [comment]
In progress. Rough plan:
- [ ] Update joints, etc. in "teacher" version.
- [ ] Reorganize and improve "teacher" version.
- [ ] Replace code with TODO comments to create "student" version.

**Comment by chrisdembia** [comment]
To aid such work, you could make the `.cpp_answers` version compilable (i.e., `_answers.cpp`).

**Comment by tkuchida** [comment]
> To aid such work, you could make the `.cpp_answers` version compilable (i.e., `_answers.cpp`).

That's what I did. What's the other way?

**Comment by chrisdembia** [comment]
Hmm...filling out the student version from the answers. I also meant (but did not say) that the teacher version could remain as `_answers.cpp` (even during the developer's workshop). One reason for this is that the file then gets proper syntax highlighting.

**Comment by aseth1** [comment]
@aymanhab @jimmyDunne @klshrinidhi take a look at comment where you can add/change

**Comment by jenhicks** [comment]
Closing issue, since Tom's list is complete and dev week example was delivered. I think remaining issues are tracked elsewhere.
