### ISSUE TITLE
Need diagnostic tools regarding connections, inputs

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#877]
Typically users create components and forget to add them to other components or forget to wire them, would be good to show the list of "connected" components and satisfied/unsatisfied inputs. Eventually this will be done in the GUI but the functionality in the API would be extremely helpful as well.

**Comment by aseth1** [comment]
We can inspect each Component's property list of Connectors (e.g. `get_connectors()`) and cycle through them and ask if it `isConnected()`. This could be a built in filter for ComponentList (`isConnected` is true for all or false for any of its Connectors). Would this be sufficient?

**Comment by chrisdembia** [comment]
I liked the idea of a built-in ComponentListFilter!

**Comment by aymanhab** [comment]
I like the idea as well, but in terms of use-case, it appears that you'd need a list of Components that do "not" meet the filter so you can give feedback to user rather than cycle only through components that are fully connected. What do you guys think?

**Comment by chrisdembia** [comment]
I agree with @aymanhab, the filter should be `ComponentListFilterUnconnected` or something

**Comment by chrisdembia** [comment]
Or `ComponentListFilterConnectionStatus` and could take a boolean to decide whether it filters connected or unconnected components.
