### ISSUE TITLE
ASSERT_EQUAL does not evaluate Vec3

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#880]
If you pass ASSERT_EQUAL two difference Vec3's, it incorrectly evaluates them as equal. [This section of code](https://github.com/opensim-org/opensim-core/blob/b47cfb4cd5f3a2bc4632578c01f2f03adcd5763d/OpenSim/Auxiliary/auxiliaryTestFunctions.h#L36-L39) needs to be updated to use either SimTK_TEST_EQ or SimTK_TEST_EQ_TOL. 

I tried to update but couldn't get it working

**Comment by tkuchida** [comment]
Could we leave `ASSERT_EQUAL()` as it is and instead define the comparison operators for Vec3 to compare 2-norms?

**Comment by chrisdembia** [comment]
We could also specialize the ASSERT_EQUAL for Vec3 etc to use 2-norm.
