### ISSUE TITLE
getOutput and getInput should not search using findComponent

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#881]
Right now, getOutput and getInput do a search for all components of type Component to find the desired output. These methods should not do searching, and the searching should be moved to `findOutput` and `findInput`.

Also, the searching is done with `findComponent<Component>()` (since you don't know the type of the component that contains the output), and this can cause finding the wrong component/output.

**Comment by chrisdembia** [comment]
I ran into this with the muscle metabolics component.

**Comment by aseth1** [comment]
I agree Component::`getXXX("name")` should not do a find. Instead we should find the Component and then get what we want from it. It is then unnecessary to have `findConnector`, `findInput` and `findOutput`

**Comment by chrisdembia** [comment]
I believe @carmichaelong fixed this in https://github.com/opensim-org/opensim-core/pull/1181.

**Comment by aseth1** [comment]
You are correct. This issue closed by #1181.
