### ISSUE TITLE
Profile time for Building and Testing

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#886]
It's taking much longer now to build and run tests on OpenSim. It took half a day on a 2 yr old relatively high-end laptop to build the OpenSim stack twice (one Debug, one release) this seems excessive. Would be great to keep track of how we're doing there, particularly for users who don't have an 8 core state-of-the-art machines. @chrisdembia mentioned instrumentation we can use to track this.

**Comment by chrisdembia** [comment]
CDash gives graphs of historical build time for each test. Also, there's total time history for travis: http://scribu.net/blog/travis-ci-build-stats.html
