### ISSUE TITLE
TwoFrameLinker::scale overrides sometimes and doesn't override other times

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#896]
- `TwoFrameLinker<Force, PhysicalFrame>::scale` does not override.
- `TwoFrameLinker<Constraint, PhysicalFrame>::scale` overrides because its base class method `Constraint::scale` is virtual.

This makes it impossible to solve the compiler warning about `override`. Marking the function `override` gives an error for the first case because base class has not virtual function named `scale`. Not marking the function `override` gives a warning in the second case because base class has a virtual function named `scale`.

I think it will be good to discuss and make this consistent for better understanding.

**Comment by chrisdembia** [comment]
Maybe one of these should be `extendScale()`?

**Comment by aseth1** [comment]
I am happy for the virtual method to be `extendScale()`. There are other instances where `scale()` is overridden and we may consider changing those as well.

**Comment by klshrinidhi** [comment]
This is reported as a [bug in Clang](https://llvm.org/bugs/show_bug.cgi?id=22582). I am not sure if Clang developers acknowledge it as such.

**Comment by aseth1** [comment]
Fixed by #1994
