### ISSUE TITLE
"dereferenced null pointer" related warnings

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#897]
There are few places where it is assumed (and relied on) that a reference to a `nullptr` can be passed around. My understanding is that according to C++ standard, dereferencing a null pointer is _undefined-behavior_. Following are the cases I am noticing. There may be more.
- [Vendors/lepton/src/ExpressionTreeNode.cpp](https://github.com/opensim-org/opensim-core/blob/master/Vendors/lepton/src/ExpressionTreeNode.cpp#L62) --
  `getOperation()` returns a reference which can be a reference to a `nullptr` and this line checks if it so. Compiler says it may (in some optimization levels) assume that the condition always evaluates to `false`, which would be bad.
- [Vendors/lepton/src/ParsedExpression.cpp](https://github.com/opensim-org/opensim-core/blob/master/Vendors/lepton/src/ParsedExpression.cpp#L49) -- Same as above.
- [OpenSim/Simulation/Model/GeometryPath.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/GeometryPath.cpp#L77) -- `aModel` is a reference to a `Model` and from this line, it looks like `aModel` can be a reference to a `nullptr`.
- [OpenSim/Simulation/Model/AbstractTool.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/AbstractTool.cpp#L466) -- `get()` returns a reference. This line checks if it is returning a reference to a `nullptr`.
- [OpenSim/Simulation/Model/AbstractTool.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/AbstractTool.cpp#L495) -- `get()` returns a reference. This line checks if it is returning a reference to a `nullptr`.
- [OpenSim/Simulation/Model/ForceSet.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ForceSet.cpp#L193) -- `updModel()` returns a reference. This line checks if it is a reference to a `nullptr`.
- [OpenSim/Simulation/Model/ForceSet.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ForceSet.cpp#L217) -- `getModel()` returns a reference. This line checks if it is a reference to a `nullptr`.
- [OpenSim/Simulation/Model/ExternalLoads.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ExternalLoads.cpp#L236) -- Same as above.
- [OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp#L691) -- `aBody` is a reference to a `const PhysicalFrame` and this line checks if it is referring to a `nullptr`.

If a function returns a reference, it should probably never be `NULL`. If it is desired to return `NULL`, use pointers instead.

**Comment by chrisdembia** [comment]
I agree. `dynamic_cast` will give NULL if the type is a pointer, and an exception if the type is a reference (`dynamic_cast<T*>(x)` vs `dynamic_cast<T&>(x)`); perhaps we should mirror this convention. We could also have methods like `hasModel()` to replace the check for NULL.

**Comment by aseth1** [comment]
The check in `GeometryPath` should be removed. This is a remnant from before Component when GeometryPath had `setModel(Model* model)` that took a pointer. It makes no sense now.

**Comment by chrisdembia** [comment]
Perhaps it makes sense to change a bunch of those to `isConnected()` (I don't think that exists yet) since that more clearly communicates what's the check is doing?
