### ISSUE TITLE
Replace all calls to constructProperties with constructInfrastructure

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#90]
Also, constructProperties could be made a private method of Component, so subclasses can't call it directly. Could Component also call constructInfrastructure, so that subclasses don't need to do this?

**Comment by jenhicks** [comment]
Non static initiliazers for inputs and outputs might resolve this issue.

**Comment by jenhicks** [comment]
Related to #200

**Comment by chrisdembia** [comment]
I'm closing this issue since we don't want to do this anymore; we plan to remove `constructInfrastructure()`.
