### ISSUE TITLE
Enable additional builds with Appveyor

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#902]
We now have 4 concurrent appveyor jobs. We can use this to run a separate BTK build on Appveyor, or a separate Debug build, or a 32bit build. @klshrinidhi do you want to choose and add some more Appveyor jobs?

**Comment by tkuchida** [comment]
Added a 32-bit build in #921. Should we add a Debug bulid?

**Comment by chrisdembia** [comment]
No, I don't think so; at least not now. We have a Debug build on Travis.
