### ISSUE TITLE
SWIG wrapping long-term plan

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#904]
This is more of a proposal for long-term regarding SWIG wrapping.
- I think it will be good in the long run to have **one interface file per class**.
  - :+1: The whole process of wrapping will be lot more comprehensible.
  - :+1:  Adding new classes will be relatively easier.
  - :+1: Tracking problems/bugs will be relatively easier as it will be relatively easier to understand effects of editing interface files.
  - :+1: Build will be faster as there will be as many CXX files as there are interface files.
  - :+1: Dependency management in CMake can be much more fine grained just like we do it with CXX code.
  - :+1: We can write unit tests to test each wrapped class for Python/Java.
  - :-1: There is initial investment of time/effort in creating individual interface files and giving CMake an appropriate dependency graph.
- I think we need lot more unit tests to make sure changes to interface files don't break anything.

Let me know your thoughts.

**Comment by aymanhab** [comment]
@klshrinidhi Of the 300+ classes we wrap/expose today, likely the majority are handled seamlessly by including the header files in the common interface file(s). That's reasonably streamlined. 

Breaking this into a handful of interface files (one per library) seams like a perfect granularity, while one per class would be excessive unless the whole process is fully automated. If we follow the full automation route, users will have to have other custom tools to indicate what to wrap and troubleshoot so complexity would increase. I'm not sure who are we targeting here, users have looked and followed our swig interface files in the past (the few who wanted to). Totally agree on need for unit testing but not sure about the rest.

**Comment by klshrinidhi** [comment]
Currently, I am finding the interface files pretty confusing to get SWIG to generate multiple CXX files instead of one. There seems to lot of trial and error involved. This issue is coming from that perspective.

For classes that can be exposed by just including the header file, we can make one interface file for a group of maybe a maximum of 10 classes. Grouping classes into one interface file can lead to problems we are having right now about build taking too long. For these kinds of classes, we could explore possibility of having CMake generate the interface file and split them up into appropriate number of chunks.

For classes that need more than just including header file, we should probably create one interface file per class. It has more benefits than downsides I think.
