### ISSUE TITLE
Python bindings simbody library might always be out-of-date

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#907]
It seems that on Appveyor, the Python bindings' simbody library (_simbody) is re-built when trying to install OpenSim. So CMake may think this target is always out of date.

**Comment by aymanhab** [comment]
Just reproduced that behavior on master while trying to install after a full rebuild.

**Comment by chrisdembia** [comment]
Thanks; it is just the _simbody library for you?

**Comment by aymanhab** [comment]
_simbody gets rebuilt, everything else gets relinked.

**Comment by chrisdembia** [comment]
This is still happening; see https://ci.appveyor.com/project/opensim-org/opensim-core/build/7108/job/jqxmka0pxj96jvb2

**Comment by chrisdembia** [comment]
I found part of the issue. See https://github.com/opensim-org/opensim-core/tree/swig_simbody_deps for an attempted fix.
