### ISSUE TITLE
Which version of OS X / Xcode should we support?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#91]
@apoorvar  and I spent a while getting OpenSim to build on her computer using Xcode. Our CMake files imply that we support OS X 10.4, but that is probably not going to work anymore, considering we rely on C++11. Apoorva is using 10.8. I think she plans on submitting a PR containing the changes to CMake we needed to make to get OpenSim to build in Xcode.

@apoorvar's research:

"According to this page, it looks like you need at least XCode 4.2 and Lion (OS X 10.7) to use C++ 11 features, so I'm not sure Simbody/OpenSim will work on Snow Leopard (10.6) anymore. On top of that, it looks like XCode 4.2 is the one version that's still compatible with Snow Leapord, can maybe do a partial-version of C++11, and *not* free to download for Snow Leopard developers.

http://stackoverflow.com/questions/7482026/can-i-use-the-latest-features-of-c11-in-xcode-4-or-osx-lion

It may be time to just say we support OS X 10.7+, but unfortunately, I don't know anyone who has Lion as their OS to test out compatibility on there."

If we want to be kind to other users, we could try to support OS X 10.7. If we want to be kind to us, we would support only 10.8+ (since I don't think we have a 10.7 machine).

**Comment by jenhicks** [comment]
Our readme says OSX 10.11 (El Capitan) and Xcode >= 7.3. @chrisdembia can you update if there is a larger set for which we've tested. If that's correct, let's close this issue.

**Comment by chrisdembia** [comment]
Thanks for bringing this up. I am unwilling to test on an older version of OSX and I think it is fine if we only support El Capitan for now.
