### ISSUE TITLE
testC3DFileAdapter taking 6min on Windows with MSVC

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#922]
Should look into reducing this time.

**Comment by tkuchida** [comment]
The [latest AppVeyor build](https://ci.appveyor.com/project/opensim-org/opensim-core/branch/master) indicates that testC3DFileAdapter is taking [50 seconds on 32-bit](https://ci.appveyor.com/project/opensim-org/opensim-core/build/4060/job/09o09cfdqir9y29d#L470) and [36 seconds on 64-bit](https://ci.appveyor.com/project/opensim-org/opensim-core/build/4060/job/8uv4kfiri50axb5n#L550). Has the issue been resolved, or was the test always faster on AppVeyor?

**Comment by aseth1** [comment]
From #987 

>Made testC3DFileAdapter faster. It was already slow and it got even slower after adding more tests in this PR. Addresses #922.
    Appveyor 32bit -- 407sec to 49sec
    Appveyor 64bit -- 363sec to 33sec
    Travis Linux Debug -- 1110sec to 181sec
    Travis Linux RelWithDebInfo -- 355sec to 57sec
    Travis OS X -- 912sec to 160sec

Issue #991 opened to address covergae of testC3DFileAdpater for different types of C3D files.
I am closing this issue.
