### ISSUE TITLE
OpenSim_DECLARE_OUTPUT cannot construct output a of 'no default constructor' type

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#928]
I am working on the issue #889 on [this branch](https://github.com/opensim-org/opensim-core/tree/tablesource_component). Using the macro as:
`OpenSim_DECLARE_OUTPUT(row, RowVectorView, getRowAtTime, SimTK::Stage::Time);`
produces following compiler error:

```
field of type 'SimTK::RowVectorView_<double>' has private default constructor
    explicit Output(const std::string& name,
             ^
...... pruned ....
```

This is because the class `Output<T>` has a data member of type `T` and `Ouput<T>` has a default constructor which attempts to call the default constructor of `T`.

**Comment by chrisdembia** [comment]
Ohh so a `static_assert(std::is_default_constructible<...>...)` could be helpful?

How come this error doesn't come up in the sandbox? It sounds like you want the output to return a RowVectorView, but I don't get how that would work when interpolating; you'd need to return a Vector.

I also think it is preferable to return a Vector instead of a RowVector for that output. @aseth1?

**Comment by klshrinidhi** [comment]
I think it will be useful to allow 'no default constructor' types. It doesn't make much sense to not allow them because `Output` class does not do any computation.

Yes. I need to return a Vector but first I wanted to see it work without interpolation just returning the view as is. I have changes in my local copy that I have not commited/pushed yet.

**Comment by chrisdembia** [comment]
> I think it will be useful to allow 'no default constructor' types. It doesn't make much sense to not allow them because Output class does not do any computation.

Good point. Perhaps then `Output<T>` can hold onto a pointer or reference to T instead of a value?

**Comment by jenhicks** [comment]
@aseth1 Can you verify if this is resolved?

**Comment by jenhicks** [comment]
Document for now
