### ISSUE TITLE
Convert PrescribedForce to new Component API with Inputs/Outputs/Connections

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#932]
Old class has:
Properties:
- name:body, type:String: optional
- name:pointIsGlobal, type:Bool
- name:forceIsGlobal, type:Bool
- name:forceFunctions: type:FunctionSet
- name:pointFunctions: type:FunctionSet
- name:torqueFunctions: type:FunctionSet

Proposed:
- body becomes a connection
- All forceFunctions, pointFunctions and torqueFunctions are practically optional, can they be connections? Inputs? or should they stay as properties? Note that Function is not a Component altogether.

Outputs:
- "force_applied, torque_applied, point_of_application". What else?

**Comment by aymanhab** [comment]
@aseth1 I made body into a connector to PhysicalFrame, if everything else stays as property then I only need to add outputs and we're done with this one (once we agree on names), otherwise let me know.

**Comment by aseth1** [comment]
I think the flags and functions remain properties. The Outputs make sense too.

**Comment by aymanhab** [comment]
Addressed in PR #938 pending review/merge.

**Comment by aymanhab** [comment]
Merge done, closing
