### ISSUE TITLE
ModelComponent::extendAddGeometry should not be necessary

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#936]
The Geomtery handling API is becoming more complex than handing Components, in general.  We need to sort this out.

**Comment by aymanhab** [comment]
Thanks @aseth1 :+1: for simplification and leveraging latest API capabilities.

**Comment by aymanhab** [comment]
Questions that need discussion:
- How to remove extendAddGeometry?
- Can Geometry be treated like all other components in terms of book keeping?

**Comment by jenhicks** [comment]
@aymanhab Can you verify that this issue can be closed?

**Comment by aymanhab** [comment]
Fixed by earlier PRs, function doesn't exist anymore.
