### ISSUE TITLE
Make it easier to get OpenSim's version number from bindings.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#945]
Do we have this ability right now? This would be helpful for people who may have multiple versions of OpenSim installed.

**Comment by aymanhab** [comment]
opensimModelCommonJNI.GET_OSIM_VERSION_get() in Java

**Comment by aymanhab** [comment]
@chrisdembia If you can make similar call in Python we can close this issue. Thanks

**Comment by chrisdembia** [comment]
Ah the python bindings have `opensim.GetVersion()`, `opensim.GetVersionAndDate()`, etc. Pretty good. Do you have these methods in Java/MATLAB?

**Comment by chrisdembia** [comment]
Another conventional way of getting version info in Python is `opensim.__version__`. I'd like to leave this issue open until we add this.

**Comment by aymanhab** [comment]
This issue can now be closed,
