### ISSUE TITLE
Marker wrapping is incorrect leading to Marker not an Object

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#948]
Latest bindings of master result in incorrect hierarchy for Marker class since Station is neither an Object or Component

**Comment by chrisdembia** [comment]
@aseth1 has fixed this in #946

**Comment by aymanhab** [comment]
Thanks @chrisdembia I was just making sure my automation PR to build GUI works before integrating PathPoints and ran into a few issues including this one.

**Comment by aymanhab** [comment]
Fixed by PR #919
