### ISSUE TITLE
SimbodyEngine's getPosition, getVelocity etc are not accounting for frames correctly.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#949]
The SimbodyEngine has bugs! https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp#L190. This method is assuming internally that there are no intermediate frames, since it uses the Simbody MobilizedBody to do the transformation. This method should be reimplemented, and also deprecated.

**Comment by aseth1** [comment]
I would be in favor of 1)  reverting it to use only Body so it is not wrong, and 2) deprecating since it is no longer needed. Wherever we can in the API we should use Frame and Point methods.

**Comment by carmichaelong** [comment]
As per discussion with @aseth1, the plan is to do the following:
1) Keep PhysicalFrame as an argument, but throw an Exception when a PhysicalOffsetFrame is used. (Note: If we were to just change it to Body, then Ground could not be used).
2) Deprecate these functions.

**Comment by chrisdembia** [comment]
See [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/ContactGeometry.h#L131) for the format for deprecating. Note the doxygen comment.

**Comment by carmichaelong** [comment]
@aseth1 Is the intent to deprecate these specific methods (i.e. all methods within SimbodyEngine that take PhysicalFrame as an argument) or deprecate all methods within this class? (Or as a third option, deprecate the specific methods first, then in a later PR deprecate the rest.)

**Comment by aseth1** [comment]
@carmichaelong It may be easiest to just deprecate the specific methods involving `PhysicalFrame` although it would be nice to deprecate the whole `SibodyEngine` class. With the individually deprecated methods you can also provide a more informative message about which `Frame` method to call instead, which would help ease the transition.

**Comment by chrisdembia** [comment]
By the way, if you deprecate a method that OpenSim uses, then the Travis-CI tests will fail because we turn warnings into errors. So reducing the number of methods you deprecate will decrease how much extra code you have to fix.

**Comment by carmichaelong** [comment]
Thanks for the heads up @aseth1 and @chrisdembia. Sounds like the first PR should just include the specific methods involving `PhysicalFrame` (which is also more specific to this issue).

**Comment by jenhicks** [comment]
Can we close this issue now?

**Comment by aseth1** [comment]
Yes, I believe so.

**Comment by chrisdembia** [comment]
🎆
