### ISSUE TITLE
List of classes needing update from Storage to TimeSeriesTable/DataTable

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#965]
List of classes that need update from `Storage` to `DataTable`. This list is based on classes used in Examples directory.

* `Model`
 * `printControlStorage()`
* `Manager`
 * `getStateStorage()`
* `ForceReporter`
 * `getForceStorage()`
* `SymbolicExpressionReporter` (in Examples)
 * Has a `Storage` data member
* `AnalysisPlugin_Template` (in Examples)
 * Has a `Storage` data member

**Comment by klshrinidhi** [comment]
@aseth1 
Let me know what you think.

**Comment by aseth1** [comment]
Looks like the right list to target. For the top 3 leave the method that returns the storage but `deprecate` them. The `AnalysisPlugin_Template` example we should discuss. I am in favor of removing it altoghter since we no longer want people to write new `Analysis` classes since we now have outputs and reporters.

**Comment by chrisdembia** [comment]
I think we should create an example that exactly replicates (using outputs/reporters) the functionality of creating an Analysis before removing the example. It would still be good to have easy-to-use packaged "studies" that aren't customizable (i.e., "just give me all the kinematics"), and that could still be the Analysis, in which case it may make sense to modernize the AnalysisPlugin examples. If it's not the Analysis, I think maybe we should figure out what it is before removing Analysis example.

For example, what about convenience classes like `KinematicsSomething` that would gather up all coordinate values into one output for reporting?

Anyhow I think the `AnalysisPlugin_Template` does not need to be updated to use DataTable.

**Comment by chrisdembia** [comment]
I think it would be great to have a new API example that has (1) a new Component "calculator" class, that computes "force generation ability", and (2) has a sample main program that adds the new component to a model, combines it with a reporter, and writes the data out to a CSV file.

**Comment by chrisdembia** [comment]
@klshrinidhi can this be closed?
