### ISSUE TITLE
Location of Bindings install on OS X is  unexpected

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#973]
Install command from Xcode places java and jar files under /share/doc/OpenSim

**Comment by chrisdembia** [comment]
This behavior is toggled with `OPENSIM_INSTALL_UNIX_FHS`. If set to OFF, it uses our old layout (the one on windows). However, it is default ON for UNIX (OSX, Ubuntu, etc.). If we abide by the Unix Filesystem Hierarchy Standard, then we cannot create an `sdk` folder in the root of our install tree. I think a better location for the java bindings might be `share/java`, based on what other Ubuntu packages do. I'm not sure though. See comments [here](https://github.com/opensim-org/opensim-core/blob/master/CMakeLists.txt#L139).

Anyway, the GUI should rely on a variable from OpenSimConfig.cmake to get the location of the java bindings from the OpenSim install. I think @klshrinidhi already created such a variable.

**Comment by chrisdembia** [comment]
For the GUI distribution of OpenSim on OSX, I am undecided as to whether I prefer `OPENSIM_INSTALL_UNIX_FHS` ON or OFF.

**Comment by aymanhab** [comment]
Thanks Chris for the clarifications, I still think that anywhere under doc
is just unexpected.

On May 13, 2016 11:52 AM, "Christopher Dembia" <notifications@github.com>
wrote:
>
> For the GUI distribution of OpenSim on OSX, I am undecided as to whether
I prefer OPENSIM_INSTALL_UNIX_FHS ON or OFF.

**Comment by chrisdembia** [comment]
Yes, I agree; it doesn't make sense to put software in doc. I'll submit a PR soon to change these install dirs.

> I prefer OPENSIM_INSTALL_UNIX_FHS ON or OFF.

Which one? 📂

**Comment by chrisdembia** [comment]
FYI I plan to do what vtk does for its [python](https://gitlab.kitware.com/vtk/vtk/blob/master/Utilities/Python/CMakeLists.txt#L26) bindings:

```cmake
if (NOT VTK_INSTALL_PYTHON_MODULE_DIR)
  set(VTK_INSTALL_PYTHON_MODULE_DIR
      "${VTK_INSTALL_LIBRARY_DIR}/python${PYTHON_MAJOR_VERSION}.${PYTHON_MINOR_VERSION}/site-packages"
      CACHE
      PATH "Directory where python modules will be installed" FORCE)
endif()
```

They install their .jar file into `lib`, but Ubuntu puts the `vtk.jar` in `/usr/share/java`. So I'm not sure what to do for the jar file yet.
