### ISSUE TITLE
Replace reference to Sets during model building with Iterators

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#974]
Per dev team meeting, this is needed for correct wiring of nested models. @aseth1 will specify what specific functions are considered "model building".

**Comment by chrisdembia** [comment]
I found an instance of using `updContactGeometrySet()` in `ElasticFoundationForce::extendAddToModel()`. It's probably used in HuntCrossleyForce also.

**Comment by jenhicks** [comment]
Given discussion of support for handling models with hierarchical components, we need to decide if this task is in or out for 4.0. Leaning towards hold for post-4.0

**Comment by chrisdembia** [comment]
I thought that we decided we would support putting any component (including Bodies, Joints, Constraints) in any other component for 4.0, but that we would not support putting a Model in another component. 

The former still requires replacing the use of Sets internally (mostly in Model) with iterators.

We could have a more nuanced situation for 4.0, where we say something like "we support putting arbitrary components inside other components, except for ContactGeometry and Model". In this case, ElasticFoundationForce could still use Model::updContactGeometrySet().

**Comment by aymanhab** [comment]
Thanks @chrisdembia the question that was raised was whether having a Body inside a Joint (e.g. Body internal to the shoulder joint) should cause that Body to show in the Bodies list on navigator, topology-view or Tools that operate on Bodies. If this internal Body shouldn't be changed and is completely internal to the Joint then using the Sets will be ok, or switching to iterator if the iterator knows how to handle it. Still up for discussion as far as I can tell.

**Comment by chrisdembia** [comment]
Thanks for the clarification. I think I understand now.

To support "internal" subcomponents, we introduced "member subcomponents." These are subcomponents that a user cannot remove or edit, and we have two functioning member subcomponents in Thelen2003Muscle. The idea is that Thelen2003Muscle gets to choose how much to expose of the internal components. Right now, I am almost positive the iterator *does* iterate through these subcomponents. But IMO the iterator should *not* iterate through member subcomponents. I'm not really sure though!
