### ISSUE TITLE
Upcoming State Xml format produces big files; should we support zipping?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#976]
The upcoming XML file format for a states trajectory is about 25 times larger than the previous states storage file format that OpenSim used. This could mean states trajectory XML files that are 50 mb. We already feel that the states storage files are too large. Therefore, it seems that OpenSim will want to use a compressed XML version. After compressing to a zip file, the XML version was half the size of the storage file version.

I'm not sure about the best way to go about saving the file to zip, though. I looked into the [zlib library](http://www.zlib.net/manual.html), but it seems to have a complicated interface. It also deals with in-memory compression. An alternative is [libzip](http://nih.at/libzip/libzip.html), which deals with zip archive files (and depends on zlib). Bullet seems to use `minizip`. I'm going to give a shot at using libzip.

cc @sherm1

**Comment by chrisdembia** [comment]
Related: #149 

Other options:

- miniz: https://code.google.com/archive/p/miniz/
- libarchive: http://www.libarchive.org/
- de/compress std::string's with zlib: http://panthema.net/2007/0328-ZLibString.html

I found all of those from http://stackoverflow.com/questions/262899/portable-zip-library-for-c-c-not-an-application.

**Comment by sherm1** [comment]
Xml zipping should be very effective. It will be interesting to see what compression ratio you get.

**Comment by chrisdembia** [comment]
With the first state xml file I tried: 50x! I also really like this idea because it sets us on the path to easily also include the model file in the zip.

**Comment by sherm1** [comment]
Wow, that's great compression! I like this much better than a binary format since it is simultaneously human readable/editable and compact.

**Comment by chrisdembia** [comment]
I agree.

**Comment by aymanhab** [comment]
@chrisdembia that sure is exciting, thanks for taking this on. One question regarding context: Is this compression intended for disk i/o only or will the trajectory have to live in memory, as I'm a bit worried about the memory foot print. Thanks.

**Comment by chrisdembia** [comment]
This compression is intended for disk i/o only. I haven't evaluated memory foot print, and I do think it might be quite large. If it becomes an issue, we can allow StatesTrajectory to read one state from a file at a time. I'd prefer to leave that to the future though, as it sounds pretty hard.

I'll say that Tim and Jack essentially stored states trajectories of their 10-second simulations, and had no issue as far as I know. Although, I think they only stored states every 0.001 or 0.01 seconds.

**Comment by chrisdembia** [comment]
Just as we write out partial states trajectories now (to the states .sto file), we might want to do that too for the StatesTrajectory.

**Comment by chrisdembia** [comment]
From dev meeting: We must document clearly that users should avoid editing the xml file. In the .xml file (as a comment), in a README file in the zip, and in the doxygen for StatesTrajectory, we should add notes that say:

1. This file is "automatically generated"
2. You should only edit it if you know what you are doing.
3. There are much better ways to alter a states trajectory (loading a StatesTrajectory, making a copy, and editing individual state objects)
4. We cannot provide support for any issues you run into if you modify this file.

**Comment by chrisdembia** [comment]
As for getting dependencies (zlib, libzip): @klshrinidhi says that if there are binaries for them, we can just fetch the binaries automatically. Otherwise we should use superbuild. And we agreed not to use libzippp, at least not for now.
