### ISSUE TITLE
python "report_marker_locations" property not display within XML

### ISSUE THREAD

**Issue by fablebGitHub** [opensim-org/opensim-core#977]
Hi

i work with your python binding ( opensim 3.3). 
I report a issue with the property "marker error reports"
my code is the following
`    ikTool = osim.InverseKinematicsTool()    
    ikTool.setModel(myModel)
    ikTool.setMarkerDataFileName("motion.trc")
    ikTool.setOutputMotionFileName("outputIK.mot")
    rm = ikTool.getPropertyByName("report_marker_locations")
    rm.setValueIsDefault(True)
    ikTool.updPropertyByName("report_marker_locations")
    ikTool.printToXML("ik-setup-VERIF.xml")`

eventually, the xml doesn t inlcude the "report_marker_locations property"

if i remove  rm.setValueIsDefault(True).  the property is displayed 

is it an error ? or i have forgotten something ? 

regards

**Comment by fablebGitHub** [comment]
Hi 

finally, my question is rather : how can i change the value of an abstract Property in python. 
The method getValue doesn t sound exist . 

cheers

**Comment by fablebGitHub** [comment]
I have found by myself. 
i have to use the PropertyHelper. 

`    osim.PropertyHelper().setValueBool(True,pr)`

**Comment by chrisdembia** [comment]
Thanks for reporting and closing. I'm happy you found a way to do what you wanted. Unfortunately, the Tool classes use an old property system, which does not provide setter/getter methods in the API. As a result, you have to do weird things like you have found.
