### ISSUE TITLE
Update reference to file containing buildinfo 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#978]
GUI uses the file buildingo.txt to show Build Info (under Help/About details) and Matlab configuration script does something similar to check for compatibility. Both need to be updated to the new file name in PR #975 as well as documentation on confluence and the change log.

**Comment by chrisdembia** [comment]
I have already updated the Matlab configuration script in #975, though I did not test the change.

**Comment by aymanhab** [comment]
The filename is not actually used by the GUI, the call to get the name of the compiler used has been fixed in PR #1473 however it's not clear if that's enough or if 32/64 bit distinction needs to be made some other way.

**Comment by aymanhab** [comment]
I (Ayman) Will check which function used by GUI for Abot dialog and update needs, @chrisdembia fixed configure opensim to use latest functions

**Comment by aymanhab** [comment]
@aseth1 and @aymanhab will review and test

**Comment by aymanhab** [comment]
@chrisdembia The method called by the GUI  (to show in the About Dialog is opensimModelCommonJNI.GetCompilerVersion() and it returns blank as of API alpha).

**Comment by chrisdembia** [comment]
Hmm...I am able to use the function in MATLAB:

```
>> import org.opensim.modeling.*
No completions found.
>> opensimCommon.GetCompilerVersion()
ans =
Mac OS X :/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
>>
```

(note, `opensimModelCommonJNI` should now be `opensimCommon`, or maybe `opensimCommonJNI`)

 It could be a Windows-specific issue, since I can't think of what we've done since the alpha to fix this. @carmichaelong @nickbianco since you have the 4.0 MATLAB bindings installed for Windows, could you check?

**Comment by carmichaelong** [comment]
Tested this, with some caveats: 1) I tested on tgcs2017 branch. 2) Unsure what exactly I'm testing for.

I tried the following lines, none of which worked, but had different error messages:
```
>> import org.opensim.modeling.*
>> opensimCommon.GetCompilerVersion()
Undefined variable "opensimCommon" or class "opensimCommon.GetCompilerVersion".

>> opensimModelCommonJNI.getCompilerVersion()
No appropriate method, property, or field getCompilerVersion for class
org.opensim.modeling.opensimModelCommonJNI.

>> opensimCommonJNI.getCompilerVersion()
Undefined variable "opensimCommonJNI" or class "opensimCommonJNI.getCompilerVersion".
```

**Comment by chrisdembia** [comment]
Thank you; what about `opensimModelCommon.GetCompilerVersion()` (capital G)?

**Comment by chrisdembia** [comment]
The method should exist; we're looking to see if it outputs a blank string.

**Comment by nickbianco** [comment]
Also on tgcs2017 branch. The last command (with a capital G) worked for me.

```
>> import org.opensim.modeling.*
>> opensimCommon.GetCompilerVersion()
Undefined variable "opensimCommon" or class "opensimCommon.GetCompilerVersion".
 
>> opensimCommonJNI.GetCompilerVersion()
Undefined variable "opensimCommonJNI" or class
"opensimCommonJNI.GetCompilerVersion".
 
>> opensimModelCommonJNI.GetCompilerVersion()
ans =
Visual Studio 2015
```

**Comment by chrisdembia** [comment]
Cool. Thank you.

**Comment by chrisdembia** [comment]
>  @chrisdembia fixed configure opensim to use latest functions

I'm not sure what you meant but we do not use any OpenSim API functions in configureOpenSim.m (since we must assume the API is not yet configured with OpenSim); we parse the buildinfo.txt file.

**Comment by chrisdembia** [comment]
Create separate issue for updating buildinfo information on confluence.
