### ISSUE TITLE
Document the layout of the OpenSim installation on all platforms.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#979]
We have done something similar for Simbody in its [README](https://github.com/simbody/simbody#layout-of-installation):

![image](https://cloud.githubusercontent.com/assets/846001/15303918/38997eba-1b6f-11e6-92bd-98fac13a75ae.png)

Places to be updated:
- changelog
- Confluence
- README

Related: #975 #978

**Comment by aymanhab** [comment]
@chrisdembia While this works for Simbody which is a toolkit with no specific entry point and we're free to place folders as we like as long as we can find them, it is quite different for the application framework we use (Netbeans Platform) where there's a assumed directory structure (e.g. the relative placement and names of the folders bin, etc, ide, opensim, platform  in OpenSim 3.3- is not modifiable). My current game plan is to make our application layout mirror Netbeans on all platforms and then backfill the missing pieces (includes, libs, python, Geometry etc.) by placing them in sensible locations. Other option is to have a separate application installer and an API installer which is just a zip of opensim-core installation. What do you think?

**Comment by chrisdembia** [comment]
Gah this stuff is so complex; it's hard for me to get it all straight in my head. I'm fine with using the same directory structure for the GUI on Windows/OSX. For the copy of opensim-core that we use with the GUI, we can set `OPENSIM_INSTALL_UNIX_FHS` to OFF, so that opensim-core also has the same layout on Windows/OSX. So far, I am undecided as to whether or not that's a good idea; it may be fine.

I don't think we should shuffle around the opensim-core layout when it gets distributed with the GUI. Because, then the OpenSimConfig.cmake file will be incorrect. A better option is to give opensim-core a CMake option like `OPENSIM_INSTALL_LAYOUT_FOR_GUI`; then we can choose whatever layout we like, and the OpenSimConfig.cmake will be correct. The only exception I think is okay is copying OpenSim dlls. But ideally, opensim-core and the GUI would just share the same bin dir.

I have no opinion (yet) about Geometry, or the `opensim-models` stuff.

If/when we support Ubuntu, it will be Ubuntu that decides the installation layout, not Netbeans, etc. But for OSX and Windows, we get to choose (or let Netbeans choose). So our policy for Windows/OSX may be different than for Ubuntu. But we can deal with that when we get there.

As for an "API installer," I think we can just distribute API binaries through package managers; homebrew (OSX) and Chocolatey (windows). What do you think?

**Comment by chrisdembia** [comment]
@aymanhab let me know if you think we can close this, based on the [list in DEVELOPING.md](https://github.com/opensim-org/opensim-core/blob/master/DEVELOPING.md#cmake-options-for-packaging-a-binary-distribution).

**Comment by aymanhab** [comment]
The part related to API has been addressed, the GUI layout on platforms other than windows is still work in progress but doesn't belong to this repo/issue. I'm closing.

**Comment by chrisdembia** [comment]
Okay yes; we will need another list for the GUI. Having that layout will be useful for writing new confluence documentation.
