### ISSUE TITLE
Target/label C3D testing data files according to the intended condition 

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#991]
and/or add comments in the test to indicate the different conditions presented by the files: e.g. different forceplate configurations, different units, w/out EMG data, other analog data, etc.... 

This issue was raised from review of #987 where the test was sped up by eliminating the reading of one particularly large data file. If the point of the test was to verify we can handle large files, then perhaps we it could become its own case that is tested only in release. 

The following files are tested
-    filenames.push_back("jogging.c3d"); **_--> multiple force-plates with different orientations_**
-    filenames.push_back("singleLeglanding_2.c3d");
-    filenames.push_back("aStaticTrial_2.c3d");
-    filenames.push_back("aStaticTrial.c3d");
-    filenames.push_back("doubleLegLanding.c3d");
-    filenames.push_back("sideCutting.c3d");
-    filenames.push_back("singleLegLanding.c3d");
-    filenames.push_back("walking2.c3d");
-    filenames.push_back("walking5.c3d"); **_--> huge data file of minutes of treadmill walking_**

The **_bold_** text are a sample annotation of the condition that helpful to document what coverage exists.

**Comment by chrisdembia** [comment]
> If the point of the test was to verify we can handle large files, then perhaps we it could become its own case that is tested only in release.

It also seems that this test may be a good candidate for parallelizing by splitting into multiple tests. A header file could contain the actual testing function, and each file could have its own executable test.

**Comment by jenhicks** [comment]
For 4.0, we should add comments about the purpose of each file in the test, per Ajay's comments.

**Comment by jimmyDunne** [comment]
I passed these c3d files on for internal testing, they were not meant to be pushed to the main OpenSim repository. We should take them off immediately and I can gather some c3d files that I have had permission to distribute.

**Comment by jenhicks** [comment]
@klshrinidhi Can you remove these files from the repo per @jimmyDunne comment?

**Comment by klshrinidhi** [comment]
These files have been in the repository for several months now. I committed them as part of testing C3DFileAdapter. This comment could have been made in that PR.

I can remove the files when I have enough other files to test the adapter.

**Comment by jenhicks** [comment]
@klshrinidhi Is starting a PR to remove extra files. walking2 and walking5 are ok to distribute so can remain in the test.
