### ISSUE TITLE
SimbodyEngine kinematics getters

### ISSUE THREAD

**Issue by mitkof6** [opensim-org/opensim-core#992]
Shouldn't these two functions have different implementation?

[getAngularVelocity](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp#L268)

[getAngularVelocityBodyLocal](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/SimbodyEngine.cpp#L281)

The same goes for the rest functions with Local at the end of the function.

**Comment by chrisdembia** [comment]
The first one is correct. The method names and their documentation are vague, also. I think a good fix would be to add the necessary methods to `Frame`, deprecate the methods in Simbody engine, and either remove the `Local` variants or fix them.

**Comment by jenhicks** [comment]
Closing given age; feel free to re-open if high priority.
