### ISSUE TITLE
Java_TestEditProperties test case times out

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#999]
Test case fails to perform 10 edits in 30 secs (used to pass when introduced) indicates slowing down of initialization sequence and/or save restore of state(s). The case pass if I change timeout to 50 secs but 5 sec./edit is not interactive/acceptable.

**Comment by chrisdembia** [comment]
Was this discovered locally or through travis/appveyor?

**Comment by aymanhab** [comment]
Locally while trying to update to latest master to sync. up.
